### ISSUE TITLE
Editor forgets contents when switching back from preview with a newly created note.

### ISSUE THREAD

**Issue by sjmduncan** [gsantner/markor#10]
#### General information

* **Device:**   Moto G 4G
* **Android Version:**  Android 7.1 (LineageOS 14.1)
* **App version:** v0.1.1

#### Steps to reproduce

1. Create a new file, add some text, give it a name
2. Switch to preview
3. Switch back to edit

#### Expected result
The editor shows the information entered in step 1.

Instead the original file is saved but the editor shows a blank file as if you were creating a new one.

For existing notes this works as expected.

**Comment by gsantner** [comment]
can be fixed by doing a save call before switching. feel free to send a PR

**Comment by sjmduncan** [comment]
Alright, just waiting on the toolchain now.
