### ISSUE TITLE
Markup editing issues

### ISSUE THREAD

**Issue by SpotlightKid** [gsantner/markor#100]
#### General information

* **Device:** Acer B3-A30
* **Android Version:**  Android 6.0
* **App version:**  v0.1.5

#### Steps to reproduce

1. When entering an ordered list, after entering return after the second item line, no new item is generated on the next line.
2. The toolbar button to insert a link does not use the current text selection as the link text.
3. The H1 H2 and H3 buttons should enter the hash sign at the start of the line not at the current cursor position.
4. The button for the horizontal line always inserts two lines of `----`.

#### Expected result

1. If the current line is an (un-)ordered list item and return is pressed, an appropriate item marker should be inserted at the beginning of the next line (after the proper indentation).
2. When something is selected and the link button is clicked, the 'Name' field in the dialog that pops should be pre-filled with the selection text. Nice to have: If nothing is selected but the cursor is currently positioned in a link, the link markup should be parsed and the current link title filled in as well.
3. The hash signs are inserted at the start of the line or the current selection.
4. Only one new line with '----' is inserted.

**Comment by gsantner** [comment]
@jamiet-dev  @sjmduncan 
Could you/Do you want to take on this? Thanks 😄

**Comment by sjmduncan** [comment]
I'll take this!

**Comment by gsantner** [comment]
thanks you very much! Please do fresh fork/clone from master branch, there was a big change some hours ago
