### ISSUE TITLE
Setting to control document open cursor pos (top/bottom), seperate last pos option

### ISSUE THREAD

**Issue by DS-109** [gsantner/markor#1004]
#### General information

* **App version:** 2.2.10
* **System:** Android

#### Description
The default is to enter a document at the last cursor position, which was implemented in 2018:
https://github.com/gsantner/markor/issues/205
As an alternative, the settings have an option "start at bottom" (?, in German "Unten beginnen").
I would be happy if this option could be extended to a third alternative "start at top"!

When I open documents after a longer time, I usually read it from the beginning before I decide where to write something ( a chapter, a thing in a sorted list, etc.)

**Comment by FrantisekRadacovsky** [comment]
Hey. I would like to start working on it, is it still up for grab? If yes could you please assign it to me? Thanks.
