### ISSUE TITLE
Make Markor resizable

### ISSUE THREAD

**Issue by alexanderadam** [gsantner/markor#1006]
#### General information

* **App version:** `2.2.10` (F-Droid)
* **System:** Android 10 / Samsung Galaxy Tab S6

#### Description

I'm using [Samsung DeX](https://www.samsung.com/us/explore/dex/), which gives a desktop like experience and makes use of Android windowing support.

[Samsung has documentation on how to enable window resizing for Android applications](https://developer.samsung.com/samsung-dex/modify-optimizing.html):

```xml
<application
    android:resizeableActivity="true">
</application>
```

This documentation also has more tweaks and information on how to improve the desktop experience in case you're interested.
They also have [an app testing guide](https://developer.samsung.com/samsung-dex/testing.html) (although some apps are fine with this guide but won't work on "real" DeX sometimes).

At the moment the resizing button is greyed out and the application is always nearly squarish:

![Screenshot of Markor on Samsung DeX](https://user-images.githubusercontent.com/372620/88280072-7a521c00-cce5-11ea-8e6b-20469b2d28b1.jpg)

**PS:** I know that it is possible to _force_ all apps to be resizable via `Samsung Labs` > `Force Resize` but it would obviously better to make the application natively resizable to create less friction.

**Comment by gsantner** [comment]
I can add it, but not test as I don't have such a special device.

However, ` If your app targets API level 24, but you do not specify a value for this attribute, the attribute's value defaults to true. `. Which is the case, so this should be already be true by default according to documentation.

**Comment by alexanderadam** [comment]
Thank you for the fast commit.

> I can add it, but not test as I don't have such a special device.

I can test it and give feedback.
Is there any apk that I could test? There's none [in the releases](https://github.com/gsantner/markor/releases), right?

> However, `If your app targets API level 24, but you do not specify a value for this attribute, the attribute's value defaults to true.`. Which is the case, so this should be already be true by default according to documentation.

It didn't seem to work on Samsung Galaxy S6 with Android 10. Maybe something else is missing? Apps like [VLC](https://code.videolan.org/videolan/vlc-android) seem to resize fine and [it seems that they also have `android:resizeableActivity="true"`](https://code.videolan.org/videolan/vlc-android/-/blob/master/application/vlc-android/AndroidManifest.xml#L509) explicitly included. But I can't tell whether this line alone is the reason why it is working (I'm not an Android developer).
