### ISSUE TITLE
Todo edit renders underneath toolbar

### ISSUE THREAD

**Issue by nathanielc** [gsantner/markor#1008]
#### General information

* **App version:** 2.3.0 (114)
* **System:**  Android version 10

#### Description
The todo.txt edit mode renders the first line underneath the toolbar.

Screenshot of view mode shows five lines
![Screenshot_20200726-120131](https://user-images.githubusercontent.com/3771906/88486022-d90ed400-cf37-11ea-9b2c-1f2403b42692.png)

Screenshot of edit mode shows four lines, cursor is on first line showing under the toolbar.
![Screenshot_20200726-120155](https://user-images.githubusercontent.com/3771906/88486030-e461ff80-cf37-11ea-9e4c-be8c0efc4c82.png)

**Comment by gsantner** [comment]
Alreaddmy fixed, please update to 2.3.2

**Comment by nathanielc** [comment]
Thanks, can confirm it's fixed.
