### ISSUE TITLE
App 'Auto' Theme: Theme may not be correctly applied when day/night toggles & app is running

### ISSUE THREAD

**Issue by ohenepee** [gsantner/markor#1009]
#### General information

* **App version:**  2.3.1 (115)
* **System:** Android 7.0

#### Description
Having the app's theme set to Auto has an issue that I haven't seen anyone report (which shocks me), it has existed since the Auto theme's introduction.

If the app is opened (let's say round 4pm) and is minimized to background, bringing it to foreground (around say 7pm) will cause the theme to switch to Dark/Night mode however the text will remain in Light mode which becomes unreadable.

![Screenshot_20200726-185953](https://user-images.githubusercontent.com/15159487/88487286-35dbb000-cf73-11ea-9a7f-6617d0428a25.png)
![Screenshot_20200726-190010](https://user-images.githubusercontent.com/15159487/88487289-40964500-cf73-11ea-9edb-8524a455e130.png)

**Comment by gsantner** [comment]
Hi I think somebody told this in chat already, but it's quite minor thing, as just needs app restart.

**Comment by ohenepee** [comment]
Its obvious to anyone that it needs an app restart, but ur comment seem to imply its not worth fixing (or probably can't be fixed)... is this the case?

**Comment by gsantner** [comment]
It has low priority, that I want to say.

**Comment by Samuelgabor** [comment]
Hi. I would like to work on this issue. Is it still free?

**Comment by Samuelgabor** [comment]
Is this issue still free? I would like to work on project like this. Thank you.

**Comment by gsantner** [comment]
Yes, please go for it!

Note: First most importantly you have to reproduce it, so you can fix it. You will require to change your system time settings, or temporary adjust the time ranges in code.
