### ISSUE TITLE
Automatically open notebook file on startup

### ISSUE THREAD

**Issue by add1989** [gsantner/markor#1013]
Hi,

It is already possible to set a start up tab (notebook) and a startup folder. It would be really great if you could also set a startup filename in this case.

Use case: My notes folder has a LOT of .MD files and it would be nice to be able to open index.md automatically and without having to search or rename.

**Comment by gsantner** [comment]
You can set QuickNote to index.md, and set default tab to QuickNote.

**Comment by add1989** [comment]
I hadn't thought of that, however I do use QuickNote as a kind of 'scratchpad' - so it would mean losing that. Also, QuickNote always opens in edit mode first and my index.md is the one I've that I don't need to edit very often 😄

**Comment by gsantner** [comment]
Notebook / Files view is for browsing files, whatever about editing & viewing is not something covered there.
