### ISSUE TITLE
How to enable "Table of Contents" in view/read mode

### ISSUE THREAD

**Issue by lexterror** [gsantner/markor#1014]
Hi, I'm really glad you included the "Table of Contents" feature. But I think it's most necessary if you want to jump to different sections of the file while reading not just in edit mode. Unless I missed something... Is there a shortcut that I'm missing?

Thank you!

**Comment by gsantner** [comment]
The reason for adding in edit mode is... that it was there for view mode already and missing for edit :D.

You can enable it in markdown settings.

**Comment by lexterror** [comment]
gsantner: I don't mean to sound weird, but I can't find the setting for "Table of Contents" for read/view mode.

**Comment by lexterror** [comment]
I just found it. Thank you!
