### ISSUE TITLE
Folder save for quicknote/todo settings

### ISSUE THREAD

**Issue by aevw** [gsantner/markor#1017]
There's no "select this folder" option in Settings/General/Save Location 
for QuickNote and To-Do 
but there is for Notebook

**Comment by gsantner** [comment]
Ehm, Todo and quicknote are two **files**. Why wouod you want folders for what is a file?

**Comment by aevw** [comment]
To be able to save certain type of files in different locations. Why there's option for those files in settings for location?
![markor](https://user-images.githubusercontent.com/69059460/89125878-dbcd7400-d4b7-11ea-9013-684652f827cd.jpg)

**Comment by gsantner** [comment]
I still dont get it sorry, you can create any amount of folders, click them and create files in them. QuickNote and To-Do are single special files.

**Comment by aevw** [comment]
Yes you're right I can use file explorer to do that. In separate locations would be faster to find those files right away, I have quite a lot of notes generated in "Files" section.

**Comment by gsantner** [comment]
you can use favourite as well, additionally. For quick jumping between frequently vistied tolders.
