### ISSUE TITLE
Request: ==text== for highlighting

### ISSUE THREAD

**Issue by glocalglocal** [gsantner/markor#1022]
It would be nice to support ==text== for highlighting. Typora does this as an option, but I understand this isn't standard markdown.

**Comment by gsantner** [comment]
Every additionaly syntax highlighting is directly affecting performance. Just checked CommonMark and couldn't find something similar. Want to stay compatible with most other software and especially desktop tools. Wheras none supports it I've tried.

Suggestion: Use a non-typora specific syntax of markdown, like CommonMark.
