### ISSUE TITLE
Undo disabled after rotating device while editing

### ISSUE THREAD

**Issue by JohnVeness** [gsantner/markor#1023]
If I am editing a document and rotate the device (i.e. change orientation from landscape to portrait or vice versa), the undo button is greyed out.

Package: net.gsantner.markor
Version: v2.3.2 (116)
Flavor: Default (release)
Build date: 2020-07-29T08:02Z
ISource: com.google.android.packageinstaller
VCS Hash: 73c73f21ffecbdec2d35bae8e0472980572af8e5

**Comment by gsantner** [comment]
Android standard behaviour is to reset activity state when rotating the screen. With rotation the undo/redo history gets cleared as such the buttons also get "greyed out" because history is empty then.

Rotation allows maximum cache of ~500kb and for most users at has been shown to be not enough at all.

Closing this as won't fix.

**Comment by JohnVeness** [comment]
OK, thanks for info. For your interest, I'm using Markor on an Fxtec Pro1 (a new keyboard slider phone), and quite often do quick edits in portrait and switch to doing "serious" edits with the physical keyboard in landscape. It's a pity the undo/redo history isn't preserved in that case, but if there's no simple fix, I understand.

**Comment by gsantner** [comment]
Would it be helpful to you, to have a option to force markor always into Landscape mode - independent to your system or sensor rotation?

**Comment by JohnVeness** [comment]
Hmm, nice idea, but when I'm just "consuming" documents that I've written, I usually do so in portrait, as that's easier to do one-handed.

**Comment by riveravaldez** [comment]
> Would it be helpful to you, to have an option to force markor always into Landscape mode - independent to your system or sensor rotation?

Hi, @gsantner , sorry to comment on a closed issue, but I think the mentioned option would be a great solution (as long as the user can choose if the forced orientation would be Landscape or Portrait). In my case, I'm using Markor all the time in Portrait, but being the system with the rotation enable, any movement that changes it makes me loose the undo history, which some times can be very problematic.

Thanks a lot, hope this option makes it to some future version! (And have a great year's beginning ^_^ )

**Comment by gsantner** [comment]
See <https://github.com/gsantner/markor/issues/93>. In case somebody is interested, it is always open for development.

**Comment by milahu** [comment]
still an issue, please re-open
