### ISSUE TITLE
Feature Request: Large file support

### ISSUE THREAD

**Issue by sudomain** [gsantner/markor#1024]
#### General information

* **App version:** 
2.3.2
* **System:** 
Android 7.0, LG Stylo 3 Stock ROM
#### Description
Markor crashes when large files (~10,000 lines) are open and user switches to another app. Additionally, nothing is shown in the view mode. I have to switch to edit mode to see the document.

The document in question is the Bash Reference Manual that I generated in Termux using this command:

`info --subnodes --output bashref.texi bash`

**Comment by gsantner** [comment]
With what we use (base on standard Android components, regex) the limiting factor is device hardware. Or generally speaking the used components might or might not be the main reason for big files crashing.

Without fully rewriting and recreating Markor it's impossible on low-specced phones to support big files.

Thus closing as won't fix, as nobody including me really wanna do this full rewrite.

**Comment by sudomain** [comment]
> the limiting factor is device hardware. 

As a temporary measure, I've been using the text editor that comes with [the MaterialFiles file manager](https://github.com/zhanghai/MaterialFiles) (also on FDroid) which, despite my hardware, is handling the file fine (including quick scrolling). It's disappointing to hear that this is a wontfix, but I'm very appreciative for  Markor and the many things it does well.

I'm not familiar with Markor's codebase, but this is MaterialFiles' [TextEditorActivity](https://github.com/zhanghai/MaterialFiles/blob/04a5ee554aab22d9de14fd8e920caf8842e294d3/app/src/main/java/me/zhanghai/android/files/viewer/text/TextEditorActivity.kt).

> Thus closing as won't fix, as nobody including me really wanna do this full rewrite.
If I or someone made a (sane) PR for it, would it be considered for merging? Or are files of this size out of the scope of this project

**Comment by gsantner** [comment]
> If I or someone made a (sane) PR for it, would it be considered for merging? Or are files of this size out of the scope of this project

I'm happy to merge PRs if it improves things and it keeps the majority of features Markor already has. Markor's main functionalities are though centered around regexes (which apply to the whole file), it's gonna be a hard job to redo that.
