### ISSUE TITLE
Q: How does insert date button works for todo.txt

### ISSUE THREAD

**Issue by ljb279** [gsantner/markor#1026]
#### General information

* **App version:** v2.3.1 and v2.3.2 F-Droid
* **System:** Android 7.0

#### Description
In v2.2.10 I can insert today's date into a todo.txt file just by tapping the Date toolbar button. This was very useful for adding dated notes to a TODO item.

In v2.3.1 and v2.3.2, instead of inserting the date, Markor opens a date picker dialog with the current date highlighted. But I can't get it to insert anything.  I can select a date by tapping on it, and change months, but there is nothing I can find to actually close the dialog and insert the date. Short tap, long tap, anywere on the dialog - nothing happens. What am I missing?

**Comment by gsantner** [comment]
Uhm, there is a "Cancel" and "OK" button? Not sure what can be done for better discovery of the buttons.

![Screenshot_20200816-225742_Mordor](https://user-images.githubusercontent.com/6735650/90343780-ec333200-e013-11ea-9e53-9027d7b8a985.png)

**Comment by ljb279** [comment]
Thanks for the reply and screenshot. I was afraid of that... See attached screenshot from my phone. Alas, no Cancel or OK.
My phone is rather low-end with a resolution of 480x854 which LG calls "FWVGA". I suspect I just don't have enough pixel rows to show the whole dialog. Nor does it scroll or zoom. I will say I've never had problems with Markor, or Firefox (my 2 most used apps!) until this one. But I suspect this will not be worth fixing.

![Capture+_2020-08-16-17-32-04](https://user-images.githubusercontent.com/6787065/90344330-dbb89280-dfe6-11ea-91db-9ef91ee2185c.png)

**Comment by gsantner** [comment]
Removed the "Insert date" heading, this should result in the buttons being visible on your device. Please let me know with next update if you can see it.

Thx

**Comment by ljb279** [comment]
Confirmed fixed in v2.3.3(117) and works fine. Thanks!
