### ISSUE TITLE
Searching not working while going back to edit mode

### ISSUE THREAD

**Issue by aevw** [gsantner/markor#1027]
#### General information

I think this might be a bug. While doing search for keywords after switching back from "view mode only" back again to "edit view" it simply refuses to go to searched phrase/word. You have to open file again to make searching work.

* **App version: 2.3.2
* **System: 10

#### Description
1. Open document
2. Go to 'view only' mode
3. Go back to 'edit mode'
4. Look for a word
5. Select result
6. App doesn't go to location of that word

**Comment by gsantner** [comment]
Can reproduce, no pc on holiday though.

Fix: edittext.requestFocus() at search result select.
