### ISSUE TITLE
Feature Request: Option to show Favorites at startup

### ISSUE THREAD

**Issue by dgasaway** [gsantner/markor#1028]
#### General information

* **App version:** 2.3.2 (116)
* **System:** Android 10

#### Description

I would like to have an option for the application to list Favorites when it first starts.

**Comment by gsantner** [comment]
This is already there. In settings select Favourites instead of notebook for start tab.

**Comment by dgasaway** [comment]
There is no such option for 'App start tab'.  However, I didn't understand at the time that 'App start tab'='Notebook' and 'App start folder'='Favourites' would give me the results I wanted.  Thank you.

**Comment by gsantner** [comment]
Anyway its the option I meant
