### ISSUE TITLE
Can't open .xlf files

### ISSUE THREAD

**Issue by aevw** [gsantner/markor#1033]
#### General information

* **App version:2.3.2
* **System:10

#### Description
Markor opens .xml files without any problem but it doesn't recognize .xlf files. How could I go about with opening this type of file with Markor?

Thanks

**Comment by gsantner** [comment]
This requires addition of .xlf file extension to some files.

It's an very easy task, just needs copy paste of what you can find with yaml.


![grafik](https://user-images.githubusercontent.com/6735650/90732848-3722a300-e2bb-11ea-88e5-e02cdb221b36.png)

Easy todo for most people (you?) looking at this comment, waiting for PR.

**Comment by harshad1** [comment]
Isn't adding the `.xlf` format to the list of formats to open in `Settings/General/Miscellaneous/Always open with this app` sufficient?

**Comment by gsantner** [comment]
when using markor file browser yes. But when wanting to open xlf files from other app, Manifest change is needed

**Comment by gsantner** [comment]
sad to see that nobody worked on this very very simple & easy one, it was already described exactly what todo ....

it should not always be up to harshad1 and me to do everything the community requests.
