### ISSUE TITLE
To-Do list, sort by selected category or tag

### ISSUE THREAD

**Issue by spiralofhope** [gsantner/markor#1035]
#### General information

<details>
 <summary>Click to expand</summary>

Markor 2.3.2

Settings > About phone > 

* Custom built version:  alps-mp-q0.mp1.V8.4

Settings > About phone > Android version

* Android version: 10
* Android Security patch level: 5 December 2019
* Baseband version:  MOLY.LR12A.R3.MP.V84.T1,MOLY.LR12A.R3.MP.V84.T1
* Kernel version:  4.14.141
  *  `#1` Thu Mar 19 09:23:51 CST 2020
* Build number: UMIDIGI_Power_3_V1.1_20200319

</details>

#### Description

The closest to this feature which I could find was #211 - Sort to-do lists (with dialog asking for order)

I need to organize my list so I can say "I'm at `@home`, what todo items do I have here?" or "I'd like to do my `+groceries`".  What I'd like is:

<details>
 <summary>Click to expand</summary>

1. Click the `AZ` sort button.
2. Select (**new**) `Category (select)`
3. View the category picker (the list of categories)
4. Select one category
5. All items containing that category are moved to the top
  a.  Unfinished items first, sorted by description, ascending.
  b.  Finished items next, sorted by description, ascending.
  c.  The remaining items are not processed (sort doesn't matter)

</details>

The above feature would be implemented separately for categories, and for tags.

----

The more advanced version of this feature request would include both categories and tags:

<details>
 <summary>Click to expand</summary>

1. Click the `AZ` sort button.
2. Select (**new**) `Category/Tag (select)`
3. View the category picker (the list of categories)
4. Select one category
5. View the tag picker (the list of tags)
6. Select one tag
7. All items containing _both_ that category and that tag are moved to the top
  a.  Unfinished items first, sorted by description, ascending.
  b.  Finished items next, sorted by description, ascending.
  c.  The remaining items are not processed (sort doesn't matter)

</details>

**Comment by gsantner** [comment]
Hey,

most of the users will be fine with the existing sort. Most users will be scared when it's so complicated to sort stuff.

Instead, I suggest to improve the default sorting options to give better results, but I don't wanna add a full fledged search-customization whereas only low amount of people gonna use it anyway.

**Comment by spiralofhope** [comment]
One extra dialog isn't scary!

The first, simple, version wouldn't be difficult at all to use.

----

### improved sorting

I think the idea of improving sorting won't work.  Here's my idea for tags:

original list:

- example one +a +b
- example two +b +a
- example three +a +b +c
- example four +c +a

If sorted by tag it would:

- for each line, alphabetize its tags
- sort the list by tags (already implemented)
- then sort the list by name (already implemented?)

The above would become:

- example one +a +b
- example three +a +b +c
- example two +a +b
- example four +a +c

This is still horrible for my use, because  I could not easily find all items with the tag +c

I need to be able to put all +c in one clump.  The only other idea I have is to have some sort of typeahead search which filters the list.. but that doesn't seem appropriate.

**Comment by gsantner** [comment]
>  I could not easily find all items with the tag +c

Then why you not use search, you actually already say **find** and **typeahead search**. Both of it is available at Markor. Just press the search button and type `+c` or ` +c `

**Comment by spiralofhope** [comment]
I tried the typeahead search, and I see it builds a black-and-white list.  I can click on a line and it brings me to my main todo page again, selecting that line.  This isn't very convenient because I have to return to the search dialog many times.

Maybe this would be a simpler request:

- Click "search"
- Type text
- click (**new**) "move these items to the top"

Then it would iterate through the list and move those matched items to the top, (sorting them by their name)

**Comment by gsantner** [comment]
I dont plan changes on the search.
