### ISSUE TITLE
Q:  New file button 

### ISSUE THREAD

**Issue by madeindjs** [gsantner/markor#1036]
#### General information

* **App version:**  2.3.2
* **System:** Android 8.0

#### Description

Since I updated to version 2.3.2, I can't be able to create a new file. Nothing happens when I click on "+" button. But I can edit and save existing files without problems.

**Comment by gsantner** [comment]
Hey,

are you sure you are in a folder where you can actually create files? And not in i.e. "Favourites"? I'm using Markor every day, and also tried file creating now - had no issue. Also nobody else has reported somthing similar yet.

**Comment by madeindjs** [comment]
Hi,

I just rebooted my phone and It works now. Maybe it was an issue with my SD cards but I was be able to view and edit files.

So I think I can close issue for now.

Thank you for you answer.
