### ISSUE TITLE
Improve contrast on To-Do list completed items

### ISSUE THREAD

**Issue by spiralofhope** [gsantner/markor#1038]
#### General information

<details>
 <summary>Click to expand</summary>

Markor 2.3.2

Settings > About phone > 

* Custom built version:  alps-mp-q0.mp1.V8.4

Settings > About phone > Android version

* Android version: 10
* Android Security patch level: 5 December 2019
* Baseband version:  MOLY.LR12A.R3.MP.V84.T1,MOLY.LR12A.R3.MP.V84.T1
* Kernel version:  4.14.141
  *  `#1` Thu Mar 19 09:23:51 CST 2020
* Build number: UMIDIGI_Power_3_V1.1_20200319

</details>

#### Description

When I mark an item as completed, it changes color.  I can't see it very well on either the light or dark themes.  Perhaps it could just be black-and-white with a strikethrough?

**Comment by gsantner** [comment]
It's intended this way, to gain focus on the remaining tasks.

**Comment by spiralofhope** [comment]
That's unfortunate.  :(

**Comment by gsantner** [comment]
If you want to suggest a different color (hex code) I'm fine with changing. However I want to keep it colored slightly different.

Strikout is more expensive for performance (and you cannot read it at all then), hence not used that one

**Comment by spiralofhope** [comment]
It does have a strikethrough right now.  Maybe if you'd like to be certain it's different, italics would be okay.

For a dark theme, perhaps something like [`#feeb8d`](https://www.color-hex.com/color/feeb8d) or a more dim [`#f3e3bb`](https://www.color-hex.com/color/f3e3bb)

For a light theme the color seems okay, but something like [`#353549`](https://www.color-hex.com/color/353549) is easier to see.  The strikethrough is definitely bad on a light theme.

To understand contrast colors well, I found this website useful: https://webaim.org/resources/contrastchecker/

**Comment by gsantner** [comment]
> For a dark theme, perhaps something like #feeb8d or a more dim #f3e3bb

There is e.g. solarized theme, and gruvbox theme. both have yellow-ish background color so not a good idea.

> The x is a fairly good indicator that something is completed, but if you'd like to make the line stand out as completed, perhaps it should be replaced by something like an x mark. But this is getting complicated and inappropriate:

Big nope, x is in text, we show x, and no custom symbol. Especially: Emoji is different on OS/vendor basis and we don't wanna break stuff.

**Comment by spiralofhope** [comment]
> > For a dark theme, perhaps something like #feeb8d or a more dim #f3e3bb
> 
> There is e.g. solarized theme, and gruvbox theme. both have yellow-ish background color so not a good idea.

Are those these?

https://ethanschoonover.com/solarized/  ([source](https://github.com/altercation/solarized))
https://github.com/morhetz/gruvbox

My Markor only has Auto, Dark and Light.  How would I try them?

**Comment by gsantner** [comment]
See the second settings category for editor-only colors.

**Comment by spiralofhope** [comment]
> See the second settings category for editor-only colors.

I need my hand held; I really did comb through everything, and I just can't see it.

I don't know what you mean by "settings category".  I:

- click the vertical three dots at the top-right
- click 'settings'
- I see Theme under "Essential".

For every other thing (General, Other, etc) I don't see any reference to themes, solarized or gruvbox..

**Comment by gsantner** [comment]
"Other" settings.
