### ISSUE TITLE
todo: don't add completition date when date setting unchecked

### ISSUE THREAD

**Issue by spiralofhope** [gsantner/markor#1039]
#### General information

<details>
 <summary>Click to expand</summary>

Markor 2.3.2

Settings > About phone > 

* Custom built version:  alps-mp-q0.mp1.V8.4

Settings > About phone > Android version

* Android version: 10
* Android Security patch level: 5 December 2019
* Baseband version:  MOLY.LR12A.R3.MP.V84.T1,MOLY.LR12A.R3.MP.V84.T1
* Kernel version:  4.14.141
  *  `#1` Thu Mar 19 09:23:51 CST 2020
* Build number: UMIDIGI_Power_3_V1.1_20200319

</details>

#### Description

I don't use the date functionality for one of my todo lists, and it's inconvenient for me to delete the date.

I see there is the setting "Tasks with today's date", but I also want to not add the date when I complete an item.

**Comment by PatriciaHeimfarth** [comment]
I would like to work on that issue

**Comment by gsantner** [comment]
Please go for it!
Should be as easy as 3 lines of code :D. AppSettings + todotxt classes.
