### ISSUE TITLE
Do not remove priority when completing a To-Do item

### ISSUE THREAD

**Issue by spiralofhope** [gsantner/markor#1040]
#### General information

<details>
 <summary>Click to expand</summary>

Markor 2.3.2

Settings > About phone > 

* Custom built version:  alps-mp-q0.mp1.V8.4

Settings > About phone > Android version

* Android Security patch level: 5 December 2019
* Baseband version:  MOLY.LR12A.R3.MP.V84.T1,MOLY.LR12A.R3.MP.V84.T1
* Kernel version:  4.14.141
  *  `#1` Thu Mar 19 09:23:51 CST 2020
* Build number: UMIDIGI_Power_3_V1.1_20200319

</details>

#### Description

I use some todo lists to regularly complete and un-complete items, and it is important for me to keep the priority even when I complete something.

**Comment by gsantner** [comment]
> Many Todo.txt clients discard priority on task completion. 
 https://github.com/todotxt/todo.txt#rule-2-the-date-of-completion-appears-directly-after-the-x-separated-by-a-space

So does Markor and all other todotxt I tried.
