### ISSUE TITLE
Auto-save not functioning

### ISSUE THREAD

**Issue by spiralofhope** [gsantner/markor#1041]
#### General information

<details>
 <summary>Click to expand</summary>

Markor 2.3.2

Settings > About phone > 

* Custom built version:  alps-mp-q0.mp1.V8.4

Settings > About phone > Android version

* Android version: 10
* Android Security patch level: 5 December 2019
* Baseband version:  MOLY.LR12A.R3.MP.V84.T1,MOLY.LR12A.R3.MP.V84.T1
* Kernel version:  4.14.141
  *  `#1` Thu Mar 19 09:23:51 CST 2020
* Build number: UMIDIGI_Power_3_V1.1_20200319

</details>

#### Description

- View QuickNote
- Make a change to QuickNote
- Switch to To-Do
- Make a change to To-Do
- Switch to QuickNote
  -  (the changes were not kept)
- Switch to To-Do
  -  (the changes were not kept)

As far as I can tell, there is no auto-save any more..

- I tried exiting the application, then stopping it, and the problem persists.
- I tried rebooting, and the problem persists.

I know it used to work. I must have changed some system setting, but I don't know what might have caused this.  Do you have any ideas?

**Comment by gsantner** [comment]
I and many users use Markor daily .. and I really write in todo/quicknote like every hour - not having any issues so far.

You pasted lots of info, but the most important info is not among. Android version.

**Comment by spiralofhope** [comment]
Oh!  It's Android 10.

I'm thinking I should uninstall and reinstall to see if there was some permissions problem somehow.

I just found another app with similar external storage issues, so maybe this is just me somehow.

**Comment by spiralofhope** [comment]
How strange, I fixed it.

What I did was to delete my existing `todo.txt` and `QuickNote.md` and re-start Markor.  I still use my own custom save location on my external storage.  Now when I use Markor it has re-created those two files and saving works as-expected.

**Comment by gsantner** [comment]
Hey thanks for trying. Weird but cool to hear it's working now 😃
