### ISSUE TITLE
Feature Request: Solarized Light and Dark themes

### ISSUE THREAD

**Issue by lord-aerion** [gsantner/markor#1046]
#### General information

* **App version: 2.3.2 (116)** 
* **System: Android 8.0.1** 

#### Description
The dark theme is pretty good, but the light theme is too stark. I’d love to see two additional theme options: Solarized Light and Solarized Dark.

The Solarized project’s homepage has detailed information on the implementation https://ethanschoonover.com/solarized/

**Comment by gsantner** [comment]
For the editor/viewer there is already Solarized and other popular themes.

![Screenshot_20200903-184509_Markor](https://user-images.githubusercontent.com/6735650/92143555-bbc20500-ee15-11ea-86bb-d325457c1dd0.png)


As of Markor itself, no other designs (that modify everything likr about page too) are not planned. I want to keep it Dark or Light. Finding a good-working balance for icons, other colors and components is doable with two, but gets hard with more.
