### ISSUE TITLE
Syntax highlighting for more languages

### ISSUE THREAD

**Issue by georgefst** [gsantner/markor#1049]
#698 is an awesome addition. But what was the decision-making process for which languages to include? Would there be any real downside to including [all the languages supported by Prism](https://prismjs.com/#supported-languages)? If so, are you at least open to requests for a few more, reasonably popular, languages?

My notes contain a lot of Haskell and Rust code in particular, so right now I have highlighting for about half of them.

Version 2.3.2, Play Store

**Comment by gsantner** [comment]
Every piece of code and file increases file size and load speeds. If theres a particual need it's possible to add, but in general I don't want to blow up Markor with every possible thing that is out there.

**Comment by georgefst** [comment]
Well, personally I'd love to see Haskell.

More generally, perhaps inspiration could be taken from something like [TIOBE](https://www.tiobe.com/tiobe-index/). Although I'm always a bit skeptical of these sorts of rankings - I'm certain there are likely to be more people wanting to include Bash in their notes than say, Cobol.

**Comment by gsantner** [comment]
As you probably can see how it all works together here - please send a PR to add the additional languages you want to have. Thanks
