### ISSUE TITLE
Table has no/incorrect highlighting & resulting table has no borders

### ISSUE THREAD

**Issue by Framstag** [gsantner/markor#105]
#### General information

* **Device:**   Nexus 5x
* **Android Version:**  Android 8.0
* **App version:**  v0.1.6

#### Steps to reproduce

Create table:
```
|Spalte|Spalte|
|--------|--------|
|eins | zwei |
```

#### Expected result
** table will be hilighted in editor. 
** Layouted table has borders

**What do you see instead?**

** Current there is no highlighting. If I'm adding a lower border, parts are rendered in orange: `|-----|----|`
** Table has no borders, text is "just" alligned.

**Comment by gsantner** [comment]
Wir sind bei Markor schon sehr an der Grenze des möglichen was mit Regex-Highlighting möglich ist. Denke aufgrund von Performance ist es besser für Tables nicht etliche zusätzliche Regeln hinzuzufügen, die letzten Verbesserungen des Highlighters sind bereits spürbar (Verzögerung) auf älteren Geräten.

Tables funktionieren im Rendering, jedoch nicht alle diversen Variationen. Siehe dazu #27. Alles was den Renderer angeht ist ein upstream problem.

**Comment by gsantner** [comment]
Ups, #92.
