### ISSUE TITLE
Open Youtube link in Youtube app, or provide options to open with

### ISSUE THREAD

**Issue by anishmittal2020** [gsantner/markor#1050]
When I click on any Youtube link on the html view of the markdown page, it opens its own browser and starts playing the video. But, it might be useful it provides the options set in Android to open youtube links with list of particular apps (like Youtube, Chrome, NewPipe or SkyTube). 

This is useful, when we could play it directly from the desired app which has certain functionality which the default browser of the Markor doen't have (such as ability to stream to TV using a chromecast).

**Comment by gsantner** [comment]
There is a option to open in other app. Click the three dots in the top-right and you will see it.

**Comment by anishmittal2020** [comment]
@gsantner Yes I am aware of that, but I was hoping that the links could directly open in the relevant app, as the users can set what links sid open in default apps.

**Comment by gsantner** [comment]
#686
