### ISSUE TITLE
md: auto format table rows (auto add new on enter press)

### ISSUE THREAD

**Issue by hallnorthncov** [gsantner/markor#1058]
#### General information

* **App version:** v2.2.9 F-Droid
* **System:** Android 6.0

#### Description
I want the table(|-|-|) to be automatically formatted like the list(-).

![tablea](https://user-images.githubusercontent.com/66166206/92745101-a2d8c700-f3b4-11ea-8638-4f4243eedde8.gif)

**Comment by gsantner** [comment]
While it's possible, it's gonna be not as easy.

Note that you also have a table action button in the bottom row. With it you can easily add another table row easily.

**Comment by gsantner** [comment]
I thought about it, and my honest thought is: Markor has a easy to use table button that should be used. Automatically changing preceeding lines and lines afterwards is atm out of scope. Due small screen size it might often happen then that things span across multiple lines just so all columns fit. Don't want to add too much automation here.
