### ISSUE TITLE
Faulty rendering of markdown in preview

### ISSUE THREAD

**Issue by haverholm** [gsantner/markor#106]
Header markup isn't rendering correctly in preview unless a space is added after hashes. This doesn't reproduce in any markdown renderer I've used and, though I assume it's deliberate, is effectively a bug.

**Comment by gsantner** [comment]
Report rendering errors including sample to upstream. we cannot fix their issues.

commonmark-java.

**Comment by haverholm** [comment]
Or I'll just continue using Writeily which did not have this bug. No thanks bye. :neutral_face:

**Comment by gsantner** [comment]
Haha, you can ofc. Anddown is just not really updated anymore, and misses a lot

**Comment by gsantner** [comment]
Both, Markdown and commonmark specification do say there must be a space after - `## header`. See e.g. <http://spec.commonmark.org/0.27/#atx-headings> . What you are telling is just not spec conform.
