### ISSUE TITLE
md: Disable edit-mode ToC in view-mode

### ISSUE THREAD

**Issue by contrapunctus-1** [gsantner/markor#1060]
Thanks for adding the ToC - it makes it easy to read large files. I have a request for a behaviour which would greatly ease their editing as well.

## Situation
1. View mode. User taps a ToC heading.
2. They switch to edit mode.

## Current  behavior
The cursor is placed at the beginning of the document (even with the 'open at end' option enabled? Might be a bug.)

## Suggested behaviour
Place the cursor at or below the heading.

If there is a concern about a case where the user -

1. taps a ToC heading
2. scrolls around, possibly going to another section
3. switches to edit mode

...then the behavior could be to fall back to usual behavior (cursor at start or end of document) if the user scrolls after tapping the ToC heading.

This would make editing large files a lot easier.

**Comment by gsantner** [comment]
Hi, that ToC is only there for edit mode, hence it should be only available in edit mode.

Thus, resolve will be that the edit mode ToC gets disabled/unavailable on view mode.

**Comment by contrapunctus-1** [comment]
Hey, @gsantner . I'm not sure what you mean by "edit mode ToC" - I haven't seen any ToC in the edit mode. 🤔 I'm running v2.3.2 from F-Droid.

**Comment by gsantner** [comment]
Please share a screenshot **what** you actually tap, thats clears things.

**Comment by contrapunctus-1** [comment]
@gsantner Here is a video demonstrating the problem - https://upload.disroot.org/r/bPbuFGWV#ukUtez62aWnV3AvNGsVrBHgvRjpjBNGR8Ogomo21Og8=

**Comment by gsantner** [comment]
OK, so your request is to synchronize view mode scroll state with edit mode scroll state.

This has been already requested, and I marked it as a won't fix. It's due it's not feasible to implement, the view content (/HTML) does not fully correlate to the original text (otherwise it wouldn't have been converted :P).

**Comment by gsantner** [comment]
OK, so your request is to synchronize view mode scroll state with edit mode scroll state.

This has been already requested, and I marked it as a won't fix (#679). It's due it's not feasible to implement, the view content (/HTML) does not fully correlate to the original text (otherwise it wouldn't have been converted :P).

**Comment by contrapunctus-1** [comment]
@gsanter I'm well aware of that issue. This is not a duplicate; note the title I had set - "Use the ToC heading we tapped on". The program just derives the information of where to open edit mode from the ToC heading the user tapped.

**Comment by gsantner** [comment]
> Surely the heading in edit mode is guaranteed to correlate to the ToC heading??

Nope, you can have 
```
## My ~~Cool~~ Headline
text
```
for example and it will be something different in view vs edit mode.


![1](https://user-images.githubusercontent.com/6735650/93709935-e664cb00-fb42-11ea-8b4b-2509a52063a0.png)

![2](https://user-images.githubusercontent.com/6735650/93709937-e8c72500-fb42-11ea-8f96-fa05d5942bcf.png)

![3](https://user-images.githubusercontent.com/6735650/93709938-ea90e880-fb42-11ea-95d9-7f77b5d5a523.png)

we would need a HTML to Markdown converter, which is out of scope of the project.
