### ISSUE TITLE
some suggest: 

### ISSUE THREAD

**Issue by ljca** [gsantner/markor#1066]
#### General information

* **App version: v2.3.3** 
* **System: Android 8.1** 

#### Description
I hope to increase the option to automatically expand the collapsed items when exporting to a pdf file or printing.

**Comment by ljca** [comment]
When I created a file but gave it a wrong file name to try to correct it, but at this time I can only change it in the file manager, which is very inconvenient, so I personally think that the function of manipulating files should be added ( Not only create and delete, but also move, rename and other functions)

**Comment by gsantner** [comment]
where you placed it?

PDF writing is done by Android itself, not Markor.

**Comment by ljca** [comment]
> Bold rendering cannot render part of a paragraph of text
