### ISSUE TITLE
Search will only navigate to first instance

### ISSUE THREAD

**Issue by harshad1** [gsantner/markor#1068]
Currently, the search dialog (search dialog, heading dialog etc) callbacks use `indexOf` to go to the requested position in the file.

If multiple instances of the search term are present in the file, this prevents us from jumping to anything except the first instance.

For example, consider the following structure

```
## Project 1
### notes <- instead stops here

## Project 2
### notes

## Project 3
### notes <- expected to go here
```
If a user searches for 'notes' and clicks on the 3rd instance, they will be taken to the first instance.

**Comment by gsantner** [comment]
After having all the todo stuff & PRs merged, we might go for `callback(String selection, int selectionIndex)`. Though it might get hard due search filter proxymodel.

**Comment by harshad1** [comment]
I have a working version of exactly this :). Will create a PR later today.

Oct. 1, 2020 05:20:10 Gregor Santner <notifications@github.com>:
