### ISSUE TITLE
Feature request: Add favorites as a tab

### ISSUE THREAD

**Issue by harshad1** [gsantner/markor#1069]
I am of the opinion that `favorites` is important and useful enough to include as a full tab at the bottom of the main screen. If there are concerns that 5 tabs at the bottom (`files`, `to-do`, `quicknote`, `favourites`, `more`) are too much, then I feel that `more` can be moved into the menu

**Comment by gsantner** [comment]
there has been previously 5 items and it has been making issues on some devices, hence reduced to 4. Plus without hacks titles are shown only by max 4.

I don't intend to increase to 5 again. For quick get to favourites. PRO tipp: long-press the "+" button.

**Comment by harshad1** [comment]
:+1: for long press '+'

Since 5 tabs is too much, do you think it makes sense to exchange 'favorites' and 'more'

**Comment by gsantner** [comment]
I would keep it this way
