### ISSUE TITLE
switching from edit to view mode doesn't remember cursor position

### ISSUE THREAD

**Issue by seelaman** [gsantner/markor#1070]
#### General information

* **App version:**
2.3.3 Playstore

* **System:** 
Stock Android 10, Samsung Note 9

#### Description
When I'm in a long markdown file and I switch from edit mode to view mode (for example to jump to a link), the document is displayed scrolled to the top. It would be nice if the view was centered around the cursor position from edit mode so I don't have to use the search to jump back to where I was.

It's similar to [#205](https://github.com/gsantner/markor/issues/205) but that one only applied to "default to view mode" which I'm not using.

Implementation wise it could also be similar to [#1025](https://github.com/gsantner/markor/issues/1025)

**Comment by gsantner** [comment]
This has been already requested, and I marked it as a won't fix (#679). It's due it's not feasible to implement, the view content (/HTML) does not fully correlate to the original text (otherwise it wouldn't have been converted :P).
