### ISSUE TITLE
Feature Request: Larger paragraph spacing in edit mode

### ISSUE THREAD

**Issue by errorjones** [gsantner/markor#1076]
Hello,

any chance to make the paragraph spacing in edit mode customizable or a bit larger by default? The display of longer texts and lists would become much clearer that way.

using v2.3.3 (117) on Android 9 PKQ1

**Comment by gsantner** [comment]
This is already there. Edit mode settings -> Line spacing.

**Comment by errorjones** [comment]
> This is already there. Edit mode settings -> Line spacing.

Actually, you first have to enable "Experimental features" under "General" settings. Only then the line spacing option will become available. But yeah, problem solved!
