### ISSUE TITLE
Markdown-dialects: Zim-Wiki

### ISSUE THREAD

**Issue by pschwede** [gsantner/markor#1082]
#### General information

I'd like to see Markor support several different markdown dialects. Personally, I would like to edit files written in [the zim wiki dialect](https://zim-wiki.org/manual/Help/Wiki_Syntax.html), right now.

#### Description

- **How to recognize the dialect?** Zim wiki files begin with three lines:
```markdown
Content-Type: text/x-zim-wiki
Wiki-Format: zim 4.0
Creation-Date: JJJJ-MM-DDTHH:mm:ss+nnnn
```
- **Other than syntax, what are further differences?** Zim wiki supports cross-file links. I don't know if Markor has this built-in already.
- I could help writing an interpreter. If this issue is rejected, I'll write an converter on my own.

**Comment by pschwede** [comment]
See https://github.com/gsantner/markor/issues/393

**Comment by gsantner** [comment]
Zim is not a Markdown dialect, completley different. If one, than it is a DokuWiki-ish syntax.
