### ISSUE TITLE
Search & Replace + other features

### ISSUE THREAD

**Issue by TTallroth** [gsantner/markor#1091]
#### General information

* **App version:** 
2.3.3

* **System:** 
Huawei P20 Lite, Android 9.1

#### Description
This is a feature request, for which I couldn't find the functionality in the current app version:
* Search and replace text (using regular extensions).
* Option to display line number.
* Split loading of large (huge) text files into pages. Current version takes forever to load a Bible text.

These are necessary features for me, before I can consider a full switch of text editor.

**Comment by TTallroth** [comment]
extensions -> expressions

**Comment by gsantner** [comment]
* #94
* #155
