### ISSUE TITLE
Remember more than 1 recent time format

### ISSUE THREAD

**Issue by harshad1** [gsantner/markor#1092]
The time / date dialog is pretty useful for entering dates and times. Currently, only the most recent time format is remembered (in addition to the list of default formats). It would be helpful if the 'n' most recent formats were remembered.

**Comment by harshad1** [comment]
I think n = 5 would be useful

**Comment by gsantner** [comment]
I  think the dialog is quite stuffed already, and has the most important + last options. I would not go for adding more additional lists there

**Comment by harshad1** [comment]
We should sort by recently used. That way the most recently used options would always be at the top and the user will almost never have to scroll to see their desired format.

I use the following formats daily:
- `yyyy-MM-dd'T'HH:mm` (Iso date)
- `'#' yyyy-MM-dd, EEEE` (daily entry heading)
- `HH:mm` (timestamp with leading 0 and no seconds)

I am sure other users have formats they use all the time, but which aren't in the list
