### ISSUE TITLE
Due date 'days in future' should be configurable

### ISSUE THREAD

**Issue by harshad1** [gsantner/markor#1093]
The due date insert functionality in 'todo.txt' (long press date button) will insert a due date +3 days in the future. This offset should be user configurable in the settings.

**Comment by harshad1** [comment]
@gsantner I am also of the opinion that the user should have the option to choose whether short or long press inserts due date.

**Comment by gsantner** [comment]
I'm sorry but I think Markor shouldn't go too much settings-creep here - not everything really needs to be a settings option.

For you - you can customize the 3 locally if you need to. For everybody else, theres the date picker as well - that should be enough for 99% of cases.

**Comment by harshad1** [comment]
> you can customize the 3 locally if you need to

I am trying really hard not to create a special version of markor for myself :). I went down that path for a while (had a lot a custom features like per-file line wrapping etc) but I want to limit myself to changes which can be pushed upstream.

If you do not want the due date changes proposed in this PR then I can live without them for now.

In general though, Is there a better way do discuss things than creating tickets on Github? i.e. is there a discord or slack channel for Markor?

**Comment by gsantner** [comment]
> In general though, Is there a better way to discuss things than creating tickets on Github? i.e. is there a discord or slack channel for Markor?

Matrix, see readme. Also, as soon "GitHub discussions" gets public available thats gonna be added as community tab to markor repo.
