### ISSUE TITLE
Unified theming and font for both Edit and View mode.

### ISSUE THREAD

**Issue by ThomasLeigh** [gsantner/markor#1094]
Could it be possible to have unified theming and font characteristics applied to both Edit and View mode? Or in other words, the View mode customizable to a degree similar to the Edit mode (e.g., any background color, exactly the same font family and size, however big, etc.)?

**Comment by gsantner** [comment]
font family & sizes should be already same.

**Comment by ThomasLeigh** [comment]
In Edit Mode settings I have set font size to “28”, in View Mode into “36”. Font name is “Lato”. Strangely, plain text (no Markdown) is displayed not larger, but a little bit smaller in View mode than in Edit mode.

**Comment by ThomasLeigh** [comment]
The reason I ask for the same theming is that due to my vision I can hardly read anything which is not placed on a background other than black. Since in View Mode I haven’t found possible to set dark background color other than dark-gray, I use Edit Mode for reading, but it would be great to have it available also in View Mode.

**Comment by gsantner** [comment]
you can fully customize view mode with css, the inject head settings option

**Comment by ThomasLeigh** [comment]
Thank You very much, I’ll experiment with this. By default, there is already some content present there (within “inject head” option) - should I leave it as is? (currently I only change the CSS part)

I think many users would appreciate if customizing the look of the view mode would be as simple as in case of Edit Mode.

**Comment by gsantner** [comment]
In general as said it should somewhat take over the sizes and it does the font. However its webview and font size not directly appears same as on a edittext component.

**Comment by 4ut0-M-4t** [comment]
Could you reconsider adding an option to get different fonts for Edit mode and View mode?  
My use case includes viewing HTML documents (where default font fits best) and editing all sorts: plaintext (txt, JSON, JS), Markdown, Markup, OrgMode, CSV, todo.txt, Zim (where monospaced font is a must). It's a pain to change settings for the whole app every time I need to *view* an HTML document.
