### ISSUE TITLE
Are shourcut icons adaptive?

### ISSUE THREAD

**Issue by 532910** [gsantner/markor#1099]
It doesn't look like adaptive:
![image](https://user-images.githubusercontent.com/14617699/96518694-19020080-1274-11eb-9804-0e71f870abe6.png)

Known apps with adaptive shortcut icons:
[Element](https://github.com/vector-im/element-android), [Orgzly](https://github.com/orgzly/orgzly-android), [Calendar](https://github.com/LineageOS/android_packages_apps_Etar), [SELinuxModeChanger](https://github.com/MrBIMC/SELinuxModeChanger), SoundCloud
![image](https://user-images.githubusercontent.com/14617699/96517260-4ef1b580-1271-11eb-8723-448ca6413dc2.png)

All of these shortcuts are created the same way, via long press from the main icon and dragging it to the desktop.

**Comment by gsantner** [comment]
Yees they are: <https://github.com/gsantner/markor/tree/master/app/src/main/res/drawable-anydpi-v26>

![grafik](https://user-images.githubusercontent.com/6735650/96519238-d4269b80-126c-11eb-90df-52cbbf374f05.png)

**Comment by 532910** [comment]
Could they be bigger?

**Comment by gsantner** [comment]
The final size is controlled by your launcher and system, not Markor. Or do you mean just the "foreground" icon?

**Comment by 532910** [comment]
OK, let's leave it the as it is (:
