### ISSUE TITLE
File count for directories includes non-markdown files

### ISSUE THREAD

**Issue by sjmduncan** [gsantner/markor#110]
#### General information

* **Device:** Moto G 4G
* **Android Version:**  Androind 7.1
* **App version:**  v0.1.5

#### Steps to reproduce

1. Create an empty <test> directory
2. Place a non-markdown file in <test>

#### What happens

The file count for <test> is 1 when viewed (in Markor) from its parent directory, but when you open <test> the non-markdown files are filtered and it is shown as empty.

#### Expected result

I think the solution is to show non-markdown files in the file list as greyed-out (disabled & non-clickable) entries, because Markor is close enough to a file browser that this is what I naturally expect. Also then you could see the file names of other files (e.g. images) that you might link to in your documents.

Alternatively Markor should just ignore non-markdown files for the directory file count.

Either way the file count and directory contents should be consistent.

**Comment by gsantner** [comment]
It is expected and wished by many users to support more than just .md files. But no, its not in general a filebrowser, the set is limited to 6 variations of `.markdown` and `.txt`. Other files are not listed.

I store some things personally too e.g. in a .txt file, even tho its markdown format

**Comment by gsantner** [comment]
What about showing

* Count of files: 15
* Count of files: 0 (+5)
* Count of files: 6 (+3)

whereas `+x` is subfolder nonsupported count. this way its clear if folder is empty or not, and if markor supported files are in there

**Comment by gsantner** [comment]
If you want to work on that, heres an idea:

* add a third section to the adapter, hidden files
* hide this whole new section by default
* show on toolbar toggle (in filesystem fragment menu) active these unsupported things there

**Comment by gsantner** [comment]
Can maybe combined with #115

**Comment by gsantner** [comment]
Fixed the issue itself, moved the adapter addition with addition of hidden-section to 115
