### ISSUE TITLE
todo.txt: Improve todo sorting for Russian & Ukrainian

### ISSUE THREAD

**Issue by andrey703** [gsantner/markor#1103]
#### General information

* **App version:** v2.3.3 (117) from Google PlayMarket
* **System:** Android 6.0.1, Samsung Galaxy s5 mini, SM-G800H

#### Description
Hello @gsantner. I am facing wrong sorting of entries in **todo.txt**. Sorting of all kinds **ascending** and **descending** works correctly if the application language is English. When choosing Russian or Ukrainian language of the application, all sorting **descending** does not work.

Thank you for your hard work. Love the app.

**Comment by gsantner** [comment]
What is your **System** locale (not markor settings one)? Markor uses [natural sorting](https://github.com/gsantner/markor/blob/149ec7063035be06cc5a575a109ac7fd5f0c30b4/app/src/main/java/net/gsantner/markor/format/todotxt/TodoTxtTask.java#L357) from root locale (system) by default for todo.

**Comment by andrey703** [comment]
System locale - Russian. The problem persists when choosing English for system locale.

**Comment by gsantner** [comment]
How do other apps behave? I don't think apps implement special sorting based for non-latin characters...literally everything/everybody uses natural sorting

**Comment by andrey703** [comment]
Unfortunately, I have not considered other applications that use sorting. 
Clarification on the problem. I looked more closely. When you select Russian and Ukrainian languages of the markor application, when you click on the sorting **"descending"**, the records are sorted **"ascending"**.
Do you think [this line](https://github.com/gsantner/markor/blob/149ec7063035be06cc5a575a109ac7fd5f0c30b4/app/src/main/java/net/gsantner/markor/format/todotxt/TodoTxtTask.java#L328) could be the problem?

**Comment by gsantner** [comment]
that line is for inverting the order, if it's 0 all stays same as before, -1 gets 1, and 1 gets -1..don't see something wrong on that line.

**Comment by andrey703** [comment]
I understood you.
I have checked markor on **samsung galaxy s4 mini GT-I9195** as well as latest version of **BlueStacks**. The problem remains.
I have installed [Material Files](https://github.com/zhanghai/MaterialFiles) app which uses file and folder sorting. The sort works fine, both **"ascending"** and **"descending"**. But I have not figured out if the developer is using natural sorting.
