### ISSUE TITLE
[Feature request]: add support for programming language highlight.

### ISSUE THREAD

**Issue by stevenleeS0ht** [gsantner/markor#1106]
It would be nice to add support for source code highlight.

**Comment by gsantner** [comment]
In view mode there is syntax highlighting for source code.  
i.e. \`\`\`python  does highlighting for python.  

For edit-mode everything needs to be developed on our own, and focus is on writing, not coding there.

**Comment by evgeni** [comment]
May I ask for a simple extension, that would probably suffice most users?

In view mode, ````python` works just fine, but in edit mode, it doesn't even trigger a "code" block. If you could make it display as a code block, without any further highlighting, this would make editing easier and not require you to actually do any real highlighting.
