### ISSUE TITLE
Archive completed tasks: bad UX

### ISSUE THREAD

**Issue by isti03** [gsantner/markor#1107]
If I choose a file that does not exist to archive completed tasks to, nothing happens. 

If this is not intentional, please fix it, and let the program create this chosen file. 

If it is intentional, please add a notice that notifies the user that this file does not exist and they have to create that manually. The current way of working is pretty frustrating.

**Comment by gsantner** [comment]
supposed to be auto-created.  
@harshad1 may due recent todotxt rework?

**Comment by harshad1** [comment]
I can reproduce this. Looking into it.
