### ISSUE TITLE
EM Dash from triple or double short dash

### ISSUE THREAD

**Issue by frafor** [gsantner/markor#1118]
#### General information

* **App version:** 2.4.0 (119)
* **System:** Android

#### Description

Triple dash (---) should be transformed into EM Dash. "Open" and "Close", should be transformed into typographical marks.

I made server intents at finding the issue, but was unable to find one referring to the issue.

**Comment by gsantner** [comment]
Is this a personal request, or by some Markdown standard? Please show me the CommonMark spec description for triple dash.

**Comment by gsantner** [comment]
no response

**Comment by eyolf** [comment]
I'm jumping in here. It is not part of markdown itself, but the author of markdown also wrote [Smartypants](https://daringfireball.net/projects/smartypants/ ) which does that kind of conversion, and it _is_ part of dokuwiki, and hence of zim markup, so in _that_ file format, the conversion _should_ be done (see e.g. [the dokuwiki wiki](https://www.dokuwiki.org/wiki:syntax#text_to_html_conversions)

**Comment by gsantner** [comment]
In that case please create a new issue. This is why it's important to include all required details in bug reports. Didn't know its about Zim as not mentioned and no reply.
