### ISSUE TITLE
Slow file access/update file list

### ISSUE THREAD

**Issue by mhanser** [gsantner/markor#1120]
#### General information

* **App version: v2.4.0 (119)** 
* **System: Android 11 Security-Patch 11/2020, Google Play System-Update 09/2020**

#### Description
I am syncing a folder with around 650 Markdown-files in it. When I am switching between tabs in Markor (from QuickNote to files) it takes the file list a long time to update. This behaviour never gets better.

The files within the folder are synced with Syncthing. At the moment it is only synced between smartphone and computer.

I've noticed this change in behaviour some time after the upgrade to Android 11.

**Comment by gsantner** [comment]
Where do you store the files? What is the device and specs?

I have a new phone and Android 11 since yesterday, and I use Markor+Syncthing too..but so far didn't see performance issue.

**Comment by mhanser** [comment]
I am using a Google Pixel 3a. The other Syncthing clients are a Chromebook that uses Gallium OS and a old Notebook with Lubuntu 18.04.

I am using this configuration since May. The problems described started around the time I've updated to Android 11.

**Comment by gsantner** [comment]
Only Android device/OS is relevant

**Comment by mhanser** [comment]
The files are stored in a separate folder in storage/emulated/0 on my Google Pixel 3a with Android 11.

**Comment by gsantner** [comment]
OK, same situation than like me just different device.

How do you access the files, did some "Select storage" popup where you had to select mount folder? Or just normal file access by "Grant permission for files"

**Comment by mhanser** [comment]
Yes when I've configured Markor I have selected the folder in the settings menu. Then a system menu pops up where I can select the folder. File access ist already granted to Markor.

Maybe the problem is caused by something else because now I see that the file access feels also slower in the file Explorer.

**Comment by gsantner** [comment]
Ok, no SAF, direct file access I see (which should perform fastest)

**Comment by mhanser** [comment]
Other filemanager app (Solid Explorer).

While searching for solutions I've found an article https://www.reddit.com/r/androiddev/comments/ga5u72/saf_is_so_slow/ about changes in Android 11 regarding file access. I'm no Android programmer but ist sounds to me that it could have something to do with this problem.

**Comment by gsantner** [comment]
How you described me the access is traditional file access, not using saf. Yes SAF is painfully slow, thats why I tend to stay away from it as much possible on Markor.

**Comment by gsantner** [comment]
closing as not seems like markor can do something different for you
