### ISSUE TITLE
Markdown should consistently use '*' or '_' for bold and italics

### ISSUE THREAD

**Issue by harshad1** [gsantner/markor#1124]
Currently, we use '_' for italics, but '**' for bold. We should make these consistent.

Alternatively, we should allow the user to pick the character, similar to how we allow the user to pick the unordered list character.

**Comment by gsantner** [comment]
_ for italic and * for bold is just the most common in any markdown application. Also i.e. here on the github comment field::

![screenrecord](https://user-images.githubusercontent.com/6735650/98968061-80c30880-250d-11eb-9963-137383e558af.gif)

I don't see much off a reason to add additional settings option or action here, just bloat.
