### ISSUE TITLE
Feature request: non-standard links and image syntax

### ISSUE THREAD

**Issue by Igggr** [gsantner/markor#1127]
#### Is it possible to add such syntax for links and images?

[[ mylink | link_description]]
![[ myimage.png ]]

I know - it is not a standard one, but it will be nice to have. I plan to use markor to see my [obsidian](https://obsidian.md/) notes on phone - and almost all of them already have such non-standard links.

As I understand - "inject" options in the display setting - will be run **after** it is converted to HTML and it is too late to try to replace links here?

**Comment by gsantner** [comment]
Duplicate https://github.com/gsantner/markor/issues/860

What you do at javascript via injection is up to you, you have full access to the DOM/HTML
