### ISSUE TITLE
donated, but prompted to donate

### ISSUE THREAD

**Issue by underhandedness** [gsantner/markor#1132]
#### General information

* **App version: 2.4.0** 
* **System: pie** 

#### Description

I have zero gapps.  I donated via paypal.  As updates are installed from F-droid the app prompts to donate.  Is this intended behavior?

**Comment by gsantner** [comment]
First of all, thank you!

The info popup is there mainly as reminder "Hey, look, there are REAL people that take much of their lesure time to create this".  
It's NOT a in-app-purchase to unlock something, you don't get some extra features or something.

Yes it's intended that this reminder shows up roughly once a month, no worries - thank you for your support, and you can just press close.

PS: Markor nor any other of my apps track in app or on website what you do, so it would be anyway impossible to match whatever you do :D.
