### ISSUE TITLE
Add new preset color scheme

### ISSUE THREAD

**Issue by lokesh-krishna** [gsantner/markor#1133]
#### General information
Could you please consider adding the [Nord colour scheme](https://www.nordtheme.com/) as one of the preset color schemes?

#### Description
If you could tell me what colors need to be specified then I can list all the corresponding colour hex codes from Nord's [official documentation](https://www.nordtheme.com/docs/colors-and-palettes).

**Comment by gsantner** [comment]
Please paste me the 2 to 4 colors for it (Standard Foreground text color, Standard background text color - for dark and light mode respectiveley).

https://github.com/gsantner/markor/blob/master/app/src/main/res/values/colors.xml#L52

**Comment by lokesh-krishna** [comment]
Made a PR: #1134.
