### ISSUE TITLE
Allow manually specifying hex code of color in color selection

### ISSUE THREAD

**Issue by lokesh-krishna** [gsantner/markor#1136]
#### Description
Presently, the user is allowed to pick colors for BG and FG using a color wheel. While this is handy when exploring new colors, this is actually hard to use when the user already has a specific hex code in mind and would just like to enter it

**Comment by gsantner** [comment]
Might be the picker supports it as-is , just  not enabled

**Comment by lokesh-krishna** [comment]
Could you please consider enabling it then?

**Comment by botingzhang** [comment]
Did the color picker go away entirely? I saw earlier documentation from v1.5 that suggested there's a way to pick FG and BG colors here ...
![Screenshot_20210816-113654](https://user-images.githubusercontent.com/32554567/129614332-ba4052b9-de90-4b41-a24e-e3d184b6f8bf.jpg)

**Comment by gsantner** [comment]
This option is at Editor settings.

**Comment by botingzhang** [comment]
Sorry to be a dunce, but could you point out where? Thanks!

![Screenshot_2021-08-16-12-56-12](https://user-images.githubusercontent.com/32554567/129627307-0d4b79cb-9cc8-44e7-8cea-d157fdc4e837.jpg)

**Comment by botingzhang** [comment]
Never mind I found it!!! Sorry to be lame-o!!

**Comment by gsantner** [comment]
My view of the situation: You unlikely choose something wild like pink or green. but some shadow of black/grey/white/darkblue mostly. For this, color wheels are not precise enough usually. 

For normal users, there are predefined themes that should work fine, and for more experienced users that want custom colors, they can enter hexcodes. Thus the new way will be just a input for hexcolor. 

#1428 is exactly that and good described, so closing this issue in favor of it.
