### ISSUE TITLE
ShareInto Markor:: Allow to select folder for new file

### ISSUE THREAD

**Issue by aisbergde** [gsantner/markor#1138]
#### General information

* **App version:**  
2.4.0 (119)
* **System:**  
Android 10, MIUI Global 11.0.9, stabil, für Poco 
Markor settings to open multiple instances

#### Description
- try to share from a Webbrowser to markor  
created link is shown
- select target 'create new file'
- if you only enter the name of the file all works fine
- but if you click on the "Folder" / "Ordner" button then the process stoppers and Markor disappears

**Comment by gsantner** [comment]
Folder is supposed to be disabled here.
