### ISSUE TITLE
add directory tree menu on the sidebar

### ISSUE THREAD

**Issue by darkkingredian** [gsantner/markor#1141]
let's say you are editing folder1>another folder>another another folder>note.md
now you want to edit folder2>another folder>another another folder>note2.md
so you have to go back several folders and go into that note
but if you have a sidebar listing all the files and folders then you can just click that specific note

sort of like this
![filetree](https://i.imgur.com/4xknLmb.png)

**Comment by gsantner** [comment]
as much as I would like it to be, and to have a 20"+ monitor in my pockets - it's not possible. And for phones, which is the 99% use case of Markor, barley a filename (current folder / hierachy 1) fits from width perspective.    
Closing as won't fix as theres no proper option to add this from use perspective, in any way it would be disgusting to use.
