### ISSUE TITLE
File explorer: Parse title from textfiles

### ISSUE THREAD

**Issue by fullcavediver** [gsantner/markor#1142]
#### General information

* **App version: 2.4.0** 
* **System: Android** 

#### Description

I use markor as a viewer and editor for the local wiki.js knowledge database. The presentation of the documents below 200 kB is error-free.

wiki.js and other markdown applications like to create header information, such as:

```
---
title:
description:
published:
date:
tags: 
editor:
dateCreated:
---
```
Would it be possible to use this information and show the title from header information instead of filename, if this record is present in the header?

Thanks a lot!

**Comment by gsantner** [comment]
in file explorer or really on document editor/viewer?

**Comment by fullcavediver** [comment]
I thought of the explorer - the title "Docker Installation" instead of "docker-installation.md", but the showing in the dokument is of course also a nice function. Is it possible to change the font size of the title via Inject -> head?

**Comment by gsantner** [comment]
Then the answer is no, sorry.
Reading line-by-line every single file always in the file browser would make it unusable for most people. Some devices and storage devices (ie sd) partially take like 1 second to even load one single file.
