### ISSUE TITLE
Add Zettelkasten template/sample

### ISSUE THREAD

**Issue by einverne** [gsantner/markor#1143]
#### General information

* **App version:** 2.4.0 Play Store
* **System:** Android 10

#### Description
I've noticed that Markor already has a lot of built-in templates support. But for me, I usually create a new file with the name start with `YYYYMMDDHHmm`, such as 20201205133000，and then append the file name.

But for now, I have to input the prefix on my own. If there is an option to custom the default file name, it will be much easy to use.

I have checked the code if it is acceptable, I'd like to open a PR.

**Comment by gsantner** [comment]
I don't use Zettelkasten, however maybe the Hugo or Jekyll one fit? Please try both, they have dynamic timestamp in it.

Otherwise, please create such a file on your own in the samples directory. Requirement: Public Domain /CC0 license. So people don' have to worry about license when they create a dumb file :D.

**Comment by shanvrolijk** [comment]
I very much like this idea. I use a lot of templates. And allowing users to make their own template will help tremendously.

**Comment by gsantner** [comment]
Fully custom template is other task, and as notes there. you can also just write the file somewhere and use the >>Import<< option.

**Comment by einverne** [comment]
> Fully custom template is other task, and as notes there. you can also just write the file somewhere and use the >>Import<< option.

Fully custom template is another heavy feature. For now, when I use my PC, I use Obsidian to create new notes. In Obsidian, it is very easy to set a custom template for a new post, so it becomes very easy to create a note, just hit a shortcut like ctrl+n. And Obsidian can even set the custom note name, as I mentioned, I often use `YYYYMMDDHHmm` patten.

**Comment by gsantner** [comment]
@einverne 
Do you think makes sense to list Markor at that list?
https://zettelkasten.de/tools/

**Comment by einverne** [comment]
In my opinion, Zettelkasten is a method to take notes. Markor is really a great tool to implement the method on the Android platform. Markor is just a simple markdown editor so it is flexible to use in any note-taking method.
