### ISSUE TITLE
View/Edit-Mode switch changes cursor position

### ISSUE THREAD

**Issue by mezysinc** [gsantner/markor#1149]
#### General information

* **App version:2.4.0
* **System: 

#### Description

After going back from View Mode to Edit, Markor goes to the beginning of the text and not to the same text section that was being worked on in Edit mode.

#### How to reproduce
1. open some long text file in edit mode, go to the middle
2. switch to view mode
3. you're now at the beginning of the text
4. switch back to edit mode
5. you're back at the section that you were editing

**Comment by gsantner** [comment]
needs check, might be introduced by recent changes. definetley was working before as expeced.

**Comment by mezysinc** [comment]
It looks like in 2.4.1 it still only remembers positions for each view separately
