### ISSUE TITLE
Undo / Redo only updates 1 character at a time.

### ISSUE THREAD

**Issue by harshad1** [gsantner/markor#1150]
Undo / redo only updates one character at a time. It can be tedious to undo / redo changes because of this.

In addition, several processes such as indenting / de-indenting text and renumbering a list result are not undone / re-done as one operation. Rather each individual sub-step is recorded.

**Comment by harshad1** [comment]
To solve this we need 2 things, IMO:

1. Time or word based 'chunking' of undo/redo (I feel we used to have this at one stage)
2. Disable undo / redo recording around `regexReplaceAction` and `renumberOrderedList`

**Comment by gsantner** [comment]
it can be multiple ones when i.e. bigger chunck has been selected and "back" pressed.

Btw, time based chuncking was the first self-made implementation by me. Due memory limtations on certain devices it was required to use the common class that is in use now.

**Comment by harshad1** [comment]
I see.

I can try to work on (2).

**Comment by gsantner** [comment]
Up to you if you want to.  
I don't see a high need or priority
