### ISSUE TITLE
Improve Markdown Latex/KaTex/Math when used with complex formulas

### ISSUE THREAD

**Issue by dhdgves** [gsantner/markor#1154]
Such as "$$ \left. \begin{array}{ll} \frac{\partial \sigma_p}{\partial \rho} + \frac{1}{\rho} \frac{\partial \tau_{\rho \varphi}}{\partial \varphi} + \frac{\sigma_\rho - \sigma_\varphi}{\rho} + f_\rho = 0 & \ \frac{1}{\rho}\frac{\partial \sigma_\varphi}{\partial \varphi} + \frac{\partial \tau_{\rho \varphi}}{\partial \rho} + \frac{2\tau_{\rho \varphi}}{\rho} + f_\varphi = 0 & \ \end{array} \right} $$"
I am sure this formula is in correct format. I can see my formula display well in Typora.

**Comment by gsantner** [comment]
I pasted the $$ xyz $$ from above into other editors/demo sites that use MathJax. Does not show anything either there.

Not sure if paste error on your or my side, your formula is just wrong, formula is incompatible.

Please upload textfile (/.txt) in question to here.
