### ISSUE TITLE
Follow links to headings

### ISSUE THREAD

**Issue by mrpurplecloud** [gsantner/markor#1163]
#### General information

* **App version:** 2.4.0
* **System:** Android 9.0

#### Description
I use Obsidian as my bi-directional note-taking software on PC. It uses links to headings (both internal and cross-file) to implement bi-directional note references. It'd be nice if Markor could support following links to headings (in View mode), like 
```
[topic](filename.md#heading)
```
or make it an option in settings for user to choose. This way Markor could serve as a unique bi-directional note-taking mobile client! 

Supporting Obsidian specific wiki link syntax [[ ]] would be even better, but I suppose that's a much bigger decision to make.

**Comment by gsantner** [comment]
#865 , #912
