### ISSUE TITLE
no context menu on long press on file, can't mark a file as favorite

### ISSUE THREAD

**Issue by aisbergde** [gsantner/markor#1164]
#### General information

In the past I was able to mark files as favorites. I don't remember how I did but I have some files marked as favorite. Currently I can't find a way to mark a file as favorite. 

I searched the FAQ and I found here
https://gsantner.net/blog/2019/05/06/markor-v1.8-file-navigation-favourites-markdown-editor.html

>Favourites
>Add any file or folder to your favourites! Long press a file/folder and tap the star button to add to or remove from favourites.

But when I long press a file or folder then nothing happens, only a short tactile feedback. No menu.

* **App version:**
2.4.0 (119) Google Play Store

* **System:** 
Android 10
MIUI global 11.0.9
Pocophone F1 with original OS

**Comment by gsantner** [comment]
Tried it, still works fine.

No popup. Favourite/Star appears in top toolbar on selection.

**Comment by aisbergde** [comment]
I restarted Android. Now it works. Looks like I should restart Android more often🤔
