### ISSUE TITLE
Exiting a file should not change folder

### ISSUE THREAD

**Issue by chtixof** [gsantner/markor#1165]
#### General information

* **App version:** 2.4.1 (120)
* **System:** Android 10

#### Description

Steps to reproduce:

- create a folder md in the markor folder
- in this folder, create a file test.md
- type some text in it
- exit the file

Result: you land back in the markor folder, not the md folder where the test.md file is. We should get in the md folder, where the file is.

Thanks for your work!

**Comment by gsantner** [comment]
Please test with v2.5.0. I tried right now, same scenario and I got sent back to the correct folder.

**Comment by chtixof** [comment]
Hello. As version 2.5 is not on FDroid, I reinstalled from GPlay. Same behaviour. Screen record attached.

https://user-images.githubusercontent.com/9341373/102756641-81eb1f00-4370-11eb-9faa-6c4fb54efedb.mp4

**Comment by gsantner** [comment]
You use the applications/toolbar Home button, it's correct behaviour to go to initial state here.

To go back to previous folder use your normal back button on the bottom (or the back gesture on newer android version).

**Comment by gsantner** [comment]
#949

**Comment by chtixof** [comment]
Thanks Gregor for your answer.
I was mislead by the back arrow acting as a Home button. ;)

**Comment by chtixof** [comment]
When there are 2 files in a subfolder, if a md link sends from one to the other, then the back button sends back to the first file and there is no way to get back to the subfolder from the second file. Have to go through the first file ir the root folder. Indeed, the back arrow of the top left when on a md file should send back to the folder containing the md file, not to the root Markor folder. Could even replace the back arrow by a folder. 😉

**Comment by gsantner** [comment]
I might replace the icon with a "home" icon then it is clear and more expectable what it's function.

**Comment by gsantner** [comment]
I might replace the icon with a "home" icon. Then it is clear and understandable what it does.

**Comment by pgorod** [comment]
This totally gets me, also. The arrow feels like a back button, and actually, I'd prefer it to be one. I don't miss the Home button that much, but I do expect to find an obvious way to exit a document.

I also feel that in terms of usability, when I'm pressing buttons and doing stuff on screen, having a button that does what I want to do next (exit document) is somewhat better than having the "Back" android gesture. It's just less intuitive at that moment, thinking "you can't find a button, but remember there's a generic gesture that works well here" is too much to demand from my feeble brain, on most days. 😛

**Comment by pgorod** [comment]
> I might replace the icon with a "home" icon. Then it is clear and understandable what it does.

just as a reinforcement, I think this is a good idea. The current left-arrow icon is used in tons of places in Android, in that very position (top-left of the screen) for the **Back** action. Even Markor uses it in the Settings. 

That's another reason for what I wrote above, to make sure that there is a left-arrow button there, which does what is expected (**Back**), and eventually add a second button that is a **Home** icon and takes us to the **Home** folder. 

Thanks

**Comment by chtixof** [comment]
Thanks for the new version including the "back arrow" feature 👍
