### ISSUE TITLE
Insertion of a date removes the keyboard

### ISSUE THREAD

**Issue by chtixof** [gsantner/markor#1166]
#### General information

* **App version:** 2.5
* **System:** Android 10

#### Description
Steps to reproduce:
- open a md file in change mode ; this makes the keyboard appear
- insert a date via the button on the bottom ribbon ; this makes the keyboard disappear

The behaviour is different with the other buttons like the Bold button, which preserve the keyboard, which is more convenient.

Thanks.

**Comment by gsantner** [comment]
The dialog requires much screen space, think especially about small screen devices - hence keyboard hidden. Bold does not have any dialog or anything.

**Comment by chtixof** [comment]
Understand the need of the dialog  box for the date. But when the dialog box is closed, it would be more ergonomic to get back to the previous state of the keyboard, on or off. However, it is a "nice to have". This date feature enables the use of Markor  as a diary. Worth to mention on the description of the app, for the search engines ;)

**Comment by gsantner** [comment]
Diary: Yeah, I use especially the bottom most format template for this ;).

If you have some specfic sentence in mind for Markor website just write it here.

Virtual keyboard on/off/position is often tricky - often its offscreen or inserts at wrong cursor. So I rather keep it as is :D.

**Comment by chtixof** [comment]
I well understand. Also, it's a temptation to add more and more features. But be scarce not to destroy one of the main features of Markor: its simplicity.

Suggestion for the text:
📅 Click-button insert of a date and time can turn a file into a simple and versatile diary

**Comment by gsantner** [comment]
Long press date button to use last used format
