### ISSUE TITLE
Abstract markdown highlighting, allow to switch between highlighters

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#117]
### General information

* **App version:** v0.2.1

#### Steps to reproduce
Currently the `HighlightingEditor` has everything in it for highlighting markdown. This makes switchting between different highlighting impossible. Currently it's planned to switch between 

* Markdown (current)
* Plain (basically no highlighting) (to be implemented later, seperatly)
* Todo.txt (highlights `@tag`, `+context`)   (to be implemented later, seperatly)

Later there may be then a toolbar-menu-option to switch between these highlighting modes.

#### Expected result
The target is to make highlighting settable, so e.g. a call like `editor.setHightlightingMode(Mode.Markdown)` / `editor.setHightlightingMode(new MarkdownHighlighterMarkdown(params))` possible. Therefore HighlightingEditor itself should not be aware of any Markdown related stuff than anymore, highlighting should be provided by the setted highlighter then.

**Comment by gsantner** [comment]
@sjmduncan Do you think this would be a lot / hard work?

**Comment by sjmduncan** [comment]
It shouldn't be too difficult:

1. Make the `Highlighter` class abstract put the current code in a `HighlighterMarkdown` implementation
2. Move the code for auto-indent and auto-populating list item prefixes to the HighlighterMarkdown class

A lot of it is already pretty well contained, the rest should be fairly straightforward to move to the right places.

I'll have some time for this next week if nobody is planning to tackle it already.

**Comment by gsantner** [comment]
great! 

In general my plan is to do this for shortcuts (done), highlighter and parser. I will then introduce then a DocumentFormat option in Documrnt, and according to this Editor will switch accordingly. E.g. at filesystem-fragment I think of adding at ContextMenu -> Edit as Markdown, Edit as Plain

**Comment by sjmduncan** [comment]
This is already implemented separately - it's handled by `IndentationFilter` which is a child class of `HighlightingEditor`, while 'Highlighter' does the actual highlighting.

Keeping them separate would be fine, provided we use the same patterns for matching and the applied actions to avoid the current situation where the same patterns are defined twice in different places and in different forms.

**Comment by gsantner** [comment]
> This is already implemented separately - it's handled by IndentationFilter which is a child class of HighlightingEditor, while 'Highlighter' does the actual highlighting.

👍 

> Keeping them separate would be fine, provided we use the same patterns for matching and the applied actions to avoid the current situation where the same patterns are defined twice in different places and in different forms.

Agreeing too

**Comment by sjmduncan** [comment]
I finally found some time for this.

There's no markdown-specific stuff in `Highlighter` or `HighlightingEditor` (except that 'Highligher.getDefaultHighlighter()' returns an instance of `MarkdownHighlighter`)

Auto-format ('applied actions') uses the same patterns used by the highlighter.

They can be enabled/disabled independantly, and you can provide whatever implementation of `InputFilter` you want for auto-formatting.

There is no PR yet (it's on my forks `highlighter-abstraction` branch) because I want to tidy up the highlighter implementation a bit so that there's a nice example for whoever ends up adding highlighting for other formats.

**Comment by gsantner** [comment]
my plan is for now to just add Plain as other option, which is basically a empty implemented interface/ class :D

If you want to include such a switcher too you can do that too (DocumentEditFragment).  Otherwise if theres something available `_highlighteditor.setHighliter(new PlainHighlighter/MarkdownHighlighter);`  i can do that after PR too

**Comment by gsantner** [comment]
btw, have you received my mail, or did I sent to the wrong one?

**Comment by gsantner** [comment]
shall i merge the branch to an seperate branch on this repo?

**Comment by sjmduncan** [comment]
> just add Plain as other option

This could be done just by disabling the highlighter and auto-formatter.

I'll make a PR, since the abstraction part is pretty much done. I just wasn't sure about exactly how the highlighter and the auto-formatter should work  together, but that part is just picking combinations of `[enable/disable/set]Highligher` and `[set/remove]AutoFormat`

**Comment by gsantner** [comment]
Switchting via toolbar option, and alternative textformat - plaintext - is implemented now.

**Comment by gsantner** [comment]
@sjmduncan I worked **a lot** these days on Markor. Related to abstracting, I invested much time to get it in both, good state of abstraction and for a easy way to add new formats, by generalizing common used things across highlighters/converters/actions. Tell me how you like it, and if you see some improvement ideas if you want :).
