### ISSUE TITLE
Markdown: Emoji + digit bug (:smiley:1)

### ISSUE THREAD

**Issue by mberend** [gsantner/markor#1170]
When you use for example:
`:smiley:1` it does not show an emoji. When you change it to `:smiley:-1` then it works. The bug is only for digits.

**Comment by gsantner** [comment]
This is about Markdown right? I didn't even know this is possible and valid. Any way, Markor uses flexmark Markdown parser so you have to ask there. https://github.com/vsch/flexmark-java/wiki
