### ISSUE TITLE
Privacy feature: Disallow screenshots (Secure flag)

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#1174]
#### General information

* **App version:**  2.5
* **System:** Android 11

#### Description
* The goal is to add feature to app to disallow screenshots of the running Markor app (so other apps cannot screenshot or see what you write).
* Should be a settings option to enable/disable globally for all activities in the Markor app
* Make it enabled by default
* Optionally, if you find some other security/privacy improvements&tweaks, can also be added (comment if you have something)

Check documentation for FLAG_SECURE and related Android Developers security/privacy guides.  
Overall it should be quite easy to implement this, settings are more or less copy paste from existing checkboxes 😉 .

**Comment by Ln11211** [comment]
@gsantner, As it reads good first issue and you said it's more or less copy paste, canI try this ?

**Comment by gsantner** [comment]
Yes it is one of the easiest.

**Comment by detherminal** [comment]
Hello. I want to make this. How can I give you the answer

**Comment by gsantner** [comment]
Merge/Pull request.

**Comment by Ln11211** [comment]
@gsantner , I found a nice resource and it says that you can use a built in [mechanism](https://medium.com/nomtek/screenshot-preventing-on-mobile-apps-9e62f51643e9) to prevent screenshots. Check out the link and let me know if we can use this to implement it.

I also found one in [stackoverflow](https://stackoverflow.com/questions/9822076/how-do-i-prevent-android-taking-a-screenshot-when-my-app-goes-to-the-background) that prevents taking screenshot when an app goes to background.. 

But, this one from geeksforgeeks seems good and simple, [geeksforgeeks](https://www.geeksforgeeks.org/how-to-prevent-screenshot-or-screen-recorder-in-android/) . 

I would like to go with the code by geeksforgeeks...

**Comment by gsantner** [comment]
yes java FLAG_SECURE is what you need.

**Comment by Ln11211** [comment]
@gsantner , I don't think I can do this issue as I lack the knowledge of working with android code, I'm sorry for wasting your time.

**Comment by gsantner** [comment]
No worries.

By the way, it's never too late to get started :-)

**Comment by gsantner** [comment]
do it

**Comment by gsantner** [comment]
@Zoo-M0    
It happens every year in october (/hacktoberfest) that many people want to start on many things, but mostly nothing happens.  
Unless there is merge request open, generally consider all issues/bugs/features open. Currently there are 0 open ... so everything 😄 .

**Comment by Zoo-M0** [comment]
@gsantner perfect, I will look into it
