### ISSUE TITLE
Compatible File Manager

### ISSUE THREAD

**Issue by anishmittal2020** [gsantner/markor#1175]
#### General information

* **App version:** 2.5.0
* **System:**  Android 10

#### Description

Can you please tell us which file managers are compatible with Markor? I use the open sourced Material Files, but I can't open it as it says that Markor does not supports filemanagers that do not provide full path.

Could you please provide some examples of File managers that are compatible with Markor?

**Comment by gsantner** [comment]
Simple File Manager for example https://www.simplemobiletools.com/filemanager/ .

I tried about 15 in the past when it got supported and all worked, but times change fast - try others on your own. Please send pull request if you can fix something.

**Comment by anishmittal2020** [comment]
@gsantner Could you please read the comment for you from the creatorof Material Files file manager: https://github.com/zhanghai/MaterialFiles/issues/573#issuecomment-1110475817

**Comment by hiqua** [comment]
@gsantner do you know if the default "Files by Google" app is supposed to work? I guess it's a pretty big one and it doesn't work on my phone.

**Comment by gsantner** [comment]
With improvements in Markor 2.10.1, all file manager apps (~15) I tried/downloaded, worked with opening textfile in Markor.

Yes including Google Files, AOSP/"Documents"/Normal Android file manager, Material Files,...
