### ISSUE TITLE
todo.txt: sort by due date

### ISSUE THREAD

**Issue by reini-1** [gsantner/markor#1178]
#### Description

It would be fine, if tasks could be sorted by custom tag `due:` and if there would be a possibility to sort by multiple items e.g. first by due than by priority than by context and so on.
Maybe define one or more custom sort orders in settings or a redesign of sort dialog ...

**Comment by gsantner** [comment]
Sort by due date is already there in the latest app release. Just scroll down in the list of sort options.

Bloating the sort menu with more advanced options is not in plan.
