### ISSUE TITLE
Hide sync folders

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#118]
dialog has

* .stversions
* .stfolder
* .sync

**Comment by sjmduncan** [comment]
Also `.sync` for Resilio

Is there a reason to show any hidden stuff (i.e. anything that starts with `.`)?

**Comment by gsantner** [comment]
in the normal browser this stuff is already not shown, this is about the import/select dialog.

Yep, for import showing hidden too makes sense

**Comment by gsantner** [comment]
I rethought on it, I think it's best to make no restriction at import at all, an unfiltered file-selection-dialog
