### ISSUE TITLE
Nord theme?

### ISSUE THREAD

**Issue by maheshsundaram** [gsantner/markor#1180]
#### General information

* **App version:** 2.5.0 F-Droid and Google Play
* **System:** Android 9, moto g 6

#### Description

I saw that in the latest release notes that there is a Nord theme, however after updating I see only the dark and light themes available. Perhaps I am misunderstanding?

![Screenshot_20201231-143258](https://user-images.githubusercontent.com/9041312/103432607-d61eac00-4b85-11eb-815c-deb8003a7076.png)

#### Log

Let me know if you think a log would be useful here, and thank you and all the contributors for your work on this app - I spend most of the time on my phone using it!

**Comment by gsantner** [comment]
nord is a editor only theme (Editor settings -> Basic colors), and it is there in release.

**Comment by maheshsundaram** [comment]
Hi @gsantner Thank you, I found it under 

Settings -> Other -> Basic color scheme

I see, now I understand. Thank you
