### ISSUE TITLE
zim: format not detected

### ISSUE THREAD

**Issue by treborxy** [gsantner/markor#1182]
Hello everyone,
it's great news Markor is supporting zim - could become an invinceable team - thank you! :-)
Right now I found an issue (where I can't tell if its my fault or a bug)

#### General information

* **App version: 2.5.0 (121) F-Droid** 
* **S7 lineageos 10 (20201211):** 

#### Description
A synced zim file is not recognized as zim-format automatically. It is possible to have it rendered correctly by per-file-settings.
Here the header and start of the zim-file:
```
Content-Type: text/x-zim-wiki
Wiki-Format: zim 0.6
Creation-Date: 2021-01-02T11:10:32+01:00

====== Synctest ======
Angelegt Samstag 02 Januar 2021

Hier werden Tests zur Synchronisierung mit Rasp und Android-Devices durchgeführt.
```

**Comment by gsantner** [comment]
probably something not as expected with the file heading at recognition..or ie file endings.

@fredericjacob

**Comment by gsantner** [comment]
anyway, you can select the zim format manually in the toolbar menu

**Comment by fredericjacob** [comment]
Hi @treborxy, nice to hear that you enjoy it so far.
The header looks fine for me, as well as the rest of the syntax.
The file ending has to be .txt so that it is automatically recognized as a Zim file - is this the case?
If yes, it seems to be a bug. In this case, I suppose there could be a problem with the line endings or some invisible control characters which cannot be matched as the header. How do you sync the files? And do they come from Windows, Mac or Linux?
Could you also upload the complete text file so that we can reproduce the issue? (Ideally, directly from your phone to make sure that no line endings are changed during sync.)

**Comment by treborxy** [comment]
Yes of course - see file attached

Am 3. Januar 2021 02:45:14 schrieb fredericjacob <notifications@github.com>:
>
> Hi @treborxy, nice to hear that you enjoy it so far.
> The header looks fine for me, as well as the rest of the syntax.
> The file ending has to be .txt so that it is automatically recognized as a 
> Zim file - is this the case?
> If yes, it seems to be a bug. In this case, I suppose there could be a 
> problem with the line endings or some invisible control characters which 
> cannot be matched as the header. How do you sync the files? And do they 
> come from Windows, Mac or Linux?
> Could you also upload the complete text file so that we can reproduce the 
> issue? (Ideally, directly from your phone to make sure that no line endings 
> are changed during sync.)—
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.


Content-Type: text/x-zim-wiki
Wiki-Format: zim 0.6
Creation-Date: 2021-01-02T11:13:10+01:00

====== ToDoSync ======
Angelegt Samstag 02 Januar 2021

[ ] [[../Synctest.txt|Test]] absolvieren
[>] mit 644 - Rechten wird in Markor zim nicht erkannt
[>]  mit 660 - Rechten wird in Markor zim nicht erkannt
[>] ohne space bzw _  im Dateinamen wird in Markor zim nicht erkannt
[>] hängt die Erkennung von der Codierung ab? Nein, alles utf8
[ ] hängt die Erkennung von Steuerzeichen am Zeilenende ab?

**Comment by gsantner** [comment]
the file starts with todo and ends with .txt. this automatically makes it todo.txt format. So unrelated to anything with Zim code. Use a different filename at start for example (to-dosync.txt ie).
