### ISSUE TITLE
Add launcher shortcut for "Share into" (similar to widget + button)

### ISSUE THREAD

**Issue by kankaristo** [gsantner/markor#1184]
I've been using Markor for just a few days, but I like it a lot, thanks for making it!

One thing that I haven't found is a fast way to "capture" a thought: write down a few words as fast as possible.

The "plus" button ("Share into") in Markor's widget does basically what I want, but I'd like to have **only that** as a standalone button, not the whole widget with the file listing and other buttons.

A single button could also be added to the main app row (the one visible on all home screen tabs/pages).

Ideally, there would be separate widgets/buttons for "Add to To-Do" and "Add to QuickNote", so that you wouldn't accidentally select the wrong one (like I've done a couple of times with the current "Share into").

Trello's Android app has a similar button to create a new card, and it's become invaluable in my (GTD) workflow. It would be great to have something similar in Markor!

**Comment by gsantner** [comment]
Hm, what do you think of a seperate launcher shortcut for that. Similar you can enable launchers for todo & quicknote. What you ask for not sounds much like a widget, but a simple launcher & starter.

**Comment by kankaristo** [comment]
The Trello "Add a card" button is a 1x1 widget, but a launcher might make more sense.

**Comment by kankaristo** [comment]
That was fast, thanks! Any idea when v2.6 is coming to Google Play? Is there a beta program I could join?

**Comment by gsantner** [comment]
No ETA, it's ready when it's ready. Usually end of of month.

**Comment by gsantner** [comment]
No ETA, it's ready when it's ready. Releases usually are end of of month.

2.5.1 / 2.5.2 / 2.6.1 are on F-Droid, which is the main distribution channel of Markor currently.
