### ISSUE TITLE
zim: edit-mode textaction - link insert 

### ISSUE THREAD

**Issue by treborxy** [gsantner/markor#1186]
#### General information

* **App version: 2.5.0** 

#### Description
Links inserted by Markor tool-menue are html-style, not zim-style. This is ok within Markor, but does not render well in zim

Link given by Markor tool-menue:
``
<a href='Synctest.txt'>Link zu Synctest.txt</a>
``

Link given ZIM style:
``
[[./Synctest.txt|Link zu Synctest.txt]] 
``

**Comment by gsantner** [comment]
already known.

**Comment by treborxy** [comment]
Sorry for bumping - did not see it beeing listed

**Comment by gsantner** [comment]
@fredericjacob  's Zim #1098

**Comment by fredericjacob** [comment]
@gsantner Can you assign me this issue? I've started working on this in #1195.
