### ISSUE TITLE
Issue with paths saving on external sdcard

### ISSUE THREAD

**Issue by TheBattleWolf** [gsantner/markor#1188]
#### General information

* **App version:** 
2.5.0 F-Droid
* **System:** 
LineageOS, Android 10, Redmi Note 8T
#### Description
Select a directory in on your sdcard e.g. `/storage/ABCD-1234/new/directory` and set it as your notebook. If you now create a note, it saves your file to `/storage/ABCD-1234/new/directory/new/directory` if you enter that directory and create a note, it saves it to `/storage/ABCD-1234/new/directory/new/directory/new/directory` and so on.

**Comment by gsantner** [comment]
please check open issues.

#603
