### ISSUE TITLE
Table of Contents - missing headings

### ISSUE THREAD

**Issue by radanovicnik** [gsantner/markor#1189]
#### General information

* **App version:** 2.5.0 (121) Google Play
* **System:** Android 10

#### Description

Only headings `h2` and `h3` show up in automatically generated table of contents (`[TOC]`).
It's different from desktop editors which put all heading levels in.

This forces you to use only those 2 heading levels instead of the full range (`h1`-`h6`) if you want your files to be displayed consistently.

[Example](https://user-images.githubusercontent.com/70813474/104121505-0c56eb00-533f-11eb-953c-0dcc7f283052.jpg)

**Comment by gsantner** [comment]
You usually have, or should have only one h1 - the title of the file/document. Which not needs to be indexed as its right there on the beginning.

**Comment by gsantner** [comment]
Configuration of "Table of Contents" is **only** done when you enable it in settings. You don't have in this case, so you just get what is the default configuration of the markdown parsers TOC.

Markors configuration also has h1 enabled - so just enable TOC in app settings and remove [TOC] in your file.
