### ISSUE TITLE
KaTeX line break not working

### ISSUE THREAD

**Issue by radanovicnik** [gsantner/markor#1190]
#### General information

* **App version:** 2.5.0 (121) Google Play
* **System:** Android 10

#### Description

`\\` in math blocks just escapes the `\` instead of creating a line break, as is supposed to happen with KaTeX:

https://katex.org/docs/supported.html#line-breaks

This forces you to write `\newline` for breaking lines, which is (longer and) not compatible with editors that use MathJax for rendering.

[Example](https://user-images.githubusercontent.com/70813474/104121656-38bf3700-5340-11eb-8aab-5231fb8443e5.jpg)

**Comment by gsantner** [comment]
MathJax and KaTex are similar but not the same, and you just found a difference. Given KaTex does it this way and MathJax not it is just like that - Markor has KaTex and you have to use it's syntax. This not sounds like any bug report bug a finding/statement...

**Comment by radanovicnik** [comment]
Sorry, I explained it badly.
KaTeX does support `\\` for line break, it says so in the docs (link above).

For example, `\\` works in StackEdit, which also uses KaTeX.

`\\` just doesn't seem to work in Markor for some reason.
