### ISSUE TITLE
Color picker does not show

### ISSUE THREAD

**Issue by Gennadiyev** [gsantner/markor#1191]
#### General information

* **App version:** 2.5.0 Google Play
* **System:** Android 11, HUAWEI Matepad Pro

#### Description

The color picker never appears on the *Link color* color selection dialog.

Specifically, both sliders work, but the below part is empty (and not responding to touches), whether the device is vertically- or horizontally-held.

![Screenshot_20210111_142653_net.gsantner.markor.jpg](https://i.loli.net/2021/01/11/hguHqeS4EmWwc3R.jpg)

From my perspectives, #1136 is a good workaround.

**Comment by gsantner** [comment]
can you add a debug log? appears fine here.

**Comment by gsantner** [comment]
No response, I cannot reproduce and haven't seen any other case yet. closing
