### ISSUE TITLE
Content deformed while editing file in SDCard

### ISSUE THREAD

**Issue by oddleaf** [gsantner/markor#1192]
#### General information

* **App version: 2.5.0 Google Play** 
* **System: 6.0.1, Samsung J2 Prime (SM-G532G/DS)** 

#### Description

Content deformed while editing file in SDCard. (Editing file in internal storage is just OK)

Seems to be the issue occurs after deleting content in a file then saving it. While adding content without removing anything seems to produce expected result.

I tested it on a Markdown file, but similar issue seems to occur also on another filetypes.

If it could be your reference... I experience this issue since v2.3.2 (but I didn't get enough time to report it. So I just reinstalled last 'stable' version I have, v2.2.8 from my backup).

#### How to reproduce

1. Create new file and write:

```
hello
world
```

2. Reopen, then edit to:

```
hello
foo
```

3. Reopen, but I get:

```
hello
foo
d
```

4. Edit it to:

```
hello
```

5. Reopen, but I get:

```
hello
foo
d
```

6. Edit it to:

```
a
```

7. Reopen, then I get:

```
a
llo
foo
d
```

8. Edit it to:

```
a
hello
foo
d
```

9. Reopen, (it shows the same as in 8, which is an expected result) then continue editing to:

```
hello
foo
d
```

10. Reopen, then I get:

```
hello
foo
d
d
```

**Comment by gsantner** [comment]
do you give it some time between edits? like wait 2 seconds before reopen?

SD Card I/O on Android usually is slow like snail.

**Comment by oddleaf** [comment]
Tried just now, I also clicked save and waited for some seconds before each operation to be sure. But it didn't fix.

**Comment by oddleaf** [comment]
I retested it by editing a file and keeping it open. To monitor any change, after I click save then I read the file through http server from another device.

I think I got some pattern:

1. Create new file, write and save:

```
hello
world
```

Result:

```
hello
world\n
```

2. Without reopen, edit to and save:

```
hello
foo
```

Result:

```
hello
foo
d\n
```

It seems like... `world` (5 chars) replaced by `foo` (3) resulting into `foo\nd` (5).

`\n` after `foo` seems to be caused by Markor added a newline to EOF if none of it, which is normal. But the problem is the remaining `d`, it looks like residue in a buffer?

Though, there's also another `\n` after `d`. I don't know how to explain that. (Sorry, I don't read the source code yet) but I assume that `\n` **before** `d` is a replacement that applied in buffer, while `\n` **after** `d` is the real EOF terminator applied when saving the file.


Other test results with a `\n` in EOF ignored:

* `hello world` ✕ `hello wor` = `hello wor\nd`
* `hello world` ✕ `hello rld` = `hello rld\nd`
* `hello rld\nd` ✕ `hello ld` = `hello ld\n\nd`
* `hello ld\n\nd` ✕ `hello ld123` = `hello ld123`

**Comment by gsantner** [comment]
not sure how exactly that could happen, we get the edited text as a string and write that to disk. No delta applied or something similar.

**Comment by oddleaf** [comment]
Hmmm, I see. Or probably SAF didn't truncate the file properly?

**Comment by oddleaf** [comment]
Seems to be mode `"rw"` in `net.gsantner.opoc.util.ShareUtil.writeFile` line `1151` is the cause:

`pfd = _context.getContentResolver().openFileDescriptor(dof.getUri(), "rw");`

It needs to be `"rwt"`, `"t"` for truncate. Please give it a try (I don't have a supported environtment to try it).

**Comment by gsantner** [comment]
you can download test apk here when finished

https://github.com/gsantner/markor/actions/runs/484829208

**Comment by oddleaf** [comment]
Yes! It's working perfectly! Thank you! :D

Anyway, I looked at code in v2.2.8 (which is previously worked for me), the `mode` was `w`. But in current version is `rw`, if we just writing to the file without reading it (when saving), why would it also hold `r` instead of just `w` or `wt`?

PS: I didn't know there's such a great feature of Github, build on cloud(?).

**Comment by gsantner** [comment]
@oddleaf 
Please also try this ("w") version from here https://github.com/gsantner/markor/actions/runs/485307850 .
If possible please open, close, edit, rewrite, close app, switch between apps ... whatever multiple files of different sizes - let me know if you notice something wrong (or i.e. wrongfully deleted).

Any notable difference for you between w and rwt build?

**Comment by oddleaf** [comment]
> It's GitHub's own Continious Integration system, GitHub Actions. There are others like CircleCi and Travis CI too.

Oh, thank you!

<br />

I don't see any notable difference between the two, it seems to be alright.

I don't know but if there's any behavioral change in some case like [this](https://stackoverflow.com/questions/64741675/clear-file-before-writing-new-content-into-it-java-android), then please consider using `wt` or `rwt` instead.

<br />

I just encountered another problem... Markor crashed when I try to create empty Zim Wiki on both SD Card and internal storage. It also happens on Google Play version, I think I need to file it into another issue.

**Comment by oddleaf** [comment]
@gsantner Thank you! :)
