### ISSUE TITLE
Feature request: disable delete confirmation dialog

### ISSUE THREAD

**Issue by poisonborz** [gsantner/markor#1198]
Like many, I use the app as a simple note taking app for some quick scribbles. In this use case the user creates and removes notes a lot. The "Are you sure to delete?" dialog is unnecessary and is a bit of a drag to have to click on it all the time.
It would be great to have an option to just delete the selected notes right after clicking the Delete button.

**Comment by gsantner** [comment]
There are users who accidentally click delete, and get their real important stuff deleted unintentionally. It's there for that reason, you can thank later.

I don't plan to make changes here.

**Comment by poisonborz** [comment]
To note, this would be an **option** that the users could **choose for themselves**. The app could display a warning before activating this. One could really only blame himself after activating this.

**Comment by gsantner** [comment]
Still no, I dont see the need that everything must be a option. Markor already has very much settings options and this one is not important to be controllable.
