### ISSUE TITLE
Open media in the Markor app (WebView compatible formats)

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#1200]
#### General information

* **App version:** 2.5
* **System:** 11

#### Description
Allow to open images (jpg/png/webp) in the app - using capabilties of the View-Mode. The webview supports these files AND comes with builtin zoom controls, pinch-to-zoom etc.

So: No addition of custom UI, ImageDisplay classes etc. Instead just use the view-mode webview with img src.

-------

[List](https://developer.android.com/guide/topics/media/media-formats) of supported formats from Android and so most of them on WebView too:

![f](https://user-images.githubusercontent.com/6735650/107078403-97b48680-67ee-11eb-8566-dc66aaf1c64d.png)

**Comment by gsantner** [comment]
[List](https://developer.android.com/guide/topics/media/media-formats) of supported formats from Android and so most of them on WebView too:

![f](https://user-images.githubusercontent.com/6735650/107078403-97b48680-67ee-11eb-8566-dc66aaf1c64d.png)

**Comment by chtixof** [comment]
Hello. Alternatively, a quick solution is to change the Markdown code when an image is inserted. Insert like: 
` [![text](IMG.jpg)](IMG.jpg) `

That is an image with a link on itself. It opens for example in the Gallery, which is fine for me.

**Comment by gsantner** [comment]
Markor already has <<open in external app>> at file browser. Actually that is the place where with this issue builtin support should be added.
