### ISSUE TITLE
Editor: Open file at Line Number from Intent

### ISSUE THREAD

**Issue by MisterY** [gsantner/markor#1202]
#### General information

* **App version:** 2.5.0 F-Droid
* **System:** Android 10, Xiaomi Mi 9T, Lineage OS

#### Description

Since it's 2021 and there is still no decent full-text-search solution, would you please at least accept the line number from aGrep's intent?

In the aGrep's Preferences, there is an option "Send Intent with the line number". Hopefully this would be enough to navigate to the line number in Markor editor, allowing quick navigation in long files.

The code that creates the Intent can be previewed [here](https://github.com/jiro-aqua/aGrep/blob/8eb6f8a5dd6ab588b0afa1bda799075b8b8fb203/src/jp/sblo/pandora/aGrep/TextViewer.java#L197).

The navigation from a long-press is initiated [here](https://github.com/jiro-aqua/aGrep/blob/8eb6f8a5dd6ab588b0afa1bda799075b8b8fb203/src/jp/sblo/pandora/aGrep/TextViewer.java#L217). There's a slight difference but it should not matter for the receiver. The parameter is still "line".

As a side note, I would debate the need to have the full-text-search integrated but you've already rejected that request multiple times so far. Even though I have to say I don't understand the reasoning. The current phones have multiple Gigabytes of RAM and storage. aGrep, at least in my case, returns the results pretty much instantaneously so I don't really see a reason not to have search from the current location in the file navigator.

So, at least I'd hope that we can navigate to the desired result from aGrep.
Thanks!

**Comment by MisterY** [comment]
Also, whenever navigating from aGrep to Markor, it always ends up in a viewer. 
I've turned off the "prefer viewer" option but to no effect.

**Comment by gsantner** [comment]
I may read the rest later but

> Since it's 2021 and there is still no

starting with that attitude you usually not find somebody to waste his !!freetime!! with whatever you bid them for.

**Comment by MisterY** [comment]
> Btw Markor has a decent simple & regex search - just not recursive.

For most basic cases this is more than sufficient.
My use, on the other hand, is a bit more complex. With VS Code and it's various extensions for Markdown, it has become a decent multi-platform solution for wikis and knowledge bases. Naturally, one wants to replicate this on the phone, which makes it that much more useful - to have the information when needed and to enter it while still fresh and relevant.

Markor is on a good path to match the necessary functionality in this respect, with only the search missing. It is obvious that the search is likely the most useful thing in a knowledge base or a wiki.
(I'm not sure what is going to happen with the changes in Android, and limiting of the file access, though. This might have crippling effect on combining tools as I do here.)
aGrep is actually not a bad solution for this purpose. I think that accepting the line number parameter will already bridge the search and editing.
With Syncthing and rclone covering file synchronisation, this is a fairly complete solution.

**Comment by MisterY** [comment]
One more use-case: https://github.com/amake/orgro/issues/34

**Comment by gsantner** [comment]
from agrep: 

![Screenshot_2021-05-13_11-45-38](https://user-images.githubusercontent.com/6735650/118109093-081c0680-b3e1-11eb-83b6-ea8f92acb2b3.png)

we have support for line number by search PR #1337 .  
Though not for the "unusual GET parmameter instead of a Intent Extra", which agrep does.
