### ISSUE TITLE
Please support outline in the markdown view

### ISSUE THREAD

**Issue by freelsen** [gsantner/markor#1203]
#### General information

* **App version: v2.5.0 (121)** 
* **System: Android ** 

#### Description
The outline is really needed for a large document. It is a common feature for desktop markdown softwares. But surprisingly all the mobile apps do not have it. Please support it as a pioneer.

**Comment by gsantner** [comment]
well this is already implemented?

Click the Title bar and the outline pops up

**Comment by freelsen** [comment]
Thank you for the quick reply. I have checked that and found that the table
of contents is only shown under edit mode. And after I jump to one location
and switch to view mode, it always starts from the top of the document,
instead of the location in the edit mode. This makes the outline useful
only for editing but not for viewing.

I hope the outline to be added to the view mode too. Thank you for the
consideration.

**Comment by gsantner** [comment]
For viewing, use Table of Contents. Enable optional in Markor settings.

**Comment by freelsen** [comment]
Thank you very much.
I found it. It is really great to have it.

But if you don't mind I would say it is not as convenient as the pop up
outline (like the one in the edit mode), because I have to go back to the
top of the document to find the table of contents everytime when I want to
go to a new location, instead of just hitting a button. Is there any option
that can do this?

**Comment by gsantner** [comment]
I dont plan to make changes here.

Even more, the table of contents in view mode is exported **as is** also in html.pdf etc - so you have that navigation there ttoo automatically.

**Comment by freelsen** [comment]
Ok. I just found the quick way to go back to the top by long pressing the
head bar. So that will do it. Thank you for all the replies. Have a great
day!
