### ISSUE TITLE
Feature: Pick random file button

### ISSUE THREAD

**Issue by pschwede** [gsantner/markor#1211]
#### General information

* **App version:** 2.5.0
* **System:** Android 10 (QPOS30.52-29-7-5

#### Description

This is a feature suggestion: An additional button could allow to open up a random file within the notebook folder.

**Comment by harshad1** [comment]
Fundamentally, this is up to @gsantner, but personally I think that adding this to markor itself isn't ideal and would lead to clutter (I would not add similar functionality to vim, for example).

Instead this sounds like a perfect use case for launching markor from an external app which does the actual selection.

**Comment by gsantner** [comment]
It is already implemented. close your eyes and randomly scroll up, down and press something. Open eyes again.

**Comment by pschwede** [comment]
> It is already implemented. close your eyes and randomly scroll up, down and press something on your phone. Open eyes again.

Not if you have lots of nested folders. (E.g. a Zim journal with folder like /year/month/day/...)
