### ISSUE TITLE
Edit mode: last line too close to toolbar?

### ISSUE THREAD

**Issue by riveravaldez** [gsantner/markor#1214]
#### General information

* **App version:** v2.5.0 (121) F-Droid
* **System:** Android 6.0, LG G4 Beat (LG-H735AR)

#### Description

Hi, not a bug but a UI detail?
When writing, the last line sometimes touch the downside toolbar and trying to select a character position ends in touching some tool/action not desired.
Maybe with a little more space between last text line and toolbar this could be avoided?
Just an idea.
Best regards and thanks **a lot** for such an awesome piece of libre software.

#### Log

No log.

**Comment by gsantner** [comment]
Right it has 0 margin/padding. Though it is intentional currently, vertical space is very limited and the more space for content the better

**Comment by riveravaldez** [comment]
Hm, I see...
Well, you really can't argue with reality, isn't it? ;)
Thanks a lot for the very quick very simple explanation.
Let me know if I should `Close with comment` this thread.
Thanks again!
