### ISSUE TITLE
Action bar to far at the bottom

### ISSUE THREAD

**Issue by Offerel** [gsantner/markor#1215]
At least here, using a Samsung Galaxy S20, when I have only gesture navigation buttons enabled in Android, the Action bar is partially covered by the small gesture hint bar. Can either the action bar moved some pixels higher or optionally positioned at the top of the editor window? Would be a lot better, specially by using the mentioned Android navigation.

**Comment by gsantner** [comment]
Please add video/marked screenshot what you mean.

**Comment by Offerel** [comment]
![Screenshot_20210203-231753_Markor.jpg](https://user-images.githubusercontent.com/14041522/106816803-35387a80-6676-11eb-96f3-bbf558519f1a.jpg)

Hopefully the screenshot is useful. I fear you can't do much against the partially covered area. Maybe moving the bar to the top is a better solution, but that's up to you.

**Comment by gsantner** [comment]
Ok I see, that should not happen. And no it doesn't look like that usually / doesn't for me at least.

What do you have configured in **android system settings** for display scaling / text size? Normal? Large?

**Comment by Offerel** [comment]
Text scale was standard, zoom also. The bar does not change, when I change the above settings.

But... the screenshot seems to resample only the state, when the keyboard is not visible. If I tap inside the the text, the keyboard comes up and the bar is above the keyboard.

If I change to the standard navigation, the action bar is also completely hidden behind the standard navigation. But the gesture navigation hints are smaller and that's why the action bar can't be hidden completely. 

So, it's all fine during typing.

**Comment by gsantner** [comment]
I don't know what todo about this, I cannot reproduce or fix the issue with any reachable device. If somebody wants to make improvements, just make a PR.
