### ISSUE TITLE
[Feature Request] Exclude filenames by pattern/regex from listing

### ISSUE THREAD

**Issue by Offerel** [gsantner/markor#1216]
I'm not sure if I have asked this before. But would it be possible to exclude files in the list of notes in the notebook, defined by a pattern or regex?

For example the notebook directory in my case is full of markdown files with extension .md but additionally there is a database from the sync tool saved there to keep track of the sync state. It would be nice, if I could exclude such files from the listing in some way.

**Comment by gsantner** [comment]
If you can control the filenames, use a . dot prefix for these special files. then they get hidden by the toolbar sort option.
