### ISSUE TITLE
Preview In View Mode

### ISSUE THREAD

**Issue by shockergit** [gsantner/markor#1218]
please add preview of all syntax in View mode

**Comment by gsantner** [comment]
"All" is endless but Live is not.

**Comment by shockergit** [comment]
what

> "All" is endless but Live is not.

just need a preview like in jotterpad or ia writer

**Comment by gsantner** [comment]
Preview button is the button on the top-right.

**Comment by shockergit** [comment]
> Preview button is the button on the top-right.

sorry i was creating plain text file and previewing it . it works in md sorry

**Comment by gsantner** [comment]
I see. Thought you mean support "all text filetypes' syntax" :smiley:

**Comment by shockergit** [comment]
> Preview button is the button on the top-right.

not previewing this syntax can you fix it.
^^Markor^^

**Comment by shockergit** [comment]
> I see. Thought you mean support "all text filetypes' syntax" 😃

no lol bad inglish skills

**Comment by shockergit** [comment]
please add preview for this syntax too
==Markor==  
^^Markor^^
please
