### ISSUE TITLE
F-Droid automatic builds stopped working

### ISSUE THREAD

**Issue by spitlo** [gsantner/markor#122]
I'm not sure if this is an issue for the maintainer of this repo or for the F-Droid people, but there has been no releases on F-Droid since 0.1.5.

Judging by the F-Droid [build log](https://f-droid.org/wiki/page/net.gsantner.markor/lastbuild_7) for Markor, it has to do with the upgrade to SDK Platform 27.

Related commit: https://github.com/gsantner/markor/commit/135282f496dd3b8167c81a0c8f1b52e244b55ada

**Comment by gsantner** [comment]
nothing we can do about that other than wait, they need some time to update buildserver

**Comment by spitlo** [comment]
Great! Closing this then.
