### ISSUE TITLE
Fix per-file setting of Format

### ISSUE THREAD

**Issue by volt4ire** [gsantner/markor#1220]
#### General information

* **App version:  2.5.0
* **System: 11

#### Description
Whenever I set the formatting of a note with a .txt file extension (via the three-circles-menu-item>File settings>Format >Markdown menu item) and then reload or close and then return to that note, the formatting of the note is reset to plaintext. Can you please help me resolve this issue? 
Also, is there a way to have Markor load all .txt files as if they were Markdown files (eg: by showing the Markdown Text Actions bar above the keyboard rather than the Plaintext one) by default? If not, would you consider adding an option for doing so? Thanks!!

**Comment by gsantner** [comment]
> Whenever I set the formatting of a note with a .txt file extension (via the three-circles-menu-item>File settings>Format >Markdown menu item) and then reload or close and then return to that note, the formatting of the note is reset to plaintext. Can you please help me resolve this issue?

to be checked.

>  Also, is there a way to have Markor load all .txt files as if they were Markdown files (eg: by showing the Markdown Text Actions bar above the keyboard rather than the Plaintext one) by default? If not, would you consider adding an option for doing so? Thanks!!

Well pretty simple, use `.md.txt` or `.md` for filename. Making a change to mark all .txt as Markdown will make most people unhappy and introducing a own setting not sounds much helpful. You probably have other Markdown software too, and you can expect proper markdown highlighting and stuff also there if you name them with one of the common extensions.

**Comment by harshad1** [comment]
@gsantner it looks like last format is not remembered

**Comment by volt4ire** [comment]
@gsantner Thanks for this update! I prefer to keep all my notes with a .txt extension to maximize compatibility with legacy external editors which is why I asked about offering a setting able to render .txt files as markdown by default. Since I so often use Markor I have changed my notes to a .md extension for now though while the bug of per-file formatting not being remembered persists

**Comment by timbze** [comment]
I use Zim Desktop and Syncthing to sync to Android. The files are stored as .txt, so I also would use the option to use a default file format (zim wiki) for my files.

But if at least my main file that I use on my Android would remember it's setting that would help me out too.
