### ISSUE TITLE
Custom Sort order for Folders and change folder colors

### ISSUE THREAD

**Issue by shockergit** [gsantner/markor#1224]
It would have been nice if you add an option to set custom sort order to set my prefered folder on top and option to change color of thr folder

**Comment by harshad1** [comment]
@shockergit you can start a folder and it will have a different color.

As for order, i just name my folders appropriately:
```
0_Inbox
1_projects
2_checklists
```

This way they show up in the correct order on all platforms

**Comment by shockergit** [comment]
> @shockergit you can star a folder and it will have a different color.
> 
> As for order, i just name my folders appropriately:
> 
> ```
> 0_Inbox
> 1_projects
> 2_checklists
> ```
> 
> This way they show up in the correct order on all platforms

I use the star feature it only have only one colour. thanks for the idea about numbering thats works
