### ISSUE TITLE
Zim not auto-detected by other date format

### ISSUE THREAD

**Issue by timbze** [gsantner/markor#1227]
#### General information

* **App version:** 2.5.0
* **System:** Android 11

#### Description

I'm seeing in #1098:
> - [x] File detection (.txt files with a zim header)

However, the app does not recognize my txt files as zim format.

This is the header of my zim txt files (first 3 lines):
```
Content-Type: text/x-zim-wiki
Wiki-Format: zim 0.6
Creation-Date: 2021-02-09T15:21:45-06:00

====== TO DO ======
Created Tuesday 09 February 2021
```

**Comment by timbze** [comment]
I have not looked into the code very far, but looking [here](https://github.com/fredericjacob/markor/blob/9cac0704494065303c818aedcad4aa48c19309ac/app/src/main/java/net/gsantner/markor/format/zimwiki/ZimWikiHighlighter.java#L51), I'm wondering if it might be because of the timezone at the end of "Creation-Date" line.

**Comment by gsantner** [comment]
Probably it makes sense to probe only for "text/x-zim-wiki" and nothing else.. this matching against non-always-equal heading is just tedious.

**Comment by timbze** [comment]
> Probably it makes sense to probe only for "text/x-zim-wiki" and nothing else.. this matching against non-always-equal heading is just tedious.

Agreed. IMO check the first line only, or perhaps first 3.
