### ISSUE TITLE
Unable to exit from QuickNote

### ISSUE THREAD

**Issue by sivaraam** [gsantner/markor#1236]
#### General information

* **App version:** 2.5.0 F-droid
* **System:** Android 5.1.1, Samsung SM-J111F

#### Description
I'm not able to exit from the app after opening the QuickNote preview.

#### Steps to reproduce
1. Open the app
2. Go to QuickNote
3. Tap on the preview icon
4. Hit back
5. Hit back again

#### Expected result
The "Press 'back' again to exit" snackbar is shown.

#### Actual result
The preview of QuickNote is shown.

**Comment by gsantner** [comment]
you can also click the button on the top-left.

**Comment by sivaraam** [comment]
Yeah. That seems to be working fine 👍

**Comment by sivaraam** [comment]
That counts as a work-around but shouldn't the actual issue be fixed? 🤔

**Comment by gsantner** [comment]
I dont see the need for fix, from the "sub window" you can get out with normal back button (back to main). 

And having preview/edit swap on the main page after you just used preview seconds ago...is actually nice.

**Comment by sivaraam** [comment]
! Additionally, you have the system HOME button just beside system BACK. Can also be used. It's not like there is no way out...there are many ways.

You're right. It's not like there's not way out. I think I expected a way out just by using the 'Back' button.

! And having preview/edit swap on the main page after you just used preview seconds ago...is actually nice.

I find it confusing that back takes me to a view which I just left behind. But you seem to find it nice. So, looks like we have different preferences. 🙂
