### ISSUE TITLE
At times, cursor jumps when editing

### ISSUE THREAD

**Issue by sivaraam** [gsantner/markor#1237]
#### General information

* **App version:** 2.5.0 F-droid
* **System:** Android 5.1.1, Samsung SM-J111F

#### Description
Sometimes while editing in the editor the cursor jumps to some other random place and starts continuing my editing there. This annoys me when it happens. I'm not sure of a certain sequence that could be causing this but I'll let you know if I notice anything. 

I wanted to file this with the hopes that I'll get some hints as to why this might be happening (or) some help on identifying the root cause of this issue. Any help would be great!

**Comment by harshad1** [comment]
Do you have a second device on which you could verify this behaviour?

**Comment by sivaraam** [comment]
I do have another device but I'm not sure how to verify this easily as I don't use that primarily and this issue appears to be happening randomly.
