### ISSUE TITLE
Start on bottom not respected in bottom tabs(To-Do and QuickNote)

### ISSUE THREAD

**Issue by krisfremen** [gsantner/markor#1238]
#### General information

* **App version:** v2.5.0
* **System:** Android 10 - ONEPLUS A6013

#### Description
Opening a file through the Files tab will go to the bottom(view and cursor).

Opening the same file via the To-Do or QuickNote tabs will not go to the bottom of the file with the actual view, although the cursor seems to be there, as any of the Text Actions will add it to the end of the file.

**Comment by gsantner** [comment]
Hey @krisfremen 

QuickNote and ToDo are slightly special due they (intentionally) are forced to bottom position. This is especially there for ShareInto and quick appending of text to these files.

Cursor on main tabbed view is forced to bottom (OK), for the full editor window I couldn't reproduce a issue.

**Comment by krisfremen** [comment]
I see.

I'm doing a screencap to illustrate the issue, seeing is believing. 😄 

Cheers!
