### ISSUE TITLE
ShareInto: web link formatting

### ISSUE THREAD

**Issue by harshad1** [gsantner/markor#1240]
In the share-to dialog, the current link formatting is hard to read due to 2 factors:

1. The text size is too small ([this is due to scaling by 0.7](https://github.com/gsantner/markor/blob/master/app/src/main/java/net/gsantner/markor/ui/hleditor/Highlighter.java#L105))
2. The trailing parenthesis is captured by the link regex

![link](https://user-images.githubusercontent.com/1940940/108003204-e0b2ca80-6fa6-11eb-8efd-d3ae880d49cf.png)

**Comment by gsantner** [comment]
url is intentional small to be able to focus on text itself. Especially when you get in these long urls with utm_source, fbid & co.

trailing paranthese however shouldn't be captured/blue

**Comment by harshad1** [comment]
:+1:

**Comment by harshad1** [comment]
Looks like the solution will require re-creating the WEB_URL pattern. IMO this is not worth it.

**Comment by gsantner** [comment]
I say 98% is better than 99%+slow/bad performance :smiley:

**Comment by harshad1** [comment]
Agreed (also maintainability). You can close this if you like.

**Comment by gsantner** [comment]
by the way theres a new commit on master that auto adds a space before ")" -> " )". For the reason if you reshare to messenger, they will open "https://oihqoiwhdwoidhwodi/asdb)" in browser if you click the (markdownish) link. However not if it's having a space at the end 😉

**Comment by gsantner** [comment]
> You can close this if you like.

You can too. If you want to make changes still, you can of course
