### ISSUE TITLE
Markdown toc settings option conflicts frontmatter

### ISSUE THREAD

**Issue by Offerel** [gsantner/markor#1246]
#### General information

* **App version: 2.5.0 Play Store** 
* **System: Android 11** 

#### Description
Frankly i don't know if this would be an Feature Request or some other thing. Hopefully, i could get this to work. I really love this app since a long time, but there is one thing which drives me nuts. In my markdown files i make a lot use of YAML frontmatter. Mostly the file starts with the usual '---', than some metadata and after another '---' the real markdown content begins. In most other markdown applications, this information is hidden, unless i show this metadata parts.
 
In Markor, i have not found a way to hide the YAML header. Its always showed as part of the markdown content. Specially the metadata is doubled, when i make use of the ToC feature. In this case i have the YAML visible in the ToC and the content.

By searching here, i have found #487 but i didn't find these markdown settings you mentioned there. Can you please be so kind and show us, where i can hide the YAML header?

------------------------
EDIT:

Have found it. If i enable ToC / Inhaltsverzeichnis, YAML is showing.

I have attached one of my markdown files, renamed to txt, because GitHub doesn't allow md. 
[Adjusting child processes for PHP-FPM.md.txt](https://github.com/gsantner/markor/files/6003306/Adjusting.child.processes.for.PHP-FPM.md.txt)

I get this view in the app
![Screenshot_20210218-150642_Markor](https://user-images.githubusercontent.com/14041522/108368688-07693f00-71fb-11eb-9c03-f08acebbb981.jpg)

**Comment by gsantner** [comment]
I don't know what you do, or if you write incorrect formatted YAML header.

But I use YAML header (blog posts and jekyll wiki), not YAML header (normal md files like quicknote) .. everyday. And I haven't seen YAML header in content. Also there is no settings option. The markown parser does consume it when correctly formatted. 

![Screenshot_20210218-145838](https://user-images.githubusercontent.com/6735650/108367879-287d6000-71fa-11eb-9725-738d228c7d61.png)

**Comment by Offerel** [comment]
I have attached one of my markdown files, renamed to txt, because GitHub doesn't allow md. 
[Adjusting child processes for PHP-FPM.md.txt](https://github.com/gsantner/markor/files/6003306/Adjusting.child.processes.for.PHP-FPM.md.txt)

I get this view in the app
![Screenshot_20210218-150642_Markor](https://user-images.githubusercontent.com/14041522/108368688-07693f00-71fb-11eb-9c03-f08acebbb981.jpg)

**Comment by Offerel** [comment]
Hmm i have followed your hint, to reset the app. This seems to work. Sure, i must setup some options now, which i havent as of yet. But i will do my best. If i found that the issue comes from one of the settings, i will report.

**Comment by gsantner** [comment]
Yeah let me know when you find some conflicting option. But in general it should work as expected.

**Comment by Offerel** [comment]
Have found it. If i enable ToC / Inhaltsverzeichnis, YAML is showing.

**Comment by gsantner** [comment]
insert position of toc needs to be adapted then.

**Comment by gsantner** [comment]
insert position of automatic toc needs to be adapted at MarkdownTextConverter.

I merged the real problem into the issue description.

**Comment by fgtham** [comment]
Currently the TOC handling code requires an empty line between YAML block and beginning of Markdown content:

```yaml
---
foo: bar
---

# A heading
```

If the empty line is missing, like in the attached file, the YAML block contents are displayed right after the TOC just like in the issue's screenshot.

A quick workaround is to insert an empty line where needed.

**Comment by Offerel** [comment]
Wow nice finding. I will try to mass-change my current markdown files and keep the timestamp with some script. Should be not to complicated.

After that, I implement the empty line in my PrimitiveNotes apps to.

If the empty line is fixed later in markor, this should not harm the new change in my app.

Many thx.
