### ISSUE TITLE
Changing font color and highlight color

### ISSUE THREAD

**Issue by shockergit** [gsantner/markor#1248]
Give an option to change font color and highlight color of selected text, Just like bold and italics.  
It will be very handy

**Comment by gsantner** [comment]
Already is there, see the markdown reference and you can use the action for color.

**Comment by gsantner** [comment]
There is a button on the bottom with color selection for that. Also check the markdown reference, has a example.

**Comment by shockergit** [comment]
Thanks i saw it now. Why you hide it inside the attachment menu.
