### ISSUE TITLE
Markor is not associated with file extension ".md"

### ISSUE THREAD

**Issue by palto42** [gsantner/markor#125]
#### General information

* **Device:**   Samsung Galaxy S8
* **Android Version:**  Android 7.0
* **App version:**  0.2.2

#### Steps to reproduce

1. Save a textfile with Markdown format and file extension ".md" in some folder on the phone
2. Open the folder with the Samsung file explorer
3. Tap on the file to open it

#### Expected result
The file should be opened with Markor or a dialogue should be displayed to select a suitable app (if there are multiple options for md files) to select Markor as an option.

**What do you see instead?**
Instead an error message is displayed that the file can't be opened because there is no App for this file type.
The same result if I try to open the file from within the nextcloud app.
I can open the file from within Markor without issues.

**Comment by gsantner** [comment]
Maybe install Intent Intercept  and tell me (copy) what is the intent sent out by your file manager. 

(View inter-app communication) - https://f-droid.org/app/uk.co.ashtonbrsc.android.intentintercept

**Comment by palto42** [comment]
I can only install from Google Play or Samsung app stores (policy restriction), so I installed the app "Intent Analyser" instead (hope it's something similar).
If I try to open an ".md" file from the Nextcloud app, the Intent Analyser shows me some information [Intent Analyser message](https://github.com/palto42/files/blob/master/Markor-Intent.jpg).

If I try to open the file from the Samsung file browser, the Intent Analyser doesn't show anything but I still only get the [app error message ](https://github.com/palto42/files/blob/master/Screenshot_open_md.png)

**Comment by gsantner** [comment]
sorry, but when even intent interceptors cannot catch the intent, I can only suggest you to use a functional file browser .

**Comment by palto42** [comment]
Thanks for the quick responses, but I don't understand why you immediately close the issue since the Intent Analyser catches the intent from the Nextcloud app which has the same issue as the file browser. Is the information from this app not useful?

**Comment by gsantner** [comment]
because your file manager semms to not send out view intents as all as you told above. Markor cannot respond to things that are never sent..

For the content thing theres another issue, which is about content URIs.

The issue title is about md not associated with Markor, which it is.
