### ISSUE TITLE
Edit text files with arbitrary extensions

### ISSUE THREAD

**Issue by SumatraPeter** [gsantner/markor#1251]
Using v2.5.0 from F-Droid on an Android 5.0.1 tablet.

How do I edit text files with arbitrary extensions? For example I navigate in Markor to a folder with plaintext .SRTs, but selecting any of them displays the standard Android "Open with..." app selection dialog.

Ideally speaking we should be able to not only open text files with any extension, but also add extensions to the app's options that we want associated with it. So for example if we add .SRT to the app's association list, thereafter clicking on such files in the file manager should open them in Markor.

**Comment by gsantner** [comment]
General settings, option 4 "always..."

**Comment by SumatraPeter** [comment]
Awesome. Doesn't associate the app with the extension, but does make the files open within the app. Thanks!
