### ISSUE TITLE
Feature request: support for Notable note image (or any) attachments

### ISSUE THREAD

**Issue by tonyrulez** [gsantner/markor#1252]
On Windows and Linux I use [Notable](https://github.com/notable/notable) to create and edit notes, On my phone these notes are synced with FolderSync.

The Notable file structure looks like this:
```
.
├── ...
├── notable          # root folder of notable
│   ├── attachments  # various attachments (e.g. jpg and png images for the notes)
│   └── notes        # the notes themselves in .md
└── ...
```

The images are linked this way: `![Image](@attachment/image.png)` 

Currently in reader mode these images are not shown. Would be great to see these images.

Note that folder name is `attachments`, link is `@attachment`. This is not a mistake, see [Notable cheatsheet](https://cheatsheet.md/notable.pdf) for deep linking.

**Comment by gsantner** [comment]
Idk why most markdown applications try to gain vendor-lockin by introducing some home brewed syntax that works just in their application/platform.  
Theres a simple and compatible syntax that works in EVERY markdown application out there: `[file](../attachements/file.jpg)`.  

I'm not really fond of such vendor-lockins - you will never run into these kind of things at Markor.

**Comment by gsantner** [comment]
Idk why most markdown applications try to gain vendor-lockin by introducing some home brewed syntax that works just in their application/platform.  
Theres a simple and compatible syntax that works in EVERY markdown application out there:  
`![title](../attachements/file.jpg)`.  

I'm not really fond of such vendor-lockins - you will never run into these kind of things at Markor.
