### ISSUE TITLE
Black field at file opening

### ISSUE THREAD

**Issue by thumos333** [gsantner/markor#1253]
#### General information

Just installed Markor and there seems to be a problem with initial opening of files from time to time: a black field appears in-between the Android keyboard and the app's bottom panel. The black field disappears if I tap "back" to hide the keyboard and tap on the text to get the keyboard back on.

* **App version:** 2.5.0 (121)
* **System:** Android 6.0.1 (MIUI Global 9.5.5.0)

Here is a picture illustrating the issue:

![Screenshot_2021-02-25-01-28-09-082_net gsantner markor](https://user-images.githubusercontent.com/29035180/109068290-7837bc00-7711-11eb-8be5-087ac61c50ef.png)

**Comment by gsantner** [comment]
Cannot reproduce
