### ISSUE TITLE
Misinterpretation of `\` in KaTeX formula

### ISSUE THREAD

**Issue by Gennadiyev** [gsantner/markor#1254]
#### General information

* **App version:** 2.5.0 GP
* **System:** Android 10 (HUAWEI Matepad Pro)

#### Description

In a word, Markor did not render KaTeX correctly when using `\` symbol in a line that does not start with `$`.

For example:
**BAD for Markor but expected:**  
`Test $$\begin{aligned} x&=1+1 \\ x&= 2 \end{aligned}$$`
**GOOD for Markor:**  
`Test $$\begin{aligned} x&=1+1 \\\\ x&= 2 \end{aligned}$$`
**Also GOOD for Markor:**  
```
Test
$$\begin{aligned} x&=1+1 \\\\ x&= 2 \end{aligned}$$
```

----
Another example:
**BAD:**
```
1. $a \qquad b$
2. $a \quad b$
3. $a\ b$
4. $a \; b$
5. $a \, b$
6. $ab$
7. $a \! b$
```
**GOOD:**
```
1. $a \qquad b$
2. $a \quad b$
3. $a\ b$
4. $a \\; b$
5. $a \\, b$
6. $ab$
7. $a \\! b$
```

It can be worked around though by always opening up a new line in markdown file when starting a KaTeX formula, but that's just not so LaTeX-flavoured.

**Comment by gsantner** [comment]
wait for next update, #1196 had some fixes.
