### ISSUE TITLE
File encryption feature

### ISSUE THREAD

**Issue by cazzoo** [gsantner/markor#1255]
#### General information

N/A

#### Description
Hi! I'm using Markor sometimes and it's really neat, the application works well and allow me to store my note quite easily, thanks for that.
I just wonder if anytime you consider adding the feature to encrypt the files and Uber the fingerprint to unlock file reading/editing.
This may be really nice to have such capability

Thanks

**Comment by gsantner** [comment]
you can find encryption in settings, then create a encrytped file via dialog.

**Comment by cazzoo** [comment]
Oh, indeed I could find the encryption feature enabling the extra experimental features.

Regarding this one, is there a way to crypt existing file ?
Also, I did created a crypted file, while accessing with Markor I had no prompt to enter my password hash.
Is there a way to do this ?
Moreover, could we imagine having the fingerprint to unlock a crypted file ?

**Comment by gsantner** [comment]
manually "select all" and copy over the content.

Note the extension ends with ".jpenc" for encrypted files, for seeing the difference.

Fingerprint don't know, not high important at last.

**Comment by qazip** [comment]
What encryption does Markor use? How do I unencrypted a markor encrypted file in the desktop?

**Comment by gsantner** [comment]
Use the discussions search. this has been questioned multiple times. AES.
