### ISSUE TITLE
HTML Support

### ISSUE THREAD

**Issue by shockergit** [gsantner/markor#1256]
Add support for HTML file editing and previewing

**Comment by gsantner** [comment]
Uhm, already there?? You can open .html files just fine, edit them, view them. I use this like once a week.

**Comment by shockergit** [comment]
> Uhm, already there?? You can open .html files just fine, edit them, view them. I use this like once a week.

![IMG_20210227_150945](https://user-images.githubusercontent.com/63154802/109383681-dfa36680-78df-11eb-8644-445dd06e5151.jpg)
Im getting this error while opening a htm file . The html is exported from the markor itself

**Comment by gsantner** [comment]
this dialog might appear when you open from some other app. It has absolutley nothing todo with html format, or html file.

**Comment by shockergit** [comment]
I fixed it by turning off content url in my file explorer

**Comment by shockergit** [comment]
![Uploading IMG_20210227_153024.jpg…]()

**Comment by gsantner** [comment]
OK! Thanks
