### ISSUE TITLE
Adding Multiple preview modes.

### ISSUE THREAD

**Issue by shockergit** [gsantner/markor#1258]
Adding multiple preview formats and saving it in different names. And an option to choose default preview mode for file
![IMG_20210227_152015](https://user-images.githubusercontent.com/63154802/109383862-437a5f00-78e1-11eb-8e46-91fc9dc8e4af.jpg)

**Comment by gsantner** [comment]
You can change the format in the FILE SETTINGS menu. And you can export as you wish.

**Comment by shockergit** [comment]
> You can change the format in the FILE SETTINGS menu. And you can export as you wish.

![Uploading IMG_20210227_153443.jpg…]()
Only two options

**Comment by shockergit** [comment]
Wrap words and syntax highlighting no other option in file settings

**Comment by gsantner** [comment]
First of all, there is a ISSUE TEMPLATE  for a very important reason. Fill out the values they are important.

Second your posted image is bad URL.

**Comment by shockergit** [comment]
Using the latest version from playstore.
2.5.0
![IMG_20210227_154900](https://user-images.githubusercontent.com/63154802/109384525-50994d00-78e5-11eb-9649-6fbe9432466d.jpg)
