### ISSUE TITLE
Keeping line-breaks in View mode, without requiring two spaces at end of line 

### ISSUE THREAD

**Issue by pgorod** [gsantner/markor#1259]
### General information

This is not strictly a debugging issue for the developers. It's just a technical discussion for the community, although perhaps if this works well we could ask for a Markor option to be made from it.

### Description

Markdown specification requires that you put two spaces at the end of the line in order for the line-break to render in HTML. Otherwise, the line breaks are ignored. Markor follows this specification correctly, so when you go to **View mode** you lose any simple text `\n` line-breaks.

But for many of us, we are just taking notes and don't want to use much formatting, or (as is my case) are importing a ton of text notes from previous apps, turning them into markdown. The "two spaces" rule is a hassle.

This has often been asked, discussed, marked "wontfix", etc: #875, #516, #189

### A solution using custom CSS

So I started playing with custom CSS (Markor option **`Settings / View mode / Inject -> head`**) and it's a bit tricky. I had some nice results with only a couple of CSS styles on top:

```css
html,body {
   white-space: pre-line;
}
p {
   margin-bottom: -1em;
}
```
But unfortunately this looks quite wrong whenever lists are used (`ul`, `ol`, `li` HTML tags).

So I ended up with something more complex, and less performant, but that is looking great for my experiments:

(I include the default Markor custom CSS so you can see where to put my code)

```js
<script type="text/javascript">
// ADDED CODE STARTS HERE:
document.addEventListener('DOMContentLoaded', function (e) {
      var preElements = document.querySelectorAll('p');

      Array.prototype.forEach.call(preElements, function (pre) {
          pre.innerHTML = pre.innerHTML.replace(/\n/g, "<br />");
      });
  });
// ADDED CODE ENDS HERE:
  
function onPageLoaded(){

/*if ('format-markdown fileext-md' == 'MarkdownTextConverter') {
window.scrollTo(0,document.body.scrollHeight);
}*/

}
</script><script> function onPageLoaded_markor_private() {

onPageLoaded(); }
</script>
```
(just to be clear, if you add the JS, don't use the CSS given above; they're alternative approaches, not meant to be used together)

So before anything else, I'd like to ask:

1. Interesting? Useful?
1. Can anybody find cases where this doesn't work well with their documents? I'm sure this still needs improvement.
1. If it works well, I would consider this for a global option in the **`Settings / View mode`** menu: **`Render all line-breaks`**, with description text **`Skip the Markdown requirement for two spaces at end of line to produce a line-break.`** This would be opt-in, i.e. **off** by default, to respect the Markdown specification.

**Comment by pgorod** [comment]
I had a bug in the code above, just edited it to fix. Sorry.

**Comment by harshad1** [comment]
Another option is using search-replace to insert 2 spaces at the end of each line. This hack is my preferred 'solution' :)

**Comment by gsantner** [comment]
While I'm aware off potential flexmark parser options, `replace("\n", " __"\n)` might be the better option - for the reason it not requires any parser option changes, and works in the same way for all markdown parsers.

**Comment by gsantner** [comment]
While I'm aware off potential flexmark parser options, `replace("\n", " __\n")` might be the better option.  
For the reason it not requires any parser option changes, and works in the same way for all markdown parsers.

**Comment by pgorod** [comment]
> Another option is using search-replace to insert 2 spaces at the end of each line. This hack is my preferred 'solution' :)

But that requires changing the original files, and there is no moment to do this automatically. I thought about using that kind of approach ("fix all my files") but that always leaves the issue of all the future edits I will be making. With this approach I am using, it all happens automagically and I can forget about this whole issue forever... 😃 

> While I'm aware off potential flexmark parser options, replace("\n", " __\n") might be the better option.

I'll try this variation and tell you how it goes.

**Comment by gsantner** [comment]
> But that requires changing the original files,

Wrong, we have a convert markup -> html function. And in there we already do a series of optimizations. That improved markup gets rendered, but not written to disk / editor.

**Comment by pgorod** [comment]
I'm not sure I understand correctly. I was assuming @harshad1 meant doing the search and replace manually (or scripted) in an outside program. But from what @gsantner writes, you mean having an option in Markor to do the operation adding two spaces rit internally, right before

**Comment by pgorod** [comment]
(sorry about the closing and reopening, it was an accidental click)

I'm not sure I understand correctly. I was assuming @harshad1 meant doing the search and replace manually (or scripted) in an outside program. But from what @gsantner writes, you mean having an option in Markor to do the operation adding two spaces internally, right before displaying the HTML? That sounds great!

**Comment by pgorod** [comment]
Thanks for the new update. It works wonderfully (also with Back button improvement)!

Everything happened so fast! I am amazed. 🎉
