### ISSUE TITLE
Handling of content:// URIs 

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#126]
#### General information

* **Android Version:**  7
* **App version:**  0.2.2

#### Steps to reproduce
Currently everything is handled as `java.io.File`. `content://` URIs are just converted to File using `getPath()`, which will not work in many cases when data coming from other applications.

#### Expected result
* [x] intent-filter for content URIs for DocumentActivity
* [ ] Content URIs get correctly handled aswell. Includes saving/writing/reading/isFolder/isFile/isReadonly. One has also to check that at content URIs >renaming< may not be possible.

* [ ] Ideally there is the current Document class contains a DocSource Object. Soirce is  a Baseclass, has two derivates, one for file, one for content. Baseclass with an abstract `boolean read/write/move/isFile/isFolder/isReadonly/isMoveable` method. Parameters between activity are shared then with type  `Document` or with the baseclass.
  * Maybe DocumentFile already has required stuff builtin? <https://developer.android.com/reference/android/support/v4/provider/DocumentFile.html> and openInput/OutputStream on getUri()
* Maybe note future addition of other sources, e.g. Network? A sync provider/library with callbacks? ..

##### Some notes
* <https://stackoverflow.com/questions/10925196/deleting-files-via-a-contentresolver-as-opposed-to-deleting-them-via-file-del/26360071#26360071>
* <https://stackoverflow.com/questions/37168200/android-5-0-new-sd-card-access-api-documentfile-renameto-unsupportedoperation/37168394#37168394>
* <https://developer.android.com/guide/topics/manifest/data-element.html>

**Comment by paldepind** [comment]
I ran into this error when trying to open a Markdown file through the Dropbox Android app.

Is there any way to use Markor with Dropbox or another syncing service?

**Comment by gsantner** [comment]
Well it's more like a "this is not done yet" then an error :D.

Yep, I (and many others told me they do) use Syncthing for that. <https://syncthing.net/>

**Comment by gsantner** [comment]
@paldepind : Markor got some <3 in the latest update regarding this. While you can't open files directly out of the DropBox app, you can now set the folder to `STORAGE/Android/data/com.dropbox.android/files/u123456/scratch/` and edit files in there, thats the folder where Dropbox should sync all files too. Don't forget to check the `Offline available mark` in the dropbox app.

**Comment by dubaaron** [comment]
> @paldepind : Markor got some <3 in the latest update regarding this. While you can't open files directly out of the DropBox app, you can now set the folder to `STORAGE/Android/data/com.dropbox.android/files/u123456/scratch/` and edit files in there, thats the folder where Dropbox should sync all files too. Don't forget to check the `Offline available mark` in the dropbox app.

Thank you very much for this.  For the record, Dropbox used to support setting the "make available offline" for a folder on the free version -- as of this writing, that is no longer the case, you have to upgrade to premium/subscription Dropbox for that.  (Also for the record, you used to be able to connect more than 3 devices for sync on free Dropbox, that is also no longer the case).

**Comment by gsantner** [comment]
thanks for notice. I dont personally use dropbox so commmunity feedback is important.
