### ISSUE TITLE
todo.txt: "rec:" (recurring tasks) supported?

### ISSUE THREAD

**Issue by Moonbase59** [gsantner/markor#1263]
#### General information

* **App version: 2.6.0 (122)** 
* **System: Android 6** 

#### Description

Does Markor support `rec:` entries (recurring tasks)? They do get italicized but when I check a task as done, no new entry gets created.

Typical entries would be:
```todo
2021-03-01 Pay rent @bank due:2016-04-01 rec:+1m
2021-03-01 Check Markor issues @github rec:1w
2021-03-01 Train +Spanish vocabulary @home rec:3b
```
meaning:
* Pay rent on every 1st of a month (next task based on `due:` date)
* Check Markor issues once a week (next task based on last "Done" date)
* Train Spanish all 3 business days (excluding sat/sun; next task based on last "Done" date)

I use *Markor* on Android, *Todour* on Linux, and *Syncthing* to sync between them.

**Comment by gsantner** [comment]
Never used or explicitley heard of that todo.txt extension. rec:xyz, just like any key:value pair is highlighted, whatever you will do with that is up to you.

When you check or uncheck, Markor does it. If you want to have kind of subtasks or copy of the tasks, you need to make the duplicate on your own.

With todo.txt and its custom key:value pairs possibilites of extensions are endless - but not everything needs a own special implementation. Which is the case here.

**Comment by Moonbase59** [comment]
Ok, thanks for the explanation. I was hoping, since most other _todo.txt_ tools nowadays support `due:`, `t:`, `rec:` and `rec:+`.

Thanks anyway for making Markor!

**Comment by Witcher01** [comment]
Would a PR with support for recurring tasks be merged by any chance, or is it that you just don't want this feature in Markor?

**Comment by gsantner** [comment]
Remember at first, Markor is especially one things - a texteditor. Feel free to put rec: anywhere you want and it will be highlighted. Second, when something is gone in a textfile it is gone. I don't
quite get whats the improvement here to automatically duplicate lines of text. Lets say you have "rec:daily walk the dog", what is the benefit when you get "walk the dog" added everyday, when you
anyway already have it in the same file? You can also just search for rec: then and get immediately everything you marked as recurring.

If you feel like this needs some special handling, feel free to implement something.

**Comment by gsantner** [comment]
I'd then suggest to replace the existing todo line with the updated date and mark it un-done

**Comment by SeerLite** [comment]
Then I would have to manually add in my head. "This is a weekly task. Today is October 28..."

**Comment by gsantner** [comment]
todo.txt is a format intentionally for simplistic usage, for more features a different format & tool might fit you better. Recurring might be something supported by some todo.txt tools by whatever means, but it's not any builtin of todo.tyt.
The right tool for the right job. Maybe Markor just is not the right one for some quite specific cases.

Also, what you might see needed or miss, is what others are bugged out about or is bloat to them.

**Comment by ERamseth** [comment]
So there's no possibility of adding support for (I guess what you would call) automatically recurring tasks? Would it even be worth adding a feature request in your feature request form?

You're right in that it's an extension to the original format, but the official apps for ios and android (all now seemingly gone) and most modern todo.txt apps support it. The mechanism was (I believe) originally described by topydo and has been adopted by sleek, 2do-txt, swiftodo, and others. Unfortunately all of these apps aren't for android and it seems almost all (if not all) dedicated todo.txt apps on Android are gone (simpletask, todo.txt, a few others).
