### ISSUE TITLE
File manager: Add file copy support

### ISSUE THREAD

**Issue by harshad1** [gsantner/markor#1264]
Right now, Markor supports moving files in the file manager. Copy should be supported as well

**Comment by gsantner** [comment]
We already have import, which is Copy at core

**Comment by harshad1** [comment]
Its inverted though, Destination <- Source, Rather than Source -> destination. And it doesn't support multiple files etc

**Comment by gsantner** [comment]
If you want to work on #1265 issue, it can be combined with this issue, same code - just that no old::delete() calls happen at copy.
