### ISSUE TITLE
File manager: Ask for overwrite confirmation at copy/move

### ISSUE THREAD

**Issue by harshad1** [gsantner/markor#1265]
Moving files can overwrite files with the same name at the destination. Instead we should warn the user and present the following options:

1. Skip
2. Overwrite
3. Keep both (will find non - conflicting name by adding a suffix)
4. Skip all
5. Overwrite all
6. Keep all

4, 5, 6 will be needed in case of move / copy multiple files

**Comment by harshad1** [comment]
[Simple file manager](https://f-droid.org/en/packages/com.simplemobiletools.filemanager.pro/) on F-Droid has good behavior. We should try to do what it does, IMO

**Comment by gsantner** [comment]
Want to keep it simple: Just do it when no conflict. And if conflict, just ask - overwritd YES/NO
