### ISSUE TITLE
The editor activity shows up as a separate entry from the file browser activity in recents, and causes issues when any app switching is involved.

### ISSUE THREAD

**Issue by Asmageddon** [gsantner/markor#1269]
Which causes issues such as:

 * Trying to use "switch to last app" functionality switches back to Markor's file browser activity and not a different app.
 * Markor breaks in split screen and free-floating window modes.
 * When going back to home screen and re-opening markor file editor via recents screen, pressing back closes the editor instead of going back to the file list.
 * It's just generally frustrating.

**Comment by gsantner** [comment]
What is "switch to last app" functionality? Nothing of Markor at last.

As of other points, Markor uses a own Window/Activity by default. This is the only way so you can have multiple files open at same time.

If you dislike this feature for some reason, just disable it in Markor' settings, simple as that.
