### ISSUE TITLE
Add support for syncing with Own/Nextcloud API

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#127]
(issue draft)

#### General information

* **App version:**  v0.2.2

#### Steps to reproduce
First of all, note that I still want to keep Markor lightweight in this terms (e.g. not add like 10 sync API providers). Currently there is no synchronisation API / up/download included in Markor. 

#### Expected result
* <https://github.com/nextcloud/android-library>

**Comment by SpotlightKid** [comment]
Instead of supporting only one specific service, wouldn't it be better to implement webdav, maybe?

**Comment by gsantner** [comment]
In this case I meant to use Nc/Oc via it's own API, but WebDav of course is another option general. The only drawback I see with it, is that this means the drop of offline support with it, because webdav means always connected and save to cloud after save.

**Comment by Offerel** [comment]
Personally I use "Synchronize Ultimate" to sync my notes via WebDAV. "FolderSync" is another option. But the last one does not work with Nginx 1.10/SabreDAV, so that I use the first option.
