### ISSUE TITLE
Add format: Txt2tags (Highlighter, TextActions)

### ISSUE THREAD

**Issue by farvardin** [gsantner/markor#1283]
Hello,

I'm working on a [txt2tags](https://txt2tags.org/) support on Markor. At the moment it's rather functional, but I've just replaced Zim (which I don't use), by txt2tags. Btw, txt2tags syntax is 80% like the Zim one. Another similar markup langage is [Creole](https://en.wikipedia.org/wiki/Creole_(markup)), which came to almost the same reasoning as txt2tags did. 

I've put the fork there: https://github.com/farvardin/markor/

I'm using it every day, but I'm not sure if other people would be interested too. In this case, it might worth considering to make a cleaner version, in complement to Zim and not in replacement, but I suppose it would need some extra work to support this.

**Comment by gsantner** [comment]
hi @farvardin 

I'm open for additional format at Markor.  
Though, I do not know txt2tags. If you say "OK this thing is very very similar to Zim", my suggestion is:

* Use class hierachy (`extends ZimClassXyz`)
* OR make smaller adjustments to ZimClasses so it also works for txt2tags by a different boolean switch

Overall, also add the format to the list of available options. The root/main point of the where the available formats is configured...is the `TextFormat` class: <https://github.com/gsantner/markor/blob/master/app/src/main/java/net/gsantner/markor/format/TextFormat.java#L37>

But please don't destroy/make Zim malfunction.  
So, happy to merge when it's ready! Please open a pull request when you have something minimal viable available, so we can take a look at the state and next steps.

Thanks

**Comment by farvardin** [comment]
Hello,

I've looked how to integrate the txt2tags format in addition, instead of replacing zimwiki (which was just a quick hack to check if it could work as expected).

It seems to work well. 

> But please don't destroy/make Zim malfunction.

Sure! I wasn't my intention of course. Every markup format can coexist with the others ;)

I'll work more on it for a better integration, and I'll propose a pull request when I'll be satisfied!

**Comment by farvardin** [comment]
@gsantner I've made the PR!

It compiles fine for me.
