### ISSUE TITLE
Improve/Customize image Links in Obsidian

### ISSUE THREAD

**Issue by heartnn** [gsantner/markor#1285]
#### General information

* **App version: 2.6.0** 
* **System Android 11:** 

#### Description

Obsidian support `[[]]` for links and `![[]]` for images. `[[]]` is already supported.

**Comment by gsantner** [comment]
please ask at the markdown parser, not at Markor.

flexmark-java

**Comment by ccchan234** [comment]
> please ask at the markdown parser, not at Markor.
> 
> flexmark-java

wow, people think that Markor is the de facto/default Markdown editor! Good to hear that.
