### ISSUE TITLE
Introduce option in settings to hide formatting bar from page view

### ISSUE THREAD

**Issue by arol9** [gsantner/markor#1288]
#### Description

It would be very useful especially on phones with very small screens.

#### Screenshot
![markor_1](https://user-images.githubusercontent.com/80759040/111812659-1bb26180-88b7-11eb-9615-120399109bd8.png)

**Comment by gsantner** [comment]
No sorry, this is one of the most major features. We already had hiding in the past there were always sone ("cheap") devices which had problems with the layout and way we have this.

**Comment by arol9** [comment]
That's fine but I guess you wrongly assumed that everybody uses markor the same way (most people are not devs)


You'd be surprise how unimaginably different this app is used by most people


> there were always sone ("cheap") devices which had problems with the layout

this comment kinda has discriminatory connotation, status wise

**Comment by gsantner** [comment]
> That's fine but I guess you wrongly assumed that everybody uses markor the same way (most people are not devs)

No assumption, the bottom toolbar for quick actions for the numerous edit helpers IS one of the major features of Markor.

> this comment kinda has discriminatory connotation, status wise

Sorry to say, but that is the reality - a cheap 256MB RAM Android 4.1 from 2012 [i.e. `old car without servo`] just IS NOT a high-end 2021 phone

**Comment by lokesh-krishna** [comment]
I think the point they were trying to make is that if all the actions were disabled then the bar might as well be hidden at that point. That's the use case I thought of too when I came here to open an issue and found this. Nothing at all to do with performance. Just aesthetics.

Is that something you might be willing to consider? Automatically hiding it if all options are disabled?
