### ISSUE TITLE
Shortcut to file doesn't work

### ISSUE THREAD

**Issue by sivaraam** [gsantner/markor#1289]
#### General information

* **App version:** 2.6.0
* **System:** Samsung SM-J111F running Android 5.1.1

#### Description
When I add a shortcut to a file using file menu -> Share -> Create shortcut, the shortcut is created successfully. But when I click on it, I only get "App isn't installed".

#710 looks similar.

#### Log
```
I/ActivityManager(  804): Killing 28291:net.gsantner.markor/u0a238 (adj 15): DHA:empty #8
I/Timeline(27297): Timeline: Activity_launch_request id:net.gsantner.markor time:73535037
W/ActivityManager(  804): Permission Denial: starting Intent { act=android.intent.action.VIEW dat=file:///<SANITISED>/The_Note.md flg=0x14000000 cmp=net.gsantner.markor/.activity.DocumentRelayActivity bnds=[20,50][130,190] } from ProcessRecord{3768fe4 27297:ch.deletescape.lawnchair.plah/u0a24} (pid=27297, uid=10024) not exported from uid 10238
E/BaseDraggingActivity(27297): Unable to launch. tag=ShortcutInfo(id=243 type=SHORTCUT container=desktop screen=3 cell(0,0) span(1,1) minSpan(1,1) rank=0 user=UserHandle{0} title=The_Note) intent=Intent { act=android.intent.action.VIEW dat=file:///<SANITISED>/The_Note.md flg=0x14000000 cmp=net.gsantner.markor/.activity.DocumentRelayActivity bnds=[20,50][130,190] }
E/BaseDraggingActivity(27297): java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.VIEW dat=file:///<SANITISED>/The_Note.md flg=0x14000000 cmp=net.gsantner.markor/.activity.DocumentRelayActivity bnds=[20,50][130,190] } from ProcessRecord{3768fe4 27297:ch.deletescape.lawnchair.plah/u0a24} (pid=27297, uid=10024) not exported from uid 10238
```

**Comment by gsantner** [comment]
does it work if you enable "special launchers" in the app settings?

**Comment by sivaraam** [comment]
If you mean "General > Launcher (Special documents)", that's already turned on. If you mean something else, kindly let me know.

**Comment by gsantner** [comment]
Yes this one, might require a reboot

**Comment by sivaraam** [comment]
It's been turned on for long. The special document shortcuts (To-Do, QuickNote) work fine. Only the shortcuts to specific documents don't work.

**Comment by gsantner** [comment]
OK, so for both, new created and existing ones?

**Comment by sivaraam** [comment]
> 
> 
> OK, so for both, new created and existing ones?

Yeah.

**Comment by gsantner** [comment]
which android Launcher app?

**Comment by sivaraam** [comment]
I tried the with the one that came with the phone, OnePlus launcher.

**Comment by gsantner** [comment]
@sivaraam 

Does it work better now with the latest Markor release?

**Comment by sivaraam** [comment]
Yeah. It does appear to be working fine now. Thanks!
