### ISSUE TITLE
Images from local filesystem loaded in preview

### ISSUE THREAD

**Issue by raschix** [gsantner/markor#129]
#### General information

* **App version:**  0.2.2
* **Device:**   BQ Aquaris X
* **Android Version:**  Android 7.1.1

#### Expected result

**What is expected?**
Images are not shown.

**What do you see  #instead?**
An image place holder.

#### Steps to reproduce

The last available version on F-Droid (0.1.5) shows the images. I can't test other versions (0.2.1 and below). No APK available.

**Comment by gsantner** [comment]
Your bug report lacks a lot of details..

* WHERE are images not shown? In the preview?
* Which images? Source?
* Markdown example line
* Firewall activated, Markor blocked?

I've running current latest version, which shows image, as 0.1.5 and 0.2.1 doing aswell:

![screenshot_20171117-101924](https://user-images.githubusercontent.com/6735650/32939832-22aeaa30-cb81-11e7-8f59-850c4dc80c22.png)

**Comment by raschix** [comment]
The images are not shown in the preview.
The images are in a sub folder named "media".
No firewall, no blocking of Markor.

Here an Example:
`![test](media/image.jpg)`
I have also tested the absolute path `/storage/...`

Here a link for the example include a screen: https://www.geomontan.de/test/

**Comment by gsantner** [comment]
thanks, need to look into it

**Comment by gsantner** [comment]
You can try current git version if you want, should work again now
