### ISSUE TITLE
todo.txt: Browse tags/projects does not show up onLongClick

### ISSUE THREAD

**Issue by 0815horsti** [gsantner/markor#1292]
#### General information

* **latest version of markor** 
* **System:** 
- Android 11 on Samsung Galaxy Note 9
- German language
- Nova Launcher Prime

#### Description

When long-clicking on the "tags (@)" button in my todo.txt file the add function changes to filtering to filter all tags starting with an "@".

This should be possible with the "project" button to give an overview of the tasks of all projects (e. g. "+something").

Bug or feature?

**Comment by gsantner** [comment]
Feature.

Long press = browse existing projects/tags.  
Short press = add new project/tag to current todo line.

**Comment by 0815horsti** [comment]
Nope. 

Long press = does not browse ..

I can reproduce it.
- open my todo.txt file
- switch to edit mode
- short press on that button => add project
- long press => also add project
