### ISSUE TITLE
[feature request] disable auto save

### ISSUE THREAD

**Issue by JunkyardCat** [gsantner/markor#1293]
Hi is it possible to disable auto save? And in place just put in a save button to manual save

**Comment by gsantner** [comment]
No there is no such option.

**Comment by JunkyardCat** [comment]
Will you be implementing one in the future?

**Comment by gsantner** [comment]
Not considering it.

**Comment by gsantner** [comment]
Not considering it.
Just makes sad faces of people with lost important information, because they accidentally swiped the app away, and forgot to press save.

**Comment by JunkyardCat** [comment]
@gsantner 
im not saying to enable the "manual save" by default. What im saying is just give some people the option to do this
