### ISSUE TITLE
[duplicate] Recursive search

### ISSUE THREAD

**Issue by adelobosko** [gsantner/markor#1294]
I am not strong on android / java development.
Could we search by context, simple steps:

// Step0() method
0)  Creat new thread / task ==> currentT
    ==>
1) Get the current directory.

2) Get all files and subdirs of the current directory

3) Find directories and files by name 
      (add to the search result: paths to dir/file, count of results (for configuring search and taking by chunks if apparat is low (for ex. get first 100, then skip 100 and take next 100, skip 200 take 100...))

4) Search context in all files in the current directory
    4.1) create something like StreamReader

    4.2) read file line by line
    (or by chunk if you configure, but do not forget about offset that depends on search text length (for ex. chunk = 100, search text length = 10 symbols, get(0,100), get(80-180), get(160-260,get(240-349))

    4.3) search all includes of search text into the current line / chunk

    4.4) add the current line and character index to the search result (group by file path)
    (and if configure.IsShowPreview == true then move intto searchResult configure.PreviewSymbolsCount behind search index:
    ex. line "abcd 12345 6 123 TEST 123545 gsads", searchText = "test", if PreviewSymbolsCount == 10 => resultPreview = line.Skip(index-PreviewSymbolsCount ).Take(searchText.Length+PreviewSymbolsCount *2) 
    => resultPreview  = line.Skip(16-10).Take(4+10*2) => line.Skip(6).Take(24) => "2345 6 123 TEST 123545 "

 5) Get all directories of current directory
     5.1) recursion to step 0
     foreach(var directory in currentDirectory.GetDirectories())
     {
        var t = Step0(directory, ... searchResult..., ...config...)
        t.Wait();
     }

  6) start currentT

  7) return currentT

8) mainTask.Wait(), wait for until all task ending...

9) show searchResult...

it does not take too much memory and CPU, as you can configure a search:
    - read file by lines or chunks; 
    - (get all) get every N search result (then click the "get next" button and get next N);
    - (not)use infile search;
    - (not)show preview;
 
Could somebody do this, as I think people who know Java will do it faster and better than I...
if not I will try it do myself then.

**Comment by gsantner** [comment]
Use search.  
It has been said numerous times that Markor won't get recursive file search.

**Comment by adelobosko** [comment]
> It has been said numerous times that Markor won't get recursive file search.

Ok. What about adding a subdirs to the queue instead of recursion?
