### ISSUE TITLE
First tag or category is added twice when "append" is enabled

### ISSUE THREAD

**Issue by ljb279** [gsantner/markor#1299]
#### General information

* **App version:**  Markor-2.6.0(122) from F-Droid
* **System:** Android-10

#### Description
If you enable "Settings > todo.txt > Append contexts and projects", then the first tag (project) or category (context) that is added to a TODO item with the buttons gets added twice.

Steps to duplicate:

1. Use Settings to enable "Append context and projects" under todo.txt.
2. Open a todo.txt file, or create a new one.
3. Tap Enter to create a new item.
4. Tap either the @ (add context) button, or the ticket (add project) button. Select from the list or type a new item and tap OK.

Result: The selected or entered `@tag` or `+tag` is added twice, like this:
   `2021-03-31 @shop @shop`

I think this started with v2.6.0 but I'm not sure.

**Comment by gsantner** [comment]
Already fixed, not released.
