### ISSUE TITLE
Duplicated setting in v0.1.2

### ISSUE THREAD

**Issue by milouse** [gsantner/markor#13]
#### General information

* **Device:**   Fairphone 2
* **Android Version:**  Fairphone Open 17.09.3  (Android 6.0.1)
* **App version:**  v0.1.2

#### Steps to reproduce

1. Open Markor
2. Go to burger menu, settings
3. Look at the different prefs

#### Expected result

Settings should be different

**What do you see instead?**
« Hide status bar » appears twice.

That's because the same labels are used for `pref_key__is_overview_statusbar_hidden` and `pref_key__is_editor_statusbar_hidden` (see lines [32](https://github.com/gsantner/markor/blob/master/app/src/main/res/xml/preferences.xml#L32) and [87](https://github.com/gsantner/markor/blob/master/app/src/main/res/xml/preferences.xml#L87) of `preferences.xml` file)

**Comment by sjmduncan** [comment]
One is for the notes list page and the other is for the editor/preview, the editor/preview one is broken (#14).

This should just be one setting for the whole app, I can merge those and fix the broken option unless there are any objections?

**Comment by gsantner** [comment]
I wanted (and want to keep it like that). I want the app to be useable fullscreen in editing view, while I want to be able to browse normally with visible clock statusbar and so on.
