### ISSUE TITLE
todo.txt: Settings option for always-visible @contexts

### ISSUE THREAD

**Issue by harshad1** [gsantner/markor#1302]
Markor will list all the projects and contexts available in the `add projects` and `add contexts` dialogs respectively.

However, if I delete (or mark as done and archive) the last task with a context or project, it is no longer in the list and I have to type it again.

We should have a setting where a user can enter a (space separated) list of projects and contexts.

I.e for example

```
@home @pc @work +work +garage 
```
These will then always be available in the context

**Comment by gsantner** [comment]
similar was there in the past and people were just confused about it

**Comment by harshad1** [comment]
Just needs a good enough description then? Its a pretty useful feature...
