### ISSUE TITLE
[feature request] option to disable auto save

### ISSUE THREAD

**Issue by JunkyardCat** [gsantner/markor#1303]
Hi is it possible to add an option to manually save files?. The default settings will still be auto save so that other people who likes auto save dont need to change anything

**Comment by gsantner** [comment]
There is an button to manually save at any time. disable auto save is not planned currently, too many tears because people kill the app and forget to save.

**Comment by JunkyardCat** [comment]
@gsantner 
Im not saying to disable auto save by default. Just have the option to disable auto save for users like me.

What this means is that auto save will still be here but can be disabled by going into option

**Comment by harshad1** [comment]
Note that many actions operate on the file (file information, for example) and not the text view contents. These implicitly save the file.

**Comment by JunkyardCat** [comment]
@harshad1 
I see but im fine looking at outdated info if ever i will look up file information while editing before saving the file

**Comment by JunkyardCat** [comment]
i checked the thread you mentioned @dnngll but i have to disagree. i just want an option to switch to normal mode i ma not saying to remove auto save i just want an option to choose to manual save.

so what this means is that all user will be defaulted to have auto save

**Comment by dnngll** [comment]
Hello @JunkyardCat,

thanks for your input. I don't quite get your point though: We want different things, and one doesn't negate the other (however, @gsantner already stated that he's not planning to implement #1303). Or did I misunderstand?

In https://github.com/gsantner/markor/issues/1419#issuecomment-904016195 I was just referring to @gsantner's comment because I thought, that https://github.com/gsantner/markor/issues/1419#issuecomment-904013447 wasn't valid.

**Comment by gsantner** [comment]
hello, there is already #1419 about this topic. Please have this discussion there.

And let's see what future brings.

**Comment by gsantner** [comment]
One pretty simple thought: What if you get a button at the top toolbar - `Close file without saving`. Clicking it closes the file and the original file remains as is. No settings option or alike.

Manual save button is available as well, since quite some time now.

Would this solve the problem?

**Comment by JunkyardCat** [comment]
@gsantner 

Can i ask what is it that wont work out? can you give more concrete example? is it the viewing real time of markdown file in preview mode? is it the auto parsing of todo?

For me I think itll work out. On top of my head i think the one thing thatll not work as expected is the preview of the markdown when clicking the preview button since its not yet saved and also i guess the todo wont be able to auto apply its thing(i dont really know whats it called. its the one where you put in carriage return and it automatically parses the entry before accordingly).
i can live without those things.

**Comment by tengucrow** [comment]
This fall begin I begin to notice that sometimes Markor save information in the wrong time and past my will, so lost important info in critical situation. 

Closes incident happened yesterday - find todolist duplicated by Syncthin as conflicted - (todo.txt / todo.syncthing-conflicted......). Remove todo.txt and rename conflicted version to todo.txt (all inside Markor) and... in an hour I find out that Markor return old todo.txt on place and lost everything important.

So it would be great to see an option to make Markor behave more predictably - save everything when it needs to be saved and not save it when it is not needed.

It can even be not only "disable autosave" - it can be a button "save the file now, close it completely and do not touch it again until it is opened again." Smart features lead to unpredictable behavior and struggle with editor autosave :(

**Comment by harshad1** [comment]
@gsantner 

> Remove todo.txt and rename conflicted version to todo.txt (all inside Markor) and... in an hour I find out that Markor return old todo.txt on place and lost everything important.

I think what is happening is that `todo.txt` (or quicknote) are modified in the file manager, the new version is overwritten by the text in the tab.

I.e.

1. Todo.txt loaded into tab
2. Todo.txt file changed
3. On exit, text from tab is saved, overwriting the changed file

I will have to think about how to address this.

**Comment by gsantner** [comment]
Tabs: This is what I assume as well. Didn't have time to write it together though. I thought about generally disabling file management (delete/move/overwrite) for these two files.

> It can even be not only "disable autosave" - it can be a button "save the file now

There is a save button when you open a file. Click it, swipe the app out. This is what you asked for?

> other comments

And no, I don't consider adding up complexity just again after harshad1 and me fixed/improved lots of things,  """just to make everybody here happy""".  
If someone REALLY want changes, start contributing to the project and make a solution that not makes up more potential issues. Thanks.

**Comment by tengucrow** [comment]
Alas, it wasn't tabs todo.txt - it was ordinary file with .todo.txt extension. I don't use a regular todo.txt - I use a set of todo files named by contexts (city.todo.txt, comp.todo.txt etc.). To my shame, it's hard to say now was it Markor or Syncthing fault. 

Personally I think, that there is no other convenient and feature packed editor on the f-droid. After datestamp feature, markdown and filesystem as notes keeper - it's hard to want more.

**Comment by tmancini85** [comment]
> One pretty simple thought: What if you get a button at the top toolbar - Close file without saving. Clicking it closes the file and the original file remains as is. No settings option or alike. Manual save button is available as well, since quite some time now. Would this solve the problem?

About this proposal, since meanwhile the auto save logic was changed to be more defensive, a _Close file without saving_ button, maybe in the three dots menu, would be great. It will need a popup asking for confirmation before closing, as usual in this cases to avoid misclicking and losing all the work. 

An alternative could be the possibility to undo all the changes by long pressing the undo button, since cancelling a lot of edits character by character can be very long.

**Comment by alexlyzhov** [comment]
(This issue doesn't seemto be about reload but it [was requested](https://github.com/gsantner/markor/issues/1419#issuecomment-915553241) to discuss this here)
https://github.com/gsantner/markor/issues/1419 discussed the issue where Markor doesn't load any changes made by other apps and I just wanted to note that it's still present. In particular, when I edit anything, it syncs to my phone via syncthing, and then I switch to Markor with Quicknote open, it immediately silently overwrites Quicknote contents with stuff from its buffer. I wonder if this is in the wontfix status, and if so, why?

Currently I solve this by having 2 scratchpad.md files where one is edited from the laptop and one is edited from my phone and both are synced for reading via Obsidian. But this doesn't seem elegant.

**Comment by gsantner** [comment]
I close this now as won't fix.

At Markor very very much time goes into making file operations work properly. Every year that passes, every new android version with whatever new file limitations, every new device that gets out...makes it harder to get things properly saved.

And, I don't want to add another point to that long list of quotation to make everything correctly saved. It's more then enough. 

So here are my suggestions:

1. If you dont want to do something with a file...dont open it?
2. If you only want to view a file...then open the view mode.
3. You only want to temporary change something? Make a copy. Make a backup. Then work on the original.
4. You are too lazy to make backups or safety copies? Use some  backup or sync software that  does it for you. Syncthing has trashbin versioning (last X versions) for example.
5. None of it works for you? Pity. You can't get everything you want. Use some other app if this all is a dealbreaker to you. The time and energy of us developers is limited.

Thank you.
