### ISSUE TITLE
Filenames with newlines

### ISSUE THREAD

**Issue by contrapunctus-1** [gsantner/markor#131]
Markor can accidentally create filenames with newlines in them. If the user doesn't specify a name for a new file and the initial X characters in its contents (used to make the filename) contain a newline, the resulting filename will contain a newline...which makes the file a pain to work with in other programs. (e.g. if you're using Syncthing to sync your notes to your laptop and use other programs on them - most tools break with such filenames)

**Comment by gsantner** [comment]
please fill out the form that is there per default..

which version are you using

**Comment by contrapunctus-1** [comment]
Sorry about that, the form didn't appear in FastHub-Libre, for some reason.

I'm using Markor v0.1.5 from F-Droid.

**Comment by gsantner** [comment]
you can download latest version from issue 95, gplay or  aait till fdroid fixes stuff
