### ISSUE TITLE
Auto mode for the light/dark theme is always dark

### ISSUE THREAD

**Issue by Hund** [gsantner/markor#1318]
#### General information

* **App version:** 2.6.0 from F-Droid
* **System:** Pixel 3a with Android 11

#### Description

When I set the theme to be in automatic mode it defaults to dark mode, no matter if I have the battery saving feature enabled or disabled.

I don't like dark mode as it's bad for your eyes, but I sometimes use it in bed when I don't want to disturb my partner.

**Comment by gsantner** [comment]
auto mode is by day time, nothing else

**Comment by Hund** [comment]
That's not how auto mode works. Even if that's how you do it, it doesn't work because it's day here now.

**Comment by Hund** [comment]
>There are three ways to enable Dark theme in Android 10 (API level 29) and higher:
>
>* Use the system setting (Settings -> Display -> Theme) to enable Dark theme.
>* Use the Quick Settings tile to switch themes from the notification tray (once enabled).
>* On Pixel devices, selecting the Battery Saver mode enables Dark theme at the same time. Other OEMs may or may not support this behavior.

https://developer.android.com/guide/topics/ui/look-and-feel/darktheme

It's always recommend to follow the basic guidelines for how to design applications for Android.

**Comment by Hund** [comment]
Ignoring this issue won't make it go away..

**Comment by gsantner** [comment]
Crying does neither. Go ahead and make changes and a pull request. And keep in mind, Markor also supports devices ~SDK16 which do not have any system wide Dark/Light/Powersave setting.

**Comment by gsantner** [comment]
Crying does neither. Go ahead, make changes and a pull request.

And keep in mind, Markor also supports devices ~SDK16 which do not have any system wide Dark/Light/Powersave setting.
The current implementation works in the same way for any OS version.

**Comment by Hund** [comment]
I'm not crying, I was trying to make a rather stubborn and hostile person to understand that they where doing it wrong.

Don't worry though, it's not like I'm keeping this application and I'm not coming back here again. I'm confident that there's some competent text editor out there by an actual friendly developer.

Good luck with whatever you're trying accomplishing here! :)
