### ISSUE TITLE
[Feature request] Vim folds

### ISSUE THREAD

**Issue by Hund** [gsantner/markor#1319]
I'm a heavy user of Vim and folds. It's a must have feature to be able to handle large documents.

A fold is created by enclosing a part of the document with three opening and closing brackets like this:

```
{{{
Example text.
}}}
```

It's also possible to add a title to the fold:

```
Example title {{{
Example text.
}}}
```

In Vim it looks like this:

![vim_folding](https://user-images.githubusercontent.com/320498/115137139-6d6c1a00-a024-11eb-98a7-13dfa3c3762c.png)

I would argue that's it's even more important with folds on handheld devices with rather limited text editing features and tiny screens.

I hope this is something you would consider adding to Markor.

**Comment by gsantner** [comment]
#922
