### ISSUE TITLE
Request: Touch to toggle checkboxes

### ISSUE THREAD

**Issue by toridnyc** [gsantner/markor#1320]
#### General information

* **App version:** 2.6.0 (122)
* **System:** Android 11

#### Description

I love that Markor renders checkboxes in a Markdown file. I would like to be able to toggle a checkbox while if view mode on a Markdown file, and subsequently have Markor change the `- [ ]` to `- [x] `

**Comment by gsantner** [comment]
you can find such a checkbox button in the bottom list of actions.

**Comment by toridnyc** [comment]
Thank you. I didn't realize that button existed in Edit mode on an .MD file as well as a todo.txt file.
