### ISSUE TITLE
Wrong string in Swedish translation.

### ISSUE THREAD

**Issue by 1jss** [gsantner/markor#1321]
The Swedish string for search should be "sök", not "söc" as it says now. Small annoyance that I won't pull down the entire repo to correct, but would love to have corrected.

File: /app/src/main/res/values-sv/strings.xml
Line: 41
Remove: Söc
Add: Sök

Thanks for an otherwise great app!

**Comment by gsantner** [comment]
Translations are done at Crowdin, no code changes required. Please head over to Crowdin and correct the translations. [Link](https://crowdin.com/project/markor/invite)

Thanks

**Comment by 1jss** [comment]
I did this, but the string hasn't been updated yet.

**Comment by gsantner** [comment]
@1jss   
I found on Crowdin. I gave you the proofreader for swedish. You can now click the checkmark button beside your suggested translations. As soon new translations are accepted, they get pulled in.

thx

**Comment by 1jss** [comment]
Thanks! I'll do it right away!
