### ISSUE TITLE
Add a "sort by last opened" option

### ISSUE THREAD

**Issue by brunetton** [gsantner/markor#1324]
#### General information

* **App version:** 2.6.0 (122)
* **System:** Android

#### Description

I'm using Markor as my main notes taking system on my phone (so THANKS for that ! This is pretty awesome) but I miss a way to quickly find the last notes I **opened** (not edited). I think this is the default behavior of google keep (not sure).

I understand that implementing this would imply adding a way to remember somewhere last accessed dates (I don't know if Android files systems does it by default or not) but if I'm not the only one that needs this it'll be amazing !

Thanks

**Comment by gsantner** [comment]
In the top menu of file browser you have an option for browsing "recent" files, and another one for "popular" files. These files are from any folder, not only from a single one.  
You can also set those as default to open when you start markor.


Hope this helps.

**Comment by brunetton** [comment]
Thank you, I didn't seen those options.

But I tried a while and I didn't found a way to actually have the last opened notes sorted by last viewed date.

Steps:

- enable "popular files" view
- open a note that's not the first in the list nor the last
- close this note (so come back to the notes list)
- => here I thought that the note I just opened would jump to the top of the list of recently opened notes
- but the notes order didn't changed at all

Did I miss something ?

Thanks

**Comment by gsantner** [comment]
it will just appear in the list of mentioned groups. sorted still by what you selected on top (i.e. by name)

**Comment by brunetton** [comment]
> it will just appear in the list of mentioned groups. sorted still by what you selected on top (i.e. by name)

I'm not sure to understand what `mentioned groups` but I suppose it's one of ["recent files", "popular files", ...]. If I understand well the sort is still active when I select "recent files". 

In that case I'm sorry but I still can't get last opened files; can I ?

Rewording of my request: if I open "note.md" file and come again to the notes list; if I select "recent files" I would except this "note.md" file to be at the top of the "recent files" list. 

Thanks a lot

**Comment by brunetton** [comment]
> They contain ~30 popular/recent files. Sort order is by filebrowser top bar. That insert/last opened order has no effect here, except it is on the list and will disappear last.

So I still don't get: can you tell me if there's a way to combine filters/mentioned groups to see the last open file on the top of the notes lists ? (this is the purpose of this issue that you've closed very quickly) 

Thanks again
