### ISSUE TITLE
Per-file font size

### ISSUE THREAD

**Issue by boulderob** [gsantner/markor#1326]
#### General information

* **App version:** 
v2.6.0(122)

* **System:** 

Android 10 (galaxy tab A7 SM-T500)

#### Description

This is probably a feature request.

It appears that Markor allows you to change the Font size at under Settings which is three hops away.  Most readers and editors that i've used allow you to change this right from the document window you are editing / viewing because it's such a common operation.

Sure, setting a global default for font size and font once in settings will cover a lot of cases.  But for whatever reason, certain documents and document types just look better and are easier to work with using a larger font size and being able to switch this back and forth as you change between different documents on the edit interface itself might be useful to some.

Just a suggestion.  Thoughts?

**Comment by harshad1** [comment]
@gsantner Per-document font size would be reasonable imo.

**Comment by gsantner** [comment]
After `Format` one of the first things came to my mind

**Comment by gsantner** [comment]
After `Format` one of the first things that came to my mind

**Comment by harshad1** [comment]
I will make a pr for this over the coming weekend
