### ISSUE TITLE
preview bug in Dark theme 

### ISSUE THREAD

**Issue by shockergit** [gsantner/markor#1339]
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<html><head><title>Product Key List</title></head>
<body>
 <h3>Product Key List</h3>
<p><table border="1" cellpadding="5"><tr bgcolor="E0E0E0">
<th>Product Name
<th>Product ID
<th>Product Key
<th>Installation Folder 
<th>Service Pack
<th>Build Number
<th>Computer Name
<th>Modified Time
<tr><td bgcolor=#FFFFFF nowrap>Windows 10 Home Single Language<td bgcolor=#FFFFFF nowrap>111111-43263-97001-AAOEM<td bgcolor=#FFFFFF nowrap>DDDD-YYYYY-SSSS-AAAA-XXXXX<td bgcolor=#FFFFFF nowrap>C:\Windows<td bgcolor=#FFFFFF nowrap>&nbsp;<td bgcolor=#FFFFFF nowrap>19042<td bgcolor=#FFFFFF nowrap>VIVOBOOK<td bgcolor=#FFFFFF nowrap>2/19/2021 11:20:36 PM
</table>

</body></html>

**Comment by shockergit** [comment]
The table is grayed out in dark mode in markor

**Comment by aubreyz** [comment]
Are you sure this is data you want on the web?

**Comment by gsantner** [comment]
I masked parts of the key.

**Comment by gsantner** [comment]
You have to take care on your own, if you set custom colors somewhere, you have to take care of text and background color. You explicitley set bgcolor.

![Screenshot_20210508-172448](https://user-images.githubusercontent.com/6735650/117544587-74ce8400-b022-11eb-9b9d-4ca5ccbd8d6d.png)


Markor dark mode, as it is:

![d](https://user-images.githubusercontent.com/6735650/117544531-4355b880-b022-11eb-9c3e-60b870a975b2.png)


Closing as this is not Markor's fault, you set a color and it does just what you asked it for.

**Comment by shockergit** [comment]
> I masked parts of the key.

Thanks it was a digital license from motherboard

**Comment by shockergit** [comment]
> You have to take care on your own, if you set custom colors somewhere, you have to take care of text and background color. You explicitley set bgcolor.
> 
> ![Screenshot_20210508-172448](https://user-images.githubusercontent.com/6735650/117544587-74ce8400-b022-11eb-9b9d-4ca5ccbd8d6d.png)
> 
> Markor dark mode, as it is:
> 
> ![d](https://user-images.githubusercontent.com/6735650/117544531-4355b880-b022-11eb-9c3e-60b870a975b2.png)
> 
> Closing as this is not Markor's fault, you set a color and it does just what you asked it for.

Thanks i noticed it. I just exported the file from an app. When i opened it its not showing anything in the table. Just forget to check the bg

**Comment by gsantner** [comment]
I will delete this issue in favor of your key exposure
