### ISSUE TITLE
Move tool cannot transfer Files & Folders 

### ISSUE THREAD

**Issue by ChillllHOLA** [gsantner/markor#1342]
* **Markor Version 2.6.0** 
* **Android 6.0** 

Hi! Whenever I select a file or a folder and click on the three dots to move them to the correct place, what happens is the move tool ends up not working and **the app always crashes right afterwards.** 

This effectively makes you unable to ever move your files and folders again from a specific folder in your system storage, and it forces you to delete them and make new ones. 
Any idea on how to fix this?

**Comment by gsantner** [comment]
please search issues
