### ISSUE TITLE
Word-corrector+Auto-save+Undo inconsistency?

### ISSUE THREAD

**Issue by riveravaldez** [gsantner/markor#1343]
#### General information

* **App version:** 
v2.6.0 (122) F-Droid

* **System:** 
LineageOS 17.1-20210507-NIGHTLY-surnia
Moto E LTE

#### Description
Seems like some kind of inconsistency between the word-corrector, the auto-save setting and also the Undo action: sometimes when you put your finger in a mispelled word and then select the right spelling from the keyboard options the new word appears in an apparently random place, even overwriting other previously written words, and the Undo works strange (not always fixing it in one action). Saving manually the file and trying again seems to solve the issue, temporarily (but I'm not sure of this).

Thanks a lot, Markor is wonderful. ^_^

**Comment by gsantner** [comment]
word correction and applying the fix is done by keyboard/android, we don't have any implementation here
