### ISSUE TITLE
Q: How does Tab character setting work

### ISSUE THREAD

**Issue by Baptistou** [gsantner/markor#1344]
According to #585, a new option Settings > Edit mode > Tab width was added (experimental features must be enabled) , and according to this [discussion](https://bleepcoder.com/markor/269419403/project-discussion-general-chat-questions) :

>Ah. The fundamental issue is that we are using this setting for 2 different things.
>
>1. The number of spaces = one tab
>2. Number of spaces to indent / de-indent by
>
>These are 2 different things and should have 2 different settings. Tab size should be hidden and have default = 1. I will make a PR to add a separate setting for indent size with default = 4 (per markdown)

I have existing markdown and text files which contain tab characters and I noticed inconsistent behaviour between preview mode and edit mode :
- If tab width = 1 (default value), then tab character is displayed as 8 spaces in preview mode and 1 space in edit mode.
- If tab width = 4, then it is displayed as 8 spaces in preview mode and 2 spaces in edit mode.
- If tab width = 8, then it is displayed as 8 spaces in preview mode and 4 spaces in edit mode.

In all cases, the option does not seem to have any effect in preview mode and does not have correct result (tab width is divided by 2, indent not aligned) in edit mode.

I guess this option is still under development. Is there some documentation about this ?
Is it possible to set tab width to 4 spaces like indent/de-indent and have a consistent behaviour between modes ?

**Comment by gsantner** [comment]
> In all cases, the option does not seem to have any effect in preview mode and does not have correct result (tab width is divided by 2, indent not aligned) in edit mode.

As you typed yourself, it is in "Edit mode" settings. What did you expect for preview mode then? Use CSS to control view mode, however you like it.

**Comment by Baptistou** [comment]
> As you typed yourself, it is in "Edit mode" settings. What did you expect for preview mode then? Use CSS to control view mode, however you like it.
> 
> I checked code, and tab width is on master only applied in Edit Mode / for syntax highlighter. Thats all I can tell say, nothing about Preview Mode.

Ok, indeed it makes sense. So I added the CSS rule `tab-size: 4` in Settings > Preview mode > Inject head and that works.
Thank you for you help. Nice app :smile:

**Comment by gsantner** [comment]
> tab-size: 4

Exactly
