### ISSUE TITLE
Please add option to enable line numbers in editor

### ISSUE THREAD

**Issue by ShreeRaghav2004** [gsantner/markor#1349]
Please add option to enable line numbers in editor

_Originally posted by @ShreeRaghav2004 in https://github.com/gsantner/markor/issues/95#issuecomment-842174550_

**Comment by harshad1** [comment]
Note that this will have to work with larger headings and will have to handle wrapped text correctly.

**Comment by gsantner** [comment]
please use search, this was already requested.
