### ISSUE TITLE
FeatureRequest : Add a Agenda.txt nav_bottom tab ?

### ISSUE THREAD

**Issue by brvier** [gsantner/markor#1350]
### Feature Request

While i use todo.txt to tracks todos, i also used a Agenda.txt file for events which have a quite simple form :

```
YYYY-MM-DD 15:04 - 16:04 Event description
YYYY-MM-DD 18:04 Event 2 description
YYYY-MM-DD 18:04 Event 3 description
```

So the main feature :
- archive past events
- sort events
- set a date / time quickly

But the nav bottom bar is currently quite full. So moving "more" tab in the top right menu (like parameters) is probably the right things to do:

![image](https://user-images.githubusercontent.com/360591/118875376-48e9b300-b8ec-11eb-9b48-3652d6435bcf.png)

Interested in such feature ? or should i keep my own fork ?

**Comment by gsantner** [comment]
I don't quite get what the difference to normal todo.txt here is? I use todo.txt sometimes in quite the same fashion to temporary write down working times.

If it's really just about adding a new button in the bottom area, with default todo.txt format: No, every file there is read in paralell at startup, and at same time it would be too much tabs.

By the way, you can also change QuickNote format to todo.txt and use that.

**Comment by brvier** [comment]
It's a calendar containing future events (actually 50 events in future), not to write down working time but to schedule futur events, meetings, meetups. Putting them in todo.txt made too much noise around real todo.

Also i use a agenda.txt format which is a little bit différent mainly for datetime.

But i can understand, that may be out of scope of how you see your app.

To write working time i use a journal.md :)

19 mai 2021 22:12:30 Gregor Santner ***@***.***>:

**Comment by gsantner** [comment]
> It's a calendar containing future events (actually 50 events in future), not to write down working time but to schedule futur events, meetings, meetups. Putting them in todo.txt made too much noise around real todo.
> 
> Also i use a agenda.txt format which is a little bit différent mainly for datetime.


With it, I mean the format "todo.txt", not the filename. The default filename just happens to be todo.txt as well, but you can have as many todo.txt files as you want. I use archive.todo.txt for example as well

**Comment by harshad1** [comment]
Leaving aside the issue of whether we add these features or not, I think actions should go in the Action bar and not in the menu. We can enable / disable and reorder action items, so adding a few more should not be a problem.

Also, it's possible to set a date quickly already: select the date and then press the calendar/date action. Long press the date to select it fast.

**Comment by harshad1** [comment]
A general sort function would be nice though. Sort whole file if no selection, else sort selected lines. This could be its own action for all file types.

**Comment by gsantner** [comment]
Closing this discussion, if somebody wants to contribute to Markor, happy to get help and get it merged. 

However: No, no additional 5th tab in startpage.
