### ISSUE TITLE
Support ISO 8601 and RFC 3339 for Data and Time

### ISSUE THREAD

**Issue by anishmittal2020** [gsantner/markor#1354]
#### General information

* **App version:** 2.6.0
* **System:** Android 10

#### Description

- In Editing mode there is a *Clock shaped* icon, which when clicked, lets us enter date and time in a particular format. Please support formats from **ISO 8601** and **RFC 3339** for Data and Time: 
  - `yyyy-mm-ddThh:mm`, 
  -  `yyyy-mm-ddThh:mm:ss`, 
  - `yyyy-mm-dd hh:mm`, 
  - `yyyy-mm-dd hh:mm:ss`

**Comment by gsantner** [comment]
You can freely enter custom format in the date dialog. Also there is history of previous entered. Everything you should need.
