### ISSUE TITLE
Add format: jrnl

### ISSUE THREAD

**Issue by anishmittal2020** [gsantner/markor#1355]
Can  you please support: [jrnl-org/jrnl: Collect your thoughts and notes without leaving the command line.](https://github.com/jrnl-org/jrnl), just like you support [todotxt/todo.txt: ‼️ A complete primer on the whys and hows of todo.txt.](https://github.com/todotxt/todo.txt)

Most of the interface from todo.txt can be used for this.

**Comment by gsantner** [comment]
feel free to implement it and make a pull request.
