### ISSUE TITLE
Shortcut apps without extension and icons specific to extension

### ISSUE THREAD

**Issue by anishmittal2020** [gsantner/markor#1356]
#### General information

- **App version:** 2.6.0
- **System:** Android 10

#### Description

In the following figure: 2 shortcuts were added:
- The first one by long pressing the Markor icon, and then dragging the file out from the recent files list. This creates **Garching.md** with adaptive icon.
- The second one by opening the file in Markor and the from Menu --> Share --> Create Shortcut.  This creates **Garching** with standard icon.

![image](https://user-images.githubusercontent.com/42092626/120182179-58cb9600-c20e-11eb-8f49-14ad5afa1ccc.png)

#### Desired behavior

- Both methods should be consistent if possible.
- For files with known extensions like txt or md we can have adaptive icon that was txt or md written in the icon, so we can drop the extension from the shortcut.
- So, instead of Time.txt we can have Time with `txt` written inside page shaped icon.

**Comment by gsantner** [comment]
shortcut from share menu are traditional launcher shortcuts, which works on ANY android version. the other are App-Shortcuts introduced by later Android versions.

It makes sense to have both available, and I want to keep both options available.
