### ISSUE TITLE
New-line button doesn't work inside accordion

### ISSUE THREAD

**Issue by gatocinza** [gsantner/markor#1357]
#### General information

* **App version:** 2.6.0
* **System:** Lenovo A2016b30, Android 6.0

#### Description

When working into an accordion the new line button on the action bar doesn't work, neither Enter key on the keyboard. Nevertheless, all< br >, < ol >, < ul >, < li > tags work perfectly. I would say indent doesn't work too.

**Comment by gsantner** [comment]
can you paste your accordion?

**Comment by gatocinza** [comment]
Sure. Here I paste both input and output:

### Input:
[accordion-example.md](https://github.com/gsantner/markor/files/6587022/accordion-example.md)

### Output:
<img src="https://user-images.githubusercontent.com/85074375/120542694-04ace700-c3b1-11eb-9726-050d88464809.jpg" width="250" height="400" />

**Comment by gsantner** [comment]
one two three and  123 don't have trailing `  ` two spaces, but they should work as soon markdown="1" is set.  
As far what the newline button currently does is, create a new textline in editor and jump to it, I don't see anything other apply.

So, just add two spaces:
```
<details markdown='1'><summary>Accordion1</summary>
    - one  <
    - two  <
    - three  <
</details>

<details markdown='1'><summary>Accordion2</summary>
    1. a  <
    2. b  <
    3. c  <
</details>
```

Not sure about the newline button, as never used it. @harshad1  does it work as it is intend it to work currently on master?

**Comment by gatocinza** [comment]
Thanks for the answer. Just in case, I already tried to put trailing spaces, but didn't work too. Neither to put more than one blank space.

**Comment by gsantner** [comment]
might also be a markdown parser issue. mixed markdown and html sometimes is tricky

**Comment by gatocinza** [comment]
I see. Then I guess it couldn't be fix. Nevertheless, thank you for the feedback.
