### ISSUE TITLE
todo.txt: duplicate category inserted

### ISSUE THREAD

**Issue by kostecke** [gsantner/markor#1358]
#### General information

* **App version:** v2.6.0 (122) Gplay
* **System:**
    - Galaxy S-8 (Verizon)
    - Android 9
    - Kernel 4.4.153

#### Description

Two copies of a category tag are inserted in my ToDo.txt when I select a category from the **@** dialog.

**Comment by gsantner** [comment]
#1299

**Comment by kostecke** [comment]
I was not able to find that previous PR.

Sorry to have bothered you.
