### ISSUE TITLE
Migrate to androidx & newer Android architecture

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#1359]
#### General information

* **App version:** 2.x
* **System:** Android 11

#### Description
Remove appcompat from markor and opoc, upgrade to AndroidX. Don't use transformation magic, make adjustments at code & androidx imports.

**Comment by harshad1** [comment]
Why not use the auto migration? Seems to be the recommended route: https://developer.android.com/jetpack/androidx/migrate

**Comment by gsantner** [comment]
I know this one exists, but I prefer to stay away from it (thats why I've mentioned transformation magic).

![grafik](https://user-images.githubusercontent.com/6735650/120541474-37270600-c3ea-11eb-930a-a8894fe811e4.png)

As of applying changes/fixes by android tooling & IDE - yes. But a lot of special/greylist code is also use, which will need special attention - like coloring and showing menu icons.  
Also the current solution for Settings/Preferences will probably will need a bigger rewrite - probably one of the bigger points.

**Comment by harshad1** [comment]
👍

**Comment by gsantner** [comment]
one of my todo.txt shower thoughts says along ` markor file write proxy to /data/ app-temp-dir, read file from intent, write back on clock, use tmp file for java.io.File`. Thats the rough plan I have in mind for coping with newer restrictions. Let aside file browser.

**Comment by harshad1** [comment]
There seems to be some sort of proposed mechanism for requesting all file access for file managers. We can try that first.

Needless to say, this will not affect F-Droid

**Comment by gsantner** [comment]
probably default/gplayFlavor also comes into play for it

**Comment by harshad1** [comment]
Do we want to immitate how syncthing accesses files? I.e. use SAF and  ACTION_OPEN_DOCUMENT_TREE to gain access to a subtree. We will have to ask the user to pick the notebook directory this way. Obviously, we will then not be able to navigate up out of the notebook. But this should meet 90% of a user's needs while meeting android 12's limitations. 

As far as I can tell, we can just use regular `File` access within the notebook directory once permissions are granted.

Do we want to go down this path? It adds a limitation, but makes Markor somewhat more future-proof
