### ISSUE TITLE
Convert Images to Text | Enhancement

### ISSUE THREAD

**Issue by ChiIllHOLA** [gsantner/markor#1360]
#### Description
I could definitely see this is as a feature in Markor possibly in the near future.

With the use of OCR and other repositories that specialize in extracting text from images, we should have the necessary materials to push through with this.

> Cheers, Pete

**Comment by gsantner** [comment]
Too much bloat (size wise) for Markor (lightweight).

You may check one of the other projects I worked on, <https://github.com/gsantner/text-scanner>
