### ISSUE TITLE
Allow set checklist to done/undone in Markdown view mode

### ISSUE THREAD

**Issue by helmut72** [gsantner/markor#1361]
#### General information

* **App version:** 2.6.0

#### Description

I create and use checklists a lot in Markdown. Some Markdown apps or text editors (VSCode, 1Writer on iOS, FSNotes, ...)  allows checklists set to done in their view mode. Set any checklist to done/undone is annoying and error prone in any edit mode.

Please allow set Markdown checklist to done/undone in view mode.

Thank you!

**Comment by gsantner** [comment]
has been answered more than anything else already. use.search.

**Comment by helmut72** [comment]
> has been answered more than anything else already. use.search.

Oh sorry. But then it looks like it"s a popular feature request.
