### ISSUE TITLE
Couldn't mark as favorite more than one file at time

### ISSUE THREAD

**Issue by gatocinza** [gsantner/markor#1362]
#### General information

* **App version:** 2.6.0
* **System:** Lenovo A2016b30, Android 6.0

#### Description

Couldn't mark as favorite more than one file at time.

#### Screenshot

<img src="https://user-images.githubusercontent.com/85074375/120673673-ffa37280-c458-11eb-8bd6-c07642c7f1a7.png" width="170" height="300">

**Comment by gsantner** [comment]
yes favouriting is only shown for one file selected. not planned zo make  change here.
