### ISSUE TITLE
Last line obscured by Android toolbar

### ISSUE THREAD

**Issue by glocalglocal** [gsantner/markor#1364]
Markor v2.6.0, Android 7

In view mode in portrait, the last line of the text is obscured by the Android toolbar (for back etc). In landscape this is not an issue because the toolbar is displayed on the right, rather than the bottom.

**Comment by gsantner** [comment]
I cannot reproduce and you reported the issue without adding screenshot.

**Comment by glocalglocal** [comment]
I didn't think the screenshot would add much to my description but here is portrait: 
![Screenshot1](https://user-images.githubusercontent.com/16408198/120932760-9df83800-c6e6-11eb-8077-b48694c259bd.jpg)
and landscape:
![Screenshot2](https://user-images.githubusercontent.com/16408198/120932763-a3558280-c6e6-11eb-80f5-350fa1c7ee7f.jpg)

**Comment by gsantner** [comment]
I'm sorry but I'm not able to reproduce the issue currently.

**Comment by adelobosko** [comment]
After creating a note the editor is cut the text.
![Screenshot_20210704-003934_Markor.png](https://user-images.githubusercontent.com/56083544/124367608-6fc43480-dc61-11eb-97d7-0fdd88406541.png)

**Comment by gsantner** [comment]
I cannot reproduce, but as you can, can you help to fix the issue?

**Comment by gsantner** [comment]
@adelobosko   
I cannot reproduce, but as you can, can you please help to fix the issue?
