### ISSUE TITLE
Support [my image.jpg](<assets/my image.jpg>) syntax

### ISSUE THREAD

**Issue by HaujetZhao** [gsantner/markor#1365]
Some file or image names may contains spaces. When inserting into Markor, Markor can handle them in this for now: 

1. Transcode the space then put it in, like `[my image.jpg](assets/my%20image.jpg)`

Obviously that way is not so tidy.  

However, with this problem, I looked into the [CommonMark Spec](https://spec.commonmark.org/0.29/#links) , surprisingly, I found that Markdown do support inserting links with spaces! 

> The destination can only contain spaces if it is enclosed in pointy brackets:
>
> [Example 485](https://spec.commonmark.org/0.29/#example-485)
>
> ```
> [link](/my uri)
> <p>[link](/my uri)</p>
> ```
>
> [Example 486](https://spec.commonmark.org/0.29/#example-486)
>
> ```
> [link](</my uri>)
> <p><a href="/my%20uri">link</a></p>
> ```

In terms of the example I mentioned ahead, it would become 

```
[my image.jpg](<assets/my image.jpg>)
```

Which is really tidy and standard. 

But it seems Markor don't support that syntax, right? Will it be cooperated into Markor?

**Comment by gsantner** [comment]
See picture at  https://gsantner.net/blog/2019/03/11/markor-release-v1.7-custom-fonts-linkbox-markdown.html

for possible options. Otherwise, you want to be more on the spec compliant side, so it works with other Markdown tools.

**Comment by tifish** [comment]
Typora editor can handle spaces in image path, and this is the default style when it insert images. It will be convenient to support this style.

**Comment by gsantner** [comment]
But this is not typora. And most other Software that supports Markdown is not typora.

**Comment by HaujetZhao** [comment]
> 

Not a complain, just a correction. `[link](</my uri>)` is not a Typora-specific syntax, but a CommonMark Spec syntax. And Typora don't prefer this syntax. Typora just simply support resolving this syntax, just like other markdown editors. Many editors support resolving this syntax by default (since they use CommonMark as standard reference).

**Comment by gsantner** [comment]
I'm not sure if it's clear, but Markor uses a Markdown parser, but not implements a Markdown parser on it's own. For such bugs, you better ask at the Markdown parser.

Though, commonmark 486 is indeed broken at our Markdown parser, see <https://github.com/vsch/flexmark-java/issues/269>.

Commonmark 485 lets the space remain without converting to %20, hence won't produce a working link.

**Comment by tifish** [comment]
Just a workaround, replace spaces with %20 before rendering：https://github.com/tifish/markor/commit/1eab54db5a2667f1bc6696f2da337380a593f53c

**Comment by gsantner** [comment]
@tifish   
Can you please make a pull request and let's get it merged if it works as expected.  
Please make it for normal links `[]()` as well, not just images `![]()`

**Comment by tifish** [comment]
@gsantner Thanks for your hint. I will refine the code and make a pull request.

**Comment by gmccullo** [comment]
I don't think this works yet. I'm on version 2.8.0. I have a link that looks like this
```md
[story](<00 Book 08 Story.md>)
```
Which is a valid link. But in the preview it is not rendered as a link and does not navigate. But it works as expected if I change it to this:
```md
[story](00%20Book%2008%20Story.md):
```

**Comment by gsantner** [comment]
2.8.0 is over a year old. Update to lateat version.

**Comment by gmccullo** [comment]
Confirmed. It works. What I don't understand is why my version was 2 revs behind because I always keep my apps up to date.

**Comment by gsantner** [comment]
Because the main focus for Markor updates and installation is [F-Droid](https://f-droid.org/de/packages/net.gsantner.markor/), not Google Play. As announced in every recent update release post <https://gsantner.net/blog/2022/07/16/markor-v2.10-custom-file-templates-share-into-remove-tracking-parameters.html#how-to-install--update-markor>.
