### ISSUE TITLE
Have issues with files sometimes not listed at filemanager

### ISSUE THREAD

**Issue by skillhacker-code** [gsantner/markor#1366]
#### General information

* **App version: v2.6.0 (122)** 
* **System: Android** 

#### Description

markor is not loading file properly , it is sometimes showing some notes as empty but sometimes not issue . I am attaching the video can you please fix it 

As you can see in the video notebook folder is loading sometimes but not loading sometimes , markor used to work properly but i am seeing the problem recently .

I also tried many things reinstalled , cleared cache and data , nothing is working .

I love Markor but this is the problem that i have now . 

https://user-images.githubusercontent.com/68536959/121450380-42b19880-c9b9-11eb-88cc-a2cf6c15e5bd.mp4

thank you

**Comment by gsantner** [comment]
Are you sure the 0.NOTES folder still exists? Just looks like some bad filepath got into it.

**Comment by skillhacker-code** [comment]
Yes , it exist i named it 0.Notes because i wanted it to be on top when exploring files . 

Sometimes markor is opening that folder after a long time , 

Sometimes instantly 

Sometimes show i sticky figure which shows no idea .

Thank you

**Comment by skillhacker-code** [comment]
Note than 20 in each folder

**Comment by harshad1** [comment]
> Yes , it exist i named it 0.Notes because i wanted it to be on top when exploring files .

Could you try `0_Notes` and see if the problem persists?

**Comment by skillhacker-code** [comment]
The problem it is sometimes showing file  and sometimes not showing  files.

**Comment by gsantner** [comment]
I will for now close the issues - this means discussion can still go on. But currently don't see something we/I can change as it works here as expected.
