### ISSUE TITLE
Feature Request: Share Into Timestamp/Append-Prepend Options

### ISSUE THREAD

**Issue by smartinick** [gsantner/markor#1368]
Been using Markor for a while now, synching with other devices and sharing markdown files between dokuwiki and obsidian.

what i really like on markor is the share into function as some sort of log - when there's some interesting link to revisit later, i use share into a special file which is meant to be some sort of history/log of interesting links. adding tags for reminders,... this works quite well.

Currently the share into always prepends the shared text with a line containing "---"
-> could this be configurable?
i'd e.g. like to have date/time in a simple bullet list for each shared element:
 - [2021-06-20 10:16] shared-text #mytaglist
using this timeformat (or a setting that allows to configure it using some format-function) i'd also be able to sort the liste later on.

Personally i also add headings for each month, but that's easily done manually once a month.

Adding the date-time text manually each time is a bit of a hassle, therefore this feature request ;)

Thanks for considering!, Martin.

**Comment by harshad1** [comment]
I like this idea and think I would like it too.

I'll start working on it.

Biggest challenge would be to make it clean and user-friendly.

Starting point is going to be todo.txt format, I think. If you share into your default todo file, you'll get a dete-stamp (only date though, unfortunately).

**Comment by gsantner** [comment]
I suggest to make use of the filemanager description line format code

**Comment by smartinick** [comment]
harshad1 - Thanks for your efforts!

From my perspective there could be a setting that has 2 parts:
- checkbox: use prefix for share-into
- text: the prefix text to use, e.g. in the current version this would be "---\r\n", and it could be something similar to this pseudo-code: "---\r\n - [\format('YYYY-MM-DD hh:mm',now()] "

Off course i have no idea of the internals of markor, therefore consider this nothing more than a educated guess/wish!

Thanks!!!

**Comment by harshad1** [comment]
Note that CRLF will likely not work well anywhere in Markor. We rely on '\n' for a _lot_ of parsing code

**Comment by pudah** [comment]
> Currently the share into always prepends the shared text with a line containing "---"

In the latest version 2.7.0, this functionality seems to have been removed. Was that done on purpose?

**Comment by gsantner** [comment]
threshold is 400 characters ("long text"), for short text no separator added.

**Comment by harshad1** [comment]
The biggest challenge here is to design a good, consistent UI / behavior. I am willing to write the code if someone else develops a plan.

**Comment by gsantner** [comment]
I suggest to use code similar to file browser format setting + `replace("\\n", "\n")`. No checkbox stuff needed, for people who want to disable it, they can enter a empty string at the setting. Default value i.e. "\n----\n".
