### ISSUE TITLE
Support in-content filesearch for encrypted textfiles

### ISSUE THREAD

**Issue by opensource21** [gsantner/markor#1375]
#### General information

* **App version:** 2.7.0
* **System:** Android 10

#### Description
I wonder if it is possible that even encrypted files will be part of the search.
Are there any reason why this isn't implemented? Is the password there not accessible?

**Comment by gsantner** [comment]
decryption takes lots of performance and as you know, main part of implementation is done at file editor.

Also, if we in future support per-file encryption passwords, this gets impossible. Unless users want to type LOTS OF passwords.

**Comment by opensource21** [comment]
Well thanks AES the performance-impact of encryption doesn't seem a problem in my eyes. The question is would you accept a pull-request which adds the feature? The main part is encapsulated in a separate class, so I don't think it's a lot of work.

**Comment by opensource21** [comment]
Opened #1388 so you can see how easily this could be done.
