### ISSUE TITLE
Using GPG to encrypt file with AES256

### ISSUE THREAD

**Issue by anishmittal2020** [gsantner/markor#1377]
#### General information

* **App version:** 2.7.0
* **System:** Android 11

#### Description
Since markor can decrypt AES256 files. I can use GPG instead of the jpencconverter as the output should be compatible. 

To encrypt `a.md` to  `a.md.gpg` I do:

```bash
gpg --symmetric --cipher-algo AES256 --output "a.md.gpg" "a.md"
```
##### Compatibility with OpenPGP

Could you please tell us if markor expects files to be compatible with Openpgp? 

##### Compression Algorithm 

By default gpg uses zip for compression. And whether Markor expects the encrypted file to be uncompressed or zip or zlib compressed?

##### File naming convention

Also, what extension of encrypted file is supported my Markor? If you can tell me this then I could use same file naming convention with `gpg`. Or is it that the encrypted file should also be called as `a.md` (above example)?

#### Note

I am unsuccessful in using GPG encrypted file with Markor, if you could tell me the above I might be able to use same settings with GPG.

**Comment by gsantner** [comment]
markor does not use gpg. for more information see the discussions tab.

**Comment by anishmittal2020** [comment]
gpg is just a software. The encryption algorithm that one uses with any tool should generate the same result. Isn't it?

**Comment by gsantner** [comment]
@anishmittal2020 
Sorry confused, thought you want to do public/private key based encryption.

Still, I did not implement the encryption part, and neither I tried with OpenPGP - so you have to find it out on your own.  
Though it not looks like really a issue, so I suggest to have the questions & discussion at <https://github.com/gsantner/markor/discussions> , where already there is a similar related question.

Also renamed this "issue" to `Use OpenPGP to encrypt file with AES256 in a Markor compatible way`.

What you probably need is this information from here <https://github.com/gsantner/markor/blob/master/app/thirdparty/java/other/de/stanetz/jpencconverter/JavaPasswordbasedCryption.java>, about the used encryption & parameters:

![grafik](https://user-images.githubusercontent.com/6735650/123988213-1c838500-d9c8-11eb-905e-7c90141bfc02.png)

Please further discuss at the GitHub discussion, and @opensource21 might be able to help you there as he implemented encryption at Markor.

**Comment by gsantner** [comment]
note that there is also additional metadata stored. I suggest you to take a look at opensource21 java demo application for how to make use of it on desktop i.e.
