### ISSUE TITLE
Android 11 can't use Markor to open Markdown files in instant messaging apps

### ISSUE THREAD

**Issue by PlutoZB** [gsantner/markor#1380]
General information
App version: v2.7.0 (123)
System: Android 11
Description

Android 11 can't open Markdown-formatted documents directly from QQ using the Markor APP.

QQ, or Tencent QQ for short, is an Internet-based instant messaging software.
The problems encountered are shown in the pictures.

The Chinese translation of the picture reads, Warning! Markor does not have permission to save this file, and all changes here will be lost. Markor did not fix the problem. Please check Markor's Android permissions.

![](https://gitee.com//plutohadeszb/images4mk/raw/master/images/20210701221252.jpeg)

**Comment by ChiefMikeK** [comment]
@PlutoZB need more information! 💡
___
Please explain **In detail** what* you are trying to accomplish.  
The steps taken to get this message,  
And also make and model of cellphone ie.  
>  I'm trying to download and share a .MD file on my  Huawei  p20 EMUI-11.1.0 using Google chrome browser QQ-Web by click on the drop down menu item: share
> Then I opened Markor app and got error message

**Comment by gsantner** [comment]
Duplicate / Discussion of such things is at #1381
