### ISSUE TITLE
Option to hide header underline!

### ISSUE THREAD

**Issue by lexterror** [gsantner/markor#1384]
I tried setting the underline color to Alpha 0! I also tried "text-decoration:none" Please let me know if there is currently a way to do this!

Thank you!

**Comment by gsantner** [comment]
Have you tried adding `!important` to the css ?

**Comment by lexterror** [comment]
Yes, it does not work!

**Comment by gsantner** [comment]
`<style>h1,h2,h3,h4 { border-bottom: 0; } </style>`

**Comment by lexterror** [comment]
Thank you so much, I thought it was underline!

**Comment by gsantner** [comment]
np.

you may also use the export -> html plaintext option, where you can see the injected css (incl what markor has predefined)
