### ISSUE TITLE
Search the text of all files

### ISSUE THREAD

**Issue by nitrocode** [gsantner/markor#1387]
#### General information

* **App version:** 
* **System:** 

#### Description

I'd like to be able to search all my text files.

**Comment by gsantner** [comment]
And what is hindering you on that? Markor has search.

**Comment by nitrocode** [comment]
I can search file names but i cannot search within the files themselves. Apologies if I'm doing something wrong.

Great app by the way. Thanks for building and maintaining it. I use it daily for my notes

**Comment by gsantner** [comment]
You can search in files since 2.7.0.

**Comment by nitrocode** [comment]
Oh you're completely right. I was using an old version. Fdroid didn't update. Thank you!

**Comment by gsantner** [comment]
Thats why the description asks for version at first.
