### ISSUE TITLE
Errorneous TeX rendering where multiple `_` or `^` exist in math expressions

### ISSUE THREAD

**Issue by Gennadiyev** [gsantner/markor#1389]
## General information
* App version: 2.7.0
* Android version: 10 
* Device: HUAWEI Matepad Pro 10.8

## Description

An attempt was made to render the following formula:

```latex
$\delta ^ {(n)} (at) = \dfrac{1}{|a|} \cdot \dfrac{1}{a ^ n} \delta ^ {(n)} (t)$
```

But it shows bad results:

![Screenshot_20210711_145641.jpg](https://i.loli.net/2021/07/11/gd1MeatlQWEYDJz.jpg)

Similarly, the following equation will also fail to render properly:

```latex
$\left.\mathrm{d}x_1\right|_{x_1=a}$
```

But has a workaround by adding spaces before and after each underscore, to prevent markdown-like syntax from being rendered first.

## References

#952 and #825 are two similar issues about rendering TeX, where a suggestion is provided to use `<div>` to wrap around the markdown block. However, it is a bad practice for markdown writers to use HTML tags within their files. Meanwhile, this issue technically only exist in markor. Because markor is not the only markdown editor I'm currently using, I don't feel necessary to implement this workaround.

## Guessings

I haven't run into the codes yet, but it's quite apparent that markor is attempting to **parse what's wrapped inside the `$...$`, which corrupts the expression before it's sent to KaTeX**.

I fully understand that it may be part of KaTeX's fault, but I'm a MathJax and KaTeX user, regularly calling them in my own projects without such an error.

> I'm not native to English, please forgive for ambiguity.

**Comment by Gennadiyev** [comment]
Quick note: #1393 will also be resolved if KaTeX does not parse beforehands.

**Comment by gsantner** [comment]
feel free to improve math support at Markor, and/or Flexmark (Markors markdown parser/converter).

Markor is not a Markdown parser/converter.

**Comment by PyTran** [comment]
$w^{12}$ is very big $w=0$ is nothing

$w^{12}$ is very big $w^0=0$ is nothing

These is also a related problem when there are two superscripts in the same paragraph. In the above the top line renders correctly but the second line does not.

**Comment by fgtham** [comment]
The easiest way would be to just disable the flexmark Superscript extension:

https://github.com/gsantner/markor/blob/79317e33503a02662ffd7e467a77c343247544e8/app/src/main/java/net/gsantner/markor/format/markdown/MarkdownTextConverter.java#L111

After commenting this line, all the examples given so far rendered correctly.

Unfortunately, this would reopen #1268.
