### ISSUE TITLE
Version controlling of Notebook using Git

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#139]
#### General information

* **App version:** v0.2.3
* **System:** v7.0.1

#### Description
It would be great if it would be possible to version control the Markor Notebook folder. For this Git would be a good idea. For the library - maybe take a look at JGit (Gradle: `org.eclipse.jgit:org.eclipse.jgit`), <https://www.eclipse.org/jgit/documentation/>.

 Note that this issue is not fully described, there are many things left open for discussion, e.g. how to deal with merge conflicts. Don't be afraid to ask or bring up your ideas on this.

* Step 1
  * Get a working solution to trigger a manual clone/push/pull via an toolbar option. Public repositories are enough, try it hardcoded for now
  * Just add all files (and new/deleted files), respect gitignore (should work out of the box with library) and commit push
* Step 2
  * Add options to setting to configure Git
  * Username/Password, http Protocol (url)
  * Manual sync using setted setings
* Step 3
  * Auto-Sync - e.g. at startup? time-based? maybe commit when leaving file, push  when wifi?
  * Dealing with merge conflicts? - maybe comparision, do you want to keep this or this?
* Step 4
  * Support for SSH protocol
  * Settings option for location SSH key
  * Settings option for SSH key passphrase

-----

Some references and hints for this issue, e.g. apps using git too:
* <https://github.com/zeapo/Android-Password-Store> - <https://github.com/zeapo/Android-Password-Store/tree/master/app/src/main/java/com/zeapo/pwdstore/git>
* <https://github.com/LonamiWebs/Stringlate>

**Comment by gsantner** [comment]
Closing this as Markor's target is to stay lightweight - and let do the syncing magic by apps that are made for it.

**Comment by slayer** [comment]
Git support will be super cool feature

**Comment by gsantner** [comment]
Probably agit companion is what you look for.

Agit Agit (Software-Quelltext lesen) - https://f-droid.org/packages/com.madgag.agit
