### ISSUE TITLE
Start on bottom doesn't work for QuickNote

### ISSUE THREAD

**Issue by Kamul-PL** [gsantner/markor#1390]
## General information
* App version: 2.7.0 (123)
* Android version: 11 (LineageOS)
* Device: POCO F1

### Description
I've got checked *Start on bottom* option in *Settings/Edit mode*, but *QuickNote* file is opened on the top all the time (however it seems these option works OK for other files). I know that with some older versions the behavior was like expected. Unfortunately I can't remember which version was the last.

**Comment by gsantner** [comment]
Start on bottom is generally always active on the startpage, that setting is ignored for these tabs.

otherwise, #1379

**Comment by Kamul-PL** [comment]
> Start on bottom is generally always active on the startpage, that setting is ignored for these tabs.

Wait, if I understood it correctly, QuicNote should always start at __bottom__ of file. But it doesn't - in my case it starts at __top__. Which is quite annoying, especially for QuickNote, because it is intended for making notes as quick, as possible. But scrolling to the bottom of quite big (in my case) file is a contradiction of this idea.

**Comment by gsantner** [comment]
> Wait, if I understood it correctly, QuicNote should always start at bottom of file.

Correct and for this therr id 1379.

**Comment by Kamul-PL** [comment]
Sorry, does it mean #1379 should also solve problem with QuickNote not going to the bottom?

**Comment by gsantner** [comment]
correct

**Comment by Kamul-PL** [comment]
Thanks!
