### ISSUE TITLE
Markor crashes when pref_key__is_editor_statusbar_hidden pref is checked

### ISSUE THREAD

**Issue by milouse** [gsantner/markor#14]
## General information

* **Device:** Fairphone 2
* **Android Version:** Fairphone Open 17.09.3 (Android 6.0.1)
* **App version:** v0.1.2

## Steps to reproduce

1. Open Markor and go to preferences
2. Check the preference box, which correspond to the `pref_key__is_editor_statusbar_hidden` ([line 85 of preference file](https://github.com/gsantner/markor/blob/master/app/src/main/res/xml/preferences.xml#L85))
3. Go back on any folder
4. Try to open one of your existing markdown file

## Expected result

I have no idea

## What do you see instead?

Markor crashes and I'm redirected to the phone desktop. Unchecking the pref box allow me to open the file again.

**Comment by dimqua** [comment]
I have exactly the same problem on CM13.

**Comment by sjmduncan** [comment]
[AndroidBug5497Workaround](https://github.com/sjmduncan/markor/blob/a34ea873d7981e3f5b0ef513ebfd20957ccebfa4/app/src/main/java/net/gsantner/markor/activity/NoteActivity.java#L76) is what's breaking this for me.

**Comment by gsantner** [comment]
I am on it. Being pushed soon. The problem is that the fullscreen-android-fix must be applied setContentView.
