### ISSUE TITLE
Allow setting of base path(s) for Markdown path parsing [FEATURE]

### ISSUE THREAD

**Issue by Blackhawke** [gsantner/markor#1406]
While Markor correctly parses path names in the file manager according to EXT4 rules, it doesn't excape them in markdown URL links. So an internal pathname like ``foo+bar`` will be correctly opened by Markor's file manager, but the markdown link ``[foop](foo+bar/foop.md)`` not only won't work, Markor creates an empty folder named ``foo bar``, then ends up opening a blank file in the editor (since the existing file, ``foop.md`` doesn't exist in ``foo bar``).

The problem is, if ``foo+bar`` is deep in the file path, say ``/storage/emulated/0/git/foo%2Bbar/21/sep/28/foop.md``, then work arounds like ``../../foop.md`` don't work. The path name ends up having to be explicit. Which means, unless you're very fortunate and the folder depth is exactly the same on all computers, the path name is going to be invalid on those other file systems (like the desktop/laptop).

So, either Markor needs to properly excape valid EXT4 path names into valid URL path names, or we need a way to set an explicit root path name for the URL paths. If the latter, then in the file headers would be best, perhaps using YAML, like some other markdown editors.

**Comment by gsantner** [comment]
Markor is not a Markdown parser, so you ask more on the wrong place. Markor uses a Markdown parser but not implements one of it own. And what you wrote about, is about Markdown parsing.
