### ISSUE TITLE
Button to delete every formatting, Button to copy and paste formatting

### ISSUE THREAD

**Issue by RAPXT** [gsantner/markor#1409]
## General information
* App version: 2.7.0
* Android version: 7.1.2
* Device: LG V500
* I understand that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

### Description
In everyday usage i miss two buttons:

1. A button to delete every formatting of text and reset it to a "text only" state, meaning deleting bold, serif, underlined and other formats.

2. A button to copy and paste the formatting from one section of text to other sections, like in word or libre office.

Sidenote: Iˋve seen you have a little FAQ for makor. But what i miss there, is a description of what all the icons in the editor actually do. For someone who is used to it, it doesn´t matter very much, but for a newbie it propably takes more time to get used to it than there are willing to spend or there are already overwhelmed at first sight. I think a "more complete" user manual could definitly help (or tooltips in the app).

**Comment by harshad1** [comment]
As formatting is a part of the text itself, I do not think it will be possible to implement a format copy paste. I do not think I have ever seen any markup editor offer this.

You can achieve (2) by going into view mode and selecting all -> copy

I agree with you about the FAQ / documentation. I and others have been adding functionality for our own needs, but haven't taken the time to document them. @gsantner has done his best to keep everything as obvious and user friendly as possible, but it's hard when all of us as working on Markor in our free time as a side project

**Comment by gsantner** [comment]
Closing.

> I agree with you about the FAQ / documentation. I and others have been adding functionality for our own needs, but haven't taken the time to document them. gsantner has done his best to keep everything as obvious and user friendly as possible, but it's hard when all of us as working on Markor in our free time as a side project

Thanks for saying, it's quite how it is 😄 .

If `<somebody>` wants to add things to the FAQ/doc, just send me the markdown content for it. The blog & faq content is written in markdown as well.
