### ISSUE TITLE
Every time I open a file, a blank of the same name is put in folder documents/documents. (No data loss) 

### ISSUE THREAD

**Issue by NomadicVoxel** [gsantner/markor#1410]
## General information
* App version: v2.8.0 (124)
* Android version: 11
* Device: Moto G Stylus
* Other notes: Save location is /storage/(external_SD)/documents
* I understand that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

### Description
When the glitch occurs for the first time, the folder "/storage/(external_SD)/documents/documents" is created. 
For every file I open, a blank one with the same name is created in this folder. 
This recurses; if I open /documents/documents/QuickNote.md, then /documents/documents/documents/QuickNote.md is created.
 
No clue if there's something I did that started this issue. I've been messing around with settings and can't find anything that prevents it.

**Comment by gsantner** [comment]
#603 probably

**Comment by NomadicVoxel** [comment]
Dang, been stuck on this bug for a while huh. Guess I should just move my stuff to internal then

**Comment by NomadicVoxel** [comment]
Thanks for pointing me the right way

**Comment by gsantner** [comment]
I made some improvements for SD-Card support recently. Please see <https://github.com/gsantner/markor/issues/603>.
