### ISSUE TITLE
Markdown Preview issue

### ISSUE THREAD

**Issue by Animyos** [gsantner/markor#1411]
I have some issues with the Markdown Preview in Markor. The video should explain everything:

[https://youtu.be/TFvY27-ZXqI](https://youtu.be/TFvY27-ZXqI)

Kind regards
Animyos Fox

P.S.: Sorry, my smartphone is in German language, hope you recognize the elements of your app!

**Comment by Animyos** [comment]
I've tested a bit, and as it turns out, the preview mode cannot show the Markdown formatting if you use html titles like `<h1>` in your text right before your formatting.  HTML paragraphs however don't create this issue.

To solve this, just use the Markdown titles  `#` `##` etc.

**Comment by gsantner** [comment]
Copy paste from email answer

```
Der Markdown parser und Inhaltsverzeichnis Generator scannt ausschließlich Markdown Überschriften, HTML wird nicht überprüft für das Inhaltsverzeichnis.
```
