### ISSUE TITLE
Feature request: make "Sort by" as a per-directory setting

### ISSUE THREAD

**Issue by ema-pe** [gsantner/markor#1412]
Hi, I've been using Markor since 2018 and I find a bit frustrating that there is only one sorting option for all folders. I have some folders that I want to sort by name, and others by name but in reverse. Currently (Markor v.2.8.0) I need to change the sort manually each time. It would be great if the sorting option is saved as per-directory setting.

I know Java, but I don't use it in the latest years and I've never use it on Android projects. But if this feature is simple to implement, I can try to do.

**Comment by harshad1** [comment]
I can see the utility in this. However, I think that it can get confusing fast. There should be a good way to reset all folders to the default.

**Comment by gsantner** [comment]
One thing where I see the point to behave differently especially: At recent and popular files (so most recent file is top i.e.). But thats not calculacted from file metadata.

**Comment by ema-pe** [comment]
Hi, I think this feature can be implemented like Amaze File Manager did. There is a menu option where the user can select the sort type (name, last modified, size...), if ascending or descending and can check a checkbox to set the sort only for the current folder. See the attached screenshot.

![sort-amaze-file-manager](https://user-images.githubusercontent.com/21246809/130357715-a3a71fa9-1d71-48ad-848a-38c50bef765f.jpg)

**Comment by gsantner** [comment]
not really in our case. our sort options dont are in a own configurable dialog, but more limited menuitems.

lots of hacky code for not much benefits.

**Comment by gsantner** [comment]
Closing as won't fix. Want to keep filemanger sort buttons & options as general global options.
