### ISSUE TITLE
Todo.txt should support preserving priority on completion (via pri:A)

### ISSUE THREAD

**Issue by harshad1** [gsantner/markor#1413]
Currently, when a todo item is completed, the priority is discarded. Instead it should be preserved as a `pri:` tag. The priority should be restored if the todo is uncompleted.

[See todo.txt readme](https://github.com/todotxt/todo.txt)

**Comment by gsantner** [comment]
it also says `Many Todo.txt clients discard priority on task completion.`, which is perfectly fine. I've used quite some todo.txt software and I did not use a single one which would have added such a tag

**Comment by harshad1** [comment]
Several of the todo.txt managers I use seem to support it.

IMO having it enabled by default (i.e. not optional) it won't disrupt the workflow for anyone who doesn't need it.

**Comment by gsantner** [comment]
how does it behave when un-checking? remove pri:?

**Comment by harshad1** [comment]
Remove pri:X and use that value as the priority.

Aug. 15, 2021 05:38:44 Gregor Santner ***@***.***>:

**Comment by gsantner** [comment]
yeah makes sense

**Comment by Hyperlynx2** [comment]
Today I learned!

In my manual, non-phone todo.txt I had just been adding an x to the start of the line and then the date, keeping the priority as is. I was _just_ about to open an issue complaining that this "pri:" business is nonstandard and could I please have it the other way, when I found this ticket and the corresponding link to the spec. I've been doing it wrong!

Nice work @gsantner and @harshad1!
