### ISSUE TITLE
Auto-Save and Auto-Load/Refresh

### ISSUE THREAD

**Issue by dnngll** [gsantner/markor#1419]
## Thank you..
.. so much for a great app! I think have a suggestion that would be a huge improvement for it. I found https://github.com/gsantner/markor/issues/587 ,  but it's not quite what I'm suggesting.

## General information
* App version: 2.8.0 (124)
* Android version: 11
* Device: Pixel 5
* I understand that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

### Description
My quicknote.md is synced between several devices using Syncthing. I usually have the quicknote.md open on a notebook (VS Code) and on a phone (Markor). The app is always running on the phone.

#### 1: Auto-Saving the file:
- Behavior: If I change the content of quicknote.md **USING MARKOR** it is not being saved until I press save or until I exit the app
- Improvement: Have a setting where an save-interval can be set, e.g.: [on close | directly after typing | 1s | 5s | 1m | 5m | custom time]
- Seen where: I tried several Android-apps, one of them had exactly that setting. One could even specify the milliseconds after the last keystroke. If it is crucial to the solution please let me know, I will look for the app again and post the name

#### 2: Auto-Loading (refreshing) the file:
- Behavior: If I change the content of quicknote.md **NOT USING MARKOR** and it is being synced while Markor is open, the changes are not loaded until I press "Reload"
- Improvement: Have a setting where a loading-interval can be set, e.g.: [automatically on file change | 1s | 5s | 1m | 5m | custom time]
- Seen where: Not seen on Android yet. On a PC though, VS Code checks that box

I am curious about your feedback!

Kind regards!

**Comment by harshad1** [comment]
What about when there is a conflict?

i.e. Changes made in quicknote (for example) and not yet saved, and then changes synced over by syncthing.

**Comment by dnngll** [comment]
Basically that's the situation we're in right now:

## Starting on Notebook
- Changing the file on my notebook doesn't show up on Markor automatically
- Now adding something on Markor and saving overwrites the previous changes made on the notebook

## Starting on Phone
- Changing the file on Markor doesn't save automatically, thus doesn't show up on the notebook
- Now adding something on the notebook and saving overwrites the previous changes made on Markor

## Solution
By setting the reload-time and the save-time to "instant", one would have to write almost simultaneously to mess things up. Unlikely for a single user. And even if: Syncthing will complain about it and not overwrite anything.

**Comment by harshad1** [comment]
I feel this has come up before and there was a good reason auto save wasn't added. @gsantner?

**Comment by dnngll** [comment]
Opposite is the case. Autosave wasn't removed:

@gsantner wrote in https://github.com/gsantner/markor/issues/1303#issuecomment-812820225 : "too many tears because people kill the app and forget to save".

Above suggestion would make it even more safe, and create even less tears : )

**Comment by dnngll** [comment]
Above feature, combined with suggested "File modified indicator" (https://github.com/gsantner/markor/issues/1311), would really make things beautiful.

I imagine an icon that
- changes to (e.g.) red while you're typing.
- When you're done, and after the set milliseconds after the last keystroke, it turned yellow while saving.
- While idling it would be green.
- And when content is added via Syncthing, or any other way outside Markor, it would turn blue while loading/refreshing.

Lovely!

**Comment by gsantner** [comment]
hello, there is already #1303 about this topic. Please have this discussion there.

And let's see what future brings.

**Comment by dnngll** [comment]
> hello, there is already #1303 about this topic. Please have this discussion there.
> 
> And let's see what future brings.

Hello @gsantner,

I'm so confused... 😵

First you closed #1303 and asked to have the discussion in #1419.
One minute later you reopened #1303, closed #1419 and asked to have the discussion in #1303

However, #1303 and #1419 are 2 completely opposite things (#1303: disable autosave ***vs*** #1419: set autosave frequency higher). 

Also #1303 was already dismissed by you. Following that logic, shouldn't #1303 be closed, and the discussion going on in #1419 (like you initially did)? Or am I totally confusing things here?

**Comment by gsantner** [comment]
whatever number the issue/discussion is, please don't spread across like 5 issues.

**Comment by gsantner** [comment]
whatever number the issue/discussion is, please don't spread across like 5 issues.

Save time = Close time, no timer. When you change text, decide shortly after to undo and have original text, you have multiple file writes and a different file modification date. This is what I don't want to happen.
Also: This is what users have been reporting as bugs in the past, that file is written, but it was not changed. So doing what you suggest as enhancement, reopens another bug.

**Comment by dnngll** [comment]
> whatever number the issue/discussion is, please don't spread across like 5 issues.

I don't quite understand what you mean. Are you referring to me replying to https://github.com/gsantner/markor/issues/1419#issuecomment-904013447 in https://github.com/gsantner/markor/issues/1419#issuecomment-904016195 referring to https://github.com/gsantner/markor/issues/1303#issuecomment-812820225?

> Save time = Close time, no timer. When you change text, decide shortly after to undo and have original text, you have multiple file writes and a different file modification date. This is what I don't want to happen.

I don't understand, and I disagree. When I change text, it should be saved. When I undo it, it should be saved again. This will of course result in multiple file writes and multiple modification dates. I don't see why you don't want this to happen, since you specifically state "too many tears because people kill the app and forget to save" (https://github.com/gsantner/markor/issues/1303#issuecomment-812820225).

> Also: This is what users have been reporting as bugs in the past, that file is written, but it was not changed. So doing what you suggest as enhancement, reopens another bug.

This is not what I am suggesting, please see above: "One could even specify the milliseconds after the last keystroke". If I left the app open for an hour without doing anything, of course nothing should be saved.

### On another note:
For anyone interested in what I was suggesting, as it seems clear that it will not be implemented in Markor: I switched to https://obsidian.md, which behaves exactly the way I was trying to suggest above. The file is not altered if you don't do anything. But if you type or delete, it is saved about a second or 2 after your last keystroke. It's brilliant if working on several devices, because your file is always up to date.

**Comment by dnngll** [comment]
> whatever number the issue/discussion is, please don't spread across like 5 issues.

I don't quite understand what you mean. Are you referring to me replying to https://github.com/gsantner/markor/issues/1419#issuecomment-904013447 in https://github.com/gsantner/markor/issues/1419#issuecomment-904016195 referring to https://github.com/gsantner/markor/issues/1303#issuecomment-812820225?

> Save time = Close time, no timer. When you change text, decide shortly after to undo and have original text, you have multiple file writes and a different file modification date. This is what I don't want to happen.

I don't understand, and I disagree. When I change text, it should be saved. When I undo it, it should be saved again. This will of course result in multiple file writes and multiple modification dates. I don't see why you don't want this to happen, since you specifically state "too many tears because people kill the app and forget to save" (https://github.com/gsantner/markor/issues/1303#issuecomment-812820225).

> Also: This is what users have been reporting as bugs in the past, that file is written, but it was not changed. So doing what you suggest as enhancement, reopens another bug.

This is not what I am suggesting, please see above: "One could even specify the milliseconds after the last keystroke". If I left the app open for an hour without doing anything, of course nothing should be saved.

### On another note:
For anyone interested in what I was suggesting, as it seems clear that it will not be implemented in Markor: I switched to https://obsidian.md, which behaves exactly the way I was trying to suggest above. The file is not altered if you don't do anything. But if you type or delete, it is saved about a second or 2 after your last keystroke. It's brilliant if working on several devices, because your file is always up to date. Also, my second point from https://github.com/gsantner/markor/issues/1419#issue-977236972 is covered as well. Brilliant!
