### ISSUE TITLE
improve/change app/project icon

### ISSUE THREAD

**Issue by lokesh-krishna** [gsantner/markor#142]
Would be amazing if we could get a new icon that had a more Material Design look.

**Comment by gsantner** [comment]
I am retitling this to "improve/change app/project icon". I am not making it fixed ahead whether the new one should/will be material or not.

**Comment by dugite-code** [comment]
2 Quick ideas

![two](https://user-images.githubusercontent.com/12742064/33307195-a022efb2-d450-11e7-8103-7cc356c49554.png)
![one](https://user-images.githubusercontent.com/12742064/33307208-aa20982a-d450-11e7-8335-3ef04c39efee.png)

**Comment by gsantner** [comment]
thanks for suggestions!

but Have to admit that I dont like them too much. Also, markor isnt just a Markdown editor anymore, it got/gets a general texteditor with markup (including markdown as main feature) support

**Comment by dugite-code** [comment]
Good point, I'll have another crack at it later

**Comment by gsantner** [comment]
Nice, thanks! open for discussion

**Comment by dugite-code** [comment]
These are all a bit rough still and will need further work but it might help for the direction.

| Icon  | Description |
| ------------- | ------------- |
| ![seven](https://user-images.githubusercontent.com/12742064/33352301-2bcaeb9a-d4e3-11e7-8dd4-16e250ff66d0.png)  | Screen Icon - Aiming to be close to a screenshot Icon  |
| ![eight](https://user-images.githubusercontent.com/12742064/33352926-2d54fa20-d4e6-11e7-9f46-8133608feedb.png)  | Notepad Icon - Loosely Based off the original Markor icon  |
| ![fourtc](https://user-images.githubusercontent.com/12742064/33352325-4fd33dbc-d4e3-11e7-8e06-81cce38e6423.png) ![fourrt](https://user-images.githubusercontent.com/12742064/33352336-5d020978-d4e3-11e7-83f5-9966b99c30bb.png) | Notepaper Icon - For a more work aimed feel  |
| ![five](https://user-images.githubusercontent.com/12742064/33352361-72aa2d32-d4e3-11e7-92c3-b8d6745577f9.png) ![five2](https://user-images.githubusercontent.com/12742064/33352365-774d1ef8-d4e3-11e7-88e5-17320865e63c.png)  | This was a quick experiment with going outside the circle. I'm not a fan of how it turned out but here it is for ideas |
| ![six](https://user-images.githubusercontent.com/12742064/33352384-9107e472-d4e3-11e7-8315-457f6a240f31.png)  | Sticky Note - Rounded square background. I based it off of the Google keep Icon  |

**Comment by gsantner** [comment]
Thanks for hard work!

It is already sorted in the way of my personal liking :D. btw, if you need colors of markor, here they are:: <https://github.com/gsantner/markor/blob/master/app/src/main/res/values/colors.xml#L7>.

I have to admit, that I would go for both normal and rounded icons (/= adaptive), while I would prefer to go the non-rounded way as default project icon (which can to be decided different).

Could you maybe try to use accent-color for pencil in the leading icons? I think maybe second icon could be a way tog go, both for users, and my expectations. Default icon without round and ring (just notepad), and in rounded case something like yours.

Outside-of-circle: don't like them quite, it can go normal and/or circle rounded, but not circled with something coming out of it.

For idea 3, I think pencil inside paper works better

Summed up, I would go to next step with icon/idea 1,2 and 3.2.

**Comment by gsantner** [comment]
Looked again at it, I quite like maybe second's notepad as project icon (without rotation, and just the notepad+pencil), and the rounded one for the round counterpart. Just an idea.

**Comment by gsantner** [comment]
@dugite-code Wanna have a chat? Should be easier than posting multiple drafts here. But still feel free to do so :) 👍 . <http://gsantner.net/#contact>

**Comment by rancidfrog** [comment]
I have a couple ideas to work with for the M part, as the ring-notepad is a good base:
Continuing from the original pencil logo
![](https://i.imgur.com/Ykt1J22.png)
![](https://i.imgur.com/rrwzriz.png)
Separated pencil,
![](https://i.imgur.com/unbTA97.png)
![](https://i.imgur.com/eoNzt3s.png)
![](https://i.imgur.com/Yq0qdiV.png)

**Comment by gsantner** [comment]
I have to admit, that I prefer text/chars not too prominent in the new icon, at least not as the main target. I want the icon to show what the app does, not how it is named :)

**Comment by rancidfrog** [comment]
Understand.
My idea was just to have the M and pencil somewhat combined, but still keeping the notepad, I.e.
![](https://i.imgur.com/tsKQ5bV.png)

**Comment by gsantner** [comment]
heres what was used as base, if you something to experiment with: https://openclipart.org/detail/35197/tango-accesories-text-editor

**Comment by gsantner** [comment]
I pushed a new commit with an updated icon, if somebody can build from git and want to give some feedback, feel free to do so :)

Thanks to dugite

**Comment by gsantner** [comment]
@rancidfrog Sorry, I do unterstand better now. Yep maybe your suggested Pencil-M looks better than aside-pencil. I have to try it out

**Comment by dugite-code** [comment]
BTW I've dumped my Icon work [here](https://github.com/dugite-code/Icons/tree/master/Markor) should anyone have sugestions in relation to my work. @rancidfrog I used your sketch for [this icon](https://github.com/dugite-code/Icons/blob/master/Markor/Notepad-1.5.svg)

**Comment by rancidfrog** [comment]
Will take a look at your icons, as for quick grouped SVG: https://github.com/rancidfrog/project-info/blob/master/mMmm.svg

More to give you ideas and see what creative concepts you can come up with.

**Comment by gsantner** [comment]
Thats the current idea/state:
![dasd](https://user-images.githubusercontent.com/6735650/33829550-11f0f560-de71-11e7-8662-3e23cf4f910d.png)

comparision:

![screenshot_2017-12-11__12-41_1](https://user-images.githubusercontent.com/6735650/33829527-f10d45e2-de70-11e7-92c8-6f8e5a446bb7.png)

**Comment by gsantner** [comment]
I tried many things, color variation, placements, and this is what I found working best. I too have it on newicon branch checked in if you want to try it out. What seems to be not really working is the yellow-on-gray thing, in any combination it has bad recognizability and readibility. I tried it then with markor-darkblue which works very good :). See below, happy about feedback.

![screenshot-2017-12-14__15-12-56](https://user-images.githubusercontent.com/6735650/33996384-570c3ee4-e0e1-11e7-9bac-bbf7ba214b6d.png)


![screenshot_2017-12-14__15-08_1](https://user-images.githubusercontent.com/6735650/33996296-159fef00-e0e1-11e7-9b48-792251f9305a.png)
![screenshot_2017-12-14__15-08_2](https://user-images.githubusercontent.com/6735650/33996305-1924d83e-e0e1-11e7-9800-e98c79d4b033.png)
![screenshot_2017-12-14__15-09_1](https://user-images.githubusercontent.com/6735650/33996306-1b1d0c06-e0e1-11e7-842e-8702ecbed83c.png)

**Comment by milouse** [comment]
Sorry for the late posting.

I must admit I like the following icon:

![](https://user-images.githubusercontent.com/12742064/33352325-4fd33dbc-d4e3-11e7-8e06-81cce38e6423.png)

What I like about is that it's clear looking at it that we speak about an editor. Its colors are maybe a bit to light. The second one on that list with the blue border color was better on this point. That's what I appreciate too on [that one](https://user-images.githubusercontent.com/6735650/33829550-11f0f560-de71-11e7-8662-3e23cf4f910d.png).

On the contrary I dislike a lot the last proposal: without context or knowing the app, you can easily mistake it for an email application.

![markor](https://user-images.githubusercontent.com/349239/34000379-6603ad54-e0ed-11e7-9309-ba8c36b88194.png) | ![gmail-email-mail-logo-circle-material](https://user-images.githubusercontent.com/349239/34000538-df9bf1bc-e0ed-11e7-82a8-a1c539860f5b.png)

**Comment by gsantner** [comment]
I too tried your suggested icon, but at small scale it does very bad. Everything that has textlines may look very good at the size above, but very bad on smaller scale, and as app/launcher icon, and this is where it the most important thing to look good and to be recognizeable. Just take a look at the 3 way comparision. There is absolute no way multi-textlines will get into icon, sorry.

**Comment by gsantner** [comment]
@milouse Currently working a litle on the editing emphasis. What on keeping the pencil the traditional way? (Note, the color lines too, what colors do you think would fit? More than 4 lines will not be placeable. Not final, just for trying them)

![screenshot_2017-12-14__21-19_1](https://user-images.githubusercontent.com/6735650/34012581-a31941fa-e114-11e7-9be6-29f50c349099.png)

**Comment by gsantner** [comment]
@ everybody : this is the current proposed icon for markor:

![ic_launcher-web](https://user-images.githubusercontent.com/6735650/34014966-46d53b84-e11d-11e7-88c5-ca8718f107d5.png)


![screenshot_20171214-222123](https://user-images.githubusercontent.com/6735650/34014946-367d4326-e11d-11e7-98ce-8b40253d927b.png)

**Comment by Lonami** [comment]
It looks pretty cool! I personally would try out with less colours, but I like how it looks.

**Comment by gsantner** [comment]
So, I spent a lot of time on this now, and here is the new (final) icon of Markor. Thanks for feedback and work everybody!

![app_icon_512 png](https://user-images.githubusercontent.com/6735650/34018311-96b4ed28-e129-11e7-8b42-b99f589a24f8.png)

![screenshot_20171214-235133](https://user-images.githubusercontent.com/6735650/34018350-c0b91680-e129-11e7-90c0-1d9e69f15eab.png)


![screenshot_2017-12-14__23-38_1](https://user-images.githubusercontent.com/6735650/34018338-ae359fd8-e129-11e7-9f13-2ad0b95af2a0.png)

**Comment by Lonami** [comment]
Awesome, good job all and for the ideas :)

**Comment by milouse** [comment]
Sorry for not responding sooner. But you've done a great job. I love the last icon :) Bravo!

**Comment by lokesh-krishna** [comment]
@gsantner, really like the new icon but wanted to discuss the circular icon with you. The way it is presently, it looks like the icon got cut off and not very polished. This is because of the two vertical bars on the top bar of the icon actually being cut off.

Do you think there is someway to improve that? Maybe drop the two bars at the extremes or maybe more drastically, drop the top bar altogether?
