### ISSUE TITLE
Empty display preview for some syntax highlighting markdown text in code block

### ISSUE THREAD

**Issue by efr2et** [gsantner/markor#1421]
## General information
* App version: 2.8.0
* Android version: 8.1

For this markdown text don't display preview

```
```markdown
# H1
## H2
### H3
#### H4
##### H5
###### H6

Alternatively, for H1 and H2 an underline-ish style:

Alt-H1
======

Alt-H2
------```
```

![Screenshot_20210824-232932](https://user-images.githubusercontent.com/3049884/130686157-e83556ba-d2cb-49d2-b457-b9f0d349e384.png)

But if you replace 'H1 and H2' with 'H1 H2', preview work.

**Comment by gsantner** [comment]
you talk about syntax highlighting of markdown text in viewed content right?

I don't think we have added the plugin for that. Check <prismjs.com>

**Comment by efr2et** [comment]
If a combination of 'H1 and H2' is used in the text, the preview does not work
![Screenshot_20210824-232932](https://user-images.githubusercontent.com/3049884/130776968-4aa5ffc9-530f-4ce4-84b6-c1a8f0aee21b.png)
![Screenshot_20210825-133420](https://user-images.githubusercontent.com/3049884/130777032-e16e1bab-e434-4886-93e7-b93d68abda4f.png)

But if you remove the 'and' ->  'H1 H2', then it is displayed normally. Looks like bug.
![Screenshot_20210825-133634](https://user-images.githubusercontent.com/3049884/130777252-dcd1ffd4-eb70-4b15-874f-65b821397da4.png)
![Screenshot_20210825-133638](https://user-images.githubusercontent.com/3049884/130777282-2a02f2b4-df17-4182-97c7-f3e20e235198.png)

**Comment by gsantner** [comment]
cannot reproduce 2.9.0
