### ISSUE TITLE
Feature Request: Add option to display first-level heading as title

### ISSUE THREAD

**Issue by kb173** [gsantner/markor#1426]
I use Zettlr on the PC for writing Markdown notes. That program has an option for displaying the first-level heading (`# Heading`) as the title in the file list, rather than the true title of the file. This is practical because it allows file names to be a generic ID that can be linked without worrying about future title changes.

In Markor, however, all I see are the nondescript file IDs that are used as file names. It would be great if there was an option to display the first heading within the file as the title instead.

Example: file name is `20210905123456.md`, that file begins with `# Today's File`, I would like to be able to see `Today's File` in the files list rather than the actual file name.

Thanks for the great app!

**Comment by gsantner** [comment]
Hello, we already had this in the past.  

* Usually it was problematic ??what is a better title, the filename or the first line of text??.
* It has shown that mostly filename is the better, less hacky way, and that it's more performant.
* When there is a wiki filelist of 250 documents, we would need to open & read ALL of them (or at least a bigger portion) of it in parallel. The user awaits names to be displayed instantly, and thats tricky in this case.
* Often files not start with some title, but i.e. `---` frontmatter. Then again user would await to find & parse the `title: ` field.
* ...lots of possibilities.

Just some reasons - why there is filename used. And I don't have in mind of changing that.
