### ISSUE TITLE
Hex color for basic theme instead of color wheel

### ISSUE THREAD

**Issue by lamyergeier** [gsantner/markor#1428]
## General information
* App version: 2.8.0
* Android version:  11
* Device: Samsung A70
* I understand that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

### Description

In the following I would like to change **BG Light** to `#fdf6e3`, how can I type it instead of choosing it from the colour wheel. May be you could provide an option to type it under the colour wheel.

![Screenshot_20210906-173427_Markor](https://user-images.githubusercontent.com/42092626/132239892-09bba289-ccef-43a6-ab63-9943b711b6c9.jpg)

**Comment by gsantner** [comment]
#1136 .

**Comment by jayunx** [comment]
Dear Developer, I wanna help fix this issue, but I have not found the place to fix. I wanna know which files I can read now, plz.

**Comment by gsantner** [comment]
In `main/java/net/gsantner/markor/ui/hleditor/TextActions.java` is a action to show a color dialog. We want to use something else there to input #hex color and visualize the input color there instead [..the color wheel isn't optimal for the use].

**Comment by jayunx** [comment]
> In `main/java/net/gsantner/markor/ui/hleditor/TextActions.java` is a action to show a color dialog. We want to use something else there to input #hex color and visualize the input color there instead [..the color wheel isn't optimal for the use].

Thank you. I got your meaning.
