### ISSUE TITLE
Allow to see and search first header instead of file names 

### ISSUE THREAD

**Issue by schlichtanders** [gsantner/markor#1430]
## General information
* App version: Version v2.8.0 (124)
* Android version: 10
* Device: Shiftphone 6mq
* I understand that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

### Description
I am using Markdown as part of a zettelkasten with Zettlr. My workflow uses (random) timestamps as the filenames, which are just used for stable referencing between the files.
When looking at files are searching for a file, this timestamp id however is not of interest at all, but rather the first header.

Hence it would be really helpful if markor could add a config option to see and search the first header instead of the filenames in the `files` tab.

### partial workaround right now

I am using searching including content and this way find my notes. For the tree-view part I haven't found a workaround.

**Comment by gsantner** [comment]
Looks like a usecase pretty specific for you only. Markor already has in-content-search which you can use to search contents of files. If your files have something like `title: '` at heading, you could input that at the search dialog, and then you will get a list with found files and the contained title.
