### ISSUE TITLE
UI Suggestion: A button to edit or view file in file manager

### ISSUE THREAD

**Issue by anishmittal2020** [gsantner/markor#1438]
## General information
* App version: v2.8.0
* Android version: 11
* Device: Samsung A70
* I understand that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

### Description

Proposed UI:

![image](https://user-images.githubusercontent.com/42092626/133879109-300630c4-9b02-4d4a-bd2e-b2101512d429.png)

May be in the above when we click FitnessRegine.md it open in edit mode, and when we click the View button (the eye on the right), it opens it in the view mode.

Proposal: Add the eye on the right of files in file manager.

**Comment by gsantner** [comment]
horizontal space is very very limited. If you have a little longer filename most of it doesnt show up. Especially on small devices 2 icons and maybe 5 chars + extensions can fit then.

Hence no, no additional buttons are about to be added to each listitem.

**Comment by anishmittal2020** [comment]
How about if we could use gestures? Either

- Swipe left or right to edit it view file.
- Or, click with 2 fingers to view abd one finger to edit

18 Sep 2021 09:14:00 Gregor Santner ***@***.***>:

**Comment by gsantner** [comment]
when you long click a file additional buttons show up. I dont see the need for adding another way of interaction.

**Comment by anishmittal2020** [comment]
Can we view from those buttons, when we Long click?

18 Sep 2021 11:00:24 Gregor Santner ***@***.***>:

**Comment by harshad1** [comment]
> Can we view from those buttons, when we Long click?

This would be harder than just click to open file -> click to view (i.e. 2 short clicks vs long click + short click)

Note that files remember the view state. So if you left a file in view it'll open in view again.

**Comment by gsantner** [comment]
I agree with @harshad1, if you do a additional click at filemanager, or editor isn't that much of a difference. Even more you might get directly to view mode anyway, depending on your last use.

Closed as wont fix
