### ISSUE TITLE
Colored underline for hex colors

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#144]
#### General information

* **App version:** v0.2.3
* **System:** 

#### Description
Option for colored hex color (`#52ef23`) underline in the according color.   
Will be something like `(#[A-Fa-f0-9]{6-8})` for the regex.

**Comment by subpub** [comment]
Hello. Keep up the work👍 
As of 2.2.3, minifed ie., #fff #000 doesn't work. Also, I feel the line thickness is a little too thin, especially for closer colors.
