### ISSUE TITLE
Settings: Notebook chooser not working with Turkish app language

### ISSUE THREAD

**Issue by ygz213** [gsantner/markor#1443]
## General information
* App version: `2.8.0`
* Android version: `5.0.1`
* Device: `TCL-8079`
* I understand that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

### Description

Buttons in Settings > General > Save Location do nothing while app language is Turkish. After I change app language as English and restart, It popped up a window and the setting worked.

**Comment by gsantner** [comment]
Hello, thank you for reporting. 

This is probably related to a bad translation string, where tokens are used in the original string.

**Comment by gsantner** [comment]
Fixed by #1455
