### ISSUE TITLE
"Auto" theme should be the default

### ISSUE THREAD

**Issue by SeerLite** [gsantner/markor#1447]
## General information
* App version: 2.8.0
* Android version: 11
* Device: Redmi Note 8
* I understand that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

### Description
I think Markor should use the Auto theme by default instead of the current which is the Light theme. This is how most other apps do it. Since the user already has set the theme in the system configuration, it's a good idea to assume that they want to use that theme everywhere else while also giving the option to override it in each app's settings, and not the other way around.

Thank you for this amazing app

**Comment by SeerLite** [comment]
Additionally, Settings -> Other -> "Navigation bar color" should be set to System instead of the current default.

**Comment by gsantner** [comment]
Both said things are options, and the current values are just defaults. Feel free to set the options the way you like it, thats what options are there for.

**Comment by SeerLite** [comment]
I'm sorry, I'm not sure if I was clear. I know already that the current values are just defaults and that the options can be changed. My suggestion was to _change these defaults_ so that they are consistent with the rest of apps, most of which have "Auto" set as default things like this. This would improve the experience of new users that use dark theme system-wide or that expect it to use the system-wide theme by default.

This doesn't affect me personally at all, as I already do change all kinds of options in the settings. But I know not everyone does, so I thought this would be a nice improvement for new or casual users.

Thank you again for the great app
