### ISSUE TITLE
[feature request] Adding a pin lock

### ISSUE THREAD

**Issue by errorscode** [gsantner/markor#1448]
## General information
* App version: 2.7.0
* Android version: 6.0
* Device: LG K10 2016
* I understand that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

### Description

Hi. hope you doing well. i have a request to add an pin lock to your app and since currently you have a file encryption it would be very good to add this option as well . also i believe it would be very simple to add this option because its far better than external app locks since they can be very easily bypassed and also they are very battery draining and performance heavy . i also found a github repository which may help you if you ever wanted to consider my request.

https://github.com/aritraroy/PinLockView

**Comment by gsantner** [comment]
We had this in the past. But I don't consider it again. Anyway, hiding won't make your stuff more safe - encryption does.

Instead we currently aim for #1250 so you can use a different password for each file.
