### ISSUE TITLE
Update fails since releases >0.1.5 

### ISSUE THREAD

**Issue by surferjoeit** [gsantner/markor#145]
#### General information

* **App version: > 0.1.5** 
* **System: Android 5.0.2** 

#### Cannot install updates since 0.1.5

Hello,
i tried to update the app through F-Droid, but it crashes and force F-Droid to close on installation. Last working release for me is 0.1.5. I also downloaded latest apk from github but when i try to open download folder it forces file manager to close. I mentioned the bug and a possible solution (this seems related to build tools) on:
https://forum.f-droid.org/t/some-app-updates-fail-to-install-and-force-f-droid-to-close/1556/9

Thanks for this great app.

**Comment by gsantner** [comment]
Which is the newer version you tried? The latest update is on F-Droids build queu but not yet signed/released, would suggest to wait for it as it contained a lot of new stuff and fixes :).

**Comment by gsantner** [comment]
In the mean time you can get the latest build from github <https://github.com/gsantner/markor/releases/tag/v0.2.4>

**Comment by surferjoeit** [comment]
I already tried 0.2.4, and it forces file manager to close. I can't even access to apk file, i have to remove it through PC... Other apps had this issue, and it was related to build tools.

**Comment by gsantner** [comment]
This is v0.2.4 compiled by me, signed with the official markor key, not from F-Droid's modified tollchain

**Comment by surferjoeit** [comment]
I downloaded it, no way, i'can't access download folder until i remove the apk file via PC.

**Comment by gsantner** [comment]
ok, hm, have your tried a different file manager too?

**Comment by surferjoeit** [comment]
Yeah... i tried. i'm not a developer, so i can't detail the issue, but all other apps with this issue have been fixed by updating build tools to 27.0.1. Please see: https://github.com/gateship-one/odyssey/issues/100

**Comment by gsantner** [comment]
v0.2.4 is built with 27.0.1 <https://github.com/gsantner/markor/blob/v0.2.4/build.gradle>

**Comment by surferjoeit** [comment]
Uhm.. that's interesting. So i don't know how to help you. The behavior is the described one. I download your release from github (either with PC or with my android device) and when i try to open download location with file manager, one or another, it suddenly closes, so i'm not able to install it. F-Droid releases on the contrary force f-droid to close. For me last working release was 0.1.5.

**Comment by gsantner** [comment]
I can build a pre27 apk specially for you, if you want

**Comment by gsantner** [comment]
does that apk work? [app-flavorDefault-release.zip](https://github.com/gsantner/markor/files/1528234/app-flavorDefault-release.zip)

**Comment by surferjoeit** [comment]
It works, many thanks!
Which was the issue?

Il 04 dicembre 2017 18:59:58 CET, Gregor Santner <notifications@github.com> ha scritto:
>does that apk work?
>[app-flavorDefault-release.zip](https://github.com/gsantner/markor/files/1528234/app-flavorDefault-release.zip)
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gsantner/markor/issues/145#issuecomment-349048298

-- 
Inviato dal mio dispositivo Android con K-9 Mail.

**Comment by gsantner** [comment]
buildTools resolution seems not to take latest installed version but the latest installed major version

**Comment by gsantner** [comment]
if you have google play you can further update from google play, as this was signed with my official key

**Comment by surferjoeit** [comment]
Thanks again foto your help.

Il 04 dicembre 2017 19:55:01 CET, Gregor Santner <notifications@github.com> ha scritto:
>if you have google play you can further update from google play, as
>this was signed with my official key
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gsantner/markor/issues/145#issuecomment-349066485

-- 
Inviato dal mio dispositivo Android con K-9 Mail.
