### ISSUE TITLE
App hanging when loading folder with more than 50 notes (approximately)

### ISSUE THREAD

**Issue by badrow** [gsantner/markor#1450]
## General information
* App version: 2.8.0.
* Android version: 11
* Device: Google Pixel 4a (Calyx OS)
* I understand that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

### Description
Hi, i noticed a bug when using this app, when I tap on a folder with a lot of notes (more than 50), it hangs about 20 secondes before opening the folder. I have some folders with more than 400 notes.
Is it possible to fix that please ? May be it's not possible but I prefere to ask...
For example, making notes loading progressively when opening a folder instead of hanging and display all notes at one time ?

Thanks.

**Comment by gsantner** [comment]
I did major speed improvements recently at https://github.com/gsantner/markor/commit/83a4e2f7a38752897a1c1e7636de7beba585d9b3

not yet released.

**Comment by badrow** [comment]
Thank you !
