### ISSUE TITLE
Slow down with code section

### ISSUE THREAD

**Issue by spersson** [gsantner/markor#148]
If I insert a code section (starting and ending with triple back ticks) in a document and then continues typing in normal text then the text entry quickly slows down, getting several seconds delays after entering a few sentences. If I go back to main file selection view and then in to edit again then it is fine for another 2-3 sentences before slowing down again. I have also tried increasing the highlight delay time from 70 ms to 500ms. That helps but only that it then takes maybe 5-6 sentences of typing before the app slows down. It is still a definite problem. 
I should also say that after the app has become slow it does not help to stop typing for a while. The only thing that I have found helps is going out of the document and back in.

I'm using version 0.2.3.

Thank you very much for an otherwise great app!

**Comment by gsantner** [comment]
can you please fill out ALL details in the issue template?
Device and Android version is missinh

**Comment by gsantner** [comment]
If you can build from git, try out latest git version. Otherwise wait for **v0.2.5** and tell if it is still much slowing down.
