### ISSUE TITLE
v2.8.2 update: contents of QuickNote.md deleted

### ISSUE THREAD

**Issue by kylesorkness** [gsantner/markor#1483]
## General information
* App version: 2.8.2
* Android version: 12 (GrapheneOS 2021110122 stable release)
* Device: Pixel 4a
* I understand that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

### Description

I updated Markor to 2.8.2 last night via F-Droid. This morning, I opened and added to my large QuickNote.md file. Just now (a couple hours later), I opened QuickNote.md again to discover that the only thing in QuickNote.md is the text I had added this morning.

I have tried to duplicate the problem with _other_ .md files in Markor but have been unable. (Granted, I don't know exactly what caused this, since I only noticed the deletion some time after it had presumably taken place.) I have not experimented any more with QuickNote.md itself, in case there is still any way for me to recover the older version of that file. Is there a chance that that would be possible, or have I lost all that data for good? (It was a very large file, so I have my fingers crossed...)

I had not updated Android or any other apps during this period (or since). Nor had I used Markor any differently than I typically do. I'd be happy to provide any more information for troubleshooting, but I'm afraid I don't know what more I could add at the moment.

**Comment by gsantner** [comment]
#1482
