### ISSUE TITLE
Tag like feature

### ISSUE THREAD

**Issue by AndreaHasani** [gsantner/markor#149]
#### General information

* **App version:** 
v0.2.3
* **System:** 
Andrid 7.1.2
#### Description

First of all. Thanks for this amazing app. Was searching all day for a offline app to take my notes which would support saving notes to files so I could sync them offline (I like to use open source apps so no sync clients for me). Luckly I found this app when I was looking for a markdown app for android :D 
So this issue is mostly because I would like to suggest if its possible to have a feature like Tag so we could find our files faster. Having the search being able to support inside file search would work too.

Thanks.

**Comment by gsantner** [comment]
I have to admit, that I want markor to be fully interoptable with any other editor, be it on desktop, be it on mobile. I haev to think what and if this is needed, but basically you already have it (kind of), by using subfolders

**Comment by kantrol** [comment]
I am using Markor in combination with QOwnNotes on my desktop. Besides the orgininal data base driven tag system they recently added a tag system using *in note* tag marking (as script addon) using a simple *@tagname*. They found that there is no common tag scheme for *in note* tagging availbable, but using **@** did not interfere with markdown. 

I would like to see support for this in markor.

**Comment by gsantner** [comment]
you can always save documents in same folder and add `Cool document @tag1 @tag2` and search for `@tag1`.

**Comment by kantrol** [comment]
So putting the tag in the document name? Yes, this is a quick work around.

As mentioned I already use the desktop notes application *QOwnNotes* which is also markdown based. Syncing over to *Markor* makes them a perfect pair -  just leaving the tags incompatible :-(

Thanks for your suggestion.

**Comment by Offerel** [comment]
Hi there, i have written a notes plugin for Roundcube, you can find it here at GitHub under https://github.com/Offerel/roundcube_primitivenotes.

I would like to use maybe your app as a companion on Android. I save the keywords also as part of the filename. The system is compatible with the App TagSpaces.

I use "Note Name[keyword1 keyword2].ext". Currently i use as default html as the primary format, but if we can work together and you would optionally adopt this system, I would switch to markdown as primary format. I think this could be work. I have no clue how to make Android apps, so it would help me much, if you could implement such a tag/keyword system. What do you think about this?

**Comment by gsantner** [comment]
I have to admit, that I would prefer a tag-in-filename based solution, whatever it looks like. I would more go the way of hashtags to (e.g. `family planing #holidays`)  or with @'s.

One has to keep in mind that the filetree may be ... very big, so simple "ok, just scan every file's name every 10 seconds" may not be ideal

**Comment by IzzySoft** [comment]
There are some conventions for [Markdown metadata format](https://stackoverflow.com/q/44215896/2533433) some parsers support (for the "MultiMarkdown variant", also see [here](https://hiltmon.com/blog/2012/06/18/markdown-metadata/)). Not sure how those not supporting it would deal with that text. So alternatively I could think of storing tags (e.g. like `@tag`) in a "hidden area" (`<!-- @tag -->` wouldn't be rendered) at the top of a document. Just my "two cent".

**Comment by gsantner** [comment]
Performance. First searching recursively for documents and then parsing :exclamation: them is not really something I wan't to implement in Markor. And no auto-refresh of tags makes no fun.

**Comment by Offerel** [comment]
Hi there. Meanwhile im using additionally Epsilon Notes. But there are tags now implemented with YAML. This YAML tags are added to a tag database only when such a file is at least one time opened and not for the whole notes folder. 

I have added this tagging features also in my [Roundcube Plugin](https://github.com/Offerel/roundcube_primitivenotes) and added a script for [QOwnNotes](https://github.com/pbek/QOwnNotes). Since YAML is somewhat like a small standard for markdown, this could be also a way for Markor.

**Comment by gsantner** [comment]
While markdown editing is the main reason of Markor, it also supports other plaintext formats too (where we might get to the point were the format spec doesn't allow a YAML frontmatter). 
Still, if you want to implement it that way, I want to suggest to go the way of having a file e.g. `.markor` (inside app cache directory for now) where these things are stored.

**Comment by IzzySoft** [comment]
> Performance. First searching recursively for documents and then parsing exclamation …

I definitely agree. Didn't mean it should be done that way *on each search* – rather thought those get copied to some database or index file whenever the document is saved (and to be on the safe side, scan for new/changed files on startup as well, as something might have been "synced in" meanwhile). Then use the database/index for search – but still keep the Metadata in the file (might be used in a different place). Of course there also could be an option whether Metadata should be saved inside, so the user can chose.

**Comment by gsantner** [comment]
When somebody starts working on this feature:
Please keep also https://github.com/gsantner/markor/issues/205 in mind - please allow to define other attributes for a given file, in this case a `integer`  typed `cursorPos`.

**Comment by def14nt** [comment]
@gsantner What if you just run a regex against the text? Something like `/<!--\s*@(.+)\s*-->` should work, but then I bet there's other that laugh at that regex tbh lol

**Comment by gsantner** [comment]
as noticed, it should support both, normal search&replace and regex.

**Comment by gsantner** [comment]
Markor now has favourites, recents and popular documents.
Thats already quite amount of special lists, currently don't plan to expand the options - Markor already has huge amount for quite everything.
