### ISSUE TITLE
ShareInto: Add URL cleaning

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#1490]
## General information
* App version: 2.8.0
* Android version: 11

### Description
When browsing the web nearly all sites and their interlinks are bloated with tracking and advertising parameters.  
When sharing a link (i.e. from webbrowser) to Markor, you can easily spot the unnecassary long URLs and carry on the trash when appending the link to notes.

* Add to markor: Url cleaning @ ShareInto
* Automatically strip well known offending parameters, like utm_source, utm_campaign, ....
* Show text in ShareInto after URL cleanup

### Examples
Example links, where mostly `MARKOR` is the only relevant parameter/value:
```
https://www.google.com/search?q=MARKOR&oq=PREVIOUS_QUERY&sclient=gws-waz&uact=5

https://www.google.com/search?q=MARKOR&source=hp&iflsig=ALs-wAMAAAxyz&oq=PREVIOUS_QUERY&sclient=gws-waz&uact=5

https://www.google.com/search?q=MARKOR&oq=MARKOR&aqs=chrome..69&sourceid=chrome&ie=UTF-8

https://support.mozilla.org/de/kb/customize-firefox-controls-buttons-and-toolbars?utm_source=firefox-browser&utm_medium=default-bookmarks&utm_campaign=customize

http://www.phoronix.com/scan.php?page=news_item&px=Ioquake3-Auto-Updater&utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+Phoronix+(Phoronix)

https://www.heise.de/news/Die-Eclipse-IDE-feiert-ihren-20-Geburtstag-Happy-Birthday-6253926.html?wt_mc=rss.red.ho.ho.atom.beitrag.beitrag
```

### Additional references
* Similar utility, addon for Firefox desktop browser <https://github.com/Smile4ever/Neat-URL>, <https://addons.mozilla.org/de/firefox/addon/neat-url/>

**Comment by Self-Perfection** [comment]
I'd say this is not the job of Markor to cleanup URLs. The better way would be is to keep Markor as simple as possible. One can already achieve such behavior by sharing URL to something like https://f-droid.org/packages/moe.dic1911.urlsanitizer first.
