### ISSUE TITLE
Markor is very slow in loading files in Android 11

### ISSUE THREAD

**Issue by skillhacker-code** [gsantner/markor#1492]
## General information
* App version: Latest
* Android version: 11
* Device: Redmi note 5 por 
* I understand that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

### Description

I installed markor in android 10 and it was very fast .

But when i installed markor in android 11 and it is very slow and some times show there is no file .

So i tired different custom roms and i found out that markor is slow in android 11 but it is very fast in android 10.

It would be great if you can fix it .

**Comment by gsantner** [comment]
> App version: Latest

Please specify the version. Latest is not always latest.

btw, my daily device is Android 11 and I cannot say it's slow.

**Comment by gsantner** [comment]
> App version: Latest

Please specify the version, this field is there for a reason. Latest is not always latest.

btw, my daily device is Android 11 and I cannot say it's slow.

**Comment by skillhacker-code** [comment]
version 2.8.0 

i am closing this .
