### ISSUE TITLE
Overwrites changed files with out-of-date cached version

### ISSUE THREAD

**Issue by qtist** [gsantner/markor#1493]
## General information
* App version: v2.8.0 (124)
* Android version: 11 (OneUI 3.1)
* Device: Note20 Ultra

### Description

* I use Syncthing to sync my Documents folder between my Android device and PC. 

I noticed that when changes have been made on the PC and are synced to my phone, Markor does not detect these changes and requires killing + re-opening to detect any changes to notes files. Opening Markor and viewing an old cached version of a document will result in the newer version on-disk being overwritten and all newer changes lost. 

My problem has been described in a comment by @seelaman on an older issue: [here](https://github.com/gsantner/markor/issues/954#issuecomment-700132290)

Every time Markos gains focus, it should check if open files have been changed and reload them. I really like this app but this problem with reverting my files is a deal-breaker.

**Comment by gsantner** [comment]
The current version is 2.8.3. Try with that please.

**Comment by qtist** [comment]
Ah, I didn't realise Play Store and FDroid were behind. I'm not in a position to build 2.8.3 but have just tried the 2.8.1 APK and that appears to have solved the issue! This is much better, thank you :)

**Comment by gsantner** [comment]
fdroid should be already out, sometimes takes a bit :D
