### ISSUE TITLE
File modification date/time changes without modifying file

### ISSUE THREAD

**Issue by ljb279** [gsantner/markor#1494]
## General information
* App version: v2.8.3
* Android version: 10

### Description
Opening any file, then closing it without changes, results in the modification date/time of that file being changed to the current date/time.

Starting Markor changes the modification date/time on my Todo and QuickNote files, without even opening those files.

Markor should not change the modification date/time of a file unless it was modified, so we can tell when a file was actually changed.

I think this started in v2.8.2 and continues in v2.8.3.

**Comment by harshad1** [comment]
This has generally been the behavior always. We always load the file on open and save the file when the file is hidden 

I recently tried adding logic to prevent saves using the mod time, but this led to issues as the android file mod time is kinda unreliable.

I will continue to try and fix this as it affects me too. But no guarantee.

**Comment by ljb279** [comment]
I reverted to markor-2.8.1(125) to test this again. For me, opening Markor-2.8.1 does not change the modification date/time of my Todo or Quicknotes, nor does opening a file and quiting without changing, even if I switch to edit mode from view mode. So I still think this started at 2.8.2.

I assumed this was related to fixes made for issues I saw here and in discussions related to caching, and I figured this would be hard to fix while not breaking elsewhere. But I do appreciate keeping the issue open.

**Comment by mbomb007** [comment]
Couldn't you at least check if the edit button has been pressed, and only save it if so? View are Edit are distinct actions, so that shouldn't be too hard.

**Comment by pudah** [comment]
I am having the same issue. Version 2.8.3 on Android 11 updates files that are simply opened in view mode.

**Comment by pudah** [comment]
And just opening the program updates the time stamp on the todo.txt and Quick Notes files.

**Comment by harshad1** [comment]
This should have been solved with the merging of #1489. You can get a debug apk from https://github.com/gsantner/markor/actions/runs/1484343141 (it will install alongside markor as 'mordor') to test if things are working correctly.

**Comment by gsantner** [comment]
> And just opening the program updates the time stamp on the todo.txt and Quick Notes files.

Please use a thumbs up reaction on the issue issue. We know it sets file timestamp on every file at this specific version.

-----

Btw, there was one person saying that asked to always write regardless if content changed or not - when you read this...as you can see theres lots of people offended by this.

**Comment by gsantner** [comment]
> And just opening the program updates the time stamp on the todo.txt and Quick Notes files.

Please use a thumbs up reaction on the issue topic. We know it sets file timestamp on every file at this specific version.

-----

Btw, there was one person who suggested to always write regardless if content changed or not - when you read this...as you can see theres lots of people offended by this.
