### ISSUE TITLE
How to specify the upload folder

### ISSUE THREAD

**Issue by HOMMEEN** [gsantner/markor#1496]
## General information
* App version: v2.8.0(124)
* Android version: HarmonyOS 2.0.0
* Device: HUAWEI Mate30 Pro
* I understand that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

### Description
I would like to implement a two-way synchronization between Typora and Markor. In this way, I have to set a fixed folder to store the images. This can be done relatively easily on Typora, but I haven't found a similar setup in Markor for now.

**Comment by gsantner** [comment]
Markor is focused on offline usage, there are no "upload" or "sync" features, intentionally.
