### ISSUE TITLE
Freeze in view mode

### ISSUE THREAD

**Issue by chromer030** [gsantner/markor#1499]
## General information
* App version: 2.8.3 FDROID
* Android version: 7.1.2 arm64
* Device: Lenovo
* I understand that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

### Description
In view mode of large files, app will freeze when scrolling down.

**Comment by gsantner** [comment]
Large files generally tend to be an issue - not only for view mode.

View mode also much depends on your Webview and it's performance.  
Which android device do you have, and is it the stock webview or some custom one (i.e. Bromite)?

**Comment by chromer030** [comment]
Thank you for your explanation.
I have custom rom that it's webview is based on Bromite and after some test it seems that the issue is webview , i have this freeze in other webview based apps.
Closing this issue because culprit is not Markor.
Thank you again.
