### ISSUE TITLE
Option to use default system file picker

### ISSUE THREAD

**Issue by rancidfrog** [gsantner/markor#150]
The current file picker is not useful, as the name nor the image in the case of images can be seen.
I.E.
![](https://i.imgur.com/nXu5Dpj.png)

An option to use default system file picker can be useful, so that file name can be read or thumbnail can be used to select images.

**Comment by gsantner** [comment]
The problem is that many (as is most android devices i used eved) don't have any. So default is not an option.

if somebody starts with this, both file and folder selection is needed.

**Comment by duckbrain** [comment]
You could probably fire off the standard intent, and make sure that Markor is a receiver of that intent.

https://developer.android.com/guide/topics/providers/document-provider.html

That way, if you don't have a file picker, it will use Markor, otherwise, Android will ask the user.

**Comment by gsantner** [comment]
@duckbrain Your suggestion requires #126 to be done first, where contributions are very welcome.
