### ISSUE TITLE
Few features 

### ISSUE THREAD

**Issue by banishedsoul** [gsantner/markor#1500]
## General information
* App version: 2.8.3 
* Android version: 9 
* Device: Redmi note 7 pro 
* I understand that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

### Description
Would be eternally grateful if you can add these features 
1. Option to add multiple images at once 
2. Table option in editor toolbar to print entire table.. Ex - option to choose 3x2 tables without typing
3. A little  better aesthetics (P. S.  - I am more than  satisfied with the current aesthetics) 
4. Add an option to donate via other options (other than PayPal.. As PayPal doesn't let me donate from India) 
5. In view mode unable to copy email ids

Overall I am in awe that such an app can exist that too foss.. 
Much obliged and grateful to the dev.. 
♥️ from India

**Comment by gsantner** [comment]
1. Possibly, but at same time, you can add as much media as often you want
3. There is a button for tables in toolbar, and you can choose its size. Long press the button to lay out the header (i.e. start a 3 column table), then everytime you want to add a new row, short press the table button.
3. Personal
4. I check
5. Hm, you should be able to copy any text. make sure to use link syntax so they appear as link. `<me@example.com>`
