### ISSUE TITLE
setDocumentViewVisibility() has been called 3 times when opening a file.

### ISSUE THREAD

**Issue by tifish** [gsantner/markor#1502]
## General information
* App version: 7dc3b05c5807340f347208fb591f4ae20a5499bf@master
* Android version: 11
* Device: OnePlus 7 Pro

### Description
When opening a file:
* `DocumentEditFragment.loadDocument()` has been called twice.
* `DocumentEditFragment.setDocumentViewVisibility()` has been called 3 times.

May have some optimization here.

**Comment by gsantner** [comment]
quick test couldn't reproduce the issue (for loadDocument - only one file read, thats the important part):

https://user-images.githubusercontent.com/6735650/142717000-9e45fc7b-82f7-4e3d-8f88-a722e25fcc98.mp4

Though yes, currently there is work ongoing to improve/optimize file loading (and making the content into the UI). #1489 #1487

If you want to help, help & pull requests are welcome!

**Comment by tifish** [comment]
I have seen these been fixed today in 06ad871dc8b622c7e5bdab2c76dd7f622527c495 and d3e91a8a652cacad4ce2919f451d5eb01b1af66c :)
