### ISSUE TITLE
[feature request] Ticking checkboxes in viewing mode.

### ISSUE THREAD

**Issue by reinholdeins** [gsantner/markor#1506]
## General information
* App version: 2.8.3
* Android version: 12
* Device: Pixel 4a
* I understand that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

### Description

Is it possible to add the feature of ticking checkboxes in viewing mode + transfer of the ticks back into the editing mode?

E.g.:

https://user-images.githubusercontent.com/72997283/142740566-7f7dc02f-58ff-4177-a89e-7bbf91803c85.mp4

Cheers!

**Comment by dtcg** [comment]
I see this was marked as completed some years ago but it doesn't seem to be currently working on my device : checkboxes are untickable in view mode.

Device : Huawei p20 pro
OS : EMUI 12.0.0
Markor version 2.11.1

**Comment by gsantner** [comment]
Duplicate.

**Comment by dtcg** [comment]
Could you kindly redirect me to the source of the mentioned duplicate please?
