### ISSUE TITLE
Enable autocompletion/correction at search dialogs

### ISSUE THREAD

**Issue by brunetton** [gsantner/markor#1507]
## General information
* App version: 2.8.3 (127)
* Android version: 10
* Device: Huawei p30 lite
* keyboard: [Swiftkey keyboard](https://play.google.com/store/apps/details?id=com.touchtype.swiftkey)

### Description
Hi,

I use search function a lot in Markor; and I always found weird that keyboard autocomplete isn't activated in search form. Keyboard doesn't provides any help for entering "real" words. Instead the keyboard acts like in a password field; ie no autocomplete nor word correction is available.
As notes are globally human text, with human readable names (ie `my favorite apps.md`), it would make sens to me that keyboard should propose me to input words.

**Comment by harshad1** [comment]
Do you mean this?

![image](https://user-images.githubusercontent.com/1940940/142928232-dc62fe2b-8b4d-47ac-873f-da19db898c44.png)


If so, it appears to work for me...

**Comment by gsantner** [comment]
Might be related to keyboard and it's settings.

I.e. I see the suggestions at web browser, but not at that search dialog.

keyboard OpenBoard <https://f-droid.org/en/packages/org.dslul.openboard.inputmethod.latin/>

![screenshot-2021-11-22__21-45-11](https://user-images.githubusercontent.com/6735650/142933049-8038ea3a-ca3e-46ff-b0e3-0c15ebb7c149.png)

**Comment by brunetton** [comment]
> Do you mean this?
> 
> ![image](https://user-images.githubusercontent.com/1940940/142928232-dc62fe2b-8b4d-47ac-873f-da19db898c44.png)
> 
> If so, it appears to work for me...

Yes, exactly this. Did you edited the code or is it the official version ?

**Comment by brunetton** [comment]
> Might be related to keyboard and it's settings.
> 
> I.e. I see the suggestions at web browser, but not at that search dialog.
> 
> keyboard OpenBoard https://f-droid.org/en/packages/org.dslul.openboard.inputmethod.latin/
> 
> ![screenshot-2021-11-22__21-45-11](https://user-images.githubusercontent.com/6735650/142933049-8038ea3a-ca3e-46ff-b0e3-0c15ebb7c149.png)

I think this is related to [this line in FileSearchDialog.java](https://github.com/gsantner/markor/blob/master/app/src/main/java/net/gsantner/markor/ui/fsearch/FileSearchDialog.java#L96).

Check my related PR that fixes this (in my case): https://github.com/gsantner/markor/pull/1508

Thanks

**Comment by harshad1** [comment]
> Yes, exactly this. Did you edited the code or is it the official version ?

I am using `https://github.com/gsantner/markor/pull/1467`. But there should be nothing related to autocomplete in there...

**Comment by brunetton** [comment]
> > Yes, exactly this. Did you edited the code or is it the official version ?
> 
> I am using `https://github.com/gsantner/markor/pull/1467`. But there should be nothing related to autocomplete in there...

Maybe the keyboard you're using ignores the `InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS` option ? 
Nevermind, I solved the problem for my case in this PR: https://github.com/gsantner/markor/pull/1508
