### ISSUE TITLE
Android Launcher-specific white flash when starting Markor (Markor icon in external splashsceen)

### ISSUE THREAD

**Issue by garret** [gsantner/markor#1517]
## General information
* App version: 2.8.3 (from F-Droid)
* Android version: 12
* Device: Pixel 6

### Description
Screen flashes to white (even though the app is set in dark mode). This occurs especially when opening the app for first time and the markor logo just flashes in a white background. This is a bit annoying,especially when opening the app at night. I think that it is a solvable fix as also recently the app Lemmur had the same issue and was fixed in the latest update. 

References: 
- https://github.com/krawieck/lemmur/releases/tag/v0.7.0
- https://github.com/krawieck/lemmur/pull/257
- https://github.com/krawieck/lemmur/pull/256

**Comment by gsantner** [comment]
search issues.

**Comment by garret** [comment]
@gsantner what do you mean with "search issues, use the existing one"?

**Comment by gsantner** [comment]
The template for issues contains this, it's there for a reason:

```
## General information
* App version: 
* Android version:  
* Device: 
* I understand that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).
```

**Comment by garret** [comment]
@gsantner thanks for explaining. Could you please point me to the issue that would be an exact duplicate of this? I searched for "white" in the issues box and could only find another issue that seems similar (I even commented there) https://github.com/gsantner/markor/issues/568 but it is not the same. For this reason, I opened a new one. But maybe I am not good in searching as you write :)

**Comment by gsantner** [comment]
568 is the same cause

**Comment by garret** [comment]
Thank you very much for solving this! I had told you it could be fixed independently from the android launcher! :)
