### ISSUE TITLE
Can`t preview .gif and .webp images

### ISSUE THREAD

**Issue by marvinav** [gsantner/markor#1528]
## General information
* App version: v2.8.0(124)
* Android version: 11
* Device: Galaxy A52
* I understand that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

### Description
Links to local .gif files displayed as empty area without content. Is there any way to show preview of them inside my notes?

**Comment by gsantner** [comment]
Have you used the proper syntax in that files format?

In Markdown use `![name](file.gif)`.

Markor won't open gif inside though if you click it (a link) - thats what a gallery app is for.

See also <https://github.com/gsantner/markor/issues/1200>
