### ISSUE TITLE
Underscores in filenames break filename truncation logic

### ISSUE THREAD

**Issue by Self-Perfection** [gsantner/markor#1530]
## General information
* App version: 2.8.4
* Android version: 9
* Device: Xiaomi Mi A1

### Description
Let's compare display of two similar directories:
```
$ ls --literal -1 *
Check_truncation:
Tenet_—_Довод_(2020)_[Кристоф.txt
Tenet_—_Довод_(2020)_[Кристофе.txt
Tenet_—_Довод_(2020)_[Кристофер.txt
Tenet_—_Довод_(2020)_[Кристофер_.txt
Tenet_—_Довод_(2020)_[Кристофер_Н.txt
Tenet_—_Довод_(2020)_[Кристофер_Но.txt
Tenet_—_Довод_(2020)_[Кристофер_Нол.txt
Tenet_—_Довод_(2020)_[Кристофер_Нола.txt
Tenet_—_Довод_(2020)_[Кристофер_Нолан.txt
Tenet_—_Довод_(2020)_[Кристофер_Нолан].txt

Check_truncation_space:
Tenet — Довод (2020) [Кристоф.txt
Tenet — Довод (2020) [Кристофе.txt
Tenet — Довод (2020) [Кристофер .txt
Tenet — Довод (2020) [Кристофер.txt
Tenet — Довод (2020) [Кристофер Н.txt
Tenet — Довод (2020) [Кристофер Но.txt
Tenet — Довод (2020) [Кристофер Нол.txt
Tenet — Довод (2020) [Кристофер Нола.txt
Tenet — Довод (2020) [Кристофер Нолан.txt
Tenet — Довод (2020) [Кристофер Нолан].txt
```
These two dirs have similar list of files but it one case underscores are used and in the other spaces are used instead. Here is how Markor shows these directories:
![Screenshot_20211212-224536_50%](https://user-images.githubusercontent.com/3757038/145728006-25ec5ede-1f4a-487c-9186-a017e0f28c7c.png)
![Screenshot_20211212-230844_50%](https://user-images.githubusercontent.com/3757038/145728007-2e7d85a7-60a3-4359-be24-93d28ba01f2d.png)

In case of using underscores lots of data is omitted. There is just blank space instead of something meaningful.

This difference bites when using Markor to manage Zim notes because Zim replaces spaces in note names with underscores.

**Comment by gsantner** [comment]
OK, so can you @Self-Perfection confirm whether this is specific to when using Zim files or just generally with all kinds of files?

**Comment by Self-Perfection** [comment]
@gsantner in my example files are created with `touch "$FILENAME"` and have zero size. These files are just empty plain text files.

It affects anyone who use underscores instead of spaces in filenames.

Zim users are affected more than others because they does not have a choice, it's always underscores for them.

**Comment by gsantner** [comment]
OK thanks, haven't checked it out, but when can be reproduced it is probably related to some filename input sanitization at saving.

**Comment by gsantner** [comment]
OK thanks, haven't checked it out, but when can be reproduced it is probably related to some filename input sanitization.

**Comment by gsantner** [comment]
I tried on current master and could not reproduce. So seems like fixed already.

**Comment by Self-Perfection** [comment]
Indeed, with 2.8.5 it works better. Filenames too long to fit in one line are just wrapped to several lines and no parts of filename are elided.
