### ISSUE TITLE
How to make <a> link content has a soft wrapper show?

### ISSUE THREAD

**Issue by fanlushuai** [gsantner/markor#1536]
## General information
* App version: v2.8.1
* Android version:  11
* Device: OPPO K9 
* I understand that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

### Description

Md text content contains  some links with a long text. like:

https://www.google.com/exampletext/exampletext/exampletext/exampletext/exampletext/exampletext/exampletext/exampletext

In md preview, the link content doesnot has soft wraper show so that preview exsit uncomfortable horizontally scroll. like:

![ffb888497ca6285988c784faa0346c5](https://user-images.githubusercontent.com/21078607/147085029-6323c231-8ffd-4099-a8e8-b46807c3adf0.jpg)

**Comment by gsantner** [comment]
It should be a matter of adding one additional CSS entry to improve that. It can be tested locally on any device by the Markor Inject settings. When you got it as expected, it can be added to Markor so it's this ways "by default".

**Comment by fanlushuai** [comment]
@gsantner Thanks. 
```
<style>

 a,p{
    word-break:break-all;
 }

</style>

```

**Comment by gsantner** [comment]
It's required to apply it to block (p) right? So just a is not enough

**Comment by fanlushuai** [comment]
> It's required to apply it to block `p` right? So just `a` is not enough
> 
> maybe p+a or p > a?

Yes，`p` reqiure too . when include a long code refrence text. `p` text over long.

p>a is right. I  have tested the using of only p,. Thanks for your kindly help

```
<style>

 p{
    word-break:break-all;
 }

</style>
```

**Comment by gsantner** [comment]
ok, then I think about adding `p>a` generally.

**Comment by gsantner** [comment]
ok, then I think about adding `p>a` generally.
