### ISSUE TITLE
Text disappears when moving between apps (sometimes)

### ISSUE THREAD

**Issue by supersonic71** [gsantner/markor#1537]
## General information
* App version: v2.8.4 (128)
* Android version: 11
* Device: Realme Narzo 30
* I understand that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

### Description
Steps : 

1. Create/Open a new file
2. Also open another app (say a web browser)
3. Go back to file, add some lines say 
    line 1
    line 2 
    line 3
4. Now go to second app
5. Now come back to file. 

Sometimes some lines are missing, like only first or second line is shown. 
Interestingly, if you close and open the file again, it all appears correctly. 

Anyone else having this issue? This doesn't happen always but when it happens it is super frustrating haha. 

I don't have any battery/background restrictions on Markor.

**Comment by harshad1** [comment]
Could you install the version from here: https://github.com/gsantner/markor/suites/4708659133/artifacts/129116169 and see if you can reproduce the issue? This version will install alongside your existing markor install as 'mordor'

**Comment by supersonic71** [comment]
Hi Harshad, 
Was not able to reproduce in that.

**Comment by gsantner** [comment]
is there something differently not working there, but is in the current release?

**Comment by cpjames-prog** [comment]
Can confirm the issue is present in my current version 2.8.1 (125), but not present in the Morder apk given above.

(On Nexus 5X - Lineage OS Android 10)
