### ISSUE TITLE
Changing filename fails on only case/capitalisation adjustment

### ISSUE THREAD

**Issue by cpjames-prog** [gsantner/markor#1541]
## General information
* App version: 2.8.1
* Android version: 10
* Device: Nexus 5X

### Description

Recreate:
1. Open "Files"  
2. Highlight a file  
3. Tap to change name  
4. Vary the case of one of the letters
5. "File/folder already exists! Please use a different name"

**Comment by cpjames-prog** [comment]
Just tried creating two files "test.md", "Test.md" using filesystem app, but that's not allowed.

Seems like a feature of the filesystem, rather than the app. Sorry! I'll close it.

**Comment by gsantner** [comment]
Yes filesystem on android is usually insensitive.

Simple trick: rename to xest.md, and then to Test.md.
