### ISSUE TITLE
Image not getting rendered in HTML

### ISSUE THREAD

**Issue by anishmittal2020** [gsantner/markor#1547]
## General information
* App version: 2.8.0
* Android version: 11
* Device: Samsung A70
* I understand that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

### Description

- Case 1: Renders Properly

```markdown
# Head 1

![Title](Image/Image.png)

```
- Case 2: Image is rendered and shows the text `{#fig: width="1500px"}` which is acceptable but undesirable

```markdown
# Head 1

![Title](Image/Image.png){#fig: width="1500px"}

```

- Case 3: Image is not at all rendered!

```markdown
# Head 1

![Title][]

  [Title]: Image/Image.png {#fig: width="1500px"}

```

---

Markor does not support `{#fig: width="1500px"}` for images. Could you please ignore it such that image is atleast rendered in Case 3?

**Comment by gsantner** [comment]
Please ask at Flexmark-java, Markors Markdown parser.

The fig: stuff is not something I'm used to at Markdown, and the markdown Commonmark spec doesn't include such a thing.  <https://spec.commonmark.org/0.30/>

I recommend to use just `![name](link)`, which works for sure given you have the link correct.

**Comment by lamyergeier** [comment]
@gsantner 

> I recommend to use just `![name](link)`, which works for sure given you have the link correct.

Is it possible to render the image while ignoring `{#fig: width="1500px"}`?

**Comment by gsantner** [comment]
@lamyergeier You can use CSS `img { width: 123px !important; } ` for example to force a specific width on images.

**Comment by lamyergeier** [comment]
Thats ok but could we render the image atleast with  `{#fig: width="1500px"}` even without resizing? The issue is that the image is not at all rendered!

**Comment by gsantner** [comment]
Use normal `![title](imageurl)` syntax. That works everywhere with Markdown.

**Comment by lamyergeier** [comment]
> Use normal `![title](imageurl)` syntax. That works everywhere with Markdown.

Thats true, but `![title](imageurl)xxxx`  this should not prevent it either. May be I am wrong.
