### ISSUE TITLE
Search (+replace?)

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#155]
#### General information

* **App version:** 0.3.0
* **System:** 7.0.1

#### Description

Add search feature to document editor. This will allow to enter text, jump between found results. Maybe display matches and current jumped index too. (e.g. 5/10).

If time available, too go for simple search and replace. Add an "Replace all" action too in this case.

**Comment by JohnVeness** [comment]
This would be useful in the preview view, too.

**Comment by seth100** [comment]
+1

**Comment by gsantner** [comment]
Please use githubs comment thumbs up. this `+1` stuff helps nobody.

open for PRs.

**Comment by marwal88** [comment]
Add regexp library and a way to store expressions in a menu. Using insertpoints shown to the user as a form.
This would elevate this app.

**Comment by gsantner** [comment]
you dont need a seperate library for using regex.
common case and default case is simple search and option with more if wanted.
open for pull request and community work.

**Comment by gsantner** [comment]
seperate library for using regex is not needed. common case and default case is simple search and option with more if wanted.


**open for pull request and community work.**

**Comment by def14nt** [comment]
@gsantner This would be great (the editor menu does look a bit thin) and I can't wait to see it! Where do *you* think it should go in the editor?

**Comment by gsantner** [comment]
Closing as search is available in editor & filesystem.
