### ISSUE TITLE
markdown: auto format tables

### ISSUE THREAD

**Issue by Tapsi** [gsantner/markor#1551]
### Description

As a user I want my tables to be automatically formatted. As result it will be more readable in edit mode.

E.g. 

```
A | B
Long Text | Also long
```

Will be converted to 

```
A         | B
Long Text | Also long
```

**Comment by gsantner** [comment]
tables on mobile generally are a bit  troublesome. width is limited, and unless you make tables with one word on 2 columns...you are out of space.

might be a unpopular opinion, but do minimum space. you at least get some columns to fit in same line (/ same screen with hscroll)

**Comment by dcdom2** [comment]
Can this be implemented without the auto part (i.e. user-initiated reformatting)? Many tables are narrow enough even for mobile and without constant reformatting, they are difficult to work with.

Thanks
