### ISSUE TITLE
When sharing a link, a space is inserted at the end of the URL, before the final bracket

### ISSUE THREAD

**Issue by mglh** [gsantner/markor#1552]
## General information
* App version: v2.8.4
* Android version: 9
* Device: Sony Xperia XA2
* I understand that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

## Description

When sharing a link, e.g. from Firefox, a space is inserted at the end of the URL, before the final bracket.

## Schematic view

```
[Link](https://example.net/<space>)
                           ^^^^^^^
```

**Comment by gsantner** [comment]
yes this is intentional.

when you reshare this text "as is", apps like whatsapp will preview/show `https://example.net/`. If it's without space - `https://example.net/)`.

wontfix.
