### ISSUE TITLE
Zim subpages are saving in some alternate location

### ISSUE THREAD

**Issue by victorfeight** [gsantner/markor#1556]
## General information
* App version: 2.8.1
* Android version: 12
* Device: Google Pixel 3
* I understand that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

### Description

Say I have a Zim Notebook saved in /storage/emulated/0/Documents (appearing as "Documents" folder on my Pixel internal storage).

Say I have a Hierarchy like this:
/storage/emulated/0/Documents/markor/GTD
--Home.txt
--Home/Someday.txt

Within Home I have the following links structure:
* [[+SomeDay]]
* [[Inbox]]
Clicking [[Inbox]] correctly resolves to /storage/emulated/0/Documents/markor/GTD/Inbox.txt

Clicking [[+SomeDay]] expected behavior:  resolve to /storage/emulated/0/Documents/markor/GTD/Home/SomeDay.txt
Instead what happens is this:
![image](https://user-images.githubusercontent.com/199408/148459868-fe6b897a-7023-46c7-bf86-011c6ce0fce1.png)

Resolved to : /data/user/0/net.gsantner.markor/files

I'd have no problem using this directory, except I can't seem to find it in Android file explorer or Windows explorer.
It seems to be under AppData (private)
/data/user/0/net.gsantner.markor has several files that have been created through this new link process.

To test, I created a new Zim wiki page under /data/user/0/net.gsantner.markor/files called twst.txt and created a link like so:
[[+Test|Test]]
This gets correctly resolved to /data/user/0/net.gsantner.markor/files, leading me to believe the path logic is working but there is some issue writing to internal storage on my end.

**Comment by gsantner** [comment]
@fredericjacob Zim specific syntax/referencing?

**Comment by fredericjacob** [comment]
Hm strange, links with "+" should just be resolved as subpages. I'll take a look at this.

How does the original text file look (i.e. in edit mode, not in view mode)?
Does the same problem occur if you open the link in edit mode?
And can you please check your notebook location in the settings? It should be relevant for these kinds of links, but might still be helpful for debugging.

**Comment by victorfeight** [comment]
![image](https://user-images.githubusercontent.com/199408/149123189-a4871389-bf39-42fc-b997-cf58b6f61b3f.png)
Sorry about the tint. Hmm, attempting to click on the links in edit mode does nothing really, just lets me edit the text. 

Local file settings:
![image](https://user-images.githubusercontent.com/199408/149124644-ad4f2d7d-41ae-4a87-afed-25f1c6dba9d9.png)

Global settings:
![image](https://user-images.githubusercontent.com/199408/149124675-45184f5f-4824-469f-b141-e148127a575a.png)

Let me know if there's any other info or steps, hoping to help resolve it.

**Comment by fredericjacob** [comment]
Thanks for the screenshots. The link syntax looks fine...
There's another subpage link "SubPage", does this one resolve correctly?

You can open links in edit mode, too, by placing the cursor on a link and clicking the "Open link" icon in the symbol bar below (I would describe it as an "arrow pointing up in a stylized window").
What happens if you do this?

Can you also tell me the default notebook location in the settings? It can be found under More > Settings > General > Notebook

**Comment by victorfeight** [comment]
When clicking on Subpage, it brings up a blank white page with the following file information:
![image](https://user-images.githubusercontent.com/199408/149217144-dd2d385c-50da-4413-a285-23cf16616363.png)

Ahh, I see the button now. It only shows in landscape mode for me.

So, I first put the cursor over one of the links:
![image](https://user-images.githubusercontent.com/199408/149217838-e4d9374a-4da0-4edc-ae79-41dcf08a0f49.png)

Then, whichever link I click, brings me to an external URL in the browser (my github link, weirdly):
![image](https://user-images.githubusercontent.com/199408/149217930-718fbc30-7025-40b3-9a26-282bb499da93.png)

Settings under More > Settings > General > Notebook: Documents/markor
![image](https://user-images.githubusercontent.com/199408/149218161-cca403a2-962d-44c9-a771-7590d242fa61.png)

which appears as:  /storage/emulated/0/Documents/markor
when selecting the Save location.

**Comment by fredericjacob** [comment]
Okay, good to know that your notebook directory is set correctly - so the issue seems not to be related to some (wrong) top-level/relative link resolving.
Interestingly clicking the link seems not to recognize the zim links (what happens instead is that the "default" link resolving logic kicks in - the nearest URL to the left side of the cursor is recognized, which is your github link).

I'll try to reproduce the behaviour and report when I know more. Would  you mind to provide me the text file of your "Home" page so that I can use this for debugging?

P.S.: You can also access the "Open link" button (and other ones) in horizontal mode - it is scrollable by dragging over it. 😉 The action buttons and their order can be customized in the settings, by the way.

**Comment by victorfeight** [comment]
[Home.txt](https://github.com/gsantner/markor/files/7858890/Home.txt)
Here is my home file. Let me know if I can upload or test anything else on my end. Yea, it's a weird issue, I'll try debugging more in the coming days as well.

**Comment by fredericjacob** [comment]
I tried to reproduce the issue on an emulator with Pixel 3 (API 30), but everything worked fine there.
I created the following notebook structure, using your Home.txt file:
├── Home
│   ├── SomeDay.txt
│   └── SubPage.txt
├── Home.txt
└── notebook.zim

Both the link to "SubPage" and to "SomeDay" are displayed correctly in view mode, and both of them open the corresponding page like expected.
![grafik](https://user-images.githubusercontent.com/45181277/149634625-018ca5c5-22dd-4601-b55f-2b6a28da4cb1.png)

@victorfeight Could you please update Markor to the most recent version and check if the problem still occurs?
Does Markor have all the needed permissions to access the file system on your phone?
And is this the only file where you face the issue or does the same happen in other files as well?

**Comment by victorfeight** [comment]
> I tried to reproduce the issue on an emulator with Pixel 3 (API 30), but everything worked fine there. I created the following notebook structure, using your Home.txt file: ├── Home │   ├── SomeDay.txt │   └── SubPage.txt ├── Home.txt └── notebook.zim
> 
> Both the link to "SubPage" and to "SomeDay" are displayed correctly in view mode, and both of them open the corresponding page like expected. ![grafik](https://user-images.githubusercontent.com/45181277/149634625-018ca5c5-22dd-4601-b55f-2b6a28da4cb1.png)
> 
> @victorfeight Could you please update Markor to the most recent version and check if the problem still occurs? Does Markor have all the needed permissions to access the file system on your phone? And is this the only file where you face the issue or does the same happen in other files as well?

After updating to the most recent release, it fixed the issue and I was able to properly use Markor with my zim notebook, with all the links and sublinks properly working, and the aforementioned strange behavior disappearing. I would agree with you that it might have been a strange permission issue (though I recall reinstalling a previous version to the same bug).

I appreciate your thorough debugging and will close this  and totally looking forward to enjoying my Portable Zim notebooks.

**Comment by fredericjacob** [comment]
Okay, good to know that it finally worked. 👍☺️
