### ISSUE TITLE
Crash after rotating the note to landscape or back to portrait 

### ISSUE THREAD

**Issue by chromer030** [gsantner/markor#1565]
## General information
* App version: 2.8.5
* Android version: 7.1.2 arm64
* Device: Lenovo, ViperOS
* I understand that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

### Description
App will crash when we are inside a note and trying to rotate the device to landscape mode or after opening the note in landscape mode and trying to rotate to portrait mode , the app itself is OK and no problem and crash , the issue happens when we are inside the note and especially edit mode.

![Screenshot_20220116-182459](https://user-images.githubusercontent.com/13361552/149665421-b52682a5-efe2-4476-bf9f-a43d35ad8e32.png)

**Comment by fsover2** [comment]
I'm experiencing the same problem

- App version: 2.8.5 (129)
- Android version: 11 aarch64
- Device: google Pixel 5a, CalyxOS 2.11.0

**Comment by yaomtc** [comment]
This is happening to me on 2.10. I open up Quicknote and rotate the screen and it crashes.

**Comment by yaomtc** [comment]
This doesn't happen on other notes, just Quicknotes

**Comment by gsantner** [comment]
Your issue is unrelated to this one. But anyway, it is fixed with the next Markor update. 

https://github.com/gsantner/markor/pull/1781

**Comment by yaomtc** [comment]
Thanks, couldn't find another report for this issue. Good to hear!
