### ISSUE TITLE
per-file-settings: incl favorite state when renaming/moving a file

### ISSUE THREAD

**Issue by mbomb007** [gsantner/markor#1566]
## General information
* App version: 2.8.4
* Android version: 8.1
* Device: Samsung j3
* I understand that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

### Description

Star a txt file
Rename it
The file icon is no longer yellow, and it needs to be restarred

**Comment by harshad1** [comment]
Yeah, we store starred files by path. You'll notice that the file will become starred again if you rename it back.

The solution is to update the path in starred files when a file is renamed. Should probably update all per-file-option paths too.

Obviously this will not work if the file is updated outside Markor.

**Comment by gsantner** [comment]
Yeah it's not only about starring. Any file, be it renamed outside markor or inside, is treated as new file, with new own settings. which also includes starred.

**Comment by Twilight-Shuxin** [comment]
Hi @gsantner  I'd like to volunteer for this work if the change is preferred. Is it still open?

**Comment by gsantner** [comment]
yes. but be said, it's a bit advanced topic.

**Comment by Twilight-Shuxin** [comment]
Okay thanks, it would also be great if there could be any guide or suggestions. I'd try my best to understand the file system and solve this issue.

**Comment by harshad1** [comment]
The filesystem is just a basic Android filesystem. We store a mapping of path -> setting for each file in a flat map.

What needs to be done is
1. Identify all functions where a file is changed (move, copy, delete)
2. Add code to delete or change the mapping key as appropriate.

More advanced things to look at (in the future)
- [ ] Option to reset settings for all files
- [ ] Delete settings for file if it is not present (can test all saved settings at shutdown or something)

**Comment by harshad1** [comment]
Favourites are simply a list of paths which is parsed / updated whenever necessary.

Look at `AppSettings.java` for all of this

**Comment by Twilight-Shuxin** [comment]
Thanks so much for your help, I think I'm getting to understand it now.

**Comment by Twilight-Shuxin** [comment]
Hi, here's my understanding of this problem and I wonder if I had got it right: 

All favourite files are stored in a favourite file list maintained in AppSettings.java, and each file entry is identified by their absolute paths(which includes the file name itself). 
So to solve the issue, what needs to be done is to find all places where the absolute path of a file is to be changed and to update the favourite file list accordingly. 

Up to now I think to have these actions be taken would be enough,  if I had missed any considerations, please kindly inform me. Thanks so much!

**Comment by Twilight-Shuxin** [comment]
@harshad1 Hi, I have a question for this issue: By now I have implemented most of the parts for copying, moving and deleting the files. However I'm not so confident about `ShareUtil` and `DocumentFiles`. Do they point to files in external storage?

**Comment by Twilight-Shuxin** [comment]
By now I think I have implemented all changes and within tests there are no known bugs. I'll continue to test some more cases. I'm not sure is this the right place to reformat my code as required? (I right clicked on `app` folder and chose `reformat code` option) Should I just click run?
![3](https://user-images.githubusercontent.com/34962039/169506889-61b2aa92-6474-423f-b2c6-b62cfdc834c4.png)

**Comment by gsantner** [comment]
Yes it' this one! You can also check Optimize import. ... dont use Rearrange though, it mixes up things wuite often :D.

**Comment by gsantner** [comment]
Closing this by comment at the merge request, as won't fix.  
<https://github.com/gsantner/markor/pull/1709#issuecomment-1207203424>
