### ISSUE TITLE
Break line (two spaces at end of line) doesn't work inside a table

### ISSUE THREAD

**Issue by migoka** [gsantner/markor#1567]
## General information
* App version: 2.8.5
* Android version: 7.1.2
* Device: Nexus 7
* I understand that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

**Comment by gsantner** [comment]
Can you link some specification here (of i.e. gfm) where this is described?  
I am not aware of line breaks in tables.  
Want to know where "doesn't work" comes from.

**Comment by migoka** [comment]
Unfortunatly no! I'm not aware of any markdown specification that describes this in such detail. But e. g. emphasising works also without being mentioned in detail in the specification. So why not the same behaviour for line breaks? That's why I've used the wording "doesn't work".
By the way, I know of another markdown application that allows line breaks in a table.

**Comment by gsantner** [comment]
Hence I've asked. I'm not aware of such a thing. If your "another markdown application" supports it, nice, but it's not compatible with other software. As this is not something that is existing in the specification, and hence other don't have.

"Doesn't work" is not about wishing or liking things. Compatibility is important, and if your other application decides to introduce their own brew it's up to them. 

Suggestion: Don't use this, it won't work in most markdown supporting software.

**Comment by migoka** [comment]
OK, understood. What's about '\' instead of two spaces?

**Comment by migoka** [comment]
Just found out, <br> works!
