### ISSUE TITLE
ShareInto: Sharing into file strips too much newlines

### ISSUE THREAD

**Issue by sivaraam** [gsantner/markor#1569]
## General information
* App version: 2.8.5
* Android version: 11
* Device: OnePlus Nord
* I understand that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

### Description
Sharing into QuickNote appears to inadvertantly remove several new lines in the file. Essentially, the text in the document becomes hard to read post that.

Consider the app has content like:

```markdown
## Test section 2

Some content

### Test section 3

Some more content.
```

And shared text is: "Shared text"

After sharing content becomes

```markdown
## Test section 2Some content### Test section 3Some more content.

---
Shared text
```

**Comment by gsantner** [comment]
I can reproduce. please make an issue 

Am 22. Jänner 2022 09:39:57 MEZ schrieb Kaartic Sivaraam ***@***.***>:

**Comment by sivaraam** [comment]
> I can reproduce. please make an issue
 
 I just opened one 🤔

**Comment by Self-Perfection** [comment]
I just came here to describe exactly the same issue)

This issue happens not just with QuickNote but with any note. I've also reproduced with markdown and zim files.

Android 9, Device: Mi A1

**Comment by gsantner** [comment]
Yes it happens on any file. I saw this first a few days ago as well.
