### ISSUE TITLE
Permanent notification to start editor for a specific file

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#157]
#### General information

* **App version:** 0.3.0
* **System:** 7

#### Description

Allow to add a permanent notification for a document. This will make an non-cancelable notification, which starts the document in edit mode.

Add an action too for removing it (inside markor). Maybe a remove-all-settings-option is worth it too.

The priority should not bet set higher than notification-area only. e.g. it should not show up on lockscreen.

Mockup:

![grafik](https://user-images.githubusercontent.com/6735650/64547086-6bf05100-d31b-11e9-9625-96f6d64ddace.png)

**Comment by kai11** [comment]
I have 3-4 files which I edit often. 
But putting them to notification area seems overkill - its already crowded from sms, chat, vpn, profiles, etc.... - especially with new "thou shalt not run in backgound without notification".
Maybe put widget or shortcut to desktop instead?

**Comment by gsantner** [comment]
goal is only one. for 3-4 you csn have favourites or desktop shortcuts.

**Comment by Groxx** [comment]
Possible alternative, though I'm not sure if it'd be flexible enough for this: the notification-area Quick Settings have been around since 7.0: https://developer.android.com/about/versions/nougat/android-7.0#tile_api

**Comment by gsantner** [comment]
Thanks for hint.

I'm closing this as I feel like there are already more than enough options to get into Markor, and i.e. quicknote/todo.

**Comment by shockergit** [comment]
When will this feature come looks nice for todo tasks + a persistent notification

**Comment by shockergit** [comment]
It would have been nice it will open in viewer mode or give an option for what default mode you want to open for pinned notes.

**Comment by gsantner** [comment]
when there is somebody who is programming it
