### ISSUE TITLE
v2.8.5: Multiple Windows not working

### ISSUE THREAD

**Issue by srinetpro** [gsantner/markor#1570]
## General information
* App version: 2.8.5
* Android version: 11
* Device: Samsung Galaxy Tab S6 Lite
* I understand that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

### Description

Multiple Windows isn't working after I updated to 2.8.5 from GitHub
Before it was fine while using the 2.8.0 Playstore version.

<details><summary></summary>
Also when a note is open, switching from windowed mode (split screen view) to full screen crashes the app.
Again previously was working fine. 
</details>

**Comment by gsantner** [comment]
> Also when a note is open, switching from windowed mode (split screen view) to full screen crashes the app.
Again previously was working fine. 

--> duplicate #1565

**Comment by srinetpro** [comment]
> > Also when a note is open, switching from windowed mode (split screen view) to full screen crashes the app.
> > Again previously was working fine.
> 
> --> duplicate #1565

Hey, good to know you've fixed the 2nd issue.

**Comment by harshad1** [comment]
Hmm. Looking into this.
