### ISSUE TITLE
Line ends garbled when sharing URL into Markdown

### ISSUE THREAD

**Issue by tom65536** [gsantner/markor#1573]
## General information
* App version: v2.8.5 (129)
* Android version: 9.1.0.194 (EMUI 9.1.0)
* Device: Huawei Honor BND-L21
* I understand that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

#### Precondition
Existing Markdown file. So far I could only reproduce the behavior in presence of a table.

``` md
# Test
## Sub
Some text

Table | Table
----|----
First |

```

#### Trigger
Share an URL from Firefox to Markor, which should append the link to the end of the file.

#### Result
``` md
# Test
## Sub
Some textTable | Table
----|----
First |

----
 [GitHub](https://github.com/ )
```

#### Expected

``` md
# Test
## Sub
Some text

Table | Table
----|----
First |

----
 [GitHub](https://github.com/ )
```

**Comment by gsantner** [comment]
Please search/browse issues before creating.

**Comment by tom65536** [comment]
Sorry, I only checked the open issues.
