### ISSUE TITLE
Difficulty with Tables

### ISSUE THREAD

**Issue by km53** [gsantner/markor#1574]
## General information
* App version: 2.8.5
* Android version:  Android 10 (as I'm on Oxygen OS 10)
* Device: OnePlus 5
* I understand that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

### Description
Firstly, thank-you for the app, it is really useful and much better than others I have seen.

I use Ghostwriter (1.8.0) on my Windows laptop with files on Onedrive which are syched with files locallatly on my phone for which I use Markor (2.8.5).

I can see tables created in Markor in Ghostwriter without any issues.
To save time if I'm Ghostwriter I copy a table previously created using Markor and put it to a new md note in Ghoswriter and add new records as needed.
But when I open this up later in Markod it does not look like a table, it is just the headings and rows without any formatting being applied.
I'd like to use tables more as they re a useful way of keeping track of some information

Questions:

Why does this happen?
Does Markor depend on tables and rows created using its menu item rather than externally?

**Comment by gsantner** [comment]
Read how you need to write/structure tables in markdown here <https://github.github.com/gfm/#tables-extension->. I can't tell you what other apps use or do.
