### ISSUE TITLE
[feature request] file listing with data from within the respective file

### ISSUE THREAD

**Issue by w-markus** [gsantner/markor#1585]
## General information
* App version: as of today via F-Droid
* Android version: 7.0

### Description

Dear all,

I'd like to ask for an viewing option for the file listing. I am using Zettlr on the PC, where it is possible to list the files in the form of 3 lines

<first h1-Header in the document, if existing, else file name> <last change>
<tags, only one line, cutoff if there are to many>
< real file name> < number of words>

at least the display of the header would be very helpful. According to the Zettelkasten "rules" I am storing the files using the "Zettel"-ID as filename, which in the present folder view of Markor looks rather cryptic.

Thanks a lot in advance
Markus

**Comment by gsantner** [comment]
Please use Discussions for requests, not the issues. Thanks!

And no, don't plan to implement this. 

This might be helpful: If you are interested in finding some content in some file you can use search.

**Comment by gsantner** [comment]
Please use Discussions for requests, not the issues.

No wont wont add any content of file to filebrowser. Though you can manually format the description line by metadata like file change time and file size.

If you are interested in contents, use file search. It supports searching in contents.  
 OR..name your files properly by what you want them to be find for, then you can always use any filebrowser (interoptable).  
If your file is about holiday planning, have holiday planning in the filename. Thats it.

**Comment by gsantner** [comment]
thx for moving to discussing :-)
