### ISSUE TITLE
Auto update of numbered lists at Plaintext

### ISSUE THREAD

**Issue by tmancini85** [gsantner/markor#1592]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a question or feature request.
- [X] The issue is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=) or [discussions](https://github.com/gsantner/markor/discussions?discussions_q=). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.

### Description

First of all thanks for this beautiful app. I searched between issues and discussions and this doesn't seem to be reported, but if missed something, my apologies.

When you edit a simple text file, pressing the numbered list button adds `1.` to the beginning of the line. If you start a new line, `2.` is not added, and if you press again the numbered list button it adds another `1.`. In Markdown and Zim Wiki files it behaves as expected.

Maybe it is related to https://github.com/gsantner/markor/issues/247#issuecomment-435178009.

### Steps to reproduce

1. Edit a simple text file.
2. Press the numbered list button.
3. Start a new line.

### Information

Android version: 9
Device: Fairphone 2

### Installation method

F-Droid

**Comment by gsantner** [comment]
Is your file plaintext (as in selection), or i.e. markdown/zim?

If it's plaintext, "not working" is kind of wrong. It's not supposed to work, there is no special logic, syntax or structure for pure plaintext.

**Comment by tmancini85** [comment]
Thanks for the fast answer.

Yes, I meant plain text (I thought to edit title and my comment as soon as I sent them, but I wanted to avoid extra noise).

So, if it is intended, this issue can actually be an enhancement (tell me if I have to move to Discussions); also because, as a workaround, the Ordered list button can be disabled in _Settings->Plain Text format_.

**Comment by gsantner** [comment]
@fgtham @harshad1 @fredericjacob thought on enabling TextAutoFormat for normal plaintext?

**Comment by fgtham** [comment]
One could also just use File-Settings / Format / Markdown.

But it does raise a point. Currently, it's inconsistent: it's not intended to work, but the presence of action buttons implies that it should be working.

**Comment by gsantner** [comment]
I suggest to enable auto numbering for all file types

**Comment by harshad1** [comment]
It is important that we don't also enable automatic _update_ of numbering. Right now, the only way to get fine control over numbering is to switch to plain text mode.

Feb. 15, 2022 11:04:29 Gregor Santner ***@***.***>:

**Comment by gsantner** [comment]
I think about decreasing the complexity - to drop the the 3 special cases of 

* `todo.txt autoformat on/off in global settings`
* `plaintext no autoformat`
*  Zim + Markdown generally enabled
* .... and just have a per-file setting to enable/disable auto-format (default on)

![markor-autoformat drawio](https://user-images.githubusercontent.com/6735650/154156184-1f1dc0d1-6729-490a-bc7e-3d806a7e6794.png)

thoughts?

**Comment by harshad1** [comment]
> ... and just have a per-file setting to enable/disable auto-format (default on)

I agree

**Comment by harshad1** [comment]
@gsantner I can work on this
