### ISSUE TITLE
Shortcut bar missing some characters and buttons are too small

### ISSUE THREAD

**Issue by sjmduncan** [gsantner/markor#16]
#### General information

* **Device:**  Moto G 4G/Zenfone Max
* **Android Version:**  Both Android 7.1 (LineageOS 14.1)
* **App version:** Both v0.1.2

#### Steps to reproduce

1. Make sure 'Show Markdown Shortcuts Bar' is enabled in settings.
2. Open editor

#### Expected result

Access to characters which are buried on the secondary symbols keyboard. Most obvious missing one is \` but  \~ and \+ are also missing.

The buttons also don't expand vertically which makes it frustrating to use them even on a larger device.

**Comment by gsantner** [comment]
I dont know if its good to even keep it this way. Or to use WYIWYG symbols (ala bold icon which does `**text**`) instead

**Comment by gsantner** [comment]
![screenshot_20170919-061322](https://user-images.githubusercontent.com/6735650/30575545-de5735e4-9d01-11e7-852a-e5dda1950155.png)

**Comment by sjmduncan** [comment]
+1 for icons

**Comment by gsantner** [comment]
while we are at design: Whats better, the dark black, or little lighter black used in settings?

**Comment by gsantner** [comment]
Can you tell me if the size is better now? At both of my devices it worked perfectly before too, I dont know how it is visualized on yours

**Comment by sjmduncan** [comment]
Looks good.  Thanks!

Before: top-aligned and buttons are only text line-height. Touching below the red line does nothing.

![screenshot_20170920-081541](https://user-images.githubusercontent.com/24377181/30613720-3b93e17c-9ddd-11e7-9287-98a4308c0fae.png)


After: Full height buttons which are also wider now - much easier!

![screenshot_20170920-081400](https://user-images.githubusercontent.com/24377181/30613547-9194bade-9ddc-11e7-8d44-94007c10fdbf.png)

**Comment by gsantner** [comment]
k. should it maybe be a little less wide, so more is visible / in range?
