### ISSUE TITLE
Document/Folder information

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#160]
#### General information

* **App version:** 0.3.0
* **System:** 7.0.1

#### Description

Implement a dialog which summarizes a document/file. Should be available from fs-dialog and editor.

* Name, Location
* Filesize
* Word, Character, Line count
* Guessed document type or mime type
* Last modified
* ..list can be extended by more, just what comed to mined during creating issue. Other ideas welcome too of course 😃 

Heres an example (from Amaze FM):

<img width="60%" height="60%" src="https://user-images.githubusercontent.com/6735650/35480819-0345f346-0417-11e8-86d0-ec8f2f47d933.png">

**Comment by gsantner** [comment]
I had two locations for triggering in mind
* from the Notebook-Filesystem selection menu (where currently move,rename,delete exists)
* from editor, top-toolbar, overflow menu (when a document is loaded)

**Comment by gsantner** [comment]
you can try to sum up some informations, above are already some suggestions, maybe you find some more that is maybe interesting.

E.g. amount of lines

**Comment by sivaraam** [comment]
Hi, I just faced the bug of app crashing when trying to see 'Info' on folders. It would be nice if the app handles this gracefully until the info for folders is implemented.

**Comment by gsantner** [comment]
@sivaraam this is resovled

for anybody: improvments welcome, also for folders. pr welcome
