### ISSUE TITLE
line breaks are removed when past external content

### ISSUE THREAD

**Issue by aisbergde** [gsantner/markor#1614]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a question or feature request.
- [X] The issue is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=) or [discussions](https://github.com/gsantner/markor/discussions?discussions_q=). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.

### Description

normally I can copy external content and past into Markor and line breaks are keeped. But there are some web pages, which I can't use as source to copy content into Markor. But I can use other editors to past the content including line breaks.

### Steps to reproduce

1. open https://plantuml.com/activity-diagram-beta
2. copy any code example, for example the first one
3. past into Markor
4. line breaks are removed
5. use another editor, some of them will keep line breaks
  - code editor
  - acode
6. some other editors will also lost line breaks, 
for example this editor here for GitHub issues will not keep line breaks, but it will add some additional code around the inserted content

```
  | @startuml :Hello world; :This is defined on several **lines**; @enduml
-- | --
```

### Information

Android version: 11
Device: Poco X3 Pro
App Version: 2.8.6 (130)

### Source

F-Droid

### Format / File type

Plaintext

### Additional info / Log

```shell
-
```

**Comment by harshad1** [comment]
FWIW, this works fine for me the text inserts with the correct line breaks... Could you try a different browser, maybe?

Both the copy button and opening the editor and select all -> copy worked

I did have to use desktop mode on my phone's browser (bromite) though.

**Comment by gsantner** [comment]
I can reproduce it (currently), could not previously.  
Could also notice it at K9-Mail when writing the same text in email body for example.

**Comment by gsantner** [comment]
@aisbergde 

have you not noticed the "Paste as plain text" option, or do you not have it? It does exactly that. The code copied from the mentioned website is copied as richtext, and this is making up for the newlines getting lost.

![screenshot-2022-06-05__15-51-43](https://user-images.githubusercontent.com/6735650/172053981-7b6c227b-33a3-4015-abdd-6b30c43341be.png)

What I changed is, remapping the Paste just to "Paste as Plaintext".

**Comment by aisbergde** [comment]
I don't have this option, which, you have in your Screenshot. Maybe because I use MIUI which has some strange missing features regarding copy and paste.
![Screenshot_2022-06-05-18-14-28-278_net gsantner markor](https://user-images.githubusercontent.com/9020187/172060156-63299ee1-b117-4e53-80a9-65b96236b485.jpg)

But I use swift keyboard, and it has a way to insert the content of the clipboard. As a work around this works.

**Comment by gsantner** [comment]
anyway, with my change any paste will use the plaintext one. this functionality is available from Android Marshmallow onwards.
