### ISSUE TITLE
Plugin system

### ISSUE THREAD

**Issue by contrapunctus-1** [gsantner/markor#163]
Markor seems to steadily be gaining features. It's good to see it grow - especially as it remains the **only** freedom-respecting mobile text editor which stores data in plain text files by default (no exporting needed), which permits syncing (with Syncthing, in my case) and editing on other platforms by any other text editor, e.g. Emacs. However, some recent features (e.g. the todo list, for which some ten other applications of varying simplicity/feature-richness already exist on F-Droid alone), along with the proposed features in open issues cause concerns over feature creep.

Perhaps a plugin system could be worked out, making for easier maintenance (?) and a customizable user experience? (i.e. users would only install the plugins they want) Older features could be moved into plugins, too, giving users exactly the editor they want - no more, and (unlike super-minimalistic programs) no less.

**Comment by gsantner** [comment]
It's an option, but I think this can mean a lot of work. I don't know yet how to feel about this, as I don't want to bloat Markor myself, be it in app, or as extension
