### ISSUE TITLE
Sorting tasks in To-Do

### ISSUE THREAD

**Issue by plegrand1** [gsantner/markor#1637]
Markor version v2.8.6(130)
Android 11
MIUI 12.5.1
XIAOMI MI 9

When creating a new task in To-Do, while sorting by "Description (ascending)" is activated, once the task is saved and when switching back to display mode the display order is not respected automatically.
In the edit mode, you have to select the "Description (ascending)" sort order again (which is already selected) to re-sort all the tasks.

Is this a bug?

If not, is it possible to make sure that the selected display order is systematically respected (at refresh for example)?

Thanks again for your great application Pascal

Translated with www.DeepL.com/Translator (free version)

**Comment by gsantner** [comment]
Do you mean

a. Edit mode text is not in sync with what you have in edit mode
b. or is your description about that, that new tasks are not automatically re-ordered?

**Comment by plegrand1** [comment]
Yes, I mean that new tasks are not automatically re-ordered?
Thanks

**Comment by gsantner** [comment]
The buttons on the bottom are to apply action on the text. The sorting is done on the textfile when you click, one time, not continously.

For a different, filtered/sorted view, click on the filename/title on the top left.
