### ISSUE TITLE
compatibility issue when calling method

### ISSUE THREAD

**Issue by PSDroid2022** [gsantner/markor#1640]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a question or feature request.
- [X] The issue is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=) or [discussions](https://github.com/gsantner/markor/discussions?discussions_q=). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.

### Description

Hi, nice day! We confirm a  compatibility issue which might threaten the robustness of your app and give a detailed suggestion for you.

In ''net.gsantner.opoc.format.plaintext.PlainTextStuff", app call the framework API "java.time.OffsetDateTime: java.time.OffsetDateTime now()" and "java.time.OffsetDateTime: java.time.ZoneOffset getOffset()" in "newHuuid" method as shown in following. But actually, those two APIs are added in API level 26 (https://developer.android.google.cn/reference/java/time/OffsetDateTime?hl=en#now()).

```java
 public static String newHuuid(String hostid4c) {
        final SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd-hhmm-ssSSS'%STRIP1BEFORE%'-'%UTCOFFSET%'-'%HOSTID%%RAND%'");
        String rnd8c = String.format("%08x", new Random().nextInt());
        hostid4c = ((hostid4c == null ? "" : hostid4c) + "0000").substring(0, 4).replaceAll("[^A-Fa-f0-9]", "0");
        String utcoffset4c = String.format("%tz", OffsetDateTime.now().getOffset()) + "0000";
        utcoffset4c = utcoffset4c.substring(1, 4) + (utcoffset4c.startsWith("-") ? "a" : "f");

        return sdf.format(new Date())
                .replace("%UTCOFFSET%", utcoffset4c)
                .replace("%HOSTID%", hostid4c)
                .replace("%RAND%", rnd8c)
                .replaceAll(".%STRIP1BEFORE%", "").toLowerCase();
    }
``` 
So when the app try to call this API on devices level 14~25,app will run with an unpredictable results. So we suggest you add an "if(SDK_INT > 25)", " @TargetApi(Build.VERSION_CODES.O)" or change your app miniSDK from 16 to 26 to fix this potential issue. 

By the way, "@TargetApi(Build.VERSION_CODES.O)" will be deleted by Android compiler when releasing APKs, so it seems like a not good way to solve those issues.

### Steps to reproduce

1. 
2. 
3. 

### Information

Android version: <26
Device: 
App Version: 2.8.6

### Source

F-Droid

### Format / File type

Markdown

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
> We confirm a compatibility issue

Who is "we"?

`newHuuid` method is unused and up to removal. What's the point of the issue? Dead and not called code can't make compatibility issues.
