### ISSUE TITLE
callback compatibility issue when initialing method

### ISSUE THREAD

**Issue by PSDroid2022** [gsantner/markor#1641]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a question or feature request.
- [X] The issue is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=) or [discussions](https://github.com/gsantner/markor/discussions?discussions_q=). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.

### Description

We confirm a callback compatibility issue which might threaten the robustness of your app and give a detailed suggestion for you.

In ''net.gsantner.markor.activity.DocumentActivity", you super the framework API "<android.app.Activity: void onRequestPermissionsResult(int,java.lang.String[],int[])> in "onRequestPermissionsResult" method as shown in following. But actually, this API is added in API level 23 (https://developer.android.google.cn/reference/android/app/Activity?hl=en#onRequestPermissionsResult(int,%20java.lang.String[],%20int[])).

```java
 public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);
        new PermissionChecker(this).checkPermissionResult(requestCode, permissions, grantResults);
    }
``` 
So when the app try to initial related functions on devices SDK version 16 to 22, your app will run with an unpredictable results. So we suggest you add an "if(SDK_INT>22)", " @TargetApi(Build.VERSION_CODES.M)" or change your app miniSDK from 16 to 23 to fix this potential issue. 
By the way, "@TargetApi(Build.VERSION_CODES.M)" will be deleted by Android compiler when releasing APKs, so it seems like a not good way to solve those issues.

### Steps to reproduce

1. 
2. 
3. 

### Information

Android version: <23
Device: 
App Version: 2.8.6

### Source

F-Droid

### Format / File type

Markdown

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
The method is called by android internally (or appcompat) and is properly checked, not called by the project code. So the projects inherited method is called in safe way and thus also the super call there.

Is this some automatic report ("bot") with some faulty analysis?
