### ISSUE TITLE
the problem that developing in android studio

### ISSUE THREAD

**Issue by zhangliyuSustech** [gsantner/markor#1642]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a question or feature request.
- [X] The issue is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=) or [discussions](https://github.com/gsantner/markor/discussions?discussions_q=). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.

### Description

In first init in android studio, I can't build the project and the IDE returns that 
```
Caused by: org.gradle.internal.resource.transport.http.HttpRequestException: Could not GET 'https://maven.google.com/com/github/AppIntro/AppIntro/4.2.3/AppIntro-4.2.3.pom'.
```

### Steps to reproduce

1. just use the newest android studio
2. 
3. 

### Information

Android version: Android API 32
Device: Windows 11
App Version: Android Studio 2021.1.1

### Source

GitHub Releases

### Format / File type

No

### Additional info / Log

```shell
-
```

**Comment by zhangliyuSustech** [comment]
this can be solve vy lower the version of AppIntro

**Comment by gsantner** [comment]
![grafik](https://user-images.githubusercontent.com/6735650/159333941-57282506-69ec-4313-95f5-7729c8c8ba80.png)

please search issues before positing. you even checked it that you searched. duplicate on the first page.
