### ISSUE TITLE
Bright and Auto Themes not readable

### ISSUE THREAD

**Issue by Mithgarthsormr** [gsantner/markor#1645]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a question or feature request.
- [X] The issue is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=) or [discussions](https://github.com/gsantner/markor/discussions?discussions_q=). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.

### Description

Yesterday the app suddenly started to have dark color and dark background-color on bright or automatic theme.

The only readable themes at the moment are dark and black.

![Screenshot_20220319-145015_Markor](https://user-images.githubusercontent.com/60277471/159123876-f4e1a526-bfcc-4f23-ada6-e5b81101b5a8.png)

I've already tried to kill the app, to switch between all themes and to restart my phone.

### Steps to reproduce

1. Open Markor
2. Change to Bright or Auto Theme
3. Open a document
4. The document will have a dark background and the text-color will be the same.

### Information

Android version: 11 Build: 18.1-20220217-NIGHTLY-beyond0lte
Device: Samsung Galaxy S10e
App Version: 2.6.8

### Source

F-Droid

### Format / File type

Markdown

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
Check the "Other   -> Basic color scheme" colors. The main foreground and background color are user configurable.
