### ISSUE TITLE
file list in widget does not autorefresh

### ISSUE THREAD

**Issue by pbienst** [gsantner/markor#1661]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a question or feature request.
- [X] The issue is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=) or [discussions](https://github.com/gsantner/markor/discussions?discussions_q=). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.

### Description

When you add a file to a directory that is displayed in Markor's widget (e.g. by Syncthing), the file list is not automatically updated.  It only updates when you open Markor and navigate to that directory. It would be good if the widget would autoupdate, or if you could 'pull down from the top' to force a refresh.

### Steps to reproduce

See above.

### Information

Android version: 11
Device:  Galaxy A40
App Version: 2.8.0

### Source

Google Play

### Format / File type

No

### Additional info / Log

```shell
-
```

**Comment by harshad1** [comment]
I have a PR which addresses several widget related issues at the very moment. However, as far as I can tell, there is no way to implement pull-down to refresh. Instead, what I have added is updating all widgets whenever markor opens and setting the refresh time to the minimum possible (30 minutes). So you will be able to refresh the widget by tapping the title.

Also note that the google play version is kinda depreciated. You will have to get markor from F-Droid or here going forward.
