### ISSUE TITLE
Saved QuickNote changes disappear sometimes

### ISSUE THREAD

**Issue by MaxGyver83** [gsantner/markor#1671]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a question or feature request.
- [X] The issue is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=) or [discussions](https://github.com/gsantner/markor/discussions?discussions_q=). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.

### Description

I usually use only the QuickNote file. Since some changes to that files got lost, I always press the "save" icon after updating this file. But it still happens that when I return to Markor, my last edit is gone. This is similar to issue #1537 but the difference is that I actively save my changes.

### Steps to reproduce

1. Open QuickNote file in Markor
2. Edit text
3. Save
4. Go to home screen and use another app
5. Return to QuickNote in Markor: Sometimes the last edit is lost.

### Information

Android version: 11 (Oxygen  OS V11.3)
Device: OnePlus Nord 2 5G
App Version: v2.8.6 (130)

### Source

F-Droid

### Format / File type

No

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
try a apk from the GitHub Actions tab and check if it's better

**Comment by MaxGyver83** [comment]
OK, I just installed the latest master build from GitHub Actions (commit 2102dc6). I'll need to test it for some days because this issue did occur only sometimes.

**Comment by MaxGyver83** [comment]
The new version worked fine for some days. But yesterday it happened again. I added some text and when I opened the app again (about 2.5 hours later), the last change was gone.

Is there any log file I could upload here?

**Comment by gsantner** [comment]
There is no log I can think about you could add. But also I couldn't reproduce the issue at any time and I use Markor every day / hour.

Sure that this is not some kind of synchronization issue like Syncthing alike overwriting the file after your edit?

**Comment by MaxGyver83** [comment]
I only use Internxt but it doesn't backup the `QuickNote.md`.
Maybe it's just a problem with OnePlus/Oxygen OS!?

**Comment by harshad1** [comment]
Is the file on an SD card or something?

**Comment by MaxGyver83** [comment]
No. (This device doesn't have an SD card slot.)

**Comment by harshad1** [comment]
Next time this happens, could you check the modification time on the file? There are 2 possibilities - the save itself failed and the file should show an earlier modification time, or the file was overwritten and should show a later modification time

**Comment by MaxGyver83** [comment]
OK, I'll check it!

**Comment by MaxGyver83** [comment]
It happened again and this time I checked the file modification date (in the files tab) before opening the QuickNotes: It showed the current time!

It looks like the QuickNotes were rolled back in the moment, I opened the app.

**Comment by MaxGyver83** [comment]
I open the app using the Markor/Mordor icon. Then, I'm in the files tab and there I tap on the `QuickNote.md` file (not the QuickNote tab with the flash icon).

![Screenshot_2022-05-09-14-12-17-32_4b8860a85df4b42fa44460a7d0d51ee4__01.jpg](https://user-images.githubusercontent.com/13970628/167454657-d673a897-9318-4162-a6bf-25f5addbcdbc.jpg)

**Comment by harshad1** [comment]
Thanks. One possibility is that the text in the tab is being written to disk when you quit, overwriting the text written from the document. Will  investigate

May 9, 2022 09:26:12 Max Schillinger ***@***.***>:

**Comment by pbienst** [comment]
BTW, I have observed exactly the same behaviour...

**Comment by harshad1** [comment]
After more investigation, another cause for this may be the save process dying / being killed when writing the file. So only part of the file gets written.

No idea how one would address this without some sort of temp file scheme (which I think we want to avoid)

**Comment by harshad1** [comment]
@pbienst @MaxGyver83 please post here if these issues persist with 3.10

**Comment by MaxGyver83** [comment]
With 2.10.0?

**Comment by gsantner** [comment]
2.10.0 yes

**Comment by gsantner** [comment]
Generally can't reproduce

**Comment by rasmithid12** [comment]
Sorry for the nature of my question, but I am fairly new to Github and have
not found an answer to my question. I, at the moment rely heavily on
android/chromeos for my work. How do I use Markor effectively with this
software combination, especially for gdrive and synching. Thank you

**Comment by gsantner** [comment]
@rasmithid12   
These resources can help you: <https://gsantner.net/blog/2020/04/04/markor-how-to-use-syncthing-for-sync.html>, <https://docs.syncthing.net/intro/index.html>.  
With syncthing you can setup any amount of devices by installing it on them, and then linking the devices by the device ID.

**Comment by aaronwi** [comment]
I also have this issue on an Oneplus Nord N10

I noticed the issue was much worse when I was using an external sd card. But it still happens and loses a day's worth of changes when it does.

**Comment by gsantner** [comment]
It is totally not recommended to put your main QuickNote or todo.txt (the ones on the startscreen) on the SD-Card. SD-Card based storage & Storage-Access-Framework is painful slow and it might happen that theres not enough time to finish saving when you close/swipe out the app.

Did you know, you can set todo.txt and QuickNote file locations independent to your Notebook/start directory? Highly recommended.

**Comment by aaronwi** [comment]
> It is totally not recommended to put your main QuickNote or todo.txt (the ones on the startscreen) on the SD-Card. SD-Card based storage & Storage-Access-Framework is painful slow and it might happen that theres not enough time to finish saving when you close/swipe out the app. Also note that there is a button for manually saving, you can use that for cases you must make sure it's saved. Generally said I use Markor since years and never run into such an issue smiley .
> 
> Did you know, you can set todo.txt and QuickNote file locations independent to your Notebook/start directory? Highly recommended.

this is the odd thing, I always manually save to internal, yet even last night, it erased an entire day's worth of changes

**Comment by gsantner** [comment]
Sounds mysterious. Markor does not keep any old backups or caches of old versions. Once **really** saved/overwritten, a old version won't come back from Markor. By highest we keep the crc32 hash around. Sure it't not something from some sync software?

Also please update to the latest Markor v2.10.2 ([138](https://github.com/gsantner/markor/releases/tag/v2.10.2)), it has some SD Card improvements as well.

**Comment by gsantner** [comment]
Everything is possible. But I think it's rather some minor hard to find issue at Markor.

**Comment by aaronwi** [comment]
I still find this issue to happen randomly on a pixel device with internal storage, no syncing software. Much less often, but still does happen
