### ISSUE TITLE
Slow editing on large files

### ISSUE THREAD

**Issue by Grunthos** [gsantner/markor#169]
#### General information

* **App version:**
0.2.3
 
* **System:** 

7.1.1 on Zenfone Zoom 3

#### Description
When editing a large document, typing becomes slow. I saw

https://github.com/gsantner/markor/issues/90

which and changed the time from 110ms to 1000ms, which improved the speed, but it is periodically very slow to type (I assume it's reformatting doc if I am slow to type, then resuming typing becomes a problem.

You might be better off with a 'view mode' and an 'edit mode'; I don't need active WYSIWYG, but it's nice to be able to see the formatting when I'm done. Or maybe just a toggle.

**Comment by gsantner** [comment]
update to 0.3.0 / wait for it if you cannot update. it has some improvements.

view mode is available, just change document type to Plaintext (toolbar in editor)

**Comment by gsantner** [comment]
apk is on github and google play

**Comment by gsantner** [comment]
@ all Auto formatter (that does add e.g. bullet when pressing enter in list) is now enabled indp. to highlighter. This means if you want to get something faster, you can disable highlighter right now, while still getting the format-specfic benefits inside the editor input field.
