### ISSUE TITLE
When renaming using lowercase form of the existing note name, the existing file will be overwritten

### ISSUE THREAD

**Issue by sjl872964789** [gsantner/markor#1695]
# IMPORTANT
* App version: 2.8.6
* Android version/rom: Hydrogen OS
* Device: OnePlus 8T
* I accept that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

## Explain the Problem
When renaming using lowercase form of the existing note name, the existing file will be overwritten

## Steps to Reproduce
Explain what you did to encounter the issue
1. Create a new note named "Meeting" and record some notes in it
2. Create a new note named "Date" and record some notes in it
3. Long press "Meeting"
4. Click "Rename"
5. Enter "date"
6. Click "OK"
7. The app does not prompt "file already exists", it directly overwrites the original "Date" and its contents

## Expected behavior
There should be both "date" and "Date" notes at the same time, or at least there should be a prompt before overwriting the note

## Video
https://user-images.githubusercontent.com/15941953/166638859-ac56b0f8-5df7-4985-9cf3-027bbfd61e6c.mp4

**Comment by gsantner** [comment]
Android filesystems filenames are case insensitive.

**Comment by Twilight-Shuxin** [comment]
Hi, I'm wondering if it would be good to add a warning before overwriting same case-insensitive name files(as same as the files with the exact name). If it is desired, I would be glad to try to add it and make a pull request.
