### ISSUE TITLE
 crash and exit after rotating the screen twice during searching

### ISSUE THREAD

**Issue by jyjsunny** [gsantner/markor#1698]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a question or feature request.
- [X] The issue is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=) or [discussions](https://github.com/gsantner/markor/discussions?discussions_q=). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.

### Description

app crash and exit after rotating the screen twice during searching

There is a video sample:

https://user-images.githubusercontent.com/92309998/167803393-233f1d47-6009-444c-bee4-d6038e137600.mov

### Steps to reproduce

1. Click to search 
2. Input a word
3. Rotate the phone once counterclockwise
4. Rotate the phone once clockwise
5. Click Enter
6. The app crashes and quits

### Information

Android version: Android 8
Device: Google Pixel 4
App Version: 2.8.6

### Source

Google Play

### Format / File type

No

### Additional info / Log

```shell
-
```

**Comment by harshad1** [comment]
Hmmm. The dialog ought to just dismiss on rotate. 

Also: You're running Android 8 on a pixel 4?

**Comment by jyjsunny** [comment]
> Hmmm. The dialog ought to just dismiss on rotate.
> 
> Also: You're running Android 8 on a pixel 4? (Or is this just the emulator?)

hi, it's just emulator(Android 8, pixel 4).

The dialog box did dissolve while rotating, but when rotating back, it reappeared and crashed due to the subsequent operation.

**Comment by gsantner** [comment]
The dialog is dismissed on rotation in current release (2.9.0). So this is obsolete.
