### ISSUE TITLE
 crash and exit after rotating the screen twice during editing

### ISSUE THREAD

**Issue by jyjsunny** [gsantner/markor#1699]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a question or feature request.
- [X] The issue is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=) or [discussions](https://github.com/gsantner/markor/discussions?discussions_q=). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.

### Description

 crash and exit after rotating the screen twice during editing

There is a video:

https://user-images.githubusercontent.com/92309998/167807033-6a7ccb83-fa0b-4c57-a748-8265528ca5e2.mov

### Steps to reproduce

1. click to choose open a file with markor
2. Rotate the phone once counterclockwise
3. Rotate the phone once clockwise
4. Click to select Add Attachment
5. click ok
6. crash and exit

### Information

Android version: Android 8
Device: Google Pixel 4
App Version: 2.8.6

### Source

Google Play

### Format / File type

No

### Additional info / Log

```shell
-
```

**Comment by jyjsunny** [comment]
hi, I can reproduce this with https://github.com/gsantner/markor/suites/6424820593/artifacts/234778069.
There still seems to be the same problem:


https://user-images.githubusercontent.com/92309998/168003370-0d698a3f-3608-4bcd-a351-cc7eafed91a3.mov

**Comment by jyjsunny** [comment]
> Could you try to reproduce this with https://github.com/gsantner/markor/suites/6424820593/artifacts/234778069
> 
> I think it may be fixed already

Hello, I used the new version you provided and the above bug can still be reproduced, for details you can check the new video I posted a few days ago.

**Comment by gsantner** [comment]
the issue has not really todo anything with rotation. there just is a `OK` button which shouldn't be there. When you click on that button it crashes also without any rotation.
