### ISSUE TITLE
Mostly Freeze/Unresponsive When Opened File Size ±500 kb

### ISSUE THREAD

**Issue by Nightynal** [gsantner/markor#170]
#### General information
* **App version:** 0.3.0
* **System:**: Samsung Galaxy Grand 2, Android KitKat

#### Description
I have tried several text editors and decided to make Markor as a default editor and text viewer, but when I opened a file, TXT, size ± 500 kb, it is mostly freezing or unresponsive, and whenever I'm trying to type, the cursor always moves away to the top line. Only one app that able to open with this size, it's QuickE**t. Do you know what is happened?

**Comment by gsantner** [comment]
Can you fill out appversion? You can find it in More-About

**Comment by gsantner** [comment]
I think it would make sense for txt to not set markdown mode, this may help in your case

**Comment by Nightynal** [comment]
I have set it to text mode, and it still the same. Unfortunately, it seems a common problem in Android because I have just found that some people have the same problem open large with other text editors, even smaller one like 300 kb.

**Comment by gsantner** [comment]
Okay, I will try if I can find someting, but maybe there is something that is broken on your device, which the app cannot fix (as your comment suggests)

**Comment by Nightynal** [comment]
Thanks, here are some links I have found that have the same problem just like me.

https://www.google.co.id/search?q=android+freeze+when+open+large+text+files&oq=and&aqs=chrome.1.69i57j69i59j69i60l2j69i61l2.14120j1j7&sourceid=chrome&ie=UTF-8

**Comment by gsantner** [comment]
there were some performance improvements since your report. Please be sure to have latest version installed (v0.3.3) and deactive all additional highlighter in the settings
