### ISSUE TITLE
Cannot edit file from Dropbox

### ISSUE THREAD

**Issue by ThomasHeinrichSchmidt** [gsantner/markor#1705]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a question or feature request.
- [X] The issue is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=) or [discussions](https://github.com/gsantner/markor/discussions?discussions_q=). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.

### Description

When I  try to open a file from Dropbox I receive the following message
![Screenshot_20220518-104231](https://user-images.githubusercontent.com/8068047/168997433-832c5365-4b96-459a-8179-d365e225b11f.png)
This already happended on Android 10 and it continues to happen on 11. 
I've set the file in question to be available offline in Dropbox, but this does not help. It is also no longer possible to access local dropbox files as indicated in the Markor message (`Android/data/com.dropbox.android/files/u123456/scratch`), Android just does not allow it. 
I'm using other apps that are indeed able to open a file from dropbox in this way, e.g. [Totalcmd-Editor](https://play.google.com/store/apps/details?id=com.ghisler.android.TotalCommander)

### Steps to reproduce

1. Tap on some `File.md` in Dropbox
2. receive selection dialog, tap on Markor
3. look at error message (= screenshot above)

### Information

Android version: 11
Device:  Fairphone FP 3
App Version: **Markor** `net.gsantner.markor, v2.9.0 (132)`

### Source

GitHub Releases

### Format / File type

No

### Additional info / Log

```shell
-
```

**Comment by ThomasHeinrichSchmidt** [comment]
Yes, I've read https://github.com/gsantner/markor/discussions/1381 - but my main point was: "_I'm using other apps that are indeed able to open a file from dropbox in this way, e.g. [Totalcmd-Editor](https://play.google.com/store/apps/details?id=com.ghisler.android.TotalCommander)_".
I'm not able to access `Android/data/com.dropbox.android/files/u123456/scratch` in Android 11 any more and I doubt that it is possible to grant access to this folder. As I understand this is one of the new security features of 11. So I have not tried FolderSync.
I'm hoping that there is a way for Markor to also directly open a file from Dropbox like  [Totalcmd-Editor](https://play.google.com/store/apps/details?id=com.ghisler.android.TotalCommander) does.

**Comment by gsantner** [comment]
Still it holds. The issue still is the same. And the way to resolve it. And the the other options,like FolderSync.

**Comment by gsantner** [comment]
Still it holds. The core issue still is the same. And the way to develop on it and potentially resolve it. And the the other options,like FolderSync.
