### ISSUE TITLE
Toolbar in QuickNode and ToDo

### ISSUE THREAD

**Issue by kRkk** [gsantner/markor#172]
### General information
* **App version:** v3.0.0
* **System:** Android 7.1.2, Nokia 6

### Description
Steps to reproduce:
1. Select in the toolbar QuickNote or To-do menu.
1. Click the preview.
1. Return to the editor by clicking on the top toolbar 

**Expected result:** tollbar bar returns

**Comment by gsantner** [comment]
I don't know if I should tag this as a bug or feature. For me it's a feature 😉.  I want full fledged editing when clicking edit on Preview (whereever it comes from), thats what the option is for. 

For going back to Main-screen you have the android-back-button and the back-toolbar-option(left top). Both of them work correct and do what they are there for, going back.
