### ISSUE TITLE
[spam] a request for Croatian translation

### ISSUE THREAD

**Issue by kkzkk0423** [gsantner/markor#1730]
## Demand
- A feature request.
The system does not support Croatian translation. I hope the system support Croatian translation. Thanks.

**Comment by YG-yyds** [comment]
I think I can solve this problem and gives a simple translation.

**Comment by gsantner** [comment]
If you want to make dummy pull requests & issues, make your own repositories & or forks. There you can do whatever you want.  
Markor is not a dummy project for dummy PRs. If you really want to improve something, please do that and work on real things. Don't do such meaningless pull requests.  
Communicate that also to your other project team(s).

Thanks.

**Comment by kkzkk0423** [comment]
I'm sorry for bothering you and you don't have to worry about this. I am so sorry.

**Comment by gsantner** [comment]
As I said, do your own repositories and do whatever you want there.
