### ISSUE TITLE
Print document(s)

### ISSUE THREAD

**Issue by Symbian9** [gsantner/markor#178]
#### General information

* **App version:** 0.3.x, 0.4.x, 1.x.x
* **System:** 6.0

#### Description
Add option "Print document(s)" for print rendered documents directly from Markor.

#### Log

**Comment by gsantner** [comment]
This is already implemented for devices >= API 19 (Kitkat). The `Export as PDF` allows to print too.

**Comment by Symbian9** [comment]
I mean situation: have a smartphone & WiFi/Network printer.

How print documents from Markor directly on such printer?

**Comment by gsantner** [comment]
write text, open preview, do share -> PDF. There you get a print menu. For the rest you have to install a driver where I cant help you out.
