### ISSUE TITLE
Markor 2.10.2 can't write/edit SD Card files

### ISSUE THREAD

**Issue by chromer030** [gsantner/markor#1799]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a question or feature request.
- [X] The issue is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=) or [discussions](https://github.com/gsantner/markor/discussions?discussions_q=). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.

### Description

Markor 2.10.2 can't edit files on sdcard while permission is granted.
Save button doesn't work and all the changes will be discard by closing the app or leaving the note.
Version 2.10.1 was OK.

Markor can write and edit files in SD Card Appdata but not on specified folder in SD Card.
(I cleared the data and cache , uninstall the app and reinstall it but the issue persists.)

### Steps to reproduce

1. Specify a folder on SD Card for notebook
2. Try to edit a file.
3. Save button doesn't work.

### Information

Android version: 7.1.2 arm64
Device: Lenovo
App Version: 2.10.2

### Source

GitHub Releases

### Format / File type

Markdown

**Comment by gsantner** [comment]
....I extra asked before the update if sdcard work, and I got as response (https://github.com/gsantner/markor/issues/603) by  multiple users that it works. And it works on my device very well too :shrug: . So I don't know, not everybody can be happy.

**Comment by gsantner** [comment]
It would be very good when I explicitly ask for feedback on topics that it not gets in after release. Now we have it there and *somebody* needs to fix it it looks like....

**Comment by gsantner** [comment]
It would be very good when I explicitly ask for feedback on topics that it not gets in after release. Now we have it there and *somebody* needs to fix it it looks like....  
Just saying, SD Card is a frequently asked topic, but in the many years of Markor never somebody contributed something for SD Card support. Help is totally welcome. Android storage & SD cards is a every-year-changing topic that is very hard to make work across all Android versions.

**Comment by chromer030** [comment]
Using a folder in Internal Storage is OK on both android 7.1.2 and 10.
Both + and Saving buttons working.
(/storage/emulated/0)

**Comment by chromer030** [comment]
@gsantner 
another issue , there is not anymore any font size number in Font Size option under Edit mode settings while changing it , it's just change bar without number !

**Comment by gsantner** [comment]
Please put non-related discussion to the 2.10.2 release to collect issues there. You can remove the font size comment here then ---> https://github.com/gsantner/markor/discussions/1796

**Comment by gsantner** [comment]
Related: #1359 #1521 #603

**Comment by chromer030** [comment]
Tested the Mordor app and confirm that latest [commit](https://github.com/gsantner/markor/commit/80aa650fcca9b5f8b7cd28619c5f4f6a04ba7342) fixed the issue.
Tested on both 7.1.2 and 10.

**Comment by gsantner** [comment]
Thanks, good to hear and thanks for reporting.

**Comment by chromer030** [comment]
Thank you for fixing it fast.

**Comment by gsantner** [comment]
Usually it's not that easy. This one was some check not triggering with SAF 😄 .
