### ISSUE TITLE
”Special key" layout cut off in landscape orientation

### ISSUE THREAD

**Issue by PinkRay7** [gsantner/markor#1800]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a question or feature request.
- [X] The issue is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=) or [discussions](https://github.com/gsantner/markor/discussions?discussions_q=). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.

### Description

When I open "Special key" in landscape mode, I can't view all the options in the menu. Although the scroll bar shows I've reached the bottom, there are still some options that are not displayed.
Plus, when I switch to portrait mode, I can view all the options. But if I click one of the options,  nothing happens. I have to reopen the menu and click the option again.
This is a regression bug. On version 2.0.0, the menu can be displayed normally in landscape mode. But when switching to portrait mode, any of the options still cannot excute the expected behavior.

Video from 2.10.2:

https://user-images.githubusercontent.com/53887881/185377897-15d7e16e-b1a4-4e45-989d-4ec117d4bfd1.mp4

Video from 2.0.0:

https://user-images.githubusercontent.com/53887881/185377383-7f5821b7-51f9-488b-bad0-cbb1cacd840c.mp4

### Steps to reproduce

1. Open "Special key" in landscape mode.
2. Scroll down and find you can't scroll downwards to the last line..
3. Switch to portrait mode.
4. Click one option and see nothing happens.

### Information

Android version: 8.0
Device: Google Pixel 2
App Version: 2.10.2

### Source

GitHub Releases

### Format / File type

No

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
For version comparisons, a bet is i.e. 2.8.0. The 2.0.0 version is about 3 years behind us 😉 .
