### ISSUE TITLE
Syntax highlighting: Color underline for #rrggbbaa

### ISSUE THREAD

**Issue by KLaurence** [gsantner/markor#1802]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a question or feature request.
- [X] The issue is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=) or [discussions](https://github.com/gsantner/markor/discussions?discussions_q=). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.

### Description

When adding hexadecimal color-codes in [the eight-digit "red green blue alpha" `#rrggbbaa` format](https://en.m.wikipedia.org/wiki/RGBA_color_model) or [the three-digit `#rgb` format](https://www.quackit.com/css/color/values/css_hex_color_notation_3_digits.cfm), the underline either doesn't show up or shows the incorrect color. I've given an example for each in _Steps to reproduce_.

(While searching for existing issues, I also found [a comment](https://github.com/gsantner/markor/issues/144#issuecomment-592875991) mentioning three-digit color-codes. Since it's related to my issue about `#rrggbbaa` color-codes which isn't already reported, I've included it here.)

### Steps to reproduce

1. In the "Settings > Edit mode" menu, enable the "Underline Hex Color Codes" option.
2. Create a Markdown file.
3. Insert `#ffffff`. The color code is correctly underlined as white.
4. Insert `#ffffff80`. The color code is incorrectly underlined as yellow (`#ffff80`) but should be underlined as white at 50% opacity/alpha.
5. Insert `#fff`. No underline appears but it should be underlined as white.

### Information

Android version: 10
App version: 2.10.2

### Source

GitHub Releases

### Format / File type

No

**Comment by harshad1** [comment]
Is this a new bug? i.e. did it work correctly before? I am asking because I recently made some major highlighting changes and may have broken this if tit did work before.

**Comment by gsantner** [comment]
No it's just that only 6 chars are implemented. I consider 8 (with alpha) as well, but not the 3 digit one (like `#123`) - that can quickly lead to wrong things being highlighted (and it's performance penalty).

**Comment by KLaurence** [comment]
I see. I filed this as a bug under the assumption that the color-code was being detected incorrectly (e.g. `#ffffff80` seems to parse it as `#ffff80`, ignoring the first two `f`s).

**Comment by gsantner** [comment]
Yes no worries @harshad1 , this is not because of your highlighting PR 😉

**Comment by gsantner** [comment]
@KLaurence 

So the problem is not actually the detection, but that Android color parsing works with ARGB, not RGBA as opposed to your needs. 

See also:
* https://developer.android.com/reference/android/graphics/Color#parseColor(java.lang.String) 
* https://stackoverflow.com/questions/5248583/how-to-get-a-color-from-hexadecimal-color-string

So what I could do is manually shuffling around the color string so AA is moved to front. But generally don't know whether it's wanted and expected by most. To me at last I usually see/use alpha as last component, but that might be different at other users.

**Comment by KLaurence** [comment]
I personally think that the parsing should work with RGBA as it's the hex code format that works with styling Markdown text with CSS, so I agree with the ARGB-to-RGBA swap.
