### ISSUE TITLE
Sharing from a web page doesn't work anymore

### ISSUE THREAD

**Issue by blogdemoi** [gsantner/markor#1814]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a question or feature request.
- [X] The issue is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=) or [discussions](https://github.com/gsantner/markor/discussions?discussions_q=). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.

### Description

Hi,

The very useful option to share a web link to markor (in a markdown file with markdown syntax) isn't working anymore. When I share a web page link Markor crashes immediately. I am runing Android 12 / latest stable GrapheneOS. 

Thank you.

### Steps to reproduce

1. Share a web link to Markor
2. 
3. 

### Information

Android version: 12 / GrapheneOS
Device: Pixel 4a
App Version: v2.10.2(138)

### Source

F-Droid

### Format / File type

Markdown

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
Does it work on latest code version? You can download the debug version, Mordor, here <https://nightly.link/gsantner/markor/workflows/build-android-project/master>

**Comment by gsantner** [comment]
Thanks I can currently reproduce it too. Important to get fixed soon.

**Comment by blogdemoi** [comment]
It is a very useful feature :-)
