### ISSUE TITLE
Action Order crash.

### ISSUE THREAD

**Issue by chromer030** [gsantner/markor#1815]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question](https://github.com/gsantner/markor/issues/95) or [feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] Is the bug still present in the latest code version (git master)? Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. No worries Markor and Mordor appear as completely separate applications, you can install both side-by-side and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report - the change will be part of the next Markor update.

### Description

In Settings, by tapping `Action order` in all subsets : Markdown, todo.txt , Zim Wiki, Plain Text , The app will crash.

![Screenshot_20220823-123134](https://user-images.githubusercontent.com/13361552/186132001-fa0bb391-11ab-4c64-9b86-b56372a4274d.png)

### Steps to reproduce

1. Settings
2. Format--> Markdown
3. Tap Action order

### Information

Android version: 7.1.2 arm64
Device: Lenovo
App Version: 2.10.3

### Source

GitHub Releases

### Format / File type

Markdown

**Comment by gsantner** [comment]
Very likely by #1809
