### ISSUE TITLE
Integrate 'personal log' 

### ISSUE THREAD

**Issue by Raguenote** [gsantner/markor#1816]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug](https://github.com/gsantner/markor/issues/new/choose) or [question](https://github.com/gsantner/markor/issues/95).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] Is the wanted feature/enhancement present in the latest code version (git master)? Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. No worries Markor and Mordor appear as completely separate applications, you can install both side-by-side and Markor settings are not touched. If so, the change will be part of the next Markor update.

### Description

1. Feature personal log
2. As in https://gitlab.com/tiwa42/personal-log
3. But enriched by tagging- project- search- function 
4. Same hierarchy as todo or notes

### Information

Android version: 12
Device: samsung a21
App Version: 2.10.2

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-i like to write down ideas and scroll back from time to time to get into a creative mood.
-i think the feature would not be much of a slowdown

THANK YOU
```

**Comment by gsantner** [comment]
Hello, Markor not gets in your way here. The way you organize files is up to you.

* Whether or not have every diary entry in one file, or each day a own file
* Whether you add new entries at the top (current day at beginning) or add bottom (current day at the end of file)
* Whatever time format you use, for files and for headings - up to you.


I don't see the need here to implement something, Markor gives you all the possibilities to create a diary in the way you like it. I dont see the need to try create something more limited, when you already have all the possibilities.
