### ISSUE TITLE
v2.10.3: Widget + button not opens ShareInto but unnamed file

### ISSUE THREAD

**Issue by darhma** [gsantner/markor#1817]
# IMPORTANT
* App version: 2.10.2 (f-droid)
* Android version/rom: android 12/divestos 19.1 (a modified version of lineageos) and lineageos 19.1
* Device: OnePlus 7t
* I accept that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

## Explain the Problem
What problem did you encounter? What did you expect to happen?

When I try to create a new note from the widget by pressing the + key no window appears to enter the name and file type, but the new note is opened directly which can be edited but not saved, once closed the new note so created simply disappears.

The behavior I would expect when I try to create a new note from the widget would be that of note creation from the app: the pop-up window to select the file name, type, and template should appear. 

## Steps to Reproduce
Explain what you did to encounter the issue

Add the widget to the home screen and try to create (and then save) a new note by pressing the + button

## Log
<details>
<summary>Log</summary>

```
Paste log here
```
</details>

**Comment by gsantner** [comment]
this is usually part of the issue template:

> Is the wanted feature/enhancement present in the latest code version (git master)? Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. No worries Markor and Mordor appear as completely separate applications, you can install both side-by-side and Markor settings are not touched. If so, the change will be part of the next Markor update.


Try it please, and of course place a Mordor widget, not a Markor widget.

**Comment by darhma** [comment]
I have downloaded and installed Mordor (version 2.10.3-2252) as recommended but when I add the Mordor widget I keep having the same problem saving new notes.

**Comment by gsantner** [comment]
Ok I see, the `+` button is supposed to trigger showing ""Share-Into"", but opens a editor instead for some unknown file.

So... it's not expected that you directly jump into the texteditor this way :-D.
