### ISSUE TITLE
[feature request]: transparent widget background

### ISSUE THREAD

**Issue by darhma** [gsantner/markor#1818]
First of all thanks for the great app, lately I started to use in addition to the app (which I have been using for a long time) also the widget and besides some minor inconveniences (#1817) I find it very convenient, from the aesthetic point of view I would like if there was the possibility to set the background of the widget so that it is transparent. 

Not being a developer unfortunately I can't contribute any code and I don't know how complicated it could be to implement this feature, more of an idea I wanted to share because I think it could improve the look of the widget.

Thank you and keep up the good work

**Comment by gsantner** [comment]
I doubt you are going to be happy about transparent background. This way the text (filenames) may get unreadable due background sections of same color.

**Comment by darhma** [comment]
I generally use a black or otherwise dark background and with other widgets I don't have particular problems, perhaps an option could be added to set the transparency of the widget from fully transparent to fully opaque: some widgets I use that allow a similar thing are those of ToDo agenda (https://github.com/andstatus/todoagenda) and Geometric Weather (https://github.com/WangDaYeeeeee/GeometricWeather), also the widgets of SimpleMobileTools apps (https://github.com/SimpleMobileTools) allow to set the background transparency.

**Comment by gsantner** [comment]
Look, Markor already has countless settings options. Really many things are configurable to the finest detail.  
But: Not everything needs to be a option, especially not if its just for a very low amount of users. For all others it just gets into the way. What however is important is to have good defaults and that it works - which is the case (the bug is another issue, but thats not wanted)

And thats also why I don't consider this. Thanks for understanding.

**Comment by darhma** [comment]
Perhaps you could make sure that the widget colors are the same as those set in Settings > Other > Basic Color Scheme since there is already a way to select color and transparency. Anyway, I don't want to push it, as said, it was just an idea and if I hadn't opened the bug report I probably wouldn't have even made the feature request. Thank you in any case for the promptness of your replies and for the excellent app.
