### ISSUE TITLE
Format: org-mode (Highlighter, TextActions) 

### ISSUE THREAD

**Issue by fadavi** [gsantner/markor#182]
Thank you for your usable/free/geeky/amazing application!
Please add Org support to your application, too.

See: https://orgmode.org

**Comment by gsantner** [comment]
Forwarding conversation from IRC/Matrix which is the (my) same response to this.

TL;DR: I won't implement it by myself, but I developed features to allow Markor to easy switch between formats (and implement them indipendently).

![grafik](https://user-images.githubusercontent.com/6735650/34916031-21485d16-f931-11e7-939b-e6f2f472658f.png)
![grafik](https://user-images.githubusercontent.com/6735650/34916043-3e80a3ac-f931-11e7-8bfc-c32a183f36cd.png)

**Comment by gsantner** [comment]
#496  - @juacq97

#### General information

* **App version: 1.6.2 (47) Play Store** 
* **System: Android 4.4.4** 

#### Description
First of all, great app, it's the best markdown editor on Android by far. 
I wondering the posibilitty of add support for org-mode syntax. I have already read past entries about this format, and there were no plans to add it. That was more than a year ago, I do not know if you have changed your mind, at least I should ask hehe.

While Org-mode has many features, its markup syntax is quite simple and similar to markdown.
![captura-2019-02-03](https://user-images.githubusercontent.com/7623047/52185222-4bd33f00-27da-11e9-87ac-bc4dbdc2aaa1.png)


Will there be a way to reconsider supporting this format? It would be a killer feature that would appeal to all org-mode users that we do not have an application to write comfortably from the smartphone (there are some, but they are oriented to task lists, not to writing).

**Comment by uGeek** [comment]
Totally agree. It would be great to be able to write orgmode on Markor. In what way could we help?

**Comment by gsantner** [comment]
@uGeek 

Totally happy about help on this. If you can work on it, please go for it and I will give feedback.

**Comment by uGeek** [comment]
Would it be to adapt the syntax in a template like this?


https://github.com/gsantner/markor/blob/master/app/src/test/java/other/writeily/MarkdownHighlighterPatternTest.java

**Comment by gsantner** [comment]
yep, but you are likely more in the main/markor/format folder than the test case folder. ;)

**Comment by uGeek** [comment]
Perfect. I look at it and try to adapt
Do not program java 😅

**Comment by 809825706** [comment]
I think you should try another app named "orglzy", which is the best orgmode app on Android. And I think the best features of orgmode are foldable subtitle and reminder. the reminder feature seems impossible in a edit app (markor). And _orglzy_ is also opensource on github. If you are interested, you can try to migrate its code to markor.

**Comment by gsantner** [comment]
I'm closing this as orgmode is quite complex and I don't think that that support for it will be added for it any time soon. Btw format includes a full suite of syntax highlighter, textactions, converter and others.

However if somebody is (/starts) working on this I'm happy to give feedback, and merge when it's ready.

**Comment by gsantner** [comment]
Hey, have small news on this: Now you can open orgmode files with Markor. Just like recent Asciidoc addition, it gets loaded in Plaintext format, so you can edit the files with Markor. Note that no orgmode specific features or highlighting is there, and I don't plan to implement that on my own.

**Comment by uGeek** [comment]
It's great news !!!

I imagine it will come in the next update.
What would be the file to edit to highlight the syntax?

Thank you

**Comment by gsantner** [comment]
If theres somebody who develops it.

See the java files starting with todotxt or markdown. Its multiple obes.

**Comment by xerus2000** [comment]
I may look into that. I'd also like to have a feature to add an org-mode-compliant current datestamp whenever I create a top-level-heading, I'll see whether that is easily doable.

**Comment by xerus2000** [comment]
From the first little attempt I can see that there is still a lot of work to be done to properly modularize the formats. Markdown and org should share a lot of functionality, but as it is right now I have to copy and modify a lot.

**Comment by xerus2000** [comment]
You should look into loading the TextConverters, Highlighters and TextActions through a ServiceLoader rather than hardcoding them.

**Comment by lockywolf** [comment]
For the sake of completeness, Orgzly seems to have factored out its parsing engine into a separate library (not sure of its quality) https://github.com/orgzly/org-java . This may be handy if someone resumes work on this.

**Comment by xerus2000** [comment]
Hardly, since this app has rigid requirements within which the parsing needs to operate.

**Comment by gsantner** [comment]
Closing, so far nobody stepped up for adding support at Markor. If there is interest, start to work on it please and make a pull request. Thanks.
