### ISSUE TITLE
Zim: Problems with list indentation

### ISSUE THREAD

**Issue by roycoding** [gsantner/markor#1821]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question](https://github.com/gsantner/markor/issues/95) or [feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] Is the bug still present in the latest code version (git master)? Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. No worries Markor and Mordor appear as completely separate applications, you can install both side-by-side and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report - the change will be part of the next Markor update.

### Description

When creating a list in a Zim file, indenting seems to be working incorrectly.

Using the indent button from the toolbar correctly creates a sub-item in a list, but upon going to the next line (without using the indent button) the next list item is indented further than expected and is not rendered as valid Zim (it is rendered in the Zim application as a sub item, but with too many preceding spaces)

![Screenshot_20220826-141127](https://user-images.githubusercontent.com/747219/186976709-3f60efa5-22e2-4c94-8dca-601e925ec964.png)
![Screenshot_20220826-141144](https://user-images.githubusercontent.com/747219/186976712-35991b7f-a2ce-4746-aa94-937cae73a886.png)

This seems to affect all list types.

To work around this, I need to use the unindent button repeatedly until the sub-item is aligned with the previous sub-item.

### Steps to reproduce

1. Create a Zim document
2. Add a list item
3. Add another list item and his the indent button from the Markor toolbar
4. Hit Enter to start another list item

### Information

Android version: 12
Device: Google Pixel 4a
App Version: 2.10.2 (138)

### Source

F-Droid

### Format / File type

Zim

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
Markor's Zim implementation for lists works only till depth of 2, by 
also how Markdown works.

**Comment by roycoding** [comment]
Just to clarify, I'm only trying to indent to one level, but when hitting enter after a sub-item, Markor is indenting further than it should, creating an invalid indentation.

I want something like
- First item
- Second item
  - First sub item
  - Second sub item

But Markor is placing the second sub item many spaces over, instead of keeping it at the same indentation level.

**Comment by gsantner** [comment]
Yes that "hitting enter" thingy is what I mean with "AutoFormatter"

**Comment by harshad1** [comment]
I have a fix for this in #1834 .
