### ISSUE TITLE
Cannot create a file with an apostrophe in the name

### ISSUE THREAD

**Issue by Screwtapello** [gsantner/markor#1829]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question](https://github.com/gsantner/markor/issues/95) or [feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] Is the bug still present in the latest code version (git master)? Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. No worries Markor and Mordor appear as completely separate applications, you can install both side-by-side and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report - the change will be part of the next Markor update.

### Description

From the "Files" tab, if I try to create a new file containing an apostrophe, the filename field is cleared.

### Steps to reproduce

1. Start Markor, it defaults to the Files tab
2. Tap the big red "+" button in the lower right to open the "create new file" dialog
3. By default, the focus is in the "Name" field, which is empty and shows the placeholder text "my_note"
5. On the on-screen keyboard, type "abc", so the name field shows "abc"
6. On the on-screen keyboard, type an apostrophe `'`
    * I use the Dvorak layout, so I can press the dedicated apostrophe key <kbd>'</kbd> or long-press <kbd>x</kbd>

Expected behaviour: an apostrophe appears, so the Name field shows "abc'"

Actual behaviour: the Name field is cleared, and shows the placeholder text "my_note" instead. Backspace does not restore the previous contents

### Information

Android version: 10
Device: moto e7 power
App Version: 2.10.3

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
If I use the file manager app to rename a file so its name contains an apostrophe, Markor is fine with that - it can open such files, link to them, etc.

I tried to install the "Mordor" nightly build, but I was not able to attempt to reproduce the problem, since it crashes on startup after prompting for filesystem access permissions.
```

**Comment by Screwtapello** [comment]
It turns out I can reproduce the same behaviour with the default QWERTY layout too.

**Comment by gsantner** [comment]
Do you know how to make Android logs (logcat)? The development version, Mordor, doesnt crash here. And I really would like to know whats going on there. That is important to get fixed before next update. -- Note this is unrelated to the apostroph issue ---.

**Comment by Screwtapello** [comment]
I filed #1833 about the startup crash, including a logcat traceback.

**Comment by gsantner** [comment]
@Screwtapello   
I made changes on the filename input handling (so all different implementations operate on the same list of illegal characters) ... like NewFile dialog, Rename dialog, file creation.

Here is the definite new list of characters disallowed as of the next Markor update. The guard is active, meaning various code execution special characters/delimiters are disallowed.

```
        final String disallowedChars = "<|[\\\\?*:\"\n\r\t\0]/>" + (noRCEguard ? "" : "`$?%;=&#@");
```

Pleas also check the nightly.

**Comment by gsantner** [comment]
@Screwtapello   
I made changes on the filename input handling (so all different implementations operate on the same list of illegal characters) ... like NewFile dialog, Rename dialog, file creation.

Here is the definite new list of characters disallowed as of the next Markor update. The guard is active, meaning various code execution special characters/delimiters are disallowed.

```
        final String disallowedChars = "<|[\\\\?*:\"\n\r\t\0]/>" + (noRCEguard ? "" : "`$?%;=&#@");
```
While I generally advice against using any quotes in filenames, you at last can do `'` now.

Please also check the nightly.
