### ISSUE TITLE
Feature request: export/import all data

### ISSUE THREAD

**Issue by davidhedlund** [gsantner/markor#183]
It's not convenient to manually export every document with "Share". Can you please add an option to export and import all documents in Markor?

**Comment by gsantner** [comment]
All data is stored in your documents folder (documents/markor). You can move, copy, backup and anything else easily - there is really no need to export everything by hand ;-)

**Comment by davidhedlund** [comment]
> All data is stored in your documents folder (documents/markor).

Ok, great. I didn't find any documentation about this. Do you think it should be added to https://github.com/gsantner/markor ?

**Comment by gsantner** [comment]
It is `~` the 4th line in the apps descrption. On GitHub Readme, gplay and fdroid

**Comment by davidhedlund** [comment]
Thanks.
