### ISSUE TITLE
Continuous rotation adds date to to.do list

### ISSUE THREAD

**Issue by taner7** [gsantner/markor#1837]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question](https://github.com/gsantner/markor/issues/95) or [feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] Is the bug still present in the latest code version (git master)? Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. No worries Markor and Mordor appear as completely separate applications, you can install both side-by-side and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report - the change will be part of the next Markor update.

### Description

Using rotation button on the right bottom continuously adds date

### Steps to reproduce

1. Open a to do list, try to add a note
2. While in editing mode press rotation button at the right bottom of the screen, when it goes to landscape mode again press, and repeat these steps
3. See always the current date added one after another 

### Information

Android version: 
Device: 
App Version: 

### Source

Google Play

### Format / File type

todo.txt

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
Check the APK from here 
https://github.com/gsantner/markor/actions/runs/2986625519
