### ISSUE TITLE
Widget: Remove filter, show all files

### ISSUE THREAD

**Issue by filisko** [gsantner/markor#1840]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] Is the wanted feature/enhancement present in the latest code version (git master)? Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. No worries Markor and Mordor appear as completely separate applications, you can install both side-by-side and Markor settings are not touched. If so, the change will be part of the next Markor update.

### Description

1. I think the Widget listing should take into consideration the existing setting that we have for searching exclusion? Or just show all files as Markor already does.

### Information

Android version: 12
Device: Xiaomi 10
App Version: 2.10.3

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
Tend to generally remove the filter there. You should see the same amount of files like at the startscreen file browser.

**Comment by filisko** [comment]
@gsantner i don't have any filter there. The Widget only shows markdown files.

**Comment by gsantner** [comment]
You have the filter there, to only markdown + folders. **You just cant configure it.**   
When there would be no filter you would see it all.

**Comment by filisko** [comment]
Yes, there is a filter indeed. And folders are not included either.

**Comment by gsantner** [comment]
With the next update Markor uses the same sorting & filtering like the filebrowser on startscreen. Also folders are shown in the widget and are opened in the Markor filebrowser onclick.

**Comment by filisko** [comment]
Thanks man @georgefst ❤️❤️❤️

**Comment by filisko** [comment]
Thanks man @gsantner ❤️❤️❤️
