### ISSUE TITLE
Markor always crashes, when I try to call settings for action buttons

### ISSUE THREAD

**Issue by aisbergde** [gsantner/markor#1841]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] Is the bug still present in the latest code version (git master)? Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. No worries Markor and Mordor appear as completely separate applications, you can install both side-by-side and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report - the change will be part of the next Markor update.

### Description

in format style settings are points to set the action button order. Markor always crashes (restarts) when I try to this setting point. 

### Steps to reproduce

1. go to settings
2. go to settings for one of the format types
3. click on Aktions Reihenfolge

### Information

Android version: 12
Device: Poco M4 Pro, with MIUI Global 13.0.1
App Version: 2.10.3 (139)

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
- the same issue happens on Poco F1, with Android 10 and MIUI Global 12.0.3

I did not try the Mordor version, but issue can't be reported whithout checking this option.

It should also be possible to submit issues, using a stable version.
```

**Comment by gsantner** [comment]
duplicate #1815 fixed with next update
