### ISSUE TITLE
Elusive bug deletes content of files randomly

### ISSUE THREAD

**Issue by VVill-ga** [gsantner/markor#1842]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] Is the bug still present in the latest code version (git master)? Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. No worries Markor and Mordor appear as completely separate applications, you can install both side-by-side and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report - the change will be part of the next Markor update.

### Description

I'm not sure if it happens with all files, but in the last few months, I've had my todo.txt and QuickNote.md now completely emptied for no apparent reason (twice now, so this is pretty rare, but none the less an absolutely app-breaking bug since it deleted a ton of info I needed). I have no idea what would cause this, but I will now be making quick notes and todo lists as generic files. I will post an update if any of my normal markdown files suffer the same fate.

Another thing that may be helpful is that the undo and redo buttons both appear to be active, but pressing on either one just crashes the app. Let me know if there is anything I can upload to help diagnose the issue; my todo and quicknotes were just deleted and I'm not gonna touch those sections anymore.

### Steps to reproduce

1. Be happily making notes and todo lists
2. Leave
3. Come back
4. Find an empty file where once there were thoughts

### Information

Android version: 8.0.0
Device: LG G5
App Version: 2.10.4 (140)

### Source

Google Play

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
Hey, such reports are coming in like every 1-2 weeks, please check for existing ones - it just adds up for maintainence to write at multiple places. I.e. #1671 

Generally said, I use always the latest version of Markor (which now is 2.10.4) and I haven't run into such issue at any point. So sure it's not something with i.e. your file sync software? File management permission not granted? Generally I'm not aware of file saving issues, and we work REALLY REALLY HARD that it works well - like 50% of time just goes into making that work properly. If you want to make it better, please do it - contribute code.

Please write at 1671 if you need to respond something, want to paste logs or anything. thanks. Most helpful would be, for anything you run into - that when you can reproduce it, you use adb logcat to make logs and paste it.
