### ISSUE TITLE
Widget: Non-textfiles are opened as textfiles

### ISSUE THREAD

**Issue by filisko** [gsantner/markor#1845]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] Is the wanted feature/enhancement present in the latest code version (git master)? Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. No worries Markor and Mordor appear as completely separate applications, you can install both side-by-side and Markor settings are not touched. If so, the change will be part of the next Markor update.

### Description

When I add the Widget on my screen with some files being PDF files and press on them, Markor tries to open them as Markdown files.

The expected behaviour is that it is opened by System's default PDF files opener, as usual on normal usage.

What currently happens is that PDF file is parsed to string in the viewer.

Want to mention that there is no app in PlayStore that allows you to add a widget with a list of files! Crazy. So this is a great feature I have to say.

Thanks man!

### Information

Android version: 12
Device: Xioami 11
App Version: 2.10.4

### Source

F-Droid

### Format / File type

Binary

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
Initially it was just Markdown files listed. But by my changes at #1840 also implemented showing folders and other files.

Needs some additional handling I see.

**Comment by filisko** [comment]
Yep, understandable 🙂

**Comment by gsantner** [comment]
@filisko With next update widget file & folder clicks works in the same way when you would click a file at the mainscreen filemanager.
