### ISSUE TITLE
Voice Assistant, Speech recognition, Transcription

### ISSUE THREAD

**Issue by westurner** [gsantner/markor#1846]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] Is the wanted feature/enhancement present in the latest code version (git master)? Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. No worries Markor and Mordor appear as completely separate applications, you can install both side-by-side and Markor settings are not touched. If so, the change will be part of the next Markor update.

### Description

Users can create and/or append to documents with their Voice using a Voice Assistant in order to save lots of time.

OKG: "OK Google" 

- OKG add to {quicknote, todo,} [text]
- OKG quicknote [text]
- OKG {...} [text] *[note attrs]*

### References
- App Actions and Android Slices
  https://developers.google.com/assistant/docs
  - https://developer.android.com/guide/app-actions/get-started
    > App Actions are only available for apps published to the Google Play Store
  - https://developers.googleblog.com/2022/06/Helping-Developers-Create-Meaningful-Voice-Interactions-with-Android.html
  - https://developers.google.com/learn/pathways/app-actions
  - https://developer.android.com/guide/slices
    - slice idea: Show added text & attrs
    - slice idea: Show previous n lines of the target doc, too
- AutoVoice (Tasker,)
  - has a "note to self" demo voideo
  - https://joaoapps.com/autovoice/
  - https://www.androidauthority.com/add-more-android-voice-commands-809846/
  - is not released to F-Droid, or microgapps, either

### Information

Android version: 12
Device: 
App Version: 

### Source

Google Play

### Format / File type

Not specific

### Additional info / Log

```shell
- .
```

**Comment by gsantner** [comment]
If you are intersted, please implement it and make a pull request and add it, thanks.

Not an option: Dependency on Google Play libraries, any license/api key.

**Comment by westurner** [comment]
- AutoVoice (Google Play)

**Comment by westurner** [comment]
https://github.com/openai/whisper :+1: :
> Whisper is a general-purpose speech recognition model. It is trained on a large dataset of diverse audio and is also a multi-task model that can perform multilingual speech recognition as well as speech translation and language identification.

**Comment by westurner** [comment]
FWIU:
- There are voice transcription neural network minification approaches to reduce the file size of a [openai/whisper] potential voice transcription model app dependency for use while the microphone indicator is active.
- TensorFlow Lite is now included in the Google Play Services (SDK) app so that it's only downloaded once.
  - https://www.tensorflow.org/lite/android/play_services :
    > TensorFlow Lite is available in Google Play services runtime for all Android devices running the current version of Play services. This runtime allows you to run machine learning (ML) models without statically bundling TensorFlow Lite libraries into your app.
  - What about PyTorch?
  - What about (LinuxFoundation/) ONNX?
    - https://github.com/onnx/onnx
      - https://github.com/onnx/onnx/blob/main/docs/PythonAPIOverview.md

**Comment by gsantner** [comment]
@westurner   
Thanks for the insights and searching. If you are interested in adding something to Markor feel free to! You can make a merge request as soon something minimum viable is there.  
As of what to add, please don't bloat Markor in terms of both size and dependencies. If you have to add 50 lines to some xml/java, fine! In case you have to add pytorch,tensorflow,voice models & trainingsets, google play 3 libs.. I have to pass - thats what better is done in some external dedicated application.

**Comment by westurner** [comment]
I do not accept assignment of this issue.
(In part due to the new F-droid dependency, because F-droid doesn't even
SafetyNet)

Perhaps it would be best to close it?

**Comment by gsantner** [comment]
Assignment doesn't mean much, this is not a company^^.
