### ISSUE TITLE
Clean URLs with/like urlchecker

### ISSUE THREAD

**Issue by westurner** [gsantner/markor#1847]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] Is the wanted feature/enhancement present in the latest code version (git master)? Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. No worries Markor and Mordor appear as completely separate applications, you can install both side-by-side and Markor settings are not touched. If so, the change will be part of the next Markor update.

### Description

Users can clean URLs with/like URLCheck, which has undo and per-URL-parameter move param buttons 

https://f-droid.org/en/packages/com.trianguloy.urlchecker/

Workaround: Share to URLcheck and then Share to Markor, but that omits the `<title>` and then there's manual cursor positioning and pastinh

### Information

Android version: 12
Device: 
App Version: 

### Source

Google Play

### Format / File type

Something else (-> Additional info)

### Additional info / Log

```shell
- .
```

**Comment by gsantner** [comment]
I implemented similar functionality on my own at Markor - #1490 .

Don't like to generally directly depend and have to wait for some external specific application to be honest. As you discovered, you can also share to Markor from that app, so you can use it this way.
