### ISSUE TITLE
Page URL When Sharing Selected Content

### ISSUE THREAD

**Issue by mlsmith0** [gsantner/markor#185]
#### General information

* **App version: 0.3.2** 
* **System: Android 7.0, Samsung Galaxy S7 Edge** 

#### Feature Requests

- When selecting content on a web page and sharing to Markor, append URL to the bottom of the content. This would be great to have for reference of where the information came from.

- Bonus points if you're able to make the file name the same as the page title when sharing the page content to a new note.

Thanks in advance for your consideration.

**Comment by gsantner** [comment]
1) not really possible. there is no way to get the caller intent package below API22, and even if it is really limited or may still not work.

2) Some browsers seem to transmit tge title via Intent.SUBJECT. theres no guarantee for that, but that may be used. Feel free to send a PR for this.

**Comment by drknrg** [comment]
@gsantner Thank you for the quick response. I'm not much of an Android developer but I'll see what I can do. :relaxed:

**Comment by gsantner** [comment]
Closing as there is not much doable here
