### ISSUE TITLE
Headline wrapping past the width of screen

### ISSUE THREAD

**Issue by hydrargyrum** [gsantner/markor#1856]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] Is the bug still present in the latest code version (git master)? Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. No worries Markor and Mordor appear as completely separate applications, you can install both side-by-side and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report - the change will be part of the next Markor update.

### Description

In edit mode, regular text is wrapped but headlines are incorrectly wrapped. The width used as wrapping base is larger than screen. Thus, lines are truncated. This doesn't happen on view mode.
This happens when headlines are configured to show larger than text.

### Steps to reproduce

1. Configure headlines to show larger than text.

2. Enter the following text:

```
The following headline should read:
0.123456789 1.123456789 2.123456789 3.123456789 4.123456789 5.123456789 6.123456789 7.123456789 8.123456789 9.123456789 A.123456789 B.123456789 C.123456789 D.123456789 E.123456789 F.123456789

# 0.123456789 1.123456789 2.123456789 3.123456789 4.123456789 5.123456789 6.123456789 7.123456789 8.123456789 9.123456789 A.123456789 B.123456789 C.123456789 D.123456789 E.123456789 F.123456789
```

### Information

Android version: 9
Device: 
App Version: mordor latest

### Source

F-Droid

### Format / File type

Markdown

**Comment by hydrargyrum** [comment]
This is how it renders

![Screenshot_20220925-190708_Mordor_1](https://user-images.githubusercontent.com/2804645/192156121-09fe7781-330e-415a-b2ac-62636f982db2.png)

**Comment by gsantner** [comment]
what do you have configured in the file settings at wrap? top menu 3 dots

**Comment by hydrargyrum** [comment]
Wrapping is enabled here. If I disable wrapping there, scrolling is ok. Horizontal scrolling is painful though when on the quicknote screen, because it also triggers sliding to "todo" screen (on the left) or to "more" screen (on the right).

**Comment by gsantner** [comment]
OK thanks for confirming. Hm looks like some bug in the TextView 
internal render calculations.

It also happens when "Partial Highlighting" (Markor general settings) is 
disabled, correct?

Also if you add ~5 more chars to the heading it correctly breaks the line?

**Comment by hydrargyrum** [comment]
> It also happens when "Partial Highlighting" (Markor general settings) is disabled, correct?

I don't use the english locale, but if you mean "dynamic highlighting", yes, when disabled, the problem is the same.

> Also if you add ~5 more chars to the heading it correctly breaks the line?

What do you mean "correctly"? The "7.123456789" text is still hidden (as in the screenshot) whatever I do.

Not sure if it helps but it seems the spacing between lines seems unequal between the 0.123456789-4.123456789 (virtual) lines and the 4.123456789-8.123456789 (virtual) lines.

**Comment by hydrargyrum** [comment]
> Also if you add ~5 more chars to the heading it correctly breaks the line?

Oh, you mean that the headline is wrapped after the same character positions as the regular text (because I used the same text for both), even though it shouldn't because the font is bigger. If that's what you meant: if I add more text at the end of the headline (after a space), it breaks before the new added text, just as it would for the regular text.

**Comment by fredericjacob** [comment]
@gsantner I can confirm this. The problem occurs only if the "Bigger headings" setting is enabled. Something must have changed in the logic for adapting the font size dynamically according to the heading level in the past months. (In my old development version of the app from many months ago, this problem does not occur).

This is how it looks like with "Bigger headings" disabled:
![grafik](https://user-images.githubusercontent.com/45181277/205464981-b484527b-a1fe-47c2-87f1-1019bde8f339.png)

And like this when it is enabled:
![grafik](https://user-images.githubusercontent.com/45181277/205465027-27e5b07a-a352-42d4-b2f9-23b9a02599ef.png)

**Comment by harshad1** [comment]
I can't reproduce this. Perhaps it is solved? On latest master. (Pixel 7 pro)

![image](https://github.com/gsantner/markor/assets/1940940/39d28c3f-7e06-473f-a878-ddf71711f42f)

**Comment by hydrargyrum** [comment]
Maybe https://github.com/gsantner/markor/pull/1953 fixed it?

**Comment by hydrargyrum** [comment]
Thanks for the fix
