### ISSUE TITLE
search result - a way to open the found file in the file list

### ISSUE THREAD

**Issue by aisbergde** [gsantner/markor#1862]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] Is the wanted feature/enhancement present in the latest code version (git master)? Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. No worries Markor and Mordor appear as completely separate applications, you can install both side-by-side and Markor settings are not touched. If so, the change will be part of the next Markor update.

### Description

Currently from the search result I can only open the file to edit.

I suggest a way to be able to not open they file, but to show it in the file list. Then I can transform some actions, like setting it as favorite.

For example on long press on a search result item a context menu could open. Maybe some action could even available there, like "add to favorites" 

Working with a big amount of files some easy way to locate the file in the file browser is required. Search is intuitive. And maybe it can be easily extended.

also some quick filter in the file browser could be fine:
where I can enter parts of the filename and the file list will by dynamically filtered.

### Information

Android version: 
Device: 
App Version: 

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
#1862 #1911 similar

**Comment by harshad1** [comment]
This is easy to implement, but what should the UI be? In the search (in files) dialog we have:

1. short press on filename opens the locations in the file which match
2. long press on filename opens the top of the file (should probably respect the open on bottom option here)
3. short press on location opens that location in the file

I guess we could add a right-aligned folder icon to the file names?

Opinions appreciated.

**Comment by gsantner** [comment]
Instead of adding new special way of clicking, or reducing the space for findings. Suggesting this way:

Add a new checkbox option at upfront dialog to enable jumping. There:


![Screenshot_20221106-083545_Trebuchet](https://user-images.githubusercontent.com/6735650/200159594-bd5996f3-3ac8-4b61-a99d-06972cd6ac23.png)

**Comment by harshad1** [comment]
Thinking about this further, opening the file location on long press as the default is sufficient. Then opening the file itself is
1. Search
2. Long press to open location
3. Tap file to open

i.e. 1 extra tap to enable both workflows rather than adding checkboxes etc.

**Comment by aisbergde** [comment]
the current long press action is strange: Something opens, but it is not intuitive to understand, what. Only now I got it: the first item of the result list opens. Long press could be used more intuitive.

So, I still think, both ways are fine:

* showing and marking the file in a file list in its natural context (getting the focus, or whatever happens, if a file is manually selected)
* open a context menu

and I agree, context menu could be avoided to keep it simple. I would prefer the first option.

**Comment by harshad1** [comment]
> The first item of the result list opens. Long press could be used more intuitive.

This is a bug. It is supposed to open the file being long pressed

**Comment by harshad1** [comment]
I have a PR to address this - https://github.com/gsantner/markor/pull/1914

Long press file name in search dialog to jump to it's location. Needs a lot of testing. Would be good if some of the people asking for this could test.

**Comment by aisbergde** [comment]
If it would be merged into master, I could sync into my fork and test.

**Comment by harshad1** [comment]
You should be able to pull it in without it being in master.

Nov. 10, 2022 23:25:28 Germo Görtz ***@***.***>:

**Comment by aisbergde** [comment]
Then I just don't know how. This is how it looks like in my fork. I can only sync or update to and from master:
![image](https://user-images.githubusercontent.com/9020187/201323694-8e0f8374-badd-442e-8e92-66946455f80a.png)
Or is there another place, where I can do?

**Comment by gsantner** [comment]
Don't make it more complicated then it is - you and everybody can easy download a prebuilt APK with the PR's changes included from here <https://github.com/gsantner/markor/actions> --> <https://github.com/gsantner/markor/actions/runs/3443176585>. That build and feature can be tested/tried independent to  some other PR.

**Comment by gsantner** [comment]
Don't make it more complicated then it is - you and everybody can easy download a prebuilt APK with the PR's changes included from here <https://github.com/gsantner/markor/actions> --> <https://github.com/gsantner/markor/actions/runs/3443176585>. That build and feature can be tested/tried independent to  some other PR.

And if you want to REALLY make it more complicated then that, you don't need github for that. Add git remote harshad, git fetch harshad, git merge harshad/pr-branch .

**Comment by aisbergde** [comment]
I don't know, how to run 2 different "Mordor" one my Smartphone

If I build my fork, then it is named "Mordor". And I don't know, how I could change this in a way, which will change the name of the build application only in my fork, without pushing this back into the main development. Maybe this is very easy, but I miss experience.

**Comment by C0D3D3V** [comment]
> Maybe this is very easy, but I miss experience.
@aisbergde  gsantner basically told you all commands in his last sentence that you need to run (only in a very shorted way :D)
An maybe simpler way without adding harshad1 repo to your remotes but only upstreams (what you maybe already have done)  would be this:
```
git remote add upstream git@github.com:gsantner/markor.git
git fetch upstream pull/1914/head:pr_1914
git merge pr_1914
```
This would merge the PR with your current branch. Actually this is only one possible way xD But do not worry about it, I will test the new feature with my workflow...

**Comment by aisbergde** [comment]
I think gsantner is right and independent testing would be easier, then to mix different PR.

The best way would be to get my PR merged into master and to get these features into the official Markor. Then Mordor could be used just for testing, and I would not need to use Mordor as my productive editor.
