### ISSUE TITLE
allow additional file extensions for templates

### ISSUE THREAD

**Issue by aisbergde** [gsantner/markor#1863]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] Is the wanted feature/enhancement present in the latest code version (git master)? Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. No worries Markor and Mordor appear as completely separate applications, you can install both side-by-side and Markor settings are not touched. If so, the change will be part of the next Markor update.

### Description

only templates with specific extensions are shown in the template list. I want to be able to create and use templates for other languages using different extensions

Here are my snippets, containing also a template with file extension adoc

![IMG_20220928_072226](https://user-images.githubusercontent.com/9020187/192694298-be157c80-a3ed-41ae-b46e-2c477b9a9f18.jpg)

But it can't be selected, when creating a new file

![Screenshot_2022-09-28-07-24-37-372_net gsantner markor](https://user-images.githubusercontent.com/9020187/192694582-88f28357-b3e5-4941-9cf1-8836edf93963.jpg)

btw, alphabetical sorting would be fine in lists, where templates or snippets can be selected. When creating new files or when using snippets. Should I create a separate feature request?

### Information

Android version: 
Device: 
App Version: 

### Source

F-Droid

### Format / File type

Plaintext

### Additional info / Log

```shell
-
```

**Comment by aisbergde** [comment]
similar for code snippets. Currently only files with extension txt can be selected.

**Comment by harshad1** [comment]
I think the issue is that your file is not being detected as a plain text file.

Place to fix this is in the `getMimeType` function in `GsFileUtils.java`

I have some fixes to this in my PR. Will continue to try and address this issue too.

**Comment by gsantner** [comment]
> similar for code snippets

Code snippets and the listed templates are the same just shown in other list.

**Comment by aisbergde** [comment]
maybe on your device. On my device they are different.
code snippets list only txt, template will list txt and md.
adoc is not listed in any of these lists.

**Comment by harshad1** [comment]
> On my device they are different.

They use different mime type functions unfortunately. I am working to clean this up a little. But adding an exhaustive list of extensions is impossible. As a shortcut, I think we should also accept file types which are listed as 'open within markor' in settings

@gsantner ?

**Comment by gsantner** [comment]
>  I think we should also accept file types which are listed as 'open within markor' in settings

yes, sure. Thought it's already like this, but seems like not 😄 .

**Comment by gsantner** [comment]
btw added also adoc to the custom mime-type mapping as none of the other 10 things is capable of detect it. I mean well, it's nothing popular like jpeg.
