### ISSUE TITLE
sort search results and drop down lists alphabetical 

### ISSUE THREAD

**Issue by aisbergde** [gsantner/markor#1864]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] Is the wanted feature/enhancement present in the latest code version (git master)? Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. No worries Markor and Mordor appear as completely separate applications, you can install both side-by-side and Markor settings are not touched. If so, the change will be part of the next Markor update.

### Description

in several places lists are shown, to select an item:

- search results
- template files
- code snippets
- maybe other places

Currently the elements are not sorted by any intuitive logic. It is hard to use these lists if they contain a bit more items.

It would be much easier, it the items in the lists will be sorted alphabetical.

### Information

Android version: 
Device: 
App Version: 

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
Hello, I see that there are really many, new requests open by you again. Once again the reminder, please help programming Markor if you want something. Some things really could also be solved by somebody not having in-depth knowledge of the project, Java and Android. As said, code not comes by only talking 😉 . Markor can't fit the high continuous demands of power users without respective amount of active developers.

**Comment by aisbergde** [comment]
I really don't understand you.

As I wrote, I can't contribute by coding. I can only contribute giving feedback, reporting issues, suggesting feature request. If this has no value for you, but if this is disturbing you, then I should not wast my time and effort to report issues.

I think, we have a communication issue. I hope to create value, giving feedback, you interpret this in a different way.

Very sorry, that I am not able to communicate in a way, that leads in the results, I wanted to cause.

**Comment by gsantner** [comment]
It is totally helpfully to everybody when you report issues. But when it comes to your feature request and personal idea of whats

**Comment by gsantner** [comment]
It is totally helpfully to everybody when you report issues. Thank you.

But when it comes to your feature request and personal idea of how `something` could be better, or what could be added - I have to say, I can't make what everybody wishes. Just like harshad1, we do what we thinks is good, and is our time worth for. Time is limited.

We don't have a communication issue here, it's quite the same I'm (and harshad1 also) tried to tell you: You have an idea about programming - and just like harshad1 - maybe have no knowledge about java or the project. BUT: It is something you can learn, if you want it. But please don't try the direction of just pasting everything coming to your mind, and come guys, do it. Thats not how it works.

**Comment by aisbergde** [comment]
For me a feature request is a suggestion. you can realize, you can put it on Hold. But I thought, the best way to suggest something is a feature request. But it looks like we have a different interpretation. I try to use the formalized place. And maybe this is the wrong place, because it is interpreted as something, I want to force.
I know other projects, where discussions or other places are used to discuss possible features. Maybe this is softer.
I see, that Markor is the best editor on android. And sometimes I try other editors, and sometimes there are some things, which are better.

I see a feature request as an offer, to make something better.
Maybe this is, because I personally love to get feature requests for products or solutions, I am responsible. And I try to deliver, what I would like to get im my projects. And, unfortunately, written communication is often a bit complicated, because it can be wrong interpreted. So please interpret my feedback not as pressure, but as my best possible attempt.

**Comment by gsantner** [comment]
Again thanks your input, you mean it for the good - thats OK. But don't overload maintainers. Everything somebody writes is something needs to be read, to think about and to be responded to, all of it takes time. And opening 5 different topics by one person in ~1h is too much to handle, to respond to and to look into - when we have our job and family and maybe half an hour after work for the project on a day. And it's not only you who wants something, it's many people (there is also multiple private mails and gplay feedback I get...everyday - which is what you don't see and I do behind the scenes). Time is limited. 

And: I will try to close issues without too much comment if I don't see it fitting and don't want to continue discussing it all day over. That's what you can expect. Like I said, i.e. I don't wanna work on AsciiDoc, but you wrote already much stuff & issues about it, and took time to check your texts - so it took me already many hours for asciidoc, which I don't want to work on for example.

So please, don't overload us with feedback. And if it somewhat belongs together, maybe keep it together at one topic/issue.

**Comment by aisbergde** [comment]
OK. But I think sorting is something, which is useful for everyone.

I understand, that reading and understanding issues takes time. And if I am working and found something, then I think it is much better to create several issues, each for a clear area. Then one big issue, containing a mix of different things.

But then I get the feedback, that the frequency is to high. Should I collect them? And then report only x issues per y day, because of a virtual issue frequently limit?

It looks like, again, that use issues in different way. In my projects I use issues keep my brain clean. I put it into an issue, it is there and I don't need to keep it in my mind. Of course, the 2 categories open and close, are not enough for my way to work. I use other systems, where a can tag or group with additional tags. And this way issues are sometimes just a container for something, what I will not implement now and fast, but for ideas.

You also use discussion in the project. You could transform issues in ideas. You could also tell people: please do not create feature requests, but only ideas, and the maintainers will decide, which ideas will be converted into feature request.

Maintainers should feel well with the "ticketing system" and the workflow. If the current workflow creates to much presser, it could be changed.

For example, in my projects I don't like to use Emails as a ticket system. I get lost. I create issues from this emails in an issue tracker and force (or nudge) people to use, and this works.

**Comment by gsantner** [comment]
What you should do is value our time and respect it when we say it's too much.

And again, as you say you also use it for work - please consider contributing code.
