### ISSUE TITLE
Remove file associations from Manifest

### ISSUE THREAD

**Issue by h-cspu** [gsantner/markor#1868]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest code version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. Don't worry; Markor and Mordor appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

Please remove the default file association *.md and others in AndroidManifest.xml.

I think it's better to let the user handle file associations in Android App-Settings "Open/Launch by default".

### Information

Android version: 7 (LineageOS 14)
App Version: 2.10.4

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
No, why? When it's not listed you don't get tue optoon to choose Markor from the list.

Then next time people ask why they cant open md file with markor. No thanks.

**Comment by h-cspu** [comment]
> No, why?
I'd like Android to ask me with what app I want to open a file if i select it in a file manager.

Current situation: Android does not ask and opens md files with Markor.

**Comment by gsantner** [comment]
Do you have any other editor installed that can handle .md files? If not, that is why. When you only have one installed it always takes that one.
