### ISSUE TITLE
Share image link into Markor

### ISSUE THREAD

**Issue by gohma231** [gsantner/markor#1878]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest code version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. Don't worry; Markor and Mordor appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

I would like to be able to share image links into Markor similar to how text or URLs are shared.

Example steps:
1. Open image in photo gallery app.
2. Select share, then markor
3. Image is linked to the selected file. I'm guessing it would need to be saved in the markor directory. See image for example
![Screenshot_20221004-234738](https://user-images.githubusercontent.com/4106435/193977668-7e82b9bf-faa7-4702-9266-d38de4742ece.png)

### Information

Android version: 12
Device: Pixel 3a
App Version: 2.10.5

### Source

Google Play

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
Yes. Search for `share image` or `share picture`. There are like 3-4 of this now. Like #886 .
