### ISSUE TITLE
Widget: Hide dotFiles, similar to in-app filebrowser

### ISSUE THREAD

**Issue by uok** [gsantner/markor#1879]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest code version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. Don't worry; Markor and Mordor appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

Thanks for this helpful app!

It would be great to have an option to hide dot files/folders in the widget
Thanks!

### Information

v2.10.4

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by harshad1** [comment]
This has been implemented already in #1839 . Will be merged in soon I think

**Comment by gsantner** [comment]
Widget should use the same settings option for hiding dot files as the normal file manager does.  
Just like the other file sort settings ("sort by name"),.

**Comment by gsantner** [comment]
Oh, seems like we commented at the same time 😄

**Comment by uok** [comment]
Fixed in v2.10.6, thanks!
