### ISSUE TITLE
No way to get out of a directory?

### ISSUE THREAD

**Issue by jerry1970** [gsantner/markor#188]
#### General information
App version 0.3.1
Android 4.?

#### Description
When I click on a folder to see the contents, I see no way of getting back.

**Comment by gsantner** [comment]
Android's back button.

**Comment by kRkk** [comment]
But when you enter the folder, go to quicknote/todo/more/settings, return to the folder and click physical or software back button, a message will appear asking you to click again to exit

**Comment by gsantner** [comment]
happens sometimes but not always, I still identified why this happens. But the whole filesystem view needs to be reworked as a whole anyway, which is an own issue topic.  #115 . As said in the chat list, help welcome, but still not a single sign of help by anybody on anything, so this gonna take some time to get fixed.
