### ISSUE TITLE
Open *.xml files

### ISSUE THREAD

**Issue by fabian-thomas** [gsantner/markor#1881]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is not present in the latest code version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. Don't worry; Markor and Mordor appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

Opening *.xml files doesn't give markor as option. I would expect markor to be an option.

### Steps to reproduce

Open any *.xml file with e.g. file browser.

### Information

Android version: 12
App Version: 2.10.5

### Source

F-Droid

### Format / File type

Plaintext

**Comment by gsantner** [comment]
Most specific file extension you want to specifically open from an **external** file browser, need to be registered in androidmanifest.

What for sure you can do is click the file in Markors filemanager and it opens up at the editor. Something else requires changes on the application.

**Comment by fabian-thomas** [comment]
But you would be open to merge a PR that adds .xml?

**Comment by gsantner** [comment]
Of course!
