### ISSUE TITLE
enable the choice of color schemes that also work for red-green color-deficient users

### ISSUE THREAD

**Issue by aisbergde** [gsantner/markor#1885]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. Don't worry; Markor and Mordor appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

people with red-green color weakness (like me) can hardly or not distinguish the colors, used in syntax highlighting. We need a general solution for this that applies to all formats.

I suggest that you can configure the colors used for syntax highlighting:

- there can be gladly a scheme that works for the light and the dark theme. For example, the current scheme.
- there should be the possibility to define different combinations for the light and the dark theme
- there should be several presets, including a color schemes (or two, separated for light and dark) for red-green color weakness
- there should be a possibility to create, save and restore your own color schemes

### Information

Android version: 
Device: 
App Version: 

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
What you imply by asking for this, is complete themeing support of like every detail. Thats something I don't like to opt for, just bloats everything and means maintainence.

What I however may suggest is that: Option to convert colors to greyscale automatically. That should be visible just fine for all kinds of issues with  colors. And at same time it is something for the minimalists out there, who just want to edit text without any fancy colors.

**Comment by aisbergde** [comment]
Unfortunately, it's always a big problem that the majority of people, who can distinguish all colors well, don't want to or can't put themselves in the shoes of the 5-10%, who have problems with some color combinations. That's when you get a suggestion like this: "Let them switch to white - gray - black." You probably can't imagine how frustrating that is.

If you're lucky, the person responsible for a software product is red-green-color-weak himself. Then a solution can be found quickly.

But basically the idea is OK. Wir wollen ja nicht das Kind mit dem Bade ausschütten :-)

I could now cite several articles and scientific studies. But to make it short: Red-blue can distinguish practically all well. This should also be used instead of red-green in reports. In many products there are now also themes that are colored, and yet optimized for color-weak people.

And now I just thought: if I already implement the extension for AsciiDoc, then I can at least use colors there, which I can also distinguish. And then I had the idea to generalize this. But in the end it is enough for me, if at least the AsciiDoc contents for the syntax get a scheme, with which I can live. I don't need a general solution if that's not what you want.

**Comment by gsantner** [comment]
> I don't need a general solution if that's not what you want.

The thing is, I want a lot. You also want a lot. But time and energy is not unlimited. ^^   
It's totally not about accessibility is not wanted, totally not. But this is something rather big - we talk here about ~100 colors in project, meaning ~100 settings options. And thats something you need to outweight when it's just serving one goal - when in contrast its the same amount of other settings.

You can do that easy somewhere in a project easy where you have 3 colors. But there is more way more than that here.

And if your asciidoc colors are better fitting to you, fine for me. Though still it not really solves the problem generally. (Doing nothing doesn't either).

**Comment by aisbergde** [comment]
For AsciiDoc I will implement colors, based on https://personal.sron.nl/~pault/
Paul tol, about color schemas, distinct for all people, including colour-blind readers;

**Comment by gsantner** [comment]
Best to also take in account 1) colors used for things already in Markor 
and 2) colors you might be used to in other software supporting 
asciidoc. For example, the Markor "http-Link blue" should work fine right?

**Comment by gsantner** [comment]
Closing as AsciiDoc will use what aisbergde wanted to use and probably uses primarly asciidoc.  
For a complete app theming to the smallest bit for every single color for every single highlight in both light and dark mode... Markor is ready. And my view is the day we make every smallest bit configurable, Markor is more bloated then I want.
