### ISSUE TITLE
Homescreen shortcut does not work

### ISSUE THREAD

**Issue by h-cspu** [gsantner/markor#1887]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. Don't worry; Markor and Mordor appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

If I create a homescreen shortcut to a file (normal or "special" file) and tap on it, I only get "App isn't installed."

Yes, I have enabled "Launcher (Special documents)" and rebooted.

### Steps to reproduce

1. 
2. 
3. 

### Information

Android version: 7 (LineageOS 14)
Device: 
App Version: 2.10.5

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by h-cspu** [comment]
Forgot to mention that I'm using the default launcher Trebuchet.

**Comment by gsantner** [comment]
Do shortcuts works into your launcher from other applications, like lets say web browser?

**Comment by h-cspu** [comment]
Yes, I use homescreen shortcuts from two other apps (Simpletask, Total Commander) quite often. Never had a problem.

The Android-Version on my device is 7.1.2, LineageOS 14.1.

**Comment by gsantner** [comment]
OK, I mentioned it because you earlier said Just Android 7^^. As you see, details are often important.

**Comment by gsantner** [comment]
OK, I mentioned it because you earlier said Just Android 7^^. As you see, details are often important.    
So basically all additional information you gave now, is really important - so something to keep in mind for next issue wherever you report 😄 . Makes maintainers live easier.

**Comment by harshad1** [comment]
I've had this happen several times over the years (mostly when I am installing and reinstalling a lot while developing).

 Usually, re creating the shortcut (and sometimes rebooting) resolves the issue.

**Comment by gsantner** [comment]
Keeping this one closed now, like h-cspu also wanted. People will sooner or later come up with a own report when there is an issue. And otherwise might be just due old Android version - Android and the SDKs are not standing still and might be sooner or later the case that some things not work properly on dated Android versions.
