### ISSUE TITLE
Markdown: Italic syntax character settings option

### ISSUE THREAD

**Issue by samarulmeu** [gsantner/markor#1888]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. Don't worry; Markor and Mordor appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

Can you please have an option of choosing what character to use for Italic markdown (`*` or `_`). For me using `*` for both Italic and Bold is a consistent thing. And also `_` is a much common character in filenames. 

Thank you

### Information

Android version: Android 11
Device: 
App Version: 

### Source

Google Play

### Format / File type

Markdown

### Additional info / Log

```shell
-
```

**Comment by harshad1** [comment]
Note that using `*foo*` will both highlight and render correctly.  Also note that using underscores for italics is somewhat of a convention in markdown - github and other markdown using sites will use underscore for italics and asterisks for bold

**Comment by samarulmeu** [comment]
> Hm I'm in the opinion that _not everything needs to be an option_ . Rather the oposite, it's bloat. Markor has already quite extensive amount of options. But if you like it, feel free to implement and make a merge request.

If I could do it I would have already done it. I contributed to the translation of Markor without saying.

> Or: Just type the asterisk on your own, also a option.

On mobile is difficult to search on the keyboard twice for the asterisk as opposed to just press an icon.

**Comment by samarulmeu** [comment]
> Note that using `*foo*` will both highlight and render correctly.  Also note that using underscores for italics is somewhat of a convention in markdown - github and other markdown using sites will use underscore for italics and asterisks for bold

I know the use of markdown marks and GitHub markdown is just a flavour. All the sites that use markdown **must** recognize one asterisk for italic as specified [here](https://daringfireball.net/projects/markdown/syntax#em)

**Comment by gsantner** [comment]
There are many different flavors and stuff at Markdown, you can hardly broadly say "markdown must X". But yes thats something most parsers I know support.

However, this is off-topic to what you want. 

Still thanks, but I'm closing this now as won't fix. Not everything needs to be an option.
