### ISSUE TITLE
crash trying to open file testing.foo

### ISSUE THREAD

**Issue by h-cspu** [gsantner/markor#1893]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. Don't worry; Markor and Mordor appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

To test the ignore list, I created a test text file "testing.foo". When I try to open it, the app crashes.

### Steps to reproduce

1. 
2. 
3. 

### Information

Android version: 7.1.2
Device: 
App Version: 2.10.5

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
Don't know what one has todo with the other. Ignore list is about the search and nothing else.

And opening a fresh created file, testing.foo and opening it works juat fine here in any case.

Please attach a debug log (adb logcat).

**Comment by h-cspu** [comment]
[log.txt](https://github.com/gsantner/markor/files/9761706/log.txt)

**Comment by gsantner** [comment]
exact same like your other bug created #1894 , duplicate
