### ISSUE TITLE
enhancement: make links in preview work

### ISSUE THREAD

**Issue by k3b** [gsantner/markor#19]
#### General information

* **App version:**  v0.1.2

#### Example1   

This md source link `[test](test)` is rendered in preview as html link. 

#### Current result

a click on this linke tries to open "file:/path/to/test" with mime type null (no mime)

#### Expected result

a click on this link should open "file:/path/to/test.md" with mime type "text/x-markdown" if file:/path/to/test.md exist. Else open "file:/path/to/test.html" with mime type "text/html" if file:/path/to/test.html exist. 

#### Note:

If you install Intent-Intercept (from fdroid store) you can monitor urls with mime type.

**Comment by sjmduncan** [comment]
I'm not convinced that the expected behavior is a good idea.

It's not useful if you (e.g.) sync your notes elsewhere and use almost any decent text editor - everything else requires the full filename so these links would *only* work in the app.

**Comment by gsantner** [comment]
absolute paths ( file:///home/user/some.html )work usually

**Comment by gsantner** [comment]
He asked if files can be opened with (Action.VIEW) the correct mime type. awe would need to look into it how to intercept such a click and apply that.

**Comment by gsantner** [comment]
Done in <https://github.com/gsantner/markor/commit/c32afb8602a8509904ea6490e67d6e953b87a9ff>
