### ISSUE TITLE
Support GitHub-flavored Markdown?

### ISSUE THREAD

**Issue by MisterY** [gsantner/markor#190]
#### General information
* **App version:** v0.3.2 
* **System:** Android 7

#### Description
Checkboxes (and generally GitHub-flavored Markdown) are not supported. Any plans for adding this functionality?
i.e. 
- [ ] add checkboxes in editor toolbar
- [ ] display checkboxes in preview mode
- [ ] support other GitHub MD features

**Comment by gsantner** [comment]
Our used markdown parser doesnt support it, any requests here need to asked over there

gh: commonmark/commonmark-java

**Comment by MisterY** [comment]
Thanks. In that case, and if you are interested, you might want to have a look at 
https://github.com/stefan-niedermann/nextcloud-notes

**Comment by gsantner** [comment]
we already switched from a unmaintained parser to the commonmark-parsers which is working like described in standard. and nope, we won't include the whole Rx bloat in this lightweight app just for RxMarkdown :)

**Comment by MisterY** [comment]
Bloatware or not, it does the job correctly, making Markdown much more useful and allows for a comparable experience to desktop apps (i.e. vscode + markdown all in one extension).

I've created the issue. Let's see what happens.
https://github.com/commonmark/CommonMark/issues/522

**Comment by gsantner** [comment]
It does ;) You are awaiting an extension here, not some syntax element of markdown or commonmark.

If commonmark at some point decides to support it via an extension we will activate that on Markor too.

**Comment by MisterY** [comment]
Yes, you're right. 
Lucky me, someone was faster -> https://github.com/atlassian/commonmark-java/issues/119

Apparently it is already a [listed extension](https://github.com/commonmark/CommonMark/wiki/Deployed-Extensions#bullet-list). Perhaps not in Java version?
