### ISSUE TITLE
Markor crashes when making a new note sometimes

### ISSUE THREAD

**Issue by WTechNinja** [gsantner/markor#1904]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. Don't worry; Markor and Mordor appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

Sometimes when I launch Markor (or mordor) and the view it goes to isn't the default, like the todo list for example, when I go back to the folder view and hit the Plus sign the app crashes with this error:

`FATAL EXCEPTION: main
Process: net.gsantner.markor, PID: 28028
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean net.gsantner.opoc.frontend.filebrowser.GsFileBrowserListAdapter.isCurrentFolderVirtual()' on a null object reference
	at net.gsantner.markor.activity.MainActivity.onClickFab(MainActivity.java:273)
	at net.gsantner.markor.activity.MainActivity$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7352)
	at android.view.View.performClickInternal(View.java:7318)
	at android.view.View.access$3200(View.java:846)
	at android.view.View$PerformClick.run(View.java:27800)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7050)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
`

### Steps to reproduce

1.  Launch the app, go edit a note, and stay on that screen.
2. Switch apps, do other stuff for a long time
3. Relaunch the app, exit whatever view you're in and go to the Files view and hit Plus
4. App crashes 

This is honestly a royal pain to reproduce, it's rare enough that I had to switch to using Mordor for a few days in order to see if it had the same bug.

### Information

Android version: 9
Device: Samsung Galaxy S8
App Version: 2.10.6-0942 (Mordor)
App Version: 2.10.5 (Markor)

### Source

git master branch

### Format / File type

Not specific

### Additional info / Log

```shell
I wouldn't be surprised if the app gets killed by my phone in the background, and is missing something when it tries to resume from where it was, but I don't know. If you need any more info let me know
```

**Comment by gsantner** [comment]
thanks the stacktrace/log looks very helpful!

**Comment by harshad1** [comment]
@gsantner I think we need to apply the fragment post thing here too.

This bug was likely revealed by fixing the other one.

**Comment by gsantner** [comment]
Sounds like Markor gets to some stat where it misses some file manager reference/data. You mentioned some background process killing, do you have something aggressive enabled there?

**Comment by WTechNinja** [comment]
Nah, I haven't changed any default settings or installed anything, I just mentioned it because samsung's infamous for their battery management stuff killing everything

**Comment by gsantner** [comment]
I use Markor daily and didn't run into this crash at any time - or more general no crash at all

**Comment by WTechNinja** [comment]
I haven't had it in a bit since now markor just doesn't show the new file dialog instead of crashing, but for a bit there I was probably experiencing it twice a day
![Screenshot_20221128-143730_Scoop](https://user-images.githubusercontent.com/64444934/204386551-94f7aae6-73ad-46f5-95fd-e80078399b86.jpg)

**Comment by gsantner** [comment]
is it reproducable to you somehow?

**Comment by WTechNinja** [comment]
Sadly no. I tried a lot of things but it seems like it was triggered by long periods of inactivity, or something similar

**Comment by sohamshanbhag** [comment]
I can second this bug. This crash used to happen to me and now the + button sometimes doesn't do anything. The 'steps to reproduce' is also similar, go to markor, change directory to anywhere but the home screen, exit (i.e., press home button, not back x2) do usual stuff for a long period of time not in markor, come back and the button does not do anything.

I'm also on a Samsung, so it may be their battery management.

Sadly, for me too, it is not reproducable. It also started recently (a few months back).
