### ISSUE TITLE
View-Mode: add hide viewing options toolbar in settings 

### ISSUE THREAD

**Issue by retromore** [gsantner/markor#1908]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. Don't worry; Markor and Mordor appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

In recent versions of Markor there's a new toolbar in view-mode but there's no setting to turn in it off or on. 

I think it takes away a clean focus from viewing notes and steals valuable vertical space for no good reason because all the functions we see there are actually mirrored:

- **jump to end/start** - long press main toolbar
- **jump to TOC** - it's always on to top so same as jump to top
- **rotate screen** - arguably majority of the users have auto-rotate screen turned on, so not much use for this button 

Maybe someone finds it handy but it would be good to have an option to hide it.

### Information

Android version: all
Device: all
App Version: 2.10.5

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
Not planning to add a settings option a to disable the bottom bar. Thats a very core feature of Markor.

We also had such a in the past and it made nothing but issues.

**Comment by retromore** [comment]
I'd consider removing this feature, as explained - it mirrors all existing functions and creates clutter instead. It's a classic design issue - solving problems that did not exist.

**Comment by gsantner** [comment]
Are you sure about that "solving problems that dont exist"?

People have been asking about easy way to jump to top/bottom, to jump to top, or open external.

**Comment by gsantner** [comment]
Are you sure about that "solving problems that dont exist"?

People have been asking about easy way to jump to top/bottom, to jump to table of contents, or open external. Just like Edit-Mode that bar is to be filled with actions specific to View-Mode.

There were such actions before tough hard to discover and know. Now they are explicit with an icon.

I'm not here to pleasure everybody and owns views :-).

**Comment by retromore** [comment]
> Are you sure about that "solving problems that dont exist"?
> 
> People have been asking about easy way to jump to top/bottom, to jump to top, or open external.
> 
> I'm not here to pleasure everybody and owns views :-).

But there's a long press toolbar, to jump top/bottom, perhaps not the most obvious thing to find out but that toolbar with 3 buttons seem to have only one useful (jump top/bottom that is) and other 2 are just there to justify the existence of the toolbar. So perhaps there could a better  solution.

Cleaner and focused view is a benefit for all users I reckon, so not exactly pleasuring myself here :grin:

**Comment by gsantner** [comment]
> But there's a long press toolbar, to jump top/bottom,


> There were such actions before tough hard to discover and know. Now they are explicit with an icon.

Thats exactly what I mean.
