### ISSUE TITLE
Scroll to file in filebrowser from currently opened file

### ISSUE THREAD

**Issue by C0D3D3V** [gsantner/markor#1911]
I use Markor to search fast for a specific markdown file in a directory (that contains thousands markdown files), and then I normally move that file in another directory (e.g. ToDo directory), But to do that I need to remember the filename and scroll through the file list till I find the file, so that I then can select it and trigger the move action. 

It would be great if the move action (maybe also the other actions like rename) are accessible inside the file viewer.

**Comment by gsantner** [comment]
File management is the hardest part of the editor/viewer already, not make it even more unnecessary complex. File management is there for... the file manager, so do it there.

However what I could think off is improving the file manager scroll position, so you are more likely to have the file on screen by scroll position when going to file manager.

Another point: How do other applications work here? Doesn't matter which editor, file browser, gallery or whatever is around, when I have 500 files in a folder I will get them always listed in all applications if I like it or not. If that's a problem to me, I would rather move files off before going on. You create the files and define the hierachy as you like it, not Markor. So if the file listing is a burden it might be also a good idea to change and rethink the own flow...to work with subfolders for example😉 .

**Comment by C0D3D3V** [comment]
My use case/work flow is certainly not very common, but you could of course simplify the matter by adding a possibility in the search, where you do not jump into the file when clicking on a search result, but the file manager jumps/scrolls to the file (possibly jumps into the subfolder).

My many Markdown files are already partially sorted into subfolders, but that doesn't change my workflow. The search also works in subfolders, which I find so great. And I don't know any other Android app at the moment that allows you to search for files based on their content (with regex) and displays the results in such a great way (i.e. with the occurrences of the search term in the file). And since I work with markdown files anyway it was handy. 

An alternative to the suggestion above would be a button in the viewer to display the file in the file manager, (so that this then scrolls to the file and changes the directory).

My workflow is something like this: 
I search for something specific, open a couple of the results at will. Then decide on a file. I move this to a working directory, there I edit the file. And as soon as I'm done, I move it to a completely different folder, depending on the content of the file and the result of my work...

**Comment by gsantner** [comment]
Maybe #1862 would also do the job for you?

**Comment by C0D3D3V** [comment]
True, #1862 seems to be a good solution. So we can close my issue in favor of #1862
