### ISSUE TITLE
Launched file shortcut doesn't respect `Prefer view` option

### ISSUE THREAD

**Issue by KLaurence** [gsantner/markor#1912]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. Don't worry; Markor and Mordor appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

When opening a home screen shortcut of a Markor file, the file always opens in edit mode, whether or not the `Prefer view` option in `Settings > View mode` is enabled.

The expected behavior is, since the `Prefer view` option is enabled, for the file to open in view mode.

### Steps to reproduce

1. In `Settings > View mode`, enable the `Prefer view` option.
2. Create a home-screen shortcut of a file by long-pressing the file, pressing the three-dot menu, and clicking `Create shortcut`. Confirm the addition to the home screen if prompted.
3. Click the shortcut. The file opens in edit view.

### Information

Android version: 10
App Version: 2.10.6

### Source

GitHub Releases

### Format / File type

Not specific

**Comment by harshad1** [comment]
@gsantner I think we should just remove the prefer view option. Its behavior alongside 'remember view state' is somwhat confusing.

@KLaurence We remember the view state for all files. The option only applies to 'new' files which markor has not seen before.

**Comment by gsantner** [comment]
>  think we should just remove the prefer view option.

Hm, how about these two things: 1) renaming the title/description so it reflects what it actually does now, and 2) marking it as experimental option  (hidden by default)

Overall, so much _hustle and bustle_ around this topic - if you ever land on the edit mode ... all you need to do is press the View-button once. That's it. It's not rocket science to do that.

**Comment by harshad1** [comment]
_or_ we just remove the option all together. It's pretty marginal and IMO default opening new files in edit mode + remembering the last state is good enough for 90%.

**Comment by gsantner** [comment]
Ah Nono. You need to know this is something that is asked about frequently - it's the mass of people complaining, not specific to you 😄 .

**Comment by gsantner** [comment]
Ah Nono. You need to know this is something that is asked about frequently - it's the mass of people complaining, not specific to you 😄 .

The thing is, we now remember view mode state for all files (this is also important for screen rotation), and that is in conflict with that settings option - or at last how users might expect it to work and how it's currently (maybe wrongly) described as.

**Comment by gsantner** [comment]
Made a change here, so when there is a file open request from anywhere inside Markor, or from widget there is a single document window opener function. I added now functionality there to overwrite the last view mode state to be just view mode (=true). So you get into view mode always when launching the document and the settings option is enabled.  
The thing it doesn't affect though is activity state, so you can switch to edit mode and it will stay in edit mode after rotation. This is due that the view mode apply happens before launch, not inside Activity itself.

I think that solution is a very good one and worked well here.

**Comment by gsantner** [comment]
Made a change here, so when there is a file open request from anywhere inside Markor, or from widget there is a single document window opener function. I added now functionality there to overwrite the last view mode state to be just view mode (=true). So you get into view mode always when launching the document and the settings option is enabled.  
The thing it doesn't affect though is activity state, so you can switch to edit mode and it will stay in edit mode after rotation. This is due that the viewmode override happens before launch, not inside Activity lifecycle itself.

I think that solution is a very good one and it works well on my device.
