### ISSUE TITLE
Cursor position saving question

### ISSUE THREAD

**Issue by xp12047** [gsantner/markor#1913]
### ⚠️ This issue respects the following points: ⚠️

- [ ] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [ ] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [ ] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [ ] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. Don't worry; Markor and Mordor appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

I want to save where the cursor is after editing is done and exited.  Otherwise, I have to move the cursor to the back every time I edit the document.  Really troublesome.

### Information

Android version: 10
Device: HUAWEI
App Version: V2.10.6(142)

### Source

GitHub Releases

### Format / File type

Markdown

**Comment by harshad1** [comment]
.... This is the existing default behavior. The cursor position should be saved for all documents. Is it not working?

**Comment by xp12047** [comment]
> .... This is the existing default behavior. The cursor position should be saved for all documents. Is it not working?

Yes, if it saves where my cursor was last edited.  I won't have to tap the screen again next time I tap into it.  Now you have to manually select the location after entering.

**Comment by gsantner** [comment]
> Yes, if it saves where my cursor was last edited. I won't have to tap the screen again next time I tap into it. 

I don't understand your problem here. Markor works correctly how it should work!?

**Comment by xp12047** [comment]
> > Yes, if it saves where my cursor was last edited. I won't have to tap the screen again next time I tap into it.
> 
> I don't understand your problem here. Markor works correctly how it should work!?

Sorry, every time I open it again after editing, it cannot locate the position of the last edit.  If it remembers where I was last edited, I can happily edit when I open it again, otherwise I have to manually select

**Comment by xp12047** [comment]
Actually I've been waiting for an update about this.  I have liked this software since last year.  Thank you for developing this excellent software.

**Comment by xp12047** [comment]
> 我一直在发布（Markor）版本和开发（Mordor）版本的大量文件上尝试它 - 它在两者上都运行得很好。我转到第 50 行和第 10 个字符，关闭文件/应用程序，下次打开该文件时，我又在第 50 行，c10。
> 
> 总体而言，很多事情都有一个例外——这是在 Mainacreen 选项卡 QuickNote 和 ToDo 上——它们总是从底部开始。
> 
> 很抱歉，如果您有问题 - 我不能说其他任何事情 -**无法重现**。

Ok thanks, I'll close the question for now.
