### ISSUE TITLE
Possiblity of iOS App?

### ISSUE THREAD

**Issue by mad1mystic** [gsantner/markor#1915]
1. Possiblity to have iOS app ?
2. The app is feature rich on Android , the best feature is export or share as pdf 
3.   is there a possibility to have iOS app ? For iPhone or iPad?

**Comment by gsantner** [comment]
no, yes pdf export builtin, no still.

**Comment by acmpo6ou** [comment]
For those who stumbled across this issue and might be disappointed there is no Markor for iOS: remember that Markor just operates on Markdown and text files, so they are easily accessible from any text editor. Just use an editor of your choice on iOS.

Also, thank you Gregor for creating Markor, I love you for this 🥰
