### ISSUE TITLE
Support for extended markdown ==highlight syntax==

### ISSUE THREAD

**Issue by yangauthier** [gsantner/markor#1916]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. Don't worry; Markor and Mordor appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

Hi, I'd really like to use Markor as my default markdown editor on Android, especially to read and annotate articles in plain text. I'd like to be able to highlight text. Although I've seen that `<mark>...</mark>` works, I've noticed the markdown syntax `==...==` does not. Would it be possible to see this feature impemented in a future version of Markor . Thanks for your amazing app !

### Information

Android version: 12
Device: Galaxy S20Fe
App Version: 2.10.6

### Source

Google Play

### Format / File type

Markdown

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
Please ask at Flexmark-java, Markors Markdown parser.

**Comment by Julrob199** [comment]
Looks like Flexmark-java is stalled and currently not further developed. It stucks at version 0.28, although common markdown is now 0.31
