### ISSUE TITLE
Create Markdown templates and set default in settings

### ISSUE THREAD

**Issue by kristofzerbe** [gsantner/markor#1918]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. Don't worry; Markor and Mordor appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

On creating new MD files user can choose a template. It would be helpful, if users can create own templates and store it like the snippets in an app folder. Furthermore users should choose a different default in the template list as 'empty file' in the settings

### Information

Android version: 13
Device: Pixel 6
App Version: 2.10.6

### Source

Google Play

### Format / File type

Markdown

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
Snippets are available for selection at the new file dialog, just like the predefined templates.

So what you are asking is already available.

**Comment by kristofzerbe** [comment]
Thing is, that the jekyll-template f.e. presets part of the  name and content for the file in a dialog, which have to go through anyway and which opens up always with 'empty file'. This feature would safe a lot of taps for me.

**Comment by kristofzerbe** [comment]
... ok ... Let me think again. How can I preset the tile name in a snippet?

**Comment by gsantner** [comment]
Markor does not have a templating system. What you get is a copy of a existing file.

And whatever you may read about tokens or whatever - it's not something supported, It's Markor internals, so not something you should use.

Generally I don't plan to invent something here, you get a copy of a file and you can write there whatever you wish. And as of variables, thats what you usually place in the frontmatter, and i.e. a static generator like jekyll takes care of filling fields. But Markor is not a static website generator.

**Comment by gsantner** [comment]
You can't. Type the filename as you like.Jekyll is the only special working at that place and I don't plan to generaly add templating all over the place. I mean, typing filename should't be THAT hard, isn't it? It should be less magic and special syntax, more keeping it simple (KISS) here.

Markor does not have a templating system. What you get is a copy of a existing file.

And whatever you may read about tokens or whatever - it's not something supported, It's Markor internals, so not something you should use.

Generally I don't plan to invent something here, you get a copy of a file and you can write there whatever you wish. And as of variables, thats what you usually place in the frontmatter, and i.e. a static generator like jekyll/hugo/... takes care of filling fields. Markor doesn't lock you in to any templating system or syntax here.
