### ISSUE TITLE
Link to headers in other files

### ISSUE THREAD

**Issue by Marinorama** [gsantner/markor#1919]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. Don't worry; Markor and Mordor appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

It should be possible to link to headers/anchors in other markdown files.

As in internal links, it should be irrelevant which level the header has - there will always be just one #. And there must be clear that:
1. empty spaces in header name will become - (see above)
2. header name in link is always lower case
3. special characters will be stripped

Example:
```
[linktext](another_file.md#chapter-two)

should link to:
## Chapter Two?
in another_file.md

```
### Information

Android version: 10
Device: Lenovo Tab M8
App Version: 2.10.6

### Source

Google Play

### Format / File type

Markdown

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
use search.

#812

**Comment by gsantner** [comment]
Do you use search? #912 #865

**Comment by Marinorama** [comment]
Don't get pissed. I did, but it is quite difficult to find what I was
looking for - regarding almost 2000 topics AND the different wording.
Besides: I still cannot see in which status this feature request is today...

Am Mi., 23. Nov. 2022 um 10:18 Uhr schrieb Gregor Santner <
***@***.***>:
