### ISSUE TITLE
Auto save

### ISSUE THREAD

**Issue by niccokunzmann** [gsantner/markor#1920]
# IMPORTANT
* App version: 2.9
* Android version/rom: 6
* Device: motog3
* I accept that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

## Explain the Problem
What problem did you encounter? What did you expect to happen?

I edited the quicknot. Then I came back after a few hoours. The content is gone.

## Steps to Reproduce
Explain what you did to encounter the issue

Open quicknote
add text
(No saving)
restart the phone
see the added text is gone

## Log
<details>
<summary>Log</summary>

```
Paste log here
```
</details>

# request

What I would like instead is an autosave option either for all or just quicknote or per file activated for todo and quicknote.

**Comment by niccokunzmann** [comment]
Oh. Nice. Which version includes this?

**Comment by gsantner** [comment]
every version, autosaving is there since first markor version.

you have a old version.

**Comment by lamyergeier** [comment]
@gsantner I have version v2.10.9 (146). Auto saving is not working for me, do I need to manually enable it? 

I can't find it in the App Settings --> Edit mode.

**Comment by gsantner** [comment]
There is no settings option it is always enabled.

Can you please tell what you mean by "Auto saving is not working for 
me"? Did you type text and it not saves? Did you delete all text and it 
was again there?

**Comment by lamyergeier** [comment]
@gsantner Sorry, for the confusion. You are right.

May I suggest that  "the Save Icon" displayed while editing the document can be removed as auto save is always enabled.

**Comment by MRDGH2821** [comment]
What is the delay between typing a new text & auto saving?

In my old device auto save would happen within a second and the save icon would also fade, indicating that changes are saved. 

But in my new phone, nothing as such happens. I waited for 5 seconds, but the save icon would not fade in colour. 


Package: net.gsantner.markor
Version: v2.15.2 (161)
Flavor: Default (release)
Build date: 2025-10-23T02:34Z
ISource: F-Droid
VCS Hash: f5237bafc3900d40a91c73d75978aac5cdd6b3e9
VCS Msg: Markor v2.15.2

Old:
Android 15 on Nothing phone 1
New: 
Android 16 on Pixel 7
