### ISSUE TITLE
Use system theme by default

### ISSUE THREAD

**Issue by xmha97** [gsantner/markor#1922]
Please use system theme by default:

![Screenshot_2022-11-29-01-14-15-858_net.gsantner.markor.jpg](https://user-images.githubusercontent.com/23485114/204387705-fdf0f81d-465d-4710-8876-e5dd98a0a450.jpg)

**Comment by xmha97** [comment]
If you go to settings and set the theme again, the problem will be solved.
Apparently, the problem is with the default settings.

**Comment by gsantner** [comment]
Please use the Issue Template, thank you!
