### ISSUE TITLE
Horizontal swiping/scrolling in QuickNote is janky

### ISSUE THREAD

**Issue by KLaurence** [gsantner/markor#1923]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. Don't worry; Markor and Mordor appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

When viewing a horizontally-long QuickNote (for example, when there's a long table that doesn't get wrapped by Markor), scrolling to the right of the QuickNote is difficult and janky. Scrolling to the right of the Actions slider at the bottom of the QuickNote is also difficult and janky.

The scrolling conflicts with the "horizontal overscroll" feature that allows the user to swipe through the _Files_, _To-Do_, _QuickNote_, and _More_ tabs.

The expected behavior is for the user to be able to scroll to the ends (left end and right end) of the QuickNote before the app horizontally overscrolls.

<details>
  <summary>Example horizontally-long table</summary>

```
| Colors |
|---|
| #997862 | #1f8653 | #c09374 | #056393 | #8d579a | #77e13d | #e6c8d8 | #98085e | #01c258 | #459f91 | #d562bd | #f8c38a | #b794af | #26e5b7 |
| #5659fe | #f349fd | #594973 | #23c821 | #84d65b | #c9117c | #b75473 | #502c90 | #ebc490 | #2065cd | #ed362c | #e961fc | #d852c7 | #1e2902 |
| #57d485 | #664194 | #5eaf44 | #61fbe6 | #e5c4d1 | #2bf261 | #49699d | #7c9847 | #0f4b53 | #64eda6 | #718496 | #cdddd9 | #09b379 | #2a491d |
```
</details>

### Steps to reproduce

1. In the Edit mode of the QuickNote tab, add a long table. (An example long table is supplied above.)
2. View the QuickNote and try scrolling to the right of the table.

### Information

Android version: 10
App version: 2.10.6

### Source

GitHub Releases

### Format / File type

Not specific

**Comment by gsantner** [comment]
The main screen has horizontal swipe based navigation. That is how it is and might be conflicting what you want to do.

If you want to do painfree horizontal scrolling, please just open the file normally from the file manager. You can find QuickNote.md (or if you specified something else custom), in the file manager as well.

**Comment by harshad1** [comment]
How to reduce this sensitivity: https://stackoverflow.com/a/72067439

I will look into testing this
