### ISSUE TITLE
links to sections in another dokument

### ISSUE THREAD

**Issue by gitgerardo** [gsantner/markor#1924]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. Don't worry; Markor and Mordor appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

I would like to propose a feature: it would nice to have the possibility to right links to sections in another document.
The format of the link should be: `[Link to Section](another_document.md#section)`

Thank you!

### Information

Android version: 13
Device: oneplus 6
App Version: latest , f-droid

### Source

F-Droid

### Format / File type

Markdown

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
> The topic is not already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). (I've searched it).

Please use search! Even without search, it is visible right away on the first page - it was asked recently (#1919), which also was a duplicate.

![grafik](https://user-images.githubusercontent.com/6735650/204811372-dc74eee8-93c7-4beb-8266-15dedad31f84.png)

It not speeds things up or increases priority if its asked every week. Thanks!

**Comment by gitgerardo** [comment]
Ja,sorry!
Die Art Ihrer Antwort zeigt, wie genervt Sie sind.
Schade.

**Comment by gsantner** [comment]
Danke fürs Verständnis!
