### ISSUE TITLE
Markdown settings option - heading syntax

### ISSUE THREAD

**Issue by gohma231** [gsantner/markor#1925]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. Don't worry; Markor and Mordor appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

In Markor, pressing H1 inserts a '#' as per the atx markdown spec. Markor already supports the setext format (==== and ---- for H1 and H2 respectively). 

Can we have an option to have H1 (H2) insert '=====' (----) below a line of text using the setext format?

I'm imagining this would be togglable in Settings/Markdown. A switch that toggles between 'prefer ATX headers' and 'prefer setext headers.'  

Examples of ATX and Setext headers for reference

```
# ATX Heading 1

## ATX Heading 2

Setext Heading 1
================

Setext Heading 2
----------------
```

### Information

Android version: 12
Device: Pixel 5a
App Version: v2.10.6 (142)

### Source

Google Play

### Format / File type

Markdown

**Comment by harshad1** [comment]
Note: We do not currently support parsing setext headers for showing the headings or for changing prefix types etc. It would be non-trivial to do so.

**Comment by gsantner** [comment]
adding to harshad1: (...at syntax higloghting, and on the text action buttons at the bottom bar)

**Comment by harshad1** [comment]
Note: with #1953 Setext headings will be highlighted better. We still don't have an action to add them. (And I don't personally plan to add this as I don't need it)

As a workaround, one can create a snippet with:

```

%%PLACE_CURSOR_HERE%%
====

```

To more quickly insert a H1 setext heading. But this may not be much faster.

**Comment by gohma231** [comment]
I appreciate the workaround idea. My own workaround involves using the Swiftkey editor and pinning a snippet to the clipboard.

I simply pinned '=======================' to the clipboard for easy pasting in switftkey or anywhere else I need a header. It is always two clicks away.

**Comment by gsantner** [comment]
There are many ways to it and it seems there are two good-enough ones :-).

So, closing
