### ISSUE TITLE
"Modify Checkboxes in View Mode" option

### ISSUE THREAD

**Issue by tunbridgep** [gsantner/markor#1926]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. Don't worry; Markor and Mordor appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

I'm glad Markor has support for adding, checking and unchecking checkboxes in edit mode. This is useful for writing documents, however I find it slow and cumbersome to use in certain situations and very clunky when checking/unchecking large numbers of items at once without wanting to edit a list.

For instance. I use the Markor to-do list to store my shopping list (I use markdown for that, not todo.txt, in case that's relevant). While out and about, it's quite difficult to use the bottom buttons to check and uncheck checkboxes. I am very likely to accidentally modify text, especially when I have my phone one-handed (the other hand on my trolley). I want to be able to update/check items off the list, but not MODIFY the list.

Under this proposal, a new setting would be added to the options, "Enable modifying checkboxes in view mode". With this enabled, checkboxes that appear in view mode would be checkable/uncheckable, and the changes would be reflected on the document.

I understand that this is technically contradictory - we are editing a document in view mode, not edit mode, however I feel that checking/unchecking checkboxes is in a strange middle ground between editing and not editing, since we aren't changing any of the information in the document, only marking things as complete.

### Information

Android version: 12
Device: Moto g82 5G
App Version: 2.10.6

### Source

F-Droid

### Format / File type

Not specific

**Comment by gsantner** [comment]
Hello, this has been asked in the past, and the answer has been No. View mode is for viewing.

**Comment by gsantner** [comment]
Hello, this has been asked in the past. Numerous times. And the answer is no. View mode is for viewing.  
And Markor is more than just markdown viewer that also shows checkboxes.

Please check existing discussions.
