### ISSUE TITLE
MD: Update numbered list when inserting in the middle

### ISSUE THREAD

**Issue by contrapunctus-1** [gsantner/markor#193]
Sample text, where | is the cursor -
```
1. Foo|
2. Bar
```
On hitting Enter -
- Current behavior (v0.3.2 from F-Droid)
```
1. Foo
2. |
2. Bar
```

- Preferable behavior -
```
1. Foo
2. |
3. Bar
```

(This was an accidentally-created duplicate of #192, I edited it to report another issue.)

**Comment by frozencemetery** [comment]
Possibly worth noting, most markdown implementations (including Markor's and GitHub's) permit all elements of a numeric list to start with `1. `.  So there's one potentially easy way to resolve this, though it makes the editor slightly less nice :)

**Comment by xuvatilavv** [comment]
Checking this on the current master and the desired behavior already exists. Looks like it was solved with 2b1c4eb88.

**Comment by gsantner** [comment]
ok, closing.

lets reopen, if not works on >=2.4.0
