### ISSUE TITLE
horizontal swipe sensitivity 

### ISSUE THREAD

**Issue by astrigramkeep** [gsantner/markor#1931]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. Don't worry; Markor and Mordor appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

I find swiping within a file a little annoying since markor often mistook vertical swipes to be horizontal swipes and switches to another tab (e.g. quicknotes to to-do). I am sure not everyone experiences this issue, so maybe it would be a good idea to add an option for disabling swiping across tabs if it ends up impossible to reach a consensus on the optimal swipe sensitivity.

### Steps to reproduce

1. Swipe verticallly in any window with your thumb while holding your phone with one hand
2. 
3. 

### Information

Android version: LineageOS 19-20221202-NIGHTLY-beyond1lte
Device: Galaxy S10
App Version: 2.10.6(142)

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
#1923
