### ISSUE TITLE
Custom syntax highlighting

### ISSUE THREAD

**Issue by Hyperlynx2** [gsantner/markor#1938]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. Don't worry; Markor and Mordor appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

I'd really like to be able to customise priority colours for todo.txt highlighting. That way I can match what I use in Vim (rainbow colours, red to dark blue) :D

### Information

Android version: 12
Device: Samsung Galaxy S20 FE 5G
App Version: 2.010.6

### Source

F-Droid

### Format / File type

todo.txt

### Additional info / Log

```shell
-
```

**Comment by harshad1** [comment]
Just FYI, doing custom colors well would take a lot of work.

**Comment by gsantner** [comment]
Not planned. But when you have suggestion for different colors - that work well in light & dark mode alike - happy to try them and merge a merge-request if there is one.
