### ISSUE TITLE
Date&time  presets ++margin editor

### ISSUE THREAD

**Issue by topFun47** [gsantner/markor#1941]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. Don't worry; Markor and Mordor appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

1. Top right of margin 
2. Preset to page option algorithm date/time 
3. Margin width editor method function class

### Information

Android version: 11
Device: DL n/a
App Version: 50 n/a

Phone set to autoclose apps once leaving

Meaning that normally had left apps on standby \\\taking up cache memory

Now apps set to always close.// Rather annoyed. //Can't manage to transition between apps //simultaneously 
Running with. Limit of 2 background processes 

//Giving me extra ram  

//Boosting league mobile game experience 
//It a great phone for 39$

### Source

git master branch

### Format / File type

Markdown

### Additional info / Log

```shell
- 11:00 am eastern time Thursday 
                         Dec 15

Inman, South Carolina
```

**Comment by gsantner** [comment]
spam

**Comment by topFun47** [comment]
This is Spam for you. Not for me

**Comment by gsantner** [comment]
Please write explicit and singular what your issue is and what you want. You talk about game boosting, some money , some margin, some datetime.

**Comment by triplcSloth** [comment]
Tab/folder/AddNew.buttonPress/  Put "userinfo".mk   gets parameters  ListArray[{"file_Page "}.extension] , [{"file_format"}. editor] end 
 
Go to settings +++++++++ oooo... 
+++++++++++++ Template . Oooo....  


\\\Seen them templates before, had already tested them once. 
++Forgotten that they hold the features I wanted.  
++I 'll look through the documentation to see out how to create templates.

++ I did read the iinformative instructions. To search for  first. .

++Only that I didn't know what I was searching for.
++Didn't attemt to try either
+-- wasn't confident in thinking that date+time presets would   bring up search results
++ Thinking this was an original idea.
++ Thinking I would bring value to this . Exe

**** This is not Spam***
This is written innovation made
  simple, fast & efficient ways to reading, 
// createing  _the most  &&  _the best __ ways
 to understanding   the most amount of data.  ++Compiled & compressed into lest amount of written words 
 
++Allowing reading to be an effortless activity. 
**Addtoline30
   One day this will be a valuable skill 
          Where money is lucrative

//Incase of the great resignation 
+++ leaves no one to teach. 

++This is basically proofreading isn't it. 
++Making reading interesting**add to line30
