### ISSUE TITLE
Support declined tasks in markdown task lists

### ISSUE THREAD

**Issue by knolleCC** [gsantner/markor#1944]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. Don't worry; Markor and Mordor appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

Please support **declined tasks** in **markdown task lists** as defined in [todo-md](https://github.com/todo-md/todo-md):

`- [-] This task has been declined`

### Information

App Version: 2.10.6

### Source

F-Droid

### Format / File type

Markdown

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
Please confirm with flexmark-java (https://github.com/vsch/flexmark-java) if this is supported. Also, is this syntax support in ANY common specification like GFM or CommonMark?

Otherwise, not sure whats the benefit of  making anything custom here, as it is anyway not supported anywhere else.

**Comment by knolleCC** [comment]
CommonMark has no task lists. GFM only has open [ ] and done [x] and flexmark only supports GFM tasklists, so no, it is not in any common markdown spec I know of and that's a shame! In my world, not all tasks are "done" someday. Many get declined, because the idea was not that good on second thought or realization not feasible.

However, the Zim-Wiki does support more states of checkboxes which markor does not at the moment, but as I see this is already covered in #1185.

So, you're absolutely on the safe side to decline this request... but wait, is it decline again? 😆

**Comment by gsantner** [comment]
> it is not in any common markdown spec I know of and that's a shame

Sorry to say, but that's then how it is - this is not something supported at Markdown generally, and basically nowhere else thus if it's not in any of the specs all parsers implement. If you need a more sophisticated format, maybe choose i.e. Zim, where the format generally has that baked into syntax. 

> However, the Zim-Wiki does support more states of checkboxes 

Correct the Zim/WikiText format. But not Markdown.

> which markor does not at the moment, but as I see this is already covered in 1185.

When that gets some Zim users attention theres a good chance it's supported yes, by however means. But that's for Zim/Wikitext. Not for Markdown. As HTML checkbox and Markdown checkbox both only support two states it likely means Zim converts it t**at Zim side** to some custom HTML.
