### ISSUE TITLE
Basic Colour Scheme issues

### ISSUE THREAD

**Issue by rancidfrog** [gsantner/markor#1946]
Clicking on Presets do not apply to the colour settings above them.
So user cannot verify if changes were made, nor what the preset colours are:
![](https://i.imgur.com/d0kyOqn.png) 

It does not apply to the following tabs, only when you click on the file from Files tab:
![](https://i.imgur.com/RfcV1uQ.png)

**Comment by gsantner** [comment]
Colors also apply to QuickNote, ToDo tab, as well the view - but you currently need to restart Markor for it to properly apply.
