### ISSUE TITLE
Error when clearing all text in notes then exiting app

### ISSUE THREAD

**Issue by rancidfrog** [gsantner/markor#1947]
I get a pop up error when I clear a note or todo.
![](https://i.imgur.com/3k5t8gM.png)

I was testing for the colours by typing anything, but now if I want to backspace/delete all the text in a todo or quicknote then exit app it gives an error pop up and does not save the empty file, reverting back to the text that I wanted to erase

**Comment by harshad1** [comment]
We do not auto-save files with < 2 chars as this may indicate possible data loss. I recently added code to make the error more clear.

Please use the manual save button.
