### ISSUE TITLE
Markdown edit mode - text visually overwrites lines above with bigger headings enabled

### ISSUE THREAD

**Issue by min7-i** [gsantner/markor#1948]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. Don't worry; Markor and Mordor appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

In markdown files there are certain conditions where text is moved up seemingly overwriting previous lines in the editor view when text is entered and bigger headings are enabled.

For easier understanding I created two screen recordings showing the different behavior with bigger headings enabled & disabled:

**bigger headings enabled**

https://user-images.githubusercontent.com/97251923/211094706-ca80f2c3-b05b-471f-b740-cff04fb69efa.mp4

**bigger headings disabled**

https://user-images.githubusercontent.com/97251923/211094799-1d674528-fb2f-43c8-9c81-382c29ad8cfc.mp4

**Expected behavior**
Existing lines should not be overwritten when entering text.

### Steps to reproduce

1. Enable bigger headings in the settings.
2. Create a new empty markdown file.
3. Paste the following text into the file:
```
Test123
abc

----
Test
----
```
4. Move the cursor behind "Test", press enter (newline) and enter some characters.
5. The text is moved up seemingly overwriting the content of the lines above.
6. Go back into the file overview and then reopen the markdown file.
7. The previously overwritten lines are visible again.

### Information

Android version: 13
Device: Google Pixel 6a
Markor App Version: 2.10.6
Mordor App Version: 2.10.16-1700 (version code 221229) 

### Source

F-Droid

### Format / File type

Markdown

### Additional info / Log

```shell
-
```

**Comment by harshad1** [comment]
I am able to reproduce at lease some of this. Will look into it

**Comment by harshad1** [comment]
So looking into this, the bigger heading highlighting is a bit of a mess.

- when bigger heading are disabled we use a regex which detects only atx headings
- when bigger headings is enabled we use a regex which detects setext headings as well
- The code which decides how big to make a heading can only parse atx heading levels

The simplest solution would be to just drop support for setext headings and fix any bugs in the size code, but  I think lots of people like them.

**Comment by harshad1** [comment]
This has something to do with adjusting fontmetrics as part of a choose height span.

@gsantner IMO we should consider just getting rid of the larger headings feature.

**Comment by gsantner** [comment]
related #1856

**Comment by harshad1** [comment]
@min7-i If you can test with https://github.com/gsantner/markor/actions/runs/3889825977

That would be very helpful. Checking performance with large files is also necessary

**Comment by min7-i** [comment]
Thanks, @harshad1 . With the new build I cannot reproduce the issue anymore :thumbsup:

Regarding performance, what is considered to be a large file in Markor? The largest file I’m actively using in Markor only has 20 KB… I mean, I could create a test file with a certain file size, but I’m not sure if that’s a realistic test case.

**Comment by harshad1** [comment]
In this case large file = lots of larger headers.

I tested this and there is no / very little effect on performance.

Jan 11, 2023 09:06:20 min7-i ***@***.***>:
