### ISSUE TITLE
Don't automatically inject text-theme in export

### ISSUE THREAD

**Issue by 2B1Kenobi** [gsantner/markor#195]
#### General information

* **App version: 0.3.2** 
* **System: Samsung Galaxy Note5** 

#### Description

I had the app in Dark theme. When I tried to print out a PDF, the document is as seen when using Dark theme, with white text on dark gray background.

Can you add an option to have the printout be in black text on white background?

**Comment by gsantner** [comment]
I am more for a op-in for injecting theme into export. By default everything should be exported with white background. `Prefence option: Export text with theme (default: false)`

This is a quite easy task, so a ideal task for beginners. PR's welcome.

**Comment by gsantner** [comment]
PDF/Image export will always use light/white mode starting with next update. As such this is resolved. #594
