### ISSUE TITLE
Add new markdown file will not work at split screen mode

### ISSUE THREAD

**Issue by taiddl** [gsantner/markor#1951]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. Don't worry; Markor and Mordor appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

![Screenshot_20230110_003123_Markor](https://user-images.githubusercontent.com/108560042/211359646-d1509e1a-411f-4e84-bb9f-5918083d14ab.png)

### Steps to reproduce

1. Enter split screen mode with marker on
2. Click "Plus" float button
3. Nothing happened

### Information

Android version: 13
Device: Samsung Tab S7+
App Version: 2.10.7(143)

### Source

GitHub Releases

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
Sure that this is Markor 2.10.7, not 2.10.6? In 2.10.7, the plus button should display with a non-circle shape.

**Comment by shiyishiaa** [comment]
In non-split screen, it worked perfectly.

**Comment by harshad1** [comment]
Does it work after going from split screen back to single screen?

If not, chances are it will be addressed by #1950

**Comment by shiyishiaa** [comment]
> Does it work after going from split screen back to single screen?
> 
> If not, chances are it will be addressed by #1950

Back to single screen will not restore the function. I will try new version later. :) THANKS

**Comment by gsantner** [comment]
Testbuild download <https://github.com/gsantner/markor/actions/runs/3878574318>

**Comment by shiyishiaa** [comment]
![Screenshot_20230112_003807_Mordor](https://user-images.githubusercontent.com/39306140/211863821-a157fbc3-dba2-4c05-8dcc-cc1f9055c62f.png)
Problem get resolved in the nightly version.Thanks for your controbution. <3 @gsantner @harshad1
