### ISSUE TITLE
Markor Android App crashes on Stackedit Welcome file

### ISSUE THREAD

**Issue by raspberrypieman** [gsantner/markor#1958]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. Don't worry; Markor and Mordor appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

I have just downloaded Markor on my Android Samsun A22 mobile phone. I also have Dropbox. I want to view my Dropbox files using Markor.
I also use Stackedit (https://stackedit.io/app#) on my pc.  I decided to export Stackedit's Welcome file as .md to my Dropbox folder and try to view it on my mobile. I can select the "Welcome file.md" file in Dropbox, and I am offered a chance to view it with The Dropbox editor, or Markor. If I choose the Dropbox Text Editor, it works fine, but if I choose Markor it just crashes back to my home page. Just out of interest, I renamed it to a .txt file and Markor was able to display it OK, albeit not in markdown format.

### Steps to reproduce

1. Export Stackedit Welcome file as markdown to Dropbox folder
2. Open Stackedit Welcome file.md in Dropbox
3. Select Markor to view it

### Information

Android version: 13
Device: Samsun A22 5G
App Version: 

### Source

Google Play

### Format / File type

Markdown

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
App version?

Do you know how to create crash logs (adb logcat)? Would br very hepful.

Is that Markdown file somewhat special/unusual?

**Comment by raspberrypieman** [comment]
Markor App version: 2.10.7
No, I do not know how to create crash logs - but you can try to teach me?
No, the Welcom file markdown is not very complex - you can view it on
Stackedit,
but I tried a very simple file as well, with just a two column table using
'|' symbols,
and got the same results.

**Comment by gsantner** [comment]
But when you select/open the/a markdown file at the  Markor filemanager, everything works fine?

**Comment by raspberrypieman** [comment]
If I open markdown files that I have transferred using a usb cable, yes
Markor does not crash, however I do not get the markdown formatting I am
expecting,
but that is another matter.

**Comment by gsantner** [comment]
Here is some information on how to collect log information from a 
device, I've written that together some time ago.

<https://gsantner.net/blog/2018/03/19/android-contribution-guide.html?packageid=net.gsantner.markor>

Otherwise, there are for sure also many other guides and even videos out 
there explaining how to do it :).

**Comment by harshad1** [comment]
I can reproduce this. Will investigate

**Comment by harshad1** [comment]
So this is very strange. I am able to open and edit all sorts of files from dropbox (.py, .txt etc). But .md files cause _dropbox_ to crash. I don't see any issues within markor / mordor. 

I need to get an app to inspect the intent.

**Comment by gsantner** [comment]
@harshad1 Do you have an idea if this still happens in master branch?

@raspberrypieman Can you please check with the Markor development version Marder? you can download here <https://github.com/gsantner/markor/actions/runs/6152028911>

**Comment by harshad1** [comment]
Appears to be resolved (I am pretty sure this was a bug on Dropbox's end)

**Comment by gsantner** [comment]
Great, well then 😄
