### ISSUE TITLE
enhancement request: ability to access files and folders on SD Card

### ISSUE THREAD

**Issue by FBachofner** [gsantner/markor#196]
Markor is great.  Unfortunately it has the same limitation as Writely / Writely Pro, namely it can not access files on an SD Card.

Is this possibly related to issue #115 ?

**Comment by gsantner** [comment]
You can modify the app directory via the app settingd option

**Comment by gsantner** [comment]
Try the latest git version, which will allow to set paths to anywhere.

**Comment by gsantner** [comment]
But yes, it is related to that issue. Markor could need some work on the document browser / and or / file selection dialog or at some maintained compat library. @FBachofner always a good time to start ;).

**Comment by FBachofner** [comment]
@gsantner

Where do I find the "app settingd option"  There doesn't seem to be any such option in the Markor's settings.

In Settings / Main View , I try to select the SD card for the "select storage folder" and the SD card is not shown, only various folders at /storage/emulated/0

The SD card is at /storage/8BD2-141A and Markor does not seem to have any ability to navigate UP from /storage/emulated/0

If I could manually edit a config file, that would be fine, but I can't find the relevant app installation directory.

**Comment by gsantner** [comment]
Exactly that option.

Install git version and tell me if it works then.

Without root permission you can't edit the settings manually.

**Comment by FBachofner** [comment]
> Install git version and tell me if it works then.

Can you please point me to a guide for doing that?  Happy to try this, but while I find directories like: `https://github.com/gsantner/markor/blob/master/app/src/main/java/net/gsantner/markor/ui/FilesystemDialogCreator.java`
which seems to offer the requested feature, there does not seem to be an APK for me to install.

> Without root permission you can't edit the settings manually.

I have root on a number of available devices, so that should not be a problem.  Just can't find the files to edit!

**Comment by gsantner** [comment]
I meant build it from latest git version and install that. As I am release a new version today, just wait for that to be on available where you got it from :smile:  .

**Comment by FBachofner** [comment]
Awesome!  It works and I can now store documents on the SD card.

A **_minor issue_**: when navigating UP from the default document root (i.e. /storage/emulated/0), the first "step" is /storage/emulated which is empty.

Other than the up arrow at the top of the file browser dialog there is no indicator there is the ability to move further up in the tree (many file browsers will use ".." with an upward pointing arrow).

I fear some people will not persist in trying to move further up the tree.  You may wish to add some sort of additional visual indicator.

**Comment by gsantner** [comment]
Complete rework of filesystem view be part of the 1.7.4 release and will be featured in the 1.8 blog post.

It will add options in the toolbar to easy navigate to a writeable path at SdCards.
