### ISSUE TITLE
Erasing file's content due to lack of free space on the device. 

### ISSUE THREAD

**Issue by ThomasLeigh** [gsantner/markor#1960]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. Don't worry; Markor and Mordor appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

I had very small free space and while editing some file I noticed the save icon is not enabled (as if Markor would not notice the file has been changed). Once I switched to other app and then tried to re-open the file in Markor, the file turned out to be completely empty. 

I understand that this is probably due to lack of free space on the device while editing the file. I wonder would it be possible to prevent such issue to happen. It could be a pretty unpleasant surprise. 

### Information

Android version: 10
Device: Xiaomi Redmi Note 7
App Version: 2.10.7 (143)

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by harshad1** [comment]
We have logic that copies the text to clipboard if the save fails. Could you try to reproduce this and check if that happened? (There should have been a message too)

**Comment by gsantner** [comment]
There are said new save dialog. Otherwise guess theres not much doable here, if the disk is full it is full.

**Comment by harshad1** [comment]
Save failures (those that can be cought) will result in the file being copied to the clipboard and a toast is shown. Some failure modes are still silent though.
