### ISSUE TITLE
I want to open the default support view mode through other apps

### ISSUE THREAD

**Issue by web-mobli** [gsantner/markor#1965]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. Don't worry; Markor and Mordor appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

1. When I open the MD file from Nutcloud app or Baidu Netdisk app through Markor
2. This md file is in edit mode by default. I have set the preferred view to view mode, but it has not taken effect. It cannot be modified. The default is view mode
3. I hope it can be opened in view mode without manual switching every time

### Information

Android version: 12
Device: Xiaomi 12S Ultra
App Version: 2.10.6

### Source

Google Play

### Format / File type

Markdown

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
Please check with v2.10.9. I selected a file from another app and chose to open it with Markor - and it showed up in view mode.
