### ISSUE TITLE
.app folder in files tab

### ISSUE THREAD

**Issue by Krazyplays** [gsantner/markor#1966]
# IMPORTANT
* App version: 2.10.7
* Android version/rom: Android 12
* Device: Samsung Galaxy M21
* I accept that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

## Explain the Problem
What problem did you encounter? What did you expect to happen?

The .app folder shows in the files tab. I tried to hide it with the "ignorelist" function (with variations, including "/storage/emulated/0/Documents/markor/.app"), but it didnt work. 

I tried to search for a solution, but no result

## Steps to Reproduce
Explain what you did to encounter the issue

Passive result by using app

## Log
<details>
<summary>Log</summary>

```
Paste log here
```
</details>

**Comment by gsantner** [comment]
There is a dot files checkbox, specifically for dot files, files starting with a dot.

**Comment by harshad1** [comment]
the ignorelist is for excluding files from search
