### ISSUE TITLE
highlight on last visited document

### ISSUE THREAD

**Issue by pussstudio** [gsantner/markor#1967]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. Don't worry; Markor and Mordor appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

1. 
2. 
3. 
if there are so many files on a folder,
when i visited one file right before,
and when i want to click the next file,
I may not remember what the the last visited file is.
so, I want that...
if i visit one file and exit, i want the file to be highlighted with yellow color or other color.

### Information

Android version: no matter
Device: 
App Version: 

### Source

Google Play

### Format / File type

Markdown

### Additional info / Log

```shell
-
```

**Comment by harshad1** [comment]
Markor has a recent files list. It'll be there

**Comment by pussstudio** [comment]
Does Markor have a recent visited files list? where?

**Comment by gsantner** [comment]
folder menu in the top bar

**Comment by pussstudio** [comment]
it doesn't arrange files in accordance with visited time.
so it doesn't help. 
if each file shows the visited time, it may help.

**Comment by harshad1** [comment]
Three lines and sort by date. Imo this was pretty obvious.

**Comment by pussstudio** [comment]
the date means last-changed date. but not last-visited date

**Comment by brunetton** [comment]
Yes I had the same needs. 

For now the workaround is to use search function in files browser that have a search history. Unfortunately this history is limited in time and is cleared after app restart in my case (#1970)

**Comment by gsantner** [comment]
For recent and popular files I see that applying the sort order might not make sense.

The history is stored with order so might be enough to shut off the sorting for these cases.
