### ISSUE TITLE
Filemanager & sync client support

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#197]
When visiting/commenting this issue - you should be coming from Markor's dialog saying that the file cannot be opened. Please tell below some details which system you have and which apps are involved. This issue will be updated with latest available information, please don't report combinations multiple times. You must have Markor v0.3.3 or greater installed to see the mentioned dialog.

**Known working solutions (see dialog):**
* Dropbox official app
* Own/NextCloud
* Seafile
* FolderSync

**Not possible directly:**
* Google Drive official app (files stored in non-public directory, not changeable, doesn't add any name or file info)
  * Maybe sync files using FolderSync app instead

**Impossible:**  
* Files GO - Impossible to get other file info than it's contents

**Comment by de-es** [comment]
Android 7.1.2 / Lineage 14.1
Markor 0.3.6
Seafile Client 2.2.3 https://f-droid.org/packages/com.seafile.seadroid2/

Synced files are stored in 
`/storage/emulated/0/Seafile/mailaddress@mymaildomain.com (myseafileserver.com)`

You can only access/open the files within Seafile if they are already downloaded/synced.

**Comment by gsantner** [comment]
When you do click on a file -> open with - does markor appear? If yes, are you willing to provide me some additional information then (will write it together)

**Comment by de-es** [comment]
Yes and yes. :+1:

**Comment by gsantner** [comment]
Install <https://github.com/intrications/intent-intercept>, do the open with and select intercept. click on top-copy clipboard, and paste me that here. you can uninstall after

**Comment by gsantner** [comment]
Install hhttps://github.com/k3b/intent-intercept, do the open with and select intercept. click on top-copy clipboard, and paste me that here. you can uninstall after

**Comment by gsantner** [comment]
Install https://github.com/k3b/intent-intercept, do the open with and select intercept. click on top-copy clipboard, and paste me that here. you can uninstall after

**Comment by de-es** [comment]
```
intent://com.seafile.seadroid2.provider/name/storage/emulated/0/Seafile/mobile%40mymaildomain.com%20(myseafileserver.com)/Linux/tar.md#Intent;scheme=content;action=android.intent.action.EDIT;type=text/plain;launchFlags=0x3000000;end 
------------ 
ACTION: android.intent.action.EDIT 
DATA: content://com.seafile.seadroid2.provider/name/storage/emulated/0/Seafile/mobile%40mymaildomain.com%20(myseafileserver.com)/Linux/tar.md 
MIME: text/plain 
URI: intent://com.seafile.seadroid2.provider/name/storage/emulated/0/Seafile/mobile%40mymaildomain.com%20(myseafileserver.com)/Linux/tar.md#Intent;scheme=content;action=android.intent.action.EDIT;type=text/plain;launchFlags=0x3000000;end 
FLAGS: 
FLAG_ACTIVITY_FORWARD_RESULT 
FLAG_ACTIVITY_PREVIOUS_IS_TOP 

------------ 
AUFRUFBARE ACTIVITIES 
keine 
```

**Comment by gsantner** [comment]
looks very doable.

**Comment by gsantner** [comment]
@de-es is it always `com.seafile.seadroid2.provider/name/storage/` or did you replace something by name? what can i expect there

**Comment by de-es** [comment]
It is always the same word `name`, I didn't replace anything here. The full path on my internal storage would be `Seafile/mobile@mymaildomain.com (myseafileserver.com)/Linux/tar.md`. The space between email address and server name is intended.

**Comment by gsantner** [comment]
ok. are there other apps with quite same packagenames (ala pro,plus,light,gplay)?

**Comment by de-es** [comment]
Thank you. I will report back after the next release.

**Comment by indeedwatson** [comment]
I followed the instructions regarding Dropbox, and I can edit dropbox files, but the files that I create in the dropbox folder via markor do not get read and uploaded by dropbox.

Is this a known limitation or am I doing something wrong?

**Comment by gsantner** [comment]
I don't have an Dropbox account, the app or like that, maybe other users can help you on Forum on how Dropbox app works. Markor does the editing stuff. but does not implement syncing, or control sync features of other apps (and won't do).

**Comment by rainbyte** [comment]
Yeah, that's what I was looking for, I just wanted to save my notes in a folder (like a normal person) and share them easily, without making accounts on 3rd party sites or things like that.

**Comment by jakejoh** [comment]
what is meant by "Known working solutions (**see dialog**)"?

Is this how sync with Nextcloud is supposed to work?:
- set Markor and Nextclouds storage locations to the same folder
- sync the folder that contains the notes with Nextcloud
- have the notes synced on Nextcloud

For some reason, Nextcloud (3.2.0) isn't detecting files created by Markor.
Am I missing something there?

**Comment by gsantner** [comment]
You have to mark files as offline-available / always in sync. this has to be done on per file basis. new files never are synced, thats how their app works.
look at their bugtracker, I think there are bugreports.
Otherwise, you too can open files from nextcloud app.

**Comment by duckbrain** [comment]
I use tasker to generate a template file and open it in Markor. This stopped working a little while back. Tasker sends an intent like the following.

```
intent://net.dinglisch.android.taskerm.fileprovider/Others/Documents/church/church-2018-08-19.md#Intent;scheme=content;category=android.intent.category.DEFAULT;type=text/*;launchFlags=0x33000004;end 
------------ 
ACTION: android.intent.action.VIEW 
DATA: content://net.dinglisch.android.taskerm.fileprovider/Others/Documents/church/church-2018-08-19.md 
MIME: text/* 
URI: intent://net.dinglisch.android.taskerm.fileprovider/Others/Documents/church/church-2018-08-19.md#Intent;scheme=content;category=android.intent.category.DEFAULT;type=text/*;launchFlags=0x33000004;end 
CATEGORY: 
android.intent.category.DEFAULT 
FLAGS: 
FLAG_RECEIVER_REPLACE_PENDING 
FLAG_RECEIVER_FOREGROUND 
FLAG_ACTIVITY_FORWARD_RESULT 
FLAG_ACTIVITY_PREVIOUS_IS_TOP 
FLAG_FROM_BACKGROUND 

------------ 
MATCHING ACTIVITIES: 
Contacts (com.android.contacts - com.android.contacts.vcard.ImportVCardActivity) 
HTML Viewer (com.android.htmlviewer - com.android.htmlviewer.HTMLViewerActivity) 
Text Reader (com.amaze.filemanager - com.amaze.filemanager.activities.TextReader) 
Calendar (com.google.android.calendar - com.google.android.calendar.ICalLauncher) 
Markor (net.gsantner.markor - net.gsantner.markor.activity.DocumentActivity) 
Bromite (org.bromite.bromite - com.google.android.apps.chrome.IntentDispatcher) 
Decrypt (org.sufficientlysecure.keychain - org.sufficientlysecure.keychain.ui.DecryptActivity) 
Import Keys (org.sufficientlysecure.keychain - org.sufficientlysecure.keychain.ui.ImportKeysActivity) 
```

Using Intent Intercepter, i could modify it to a `file://` URI, which worked. I tried crafting an intent myself, but it seems to modify like this it on the way out.

**Comment by gsantner** [comment]
whats the real path where "Others/Documents" starts?

**Comment by duckbrain** [comment]
`/storage/emulated/0/Documents` or `/sdcard/Documents`

**Comment by gsantner** [comment]
Do you self assign /Others/? And why like that, and not /sdcard/ e.g.?

**Comment by dugite-code** [comment]
@duckbrain in tasker I use the send intent action to get around this:

```
A1: Variable Set [
    Name: %uri
    To: content://net.dinglisch.android.taskerm.fileprovider/storage/emulated/0/Markor/Food%20Diary/%date3/%date2/%date1.md
    Recurse Variables:  Off
    Do Maths: Off
    Append: Off ] 

A2: Send Intent [
    Action: android.intent.action.EDIT
    Cat:  Default
    Mime Type:  text/plain
    Data: %uri
    Extra:
    Extra:
    Extra:
    Package:
    Class:
    Target: Activity ] 
```

@gsantner I used to get the `/Others/` directory as well now I see `/external_files/` and I'm not sure what causes that to change

**Comment by duckbrain** [comment]
Thanks @dugite-code, that works!

I tried using the send intent, but with `file://%filename` instead of `content://net.dinglisch.android.taskerm.fileprovider%filename`, and Tasker would rewrite it to the Open file actions behavior.

**Comment by sjkiss** [comment]
Microsoft onedrive exchange android

**Comment by m52go** [comment]
Hi @gsantner, absolutely amazing app. I just ran into this issue. I'm trying to get Markdor to open a `.md` file with an absolute path through an app that's not a file explorer.

Basically I'm generating a new `.md` file in my app, and then want to immediately open it in Markdor to edit it.

Just FYI...not deal-breaking for me, but thought you should know. It looks like the focus here is on file managers.

**Comment by clach04** [comment]
Mgit 1.5.5.1 https://play.google.com/store/apps/details?id=com.manichord.mgit&hl=en_US  report

intent://com.manichord.mgit.fileprovider/external/Android/data/com.manichord.mgit/files/repo/passogva/README.md#Intent;scheme=content;action=android.intent.action.EDIT;type=text/plain;launchFlags=0x3000003;end 
------------ 
ACTION: android.intent.action.EDIT 
DATA: content://com.manichord.mgit.fileprovider/external/Android/data/com.manichord.mgit/files/repo/passogva/README.md 
MIME: text/plain 
URI: intent://com.manichord.mgit.fileprovider/external/Android/data/com.manichord.mgit/files/repo/passogva/README.md#Intent;scheme=content;action=android.intent.action.EDIT;type=text/plain;launchFlags=0x3000003;end 
FLAGS: 
FLAG_ACTIVITY_FORWARD_RESULT 
FLAG_GRANT_READ_URI_PERMISSION 
FLAG_ACTIVITY_PREVIOUS_IS_TOP 
FLAG_GRANT_WRITE_URI_PERMISSION 

------------ 
MATCHING ACTIVITIES: 
Markor (net.gsantner.markor - net.gsantner.markor.activity.DocumentActivity) 
ES Note Editor (com.estrongs.android.pop - com.estrongs.android.pop.app.editor.PopNoteEditor) 
Diary (org.billthefarmer.diary - org.billthefarmer.diary.Editor)

**Comment by clach04** [comment]
I had success with version  1.36 (and 1.34) of https://github.com/billthefarmer/editor :)

**Comment by gsantner** [comment]
@m52go:

> Hi @gsantner, absolutely amazing app. I just ran into this issue. I'm trying to get Markdor to open a .md file with an absolute path through an app that's not a file explorer.

Add the `real_file_path_2` string extra to intent for editor activity, set the absolute filepath there, thats all you need :wink: .

**Comment by gsantner** [comment]
@clach04 : Mgit (and potential some others) are support with next update
@dugite-code / @duckbrain : You can also use the `real_file_path_2` approach above

**Comment by linsui** [comment]
```
intent://com.android.externalstorage.documents/document/home%3Amarkor%2FQuickNote.md#Intent;scheme=content;type=application/octet-stream;launchFlags=0x3000000;end 
------------ 
ACTION: android.intent.action.VIEW 
DATA: content://com.android.externalstorage.documents/document/home%3Amarkor%2FQuickNote.md 
MIME: application/octet-stream 
URI: intent://com.android.externalstorage.documents/document/home%3Amarkor%2FQuickNote.md#Intent;scheme=content;type=application/octet-stream;launchFlags=0x3000000;end 
FLAGS: 
FLAG_ACTIVITY_FORWARD_RESULT 
FLAG_ACTIVITY_PREVIOUS_IS_TOP 
```

I open QuickNote.md in markor directory with stock file manager on Android 9 and failed. I can always open these file in Markor but not in file manager.

**Comment by gsantner** [comment]
@linsui can you please edit/update comment and add real/absolute filepath where the saif file is really stored?

**Comment by sys9kdr** [comment]
@indeedwatson https://github.com/gsantner/markor/issues/197#issuecomment-389385149

> I followed the instructions regarding Dropbox, and I can edit dropbox files, but the files that I create in the dropbox folder via markor do not get read and uploaded by dropbox.
> 
> Is this a known limitation or am I doing something wrong?

With following the guide about dropbox, you can edit existing files only  but can't create new files recognized by dropbox app. I think current guide about dropbox cause confusing. 

I use [AutoSync for Dropbox](https://play.google.com/store/apps/details?id=com.ttxapps.dropsync
) to sync markor/dropbox. It works fine.

**Comment by gsantner** [comment]
Dropbox: Also suggest to use AutoSync or FolderSync app.

As of new files, when using none of the apps above and only the official Dropbox apo: Yeah you need to create/upload the initial version yourself inside dropbox app.

**Comment by clach04** [comment]
@gsantner 
Quick test https://github.com/gsantner/markor/releases/tag/v1.8.2 and Mgit successful :+1

**Comment by kpm** [comment]
Doesn't open an existing file in dropbox for android, v148.2.2.  I have made the file available offline.

**Comment by proofy** [comment]
Microsoft OneDrive Version 5.3.6.3
Markor Version 2.0.4
Android 7.0

    intent://com.microsoft.skydrive.content.external/Drive/ID/1/Item/RID/https%3A%2F%2Fcompany-my.sharepoint.de%2Fpersonal%2Fs_name_domain_de%2F_api%213f7066ec-6e8b-4b6b-983e-c33127059c5c/Stream/1/Property/QuickNote.md#Intent;scheme=content;type=application/octet-stream;launchFlags=0x3000000;end 
    ------------ 
    ACTION: android.intent.action.VIEW 
    DATA: content://com.microsoft.skydrive.content.external/Drive/ID/1/Item/RID/https%3A%2F%2Fcompany-my.sharepoint.de%2Fpersonal%2Fs_name_domain_de%2F_api%213f7066ec-6e8b-4b6b-983e-c33127059c5c/Stream/1/Property/QuickNote.md 
    MIME: application/octet-stream 
    URI: intent://com.microsoft.skydrive.content.external/Drive/ID/1/Item/RID/https%3A%2F%2Fcompany-my.sharepoint.de%2Fpersonal%2Fs_name_domain_de%2F_api%213f7066ec-6e8b-4b6b-983e-c33127059c5c/Stream/1/Property/QuickNote.md#Intent;scheme=content;type=application/octet-stream;launchFlags=0x3000000;end 
    FLAGS: 
    FLAG_ACTIVITY_FORWARD_RESULT 
    FLAG_ACTIVITY_PREVIOUS_IS_TOP 

    ------------ 
    onActivityResult: 
    resultCode: 0

**Comment by proofy** [comment]
Microsoft OneDrive Version 5.3.6.3
Markor Version 2.0.4
Android 7.0

    intent://com.microsoft.skydrive.content.external/Drive/ID/1/Item/RID/https%3A%2F%2Fcompany-my.sharepoint.de%2Fpersonal%2Fs_name_domain_de%2F_api%213f7066ec-a1b2-4b6b-983e-c33127059c5c/Stream/1/Property/QuickNote.md#Intent;scheme=content;type=application/octet-stream;launchFlags=0x3000000;end 
    ------------ 
    ACTION: android.intent.action.VIEW 
    DATA: content://com.microsoft.skydrive.content.external/Drive/ID/1/Item/RID/https%3A%2F%2Fcompany-my.sharepoint.de%2Fpersonal%2Fs_name_domain_de%2F_api%213f7066ec-a1b2-4b6b-983e-c33127059c5c/Stream/1/Property/QuickNote.md 
    MIME: application/octet-stream 
    URI: intent://com.microsoft.skydrive.content.external/Drive/ID/1/Item/RID/https%3A%2F%2Fcompany-my.sharepoint.de%2Fpersonal%2Fs_name_domain_de%2F_api%213f7066ec-a1b2-4b6b-983e-c33127059c5c/Stream/1/Property/QuickNote.md#Intent;scheme=content;type=application/octet-stream;launchFlags=0x3000000;end 
    FLAGS: 
    FLAG_ACTIVITY_FORWARD_RESULT 
    FLAG_ACTIVITY_PREVIOUS_IS_TOP 

    ------------ 
    onActivityResult: 
    resultCode: 0

**Comment by smnthermes** [comment]
@gsantner it should at least be able to read the file

Android 9 (LineageOS)
Telegram
Markor 2.1.6

**Comment by alystair** [comment]
OneDrive support not possible?

**Comment by ibnishak** [comment]
Android 10

Mixplorer
Termux

**Comment by gsantner** [comment]
> OneDrive support not possible?  

As in Markor syncs itself? Nope.

**Comment by PhilT** [comment]
Android 10
Sync.com - todo.txt file is marked for sync offline
Markor v2.2.10 (113)

Shout if you need any more info. Thanks.

**Comment by sudomain** [comment]
@ibnishak can you provide more details? From Markor are you able to open files contained in the Termux private storage (`/data/data/com.termux/files/`)? Currently I keep my files in shared storage and create symlinks to it in my Termux $HOME. 
Theoretically it should be possible for Markor to access files in $HOME using the contentprovider, but I haven't gotten it working. I say this because my KeePassDX app is able access my `keepass.kdbx` file in $HOME using 

`content://com.termux.documents/document//data/data/com.termux/files/home/keepass.kbdx`

**Comment by kkuhle** [comment]
+1

Android 10

Mixplorer
Termux

**Comment by cauerego** [comment]
android 11 will limit storage access even further, and termux will probably only be accessible through FTP or the private storage as mentioned by @sudomain 

this is already an issue in my case, android 11 beta.

granted, it's a common issue among most apps. very few do offer this kind of storage access.

**Comment by gsantner** [comment]
Well, basically Android 11 kills the file access freedom at Android, thats the sad but real state.

Markor gonna be limited to its private storage only then.

**Comment by cauerego** [comment]
for instance, Material Files (Open source Material Design file manager) - https://f-droid.org/packages/me.zhanghai.android.files can access termux and any other private storage that is opened for such, along with the public storage, still useful for general files and some apps still have access to it.

**Comment by Wikunia** [comment]
DS File (Synology Disk Station App)
Latest version of Android (10) on Pixel 3 and latest version of the App. Would love to be able to edit my synced markdown files this way.

**Comment by jamescridland** [comment]
I just clicked a Markdown file in Gmail, and got this message.

Pixel 3a, latest production Android 11.

**Comment by Jaaaarne** [comment]
I'm receiving this message when trying to open a Markdown file stored inside of a TrueCrypt container, which I open on Android with EDS Lite app. Device runs Android 10. The container is not mounted, strictly speaking. The app uses a temp directory, inside which it creates a couple of more directories, inside which the unencrypted file is placed. After closing the container, the app deletes them. 

I tried pointing Markor to the permanent "base" temp directory to make it Markor's working directory. Still not working. At the same time, the built-in text editor in the file manager is able to open those files in the container and save changes to them. Also if I manually navigate to said temp directory, everything opens fine, files can be edited and changes are saved.

I understand it's not quite the sync issue, but still. Is there a workaround, except opening the decrypted file directly from the EDS temp directory?

**Comment by whispy** [comment]
Tried on Android 8.1.0, 9, 10
Dropbox Android App

Dropbox recently changed the method they use to store offline files. Previously, they stored offline files in `Android/data/com.dropbox.android/`. Since the change, they now store them in:
`/data/data/com.dropbox.android/files/user_data/files/u123456/scratch/`.

Markor appears to be unable to navigate to this folder. When trying to Open As a .md file from this folder in Markor, I got the error that led me here.

Any suggestions?

**Comment by gsantner** [comment]
> Any suggestions?

FolderSync

**Comment by cauerego** [comment]
or drop the box and get a host which you can use syncthing, if you're geek enough.

**Comment by TonSilver** [comment]
EDS Lite & EDS: https://play.google.com/store/apps/details?id=com.sovworks.edslite

Getting the message on OnePlus 5 OxygenOS 9.0.10.

P.S. At the same time Total Commander's editor words perfect.

**Comment by boulderob** [comment]
> Tried on Android 8.1.0, 9, 10
> Dropbox Android App
> 
> Dropbox recently changed the method they use to store offline files. Previously, they stored offline files in `Android/data/com.dropbox.android/`. Since the change, they now store them in:
> `/data/data/com.dropbox.android/files/user_data/files/u123456/scratch/`.
> 
> Markor appears to be unable to navigate to this folder. When trying to Open As a .md file from this folder in Markor, I got the error that led me here.
> 
> Any suggestions?

I've got the same exact path problem described above and here https://github.com/gsantner/markor/issues/197#issuecomment-778932694.   

I've got a samsung A7 tablet purchased in dec 2020 that has latest android OS update and latest dropbox app.  Dropbox is pretty ubiquitous.  Is it not possible to just adjust / update the DB path in markor or better yet, allow us to configure it since it may change in the future? That leaves the configuration to the user and makes your life easier.  It's just a path.  Perhaps there can be a default path with user override?

i know there are workarounds but the reason they're called workarounds is because they're workarounds ;)  DB is already capable of synching the files with it's own very robust app that just works.  Markor just needs that path to be updated or configurable.  introducing one or two other apps into the equation to achieve the same existing functionality is sort of "complexifying" an already viable and ubiquitous DB solution.   

Regardless thanks for the work on the app!  I'll hopefully be putting it through it's paces in the coming month once i can get some of my files on my A7!

**Comment by TonSilver** [comment]
`intent://com.sovworks.eds.android.providers.main/content/ZW5jZnM6L251YnMvZHJvcGJveC9jb2RkZXZpbGwvd2Fkcy9zaGFyZS9wZXBwZXJ6L01rUHBNYzZRcW1JZ1d4N1h4bEVJNXpzMD9sb2NhdGlvbj0lMkZzdG9yYWdlJTJGZW11bGF0ZWQlMkYwJTJGbnVicyUyRmRyb3Bib3glMkZjb2RkZXZpbGwlMkZ3YWRzJTJGc2hhcmUlMkZwZXBwZXJ6#Intent;scheme=content;type=text/plain;launchFlags=0x13000000;end 
------------ 
ACTION: android.intent.action.VIEW 
DATA: content://com.sovworks.eds.android.providers.main/content/ZW5jZnM6L251YnMvZHJvcGJveC9jb2RkZXZpbGwvd2Fkcy9zaGFyZS9wZXBwZXJ6L01rUHBNYzZRcW1JZ1d4N1h4bEVJNXpzMD9sb2NhdGlvbj0lMkZzdG9yYWdlJTJGZW11bGF0ZWQlMkYwJTJGbnVicyUyRmRyb3Bib3glMkZjb2RkZXZpbGwlMkZ3YWRzJTJGc2hhcmUlMkZwZXBwZXJ6 
MIME: text/plain 
URI: intent://com.sovworks.eds.android.providers.main/content/ZW5jZnM6L251YnMvZHJvcGJveC9jb2RkZXZpbGwvd2Fkcy9zaGFyZS9wZXBwZXJ6L01rUHBNYzZRcW1JZ1d4N1h4bEVJNXpzMD9sb2NhdGlvbj0lMkZzdG9yYWdlJTJGZW11bGF0ZWQlMkYwJTJGbnVicyUyRmRyb3Bib3glMkZjb2RkZXZpbGwlMkZ3YWRzJTJGc2hhcmUlMkZwZXBwZXJ6#Intent;scheme=content;type=text/plain;launchFlags=0x13000000;end 
FLAGS: 
FLAG_RECEIVER_FOREGROUND 
FLAG_ACTIVITY_FORWARD_RESULT 
FLAG_ACTIVITY_PREVIOUS_IS_TOP 

------------ 
MATCHING ACTIVITIES: 
Chrome (com.android.chrome - com.google.android.apps.chrome.IntentDispatcher) 
HTML Viewer (com.android.htmlviewer - com.android.htmlviewer.HTMLViewerActivity) 
Totalcmd-Editor (com.ghisler.android.TotalCommander - com.ghisler.android.TotalCommander.TCEditActivity) 
Book Reader (com.github.axet.bookreader - com.github.axet.bookreader.activities.MainActivity) 
Docs (com.google.android.apps.docs.editors.docs - com.google.android.apps.docs.editors.kix.conversion.KixOnlineImportActivity) 
Markor (net.gsantner.markor - net.gsantner.markor.activity.DocumentActivity) 
Mordor (net.gsantner.markor_test - net.gsantner.markor.activity.DocumentActivity) 
IceCatMobile (org.gnu.icecat - org.gnu.icecat.App) 
KOReader (org.koreader.launcher - org.koreader.launcher.MainActivity) 
`

**Comment by Civilian-No-001** [comment]
Android 11
mixplorer
all paths(local)
markor 2.6.0 fdroid

**Comment by c0dd3vi11** [comment]
Tried to open file from EDS (lite version available here: https://play.google.com/store/apps/details?id=com.sovworks.edslite ) in Markor. Got in-app alert.

Intent info (by intent-interceptor):
```
intent://com.sovworks.eds.android.providers.main/content/ZW5jZnM6L251YnMvZHJvcGJveC9jb2RkZXZpbGwvd2Fkcy9zaGFyZS9wZXBwZXJ6L01rUHBNYzZRcW1JZ1d4N1h4bEVJNXpzMD9sb2NhdGlvbj0lMkZzdG9yYWdlJTJGZW11bGF0ZWQlMkYwJTJGbnVicyUyRmRyb3Bib3glMkZjb2RkZXZpbGwlMkZ3YWRzJTJGc2hhcmUlMkZwZXBwZXJ6#Intent;scheme=content;type=text/plain;launchFlags=0x13000000;end
ACTION: android.intent.action.VIEW
DATA: content://com.sovworks.eds.android.providers.main/content/ZW5jZnM6L251YnMvZHJvcGJveC9jb2RkZXZpbGwvd2Fkcy9zaGFyZS9wZXBwZXJ6L01rUHBNYzZRcW1JZ1d4N1h4bEVJNXpzMD9sb2NhdGlvbj0lMkZzdG9yYWdlJTJGZW11bGF0ZWQlMkYwJTJGbnVicyUyRmRyb3Bib3glMkZjb2RkZXZpbGwlMkZ3YWRzJTJGc2hhcmUlMkZwZXBwZXJ6
MIME: text/plain
URI: intent://com.sovworks.eds.android.providers.main/content/ZW5jZnM6L251YnMvZHJvcGJveC9jb2RkZXZpbGwvd2Fkcy9zaGFyZS9wZXBwZXJ6L01rUHBNYzZRcW1JZ1d4N1h4bEVJNXpzMD9sb2NhdGlvbj0lMkZzdG9yYWdlJTJGZW11bGF0ZWQlMkYwJTJGbnVicyUyRmRyb3Bib3glMkZjb2RkZXZpbGwlMkZ3YWRzJTJGc2hhcmUlMkZwZXBwZXJ6#Intent;scheme=content;type=text/plain;launchFlags=0x13000000;end
FLAGS:
FLAG_RECEIVER_FOREGROUND
FLAG_ACTIVITY_FORWARD_RESULT
FLAG_ACTIVITY_PREVIOUS_IS_TOP

MATCHING ACTIVITIES:
Chrome (com.android.chrome - com.google.android.apps.chrome.IntentDispatcher)
Totalcmd-Editor (com.ghisler.android.TotalCommander - com.ghisler.android.TotalCommander.TCEditActivity)
Markor (net.gsantner.markor - net.gsantner.markor.activity.DocumentActivity)
Mordor (net.gsantner.markor_test - net.gsantner.markor.activity.DocumentActivity)
```

**Is it possible to make Markor works with EDS' content provider?**
