### ISSUE TITLE
Add history for file search queries

### ISSUE THREAD

**Issue by brunetton** [gsantner/markor#1970]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. Don't worry; Markor and Mordor appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

I use file searching a LOT to quickly open files, as I remember their names more than their location. I'd love to have a "permanent" search history.

### Steps to reproduce

1. open files list
2. open file search
3. search for a file name
4. open corresponding file
5. come back to file list
6. open file search

=> the searched terms are present in the search history

7. kill the app
8. restart the app
9. open files list
10. open file search

=> no search history

### Information

Android version: 12
Device: Huawei P30 Lite / MAR-LX1A
App Version: 2.10.7

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
I wasn't able to test the dev version as it crashes as soon as I launch it :(
```

**Comment by gsantner** [comment]
I don't plan or see the need to cache or build any saving for search results. Search results are something to be displayed at the time of finding and the next time you search theres a good chance it's not there anymore, or there are new results.


If you have some files you open very often, I suggest to create a kind of link list/index document that links other files.

Generally I would not know any other filemanager, document browser, git issues searcher or whatever that would do search result storing.

**Comment by brunetton** [comment]
> I don't plan or see the need to cache or build any saving for search results. Search results are something to be displayed at the time of finding and the next time you search theres a good chance it's not there anymore, or there are new results.
> 

Of course. But the issue is not about caching search *results*, but search **terms**; like web browsers remembers last searched terms in address bar.

It would be probably more clear with image: here in orange the terms I'd expect to be cached:

![Screenshot_20230206_184418](https://user-images.githubusercontent.com/86322/217046596-6eeaca1f-b60d-4137-b274-fdd5bfd7ff41.jpg)


Hope this makes sense now

> If you have some files you open very often, I suggest to create a kind of link list/index document that links other files.

Yes this is already the case. I personaly use home screen links; but this issue is not related to this use case.

> Generally I would not know any other filemanager, document browser, git issues searcher or whatever that would do search result storing.

I totally agree. But I wasn't the subject of this issue

> I know you would like this and it would make it easier for you, but it unnecassary makes things complex and bloat.

**Comment by gsantner** [comment]
OK so you really only care about the **search queries**, not the results?

**Comment by brunetton** [comment]
> => the searched terms are present in the search history

Yes indeed :) I'm not a native English guy so I probably wasn't clear. But I wrote "search for a file name" and "=> the searched terms are present in the search history"

Anyway, do we repoen the issue ?

**Comment by brunetton** [comment]
You're of course free to reword the issue to make it more clear !

**Comment by harshad1** [comment]
In #1981 I have made the recent files list default to the most recently used (i.e. the saved) order

**Comment by brunetton** [comment]
> In #1981 I have made the recent files list default to the most recently used (i.e. the saved) order

Sounds great ! But I really do not understand anything on the purpose of this branch 🤔 The name "Much simpler permissions". The branch name does not suggest that it is about that; and I didn't see any commit that sounds in connexion with that subject. Is it "Many fixes and changes" ? "Many tweaks and changes" ? 

Anyway, I can't wait to see it merged and use it ! Thanks

**Comment by harshad1** [comment]
This is a side project for me. I don't really try to keep my branches and commits very clean (perhaps some improvement is needed here).

The change is in the `loadFolder` method in the File adapter class

Feb 22, 2023 11:43:58 Bruno Duyé ***@***.***>:

**Comment by harshad1** [comment]
Here, for reference:

https://github.com/gsantner/markor/pull/1981/files#diff-b8854a3c43757eac61b3776209726c2d019c07ab3dc60b2d2c4bf3f79a935762R563

**Comment by gsantner** [comment]
Recent  files are not additionally sorted anymore now with #1981

**Comment by gsantner** [comment]
Recent  files are not additionally sorted anymore now with #1981 . Though this is about file open history. Not about the search query.

**Comment by gsantner** [comment]
Markor v2.10.8 <https://github.com/gsantner/markor/releases/tag/v2.10.8> shows recent search queries, dropdown select to fill input.
