### ISSUE TITLE
View mode - make links/urls copyable (long press -> copy)

### ISSUE THREAD

**Issue by brunetton** [gsantner/markor#1972]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [ ] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. Don't worry; Markor and Mordor appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

I'd like to be able to copy links in view mode (Markdown). As in browsers, I'd except a long press on a link should copy link.

## Steps to reproduce
- open/create a markdown document
- add an URL onto the document (example: https://f-droid.org/fr/packages/net.gsantner.markor)
- switch to view mode
- try to copy the link, it's not possible

## Workaround

I installed and set [Link Eye](https://f-droid.org/en/packages/kuesji.link_eye.fdroid) as default browser so I can use it to copy links. However it doesn't works for links that are handled by specifics apps, typically Facebook, Youtube, Google Play store links. I often need to copy/paste Youtube URLs and it's a quite complex process (open the video in Youtube app; that loads a quite lot amount of data; I need to be connected to the internet, otherwise it doesn't works. Of course I could swap to edit mode and search for my link but this is a long process for long notes !

### Information

Android version: 12
Device: Huawei P30 Lite / MAR-LX1A
App Version: 2.10.7

### Source

F-Droid

### Format / File type

Markdown

### Additional info / Log

```shell
I wasn't able to test the dev version as it crashes as soon as I launch it :(
```

**Comment by gsantner** [comment]
Duplicate #1788

**Comment by brunetton** [comment]
> Duplicate #1788

Oh so sorry :s I did searched for it !
