### ISSUE TITLE
Add a way to list recently **opened** files

### ISSUE THREAD

**Issue by brunetton** [gsantner/markor#1973]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. Don't worry; Markor and Mordor appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

I need a way to see the last files I've **opened** (ie viewed, not only edited).

## Considered workarounds

- use search history, but this history is cleared on app restarts (#1970)
- use recent files panel, sorted by date, but as stated in [this comment](https://github.com/gsantner/markor/issues/1967#issuecomment-1417991378) the dates corresponds to last **edited** dates, not last **opened**

### Information

Android version: 12
Device: Huawei P30 Lite / MAR-LX1A
App Version: 2.10.7

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
I wasn't able to test the dev version as it crashes as soon as I launch it :(
```

**Comment by gsantner** [comment]
Please don't mass open issues, thank you :-D.

There is a ongoing discussion at #1967 about the existing recents.

**Comment by brunetton** [comment]
> Please don't mass open issues, thank you :-D.
> 
> There is a ongoing discussion at #1967 about the existing recents.

Yes I read this issue, but the other issue is focused on "i want the file to be highlighted with yellow color or other color"

This issue here is more generic, the idea was to search for an answer (whatever it is, I personalty think the color is a good answer) to the question: how to quickly access recently opened documents ?

Thanks
