### ISSUE TITLE
Turn of swipe

### ISSUE THREAD

**Issue by shockergit** [gsantner/markor#1975]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. Don't worry; Markor and Mordor appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

1. 
2. 
3. 

### Information

Android version: 13
Device: S22
App Version: latest

### Source

Google Play

### Format / File type

Plaintext

### Additional info / Log

```shell
Please add an option to turn off swipe to change tab in markor.
```

**Comment by harshad1** [comment]
I recently added logic to decrease the sensitivity of the swipe to change tabs. Not sure if it has been released yet.

**Comment by shockergit** [comment]
can you add a turn on/off swith it would have been great

**Comment by gsantner** [comment]
As harshad1 mentioned the sensitivity of the swipe is or was a bit reduced. And I don't want to add a settings option here, not every small bit is supposed to be tunable.

**Comment by mariomadproductions** [comment]
@gsantner I'd also like this option, if another vote makes a difference.

**Comment by gsantner** [comment]
In the upcoming release it will be a bit less sensitive as mentioned. It's not out yet. But no settings option bloat added.
