### ISSUE TITLE
Cannot create new note

### ISSUE THREAD

**Issue by km53** [gsantner/markor#1976]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. Don't worry; Markor and Mordor appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

I cannot create a new note.  I need to kill markor to do this.   This is new behaviour, perhaps after one of the new updates.   

### Steps to reproduce

1. Open Markor
2. Click icon to create new note

### Information

Android version: 13
Device: Samsung Note 20 Ultra
App Version: 2.10.7

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
None
```

**Comment by gsantner** [comment]
Thanks for the bug report, but it is not really helpful. It not happens here / not a general issue. But check a newer version of Markor when it's out.
