### ISSUE TITLE
color coded file types in directory

### ISSUE THREAD

**Issue by nutpantz** [gsantner/markor#1977]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. Don't worry; Markor and Mordor appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

1. As markor supports a number if different file formats (txt, md,) and others might be coming out would be nice if the directory view was color coded. Directory's one color. Txt files another and other file formats their own color. It would make finding specific files much easier.

### Information

Android version: 12
Device: pixel 6
App Version: latest fdroid

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
You may sort by Mime-Type to get a distinction between types. For colors, sorry to say, want to keep it simple and not bloat it unnecessary.
