### ISSUE TITLE
Add support for GFM Task Lists

### ISSUE THREAD

**Issue by benjaminoakes** [gsantner/markor#198]
#### General information

Feature request

#### Description

Please add support for GFM Task Lists.  I use them for tasks instead of todo.txt style lists.

Example:

```
- [ ] Incomplete
- [x] Complete
```

- [ ] Incomplete
- [x] Complete

(They render as bulleted lists today, which is okay, but something that acts like GitHub would be awesome!)

**Comment by gsantner** [comment]
<https://github.com/gsantner/markor/issues/29>
