### ISSUE TITLE
Snippets / templates path should be configurable

### ISSUE THREAD

**Issue by harshad1** [gsantner/markor#1984]
Right now snippets / templates default to `notebook/.app/snippets`

Several other apps (primarily obsidian) don't like hidden folders. In order to work around this, it would be useful to allow the snippet folder to be configurable. 

In addition, it would be nice to support obsidian's time interpolation formats. i.e. `{{time}}`, `{{date}}`, and `{{title}}`

**Comment by harshad1** [comment]
I'm not actually sure if this is a good idea (adds complication and a setting option for a feature which works fine now)

**Comment by gsantner** [comment]
I don't think it needs to be a new option. What I could think off possibly is to have a check `if (Folder::exists(Notebook/markor))` use the `Notebook/markor`, otherwise `Notebook/.app`.  

That should be enough to solve that specifically, right?

**Comment by harshad1** [comment]
We already have this. Templates and snippets interpolate dates + times in backticks. The format used is Java's simple date format.



Mar 24, 2023 06:40:42 Quinn McHugh ***@***.***>:

**Comment by quinn-p-mchugh** [comment]
Ah, thank you @harshad1 - I see you noted the date-time formatting feature in #1624.

> Snippets will be interpolated with date-time formatting
> Regions in the snippet delimited by backticks will be interpolated with SimpleDateTime formatting

I'll give this a try. Thanks for your work!

**Comment by harshad1** [comment]
This is done in #2148
