### ISSUE TITLE
Floating plus icon, does not open "new" dialogue

### ISSUE THREAD

**Issue by andreasio** [gsantner/markor#1985]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

Same experience as reported here: https://github.com/gsantner/markor/issues/826.

When I open markor, often the floating plus icon is not responsive.
If I restart the app (show recent apps, swipe to close markor, reopen markor) the floating plus icon works again.

Version: 2.10.7 installed from f-droid
Phone: Android 13 with samsung one-UI version 5.0 

markor folder is shared through syncthing

please beware: I have dowloaded and installed marder, but "the app keeps stopping/marder is crashing frequently". So I was not able to reproduce.

Also: It's not a big problem, to close and open markor. Its by far the most versatile and usefull app on my phone. Thanks for making it.

### Steps to reproduce

It's not super reliable when this happens.

1.  Open markor. Share into a new file. 
2.  Do something else
3. Open markor and click the plus sign. Then nothing happes.

### Information

Android version: 13 
Device: samsung s22 ultraissue
App Version: 2.10.7

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by harshad1** [comment]
@gsantner I think I solved this in #1950
