### ISSUE TITLE
Add monochrome icon

### ISSUE THREAD

**Issue by xmha97** [gsantner/markor#1989]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

Please add the themed icon.

![Screenshot_2023-02-23-03-07-43-114_de mm20 launcher2 release](https://user-images.githubusercontent.com/23485114/220788329-91136b9a-92a9-403f-9ac4-23058913b255.jpg)

### Information

Android version: 13
Device: T11 (Xiaomi)
App Version: 

### Source

GitHub Releases

### Format / File type

Something else (-> Additional info)

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
Are you sure the icons are not coming from a icon theme you have installed?

**Comment by xmha97** [comment]
No, it's the "Themed Icons".
It's available only on Android 13.

Read more:
https://www.androidpolice.com/android-13-themed-icons-how-to-activate/

**Comment by gsantner** [comment]
Feel free to make icon suggestions 😄 . Just please don't cripple the icon in such a way it's unnoticeable that it's even Markor and not a generic text icon.

**Comment by xmha97** [comment]
I am not a designer but if you need idea, see this issue:
https://github.com/gsantner/markor/issues/142

**Comment by gsantner** [comment]
> I am not a designer

Well, me neither 😄 .

>  Also I think the current icon needs redesign because it's not minimalist.

I disagree on that, I don't make something complete new just because it's trendy. It's ok to be traditional.

**Comment by xmha97** [comment]
> > I am not a designer
> 
> Well, me neither 😄 .
> 
> > Also I think the current icon needs redesign because it's not minimalist.
> 
> I disagree on that, I don't make something complete new just because it's trendy. It's ok to be traditional. It's ok to also supply an additional minimal icon (or use a minimal iconset), but I don't want to exchange the current Markor "main" icon.

![image](https://user-images.githubusercontent.com/23485114/221445876-73e0467b-1e95-4537-98a1-db14cbee047d.png)

**Comment by gsantner** [comment]
@xmha97  
From screenshot: Did you rework the icon a bit or does the launcher you use have a builtin ability to "monochromize" the icon?

**Comment by xmha97** [comment]
> @xmha97  
> From screenshot: Did you rework the icon a bit or does the launcher you use have a builtin ability to "monochromize" the icon?

I created this picture using Photoshop.
