### ISSUE TITLE
DAV

### ISSUE THREAD

**Issue by GormCh** [gsantner/markor#1991]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

Hi there!
It's the best app for text stuff. Are there any plans for WebDav support?
All the best
Gorm Chandler

### Information

Android version: 23
Device: Google Pixel 5
App Version: 2.10.7

### Source

Google Play

### Format / File type

Wikitext, Zim

### Additional info / Log

```shell
None
```

**Comment by harshad1** [comment]
I don't think so. Opening, editing, and rendering file types is hard enough. I think markor will want to stay away from trying to implement sync protocols etc. One of the huge advantages of working with local files is that markor will play well with anything which uses / syncs these files

**Comment by gsantner** [comment]
Hello,

Markor generally doesn't have any network/internet features on it's own, intentionally. I want to keep it as such and not introduce any special SDKs (i.e. dropbox, dav, ...).

However with Markor you can also open files from other apps, and the usual case is to have some other app (like official Dropbox app,.... or in this case some dav app) that takes care of sync and Markor is just the file editor.
