### ISSUE TITLE
Install problem on Android smartphone 

### ISSUE THREAD

**Issue by nehalsin** [gsantner/markor#1994]
# IMPORTANT
* App version: 2.10.7
* Android version/rom: 9
* Device: Redmi 
* I accept that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

## Explain the Problem
What problem did you encounter? What did you expect to happen?

I'm not able to install this app in my phone after factory reset. It was working right when I was using it before reset. 

## Steps to Reproduce
Explain what you did to encounter the issue

## Log
<details>
<summary>Log</summary>

```
Paste log here
```
</details>

**Comment by nehalsin** [comment]
Error: File not found 10:38 PM, 10 March 2023, Gregor Santner ***@***.***>:
What's the error?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
-- https://linktr.ee/nehalsin

**Comment by nehalsin** [comment]
Seems to be installation error. At the last step the installation doesn't complete and shows ERROR: COULD NOT OPEN FILE. 8:06 AM, 11 March 2023, Nehal ***@***.***>:Error: File not found 10:38 PM, 10 March 2023, Gregor Santner ***@***.***>:
What's the error?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
-- https://linktr.ee/nehalsin
-- https://linktr.ee/nehalsin

**Comment by gsantner** [comment]
#1886
