### ISSUE TITLE
Document editing launcher widget - Widget Show contents of 1 files

### ISSUE THREAD

**Issue by btgtsynology** [gsantner/markor#1997]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

1. Can a new widget type be considered: a widget type that shows the internal content of one file (chosen by the user).
2. This way one could have multiple widget instances, each showing the internal contents of one file.
3. Double tapping the widget will open Markor on that file in editing mode
4. The widget has a settings button on the widget that lets you edit the widget config (which file it shows + what action to take on tapping the widget - editor or view mode). That way a change doesn't require the lengthy process of removing the widget and creating a new one.
5. Pat yourself on the back it's an awesome little app THANK YOU!!

### Information

Android version: 
Device: 
App Version: 

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-Just about to donate. This is a great little app. I love that if I put a - or * it will auto enter unstructured list mode and help me by populating that char on the next line.
```

**Comment by harshad1** [comment]
Would this be useful without any formatting? I.e. without highlighting?

**Comment by btgtsynology** [comment]
Yes. Very useful without formatting. Lots more would fit on screen. Thank you!!

**Comment by gsantner** [comment]
So this really only meant as for **viewing**, not editing right? #156 is related. (As far I recall there are also ~5 similar/duplicate widget issues too)

**Comment by btgtsynology** [comment]
I'd be very happy with just viewing and 'plain'.
There is a nice idea in #156  : to choose the display type for each widget (plain, md, .. ). Perhaps the first widget release is locked to plain (as much less work)  - with a future release to possibly offer MD, etc.

**Comment by 0x4c47** [comment]
Hi, I just recently switched from Fossify Notes to Markor. I just wanted to hint at their implementation of the note viewing widget here since it's really good and simple imo. I used it all the time to get a quick overview of my todo list on my home screen.
You can view the note and scroll through it. Tapping on it directly leads to editing the note within the app which is exactly what I want from such a widget.
https://github.com/FossifyOrg/Notes

**Comment by gsantner** [comment]
Basically duplicate to one of the oldest open issues: #156
