### ISSUE TITLE
Versions after 2.7.0 listed as incompatible with Android 7.1.1 device on F-Droid

### ISSUE THREAD

**Issue by quadrilo44** [gsantner/markor#1999]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

Versions after 2.7.0 are not available through F-Droid for my device running Android 7.1.1. If I select "Show incompatible versions" in the F-Droid settings it shows up, and it will download, but the install fails without error.

I downloaded v2.10.7 from the releases page on GitHub and it installs and runs fine.

Is this by design, or is there some error in the F-Droid metadata? The Markor page on the F-Droid website says "This version requires Android 4.1 or newer" for v2.10.7.

### Steps to reproduce

1. Use Android 7.1.1 device
2. Open F-Droid
3. View Markor entry

### Information

Android version: 7.1.1
Device: Motorola Moto g5s Plus
App Version: 2.10.7

### Source

GitHub Releases

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
Note that you need to uninstall github version otherwise you cant install from fdroid. The reason it could not be installed might have been the signing signature, not the version.
