### ISSUE TITLE
App Not Available on Google Play Store

### ISSUE THREAD

**Issue by euphonics** [gsantner/markor#2006]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

I can no longer download the Markor app on the Google Play store. I checked on 2 different Android devices in the U.S. Markor does not appear on either.

### Steps to reproduce

1. Open Google Play Store on Android device in the U.S.
2. Search for "markor"
3. Observe the app does not appear

### Information

Android version: 14 and 11
Device: Samsung Galaxy S21 Ultra and Boox Nova C tablet
App Version: n/a

### Source

Google Play

### Format / File type

Not specific

**Comment by gsantner** [comment]
Most recently asked and answered: #1990
