### ISSUE TITLE
Todo.txt Date is deleted when Task marked as done and have a Priority

### ISSUE THREAD

**Issue by gahsul** [gsantner/markor#201]
#### General information

* **App version:** v0.3.4
* **System:** Android 8.1

#### Description

**Exemple Task:**

`(A) 2018-03-25 Something to do +Project (at)Context`

When marked as complete from the Menu bar with the `x`. Then the Priority and the Date is deleted.

`x Something to do +Project (at)Context`

**Suspected Output:**

`x "Completion Date" 2018-03-25 Something to do +Project (at)Context`

#### Log

Sorry I don't know where is a log file.

**Comment by gsantner** [comment]
This may be not to hard to fix, suited for beginners. Look at `code/opoc/format` package
