### ISSUE TITLE
Updating to 2.10.8 reset QuickNote.md location

### ISSUE THREAD

**Issue by ryliejamesthomas** [gsantner/markor#2013]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

Updated to 2.10.8 recently and noticed that using shortcuts/widget/etc. to open `QuickNote.md` directly would open an empty file.

Existing `QuickNote.md` is still intact, but the path Markor was looking for it was reset to `/storage/emulated/0/Documents/markor/QuickNote.md`, whereas mine is in my main notes folder elsewhere (`/storage/emulated/0/Sync/Notes/QuickNote.md`). Changing the path in settings resolved the problem.

No other paths were reset.

NB: I can't actually test if this is still present in the dev version as testing requires updating from an earlier version.

### Steps to reproduce

1. Have existing installation of Markor and have custom path to `QuickNote.md`
2. Update to 2.10.8
3. Try to open QuickNote from shortcut icon or widget icon.

### Information

Android version: 12
Device: Nokia G20
App Version: 2.10.8

### Source

F-Droid

### Format / File type

Not specific

**Comment by gsantner** [comment]
Yes this happened to me as well, though noticed it after updating myself.

There won't be a code change here, I see this issue as something users can read as notice here and change again easily on their own in settings.
