### ISSUE TITLE
[Feature Request] Distraction free, full screen view mode

### ISSUE THREAD

**Issue by chromer030** [gsantner/markor#2015]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

1. Please add an option to auto hide toolbar and top-bar when scrolling in View Mode.
2. In view mode the purpose is only reading and not editing.
3. So a full-screen and without any distraction UI is highly needed.
4. Thanks very much.

### Information

Android version: 7.1.2
Device: Lenovo
App Version: Latest

### Source

GitHub Releases

### Format / File type

Markdown

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
There are a few existing issues and discussions about this topic (hide features X, fullscreen etc)
