### ISSUE TITLE
Font size difference between View & Edit Mode

### ISSUE THREAD

**Issue by mmoneyy** [gsantner/markor#2016]
# IMPORTANT
* App version: 2.10.7
* Android version/rom: irrelevant version
* Device: Xiaomi and Huawei
* I accept that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

## Explain the Problem
* 编辑和显示模式的字体大小范围差距大，显示模式下字体大小的下界过大
* There is a large difference in the font size range between edit mode and display mode, and the lower bound of font size in display mode is too large

## Steps to Reproduce
Explain what you did to encounter the issue

## Log
<details>
<summary>Log</summary>

```
Paste log here
```
</details>

**Comment by gsantner** [comment]
Unfortunatley yes the font-size at view-mode (WebView) and Edit-mode (EditText) isn't quite the same. But we try to get it as good as possible. If you have suggestions for adjusting the scaling applied, feel free to proper changes by a merge request. Thanks!
