### ISSUE TITLE
Use external card as storage for Markor files?

### ISSUE THREAD

**Issue by DMcCunney** [gsantner/markor#202]
#### General information

* **App version:** 0.3.4
* **System:** Android Marshmallow 6.01

#### Description
I may be missing the obvious.

I just installed Markor on a 10" tablet.  Markor claims Notebook is in /storage/emulated/0/documents/markor.  Attempts to muse that bomb with an Error: can't create notebook directory.  Similar errors occur trying to use the Quicknote and To-Do functions.  (I've seen similar problems elsewhere - my device has some odd permissions notions, and I've been unable to root it and fix that.)

I'd *like* to have Markor read from and write to a directory on my external microSD card, but there seems to be no way to specify that as a location.

Am I missing the obvious?  If it's not possible, I think it ought to be.  As it stands, I can't actually use Markor on this device.

Thanks in advance.

**Comment by gsantner** [comment]
In settings -> Top option -> Document folder --> press ".." multiple times - you should be able to specify any path. Regarding broken device, we can't fix that :D.

**Comment by DMcCunney** [comment]
Okay, I was missing something.  I'll give it another shot.

(I can hardly expect you to fix a broken device, but being able to store documents on an external card works around the breakage.)

Thanks!

**Comment by gsantner** [comment]
did that work for you?

**Comment by DMcCunney** [comment]
No.  Still confused.

**Comment by DMcCunney** [comment]
No.  Still confused.

Invoke Markor.  I get a blank screen with Markor and icons for Search, Sort, Folder, Settings, and More in a top band, and Notebook, QuickNote, To-Do and More in a status bar, with "This directory in empty" and a + icon to create a new entry in the main screen.

Press the + icon, and I get *Error: Cannot create notebook directory.*

Tap the QuickNote icon and I get a screen with Markor and icons for Preview, Undo, Redo, Save and Settings icon in the menu bar, and icons for formatting in the status bar.  The Save icon remains greyed out, probably because Markor cannot write to the default directory, so I have no way to assign a name to the note or save it.

Click the Settings icon and choose Main View, and I see Notebook, Quicknote, and To-Do entries with the default locations.  Tapping any of those returns  *Error: Cannot create notebook directory*.

I do not *see* the _settings -> Top option -> Document folder --> press ".."_ you mention in your earlier comment.

It appears that because Markor cannot write to default location, there is no way to specify an alternate location instead. What am I missing?







.

**Comment by DMcCunney** [comment]
Update: I installed Markor on an older 7" tablet running Android 4.4 KitKat.

When I chose QuickNote, I got prompted to enter a note title, which I did _not_ see on the 10" tablet.

And when I tapped Settings/Main View Notebook, I could navigate the file system hierarchy and select /mnt/extsd/179_5/Documents as the location on the external card where I wanted to store things.  The corresponding QuickNote and To-Do entries were updated to point to that location.

A permissions related inability to open the default Notebook location appears to block everything else on the 10" tablet, and I've found no way to specify an alternate location.

It would be nice it Markor could ignore that error and allow me to specify an alternate Notebook location to store QuickNotes and To-Dos that it *can* open and write to.

**Comment by davidhedlund** [comment]
> In settings -> Top option -> Document folder --> press ".." multiple times - you should be able to specify any path. Regarding broken device, we can't fix that :D.

Hello dear dev.

My micro SD card storage do not pop-up there when I press multiple times. Can you please re-open this issue?

Best
