### ISSUE TITLE
Editor: auto scrolls to bottom of file while typing

### ISSUE THREAD

**Issue by Grandof1** [gsantner/markor#2023]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

## Editing a markdown file (created on Galaxy S22)
Once there is enough content that Markor has a scroll bar, when adding new content the editor auto scroll down to the very bottom of the file and if the user pauses in the middle of typing it will auto scroll to the bottom of the file each pause. 

Once user begins typing again the editor scrolls up the file to where the content is being typed. When typing is stopped or paused editor auto scrolls to bottom again.

## Thoughts
I first thought it was due to formatting issue but I have check several times and reformatted multiple times as well as created multiple new files both using Markor on the phone as well as on the computer.

## Frustration
It gets VERY annoying trying to edit a file when the editor is constantly scrolling up and down all the time or have to scroll up manually to select another section to make changes or add content for.
Had this issue on Galaxy S7 but thought was the phone and got new phone, still having the issue but only on files that are long enough to have scroll bar. I use this for work due to its the only app to easily and quickly. Love the app but this bug is driving me nuts.
I have tried multiple different versions of the app and it happens every time. 

### Steps to reproduce

1. Create markdown file
2. Add enough content that the file is long enough that scroll bar shows up
3. Tap Save > leave app
4. Open app > open file > add new content

### Information

Android version: 13 
Device: Galaxy S22 (SM-S901W)
App Version: 2.10.8

### Source

F-Droid

### Format / File type

Markdown

### Additional info / Log

```shell
- Would love to see this fix or understand what I am doing to cause this issue.
- Not sure how to add logs to help further I'm sorry.
```

**Comment by harshad1** [comment]
Quicknote and Todo will _open_ at the end. But they should not have issues with scrolling. Could you create a screen recording or video showing the issue?

**Comment by Grandof1** [comment]
Ah ok, ya this is more of it will auto scroll to the bottom while typing.

Ill try to do a screen recording as soon as I can. Not entirely sure how ill be able to do that though aince ive never done that before.

**Comment by Grandof1** [comment]
I have a screen record but ive never done this before and not sure how to add it.

As a side note i tried creating a new file to see about the formating. I removed all header 4 and never went past header 3 but as i got enough content in the file it had to scroll a bit it started auto scrolling to the bottom.

Apologies for late response beekeeping season for me so its hard to have enough time and my computer has been having issues of late.

**Comment by Grandof1** [comment]
Sorry acidently closed the issue currently on mobile due to at work.

I am trying to add the screen recording. I hope it works, i never dont this before.

**Comment by Grandof1** [comment]
Update:

I stumbled across a work around for my issue with the app.
When I turn off `Predictive text` in my `Samsung Keyboard` settings the issue with it automatically scrolling to the bottom stops happening. I use predictive text quite a bit to type stuff that is repetitive and have been truly missing it.
I do remember about a yr ago (sorry cant give better date than that) I did not have this issue with `Predictive text` so I wonder if it is a bug in `Markor` or maybe a bug in the `Samsung Keyboard`.
I have tried other keyboards and if I remember correctly I did not have the issue unless the keyboard had a `predictive text` feature.

Hope this helps

**Comment by zvsmith** [comment]
Disabling predictive text in the Samsung keyboard or switching to GBoard also resolved this problem for me (on a Galaxy A52s running Android 13). Thankyou!

As another data point, that same change also resolved a different but similarly frustrating & bizarre text entry bug with another app - the Godot editor Android port. The problem there was spontaneous and frequent duplication and/or indenting of big chunks of code. That certainly suggests that the problem is with the Samsung keyboard itself, but enough apps seem to work just fine with predictive text enabled that there's clearly something specific in the text entry handling that's triggering the bug. If I were a betting man, my money would be on a race condition somewhere between the Samsung predictive text routine and an app's text auto-formatting routine.

**Comment by gsantner** [comment]
Thanks for hints, seems like this can be closed 😄 .

Also, please give the development version a shot, maybe it improved on it's own <https://github.com/gsantner/markor/actions>

**Comment by fabiodr** [comment]
> Update:
> 
> I stumbled across a work around for my issue with the app. When I turn off `Predictive text` in my `Samsung Keyboard` settings the issue with it automatically scrolling to the bottom stops happening. I use predictive text quite a bit to type stuff that is repetitive and have been truly missing it. I do remember about a yr ago (sorry cant give better date than that) I did not have this issue with `Predictive text` so I wonder if it is a bug in `Markor` or maybe a bug in the `Samsung Keyboard`. I have tried other keyboards and if I remember correctly I did not have the issue unless the keyboard had a `predictive text` feature.
> 
> Hope this helps

Thanks @Grandof1! This fixed for me too, that was very annoying.

I'm on Samsung S23 Ultra running Android 15 and it's the default keyboard, so many others may still be experiencing this problem and assuming it's a Markor bug. It would be helpful to guide users to this fix somewhere more visible.

@gsantner
Markor could potentially work around this keyboard configuration, perhaps it's triggering some invisible input that can be dismissed.
