### ISSUE TITLE
Sorting: folders and files are sorted separately / "folder first"-setting has no effect

### ISSUE THREAD

**Issue by min7-i** [gsantner/markor#2026]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

Probably due to the changed sorting logic in the last update I noticed that folders and files are now sorted separately. As a result, the "folder first"-setting has no effect anymore.

Personally, I don't mind that folders and files are sorted separately. However, I'd still like to have the option to show folders at the top while sorting the files by date (latest modification date at the top below the folders). In the latest version this is not possible anymore.

Here is a comparison of the old and new sorting logic:

| old | new |
| --- | --- |
| ![Screenshot_20230421-214059 (Benutzerdefiniert)](https://user-images.githubusercontent.com/97251923/233778460-1fdef07a-20e2-4790-85c9-76e79f4ccdf5.png) | ![Screenshot_20230421-210055](https://user-images.githubusercontent.com/97251923/233778475-78b676d7-a0ac-4a59-a516-1f6d527699df.png) |
| ![Screenshot_20230421-214105 (Benutzerdefiniert)](https://user-images.githubusercontent.com/97251923/233778490-26a4eb88-bd1c-42d1-ac5e-4e35bcd5c51f.png) | ![Screenshot_20230421-210102](https://user-images.githubusercontent.com/97251923/233778500-b31091ab-e3cf-41be-94b1-6780d6f49b35.png) |
| ![Screenshot_20230421-214109 (Benutzerdefiniert)](https://user-images.githubusercontent.com/97251923/233778513-1352a872-101a-4a76-9c8a-3616db861359.png) | ![Screenshot_20230421-210110](https://user-images.githubusercontent.com/97251923/233778520-57568554-fcd6-4097-9425-dd7890dc6ae2.png) |

### Steps to reproduce

1. In the files and folders view open the sort settings.
2. Sort by date, folder first, reverse order.

Current behavior:
Files with latest modification date descending are shown first and below the folders are shown.

Expected behavior:
Folders are shown at the top and below are the files ordered by latest modification date descending.

### Information

Android version: 13.1
Device: Google Pixel 6a
App Version: 2.10.8 and latest development version

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by harshad1** [comment]
Yeah. That's a bug. I'll work on a fix

**Comment by min7-i** [comment]
Thanks @harshad1 for the quick fix!

I retested it with the new test version 2.10.8-1313 from today. When "reverse order" is unchecked the "folder first"-setting now works as expected. However, if "reverse order" is also active the folders are still displayed below the files:

![Screenshot_20230424-220123_r](https://user-images.githubusercontent.com/97251923/234105065-c3c374fe-f4d1-42fb-b2b8-110b4cf607a2.png)

**Comment by harshad1** [comment]
@min7-i Could you please test this https://github.com/gsantner/markor/pull/2029

**Comment by min7-i** [comment]
Now it works perfectly. Thanks.
