### ISSUE TITLE
Resources section in more tab hidden/inaccessible, when run app in landscape mode.

### ISSUE THREAD

**Issue by iamank1t** [gsantner/markor#203]
#### Expected behavior
If i go to more tab in app and change device orientation from portrait to landscape, then the app needs to manage it's layout according to screen orientation so that user can access all features of app in landscape mode too.

#### Actual behavior
If i go to more tab in app and change device orientation from portrait to landscape, then resource section got cut out of the screen and become inaccessible even the whole section get disappeared. First i think that may be developer hides this section on landscape mode, so i test this bug on another device and on that device only Resources section heading is showing, other part is cut out from layout and hidden.

#### How to reproduce
To reproduce the bug follow the following steps :-
- Open the app and go to more tab of app.
- Now you see in portrait mode you can access all the parts including resources section.
- Now change screen orientation from portrait to landscape and resources section got hidden and become inaccessible.

<pre><code>
* Device:  Samsung J7 Prime
* Operating system: Android 7.0 Nougatt
* App Version: v0.3.4
</code></pre>

#### Recording Of The Bug
https://www.youtube.com/watch?v=DoUqFZ0wDKQ
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@iamankit/resources-section-in-more-tab-hidden-inaccessible-when-run-app-in-landscape-mode">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by gsantner** [comment]
This won't and shouldn't be fixed. The current More screen is just a quick solution and should be created new as a whole.

PR welcome, but please not with the intent of "making it orientation compatible".

**Comment by gsantner** [comment]
closed in https://github.com/gsantner/markor/commit/ffbb5fc0a370facf70b9e25d27b3ef1dea9ed7fc
