### ISSUE TITLE
Clicking "hide status bar" in the main view does not hide the status bar

### ISSUE THREAD

**Issue by codaphrenic** [gsantner/markor#204]
#### Expected behavior
I expect a specific function when i tick **hide status bar** in the main view. A function that renders the status bar immediately invisible when you navigate back to the main view

#### Actual behavior

The app has no status bar, however the tool bar at the bottom of the main view remains visible regardless of you ticking it hidden

#### How to reproduce
* download the app from fdroid store
* launch app and allow permissions if prompted
* Click on the settings icon, the third icon at the top tool bar
* Click on **main view**
* Now scroll down to more and tick the **hide status bar** check box
* Go back to the main view by clicking the arrow at the top left corner, click till you are at the main view. Down below is the imminent status or tool bar, still very visible

***

* Device: TECNO-L8Plus 
* Operating system: Android 5.1

* Application: Markor
* version: 0.3.4

#### Recording Of The Bug

<center>
https://youtu.be/BDNfZNksNdU
</center>
 

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@fego/clicking-hide-status-bar-in-the-main-view-does-not-hide-the-status-bar">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by gsantner** [comment]
statusbar is the very top bar, nothing else. Its not the toplbar and not the navbar.
