### ISSUE TITLE
FileBrowser: File list adapter sometimes doesn't set state properly

### ISSUE THREAD

**Issue by ghost** [gsantner/markor#2040]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

Markor hard to open file, and need to click so much times.

### Steps to reproduce

1. create a file and make it in the second place of the list.
2. exit and save the file.
3. click this file at once.

### Information

Android version: 12
Device: Google Pixel 3
App Version: latest (145)

### Source

F-Droid

### Format / File type

All

### Additional info / Log

```shell
- Perhaps, the reason is the contradiction between refresh list state and click item state.
```

**Comment by gsantner** [comment]
Can you please attach a video? And is it different to previous Android/Lineage versions?

Of course open/create a file, select to open it, and edit it...is the normal amount of steps.

**Comment by CiangCing14** [comment]
> Can you please attach a video? And is it different to previous Android/Lineage versions? Of course open/create a file, select to open it, and edit it...is the normal amount of steps.

This is the video in Google Pixel 3 Lineage OS 19.1：
https://www.youtube.com/watch?v=wkuVvPo7jNU

**Comment by CiangCing14** [comment]
> Can you please attach a video? And is it different to previous Android/Lineage versions? Of course open/create a file, select to open it, and edit it...is the normal amount of steps.

All the list in this software.

**Comment by gsantner** [comment]
As far I see in the video seems like the list adapter somehow doesn't refresh properly. Though I can't reproduce this on my device.

**Comment by harshad1** [comment]
I have made some improvements to the list adapter in my PR here #2176. May be good to test with that.
