### ISSUE TITLE
Scoped storage, SimpleStorage library

### ISSUE THREAD

**Issue by lrq3000** [gsantner/markor#2044]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

It seems Markor is not available in the Google Play store anymore. I read similar issues and PRs notably #1521, and it seems that the global writing permission was accepted in the past.

What is the current state about Google Play? Did they end up deny again the global writing permission and is that the reason Markor is not in the store anymore? 

Secondly, I have some experience implementing scoped storage permissions using the [SimpleStorage](https://github.com/anggrayudi/SimpleStorage) library. I already implemented in two other Android apps that had similar issues of being rejected from the Play store: [OneList](https://github.com/lolo-io/OneList/pull/44) and [SuperProductivity](https://github.com/johannesjo/super-productivity-android/pull/32).

I know you are reluctant to using libraries so that's why I am opening this issue to ask you if you are interested if I make a PR implementing scoped storage using SimpleStorage?

Trying to manually implement SAF is just torture, and also I think it's better for the Android ecosystem to modularize this task into a library that can more easily be updated to support future Android versions if Google decide again to change the file management permission system, instead of having lots of opensource apps trying to reinvent the wheel. This is actually what Google should have done in the first place, and they started making an alternative library recently but it's still alpha and we don't know if they will ever finish it. I used SimpleStorage several times so I am confident it would fit Markor's needs (ie, allowing access to a tree of files/folders). 

Note however about retrocompatibility that although the same behavior can be reproduced, existing users who will update will be required to set a new permission (ie, a dialog that asks them where to store the files - this can be set to their current folder to ease migration).

**Comment by gsantner** [comment]
> and it seems that the global writing permission was accepted in the past.

yes, it was granted.

> What is the current state about Google Play? Did they end up deny again the global writing permission and is that the reason Markor is not in the store anymore?

No. It's about users, specifically of Google Play. I get many mails on daily basis from users feeling entitled to everything "" I'm the boss, I give you 1 star rating, you must make this otherwise its shit"", want it completly different, demand this and that -- and can't accept a no. And want 24/7 professional support. For free, of course.

I can't and don't want to do fulfill what somebody wants on short-term while being rude and entitling too.

At the end, since turning off Google Play it's way more relaxed - and thats very good to my health. So I consider to keep it like this.

**Comment by gsantner** [comment]
> Trying to manually implement SAF is just torture
> ScopedStorage

Over the many years there were many different ways and literally every second Android version there is a new way to deal with files. I'm quite done with that and not keen on implementing one new thing just for sake of change.

What however really good over all the years and works also on **all** Android versions ..  is simple Java File. And thats what I want to keep focusing on.

Currently the only guard to that are i.e. permissions and i.e. acceptance at distributors - which I can live with.

**Comment by lrq3000** [comment]
Ok great, I perfectly understand why you would want to stop publishing on Google Play. I was just asking in case you had issues, but you are free to choose where you publish your app of course!

Ok for a minimal PR for scoped storage via SimpleStorage, i will give it a try. Not right now though because my computer broke :-/ But after getting some experience with the codebase by implementing MyST, I'll give it a try and you'll see if you think this is pertinent :-)

19 mai 2023 09:52:56 Gregor Santner ***@***.***>:

**Comment by lrq3000** [comment]
@gsantner thank you for assigning this issue to me. I still have no computer but this is on the top of my todo list once I get access to one :-)

**Comment by gsantner** [comment]
Hello, good day @Irq3000 !

Do you still have in mind to work on adding a first experiment with SimpleStorage library integration?

If so, happy to review a merge request. If not, also OK and I just close the issue.

**Comment by gsantner** [comment]
It not seems like somebody well come up with a implementation for that. 

So, closing.

**Comment by lrq3000** [comment]
Don't worry I will implement it, I just had major time wasters, such as my computers burning (my main one and then my replacement one... Call me lucky). Anyway, I consider I owe it to you to implement it, since your app helps me so much in a lot of areas of my life, especially given my disability. No problem that you close, doesn't change that I will do it.

**Comment by gsantner** [comment]
Hello again, feel free to work on it and make a first draft version pull request 😄 .

I close the issue - if something happens I happy open it again, but nevertheless merge request activity can happen be the ticket closed or not.

Doing some ticket housekeeping.
