### ISSUE TITLE
Don't generate id attribute BOTH on header and header anchor link upon html export

### ISSUE THREAD

**Issue by Daryadi-S** [gsantner/markor#2045]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

When export to html, Markor will generate id attribute with same value both on both header and link tag:

``` md
## The Header
```

Resulted in

```html
<h2 id="the-header"><a href="#the-header" id="the-header" class="header_no_underline">The Header</a></h2>
```

AFAIK, this is invalid in HTML as id attribute is unique and there should be only one id attribute value in an HTML document.

Thank you.

### Information

Android version: 10
Device: ASUS ZenFone LIVE L2
App Version: Marder version 2.10.8-1928

### Source

F-Droid

### Format / File type

Markdown

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
Markor uses flexmark to parse Markdown, thus to create the html. <https://github.com/vsch/flexmark-java/wiki/Extensions>.
