### ISSUE TITLE
keyboard disappears on some documents

### ISSUE THREAD

**Issue by igorzhilin** [gsantner/markor#2047]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

When editing this .md file: https://codeberg.org/labaz/linux/raw/branch/main/android%20adb%20dumpsys%20list%20packages/README.md
When you go into editing mode and tap inside the document, the keyboard pops up but immediately disappears.
Happens only with the specific file linked above.
Happens with Gboard keyboard or Hacker's keyboard.

Here's screen record: ![](https://dl.zici.fr/1685942804-96/out_6fps_500px.gif)

### Steps to reproduce

1. Create .md from this and open in markor https://codeberg.org/labaz/linux/raw/branch/main/android%20adb%20dumpsys%20list%20packages/README.md
2. Go to edit mode 
3. Tap on the text
4. Keyboard pops up and drops down

### Information

Android version: 13
Device: Samsung s20+
App Version: 2.10.8 (145)

### Source

F-Droid

### Format / File type

Markdown

### Additional info / Log

```shell
-
```

**Comment by harshad1** [comment]
I can't reproduce this. Could you try using a different keyboard?

**Comment by igorzhilin** [comment]
Yes, I tried Hacker's keyboard, and it pop ups, too.

**Comment by gsantner** [comment]
Can't reproduce this on any device. I can see the problem in your video, though the best I can do is guessing - which makes it very hard to fix. If you by chance have any Android/Java development experience (or want to learn it), feel welcome to propose a fix by merge request.
