### ISSUE TITLE
Open the md file, The rendered position is at the bottom,not at the top

### ISSUE THREAD

**Issue by s6677** [gsantner/markor#2049]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

1. when i open the md file

2. I wish there was a setting
3. The rendered article can be positioned at the bottom of the article

Current version,Now it's at the top(default) , , you need to manually press the button(Press the button to jump to the bottom),I wish there was a setting that would automatically be always at the bottom(default), instead of manually pressing the button each time

### Information

Android version: Android 12
Device:  tab s7+
App Version: 2.10.7

### Source

GitHub Releases

### Format / File type

Markdown

### Additional info / Log

```shell
-
```

**Comment by harshad1** [comment]
Quicknote and Todo will always open at the bottom when opened through the appropriate shortcuts. All other files will open at the last location. For _new files_ there is a default option under edit settings.

**Comment by s6677** [comment]
Not the text cursor in the bottom of the edit mode，it is the bottom position in view mode.When you are in view mode, there is a button to jump to the bottom,I don't like to use it, it can't always jump to the last accurate position, It is always some distance from the bottommost position,I also need to manually scroll down the screen.What I need is an automatic jump to the bottom setting(in view mode),If there is such a setting,Real-time rendering can be achieved indirectly by repeated viewing发送自我的盖乐世
-------- 原始信息 --------发件人： Harshad Vedartham ***@***.***> 日期: 2023/5/23  上午5:17  (GMT+08:00) 收件人： gsantner/markor ***@***.***> 抄送： s6677 ***@***.***>, Author ***@***.***> 主题： Re: [gsantner/markor] Open the md file, The rendered position is at the bottom,not at the top (Issue #2049) 
Quicknote and Todo will always open at the bottom when opened through the appropriate shortcuts. All other files will open at the last location. For new files there is a default option under edit settings.

**Comment by gsantner** [comment]
@s6677   
At view-mode you get the ability to inject any kind of javascript you want, thus controlling view-mode very much to specific personal needs. You may add this to the Inject-head onPageLoadeded section for example: `window.scrollBy(99999,99999)`.
