### ISSUE TITLE
Start document at the recent cursor position

### ISSUE THREAD

**Issue by ali-hardan** [gsantner/markor#205]
After a document gets loaded, position the cursor on the recent cursor position.

It's necessary for long documents.

**Comment by JohnVeness** [comment]
For those of us who have "Open preview when opening documents" ticked, I'd like to see similar happen for that view too, where it remembers the last scroll position.

**Comment by gsantner** [comment]
For anybody - feel free to send a PR for this ;)

**Comment by gsantner** [comment]
should be done together with #149  .

**Comment by gsantner** [comment]
I have done this now - position is remembered and restored where possible. This is disabled for special documents (so ToDo and QuickNote still always starts at bottom :yum: ).
