### ISSUE TITLE
Links in Obsidian markdown

### ISSUE THREAD

**Issue by merlinuwe** [gsantner/markor#2050]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

I'd miss working links from Obsidian markdown files.

These obsidian links do not link to the existing file:

[[Einzellösungen]]

Or do I have to switch something in obsidian?

### Information

Android version: 11
Device: Xiaomi Poco X3 Pro
App Version: newest

### Source

Google Play

### Format / File type

Markdown

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
The proper syntax that works in all Markdown specifications and syntax guides is this: `[title](link)`.
