### ISSUE TITLE
Open Quick Note always with visible keyboard

### ISSUE THREAD

**Issue by iexos** [gsantner/markor#2053]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

- When opening Quick Note, I do it to take a note, not to read it
- I'd like: always open Quick Note with the soft keyboard visible
- I don't mind if this would be configurable

### Information

Android version: LOS 13
Device: fairphone3
App Version: v2.10.8

### Source

F-Droid

### Format / File type

Not specific

**Comment by gsantner** [comment]
In Markor settings you can enable "special launchers". then you have a dedicated launcher for quicknote, which should start also with keyboard.

**Comment by iexos** [comment]
Its starting in edit mode, but not with keyboard for me. Is this a bug then?

**Comment by iexos** [comment]
This issue is still closed. Is this a mistake or do you reject this idea?

**Comment by justpeanuts** [comment]
Same problem: keyboard does not pop up automatically when opening any note (though the mark or remembers the last cursor position - which is almost totally useless without the keyboard popping up as well)
