### ISSUE TITLE
How to Show Line Numbers?

### ISSUE THREAD

**Issue by guang-lin** [gsantner/markor#2057]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [ ] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

How to show line numbers in Markor? Including source code files and markdown code blocks.

### Information

App Version: v2.10.9 (146)

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
By programming it and creating a merge request :-).

This has been asked a few times already, please search issues.

**Comment by guang-lin** [comment]
Thanks, I will try to make some contributions to this project in the future.

**Comment by gsantner** [comment]
Great to hear that would be awesome. There are not too much people contributing : -D.

**Comment by guang-lin** [comment]
Hi, this function for line numbers support has been implemented, and I will make a pull request as soon as possible. 😁


![Screenshot_20230605_071848_net.gsantner.markor_test.jpg](https://github.com/gsantner/markor/assets/60415467/648e1974-0286-4149-bb57-d5ea23212f03)


![Screenshot_20230605_071852_net.gsantner.markor_test.jpg](https://github.com/gsantner/markor/assets/60415467/6f9dbe59-d720-41a8-b17e-35174e6b89f6)

**Comment by guang-lin** [comment]
> Great to hear that would be awesome. There are not too much people contributing : -D.

Hi, this function for line numbers support has been implemented, and I will make a pull request as soon as possible. 😁


![Screenshot_20230605_071848_net.gsantner.markor_test.jpg](https://github.com/gsantner/markor/assets/60415467/70645562-362e-4c31-b056-3cedb6dea11f)


![Screenshot_20230605_071852_net.gsantner.markor_test.jpg](https://github.com/gsantner/markor/assets/60415467/48e3b0ca-5aa9-4c61-b134-bd6632bcc4da)
