### ISSUE TITLE
Randomly upon reopening the markor window, the current file will be scrolled up to the middle

### ISSUE THREAD

**Issue by aaronwi** [gsantner/markor#2065]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

Randomly when going back to an open markor window, I find my note document to be scrolled up to the middle of the document.

### Steps to reproduce

1. Open a document
2. Go to another window
3. Go back

### Information

Android version: 13
Device: pixel 4a 5g
App Version: 2.10.9

### Source

F-Droid

### Format / File type

Markdown

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
Is there something special at said file? Many headings with bigger headings setting enabled? Does it happen at any file?

**Comment by aaronwi** [comment]
no headings, it's entirely plain text with a few [ ] check boxes. 

Only happens to the currently open file, I only ever leave open one of 3 notes files, they are all similar, no formatting.

**Comment by gsantner** [comment]
OK!

Unfortunatley need to say that I couldn't reproduce it yet any time
