### ISSUE TITLE
Opening/Sharing files from the View mode.

### ISSUE THREAD

**Issue by lockywolf** [gsantner/markor#2070]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

At the moment, Markor's file manager works like, well, file manager. I can click on a file and open, preview, or share this file. (At least if it is an image.)

If that file is attached to a Markdown file, I can see file content in the View Mode, which is very nice. (Works for images, and, as far as I understand, will work for PDFs in the future too.)

However, in the View Mode, this image is just a pixel buffer on the screen, with no interaction possible. I would like to be able to long-tap on that image, and have the option to "open this image with" or "share this image to". If "open with" is implemented, sharing can be unixwayed on top of it, by opening it with a sharing app.

### Information

Android version: 9
Device: OnePlus 5t
App Version: F-Droid 2.10.9 (146) ISource com.Google Play
(in spite of saying Google Play, this was installed from F-Droid)

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
The "open with" button is at the bottom bar, by default the second button. with the up arrow.

**Comment by lockywolf** [comment]
From the View Markdown mode! Not from the view file mode!

**Comment by gsantner** [comment]
A image can or cannot be a local file. Opening a non-local file externally won't work, might even be base64 embedded media. So not sure how it would be openable by a external app generically.

Suggestion: swap to view mode of a local file, then you can use said button.

**Comment by lockywolf** [comment]
I am using the "view mode of a local file" now. But it's inconvenient, because there are no thumbnails for the image files in the file manager (and I'm not sure implementing thumbnails is a good idea, because, after all, markor is an editor, not a file manager).

Base64 is a difficulty, but I remember that Android had something like `content://` way of opening.
