### ISSUE TITLE
Clicking a link (url) at todo.txt file

### ISSUE THREAD

**Issue by artkpv** [gsantner/markor#2072]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

Thanks contributors for the tool. How to easier open links in todo.txt? Now I can tap for long, wait selection of a link and a dropdown menu to appear, then click open in browser (about 1-2 sec). But how to reduce to just one click? Steps:

1. Open a todo.txt with url inside like: "my task. http://example.com"
2. Tap on the link (http://example.com)
3. A default action is done for a link. Like openning the link in a browser.

![Screenshot_20230707-155525](https://github.com/gsantner/markor/assets/3657998/f3c05b57-8405-4102-af6c-986ae43d5bef)

### Information

Android version: 12
Device: Xperia 10 II 
App Version: 2.10.9 (146) 

### Source

F-Droid

### Format / File type

todo.txt

### Additional info / Log

```shell
--
```

**Comment by gsantner** [comment]
Hello, todo.txt not really has links defined as somethin special. It's treated plaintext like any other text.

At the view mode currently there are nothing specific that is helpful to you. Generally the view mode is rather minimalistic as the edit mode has very good support and a line of text is a line of text and there is not really markup.

At the edit mode however there is something which I use every day to open links from todo.txt file.   
For that you need two clicks - one to place the cursor at-or-after-the-link and then click the up-arrow-button at the button bar.

**Comment by artkpv** [comment]
Thanks for the answer, @gsantner  . Not sure I understand what 'up-arrow-button is. I can open a link by clicking twice and then choosing a browser. Not a big deal but if i open a lot of links it accumulates plus if i miss one click from those 3 it takes more time.

![Screenshot_20230707-193715](https://github.com/gsantner/markor/assets/3657998/8ee40725-5199-427a-8f0a-85844d157d81)
![Screenshot_20230707-193757](https://github.com/gsantner/markor/assets/3657998/955b2e9b-0f28-4a22-b477-dd58beb9aaa9)

**Comment by gsantner** [comment]
the icon right to the trash bin
