### ISSUE TITLE
Markdown - Nested List Syntax Highlighting Error

### ISSUE THREAD

**Issue by whispy** [gsantner/markor#2073]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

When in Editor mode and with Syntax Highlighting toggled on, nested lists that have 3 or more levels of nesting appear with a grey background. This indicates a syntax error.

However, the nesting renders correctly in Preview mode.

The syntax error should not appear in syntax highlighting.

See screenshots:
![InShot_20230710_122924823](https://github.com/gsantner/markor/assets/2874975/e227403a-6dea-4a8d-a44c-f47caabb7be9)
![InShot_20230710_122853151](https://github.com/gsantner/markor/assets/2874975/aa2a8869-b0e6-4747-9450-a1f607d7fdf5)

### Steps to reproduce

1. Make a Markdown file
2. Enable syntax highlighting
3. Enter editor mode
4. Make a nested list with 3 or more levels of nesting

### Information

Android version: 12
Device: Pixel 6
App Version: V2.10.9

### Source

F-Droid

### Format / File type

Markdown

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
There is a settings option to disable code block highlighting, so for that grey background.

The thing is the code block highlighting is very performance intensive so there is no additional logic builtin to detect if it has list items in lines before. Plus if you go deeply nested you barely have remaining space to write text for the bullet point - phone happen to be small width and Markor's major of usage are phones. 

![Screenshot_20230713-202952_Marder](https://github.com/gsantner/markor/assets/6735650/13908850-3289-4990-b990-f367298e982e)

**Comment by whispy** [comment]
Ah, I didn't realize it was code block highlighting. Thanks, I've toggled that off, as I don't use code blocks anyway.

I edit my MD files across desktop and mobile devices, so I end up deeply nesting lists/outlines.

**Comment by gsantner** [comment]
Ah OK. Yes I used to also make rather deep nested things.  
But over time more and more it turned out to be better ... especially for making use of the information later and quickly finding the important .... to use headings plus max 1 level of subnesting.

like

```
## Used to be a bullet point before probably
* point
* point
  * sub point
```

vs 

```
* used to be a bullet point
  * point
     * subpoint
  * point
```

But I don't want to tell or like lecture andboy how to do it, that everybody needs to find their own way.
