### ISSUE TITLE
[Feature request] Spell checker

### ISSUE THREAD

**Issue by danielmmmm** [gsantner/markor#2076]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

1. A spell checker with downloadable dictionaries
2. A document should be tagged by the user with one or several languages, and Markor should underline misspelled words
3. Dictionaries should be downloadable either from within Markor, or added via the Android File chooser, e.g. from freedict.org

### Information

Android version: Android 8.0 (Oreo)
Device: Huawei MediaPad M5 10.8"
App Version: 2.10.9 (146)

### Source

F-Droid

### Format / File type

Plaintext

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
Android and the virtual keyboard has builtin Spellchecker functionality usually. Does that not work for you?

**Comment by danielmmmm** [comment]
At least on my tablet, there is no (Android) spell checker and I only get the autocorrect function from whatever keyboard I use. But these only work for the word I currently type, not for pre-existing text.

**Comment by gsantner** [comment]
In Markor Editing settings section you can find a option "Disable 
spelling underline" which is disabled the red spelling underline by 
default.  Enable that and restart Markor.

Then (detected) wrongly written text is red underlined automatically. 
Maybe that helps you.

**Comment by danielmmmm** [comment]
Thanks for the suggestion. Unfortunately, this option was already disabled. I checked the box, exited Markor, removed it from recents, and started the app again, without seeing a difference. I repeated this procedure with unchecking the box, but don't see spelling mistakes either.

If you think this is an issue with my particular device, you can probably close this issue. A spell checker would be nice, but it's not the end of the world to live without one.

**Comment by gsantner** [comment]
Does spell checking and text-suggestions work in other apps and editors for you? Like when you start typing a word in a messenger app it immediatly displays suggestions and highlights bad words (and that on any of my android devices).

**Comment by danielmmmm** [comment]
I double checked and can tell you that my device (Huawei MediaPad M5 10.8") does not have a system wide spell checker. Unfortunately, there is no alternative OS like Lineage available either.

**Comment by gsantner** [comment]
OK thats unfortunate.

Maybe installing a different keyboard like Google Keyboard gives you that feature on it's own.

Closing the issue as it's supposed to be a OS wide feature

**Comment by TimReset** [comment]
Just let you know. I've check - it works very strange for me - only with Samsung keyboard and only for one language. And after changing language all strokes disappear.
