### ISSUE TITLE
Option to hide dot-files

### ISSUE THREAD

**Issue by ravilov** [gsantner/markor#2078]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

Markor used to not show dotfiles (files/folders starting with `.`). That changed at some point and I don't see a way to turn it off. I would like my dotfiles hidden from public view.

### Information

Android version: 13
Device: Samsung A53
App Version: 2.10.9

### Source

F-Droid

### Format / File type

Not specific

**Comment by gsantner** [comment]
At the filebrowser top menu you can find the toggle.

**Comment by ravilov** [comment]
Oh my, you're right! A bit hidden but it works. Thanks! 👍
