### ISSUE TITLE
Quick note save button is not working properly in landscape mode

### ISSUE THREAD

**Issue by iamank1t** [gsantner/markor#208]
#### Expected behavior
As app keeps the save button disabled if i didn't write anything in quick note yet, so when i write some text in my quick note then the save button needs to be enable so that i can save my quick note.

#### Actual behavior
When i run app in landscape mode and go to quick note section to write a note. As my note is empty yet so the save button is disabled which is fine but after writing one line, the save button is still disabled. I wait for around 5 minutes but the button didn't enable. But if i go to another tab and came back to quick note tab then the button enables(for better understanding please see recording of bug).

#### How to reproduce
To reproduce the bug follow the following steps :-
- Open the app and rotate your screen to landscape mode.
- Now go to quick note tab to write a note. As you go you see the save button at top bar is in disabled condition now.
- Write a word or line and the button is still disabled.
- Now switch to any other tab and came back to quick note tab again and you see now the save button is disabled.

<pre><code>
* Device:  Samsung J7 Prime
* Operating system: Android 7.0 Nougatt
* App Version: v0.3.4
</code></pre>

#### Recording Of The Bug
https://www.youtube.com/watch?v=niuDOe-cmMo
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@iamankit/quick-note-save-button-is-not-working-properly-in-landscape-mode">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by gsantner** [comment]
That is intended behaviour - To not have useless empty files laying around.
