### ISSUE TITLE
Android's internal file manager

### ISSUE THREAD

**Issue by marker10** [gsantner/markor#2097]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

To set the default folders it would also be useful to use Android's internal file manager. 

Is it possible to activate the use of the internal Android file manager?

### Information

Android version: 11
Device:  Oppo A9 2020
App Version: 2.10.9

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
What do you think does it make different/better due that, effectively?

**Comment by marker10** [comment]
It's easier to search folders with android file manager. It's faster especially for the sd card (external memory) that I use with Markor. Markor's file manager by default is not positioned on the root path but on the app's save folder.

**Comment by gsantner** [comment]
You can use any file manager you want and use "Open with....Markor" to open a file from that other file manager in Markor.
