### ISSUE TITLE
Ad-filled copycat on the Play Store

### ISSUE THREAD

**Issue by VenomMage** [gsantner/markor#2099]
You might want to look into this ad-filled copycat on the Play Store with the same name and description:

https://play.google.com/store/apps/details?id=com.seal.markor

I have reported it as "copycat or impersonation". Please take necessary action against that scam app.

**Comment by harshad1** [comment]
@gsantner What are the biggest blockers from having markor on the play store rn. Perhaps some of us contributors could take this on instead.

**Comment by gsantner** [comment]
@harshad1 No technical. I just want to take my time to make the best out of the project in the way I want it to be. The users on Google Play often think different and spam me to take different direction.

I prefer enjoyable life, a fun side project and using something I can say hard built by my own ... over growth, the next million or making yet another billion users app clone.

If people want to use Markor there is a way, it can be downloaded and installed freely on any (not from last century) device.

**Comment by gsantner** [comment]
@VenomMage @harshad1 
I see that the seal app entry is gone by now (do you see it too as unavailable)? I sent them a polite mail few weeks ago but didn't get a response.

Anyway, seems that one is gone.

So closing this.

**Comment by Poussinou** [comment]
Hi,

I found another copycat here https://play.google.com/store/apps/details?id=org.chicha.tmarkor from [this developer](https://play.google.com/store/apps/developer?id=TuTT).

As you are the owner of the source code, you can follow [that procedure](https://gist.github.com/Poussinou/86136151f8b939fbaa48650666bf62d6) to remove this copy from the Store, if it's your wish.

**Comment by VenomMage** [comment]
Nope, only the existing users know where to get the legit version.

Markor (the official app) should be made available again on the Play Store
to counter these copycats published by frauds.
