### ISSUE TITLE
Option to stop Markor from creating folder called "markor" in documents directory

### ISSUE THREAD

**Issue by DominiqueSite** [gsantner/markor#2102]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

I want to stop markor from creating a folder called "markor" in the documents directory. I do not even know what this folder is created for as it is empty, but I want to be able to turn this functionality off.

### Information

App Version: v2.10.9

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
@DominiqueSite How about QuickNote and ToDo? Do they refer to a file in said Documents folder? Even if you don't use them, their parent folders will be created.

**Comment by gsantner** [comment]
@DominiqueSite 
If you implement something, it's not additional bloat, it not breaks the app otherwise and rather improves the project - feel free to make changes and a merge request.
