### ISSUE TITLE
Allow filename to be left unspecified

### ISSUE THREAD

**Issue by DavidRV00** [gsantner/markor#2104]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

Hello, I'm loving Markor so far, but what I'd really like to do is just click "+" and start writing, without having the friction of specify a filename. When I have an idea I want to remember, it's important for me to just be able to get it down as quick as I can.

There are a couple ways this could be done:
1. Just allow not specifying a filename, and have Markor pick a default (maybe the current timestamp) if it's left empty.
2. Allow selecting a default template (for example I would just use the template '202901012359-zettelkasten' every time if I could, since it allows multiple notes to be written quickly without filename clash). I can select this manually each time, but it would be great if I could have it auto-selected, or if Markor just remembered what I picked last time.

I've seen a couple similar-sounding issues relating to templates, but nothing relevant that's still open.

### Information

Android version: 12
Device: OnePlus Nord N200 5G
App Version: 2.10.9

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by harshad1** [comment]
Default timestamp makes the most sense. Need to pre-highlight this so one can easily replace the default.

Also note that starting typing immediately is what quicknote is for :)

**Comment by DavidRV00** [comment]
Quicknote is awesome! But just for my usual usecase, it doesn't quite work because it doesn't spawn a new file each time; can't go back and look at it later if I've written a new quicknote.

**Comment by harshad1** [comment]
Here is a fun hack for you

Markor will execute any JS code in a script tags when you switch to view mode

I use the following code to open a file with today's date in the current folder. If the file does not exist it will be created.

You can modify this to open a new file in the current folder with any programmatically generated name. If you want a new unique name you could use seconds or a UUID

```html
<script>
let anchor = document.createElement('a');

// This asinine approach is from https://stackoverflow.com/a/28149561
// offset in milliseconds
let offset = (new Date()).getTimezoneOffset() * 60000;

let iso = (new Date(Date.now() - offset)).toISOString()
    
let today = iso.split('T')[0]

let textNode = document.createTextNode("Today's worklog");

// Append the textNode as a child to anchor.
anchor.appendChild(textNode);

anchor.href = "./" + today + ".md";

anchor.style.fontSize = "x-large";

document.body.appendChild(anchor);

window.location.href = anchor.href

</script>
```

**Comment by harshad1** [comment]
Make a shortcut to this html file and it will open in view mode -> create a new file with a unique name and open it for editing. All in one click.

You can use this to emulate Obsidian's daily note as I am doing in this example

**Comment by DavidRV00** [comment]
Awesome, I'll try this out this week, thanks.

To clarify, you're saying that I should add this html file (or a shortcut to it) in my markor notes directory, and open it from *within* markor, and that will execute the code and open a newly-created note?

**Comment by harshad1** [comment]
Pretty much

**Comment by DavidRV00** [comment]
It works, thanks!

Do you think it would be worthwhile to have this as a built-in feature of the app, though? I could potentially volunteer to work on a pull request for it if so.

**Comment by harshad1** [comment]
In some sense it is a built in feature of markor :)

Imo the most useful thing would be to create a guide to using js in markor. This is the only trick I know, there are likely others.
