### ISSUE TITLE
Over View

### ISSUE THREAD

**Issue by deepbajud** [gsantner/markor#2105]
# IMPORTANT
* App version: 
* Android version/rom: 
* Device: 
* I accept that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

## Explain the Problem
What problem did you encounter? What did you expect to happen?

## Steps to Reproduce
Explain what you did to encounter the issue

## Log
<details>
<summary>Log</summary>

```
Add ss of application in GitHub for user best help in project understanding
```
</details>

**Comment by gsantner** [comment]
Please fill out the fields.

If the question is about a overview of the project, see the project readme and its linked sections.
