### ISSUE TITLE
Sort to-do lists  (with dialog asking for order)

### ISSUE THREAD

**Issue by mjray** [gsantner/markor#211]
#### General information

* **App version:** 0.3.4 F-Droid
* **System:** Android 4.1.2

#### Description

The ability to sort to-do lists so that tasks get reordered by leading priorities would be a great enhancement, reducing the need to cut and paste so much.

**Comment by mjray** [comment]
I barely speak Java and I've no idea how to build this app, let alone understand its structure. A HACKING.md or similar would help. I tried installing gradle, cloning this repository and running "./gradlew help" from it but it just started downloading something else so I don't think that's right.

**Comment by mjray** [comment]
Blimey. 1Gb of studio and tools to develop a 3Mb app. :( It may be a while before I download that. Is there any lighter way to get started contributing?

**Comment by gsantner** [comment]
Coding at blind isn't a way todo it, unless you know every call and parameters.

**Comment by subkanthi** [comment]
@gsantner Also the plan for this is to automatically prioritize or rearrange after every entry or is the plan to have a button to rearrange.

**Comment by gsantner** [comment]
I don't use or have ssen such feature in any of my clients, don't know the exact the flow. I will not implement this, but open for PRs.

I have only one important point: Make it to support Ascending and descending, everyone has different approaches for ordering.

automatic: **no**. please only implement it non-continued. Maybe at begin/finish of editing, but never while editing, as in only manually via action. 

* Stuff flying around while editing is not very nice, 
* also not when closing keyboard and the new task magically disappears
* and also not the possible workaround to jump the cursor to the resorted line - other text than before gets visible

**Comment by subkanthi** [comment]
Hi @gsantner , Not yet will get to this sometime by the end of the week.

**Comment by gsantner** [comment]
don't really want to stuff the app with libraries^^

this one need overridden compare/equals methods I think

**Comment by subkanthi** [comment]
@gsantner  I looked at it, In Document.java , the list of ToDo items are stored as one string in _content, its going to be difficult to order it, please let me know if Iam looking at the right one.

**Comment by gsantner** [comment]
For todo list you have to look into SttTask/SttTaskParserExtensioned, SttCommander. there you have basically need to put in file and run collection.sort(comparator) - and implement some comperators

**Comment by gsantner** [comment]
has somebody started working on this?

**Comment by goldmanm** [comment]
@gsantner, thank you again for a great app. This feature would be really awesome. I'd be interested working on it, though I am busy for the next 6 weeks. If someone else hasn't started working on it in late December, I can start working on it.

Just to clarify the desired user interface when the sorting shortcut is clicked, a box appears where the user selects:

```
priority, ascending
priority, descending
context, ascending
context, descending
project, ascending
project, descending

cancel       OK
```

and then the sorting happens. 


Also, what is the desired sorting for items with multiple contexts or projects? Should item be placed in the first alphabetical context/project which matches any of the item's context/projects? Should the item be duplicated in all contexts/projects (I think this is a bad idea)? Something else?

**Comment by gsantner** [comment]
Done via #449 and https://github.com/gsantner/markor/commit/47721f68909222ef986bce15cd0e359bc6c098c0
Thanks @goldmanm ! :tada:

**Comment by esmoak** [comment]
I was going to put in a feature request for this, but I saw this and thought I would tag @goldmanm to see if Sort by "Creation Date" and "Completion Date" could be added, hopefully without too much difficulty? If Gregor would be open to the addition.

If I have a workout log in todo format, I can sort by the `@` and the `+` or the A-Z priority, but I can't get it back to chronological. (Probably my fault for the bastardization of the todo.txt format. :)  )

**Comment by gsantner** [comment]
Should be very easy to implement :)

**Comment by mohammadazeemwani** [comment]
> automatic: **no**. please only implement it non-continued. Maybe at begin/finish of editing, but never while editing, as in only manually via action.
> 
> * Stuff flying around while editing is not very nice,
> * also not when closing keyboard and the new task magically disappears
> * and also not the possible workaround to jump the cursor to the resorted line - other text than before gets visible

Nice call @gsantner. I was going here and there to look for automatic ways; Now I am settled why it is not a good thing (at least on mobile devices)
