### ISSUE TITLE
View mode - text rendering chinese characters

### ISSUE THREAD

**Issue by MUG-chen** [gsantner/markor#2110]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

Hi.
I've encountered a bug of View mode, and for now, I havn't searched a good solution for it.
Actually, If I edit a files with Markdown, and the language I used is not the same with the language in setting, then the view mode will not display the format i write such as ****(bold) or **(italic) correctly. When i changed the language to the same, it will show  the format normally.
I hope this problem could be dealed properly, Thanks.
(By the way, I'm not a native English speaker, please ignore the mistake before, lol)

### Steps to reproduce

1. My system language is English, and i write a Chinese markdown file, as i talked before, the bold and italic style aren't showed correctly
2. When i switched the setting language to Chinese, It has solved.

### Information

Android version: 13
Device: Oneplus 11 (PHB110)
App Version: 2.10.9

the picture below is the edit mode
![Screenshot_2023-09-20-11-35-13-49_7aabe639e29ea39a625bdcb66fe7cfab](https://github.com/gsantner/markor/assets/88625388/9695e11a-882b-4498-abe8-e8e77523217a)

the picture below is the view mode (system language has been set as Chinese)
![Screenshot_2023-09-20-11-35-03-87_7aabe639e29ea39a625bdcb66fe7cfab](https://github.com/gsantner/markor/assets/88625388/841738b7-976b-4b27-95fb-c58f3489ab35)

the picture below is the view mode (system language has been set as English)
![Screenshot_2023-09-20-11-38-53-66_7aabe639e29ea39a625bdcb66fe7cfab](https://github.com/gsantner/markor/assets/88625388/5ce00ad7-3767-4552-865c-fa08a5a60e62)

### Source

F-Droid

### Format / File type

Markdown

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
Maybe the system uses a different font when you switch the language? There are many variation for example of Noto font.

**Comment by gsantner** [comment]
Try settings a different/custom font in the Markor settings. Maybe it helps.

**Comment by gsantner** [comment]
Seems to be device specific or system configuration specific.

Closing.
