### ISSUE TITLE
Allow creation of 'Share Into' shortcut vwidget without enabling 'Launcher (Special Documents)'

### ISSUE THREAD

**Issue by dvdmle** [gsantner/markor#2113]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

1. **The "Launcher (Special Documents)" option includes a "Share Into" launcher for the share dialog**
2. **This should be one of the options for the shortcuts available when long-pressing the app, like QuickNote and To-Do**
---
3. (Bonus technical stuff I don't quite understand) I'm a Tasker user, so I'd like to be able to launch this share dialog as one of the app's unique 'activities.' I'm able to do this when the Special Documents setting is enabled, but not when it's disabled. All I know is that you're generally able to do this when apps have these sort of long-press launcher shortcuts, but I don't know if those things are connected. 

### Information

Android version: 13
Device: Pixel 5a, CalyxOS
App Version: 2.10.9

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
Hm, I don't like to make additional settings options for this. Usually launcher software have the option to hide specific starts in their app overview. Suggesting to use that if you just don't like to see that stuff.

**Comment by gsantner** [comment]
Happy hacking!
