### ISSUE TITLE
Does not respect file extension

### ISSUE THREAD

**Issue by kaeza** [gsantner/markor#212]
The app does not respect file extension/format. For example, Todotxt's format docs are previewed as `todo.txt` even though the file is named as `.md`.

![a](https://lut.im/5tM6ICwlHB/k36DgLoRlGabFFQB.png)

Markor 0.3.4 from F-Droid.

**Comment by gsantner** [comment]
md and txt are both extensions for plaintext, and the code does what it should - if the filename starts or ends with todo it loads todo.txt format.

**Comment by kaeza** [comment]
Ah ok. Good to know.
