### ISSUE TITLE
New Logo Proposal for Markor

### ISSUE THREAD

**Issue by mdnazmulhasan27771** [gsantner/markor#213]
Hello,
This my logo/Icon design for your project. It's free for your project.

I design this logo using adobe illustrator cc 2017. I hope you like this logo.

![standard notes beta](https://user-images.githubusercontent.com/35112507/38352012-ac984110-38d3-11e8-8499-c3c1c8bb8090.png)

If you need anything change please contact me

Md Nazmul Hasan
Email : mdnazmul.hasan27771@gmail.com

Thank You.

**Comment by gsantner** [comment]
hey thanks!

I already changed the project not so long ago, and I think it went out very well.

I may use it in some other place of the app, but the app icon wont get changed for now. There are still many other places of lack of good artwork and design in Markor ;).

**Comment by mdnazmulhasan27771** [comment]
ok, tell me where you use this icon??

**Comment by gsantner** [comment]
The actual project icon?

**Comment by mdnazmulhasan27771** [comment]
ok as your wish.

**Comment by gsantner** [comment]
I asked for clarification, this was not a answer :D

**Comment by mdnazmulhasan27771** [comment]
yes, this is perfect for your project.

**Comment by gsantner** [comment]
Sorry, I think we are talking on different topics..

I said the project icon is used everywhere, I didnt say anythin about your proposal or its planned use :). - I dont plan to change the project again now.
