### ISSUE TITLE
Basic color scheme option doesn't apply in latest version

### ISSUE THREAD

**Issue by bromelio** [gsantner/markor#2138]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

Very nice app, but can you please make the background color **white**? Or better yet custo mizable? **Please?**

### Information

Android version: 11
Device: Android Phone
App Version: Latest

### Source

Google Play

### Format / File type

Markdown

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
For the editor/viewer you can freely select a color in the settings. And thats what of Markor you usually use most of the time.

**Comment by bromelio** [comment]
Thanks for your super-fast answer, and I also found that color option, great. Just the background keeps grey, even if I chose white (#fffff). Menu items and the bottom bar are shown in true white however. Can I still do something myself or can I ask you to please make white white?

**Comment by gsantner** [comment]
Have you fully closed markor? It might need a restart so it takes 
affect. And as said, only applies to editor/viewer background.

**Comment by bromelio** [comment]
Yes, I have (now) fully closed the app and started it again. I even restartet my whole phone. And then, with those color settings...

![Color Settings](https://github.com/gsantner/markor/assets/8458358/b2af88f1-66c4-4ff3-8ff6-badab97c8174)

...I created a new, blank `.md`-file — that should be white with the above settings, right?

But please have a look for yourself, it's still (light) grey. And let me stress once again that you made a great app, many thanks, just in pure white it would look even better than this:


![Not quite white](https://github.com/gsantner/markor/assets/8458358/0d05e5b1-718c-4c92-92cf-ff3addba0710)

You see the difference between the bottom navigation bar (white) and the editor/viewer pane (grey), right?

I have the current version from the Play Store installed.

**Comment by gsantner** [comment]
OK looks like the colors don't apply at all. Do you see any green if you set to green? 

Am 21. Oktober 2023 19:51:21 MESZ schrieb bromelio ***@***.***>:

**Comment by bromelio** [comment]
Interesting. When I switch to green and create a new note, green flashes for a fraction of a second, before it turns grey again (without me doing anything in between). Then, in editor mode, it's sometimes green and sometimes grey again (most of the time grey). In preview mode it's _always_ grey.

Can you recommend me an .apk other than that from Play Store the color settings of which work or can I hope that there will be an update for this?

You know, otherwise Markor is really great and it doesn't limit width for fenced code blocks and syntax coloring works in contrast to similar apps...

**Comment by ulville** [comment]
For Preview mode you can change the background-color with inject head setting by editing css. 

``` css
  @media (prefers-color-scheme: dark) {
    html, body {
      background-color: black;
    }
    .post-item-tags {
      color: black;
    }
    .front-matter-container{
      border-bottom-color: white;
    }
  }

```

This is what I inject to have pitch black background in review mode. It's normally dark gray even I select "Black" in the theme option. Editor background does respect the black theme though.

**Comment by bromelio** [comment]
Thanks, but where can I do so?

@gsantner: are there any new developments regarding this issue? :-)

**Comment by gsantner** [comment]
No; But feel free to take.

**Comment by ulville** [comment]
> Thanks, but where can I do so?
> 
> @gsantner: are there any new developments regarding this issue? :-)

`Settings` >`View Mode` > `Inject -> head`

It's quite hard to edit it from there though. So I write it in the editor and then copy-paste it into the setting. Also don't forget to put your CSS inside `<style>...</style>` tag

**Comment by ulville** [comment]
@gsantner Does this issue block the release of v2.12 ? 

I came across to this when I was looking for the mermaid.js 10.3.1 update. Which is merged but will be released with 2.12 if I haven't read it wrong. New mermaid versions added so many nice features which I really miss when I'm using Markor. Especially the tickInterval support in gantt diagrams which is very essential for vertical smartphone screens

**Comment by gsantner** [comment]
@ulville 
No, generally said nothing / never blocks a release (except file saving is utter broken unreleased state). Though would be nice if it get fixed before release, when ever that is 😄

**Comment by ulville** [comment]
> when ever that is 😄

@gsantner anytime soon maybe? 😄 

This seems like the only issue left unfixed in the [Milestone](https://github.com/gsantner/markor/milestone/17) versus 13 fixed issues & improvements.

**Comment by gsantner** [comment]
As usual in most FOSS software. No ETAs : -). But usually it's every ~half year.

**Comment by gsantner** [comment]
As usual in most FOSS software. No ETAs : -). But usually it's every ~half year.

Milestone, marking, assignments, whatever are rather for searching and later finding what was done in a cycle. It's not to plan when what is done, that contributors decide fully by their own.

**Comment by gsantner** [comment]
Please check with upcoming release [here](https://github.com/gsantner/markor/actions?query=branch%3Amaster+actor%3Agsantner), a test APK can be downloaded there to check if it works better.

I found it working in current master state.

![screenshot-2024-03-27__04-58-43](https://github.com/gsantner/markor/assets/6735650/72589608-a33d-4b6d-92a3-baef42fa51ed)
