### ISSUE TITLE
Cannot open app when data is stored on SDCard (in case Sdcard changed or is missing)

### ISSUE THREAD

**Issue by tenzap** [gsantner/markor#2146]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

Markor is configured to take the files from a folder on my SDCard.
I had to change my SDCard. So I copied all files to the new sdcard and inserted it into the phone.

Now, when I open markor, it says that it can't find/open the files and closes immediately. As a consequence I can't open it, and can't even update the location of the files.

Could you add support for this? Or how can I update the location manually without resetting the app?

### Steps to reproduce

1. Configure Markor to take the files from a folder on my SDCard.
2. Copy the files to another sdcard and insert it into the device
3. open markor. 

### Information

Android version: 13
Device: Xiaomi Redmi Note 9S
App Version: 2.11.1

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
Duplicate #2077

> Or how can I update the location manually without resetting the app

Exactly that, resetting app data. Or waiting.
