### ISSUE TITLE
Unexpected highlighting

### ISSUE THREAD

**Issue by pyoy** [gsantner/markor#2149]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [x] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

Some codes are unexpectedly "highlighted" in edit mode, such as the following:
```
/usr/lib64/libssl.so.3.0.7
/usr/lib64/libcrypto.so.3.0.7
/usr/lib64/libc.so.6
```
When not marked as a code block, the second half of each line will be displayed in code highlighting. This is redundant and unnecessary. Can this small problem be improved?

### Steps to reproduce

No need to do anything

### Information

Android version:  9
Device:  vivox21a
App Version:  2.11.1(148)

### Source

Google Play

### Format / File type

Markdown

### Additional info / Log

```shell
-
```

**Comment by harshad1** [comment]
Yeah. Our current link highlighting regex means that pretty much anything in the form `abc.xyz` will get highlighted as a link.

What we need is a regex which will match all links but not file names etc. If you can find one, please let me know and I will make a PR to fix this.

**Comment by gsantner** [comment]
URL highlighting has been improved many times over the last years, even the builtin Android logic doesn't do the trick which you think should work well enough for all cases.

So, if you want to have it improved - don't wait for it to happen by itself, please implement it and create a merge request. Thank you.

Related: <https://github.com/gsantner/markor/discussions/2089>
