### ISSUE TITLE
Setting to list all notes in directory

### ISSUE THREAD

**Issue by DominiqueSite** [gsantner/markor#2151]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

In the 'Files' tab, in the top-right menu for sorting options, an option should be added to **ignore folder hierarchy**. This would result in listing all notes in the given directory, regardless of directory hierarchy.
This feature would allow users to sort individual notes according to 'last edited on' attribute, even if they are in different sub-directories.

### Information

n/a

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
Sorting file list requires lots of file requests (disk I/O) and the more files to list/sort the worse performance gets. When a user enables this, it can break the app.

If you want to recursive list files, I suggest to use the search, which may be used with regex.  
Or, store your files in a single folder. This way it works the same for all applications - all files listed.

I can't tell you what to do, but I don't wanna introduce this to Markor.

**Comment by harshad1** [comment]
This in whichever folder works well. Bonus points: you can filter file types etc as you like

![Screenshot_20231204-104254](https://github.com/gsantner/markor/assets/1940940/59aaab03-48ba-4009-b441-6734824c085a)
