### ISSUE TITLE
Crash on rotation when date selection dialog is open

### ISSUE THREAD

**Issue by XYIheng** [gsantner/markor#2152]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

When I click calendar in todo file, and then rotate the device, app would crash.

### Steps to reproduce

1. click To-Do
2. click calendar  
3. rotate device
4. app would crash

### Information

Android version: 8.0
Device: 
App Version: 
2.11.1

### Source

GitHub Releases

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by harshad1** [comment]
I have a fix for this in #2148.

Issue was due to maintaining activity reference. Now we 
1. Call `getContext()`
2. Suppress the recreation in `onCreate`. The callback references will be broken and trying to maintain them across a rotation is a PITA
