### ISSUE TITLE
Bug report: "Recently viewed documents" not updated after I view some documents

### ISSUE THREAD

**Issue by XYIheng** [gsantner/markor#2153]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

After I view some documents and enter the "Recently viewed documents", the viewed documents don't display. If I kill and restart the app, the viewed documents will appear in the "Recently viewed documents"

### Steps to reproduce

1. open some documents
2. enter the "Recently viewed documents"

### Information

Android version: 8.0 and13.0
Device: 
App Version: 2.11.1

### Source

GitHub Releases

### Format / File type

Not specific

### Additional info / Log

- I also noticed there exists a same related bug report and fix in [1478](https://github.com/gsantner/markor/issues/1478), but seems the bug occurs again

**Comment by harshad1** [comment]
Drag down to refresh in the recently viewed list?

**Comment by XYIheng** [comment]
> Drag down to refresh in the recently viewed list?

drag down to refresh still not work for this issue @harshad1
