### ISSUE TITLE
Assign extension to format

### ISSUE THREAD

**Issue by dcdom2** [gsantner/markor#2159]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

For example, treat `*.abc` files as `todo.txt` or as `*.md`.

### Information

App Version: 2.11.1

### Source

F-Droid

### Format / File type

Not specific

**Comment by harshad1** [comment]
You can set the file type for any file (regardless of extension) and it will be remembered for that path

**Comment by dcdom2** [comment]
What I meant was to apply for all files of that format. If you have many, it becomes difficult to do it manually for each file.

**Comment by dcdom2** [comment]
`*.tsv` and `*.tab` (tab-separated value files) for example. I also use custom extensions on my synced folders between desktop and mobile (I use specific non-default viewers on PC and would like to let Markor parse them as intended).

**Comment by gsantner** [comment]
So tsv and tab are in CSV  i gueys?

**Comment by dcdom2** [comment]
Right.

**Comment by gsantner** [comment]
But why do you not use .csv? Makes your live easier :D.

**Comment by dcdom2** [comment]
Because csv has no spacing to allow for realistic manual editing 🤷‍♂️

**Comment by gsantner** [comment]
I guess you have your reasoning, which doesn't need to be questioned. I just can recommend not to use whitespace of any kind as separator.

tav and tab can be added to Markor CSV default mapping, I don't see a big problem by that.

**Comment by dcdom2** [comment]
For simpler files, it is very useful.

On PC, there is a great [extension](https://marketplace.visualstudio.com/items?itemName=ctenbrinke.vscode-tsv) for vscode which automatically formats (only visually) the tsv file, making manual editing convenient.

>tav
I know this is probably a typo but it is tsv

While you are at it, can you do `psv` (pipe-separated) too. Thanks :)

**Comment by dcdom2** [comment]
For simpler files, it is very useful.

On PC, there is a great [extension](https://marketplace.visualstudio.com/items?itemName=ctenbrinke.vscode-tsv) for vscode which automatically formats (only visually) the tsv file, making manual editing convenient. Combine it with colors ([Rainbow CSV](https://marketplace.visualstudio.com/items?itemName=mechatroner.rainbow-csv)) and it is even better.

>tav

I know this is probably a typo but it is tsv

While you are at it, can you do `psv` (pipe-separated) too. Thanks :)

**Comment by dcdom2** [comment]
Thanks
