### ISSUE TITLE
Auto backup of settings

### ISSUE THREAD

**Issue by dcdom2** [gsantner/markor#2160]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

- It is a good practice to have an app automatically backup its settings/database to a user-specified folder and maintain a minimum of these backups (e.g. 5 daily backups) to allow reverting from a sticky situation. 🙂

### Information

App Version: 2.11.1

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
> It is a good practice to have an app automatically backup its settings/database to a user-specified folder and maintain a minimum of these backups (e.g. 5 daily backups) to allow reverting from a sticky situation. 🙂
The usual users (myself included) don't change markor settings every few minutes. Backup makes totally sense for things like messengers or documents/pictures, that are under change constantly. 

But for Markor settings, humbly said - do it manually once in a while manually if you feel the customized settings are worth to backup. We don't need auto magic here that anyway has little use.
