### ISSUE TITLE
[todo.txt] Improve highlighting speed for todo.txt format files

### ISSUE THREAD

**Issue by dcdom2** [gsantner/markor#2162]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

For larger files, enabling syntax highlighting makes the app sluggish. Bold/italic can be a lighter substitute for it.

### Information

App Version: 2.11.1

### Source

F-Droid

### Format / File type

todo.txt

### Additional info / Log

```shell
-
```

**Comment by harshad1** [comment]
All font effect are achieved with spans. Bold and Italic won't make a difference to perf. How big a todo file (line count) are you working with?

**Comment by dcdom2** [comment]
> How big a todo file (line count) are you working with?

Some of them have thousands (not tasks, the format is just convenient).

**Comment by harshad1** [comment]
The problem is that the spans needed for inter-line spacing cannot be dynamically added / removed.

**Comment by harshad1** [comment]
Changed title to better reflect what actually needs to be done.

**Comment by gsantner** [comment]
Yes, things might get sluggish depending on hardware and size of file. 

Improvements are regularly done, as good as possible with the highlighting base around. If further improvements are wanted, feel free to make them and make a merge request so everyone can benefit.
