### ISSUE TITLE
Parse markdown inside todo.txt

### ISSUE THREAD

**Issue by dcdom2** [gsantner/markor#2163]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

There are already desktop apps that support markdown formatting (e.g. bold/italic) inside todo.txt. I don't need to tell you how helpful MD is. For example, making the task title bold.

This can be off by default.

### Information

App Version: 2.11.1

### Source

F-Droid

### Format / File type

todo.txt

**Comment by harshad1** [comment]
It would be helpful if you also linked to these apps and any relevant standard.

**Comment by dcdom2** [comment]
> It would be helpful if you also linked to these apps and any relevant standard.

https://github.com/ransome1/sleek

**Comment by page200** [comment]
> Please use markdown if you want markdown.

Markdown doesn't have the features of todo.txt.

> todo.txt is supposed to be simple and lightweight

We don't oblige users to enable Markdown parsing for todo.txt. It can remain disabled in Settings by default, if you want.

> and I don't want to make it something, that in fact it is not.

The todo.txt format has flaws and has never been updated. Anyway, the proposed change is backwards-compatible, it won't confuse other todo.txt apps, and it doesn't contradict the todo.txt format. The todo.txt format doesn't limit how we render the file contents. You already have features that aren't prescribed by the todo.txt format, for example colors for priorities, projects, contexts, and dates, sorting by context and project, and so on.
