### ISSUE TITLE
Option to disable online media fetching by default

### ISSUE THREAD

**Issue by dcdom2** [gsantner/markor#2165]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

This is a privacy matter. When I open a "foreign" markdown file, the app automatically and without warning fetches linked images, etc. I understand that this is a feature not a bug, but you must be aware that it is abusable, which is why email clients have an option (or even the default option) to not load remote resources until requested manually by the user.

Thanks

### Information

App Version: 2.11.1

### Source

F-Droid

### Format / File type

Not specific

**Comment by dcdom2** [comment]
I don't know how to code unfortunately.

**Comment by harshad1** [comment]
@dcdom2 You could hire someone to do it :)

**Comment by dcdom2** [comment]
@harshad1 3rd world country. :)

**Comment by gsantner** [comment]
I don't consider such a option, not sure what it should bring - you can still connect to stuff in many other ways then images / img src.

What can be more interesting is to generally have all network acess disabled in the whole app, as far I know that however is only possible at compile time with the INTERNET permission.
