### ISSUE TITLE
[todo.txt] Option to show/hide hidden (h:1) todos

### ISSUE THREAD

**Issue by dcdom2** [gsantner/markor#2167]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

Currently, there are always shown.

### Information

App Version: 2.11.1

### Source

F-Droid

### Format / File type

todo.txt

**Comment by harshad1** [comment]
As we work on top of a text file (and markor is a text editor first and foremost) there is no way to hide tasks in the main view. What we can do is add support for matching arbitrary key:value pairs in the advanced search. So you can have views without the h:1 tasks showing.

**Comment by dcdom2** [comment]
> What we can do is add support for matching arbitrary key:value pairs in the advanced search. So you can have views without the h:1 tasks showing.

That would be great.
