### ISSUE TITLE
Remember backup directory

### ISSUE THREAD

**Issue by dcdom2** [gsantner/markor#2168]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

Currently you have to start navigation from the home folder every time.

### Information

App Version: 2.11.1

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
Actually I would say it's good that people have to select it manually explicitly. It ensures that it goes into the right directory and reduced the possibility ""oh I thought it placed it there"" and then it's gone.

**Comment by dcdom2** [comment]
I have to say that I don't like making things more difficult for everyone in the name of idiot-proofing. At least allow it through experimental features. 😕

**Comment by gsantner** [comment]
> I have to say that I don't like making things more difficult for everyone in the name of idiot-proofing. At least allow it through experimental features. 😕

Then please go ahead and make improvements, without breaking something or making more maintainence burden.
