### ISSUE TITLE
In file search queries: saved searches/views

### ISSUE THREAD

**Issue by dcdom2** [gsantner/markor#2169]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

For example, todo.txt files. Some searches I make repeatedly (e.g. tasks for @work today). It would be nice if I didn't have to type the full query every time.

If you decide to implement this by remembering search queries (whatever they are), then please allow at least one of:
1. pin a search to the top
2. delete a query/suggestion (to get rid of the one-off searches).

### Information

App Version: 2.11.1

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by harshad1** [comment]
There is a save button _right there_

https://github.com/gsantner/markor/discussions/1940

See save button and link to documentation for syntax

**Comment by dcdom2** [comment]
I can't find that advanced filtering window. Not in Markor or Marder.

**Comment by harshad1** [comment]
Tap on the title (discoverability is an issue for sure)

Advanced filtering only applies to Todo.txt files

**Comment by dcdom2** [comment]
Ooh, thanks!

Can I suggest making this the default search/filtering? And adding it to the To-Do tab?
