### ISSUE TITLE
Linkify geo: and xmpp: URIs

### ISSUE THREAD

**Issue by contrapunctus-1** [gsantner/markor#217]
It'd be helpful if Markor (I'm using v0.3.4 from F-Droid) rendered geo: and xmpp: URIs as links automatically, without requiring the link syntax.

**Comment by gsantner** [comment]
Suggest that over at <https://github.com/vsch/flexmark-java>. The possibilities for parsing/converting are endless, Markor is/should be lightweight and lightweight can't be filled by endless stuff ;).
