### ISSUE TITLE
Toast saying "File saved" when navigating away from the app

### ISSUE THREAD

**Issue by dcdom2** [gsantner/markor#2170]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

Just a peace-of-mind suggestion that the file was saved/app didn't crash.

### Information

App Version: 2.11.1

### Source

F-Droid

### Format / File type

Not specific

**Comment by harshad1** [comment]
We have a notice which should show if something broke during saving.

The entire contents of the note _should_ get shoved in your clipboard in such cases.
