### ISSUE TITLE
[todo.txt] inverse filters

### ISSUE THREAD

**Issue by dcdom2** [gsantner/markor#2171]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

For example, find lines *without* `@work` context.

### Information

App Version: 2.11.1

### Source

F-Droid

### Format / File type

todo.txt

### Additional info / Log

```shell
-
```

**Comment by harshad1** [comment]
`!@work` works

See https://github.com/gsantner/markor/discussions/1940. Please add comments there if you find bugs in the documentation.

**Comment by dcdom2** [comment]
Thanks
