### ISSUE TITLE
The Markor should not show the files in the ignore list.

### ISSUE THREAD

**Issue by snowyu** [gsantner/markor#2174]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

The Markor has the following files:

a.md
a.sync-confict-2023010111.md

add `*.sync-confict-*.md` to the ignore list

But the `a.sync-confict-2023010111.md` still here.

### Steps to reproduce

1.  create a.md and a.sync-confict-2023010111.md files in Markor
2. add`*.sync-confict-*.md` to  Settings -> General -> Ignore List

### Information

Android version: 12
Device: Boox Notes
App Version: 2.11.1

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
Please careful read the description of the settings option.

**Comment by gsantner** [comment]
Ignore option is about limiting the search as it is described in the option. Not about the file managers list.
