### ISSUE TITLE
Improve DokuWiki syntax support for newer DokuWiki features

### ISSUE THREAD

**Issue by Amarok24** [gsantner/markor#2177]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

Please add support for modern DokuWiki syntax. This should be quite straightforward since there is already Zig support which is a simplified version od DokuWiki.

### Information

Android version: 11
Device: Samsung Galaxy A40
App Version: 2.11.1

### Source

F-Droid

### Format / File type

Something else (-> Additional info)

### Additional info / Log

```shell
DokuWiki syntax
https://www.dokuwiki.org/wiki:syntax
```

**Comment by gsantner** [comment]
Feel free to improve the implementation of Markor WikiText format support.

As far I know it works somewhat fine for most wiki formats including Zim, DokuWiki & MediaWiki.

There is currently nobody active working on Zim (since a while), so contributions are very welcome.

**Comment by gsantner** [comment]
Does #2147 by chance already bring somewhat helpful improvements for this?

**Comment by gsantner** [comment]
Not any response ever. Closing. Not sure what is wanted here. But nobody else seems to seem to miss major new elements.
