### ISSUE TITLE
feature: ability to exit from editing to folders view with ONE swipe or click/touch.

### ISSUE THREAD

**Issue by ardabro** [gsantner/markor#2180]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

When I'm editing with virtual keyboard present, and I want to exit, I need to hide the keyboard first, then swipe.
It would be very nice to be able to do the same with only one swipe/click/touch.

### Information

Android version: 13
Device: Moto 30 Edge
App Version: 2.11.1 (148)

### Source

Google Play

### Format / File type

Not specific

**Comment by harshad1** [comment]
I don't think any application does this. You can use the default android navigation features to switch apps in one swipe etc.

**Comment by ardabro** [comment]
Of course, I didn't mean to make it like others, I rather brought an idea of how to make it better, more convenient...
And it wasn't about switching apps. It was about returning to the main screen of the same app (sorry for the imprecise wording).
Cheers!
