### ISSUE TITLE
some small problems that can be improved?

### ISSUE THREAD

**Issue by jack-liew** [gsantner/markor#2183]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

1.  In  code block of markdwon file,  can't see cursor.
![c98e5ed978e46614f64425e4a13fef6](https://github.com/gsantner/markor/assets/102201538/8d97b4c4-a5de-4533-a580-9f7bbf15a813)

2.  Will PC software be released?

### Information

Android version: 13
Device: XiaoMi
App Version: 2.11.0 - 147

### Source

GitHub Releases

### Format / File type

Markdown

### Additional info / Log

```shell
- Thanks for great work.
```

**Comment by guanglinn** [comment]
[An improvement](https://github.com/gsantner/markor/pull/2129#issuecomment-1772512303) for this cursor issue has been merged, you can see it in the next version.

**Comment by harshad1** [comment]
@jack-liew FYI there is also an option to disable code block highlighting under Edit mode settings, if you want that.

Point #2 is not something that is in the scope of this project IMO. I use vim. Others use vscode etc

**Comment by gsantner** [comment]
@jack-liew 
No I don't plan to make the desktop software counterpart of Markor.  
However there is countless of good software on desktop which you might combine and use depending on your personal needs.

The desktop space is quite saturated with good software. After all, back then I had no good counterpart for Markdown, hence the reason for Markor the exist. I created it to fill that space 😄 .

**Comment by jack-liew** [comment]
> @jack-liew 
> No I don't plan to make the desktop software counterpart of Markor.  
---

I really need to edit files on ftp - or webdav server, Will this function be added in the future?

Thanks for your reply.

**Comment by gsantner** [comment]
You can use your favorite ftp/webdav app (or look for a new one), and select open with Markor from there.
