### ISSUE TITLE
Update font file for Source Code Pro

### ISSUE THREAD

**Issue by Secret-chest** [gsantner/markor#2184]
# IMPORTANT
* App version: 2.11.1
* Android version/rom: Samsung Android 14
* Device: Galaxy A54 SM-A546B
* I accept that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

## Explain the Problem
What problem did you encounter? What did you expect to happen?

The Source Code Pro font included doesn't support Romanian characters `ăâșțî`. Please update it, as the current version does support them.

**Comment by gsantner** [comment]
@Secret-chest

Please feel free to update the file and make a merge request here. It only sounds like to require swapping out the font file.
