### ISSUE TITLE
Integrate git with Markor editor

### ISSUE THREAD

**Issue by lamyergeier** [gsantner/markor#2185]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

1. I use syncthing for syncing between my laptop and my phone, often there is sync conflict. I wish that markor could identify if a particular file is in a git repository (presence of .git folder somewhere up in the file path). 
2. When such files are edited may be it could offer a shortcut on editor so that user can manually decide whether to commit and save.
3. Also a shortcut key to do git pull and push would be necessary.
4. For example I would like to put todo.txt in a git repository

### Information

Android version:  14
Device:  Samsung A33
App Version: Latest

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
If you have some app that accepts sending Intents  - notifying that something should be pushed/pulled and opening the other app - that would be fine to add a shortcut to.

But I don't plan to add .. git support, cloning, pushing/pulling and especially merge conflict stuff ... to Markor. Synchronization is not what Markor does.

**Comment by lamyergeier** [comment]
Do you have any suggestion if there is already a text editor with integrated git support in Android (latest version)?

**Comment by harshad1** [comment]
Tasker and other apps can monitor a folder of files for changes. That solves 99% of the req here IMO

**Comment by guanglinn** [comment]
If we want to integrate, I think we can refer to these projects:

[MGit](https://github.com/maks/MGit)

[EasySync](https://github.com/phpbg/easysync)

**Comment by harshad1** [comment]
IMO using a local directory of files is a key feature of Markor as this allows us to easily synergize with other systems. Integrating a sync or version tracking system defeats this purpose. You would never see these as part of, say, vim.

**Comment by elyahw** [comment]
You can use git via an external app such as https://github.com/termux/termux-app

I have an *alias* to cd into my notes folder, add all changes and push them; all using a single command 'a'. You can assign it what ever you like.

**Comment by dot-file** [comment]
For anyone who will stumble upon this issue. There is [gitnote](https://f-droid.org/packages/io.github.wiiznokes.gitnote) for git integration, particularly for automatic commits.
