### ISSUE TITLE
Autosave & caption

### ISSUE THREAD

**Issue by AP2020C** [gsantner/markor#2188]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

## Autosave
I found some questions about not autosaving, but I have the opposite problem: the file saves automatically in real time (or so it seemed to me) and I cannot turn it off.
So I would like to suggest that we restore the manual save button, which seemed to be there in the past, giving the possibility
A) to have automatic saving
B) to have only manual saving
C) to have a file.md where I manually save, and in parallel a file.md.autosave that saves the changes in real time, so that if I want to undo the changes I can restore file.md. Pressing the save button should overwrite file.md. I would also like a button Save As.

## Wysiwyg
This is also a feature I have read about but not present in my version.

## Caption buttons.
At the bottom of the UI are numerous icons, many of which are not explanatory. I had to go into the options to find out what they mean. Adding a text caption would help.

### Information

Android version: 13
Device: Galaxy Tab
App Version: 2.11.1

### Source

Google Play

### Format / File type

Markdown

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
> Wysiwyg
> This is also a feature I have read about but not present in my version.

Not sure where you read about it. But it is, was never and won't be in Markor.
