### ISSUE TITLE
Added an option to synchronize preview and edit positions

### ISSUE THREAD

**Issue by naosense** [gsantner/markor#2189]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

 Currently, the preview window scrolling and editing position are separated. This is especially inconvenient when you're tweaking the text while you're skimming through the article. I hope adding an option to synchronize the preview and edit positions. Thanks in advance!

### Information

Android version: 
Device: 
App Version: 

### Source

GitHub Releases

### Format / File type

Markdown

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
Please browse existing issues before creating a new one. It has been asked a few times.

Thank you.

**Comment by naosense** [comment]
> Please browse existing issues before creating a new one. It has been asked a few times. Thank you.

sry, i do searched issues before i created this, maybe the keyword i choose is not right...

**Comment by naosense** [comment]
after i browse existing issues, i dont find any related ones.

**Comment by gsantner** [comment]
#679 #1070 for example
