### ISSUE TITLE
hope support custom template

### ISSUE THREAD

**Issue by Newdea** [gsantner/markor#2193]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

1. when I create new file in `Files`  tab,  i hope i can select custom Template, not just prebuild templates.
2. the custom template should in a folder which can be set in General setting `Save location` as `Notebook`. 
3. and inside template, it should support some variables, such as date, file.name, [syntax](https://silentvoid13.github.io/Templater/syntax.html), [functions](https://silentvoid13.github.io/Templater/internal-functions/overview.html), [scripts](https://silentvoid13.github.io/Templater/user-functions/overview.html), etc. 

### Information

Android version: 
Device: 
App Version: v2.11.0(147)

### Source

GitHub Releases

### Format / File type

Markdown

### Additional info / Log

```shell
- I like this app very much, thanks a lot~
```

**Comment by harshad1** [comment]
We have this functionality already.

folder is `<notebook>/.app/snippets` (configure it in Settings / Other

These files can be inserted as snippets in an existing file or as templates in a new file

supported features are

{{time}} for current time (HH:mm)
{{date}} for current date (yyyy-MM-dd)
{{cursor}} to place cursor
{{sel}} to replace with currently selected text (meaningless for a template)
{{uuid}} to insert a UUID4


In addition any string in backticks "`" will be interpreted as a date according to the java simple date format.

We thought about adding javascript support (and I even had a full test build) but dropped this for now. It _may_ be added back in the future, but IMO don't count on it.


I really need to document this functionality in detail :(

**Comment by Newdea** [comment]
thanks, and sorry just looked up issues did not look through readme.
it basicly work for me, but where can i configure the snippets location(dont want to use <notebook&gt;/.app/snippets folder. ), i didnt found it in Settings/Other





---Original---
From: "Harshad ***@***.***&gt;
Date: Sun, Dec 31, 2023 13:35 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [gsantner/markor] hope support custom template (Issue #2193)




 
We have this functionality already.
 
folder is <notebook&gt;/.app/snippets (configure it in Settings / Other
 
These files can be inserted as snippets in an existing file or as templates in a new file
 
supported features are
 
{{time}} for current time (HH:mm)
 {{date}} for current date (yyyy-MM-dd)
 {{cursor}} to place cursor
 {{sel}} to replace with currently selected text (meaningless for a template)
 {{uuid}} to insert a UUID4
 
In addition any string in backticks "`" will be interpreted as a date according to the java simple date format.
 
We thought about adding javascript support (and I even had a full test build) but dropped this for now. It may be added back in the future, but IMO don't count on it.
 
I really need to document this functionality in detail :(
