### ISSUE TITLE
Bug Report: Change File Format not Work 

### ISSUE THREAD

**Issue by XYIheng** [gsantner/markor#2194]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

I have a file named 'a.md' and I want to change the file format (three dot menu -> File settings -> Format -> Plain Text). But it fails. After I close the file, the file name is still "a.md" instead of "a.txt". 
However, if I open the a.md again and check the file format from (three dot menu -> File settings -> Format), it shows 'Plain Text' is checked.

### Steps to reproduce

1. open a file, e.g.,"a.md"
2. change the file format to txt (three dot menu -> File settings -> Format -> Plain Text)
3. close the file
4. see the error: file name is still "a.md"
5. open the file again
6. click three dot menu -> File settings -> Format
7. see the 'Plain Text' is checked

### Information

Android version: 8.0
Device: pixel2
App Version: 2.11.1

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
You are confusing file extension and file type/file format.   
The format option only changes the way how you take a look at the file, it not changes it's contents nor it's filepath / file extension.

What you want to do is renaming the file, not viewing a .md file's contents as plaintext.

**Comment by XYIheng** [comment]
@gsantner Thanks for your explanation! I understand it, this issue can be closed.
