### ISSUE TITLE
View mode: Remember scroll position

### ISSUE THREAD

**Issue by XYIheng** [gsantner/markor#2195]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

In a long text file. I scroll down and append some txt at the end of the file, then click view mode. The file goes to the beginning instead of keeping scroll position

https://github.com/gsantner/markor/assets/31406320/8314a63b-0825-422a-82b4-a5355c82ca1a

### Steps to reproduce

1. Open a long text file
2. Scroll down and append some txt at the end of the file
3. Click view mode
4. see the error: the file goes to the beginning 

### Information

Android version: 8.0
Device: pixel2
App Version: 2.11.1

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by harshad1** [comment]
Correlating edit to view position is very hard. Especially in a files with images etc. The best we can do is scroll to the same % as the edit mode. However this will be wrong as often as not

**Comment by XYIheng** [comment]
@harshad1 If not edit, just scroll to the end of the file, then change view mode. The bug also occurs

**Comment by gsantner** [comment]
duplicate #1025 . Please search issues before opening, thanks.
