### ISSUE TITLE
FileBrowser: File Modification Time not updated until app restart

### ISSUE THREAD

**Issue by XYIheng** [gsantner/markor#2196]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

Modifying a file does not update its modification time immediately. 
Refresh file list also not work.  
The file's modification time remains unchanged until the application is restarted.

### Steps to reproduce

1. open an existing file
2. edit it 
3. close
4. see the error: file modification time does not change

https://github.com/gsantner/markor/assets/31406320/1ba0560b-759a-4b54-9948-420c21b23023

### Information

Android version: 8
Device: pixel2
App Version: 2.11.1

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
@XYIheng Can you try a APK you can find on any of the development builds here <https://github.com/gsantner/markor/actions>? As the file metadata caching was reworked this should not be case in the master branch anymore.

**Comment by XYIheng** [comment]
@gsantner Hi, it still does not work for me. I try the apk here https://github.com/gsantner/markor/actions/runs/7493416005.
The file's modification time remains unchanged until the application is restarted.

**Comment by gsantner** [comment]
Does anybody else have the mentioned issue? I could not reproduce on master branch/Marder.

**Comment by guanglinn** [comment]
@gsantner We should call notifyItemChanged(position) or notifyDataSetChanged() after some files were modified.

**Comment by gsantner** [comment]
On pull down reload we also do that as far I know. But the info might be cached somewhere
