### ISSUE TITLE
Bug: Click file format incorrectly jumps to 'Search documents' dialog

### ISSUE THREAD

**Issue by XYIheng** [gsantner/markor#2197]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

Open a note, click the format (three dot menu -> File settings -> Format ->), and click the selected format (e.g., if Markdown is selected, then click Markdown) -> error:  The search documents dialog appears.
Is this the expected behavior or bug?

![image](https://github.com/gsantner/markor/assets/31406320/3e5a1336-a554-42e9-9b93-193fb379896d)
![image](https://github.com/gsantner/markor/assets/31406320/437b4eee-46eb-43b6-93ca-e52e20bd6e4f)

### Steps to reproduce

1. open a note (e.g., a.md)
2. click the format (three dot menu -> File settings -> Format -> Markdown)
3. see the error

### Information

Android version: 8
Device: pixel
App Version: 2.11.1

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by harshad1** [comment]
Sounds like a missing break in a case statement.

This appears to be fixed in the next release.
