### ISSUE TITLE
FileManager: New file, file type not consistent with suffix

### ISSUE THREAD

**Issue by XYIheng** [gsantner/markor#2199]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

When I want to create a new file with type "todo.txt", the suffix is still ".md".
It only happens after the first time I click the FAB
![image](https://github.com/gsantner/markor/assets/31406320/33959f8d-5e05-4b07-9d98-978c1e49a2a9)

https://github.com/gsantner/markor/assets/31406320/2b7a94de-f069-433c-af01-5b6a08f78fa2

### Steps to reproduce

1. Click FAB 
2. Click type
3. Select todo.txt
4. See the suffix after the file name automatically changes to ".txt". That's right
5. Click back
6. Click FAB again
7. See the error: the file type is "todo.txt", but the suffix is ".md"
8. If click ok to create the file, you will create a md file instead of todo.txt file

### Information

Android version: 8.0
Device: 
App Version: 2.11.1

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by harshad1** [comment]
Yeah, the new file dialog needs some TLC. I have this a plan to make some improvements here.

- Better sync between ft and extension
- Remember template per ft
