### ISSUE TITLE
Not registered as Filehandler?

### ISSUE THREAD

**Issue by dynobo** [gsantner/markor#22]
#### General information
* **Device:**  Moto G Falcon
* **Android Version:**  Android 7.1.2
* **App version:** v0.1.2

###
1. Click on .md or .txt file in e.g. any File Explorer
2. Select "Open with"
3. List with Apps is shown, but no Markor

#### Expected Results ####
Markor can be selected to open markdown files that were "opened with" and/or "share file via".

**Comment by gsantner** [comment]
I cannot tell you which version made changes regarding this, but it works in latest git version

**Comment by dynobo** [comment]
Just installed the new Update (1.3). Still not working for me.

**Comment by gsantner** [comment]
I just tested it again, on 2 versions of android, and it worked in both cases. I cannot reproduce your problem. Your filemanager can also have bugs.

![screenshot_20170927-163951](https://user-images.githubusercontent.com/6735650/30928755-bf3b98c8-a3bc-11e7-894e-2ec776571143.png)

**Comment by gsantner** [comment]
If someone can reproduce this, feel free to fix it. I cannot reproduce it on any of my devices.

Register on <https://hacktoberfest.digitalocean.com/>, send a PR to fix this and get your t-shirt for free :).

**Comment by sio** [comment]
I can confirm this issue exists in current version from Play Market (Markor 0.1.3). I run it on LG L90, Android 5.0.2

If you need any extra information, please ask. I'm not familiar with Android app development, so I don't know how to debug this in my own.

**Comment by gsantner** [comment]
an update with current code (0.1.5) should be out in half an hour. pleade tell if still happens

**Comment by sio** [comment]
I've just updated to 0.1.5 from Play Market. Issue still exists

**Comment by gsantner** [comment]
can you post a log? /logcat? what did you try?

**Comment by sio** [comment]
Maybe this will help: I use Markor mostly as external editor with MGit. When opening md files from MGit, Markor is listed among available applications. Not with default file manager though

**Comment by sio** [comment]
> can you post a log? /logcat? what did you try?

How can I get that log?

**Comment by gsantner** [comment]
> Maybe this will help: I use Markor mostly as external editor with MGit. When opening md files from MGit, Markor is listed among available applications. Not with default file manager though

With which file manager? I tried 3 different now, and every of them list markor...^^

**Comment by sio** [comment]
It's the default Android app, was there from the beginning: "File Manager", version 4.40.14

**Comment by gsantner** [comment]
It may too have bugs ;) try a different file manager

**Comment by gsantner** [comment]
> How can I get that log?

You can download the minimal adb/fastboot package on web. Then you can use `adb logcat -s net.gsantner.markor`  to start logging for markor. Then you have to produce the error/crash and see it on desktop

**Comment by sio** [comment]
>It may too have bugs ;) try a different file manager.

ES File Explorer and Solid Explorer both work fine with Markor, so the problem must be in the LG application then. Thank you.

>Then you can use adb logcat -s net.gsantner.markor to start logging for markor. Then you have to produce the error/crash and see it on desktop

I'll try that later. If it will show anything interesting I'll post it here

**Comment by kRkk** [comment]
But you can open only `.md`, `.markdown` or `.txt` aren't supported

**Comment by gsantner** [comment]
yes. May be extended to markdown too
