### ISSUE TITLE
Suggest putting the action buttons in two scrollbars

### ISSUE THREAD

**Issue by guanglinn** [gsantner/markor#2202]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

A lot of action buttons are put in just one scrollbar, this may make some commonly used actions scattered, so that the efficiency of editing is reduced.

Like this, these buttons are put in two scrollbars.

![Screenshot_20240111_210013_net.gsantner.markor_test.jpg](https://github.com/gsantner/markor/assets/60415467/c7b2d7d3-6d5e-4191-933d-346db047b8ad)

### Information

Android version: 12
Device: Huawei Nova 8
App Version: 2.11.1 (148)

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
Sorry but for my taste it makes the situation not better to be honest. It also makes it easier to trigger the wrong action/2 actions.

What users mostly miss out what button is for what, here a alternative concept like a dialog with all actions named could help (similar to ReorderActionsButtonActivity but as dialog).

**Comment by guanglinn** [comment]
The number of the buttons on the bottom bar has reached 26 in Markdown. If we scroll slowly, it can takes us seconds to find the button we need. But if we scroll quickly, it might be easy to miss the button we need, and It's hard to keep the right scroll speed. So it may be necessary to think about a better (friendly and efficient) way to display these buttons.

**Comment by elyahw** [comment]
I am for adding an option in settings to hide the bar completely.
