### ISSUE TITLE
FileBrowser: Scrollbar not shown

### ISSUE THREAD

**Issue by elyahw** [gsantner/markor#2209]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

1. It would be nice if the notes list had a scroll bar to give the user a sense of location among the notes (consider a list of 100s of notes).

### Information

Android version: 13
Device: Pixel 5a
App Version: 2.11.1

### Source

GitHub Releases

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
If there is more content then what fits to one screen page, scrolling a 
bit reveals the scrollbar. That should be the case everywhere in the app.

**Comment by elyahw** [comment]
I see. This would be a bug then. I have 490 notes in a single folder, and I can't see the scrollbar at all..

**Comment by guanglinn** [comment]
The scrollbar has been added in PR #2213.
