### ISSUE TITLE
Buttons for selected item are not visible

### ISSUE THREAD

**Issue by bno1** [gsantner/markor#221]
#### General information

* **App version:** 
v0.3.5 F-Droid

* **System:** 
Xiaomi Redmi Note 3 Pro (kenzo)
Nitrogen OS Oreo 20180419
Android 8.1.0

#### Description

When selecting a note in the Notebook tab, the top right buttons are dark and I could not distinguish them from the dark blue title bar.

Here is a screenshot: [screenshot_markor_20180423-231548](https://user-images.githubusercontent.com/6632595/39151135-ff6765ec-474c-11e8-9133-32f27d6885fa.png)

#### Log

[log.txt](https://github.com/gsantner/markor/files/1939896/log.txt)

**Comment by gsantner** [comment]
thx
