### ISSUE TITLE
Briefly highlight a note when clicking 'back' button

### ISSUE THREAD

**Issue by elyahw** [gsantner/markor#2210]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

1. Say you have many notes. A note of them is opened (not necessarily the first one). The user edits it and goes back.
2. There is nothing that tells the user which note was just opened.
3. It would be nice if this note was briefly highlighted, this would give the user a good sense of location.

### Information

Android version: 13
Device: Pixel 5a
App Version: 2.11.1

### Source

GitHub Releases

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by guanglinn** [comment]
Hi, @elyahw , this feature you expected has been implemented in PR #2211.

**Comment by elyahw** [comment]
Thank you. It's very good. The one I had in mind is to be highlighted briefly then the highlighting would disappear. Unfortunately I have no experience in Android so I can't comment on the implementation.. Thanks!

**Comment by guanglinn** [comment]
Thanks for your suggestions, I made some improvements again.

**Comment by guanglinn** [comment]
Hi, @elyahw , the feature I improved is [here](https://github.com/gsantner/markor/pull/2254#issuecomment-2067562850), but this PR was not merged.
This feature has been modified by @harshad1 , it now cannot automatically highlight the file item when you click 'back', so which may make us feel inconvenient.

**Comment by gsantner** [comment]
@guanglinn  / @harshad1 
Humbly said: We rewrote that blinking many times now and it somewhat never worked THAT really well or was that good recognizable. Instead of reworking it for the Nth time, might be better to take a different approach. I.e. existing scroll + constant highlighting of that last item. So no animation/blinking/transparency.

**Comment by harshad1** [comment]
Right now we blink when we
1. navigate back in the file explorer
2. show file location with the 'file browser' button

Blinking the file when one navigates back from the file should be doable.

Or we could use / simulate the android ripple effect if blinking is considered ugly

**Comment by guanglinn** [comment]
Windows File Explorer is well done in the sense of location. It doesn't have complex animations.

Better sense of location involves file/directory location highlight and accurate scrolling position restoration.

**Comment by guanglinn** [comment]
Android has specific methods `recyclerView.getLayoutManager().onSaveInstanceState()` and `recyclerView.getLayoutManager().onRestoreInstanceState(state)`, which can accurately restore scrolling position. But `recyclerView.getLayoutManager.scrollToPositionWithOffset(position, 1)` cannot accurately restore scrolling position.

**Comment by harshad1** [comment]
What I am getting is that consistent scroll positions as one navigates would be a good first step

**Comment by harshad1** [comment]
@guanglinn @elyahw In #2307 I have added saving and remembering scroll positions. Please review and test.
