### ISSUE TITLE
Doesn't search into pdf content

### ISSUE THREAD

**Issue by macsyyyyyyy** [gsantner/markor#2214]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

Searching file contents works for txt and csv but does not work for pdf files

### Steps to reproduce

1. Select a pdf with a keyword inside and put it into folder "DOCU"
2. open folder "DOCU" into the app
3. Search for that keyword, with the content flag ON

### Information

Android version: 12
Device: moto g72
App Version: 2.11.1

### Source

Google Play

### Format / File type

Something else (-> Additional info)

### Additional info / Log

```shell
-pdf
```

**Comment by gsantner** [comment]
Content search does search **text** content, not binary.

PDF is binary. Markor is a text editor not a PDF editor after all.
