### ISSUE TITLE
Add the ability to choose a default note Type and Template

### ISSUE THREAD

**Issue by elyahw** [gsantner/markor#2217]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

To create a new note currently you have to:
1. Press the '+' button.
2. The default is set to *Markdown* type and *Empty file* template.
3. Type the title and hit 'ok'.

I have to scroll down and pick a template which puts the creation date in the title, such as *Jekyll post*. This makes the action of creating a new note tedious.

**Suggestion:**
Why not provide the ability to choose the default note *Type* and *Template*?

### Information

Android version: 13
Device: Pixel 4a
App Version: 2.11.1

### Source

GitHub Releases

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by harshad1** [comment]
This is one of the things I plan to work on next - Remember templates per file type.
