### ISSUE TITLE
Add ability to set a default note title for the "Empty file" template

### ISSUE THREAD

**Issue by elyahw** [gsantner/markor#2218]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

A nice to have feature is the ability to be able to set a default note title for "Empty file" template. 

This would allow that every created new note would automatically start with the string "YYY-MM-DD-HH.MM" (for example). Currently I have to scroll down, choose jekyll post and delete default lines to achieve this purpose.

I suggest to add the ability to set a default name, e.g.:
`%Y-%M-%D.%H.%M Note`

### Information

Android version: 13
Device: Pixel 4a LineageOS
App Version: 2.11.1

### Source

GitHub Releases

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by harshad1** [comment]
We support time interpolation in snippets / templates. These can be inserted on creation from the new file dialog or after creating the note using an action.

See https://github.com/gsantner/markor/discussions/2221

I have been very lax at documenting all the features I have added to markor. I will try to remedy that over the next few months.
