### ISSUE TITLE
Wiki-links

### ISSUE THREAD

**Issue by evxeon** [gsantner/markor#2220]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

I use the Obsidian app and there is an option to use wiki links instead of markdown links. Do you plan to implement wiki-links in Markor? In terms of writing and editing wiki-links look more convenient.

### Information

Android version: 13
Device: galaxy note 20 ultra SM-N9860
App Version: 2.11.1

### Source

GitHub Releases

### Format / File type

Markdown

**Comment by gsantner** [comment]
For the biggest part they should work, but be advised it not works generically with most markdown software. Don't use it.
