### ISSUE TITLE
Add ability to set a default note title to enable quicker new note creation

### ISSUE THREAD

**Issue by elyahw** [gsantner/markor#2225]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

## Description

**The suggestion:**
I suggest to add a default note title, for example `yyyy-mm-dd hh-mm-ss.md` for the _Empty file_ template.

**Why?**
This will enable a quicker creation of a new note in two clicks: (1) press '+' button, (2) press ok.

**How is this an enhancement?**
1. This is an enhancement over the current behaviour which requires the entry of a new note name. Thinking about a new name for the idea you just had is not very important as the idea itself. Currently new notes have a default name of **my_note**, but it is greyed out and never used.

2. Adding this simple default title will perhaps allow us to get rid of the **QuickNote** tab which is titled "Quicknote.md" by default.

3. Another way of solving this problem is to add the ability to customise the title of the quick note, for example: `yyyy-mm-dd hh-mm-ss Quicknote.md`. After thinking about it again, I think this is better perhaps. I will leave this to be discussed.

## Information

Android version: 13
Device: Pixel 5a
App Version: 2.11.1

##### Source

F-Droid

##### Format / File type

Markdown

**Comment by gsantner** [comment]
Not speaking about everything, but

 > for example |yyyy-mm-dd hh-mm-ss.md| f

There is a template option called Jekyll. It makes a date related filename.

 > Adding this simple default title will perhaps allow us to get rid of 
the *QuickNote* tab which is titled "Quicknote.md" by default.

No, don't want to get rid of it. You may personally not have a use for 
QuickNote but others do. If you want to have every new info in a new 
file feel free to do that. QuickNote is there for a different reason, to 
quickly gather info and see everything at one glance. I use it i.e. as a 
kind of inbox where I remove things shortly after if I checked it out... 
or move it off to a dedicated file if it's something to keep.



>Message  ID: ***@***.***>

 > Another way of solving this problem is to add the ability to 
customise the title of the quick note, for example: |yyyy-mm-dd hh-mm-ss 
Quicknote.md|. After thinking about it again, I think this is better 
perhaps. I will leave this to be discussed.

This means you create a own file for everyday. Then you end up with like 
300 files a year, each with maybe 5 lines of text...and then you have to 
guess where you had the info :D.


Overall your points sounds a lot like you are looking for some "daily 
journal" kind of feature. You can search the Discussions I recall some 
cool script by users which help with that.

**Comment by gsantner** [comment]
Android Dialogs generally are expected to have maximum 3 buttons: 
Positive (i.e. OK), Negative (i.e. Cancel), Neutral (i.e. More info). 
That's also what all the API's support.Message ID: 
***@***.***>

**Comment by harshad1** [comment]
IMO the solution proposed here is nice. I will try adding it when I start working on improving the new file dialog.

Not sure if I will be able to get to it before mid-april though.

**Comment by gsantner** [comment]
Suggestion: To  rename template to "Content template", and add a third dropdown section - Filename template. Which can inlcude i.e. what we have currently in terms of Jekyll special rules, among others.

**Comment by Toremok** [comment]
Hi,
I was redirected here and wanted to vocalize that i'd also like an option to "auto-date" the filename before creation. Ideally that would happen on my own custom template, so I can create journal-like files for recordkeeping with boilerplate information in the file. Just adding my name to the list for the feature request.

Thanks!
