### ISSUE TITLE
FR: markor should not remove the empty lines in a .todo.md/.todo.txt file for users to use obsidian together!

### ISSUE THREAD

**Issue by ccchan234** [gsantner/markor#2230]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

hi.

if you rename test.todo.txt into test.todo.md, and you set to use .todo.txt format in markor, then both markor and obsidian can be used to modify this test.todo.md

obsidian need EMPTY lines above and below an entry.

e.g.

entry 1
(empty line)
entry 2
(empty line)
entry 3

in this way obsidian can do whatever magic on entry 2
.

however, in markor 's sort (sort by priority i think),
it will remove the empty lines above and below entry 2, making obsidian NO longer able to conside the above as THREE entry, but a new entry consisiting of 3 lines.

i have filed before:
https://github.com/gsantner/markor/issues/1943.

i saw others do use obsidian tgt /w markor.

on obsidian forum someone suggested me requesting this feature,
to add an OPTION to sort or not sort the empty lines?

https://forum.obsidian.md/t/todo-txt-anyway-to-use-link-to-together-with-markor/50484/5.

would like to see this implemented.
thank you

### Information

Android version: 
Device: 
App Version: 

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by harshad1** [comment]
Could you link to the appropriate obsidian spec?

**Comment by gsantner** [comment]
todo.txt sorting is for todo.txt content, of course you can ise it for other things as well.

BUT, I'm not keen on bloating the code with this, it's made for Obsidian/Markdown syntax, and not todo.txt. For markdown todos, you can use checkboxes i.e. which also support single lines as single actions.

Though what might work is treating one line as such and not add to the same paragraph. Maybe you can find such a option in Obsidian.
