### ISSUE TITLE
Incorrect URL highlighting

### ISSUE THREAD

**Issue by TimReset** [gsantner/markor#2232]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

Markor highlights some paths as URL:
eg /test/test.test/
test.test/ - will be showed as URL. That is incorrect.

Markor uses android.util.Patterns#WEB_URL 

Need to use more strict patter to find URL? (eg with required protocol - http(s), ftp, etc)

### Steps to reproduce

1. write /test/test.test/
2. Markor highlights it as URL.

### Information

Android version:  12
Device: Samsung 21 FE
App Version: 2.11.1

### Source

git master branch

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
Duplicate
