### ISSUE TITLE
Document-relative paths for external media

### ISSUE THREAD

**Issue by ravilov** [gsantner/markor#2234]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

Would be nice if relative media paths (for images etc) within a markdown document were relative to the document itself instead to the global Markor root. Then I could have things like `![](photos/001.jpg)` and a folder `photos/` wherever the document itself is, and it all just work as expected.

### Information

Android version: 14
Device: Samsung A53
App Version: 2.11.1 (148)

### Source

F-Droid

### Format / File type

Markdown

**Comment by gsantner** [comment]
It should bebrelatibe to the current file by default.

**Comment by gsantner** [comment]
Yes. Content uris often have something like 
content://external_storage/gibberish23980hd39d8h3198h as filename. No 
info where it is from / what is the actual real file path, and if it is 
even accessible by other app (i.e. Markor in this case).

Use Markor builtin file-manager to have proper full relative file 
access, embedding images etc.
