### ISSUE TITLE
Format: vimwiki

### ISSUE THREAD

**Issue by adlaurentius** [gsantner/markor#2237]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

I was under the impression that because wikitext was supported I would have syntax highlitighting when using the vimwiki format (not markdown, see: https://vimwiki.github.io/ under "Quickstart") but I can't seem to be able to get syntax highlighting on my .wiki files when using markor.

Would you be willing to merge vimwiki syntax highlighting support if a pull request was made? I haven't got a lot of experience with android development but I would be willing to give it a go. 

### Information

Android version: 11
Device: Alcatel 1S
App Version: latest

### Source

F-Droid

### Format / File type

Something else (-> Additional info)

**Comment by gsantner** [comment]
Have you tried manually setting the file format to wikitext at the top menu at the editor?

**Comment by adlaurentius** [comment]
I hadn't tried that, thank you!

Still, vimwiki has subtle differences from wikitext, like for example, H1 being
`= title =`

while at present in the editor with wikitext selected it is
`====== title ======` 

at present vimwiki headlines with only one` =` are not highlighted. 

It would also be nice to be able to select "vimwiki" in the "Type" menu and have Markor automatically change the file extension to .wiki

Is this something you would be willing to have added to Markor?
Is this something that you would accept

**Comment by gsantner** [comment]
Yes but preferably adjust/make fixes to the wikitext format as/if the differencies are rather such subtle.

**Comment by adlaurentius** [comment]
I tried to have a go at this, but I think it's out of my area of expertise. I will close it for now so that it doesn't stay idle, hopefully someone else who's interested will have a go as well.
