### ISSUE TITLE
versioning notes

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#224]
maybe take a look at these

https://github.com/google/diff-match-patch

https://mvnrepository.com/search?q=diff

https://mvnrepository.com/artifact/com.googlecode.java-diff-utils/diffutils/1.3.0
https://code.google.com/archive/p/java-diff-utils/

**Comment by gsantner** [comment]
There is normal undo/redo, otherwise always open for pull requests.

**Comment by sojusnik** [comment]
Thus a history of changes isn't on the roadmap at the moment?

**Comment by gsantner** [comment]
Everything can be on roadmap, the project is open for community contributions of any kind.
