### ISSUE TITLE
Format: FEN (chess board game related)

### ISSUE THREAD

**Issue by toolonely** [gsantner/markor#2241]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

I would like Markor to become [FEN](https://en.wikipedia.org/wiki/Forsyth%E2%80%93Edwards_Notation)-aware.

Something a la https://python-chess.readthedocs.io/en/latest/svg.html#chess.svg.board would be nice, as in whenever a document contains a FEN string, Markor could detect it and render a chess board image that is displayed. However, I imagine this would require adding more chess related library dependencies and shift Makor's focus from a general purpose text editor (albeit it already supports multiple niche things other than plain text / markdown format, most notable probably being todo.txt).

I'd be happy with Markor just detecting a FEN string, displaying it as link and letting me open it via sharing in a chess app (configured through Markor's settings) that is FEN aware, [DroidFish](https://github.com/peterosterlund2/droidfish) for example.

### Information

Android version: MIUI

### Source

F-Droid

### Format / File type

Something else (-> Additional info)

**Comment by harshad1** [comment]
I think this is niche and outside markor's scope.

Your best bet is to include the Fen string in a formatted link. Automatically detecting it is too hard and prone to errors.

**Comment by gsantner** [comment]
I would be open to add i.e. a .js file which does the rendering of FEN in whatever way in View-Mode. However I'm not really keen on adding a full format for this (no own file format option, no own highlighting, no own format classes etc).

**Comment by toolonely** [comment]
@gsantner 

Something like this?

https://github.com/andyruwruw/chess-image-generator

**Comment by gsantner** [comment]
Looks like! Not sure about dependencies and if you can easy make it i.e. one javascript file.

**Comment by toolonely** [comment]
I don't know what this action means, but to avoid misunderstandings, I have to say that that this feature request is from a pure end user perspective, thus doesn't imply any technical commitments due to my incompetence. I am trying to find a way to visualize FEN strings in vim on desktop and I made this suggestion hoping that oneday I'll be able to use my chess notes  in Markor as well on Android.

**Comment by gsantner** [comment]
Hello,

I add registration of .fen extension in #2439. This means .fen files will be opened in Markor texteditor with plaintext tools.

As you see nobody else shown interest on this topic. Apart of interest to implement, there also needs somebody to maintain it after introduction. I see neither to be the case hence more sophisticated support like chess rendering is unlikely.
