### ISSUE TITLE
First launch experience circles should be a little bit more visible

### ISSUE THREAD

**Issue by Porkepix** [gsantner/markor#2242]
# IMPORTANT
* App version: 2.11.1
* Android version/rom: Oreo (8.0)
* Device: Xperia XZ
* I accept that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

## Explain the Problem
What problem did you encounter? What did you expect to happen?

The first launch experience have circles showing which screen we're at and on how many of them. The circles not from the currect screen (the non-white ones) are currently not easy to see and should get a better contrast compared to the background color, ie. have them a little bit more clear.

## Steps to Reproduce
Launch Markor for the first time

<details>
<summary>
Screenshot
</summary>

![Screenshot_20240319-165652](https://github.com/gsantner/markor/assets/709500/4fb8092e-80ce-4498-99fa-14c7e78e87d5)

</details>

**Comment by gsantner** [comment]
![screenshot-2024-04-20__10-20-05](https://github.com/gsantner/markor/assets/6735650/3bbf9f17-c762-4048-b16c-ba559a1fa348)
