### ISSUE TITLE
Hide bottom bar when no action is selected

### ISSUE THREAD

**Issue by EthicalGhost** [gsantner/markor#2243]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

Is it possible to hide the bottom bar completely when no action order is seleted to show?
![Screenshot_Markor](https://github.com/gsantner/markor/assets/122081022/5f0635d8-b93b-436c-a9fb-bae4b1de3be1)

### Steps to reproduce

1. Launch Markor
2. In settings, unselect all action orders of any of your chosen file format (plain text or markdown)
3. Create a note in that chosen file format

### Information

Android version: 9
Device: Samsung Galaxy
App Version: 2.11.1

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
has been asked numerous times.
