### ISSUE TITLE
Attachment button does not react

### ISSUE THREAD

**Issue by biosaat** [gsantner/markor#2253]
# IMPORTANT
* App version: 2.11.1
* Android version/rom: GrapheneOS
* Device: pixel6a

## Explain the Problem
The clip button in plaintext files or todo list does not show any reaction at all. No error message is displayed.
All access rights to file system have been granted. 

## Steps to Reproduce
Open plain text file, hit clip button.

**Comment by biosaat** [comment]
Can I do anything to debug this?

**Comment by harshad1** [comment]
I will look into this

**Comment by biosaat** [comment]
Do you have any prediction on when this fix will be available in F-Droid?
