### ISSUE TITLE
支持打开其它软件创建的[[wiki]]链接将是个不错的方向

### ISSUE THREAD

**Issue by github770208646** [gsantner/markor#2256]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

1. markor是我手机上的主力软件，主要用于查看和简单编辑md
2. 同时在电脑上我会使用其它md编辑软件，并创建一些[[wiki]]格式的链接
3. 但这些[[wiki]]格式链接并不能在手机markor上打开
4. 虽然这种[标准md名称](完整路径)的格式被广泛应用，但[[wiki]]格式似乎也是一种被兼容的潮流
5. 注意是[[wiki]]而不是[[wiki.md]]

### Information

Android version: 10
Device: mi8se
App Version: 147

### Source

GitHub Releases

### Format / File type

Wikitext, Zim

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
write english.

**Comment by guanglinn** [comment]
请您使用英语描述 @github770208646
