### ISSUE TITLE
Settings rearrangement

### ISSUE THREAD

**Issue by elyahw** [gsantner/markor#2261]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

1. Open app, press "**More**". You will find dedicated button for "**Settings**".
2. I suggest to lift this button up one level for easier access. And list its contents under a heading called "**Settings**", just like the rest (I mean _Contribute_, _Community_.. etc)
3. Many of the buttons inside the "**More**" window lead to github. Most of them can be rearranged for better accessibility. For example:
-  _Open Source Licenses_, _Project License_ can be merged into a single entry called "License".
- _Source Code_, _Join the Community_, _Contributors_ can be merged under the **Contribute** heading.
- _Rate this app_ (an option used once in the app's lifetime, it certainly should not be the first option).
- _Help/FAQ_, _Report bugs_ can be merged.

It is possible to use another way of organisation. I just think the current arrangement is not very useful. I love the app and I use it every day. Thanks for the maintainers and coders.

### Source

GitHub Releases

### Format / File type

Not specific

**Comment by lu-ckystars** [comment]
i know this isn't related and is probably inappropriate but how can I find out about new updates for marder? i discovered it in this issue so thought I'd post this here..

**Comment by gsantner** [comment]
In the "Actions" tab above. Marder = development builds, everytime code changes there is that version built automatically.

**Comment by gsantner** [comment]
I don't plan to move the settings out to the More tab. It is exactly that, to give some links and options to go to further places and find more information.

However more and more gets also added to the editor/viewer overflow (...) menu.
