### ISSUE TITLE
Option to create new files while in edit mode.

### ISSUE THREAD

**Issue by Young-Angelo** [gsantner/markor#2264]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

1. Imagine if im editing a markdown file and I create a link to a file that does not exist, instead of asking me how to open the file, it would be better to have an extra option of whether I want to create the said file. 

### Information

Android version: 12
Device: m31
App Version: 2.11.1

### Source

Google Play

### Format / File type

Markdown

### Additional info / Log

```shell
-
```

**Comment by harshad1** [comment]
I link will open the file regardless of if it exists or not. It will be created if you save the opened file it with some content.

Use the open link action to open the link.

**Comment by harshad1** [comment]
These were recent changes not sure if they have been released yet.

**Comment by Young-Angelo** [comment]
> These were recent changes not sure if they have been released yet.

I don't think they haven't in either Marder nor Markor.

**Comment by harshad1** [comment]
They should definitely be in master. So if you are running master just add `[foo](./path/to/foo.md)` and open it

You can tap on the link in view mode or use the follow link action in edit mode.

**Comment by harshad1** [comment]
I am closing this for now as it is solved in master. @Young-Angelo Please wait for the 3.12 release and reopen if it doesn't work then
