### ISSUE TITLE
Consider removing dependency on webview

### ISSUE THREAD

**Issue by elyahw** [gsantner/markor#2267]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

I'm not exactly sure what webview is used for in the app but I don't think it is necessary to view and edit notes. I suggest to remove reliance on it, I think this will make the app faster and more responsive.

### Information

App Version: v2.11.1

### Source

GitHub Releases

**Comment by gsantner** [comment]
It is for viewing parsed markdown content and others. For editing it's not required.

Thanks for the thought, but won't happen, no proper webview no proper viewing of Markdown documents and more. It's not like the whole app is written it like it's suggested.
