### ISSUE TITLE
希望能在底栏关闭todo和quicknoto功能

### ISSUE THREAD

**Issue by rkdawn** [gsantner/markor#2276]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

真的不需要这两个功能呀，只需要Markdown，希望能给个开关

### Information

Android version: 
Device: 
App Version: 

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
english please.

**Comment by harshad1** [comment]
Translation appears to be:

I hope to turn off the todo and quicknoto functions in the bottom bar
I really don’t need these two functions. I only need Markdown. I hope I can provide a switch.

I would say the answer is probably 'no'

:)

**Comment by gsantner** [comment]
possible, don't want people to ask in 10 different languages and expect to guess what it means :D.

**Comment by rkdawn** [comment]
> english please.
Sorry, forgot to use English
