### ISSUE TITLE
Support for replacing with lowercase or uppercase

### ISSUE THREAD

**Issue by BambuSergio** [gsantner/markor#2279]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

I would like to be able to use things like \L$0 or \U$1, etc. in the replacement box, width regular expressions, to be able to replace the text found with lowercase or uppercase.
Thank you. Greetings.

### Information

Android version: 13
Device: Poco F5
App Version: 2.11.1

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
Regex has a insensitive flag.

Prefix query with (?i)

**Comment by BambuSergio** [comment]
> Regex has a insensitive flag.
> 
> Prefix query with (?i)

I'm sorry, but I don't understand very well. Is it possible to do what I say with regular expressions?  Some example?  I've tried (?!) but I can't get anything.  Thank you

**Comment by gsantner** [comment]
i like ignore not !

**Comment by gsantner** [comment]
Can this be closed? 

Also #2426 might be helpful to you.
