### ISSUE TITLE
Since updating to 2.12, .txt files open with text viewer, not editor

### ISSUE THREAD

**Issue by ericjunkermann** [gsantner/markor#2283]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

Since updating to 2.12, .txt files open with text viewer, not editor.

### Steps to reproduce

1. Open Markor, click on a .txt file in favourites list (which I have edited in Markor every day for years)
2. File opens in Text Viewer, instead of editor
3. other formats open normally

### Information

Android version: 7.0
Device: Samsung SM-T719
App Version: 2.12.0

### Source

Google Play

### Format / File type

Plaintext

### Additional info / Log

```shell
Can't even get to my files in Marder - all folders are crossed out
```

**Comment by gsantner** [comment]
maybe you have checked the option to open files by default in view mode. and even if not, you can always switch to edit mode at the top menu.

**Comment by ericjunkermann** [comment]
On Tue, 14 May 2024 04:53:21 -0700 gsantner/markor ***@***.*** said

> maybe you have checked the option to open files by default in view mode. and
> even if not, you can always switch to edit mode at the top menu. 

Not view mode, but a screen I have never seen before headed "Text Viewer", white text on black
with a three-dot menu with commands for moving about in the file and an Exit command - that's all.

And the Exit command did exactly that, not returning to the previous Markor screen.

And now, Markor works normally again. I am happy but very puzzled.

**Comment by harshad1** [comment]
This is very strange. Please post a screenshot if it happens again. 

I can't even find the string "Text Viewer" in our codebase.

**Comment by ericjunkermann** [comment]
In which case it must belong to some other app and somehow got set as the default app for .txt . I did some digging around and found that it belongs to Ghost Commander! I have no memory of doing anything to make it the default (and default apps on Android are crazy anyway), nor of doing anything to remove it! 

So thanks very much and apologies for the interruption.

**Comment by harshad1** [comment]
Ok :)

Closing now

**Comment by gsantner** [comment]
Might be related to #2285
