### ISSUE TITLE
When creating a new file with the same name as an existing file, the system will automatically open the existing file.

### ISSUE THREAD

**Issue by liushuqi-2022** [gsantner/markor#2288]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

When attempting to create a new file and assign it the same name as an existing file, the save operation will cause the system to automatically open the existing file with the same name.

Expect to receive corresponding prompts when there are duplicates in the naming.

### Steps to reproduce

1. Click add file button
2. Enter a file name that is the same as an existing file.
3. Click the OK button

Record
[add-already.webm](https://github.com/gsantner/markor/assets/111285450/c818b7ac-f760-4922-968f-8dfc6e55eb2f)

### Information

Android version: 8.0
Device: pixel XL
App Version: v2.12.0(149)

### Source

GitHub Releases

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by harshad1** [comment]
This is the expected behaviour.
