### ISSUE TITLE
Incorrect suffix will be included as part of the file name

### ISSUE THREAD

**Issue by liushuqi-2022** [gsantner/markor#2289]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

When I manually input a file suffix incorrectly, it will be automatically saved as the file name.

### Steps to reproduce

1. Click the Create File button
2. Enter name: "1", suffix: "txt"
3. A file named "1txt" will appear

Record
[aad-rex.webm](https://github.com/gsantner/markor/assets/111285450/fd1efe25-5f35-4181-88df-451f186c232e)

### Information

Android version: 8.0
Device: pixel XL
App Version: v2.12.0(149)

### Source

GitHub Releases

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
Suffix may not contain a dot, if you wish to. Files named "hello-cool" is just as much a valid filename as "hello.cool".

If you intentionally dont specify a suffix, have a dot in, or don't put any dot is your own choice. And you can freely adjust it to whatever you want.

**Comment by liushuqi-2022** [comment]
Thanks for your attention. The valid name in the result is not a problem. What I want to clarify is that the suffix I am referring to represents the type of file I want to create. For example, by default, when naming, if I enter "1" and "txt" respectively, I will get a MIME type of */*. However, if I enter "1" and the correct file extension ".txt", I will get a file with "text/plain" correctly. That is, incorrect file extension input may result in unexpected file types. Do you think this is an issue？

**Comment by liushuqi-2022** [comment]
> Suffix may not contain a dot, if you wish to. Files named "hello-cool" is just as much a valid filename as "hello.cool". If you intentionally dont specify a suffix, have a dot in, or don't put any dot is your own choice. And you can freely adjust it to whatever you want. Said " 1txt" as result IS a valid name, not incorrect working here.

Thanks for your attention. The valid name in the result is not a problem. What I want to clarify is that the suffix I am referring to represents the type of file I want to create. For example, by default, when naming, if I enter "1" and "txt" respectively, I will get a MIME type of /. However, if I enter "1" and the correct file extension ".txt", I will get a file with "text/plain" correctly. That is, incorrect file extension input may result in unexpected file types. Do you think this is an issue？
