### ISSUE TITLE
Long press the add file button but navigate to "Favorites"

### ISSUE THREAD

**Issue by liushuqi-2022** [gsantner/markor#2290]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

When I long press the add file button, the app navigates to "Favorites". I'm not sure if this is a specific behavior.
When I click the create file button in "Favorites", the app returns to the homepage. I believe this is not what was expected. 

### Steps to reproduce

1. Long-click the add file button
2. The app will navigate to "favorites", and click (Long-click) the add file button again
3. The app returns to the homepage

**Record**
[longclick.webm](https://github.com/gsantner/markor/assets/111285450/7caf66d7-7fe4-4d12-93c8-26397d17c5d9)

### Information

Android version: 8.0
Device: pixel XL
App Version: v2.12.0(149)

### Source

GitHub Releases

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
It is as intended. Just a little poweruser utility to get to things quick. You may find some other hidden/undocumented niceties in the project ;).
