### ISSUE TITLE
It is recommended that Markor incorporate an encryption library feature to centrally manage encrypted files.

### ISSUE THREAD

**Issue by chubbymoon** [gsantner/markor#2293]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

1. It is recommended that Markor incorporate an encryption library feature to centrally manage encrypted files, thereby enhancing the security of files written with Markor when stored in cloud drives.
2. Support the import of regular files and the export of encrypted files.
3. Enable the viewing and editing of encrypted files within the software.
4. It would be ideal to support fingerprint unlocking, similar to the encrypted space in cloud drives.
5. It is suggested to use publicly available encryption algorithms (such as AES and SM4, etc.).
6. It is recommended to include an option to "encrypt file names or not."

### Information

Android version: android13
App Version: 2.12.0

### Source

GitHub Releases

### Format / File type

Markdown

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
Recommended by whom? Your employer? ChatGPT?

Markor has a AES encryption feature. Feel free to make improvements and create a merge request 😄 .

**Comment by gsantner** [comment]
Who is the recommender?

Markor has a AES encryption feature. Feel free to make improvements and create a merge request 😄 .

**Comment by Awsalfered** [comment]
I'm looking for automatic backup and encryption of backup files
