### ISSUE TITLE
sharing link from browser lost ist header

### ISSUE THREAD

**Issue by tengucrow** [gsantner/markor#2294]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

After updating markor to v2.12.0 sharing from browser (Iceraven) lost its header.

Before update it was:

`[Fu Manchu - Wikipedia](https://en.m.wikipedia.org/wiki/Fu_Manchu )`

or

`[tpope/vim-obsession: obsession.vim: continuously updated session files](https://github.com/tpope/vim-obsession )`

Now it is:

`[wikipedia](https://en.m.wikipedia.org/wiki/Fu_Manchu)`

`[github](https://github.com/tpope/vim-obsession)`

or

`https://en.m.wikipedia.org/wiki/Fu_Manchu`

`https://github.com/tpope/vim-obsession`

Depending on whether the checkbox 'Insert link' in `Share into` windows is selected or not.

It is very uncovinient. A big part of Markor's functionality for me is that it replaces browser bookmarks, and the ability to save links along with titles reduces the amount of manual work. In the new version, this functionality has been removed; in addition, the `Insert link` checkbox gives strange behavior (the link in the window simply changes color - it is not clear what format it is converted to).

### Steps to reproduce

1. Open site in browser https://github.com/tpope/vim-obsession
2. Share link to markor
3. Get `https://github.com/tpope/vim-obsession` link instead of `[tpope/vim-obsession: obsession.vim: continuously updated session files](https://github.com/tpope/vim-obsession )`

### Information

Android version: MIUI Global 12.0.6 / Android 10 QP1A.190711.020
Device: Redmi Note 8 Pro
App Version: 2.12.0 (149)

### Source

F-Droid

### Format / File type

Markdown

**Comment by gsantner** [comment]
please search opem topic here

**Comment by yulqen** [comment]
I too feel the pain....
