### ISSUE TITLE
v2.12.1: Markdown Table of Contents behavior changed since v2.11.0

### ISSUE THREAD

**Issue by izzytechie** [gsantner/markor#2296]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

When viewing a Markdown file, the user can tap on the name of the file at the top to open a Table of Contents window listing the headers in the file. Tapping on one of the headers takes the user to the header within the file.

In v2.11.0, after tapping on the header, the Table of Contents window automatically closes. This is the desired behavior. 

In v2.12.0, after tapping on the header, the Table of Contents window does not automatically close. The user has to tap on Cancel at the bottom of the window to close the window. This is not the desired behavior. 

### Steps to reproduce

1. Open a Markdown file containing headers.
2. Tap on the name of the file at the top to open a Table of Contents window listing the headers in the file.
3. Tap on one of the headers in the Table of Contents window to go to the header within the file.
4. Observe that the Table of Contents window does not automatically close.

### Information

Android version: 10
Device: Oukitel C21
App Version: 2.12.0

### Source

Google Play

### Format / File type

Markdown

### Additional info / Log

```shell
-
```

**Comment by harshad1** [comment]
This is fixed in #2300
