### ISSUE TITLE
 v2.12.1 default file format assignment, new file not working as expected

### ISSUE THREAD

**Issue by michibr81** [gsantner/markor#2297]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

Updated to Version 2.12.1 and no have no syntaxhighlighting in Todo.txt format (no categories, no topics, no priority, checkecd or unchecked not visible). No buttons available any more for categories. No sorting possible.

### Steps to reproduce

1. Open file in todo.txt format
2. Add text

```
(A) Go Shopping @Household +Walmart
x (B) Renew brakes  http://howtofixbrake.com @Car
```

4. No Syntaxhighlighting visible (except url)

### Information

Android version: 14
Device: Zenfone 10
App Version: 2.12.1

### Source

Google Play

### Format / File type

todo.txt

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
New file - todo.txt example is not making the right contents either currently

**Comment by bruvellu** [comment]
I believe a similar issue is happening with the Wikitext format. After the v2.12.1 update, my Zim wiki files are now detected as Plain Text (no formatting). If I manually change the format of individual files, the formatting comes back, but the auto-detection doesn't seem to be working.

And, since you mentioned the new file issue, I just noticed that creating a new file using the zim-wiki-empty.txt template crashes the app. Maybe it's also related. Should I open a new issue with more details about the crash?

Cheers,
Bruno

**Comment by gsantner** [comment]
No its OK. Dont need new one.

**Comment by bruvellu** [comment]
Hi @gsantner, creating a new file using the zim-wiki-empty.txt template is still crashing the app for me in v2.12.2. Can you reproduce this as well?

**Comment by gsantner** [comment]
There are numerous dicscussions here.
