### ISSUE TITLE
Share into missing subject and tags in version 2.12.0

### ISSUE THREAD

**Issue by pudah** [gsantner/markor#2298]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

In prior versions, when the user shares into Markor from say a web browser, the data shared is a markdown formatted link. That is, the web page title in square brackets followed immediately by the URL in parentheses.

In the latest version 2.12.0 from f-droid, only the URL ends up in the shared data.

In addition, in prior version, after the share, Markor closes. In version 2.12, after sharing the shared into document opens and remains open.

### Steps to reproduce

1. Go to any web page in firefox or chromium browser
2. Select share option
3. Select Markor as target

### Information

Android version: 13
Device: Samsung tablet
App Version: 2.12.0

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

I downloaded and tried current Marder. It seems to split the difference between Markor 2.11.1 and 2.12.0.

Markor 2.11.1 (and earlier) share into format is fully formatted markdown link
`[Web Page Title](https://www.example.com)`

Marder format is both title and URL but no markdown tags
`Web Page Title https://www.example.com`

Markor 2.12.0 format is nothing but the URL, no title, no tags
`https://www.example.com`

**Comment by gsantner** [comment]
Search recent tickets before opening

**Comment by pudah** [comment]
> Search recent tickets before opening

I did search. Seems that by default the search only checks for still open issues so I didn't see there was a closed issue on this problem.

**Comment by gsantner** [comment]
Jup unfortunatley the default. I link usually the page everywhere, where also closed tickets are displayed
