### ISSUE TITLE
v2.12.1 App crashes when creating new file of "None" type

### ISSUE THREAD

**Issue by vnagel** [gsantner/markor#2303]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

I originally thought file creation was completely broken, but then realized I'd unintentionally switched to the "None" file type and that was what was causing the app to crash.

Sorry, I have not tried the latest dev version. It's not affecting me now that I know I just had to switch the type, but it still seems wrong that a supported feature would crash the app.

### Steps to reproduce

1. Click the "+ in lower right corner while on "Files" tab
2. Type in a file name e.g. "abc"
3. Select "None" file type
4. Click "OK"
5. App crashes

### Information

Android version: 13
Device: OnePlus 8
App Version: V2.12.1 (150) 

### Source

Google Play

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by harshad1** [comment]
Also solved in #2300 (by not having none as an option)
