### ISSUE TITLE
希望支持WIKI格式的链接，比如[[链接的标题]]。同时，在文件超过1.5万个并进行全文检索时不再崩溃退出。

### ISSUE THREAD

**Issue by github770208646** [gsantner/markor#2310]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

1. 支持打开WIKI格式的链接。比如[[一个office文档.docx]]或[[一个MARKDOWN文档.md]]或[[一个MARKDOWN文档]]
2. 支持更大的文件库全文检索，比如文件超过1.5万个时，全文检索仍可用。

### Information

Android version: 10
Device: MI 8 SE
App Version: 2.12.2

### Source

GitHub Releases

### Format / File type

Wikitext, Zim

### Additional info / Log

```shell
-
```

**Comment by harshad1** [comment]
English please :)
