### ISSUE TITLE
v2.12.2 New file Template name corresponds to wrong content

### ISSUE THREAD

**Issue by bertisLongfellow** [gsantner/markor#2312]
# IMPORTANT
* App version:  2.12.2
* Android version/rom: 14
* Device: Pixel 7A
* I accept that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

## Explain the Problem
I created a markdown file specifying the presentation-beamer template. Instead, I got this, looks like csv template: 
# this is a comment in csv file

# below is the header
number;text;finishing date

# csv can contain markdown formatting
1;Learn to use **Markor** formatting

# use "..." if the column contains reserved chars
2;"Use Delimitter chars like "";    :,";2019-06-24

# use "..." if the column is multiline
3;"multi
   line";2059-12-24

## Steps to Reproduce
- hit plus button
- selected markdown
- selected presentation-beamer template 
- typed filename
- hit OK

## Log
<details>
<summary>Log</summary>

```
Not applicable 
```
</details>

**Comment by gsantner** [comment]
#2297

**Comment by gsantner** [comment]
sure that you have 2.12.2 and not 2.12.1?

**Comment by bertisLongfellow** [comment]
Version 2.12.2 (151). Let me try a full uninstall/ reinstall, I will report back!

**Comment by harshad1** [comment]
I may have made a mistake when reorganizing the templates. Will investigate.

**Comment by bertisLongfellow** [comment]
I reinstalled using the latest (and same) release from GitHub. I confirm the beamer template is incorrect. I tried two others, csv and todo, they looked incorrect as well. Thanks for investigating.

**Comment by gsantner** [comment]
Thanks, v2.12.2 was supposed to fix those issues but seems like something went wrong :D.

Anyway, in the meantime you can also find the samples here on github subfolder.

**Comment by bertisLongfellow** [comment]
All good! I already presented what I built with Markor on the train yesterday, I enjoy and use Markor a lot. All the best from Canada.

**Comment by gsantner** [comment]
Hey cool, I mean ignoring the template writing issue - how do you like this feature?

I implemented this in a personal hackaton weekend and so far I havent heard from other using it. But I was really happy about the outcome and how easy I can make presentations/slides this way :D.


Did you present it to people / export it to PDF or something / present over HDMI/screenshare? Would just like to know how this helps others..what people like on that.

**Comment by harshad1** [comment]
Pretty sure I made an off-by-one error here :(

https://github.com/gsantner/markor/blob/master/app/src/main/java/net/gsantner/markor/frontend/NewFileDialog.java#L252

Simple fix. I'll get it in over the weekend. Until then please insert the org mode template

**Comment by bertisLongfellow** [comment]
@gsantner This time, and I'd say this is often the case when I use that template, I was walking to the train when I realized I'd neglected to prep a deck for a meeting later that morning. I had written a Word document which I could access on OneDrive (for Work), so I opened and copied the content, and said "hey ChatGPT, please reframe this into a presentation suitable for executive in beamer markdown" and pasted the document, and it did a reasonable job, which I copied and pasted into Markor, tweaked a bit, hit view, it looked good. I had another word document with several identical tables of different categories, which I copied into ChatGPT asking it to sum into one table formatted as markdown beamer slide, added that. I spoke some stuff into ChatGPT requesting cleaning into same format output, moved that over. Tada, complete deck. I could have stopped there and exported as you note, but I sent myself the text file, opened it before the meeting in VS Code on my laptop in the office and tweaked and presented from that.

Markor's the Swiss army knife (multi-functional tool) in the flow. ChatGPT I am learning to use to quickly digest my own written and spoken stuff into useful outputs rapidly, and since it can do it with the necessary formatting... 

I was a lot lot lot less sweaty and panicked than I might otherwise have been, and it was a clean, professional deck. I do use PowerPoint, too, and in some situations it's basically required, but the power and simplicity of this workflow drove a few things for me this week. I don't know how you feel about ChatGPT, I am guessing your commitment to sharing open source code means your own work has been absorbed by it and similar tools without any consideration to your time, wishes or rights. It reminds me I paid you a small donation a year ago or so, and then noticed you refunded it in PayPal some time later. I am more than happy to support your time; I not only use it, I enjoy it.

**Comment by gsantner** [comment]
Thanks for your reply! Great to hear that it's so useful to somebody other then me :smiley:
