### ISSUE TITLE
unable to change Todo or quick note folder

### ISSUE THREAD

**Issue by nutpantz** [gsantner/markor#2313]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

Using setting>general files and folders>save location
Neither quick note or to do section has the"select this folder"option
No matter what i try i cannot change the location of Todo out Quicknotes

### Steps to reproduce

1. Goo to settings
2. General files and folders
3. Save location quick note or Todo
4. Try and change the location

### Information

Android version: 13 + 14 +9
Device: pixel 6 a13 + pixel 8pro a14  + blackview
App Version: 2.12.2 fdroid 2.12.1 fdroid

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
The select folder button shouldn't be visible.

But either way, you need to select a file in the file by clicking it. You should not select a folder here. QuickNote might be as well be "MyNotes.txt" if you wish so thus. You are not forced to use QuickNote as filename.
