### ISSUE TITLE
Images don't render

### ISSUE THREAD

**Issue by AZeed18** [gsantner/markor#2318]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

Images don't render in Markdown (haven't tested others)

The links are correct relative links and most or all include `..` characters

Clicking on `Open link`, however, opens image and it displays

### Steps to reproduce

1. Add an image with image syntax
2. It it displayed as empty placeholder space

### Information

Android version: 13
Device: Samsung A71
App Version: 2.12.2

### Source

F-Droid

### Format / File type

Markdown

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
Works fine here. Make sure to use escapes for spaces.

Am 3. Juni 2024 18:15:04 MESZ schrieb Ahmed El-Zeedy ***@***.***>:

**Comment by AZeed18** [comment]
`![](../../../_resources/image%205.png)` for "image 5.png"

- I open notes from app's file explorer, so no content URI
- Same problem with any local images (even `![](image.png)`)
- `Open link` actually works but image is not displayed in the note

**Comment by harshad1** [comment]
Drop the `%20`

Try `![](../../../_resources/image 5.png)`

**Comment by AZeed18** [comment]
Same issue. It doesn't render even a link like this `![](image.png)` as previously mentioned.

**Comment by harshad1** [comment]
What's the file format set to?

Jun 3, 2024 21:36:07 Ahmed El-Zeedy ***@***.***>:

**Comment by AZeed18** [comment]
Markdown.

I found the problem! The path containing images has a special character `#` in the beginning of an intermediate folder's name. Even though this folder wasn't a part of the link, all local links to other images work fine.

Also, the opposite (having note in normal path and image in path with special characters) works but after encoding special characters.

**Comment by gsantner** [comment]
Thanks for checking. Unfortunatley some things (in this case webview and special chars) might not work well for all cases.
