### ISSUE TITLE
ACTION_CREATE_NOTE intent filter?

### ISSUE THREAD

**Issue by devycarol** [gsantner/markor#2320]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

1. It looks like there's an Android intent for creating a note? [More information here](https://developer.android.com/guide/components/intents-common#NewNote).
2. I think it would be cool to have this intent filter in the Markor app for any apps that have intents for "create a note for x." I'm developing one myself, and I'd love for it to be compatible with this text editor 😊 (I know that ACTION_SEND can be used, but that implementation is sorta specific to this app).
3. I haven't tried it, but it might be as simple as adding the line
`<action android:name="com.google.android.gms.actions.CREATE_NOTE" />`
to [this intent-filter in the manifest](https://github.com/gsantner/markor/blob/master/app/src/main/AndroidManifest.xml#L188)?
4. Not sure how you'd want to handle `EXTRA_NAME`, if at all. Perhaps it could be used and pre-select a note for that "share into" dialog. Apps would be likely to give a 'name' like "Grocery list from MyApp," so maybe it could search for a note with that name and append the text or offer to create a new one if no such document exists in the notebook. Alternatively, you could discard it and just check if it's a keyword like quicknote, qn, todo, new, something like that. I understand if this bit could be cumbersome.

So yeah, I think that'd be a cool thing if it works like we would expect it to—the same as the "share" action but less apps to choose from in that "select app" dialog.  Thanks for your time :).

### Information

Android version: 14 (LineageOS 21)
Device: Pixel 5a
App Version: 2.12.2

### Source

F-Droid

### Format / File type

Not specific

**Comment by gsantner** [comment]
I have added. Please let know if it helps/works ... and how you make use of it... I don't have something around that makes use of it it seems.
