### ISSUE TITLE
Absolute links for external CSS/JS

### ISSUE THREAD

**Issue by AZeed18** [gsantner/markor#2321]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

Ability to use absolute links for injecting external CSS/JS:

```md
<link rel="spreadsheet" href="/storage/emulated/0/..." />
```

The problem is I want a CSS file somewhere to be injected globally

### Information

Android version: 13
Device: Samsung A71
App Version: 2.12.2

### Source

F-Droid

### Format / File type

Markdown

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
file:// prefix is probably what you can try.

**Comment by AZeed18** [comment]
Tried

`<link rel="spreadsheet" href="file:///storage/emulated/0/test.css" />`

`<link rel="spreadsheet" href="file://storage/emulated/0/test.css" />`

**Comment by AZeed18** [comment]
Well, both URLs work if I use CSS for importing:

```html
<style>
@import url("file:///... or /... URL");
</style>
```
