### ISSUE TITLE
Format: Add support for lrc text format (lyrics)

### ISSUE THREAD

**Issue by Taratect** [gsantner/markor#2322]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

As a avid music listener, I tweak in my text editor to type out lyrics or add lyrics to my songs.
However the .lrc format isn't supported by markor which is a huge bummer

### Information

Android version: 10
Device: Redmi 8
App Version: 2.12.2

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
Huge bummer: Well you need to know everything needs to be written and 
reviewed by humans and not everything is as popular (used/needed) as you 
think it might be to your personal needs.

If you are interesting in proper support of this format in Markor, feel 
free to implement it and create a merge request to make the format 
available to other users. That is how formats are added here.

**Comment by gsantner** [comment]
Added .lrc to automatically load in Markor in plaintext format.

If you want more sophisticated support, feel free to implement it yourself or somebody else interested to implement.
