### ISSUE TITLE
Include TOC in shared md

### ISSUE THREAD

**Issue by Charles7z** [gsantner/markor#2323]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

The only way to include the TOC that Markor auto-generates is to share as non-md (text).  At least I haven't found a way to include the auto-generated table of contents in text/md format.  🤷🏻‍♂️ 

I generally want to "share" the md file with the auto-generated Table Of Contents. If it's possible already, how, and if it's not could it be included somehow in "share as full md" or something  🤷🏻‍♂️ 

Thanks!

### Information

Android version: 14
Device: pixel 6a
App Version: 2.12.2

### Source

GitHub Releases

### Format / File type

Markdown

**Comment by harshad1** [comment]
As a workaround: https://codebeautify.org/html-to-markdown

Copy text as html and convert to markdown
