### ISSUE TITLE
Auto filename uses month instead of minutes.

### ISSUE THREAD

**Issue by jakobstubenrauch** [gsantner/markor#2324]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

Thank you so much for this really nice app!

When creating a new file and using default title (not entering anything), the automatically generated filename is "`yyyy-MM-dd'T'hhMMss`" but should be "`yyyy-MM-dd'T'hhmmss`" (capital MM is for month, lower case mm is for minute).

I think I found the issue in the code, inamely in frontend/NewFileDialog.java line 224.

### Steps to reproduce

1. Open App
2. Click on Files in bottom navigation
3. Click on big red plus in the lower right (new file)
4. Do not enter anything
5. Click okay.
6. Check the filename of the newly created file
This might be different if your last used properties differ from vanilla.

### Information

Android version: 14
Device: Pixel 6a
App Version: latest

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
Thanks fpr checking code too!

**Comment by harshad1** [comment]
Lol. Sorry. Dumb mistake on my part. I'll fix.

**Comment by harshad1** [comment]
Fixed in #2307
