### ISSUE TITLE
"Start new line above" action

### ISSUE THREAD

**Issue by mledvd** [gsantner/markor#2325]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

This would be the long-press for the "start new line below" button. It would instead create an empty line above the current one.

That's it! I think it'd be cool. My use case for it is that I often want to create a new todo task above the one where my cursor is.

### Information

Android version: 14 (LineageOS 21)
Device: Pixel 5a
App Version: 2.12.2

### Source

F-Droid

### Format / File type

Not specific

**Comment by harshad1** [comment]
Added this to #2307
