### ISSUE TITLE
Swiping on "Move Text Up/Down" buttons triggers them

### ISSUE THREAD

**Issue by wshoy** [gsantner/markor#2327]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

The buttons activate when swiped in any direction. They should react the same as other buttons.

### Steps to reproduce

1. Swipe the "Move Text Up/Down" button

### Information

Android version: 13
Device: 
App Version: 2.12.2

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by harshad1** [comment]
Can reproduce. I'll address this soon

**Comment by harshad1** [comment]
I have pushed a fix to #2307
