### ISSUE TITLE
Crash after creating files with certain extensions

### ISSUE THREAD

**Issue by wshoy** [gsantner/markor#2329]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

Making an .xz or .xyz file causes the app to crash.

### Steps to reproduce

1. Create a file with .xz or .xyz extension

### Information

Android version: 13
Device: 
App Version: 2.12.2

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
Not crashes here. However if you create files which are commonly binary file extensions you can assume that something won't work.

**Comment by wshoy** [comment]
Ok, it's editing binary files that's causing it. It's not like anyone would do that, but I don't think it should crash.

**Comment by harshad1** [comment]
Can reproduce. Will fix.

I should have realized as I work with point clouds for my day job :)

**Comment by harshad1** [comment]
I have a solution pushed in #2307.
