### ISSUE TITLE
File creator no longer remembers the previous file extension

### ISSUE THREAD

**Issue by wshoy** [gsantner/markor#2332]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

It was not explicitly stated, but the file creator used to remember the previous file extension (version 2.12.0).
It was useful for creating multiple files of type other than in the type dropdown.
I think the feature should be brought back or maybe even a "Previous" type option could be added.

### Steps to reproduce

1. Tap the "+" button
2. Create a file "aaa" with an ".html" extension
3. Tap the "+" button again
4. The ".html" extension is replaced with the one in the type dropdown

### Information

Android version: 13
Device: 
App Version: 2.12.2

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by harshad1** [comment]
What is the desired behavior here?

**Comment by wshoy** [comment]
> What is the desired behavior here?

In 2.12.0 if one created a file aaa.html and attempted to create another, the name field was empty and the extension remained ".html". In the next versions, to create multiple .html files for example, one needs to write the name AND replace the extension .md with .html on every file creation (if the type option is set to "Markdown").

**Comment by wshoy** [comment]
> the name field was empty and the extension remained ".html". That should be the correct behavior.

@harshad1 I have realized I didn't quite respont to your question before. This is the edit.

**Comment by harshad1** [comment]
Ok. Seems reasonable. I'll add that functionality back

**Comment by harshad1** [comment]
Added in #2037
