### ISSUE TITLE
Markdown: Mermaid chart dark mode?

### ISSUE THREAD

**Issue by ChungLeeCN** [gsantner/markor#2335]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

I use the Mermaid syntax to draw flowcharts in a Markdown file, and everything displays correctly in light mode. However, in dark mode, the lines of the flowchart are almost invisible. We need to change the arrows and lines of the Mermaid flowchart to white or another light color for dark mode.
![dark](https://github.com/gsantner/markor/assets/130234319/a87ae2f4-afe4-4a48-b63e-be801eddf475)
![white](https://github.com/gsantner/markor/assets/130234319/09056a91-d01f-425f-acc6-35d797d14467)

### Steps to reproduce

1. wirte a Mermaid flowchart in dark theme, then you will see the issue.

### Information

Android version: 12
Device: Redmi K30 Pro Zoom Edition
App Version: v2.12.2 (151)

### Source

Google Play

### Format / File type

Not specific

**Comment by gsantner** [comment]
Not sure if Mermaid is supposed to be used/properly supports Mermaid on it's own.

Feel free to make adjustments/improvements and make a merge request to get it added.

**Comment by guanglinn** [comment]
Hi, @gsantner , @ChungLeeCN ,
Now dark mode can be supported properly by Mermaid, you can see it [here](https://github.com/gsantner/markor/pull/2345#issuecomment-2223679050).
