### ISSUE TITLE
Back button should return to the previous directory instead of the parent directory

### ISSUE THREAD

**Issue by wshoy** [gsantner/markor#2337]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

The back button should return to the earlier screen, as is the case with the Samsung's file manager.
When one clicks the ".." directory and wants to go back, it's intuitive to press the back button.
To prevent a loop, the further presses will move to the parent directory.

To reproduce:
1. Click the ".." directory
2. Press the back button
- Instead of the original directory you are now in the parent directory of the ".."

### Information

Android version: 13
Device: 
App Version: 2.12.2

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by harshad1** [comment]
I think this is the correct behavior too.

We will have to maintain a history stack.

**Comment by Asmageddon** [comment]
An option would be acceptable, but in my opinion back should always navigate up the directory tree because it's the only consistent, predictable behaviour, and going back to the previous directory is rarely useful.

**Comment by wshoy** [comment]
> it's the only consistent, predictable behaviour

It's not consistent with all the other apps and user expectations.

> going back to the previous directory is rarely useful

I disagree. How do you expect people to use "recent files" if they can't go back.

**Comment by gsantner** [comment]
You are welcome to make improvements.

**Comment by harshad1** [comment]
This is done
