### ISSUE TITLE
Crash when creating new note with `zim-wiki-empty.txt` template

### ISSUE THREAD

**Issue by bruvellu** [gsantner/markor#2340]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

Since v2.12.1, Markor crashes when trying to create a new note using the `zim-wiki-empty.txt` template:

![photo_2024-07-05_08-34-32](https://github.com/gsantner/markor/assets/361179/2a292410-df50-4347-8979-f73c635f22c2)

### Steps to reproduce

1. Open Markor and click the red "+"
2. Select `Wikitext / Zim` for type and `zim-wiki-empty.txt` for template
3. Click OK

### Information

Android version: Android 14, One UI 6.1
Device: Samsung Galaxy S24
App Version: v2.12.2 (151)

### Source

Google Play

### Format / File type

Wikitext, Zim

### Additional info / Log

```shell
Package: net.gsantner.markor
Version: v2.12.2 (151)
Flavor: Gplay (release)
Build date: 2024-05-25T10:13Z
ISource: Google Play
VCS Hash: a2afb69bc6edcf9ee35d33060a02ae7cc0292847
VCS Msg: Markor v2.12.2 (code 151)
```

**Comment by harshad1** [comment]
Fixed in #2037 

@gsantner I have one or two changes to push to that PR. I will try to get them in by tonight so we can merge soon. It has gotten quite bloated with a lot of tweaks and fixes

**Comment by gsantner** [comment]
Thank you for all your changes. I can check earliest next week.

**Comment by bruvellu** [comment]
Thanks so much @gsantner and @harshad1! I guess you meant #2307?
