### ISSUE TITLE
Add ability to rename file from inside edit screen

### ISSUE THREAD

**Issue by elyahw** [gsantner/markor#2342]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

**1. Summary:**
- It would be useful if it was possible to rename a file from inside the edit screen by pressing on the title.

**2. Current behaviour:**
- When a notes file is opened, pressing on the title (the name of the file) triggers the search menu. This is redundant as there is a dedicated search icon in the top right corner.

**3. Suggestion:**
- Instead of the current behaviour, I suggest that pressing the title triggers a rename of the currently opened file.
- One thing to consider is to check if the new name conflicts with an existing name. If so, it should be automatically given a number (e.g. _new_name 1_)

### Information

Android version: 13
Device: Pixel 5a
App Version: 2.12.2

### Source

GitHub Releases

**Comment by gsantner** [comment]
File management is primarly for the filemanager/filebrowser. Don't plan to add file move/rename to editor.
