### ISSUE TITLE
Android SDK/API 34 support, Google denies updates without it

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#2346]
# IMPORTANT
* App version: 2.11

Google demands project changes yet again, app not compliant because of using SDK 33. Needs to be upgraded to SDK 34. No new version releaseable there currently.

Probably also comes with additonal ""features"", in the meaning of Markor needs to fix again so it works in SDK34 and fit to the constantly growing list of requirements.

**Comment by harshad1** [comment]
Adding some links:

https://developer.android.com/google/play/requirements/target-sdk
