### ISSUE TITLE
Restore virtual directories for filesystem browsing

### ISSUE THREAD

**Issue by violet-octagon** [gsantner/markor#2350]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

In version v2.11.0 and prior, you were able to browse through Internal Storage (/storage/emulated/#/), AppData (public) (/storage/emulated/#/Android/data/net.gsantner.markor), and AppData (private) (/data/user/#/net.gsantner.markor/) with ease. There were two ways to move between the three folders: with the folder drop-down menu in the top right, or by moving up directories until you found the virtual directory that put you in the desired location. Notably, if you were in the copy/move prompt, the only way you could browse between the three folders was by going up directories until you found the virtual directory you wanted.

&nbsp;

https://github.com/user-attachments/assets/35f787bd-b2b9-448b-b0fe-7848dee8d584

This video shows how you can move between the three directories in older versions of the app with the drop-down menu or by traveling up directories and going through virtual directories.

&nbsp;

Markor v2.12.0 and onward (including the latest development version) removes some virtual directories, only seeming to retain "appdata-private" under /storage/. For one, this makes browsing within the first few subdirectories from root a little clunky because you can only browse *up* directories, not back down. More importantly, the lack of virtual subdirectories **makes it impossible to copy/move files between AppData (private), AppData (public), and Internal Storage**.

More specifically, you can copy/move a file from AppData (public) to Internal Storage by going up a few directories, but not the opposite direction. Older versions of the app allowed you to copy/move files in both directions. You can move a file that's in Internal Storage or AppData (public) to AppData (private) by going up a few directories until you find the "appdata-private" virtual directory in /storage/, but you cannot do that in the opposite direction anymore.

&nbsp;

https://github.com/user-attachments/assets/9e0495ff-d201-445c-8ef2-232954d5c7d4

This video shows how you cannot really move between the three directories in the latest versions of the app without the drop-down menu.

***

I want this feature restored because it makes it possible to move files out of AppData (private) to somewhere you can copy the files via MTP, another app with storage access, etc. and it increases the ease of browsing the filesystem. Right now it isn't possible to back up files moved to private app data once they're stored there.

### Information

Android version: 14 (AP2A.240705.004)
Device: Pixel 7 Pro
App Version: 2.12.2

### Source

GitHub Releases

### Format / File type

Not specific

**Comment by gsantner** [comment]
Note: That "virtual filesystem" is mere a kind of symlink with a predefined mapping or list of files to show. No system mount point or alike.

Unfortunatley Android does not support symlinks properly unfortunatley or doesnt allow to create them at relevant places...hence this is what I came up with back in the day.

Just to say what it is and what it's not.

**Comment by harshad1** [comment]
It seems like jumping to (some) special directories in the move copy dialog would be useful
