### ISSUE TITLE
File browser: Wrong icons and secondary text while scrolling

### ISSUE THREAD

**Issue by wshoy** [gsantner/markor#2358]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

The emerging icons and secondary text come from the recently hidden ones before correcting (look at the file size).
#2331 makes it more visible, but is unrelated.

![image](https://github.com/user-attachments/assets/4f18f5b7-d376-4b77-a658-50abb52a8a37)

https://github.com/user-attachments/assets/09814d74-4e0c-46aa-9620-2e539a61e5a5

### Steps to reproduce

1. Scroll
2. Look at the emerging icons and secondary text

### Information

Android version: 13
Device: 
App Version: 2.12.2

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
What you are seeing here is a common performance trick of RecycleView.

It reuses existing list elements and updates them when they get into 
view, instead of destroying and recreating the whole. I would say it's 
quite standard behavior of it.

**Comment by harshad1** [comment]
I have added a buffer and made some changes to reduce this #2359
