### ISSUE TITLE
v2.12.3 View-mode Table of contents links broken

### ISSUE THREAD

**Issue by gnomy47** [gsantner/markor#2364]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

Prior to v 2.12.3, if the "Table of contents" features was enabled for Markdown files, you could jump to a particular heading in the view mode by pressing on it.

In v 2.12.3, pressing on a heading in the table of contents does nothing. 

### Steps to reproduce

1. Open Markor's Settings, goto "Markdown" and enable "Table of contents" 
2. Have a markdown file with multiple headings 
3. Open the file in View mode and then press on any heading in the table of contents
4. Nothing happens

### Information

Android version: 14
Device: Pixel 4a
App Version: v 2.12.3

### Source

F-Droid

### Format / File type

Markdown

### Additional info / Log

```shell
-
```

**Comment by guanglinn** [comment]
This issue may be related to PR #2307. @harshad1

**Comment by harshad1** [comment]
I am pretty sure where I introduced this. Will work on fixing it.

**Comment by gsantner** [comment]
line numbers. though guess we either need to duplicate/have two anchors or only have the original ones

**Comment by AZeed18** [comment]
Might be related:

Codeblocks are no longer rendered as codeblocks in editor mode (e.g., headers are displayed large with orange color) and header-like objects (e.g., `# python comment`) are displayed in table of contents
