### ISSUE TITLE
v2.12.3:  no more custom js in .md or csv files, just .txt or other misc text files

### ISSUE THREAD

**Issue by gesu92** [gsantner/markor#2365]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

Hello mister, I just update Markor today and noticed that the js custom script it's not execute in .md or .csv files like previus versions, just execute in .txt files u other random text files.

### Steps to reproduce

1. Load javascript in the settings
2. Open .md or .csv file, nothing happend.
3. Open other random text file, here is it the javascript.

### Information

Android version: 14
Device: Moto X4
App Version: 2.12.3

### Source

F-Droid

### Format / File type

Not specific

**Comment by gsantner** [comment]
This is about Inject-head settings options right?

**Comment by gesu92** [comment]
Indeed, in the 2.13.3 there is no more javascript executed in .md and .csv files, I had to downgrade one version of the app meanwhile its solved

**Comment by harshad1** [comment]
Could you give me an example with some instructions so I can test it?

**Comment by gesu92** [comment]
Yeah, I mean, just use some javascript code that can be visually checked, like mmm document.getElementsByTagName("table").item(0).setAttribute("style","background-color: red;");

that should work in .csv and in a .md with a table

**Comment by gesu92** [comment]
I have a bigger script that I ised with Markor.
First I was thinking that some part are wrong, but casually open a .txt file and work, but in the custom files like .md and .csv does't

**Comment by gsantner** [comment]
You need to wrap your code into a block, i.e.
```
<script>

</script>
```

**Comment by gsantner** [comment]
Not sure about your problem, but your question seems to be rather about web development.

It works here at least:

[screenrecord-2024-07-27_14.22.44.webm](https://github.com/user-attachments/assets/f6b5b811-8c56-47ad-b3bc-81afc2587b8a)

**Comment by gesu92** [comment]
It's not working mr.

https://github.com/user-attachments/assets/363a85c3-f4c4-41ef-9eb0-d307266f575e

**Comment by gsantner** [comment]
You have v2.12.3.

**Comment by gesu92** [comment]
The video show How the script works on random .txt files, but in .csv or .md it's not working, in the versión 2.12.3

In the 2.12.2 working fine, if you need I can do the same video but with the 2.12.2 version

**Comment by harshad1** [comment]
I see this. Will investigate
