### ISSUE TITLE
v2.12.3: Dialog size Search/Replace too small

### ISSUE THREAD

**Issue by RalphHightower** [gsantner/markor#2367]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

The dialog for Search/Replace has shrunk significantly. The text for the Search and Replace fields are are not wide enough to see the fields. Have to scroll up to see options checkboxes and buttons. 
This problem started with the latest release. I do all my editing in Markdown. But I just tested with a newly created plain text file and the problem is there also, so I specified file format is nonspecific. 

### Steps to reproduce

1. Click on the search icon
2. Choose Search/Replace
3. Screen area for text in search & replace fields, with options, and buttons significantly reduced.
![Screenshot_20240723_143725_Markor](https://github.com/user-attachments/assets/dcab48ea-566f-497c-81d7-0da8434dc2c4)

### Information

Android version: 13
Device: Galaxy S22 Ultra
App Version: v2.12.3 (152)

### Source

Google Play

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by harshad1** [comment]
@gsantner yeah this should be made match_parent

**Comment by RalphHightower** [comment]
Thank you. **Much better!** 🎆
