### ISSUE TITLE
Cannot change the template/snippet folder

### ISSUE THREAD

**Issue by joebetsill** [gsantner/markor#2369]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

When I go to `Settings> Other> Snippet/Template Directory`:

1. The directory shown is always `/whatever/path/the/default/notebook/is/set/to/.app/snippets`, even though there is no `.app/snippets` folder at that location. Not even on a fresh install, when it points to the `Documents/markor/.app/snippets` folder.
2. The snippets/templates folder cannot be changed. No matter what I select with the folder selection prompt, the folder is still set to the original one, as described in step 1. 

As a side note: I'm not sure that I grasp how snippets and templates are *expected* to work, and maybe that's part of my problem. I am trying to select my Obsidian template folder as the Markor template folder, with the idea that my Obsidian templates would show up in the new file prompt under templates in Markor. 

Edit: I made a backup of my settings and checked the resulting file, and it shows the *correct* (what I previously selected) folder location for `pref_key__snippet_directory_path`. 

### Steps to reproduce

1. See the description field.

### Information

Android version: 14
Device: Pixel 8 Pro
App Version: 2.12.4 (153)

### Source

GitHub Releases

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
Not sure what Obsidian templates are, but it's something on it's own. Don't expect Markor to be Obsidian specific client.

For the rest, can you try creating the folders  with .app/snippets yourself and check if it works then?

**Comment by joebetsill** [comment]
Obsidian templates are just markdown files. I just want to use the same
folder for both.

Does the template/snippet folder have to point to something that terminates
in `.app/snippets`?

**Comment by gsantner** [comment]
Normal text files also here, no special things. The snippets should then show up listed by their filenames

**Comment by joebetsill** [comment]
> For the rest, can you try creating the folders  with .app/snippets yourself and check if it works then?

This does work. Markdown files placed in the manually created `.app/snippets` folder show up in the templates drop-down in the new file prompt.

Do you think allowing to choose *any* folder for template and snippets could be added, instead of making a hard requirement for it to terminate in `.app/snippets`?

**Comment by joebetsill** [comment]
It seems like line [130](https://github.com/gsantner/markor/blob/master/app/src/main/java/net/gsantner/markor/model/AppSettings.java#L130) of /model/AppSettings.java incorrectly calls `pref_key__quicknote_filepath` and since that's a file, it always fails the subsequent check to ensure the snippets directory _is_ a directory.
