### ISSUE TITLE
Checkboxes in "Date and time" action button dialog not saved

### ISSUE THREAD

**Issue by wshoy** [gsantner/markor#2386]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

"Get format instead date or time" and "**Always** use current date &amp; time" checkbox values are not saved. 

The latter checkbox always needs to be unchecked first to pick the date or time. This is not the implied behavior.

### Steps to reproduce

1. Click on the "Date and time" button
2. Check/Uncheck either checkbox
3. Click "OK"
4. Click on the "Date and time" button again

### Information

Android version: 13
Device: 
App Version: 2.12.5

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
Let me ask other way round, why would you expect them to be saved?

Especially using something other then the current date is rather the rare case.

**Comment by wshoy** [comment]
1. Indeed, saving the first one doesn't make much sense.
2. The word "always" in the second one implies, that it's saved.
3. The second checkbox looks like it doesn't do anything except reset to the current date. It could as well be something like a button (not sure). The "Pick Date/Time" buttons don't need to be disabled.

Regardless, I don't use it anymore. I was using it for the due date in ToDo. Apparently there is already such thing which I've overlooked called the "Current date". 😅 Shouldn't it be called "Due date"?

**Comment by gsantner** [comment]
Always diaables the date & time picker and makes the current time to be used. Well it's always checked. The usage has nothing todo with the checkbox checked state however.

**Comment by harshad1** [comment]
IMO the fix is to remove 'Always'. Just 

'Use current date/time'
