### ISSUE TITLE
Please remove widget rounded corners

### ISSUE THREAD

**Issue by Secret-chest** [gsantner/markor#2389]
# IMPORTANT
* App version: 2.12.3
* Android version/rom: 14 (Samsung)
* Device: Galaxy A54
* I accept that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

## Explain the Problem
What problem did you encounter? What did you expect to happen?

The widget has rounded corners, even though the launcher doesn't cut corners of widgets.

## Steps to Reproduce
Explain what you did to encounter the issue

- Use a launcher that lets widgets be square (like Lawnchair 2)
- Place the note list widget on the desk
- See how it has rounded corners

**Comment by harshad1** [comment]
I added this to better match Android's new design guidelines / style guide.

Is this because you don't like how rounded corners look? Or something else?

**Comment by gsantner** [comment]
Feel free to make improvements to the UI, the project is open for merge requests.

**Comment by Secret-chest** [comment]
> Feel free to make improvements to the UI, the project is open for merge requests. One doesn't fit for all and everybodies needs.

I can't do Android programming, but shouldn't it be easy to revert?

**Comment by Secret-chest** [comment]
> I added this to better match Android's new design guidelines / style guide.

If you want this you use a launcher that enforces them.
