### ISSUE TITLE
Customize main bottom bar

### ISSUE THREAD

**Issue by Maik-Wi** [gsantner/markor#2394]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

I use in Markor on an e-ink device. I actually only use and need the files, To-Do and QuickNote are useless for me. I would therefore like it if I could leave out the two tabs in the settings.

### Information

Android version: 11
Device: Boox Tab mini C
App Version: 2.12.5 (154)

### Source

Google Play

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by nutpantz** [comment]
i also would like to have an option for their visability, or to replace them with a template of my own.  a quick access template if you will, much how they are hard coded now.. that would be much more useful.

**Comment by gsantner** [comment]
You can freely select the file to load and its format.

I don't think about adding a settings option to remove/hide it though. Not every tiny bit needs configurable. Feel free to compile the app on your own however that fits your needs.
