### ISSUE TITLE
req: name format option without {{title}}

### ISSUE THREAD

**Issue by nutpantz** [gsantner/markor#2395]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

all the options for name formats for a new file have {{title}} ( other then uuid)
this forces me to always type something for a title when really for many many things date and time will do.
if i need to make a quick note to drop in my diary folder or drop into my misc notes folder all i need in the date and time.

### Information

Android version: 14
Device: pixel 8 pro
App Version: 

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by harshad1** [comment]
You can type whatever you want in the format field. The options in the drop-down are examples only.

If the title field is empty it will not be appended to the final file name.

(We add '_{{title}}' internally to the end of the format if the format does not contain '{{title}}' and the title field is not empty)

**Comment by nutpantz** [comment]
thank you i just thought it needed a title, i searched the documention but it did not say anything on the subject.
i had no idea they were just examples and i could use my own and it would be remembered

**Comment by harshad1** [comment]
Adding documentation to markor would be an excellent way to contribute :)

**Comment by nutpantz** [comment]
not if oyu knew how bad my spelling and grammer is...
