### ISSUE TITLE
req: option to hide/remove built in templates

### ISSUE THREAD

**Issue by nutpantz** [gsantner/markor#2396]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

custom templates have come a LONG way in markor, i question the need for the built in templates, or at least the need for them to always be visible. or the need for them to be hard coded in the app really also.
honestly i think the best option would be to just make default template files in .snippets during install that the user can delete if they are not needed or wanted, as a file they could also give a user an example of what a template can acommplish. 

### Information

Android version: 14
Device: pixel8pro, pixle6 a13, bv6600 a09, s7ea 12, fire10hd a11,
App Version: 

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by harshad1** [comment]
As a compromise, they are now listed _after_ user templates.

In practice I never see or interact with them.

**Comment by nutpantz** [comment]
i use 3 templates and every time i use the 3rd i have to always scroll up to see the first 2 to use them as they are hidden with the big list of a bunch of built in mostly listed below.  so even though they are listed after and never used, they are in the way of smooth work flow.

**Comment by gsantner** [comment]
Like harshad said, custom templates are sorted to the top. Create as many custom templates you like and you won't see the builtin templates.

I don't think changes are needed here. If you don't need them don't use them. Easy.
