### ISSUE TITLE
Sort notes

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#24]
#### General information
* **App version:** 0.1.2

#### Expected result
Feedback from gplay

**What is the expected output?** 
Nice working with syncthing! Would be nice to have an option to sort notes by date.

**Comment by gsantner** [comment]
Register on <https://hacktoberfest.digitalocean.com/>, send a PR to fix this and get your t-shirt for free :).

**Comment by kartikarora** [comment]
@gsantner A little more info on this please?

**Comment by gsantner** [comment]
This was requested by google play users:

To be able to sort the notes at the main view (the list fragment):

Accordingly to:
* Modification date
* Name
* Size

Descending/Ascending. If you go the submenu way in toolbar, or in the settings/preferences.xml is up to you

**Comment by valvin1** [comment]
nice, it seems this feature will be implemented in the next feature ?

**Comment by gsantner** [comment]
there are some points left, but e.g. sort by filename works already

**Comment by valvin1** [comment]
👍
