### ISSUE TITLE
Use a single process for the whole app

### ISSUE THREAD

**Issue by elyahw** [gsantner/markor#2410]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

I noticed that there are 3 different processes being launched (one for the settings, one for file browser, and one for editor).

This is a little bit confusing when task switching on Android, as most of the time I have 2 open instances of the Markor (which are the file browser and the editor).

I think it would useful if all of them were merged into a single process.

### Information

Android version: 13
Device: Pixel 5a
App Version: Latest v2.12.5

### Source

GitHub Releases

### Format / File type

Not specific

**Comment by harshad1** [comment]
I have made some improvements to this in #2377

**Comment by harshad1** [comment]
Do you have this option unchecked?

![Screenshot_20240918-072621](https://github.com/user-attachments/assets/75d17bd9-fb8c-47d1-ae3e-97404ee7ea0b)

**Comment by harshad1** [comment]
Hmmm.. it should be unchecked by default. I'll fix it if it isn't.

**Comment by gsantner** [comment]
It was default multiple windows when I implemented it first time, as far 
I recall.

**Comment by gsantner** [comment]
@elyahw 
Don't get me wrong, but it seems you know the code base somewhat good. As you are developing on a crippled down fork of Markor.  In the recent months saw a increased amount of things you are asking for.

May I politely ask you to contribute to this project, especially if you want something for your fork. Don't let the others do the stuff you want and take their time to answer your stuff, please start contributing. I checked and didn't see any yet: <https://github.com/gsantner/markor/pulls?q=is%3Apr+author%3Aelyahw>.

Thank you.

**Comment by gsantner** [comment]
@elyahw 
You might misunderstood a bit, for sure I like Markor to be KISS and simple. BUT: I don't like adding a settings option for every tiny bit. That is also bloat and not simple.  
Markor should work out of the box good enough for most people, and years have shown that it does.

If you want a big sync-integration godzilla Word application, you can use MS-Word, Google Docs or alike. If you want a bare plain editor you use something like Windows Notepad.exe. I don't want Markor to be either. The right tools for the right job. Adding lots of settings options just so a vocal minority can make Markor look like Notepad.exe is not something I want to do.

**Comment by gsantner** [comment]
Thanks for help!
