### ISSUE TITLE
remember title format from the last time I added a new file

### ISSUE THREAD

**Issue by ehula** [gsantner/markor#2442]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

1. Remember the last used title format (i.e. `yyyyMMddHHmmss`_{title}) so that it is the default the next time I add a new file.

### Information

Android version: 14
Device: Google Pixel 6 Pro
App Version: v2.12.5 (154)

### Source

GitHub Releases

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by harshad1** [comment]
Hmmm. This should be the current behaviour. Investigating

**Comment by harshad1** [comment]
Added a fix in #2443 

- Dialog will remember file format
- File format will remember template
- Template will remember title format

**Comment by ehula** [comment]
Awesome! Thank you!

**Comment by harshad1** [comment]
This has been addressed in #2443
