### ISSUE TITLE
Option to disable vertical scrolling bounce animation

### ISSUE THREAD

**Issue by stevenxxiu** [gsantner/markor#2444]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

I want to disable all the vertical scrolling animations. These can be seen by:

- In the text view, show or hide the keyboard. There will be a vertical scrolling animation.
- There will also be a fling when scrolling quickly to the top or bottom.

I've already removed all animations in settings, including in `Developer options`.

I'd like a way to disable this, or simply to just disable it.

This feature would be greatly appreciated. I've used *Markor* for a long time and love it.

### Information

Android version: 14
Device: Pixel 7
App Version: v2.12.5

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by harshad1** [comment]
Most of these are android defaults.

**Comment by stevenxxiu** [comment]
Possibly, but it depends on the app. Most apps don't have the scroll bounce animation, say *Firefox*.

*Android* should also respect its own animation settings.

**Comment by gsantner** [comment]
@stevenxxiu 
Like harshad1 said, android defaults. If they don't respect something you might ask at the wrong place. We explicitly disable a lot of stuff that is builtin at Markor even instead of adding new. Beside one blink animation for filemanager selection we don't introduce custom animations. 

Markor doesn't go direction of fancy animation UI but rather traditional UI.  Sorry if the little builtin system defaults are too much to bear, but not thinking of tweaking/worsening the defaults unnecessary.
