### ISSUE TITLE
Update CSS parser

### ISSUE THREAD

**Issue by Benko111** [gsantner/markor#2446]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

Hi, is there any option of updating the Markor CSS parser? Would be great to be able to use all the modern CSS features like registered custom elements and all that added CSS functionality. I have no idea how it works and how big of a project it would be, so would it be possible and feasible?
I do find myself pretty often using my browser because Markor doesn't know the latest CSS. 

### Information

Android version: 
Device: 
App Version: 

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
There is no CSS parser contained in Markor. This is the webview/webengine of your device.

To update it, update/upgrade your device.
