### ISSUE TITLE
Add tagging mechanism and search by tag

### ISSUE THREAD

**Issue by gonciarz** [gsantner/markor#2447]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

1. Add ability to asign multiple tags to a file (many to many relationship) (to a content or to metadata)
2. Add ability to efficiently search by tag (add search engine)
3. Tags should be sharable and editable (should be persisted in a text format)
4. Tag detection changes (they should trigger adding or removing tag assignments)

### Information

Android version: 14
Device: n/a
App Version: 2.12.5

### Source

F-Droid

### Format / File type

Markdown

### Additional info / Log

```shell
If I find some time, I may help to contribute.
```

**Comment by gsantner** [comment]
Hello, please search through open and closed issues. This has been asked a few times.

**Comment by gonciarz** [comment]
@gsantner apologies, I quickly looked up (using my mobile) before requesting and haven't found any issue. I will try to find it when I am in front of my desktop. Thank you.
