### ISSUE TITLE
Editor UI: vertical space too large, overlaps with status icons

### ISSUE THREAD

**Issue by secretmango** [gsantner/markor#2448]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

![screenshot of the editor UI](https://github.com/user-attachments/assets/ec8cd7ba-0da9-4546-9cc7-16e7222e84ba)

When editing a text, the top buttons are too high and the bottom buttons are too low

This does not happen on any other app, I tested Jerboa, Grayjay, Signal, Fedilab, Amethyst, OSMAnd~, Firefox, Openkeychain, Obtainium, ...

Those should cover most of the Android GUI libraries (Android View, XML, Jetpack Compose, Flutter)

### Steps to reproduce

1. Use Android 15, I use a GrapheneOS alpha release
2. Edit a document

I tested this with the debug APK.

### Information

Android version: 15 (GrapheneOS alpha version)
Device: Pixel 6a bluejay
App Version: 2.12.5-2359 and latest stable

### Source

GitHub Releases

### Format / File type

Not specific

### Additional info / Log

```shell
Not yet
```

**Comment by gsantner** [comment]
#2387

**Comment by hack-wizard** [comment]
This is also happening on my Pixel 7 Pro, again common thread here appears to be Android 15.  I've also seen this behavior in at least one other app I use.

Marder has the same issue, really hope this can be fixed soon, because all the other MD editors on F-droid are notably inferior.

**Comment by gsantner** [comment]
Closed as duplicate
