### ISSUE TITLE
tile action buttons into rows

### ISSUE THREAD

**Issue by champignoom** [gsantner/markor#2454]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

The action buttons are currently arranged in a single row with a horizontal scroll bar. It would be more convenient to arrange them into multiple rows, so that no scrolling is needed, like in Termux. Ideally, logically related buttons are put together. For example, bold, slant, headers, and other markup buttons are in one row, while table, image, audio etc are in the other.

![markor with all action buttons in a single row](https://github.com/user-attachments/assets/6d3f0595-3dfc-4e72-87e9-0795cc50a0c4)

![Termux with tiled buttons](https://github.com/user-attachments/assets/82b6931e-8356-4a41-99c2-b690acb28f24)

### Information

Android version: 14
Device: Xiaomi 14
App Version: 2.12.5, marder dev

### Source

Google Play

### Format / File type

Markdown

**Comment by gsantner** [comment]
Hello,

vertical space is limited on mobile. Especially in landscape mode multiple ones will hinder from reading content, or making it impossible to see anything if the keyboard is also popped up.

The most common scenario is that people only use a handful of actions, and the rest is unused.
You can rearrange the order in Markor settings to your liking so you will barely be horizontal scrolling then.

**Comment by harshad1** [comment]
You can also control spacing so more are visible at once.

**Comment by champignoom** [comment]
> You can rearrange the order in Markor settings to your liking so you will barely be in need of horizontal scrolling.

This would also work, but I can't find such setting for button rearrangement other than spacing adjustment.

**Comment by champignoom** [comment]
> vertical space is limited on mobile. Especially in landscape mode multiple rows will hinder from reading content, or making it impossible to see anything if the keyboard is also popped up.

Another idea: when the editor hight goes below than a certain threshold, due to either small screen size or keyboard activation, the top status bar and the bottom tab bar could be hidden or collapsed, since both are larger and less needed than text action buttons when typing.

**Comment by harshad1** [comment]
Settings -> <Format> -> Action order

**Comment by guanglinn** [comment]
It has been proposed before, like this

![Screenshot_20240111_210013_net.gsantner.markor_test.jpg](https://github.com/gsantner/markor/assets/60415467/c7b2d7d3-6d5e-4191-933d-346db047b8ad)

**Comment by gsantner** [comment]
There are a few ways to customize, should work out for most users.
