### ISSUE TITLE
Auto add `Content-Type:` header when creating new zim/wikitext file

### ISSUE THREAD

**Issue by tenzap** [gsantner/markor#2456]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

When creating a new file of format zim/wikitext, the default model is empty file.

It should at least contain this first line: `Content-Type: text/x-zim-wiki`
Otherwise, when opening the notepad containing that file in zim-desktop software, the file will not be displayed in the desktop app.

See: https://zim-wiki.org/manual/Help/Importing_external_files.html
```
 Finally zim pages that have a ".txt" extension must start with a header line that identifies the content as zim wiki formatted text, optionally followed by more header lines and separated from the main content by an empty line. Like this:

Content-Type: text/x-zim-wiki


=== First heading ===
some text


Without the heading line, ".txt" files are regarded as text file attachments. 
```

2 possibles ways to achieve this:
- add the header line as soon as a file zim/wikitext file is created, whatever the model selected.
- When choosing type = wikitext/zim, it should automatically select the model zim-wiki-empty.txt

### Information

Android version: 12
Device: Xiaomi Redmi note 9s
App Version: 2.12.5

### Source

F-Droid

### Format / File type

Wikitext, Zim

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
The template can be adapted by simple text changes in the git repository.

A merge request is welcome, a easy thing for somebody who wants to contribute (first time also).

**Comment by harshad1** [comment]
We already gave a built in template for this:

![Screenshot_20241024-191735](https://github.com/user-attachments/assets/1d1af981-26b3-498a-a58b-dba9fd244312)

**Comment by gsantner** [comment]
Markor is not just Zim but many formats. You have the free choice to apply whatever text you wish.

If you chose empy text, you get exactly that - empty text. 

Maybe Markor is not the right software for you if you expect a pure Zim client, or checking the right box that fits your needs is too much to you to ask for.

**Comment by gsantner** [comment]
I don't use Zim, so don't know much about others on Android.

Because Markor supports many formats, that is the difference to something for just one - you have to make the choice for a speicifc one at those few places.
