### ISSUE TITLE
Phone's interface overscans the Markor's interface

### ISSUE THREAD

**Issue by mooreye** [gsantner/markor#2458]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

When editing a file, I can't tap the top bar's buttons because they are under the phone's main GUI. See screenshot:

![markor](https://github.com/user-attachments/assets/1ddd218a-79cd-45bc-b7a6-0db0cac643e9)

### Steps to reproduce

open any file in Markor

### Information

Android version: 15 (GrapheneOS)
Device: Google Pixel 8
App Version: 2.12.5

### Source

F-Droid

### Format / File type

Not specific

**Comment by gsantner** [comment]
please check recently (closed) issues. This is number 4.
