### ISSUE TITLE
Feature: Alternative main-navigation using navdrawer

### ISSUE THREAD

**Issue by troyengel** [gsantner/markor#246]
#### General information

* 0.3.7
* Android 8.1

#### Description

Currently the main navigation has a ribbon at the bottom with Notebook/To-Do/Quicknote/More. It feels weird with modern Android UI, most applications use a "hamburger" menu in the upper left, when clicked it pops out a left-drawer with nav items. I believe Markor will look and feel nicer if converted to this style, it "fits" for this kind of app. (the same design used with the GMail app for example)

If the main screen Nav is moved to the hamburger drawer method, this also allows more space for menu items to be placed in it (Settings, Help, Rate, etc.) which currently don't fit on the ribbon on the bottom (More...), so besides feeling nicer it would have a functional benefit. :)

Thank you for making the app!

**Comment by gsantner** [comment]
Well, I have to admit to usually prefer navslider too, but I can't agree with the above, Android+Material Design is more and more shifting towards bottomnav (which kinda makes sense because bigger screens).

If you or someone else can make it so it is interoptable with bottombar code, feel free to send a PR! :). It is some work, but it is possible, because the main part is inflating menu.xml, which is not too different between navdrawer and bottomnav - only managing later is the task.

**Comment by troyengel** [comment]
We can have a gentleman's disagreement. :) I just had a look through my apps, 45 out of 72 use a navslider and abou t9 "don't make sense" to use it (protractor, ruler, etc.). It of course just depends on which apps you use and what kind of device - I'm on a "regular sized" phone, not a tablet. _shrug_ But I hear you, I do have some apps with bottom nav (like Bitwarden) too.

Alas, I'm afraid I'm not an app developer (don't even have the SDK installed) to assist. Phone apps are a bit out of my territory is all, maybe some day.

**Comment by gsantner** [comment]
yeah as said, I prefer navslider too usually, but in case of markor exactly these options make totally sense to be populated as tabs or in this case, as bottomnav. To quickly swap between the most important documents and the file browser.

This was not just a call just to you, but to any contributor :).

**Comment by gsantner** [comment]
Closing this - unless Markor get's an PR this won't likely happen - which it didn't get yet.
