### ISSUE TITLE
The option titles and toolbars at the top and bottom of the application interface will overlap with the phone system's notification bar and navigation bar.

### ISSUE THREAD

**Issue by Hkl1213** [gsantner/markor#2460]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

After upgrading to Android 15, on the Settings page, the title overlaps with the phone system's status bar. The same thing happens when you open a file, the toolbar overlaps with the navigation bar.

### Steps to reproduce

1. Go to the "Settings" page or open files
![Screenshot_20241026-073310](https://github.com/user-attachments/assets/24ef0883-ffcf-4378-a1ad-067a9adb1ad6)
![Screenshot_20241026-073341](https://github.com/user-attachments/assets/89aa4731-1780-4871-9fc4-1c8bcce2796c)

2. 
3. 

### Information

Android version: 15 (AP3A.241005.015)
Device: Pixel 8a
App Version: v2.12.5(154)

### Source

Google Play

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
This has been opened for the 5th time. Last time few hours ago.

Please use search and check the issues....

**Comment by gsantner** [comment]
This has been opened for the 5th time. Last time few hours ago. was the most top, most recent, first one in the list if you followed the link.

Please use search and check the issues.
