### ISSUE TITLE
md::List TextAction - match multiple lines if selected

### ISSUE THREAD

**Issue by troyengel** [gsantner/markor#247]
#### General information

* 0.3.7
* Android 8.1

#### Description

Hi, when you have multiple hard-break lines of text and highlight them all, then use one of the List elements from the format toolbar the result is only the first line getting the `- ` added to it in front. The expectation would be that on each new line start (hard line break), all lines are formatted as `- ` list elements. Well, that's my expectation at least. :) Thank you!

Visually:
```
one
two
three
four
```
Highlight/select all lines, use unordered List button, result:
```
- one
two
three
four
```
Expectation:
```
- one
- two
- three
- four
```

**Comment by gsantner** [comment]
open for PRs ;)

**Comment by troyengel** [comment]
While I'm not an app devel to code it, I can help research. A java coder did a little comparison of reading strings line by line in 4 different ways and presents his findings of which is the fastest code path: https://stackoverflow.com/a/26698176/150649 - IMHO, `java.util.Scanner` while not the fastest seems like the cleanest to write. $0.02, hope this helps someone.

**Comment by gsantner** [comment]
we do use buferredreader already (which is fastest in your linked test :;)

**Comment by jdckr** [comment]
Hi,
I have checked the code and am wondering what the intention of 
`runMarkdownRegularPrefixAction` is. At the moment, if a single word is selected, it adds/removes the `action` string in front of the word (e.g. in the middle of a line). But on the other hand this function is only used for "line actions" which are always added in front of the line. I have an implementation which breaks the single word prefixing within a line but enables actions on multiple lines:

![2018-11-01_13-54-06](https://user-images.githubusercontent.com/40456550/47853218-4f6fb800-ddde-11e8-9698-3a3ea9f1f5f6.gif)

If this is what it should do I can submit a PR.

**Comment by gsantner** [comment]
@jdckr 

These are the used usages yes, from what I see in gif this looks promising ;).
Can you also take a look at the other ones, how they do work? 

![screenshot_20181101-141943](https://user-images.githubusercontent.com/6735650/47854130-37e5fe80-dde1-11e8-9b7e-1788c7fa285a.png)

**Comment by jdckr** [comment]
The others work as well. For numbered list it will just add `1.` to the beginning for every line. This is fine for markdown but looks strange in a raw text file. If this should also be supported I would recommend to split this into another function. Btw I have created a PR which we can use for further implementation discussions.

**Comment by troyengel** [comment]
Just asking the question, lately I've been converting a lot of wiki docs to md and dealing with Table of Contents listings -- will this survive the operation outlined above?

```
  - item 1
      - subitem 1
  - item 2
      - subitem 2
```
  - item 1
      - subitem 1
  - item 2
      - subitem 2

**Comment by gsantner** [comment]
Hey everybody, can you please recheck if this bug/fetaure is still present?

**Comment by troyengel** [comment]
It seems fine to me - I'm now on Android 11, Markor is v2.3.3 (117) and it seems to be working as I expect, no regressions. Thank you!

**Comment by gsantner** [comment]
thank @harshad1
