### ISSUE TITLE
Add WebDAV support

### ISSUE THREAD

**Issue by gnusupport** [gsantner/markor#2473]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

Please add WebDAV support as directory 

### Information

Android version: 
Device: 
App Version: 

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by harshad1** [comment]
Markor does not directly work with anything on the network

You can use something like DavX5 to mount your remote directory and then access it through markor.

**Comment by gsantner** [comment]
What could be improved is opening files from other apps / mounting storages from other apps. 

Like the system file/documents app allows to pick files from i.e. NextCloud app directly. Which can be applied in similar fashion to apps that supply WebDav virtual storage.

**Comment by gnusupport** [comment]
Yes, that is what I mean, something similar, just as the application named Material Files which can access WebDAV and secure shell servers, is that way I could use multiple devices with this application and same directory, basically having my own cloud on the control.

**Comment by arichiardi** [comment]
Has anybody tried Davx5? I don't think I see the mounted dirs in Markor - should I navigate out of the `emulated` tree?

**Comment by lgwapnitsky** [comment]
> Markor does not directly work with anything on the network
> 
> You can use something like DavX5 to mount your remote directory and then access it through markor.

Davx5 is for cal/carddav

**Comment by arichiardi** [comment]
@lgwapnitsky not really, it is able to mount webdav endpoints - I found my solution - I am using [s3Drive](https://s3drive.app/) that can sync.
