### ISSUE TITLE
Add image scaling in markdown 

### ISSUE THREAD

**Issue by mikesplaces** [gsantner/markor#2476]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

1. Is it possible to add image scaling in markdown? I write journals and longer essays on my android phone and then edit on my Mac. It would be nice to be able to scale down the image using something like 200x200 in the image markdown to make the image size smaller when I add it. 
2. 
3. 

### Information

Android version: 14
Device: vivo y27s
App Version: latest

### Source

F-Droid

### Format / File type

Markdown

### Additional info / Log

```shell
-
```

**Comment by harshad1** [comment]
FWIW, I have a script which crawls my directory tree and changes image resolution if it sees any images > 500kb in size.

**Comment by gsantner** [comment]
Markor has multiple ways to open a image (from filebrowser or from editor->image button) in external app. You can freely install any Gallery or image editing app. However Markor is not a picture editor, currently don't plan to add such a feature.
