### ISSUE TITLE
200kb txt file slow performance with google play version 2.13.1

### ISSUE THREAD

**Issue by clach04** [gsantner/markor#2478]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

I reverted back to 2.12.5.

File is ~200kb (4.6K lines). Utf-8, mostly us-ascii but some CJK glyphs. 

Slow to search, slow to edit. Similar to previously fixed issue[ locate and link)](https://github.com/gsantner/markor/discussions/1794).

TODO test latest Dev version on same phone. 

### Steps to reproduce

1. Open large text file. Slow to open and display top icons (like search)
2. Search 
3. Modify a line (append text to existing line)
4. Slow to close (with back button

### Information

Android version: 10
Device: Samsung s9plus
App Version: 2.13.1 and net.gsantner.markor-v156-2.13.1-flavorAtest-debug.apk

### Source

Google Play

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
There is a issue open just a few before...please use serach.

**Comment by clach04** [comment]
> There is a issue open just a few before...please use serach.

Do you happen to have a link? I did search and the only vaguely similar issue is https://github.com/gsantner/markor/issues/2469 which appears to be specific to syntax highlights, this report if for regular txt files without syntax highlights.

2022 ticket https://github.com/gsantner/markor/discussions/1794 is the one I was alluding to in my original report

**Comment by gsantner** [comment]
Also plaintext has some highlights, unless you fully expclitily disabled it.

**Comment by gsantner** [comment]
The first one. Also plaintext has some highlights, unless you fully expclitily disabled it. Ergo should get better if you disable it temporary.

**Comment by clach04** [comment]
> The first one. Also plaintext has some highlights, unless you fully expclitily disabled it. Ergo should get better if you disable it temporary.

Ooohhh! I'd incorrectly assumed no highlights, just tested and confirmed 👍 thank you!

I'll close and make a note in the other issue.
