### ISSUE TITLE
"Start on bottom" setting doesn't affect the QuickNote

### ISSUE THREAD

**Issue by chtx** [gsantner/markor#2483]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [x] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

Unchecking the "Start on bottom" setting in the "Edit mode" section of settings doesn't affect the QuickNote on startup. 

When I open the app (I have the QuickNote opening by default) - the cursor jumps to the bottom.

### Steps to reproduce

1. Set the "App start tab" to "QuickNote"
2. Uncheck the "Start on bottom" setting
3. Open the QuickNote and move the cursor somewhere other than the bottom of the note. 
4. Restart the app. The cursor will appear at the bottom of the QuickNote. 

### Information

Android version: 15
Device: Pixel 6a
App Version: 2.13.1

### Source

F-Droid

### Format / File type

Markdown

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
Correct. QuickNote and ToDo have special behaviour. That is working as expected from my side.

If you don't like it, use any other file from the filebrowser.

**Comment by gsantner** [comment]
Correct. QuickNote and ToDo have special behaviour. That is working as expected from my side.

If you don't like it, open any other file from the filebrowser.

This is not a bug.
