### ISSUE TITLE
Different font for editor and preview 

### ISSUE THREAD

**Issue by Isvvc** [gsantner/markor#249]
Having a monospace typeface is useful for editing markdown files and using one is how I prefer to write markdown, but I like reading the preview in a regular sans-serif typeface. 

Having the option to assign a different font for the editor and preview would be a very nice feature.

**Comment by gsantner** [comment]
simple task for, friendly for beginners

**Comment by gsantner** [comment]
Closing in favor of #263 where this could be done according to any preferences, sizes and types.
