### ISSUE TITLE
White screen when i put the widget

### ISSUE THREAD

**Issue by Alexis-Martin** [gsantner/markor#25]
#### General information

* **Device:**   fairphone 2
* **Android Version:**  6.0.1
* **App version:**  0.1.2

#### Steps to reproduce

1.put the widget on a new wall

#### Expected result
**What is the expected output?**  it will open the app and we may choose a note.

**What do you see instead?** nothing just a white screen

**Comment by gsantner** [comment]
Already fixed in latest release. Wait for F-Droid to publish
