### ISSUE TITLE
HTML Export not possible 

### ISSUE THREAD

**Issue by maulwuff** [gsantner/markor#251]
#### General information
When trying to export as html file, none of the target apps can handle the sent result. 

Nextcloud says, not a valid file
Fx fie Explorer says, item can't ne saved. 
At least Threema inserts html code in the text field of a chat - but that's useless aswell. 

* **App version:** 0.3.7
* **System:** Android 7.1.1

**Comment by gsantner** [comment]
I can't control other projects or their features. Blame them, not us ;).

Just look at the export options, one below there is export as HTML as plaintext, which should work for any app allowing text.

**Comment by maulwuff** [comment]
HTML plaintext works - with some additional renaming afterwards.

Can you tell me which app is known to support your style of html export?

Why don't you let the user save the html file right to disk from your app? Would make things easier ;-)


Am 15. Mai 2018 00:09:46 MESZ schrieb Gregor Santner <notifications@github.com>:

**Comment by gsantner** [comment]
For example those below which I have installed. So pretty much every messenger.
If you want to really show something somebody, you usually anyway do export as PDF and not to HTML.

![grafik](https://user-images.githubusercontent.com/6735650/40058891-d8715760-5852-11e8-9428-86f2b17064aa.png)

**Comment by maulwuff** [comment]
Nextcloud shows an error because it doesn't receive a file, but a string. 

K9 pastes html code into the email body. That's not really useful for me. 

HTML is great for sharing, as it has less overhead than PDF and is not limited to dina4 paper format ;-)

Am 15. Mai 2018 15:17:47 MESZ schrieb Gregor Santner <notifications@github.com>:
