### ISSUE TITLE
Crash switching away from large files (TransactionTooLarge)

### ISSUE THREAD

**Issue by lokesh-krishna** [gsantner/markor#253]
Almost always, switching away from a large file leads to Markor crashing on me with the following message: Markor has stopped.  

The file in question is 9,000 words long though this has also occurred with relatively smaller files.  

Since taking notes is my primary use for Markor and my notes tend to run long, this gets in the way a lot.

What further information can I provide?

I'm attaching a screenshot of the crash message. 

![Crash](https://i.imgur.com/ClZnVbM.png)

**Comment by ali-hardan** [comment]
I have this problem too on Galaxy J5 Prime & Android 7.0

**Comment by lokesh-krishna** [comment]
That article helped a lot. I managed to grab a log but it is too verbose. How do I make it more manageable for you? It currently sits at 105844 lines.

**Comment by lokesh-krishna** [comment]
Managed to get a much cleaner log after first flushing it and then taking a log again.  

Here is the relevant [gist](https://gist.github.com/lokesh-krishna/0e4fb23eac120a057438ed5981078e5a).

**Comment by gsantner** [comment]
https://developer.android.com/reference/android/os/TransactionTooLargeException

**Comment by lokesh-krishna** [comment]
Is there any workaround that we as users can employ presently?

**Comment by gsantner** [comment]
Till I have some solution to this OS problem I think you have to split up textfiles to be smaller.

Did it work before without any problems? Somehow I can't remember any change that would put more into the onPause bundle..

**Comment by gsantner** [comment]
Btw about 

> Till I have some solution 

PRs are welcome, I don't want to keep working on Markor completly at all ;)

**Comment by lokesh-krishna** [comment]
It has always been this way for me and I've been using Markor for at least around 6 months now.  

I'll go with splitting text files for the nonce. Thank you so much :)

**Comment by gsantner** [comment]
The last commit (and so next update) will reduce loading time of files itself about 60%, reduce history by one and will also not allow to cache file in activity-transaction if it has more than roughly 9000 characters.

While 10k is the limit I want to make sure theres enough left for other stuff.

**Comment by lokesh-krishna** [comment]
Thank you so, so much :)  
What happens if a file is larger than 9,000 characters though?

**Comment by gsantner** [comment]
It won't preserve history (as in no undo-redo)

**Comment by lokesh-krishna** [comment]
Fair enough. Looking forward so much to the update :)

**Comment by gsantner** [comment]
made minor adjustmant to now max out at 9200
