### ISSUE TITLE
Share into Quicknote/To-Do/Clipboard

### ISSUE THREAD

**Issue by IzzySoft** [gsantner/markor#254]
Looking for a suitable Markdown editor/notebook, I found your project. Before I install it, I'd like to have a little clarification. The documentation mentions:

> Share into QuickNote - Pocket/Read-it-Later alternative

There are hundreds of apps going by the name of "QuickNote" – but I couldn't find any that would work as a RiL alternative. Could you please clarify (link) which one you mean?

I have the vague guess that you rather mean something along the lines of "share from any other app to Markor's QuickNote feature, which can serve as a local RiL alternative". If that's what it means, the description is a bit misleading – as Pocket is a service collecting your "notes" so you can read them from any device (including browser integration).

Similarly:

> Share into To-Do - Wunderlist alternative
> Share into Clipboard - without a seperate clipboard app

The addendum "without a separate clipboard app" on the last entry is what brought me to the guess you're talking about internal features of Markor.

If my guess is right, maybe the description should be slightly altered to avoid such confusion?

> Share into *Markor's* QuickNote as a Pocket/Read-it-Later alternative
> Share into *Markor's* To-Do as a Wunderlist alternative
> Share into *Markor's* Clipboard - without a separate clipboard app

Whichever way, it's no show-stopper – but would be really helpful when comparing apps (though if the list of requirements contains "must be available on F-Droid", there's only one other candidate left for me anyway :wink:)

**Comment by gsantner** [comment]
If you have some improvment ideas, please send a PR, I think thats the easiest to talk about.

In general, Markor is targeted to be your number one lightweight app for simple text formats, writing them and  copying/pasting/importing/sharting text! ;)

**Comment by IzzySoft** [comment]
Thanks a lot for your fast response, Gregor!

> QuickNote is a file in your markor document directory …

OK, so my conclusion/connection was right (I saw that feature and finally decided this must be what's meant).

> LinkBox is a file for bookmarks and links

Didn't see that yet in the description – definitely sounds cool!

> Yes, all internal features. Markor will never depend on other apps.

Thanks! Good to know. So would you mind the mentioned little update to the description, or …

> please send a PR, I think thats the easiest to talk about.

For that minor description change, I'd feel that a bit overkill. Not being an Android dev, there's not much else I could probably contribute. So I'd prefer you'd simply copy/paste fom above :wink:

> Markor is targeted to be your number one lightweight app for simple text formats, writing them and copying/pasting/importing/sharting text! ;)

You just made sure it is! I'll go ahead and give it a try ASAP (i.e. within the next few days) – and most likely will stay with it :)

Thanks again! With my question answered, I'd consider the issue solved (just reopen if you want it as a reminder for the minor documentation update ;)

**Comment by gsantner** [comment]
> For that minor description change, I'd feel that a bit overkill. Not being an Android dev, there's not much else I could probably contribute. So I'd prefer you'd simply copy/paste fom above wink

Still I would prefer if you or someone else can send a PR with improvements. As you see your comments above, there are a lot of misleading or not fully understandable things in the descrpition. I would be glad if I get some help on that. I think others have different views on things and my view and so description and wording can be a lot improved.

I have only one point, that the features lines stay at max-length of the following - so it doesn't go multiline too often on F-Droid :

> {smile}  scroll Allows to set language other than system setting

**Comment by gsantner** [comment]
> Understood, thanks. Not sure if I find time to fork->clone->edit->…, but will keep it in mind. Though the problem is that adding a word (as I suggested) contradicts with keeping the max-length as you just requested …

When you want and have time of course! :)
Max-length: This is only about the heading lines (with the smiley), the more informative stuff below can be in any length. The reason is that people faster grasp what this is about. I myself feel lost when I find a block of 10 text lines without linebreak or stuff :smile: .

>Apart from that: after having it installed and cleared my "initial confusion" (ahem, got the idea how it works), I start liking it very much. Expect a few "issues" during the next days – and, when I'm through, most likely a review published on my site wink

Glad to hear that! :)

BTW: Have some apps in my repo that could suit yours too. Eg.g. not much games are in. SDL project has a lot of games that will likely never get published on F-Droid but work very well (and are FOSS) - <https://sourceforge.net/projects/libsdl-android/files/apk/> - SuperTux

**Comment by IzzySoft** [comment]
No promises, Gregor; usually I already drown in other tasks. No timing for the article yet either, though it's definitely on my list.

> I myself feel lost when I find a block of 10 text lines without linebreak or stuff :smile: .

You're not alone with that! OK, once the article is done (and my thoughts are written down), I could see where to fit something into the description.

> BTW: Have some apps in my repo …

Well, I don't take games, and there are some other restrictions as well (see e.g. [here](https://apt.izzysoft.de/fdroid/index/info)). But if something fits, be welcome to [file a request](https://gitlab.com/IzzyOnDroid/repo) :wink:

**Comment by AsmoLab** [comment]
Interesting approach to "To-Do's" thanks for creating the post and for all the answers.
I'd like to share one more alternative our team created, it's a free tool called Zenkit, we'd love to have tour opinion on it:
https://zenkit.com/en/alternatives/Wunderlist-alternative/
