### ISSUE TITLE
Remember position in file list

### ISSUE THREAD

**Issue by IzzySoft** [gsantner/markor#256]
#### General information

* **App version:** 0.3.7 (F-Droid)
* **System:** Wileyfox Swift, Android 6.0.1 (CyanogenOS)

#### Description
When opening a document from the list, then closing it, list jumps to the start. Best explained by an example: Imagine I have 100 documents in a folder, the first being `Anchor.md`. Now I open `Notes_Mary.md`, read/edit, and close it again. File list has jumped back to `Anchor.md` (the first document) again, but I wanted to cross-check with `Notes_Peter.md` – so I have to scroll through the list a lot.

#### Suggested behavior
When closing the document, the list still remains at the place/position where the just document (in above example: `Notes_Mary.md`) was opened from. _Optionally,_ there could be a floating button (or something else) to "jump to top".

#### Note
I'm not talking about "remembering position between app starts" here :wink:

**Comment by gsantner** [comment]
```
onResume -> bundle.get(y_scroll) , scroll set
onPause -> bundle.put(y_scroll, scroll get)

**Comment by IzzySoft** [comment]
That was fast – thanks! Looking forward to the next version then.
