### ISSUE TITLE
ToDo: How to easily mark a task done?

### ISSUE THREAD

**Issue by IzzySoft** [gsantner/markor#258]
The ToDo view already has a special design: each item with a timestamp, no line breaks inside an item, and rulers to separate them – which is great. What I miss is a way to

* easily mark an item "done" (e.g. `~~strike it~~`)
* easily remove an item

Not familiar with implementation I could think of different approaches:

* long-press on an item opening a context menu, offering to "mark done", "remove" and maybe some other useful actions
* [ ] prepending items with a checkbox (unmarked) wich can be toggled by a simple tap, and a long-press would fire a "do you want to remove" dialog
* open to other solutions as well :wink:

Would something along those lines be possible?

**Comment by gsantner** [comment]
"ToDo" is using the todo.txt format, and you check/uncheck by inserting a x in front, or by the x button.

Trash can deletes, X marks as done, everything is there what you asked for.

**Comment by IzzySoft** [comment]
Uh! :scream: I was blind. Blame it on the display (5" is too small for an editor). I totally missed the bottom navigation bar. Mea culpa!
