### ISSUE TITLE
TextAction: Insert time/date, for current or selected time

### ISSUE THREAD

**Issue by IzzySoft** [gsantner/markor#260]
When in Todo mode, the bottom bar a.o. contains a "calendar icon" which, if tapped, inserts the current date. Unfortunately, this is not available in the other modes (QuickNote, Notebook). Could you please make it available there as well?

<sup>(spin-off from #257)</sup>

**Comment by gsantner** [comment]
has somebody started working on this?

**Comment by IzzySoft** [comment]
Not me, I'm not an Android dev, sorry.

**Comment by gsantner** [comment]
From #374 comes the idea too to always have the actual date in Presentation mode. So beside selecting an date/timeformat there should be an checkable option to just insert the formatstring instead of the parsed string.

**Comment by gsantner** [comment]
@IzzySoft I'm thinking about replacing this issue with a new one. I think this issue lacks lots of details what should be done and what are basic requirements (for date/time picking and format selection) :)

**Comment by IzzySoft** [comment]
@gsantner Go ahead and organize it the way it's best for you. I'm fine with that. What counts for me is getting it done :wink: So maybe combine the two issues into one new covering all aspects would be what you'd like.

**Comment by gsantner** [comment]
Disabled conversation on this (#260) and the other issue (#374). When somebody comes here, please go ahead to #375 :).

**Comment by gsantner** [comment]
Done at #454 , will be available in next update (> 1.5.0).

Example: 

![https://user-images.githubusercontent.com/22313019/49843145-73032680-fdbe-11e8-8055-16d0befbfc19.gif](https://user-images.githubusercontent.com/22313019/49843145-73032680-fdbe-11e8-8055-16d0befbfc19.gif)
