### ISSUE TITLE
Change font size for preview

### ISSUE THREAD

**Issue by lokesh-krishna** [gsantner/markor#262]
I'm sorry if I'm missing something but it seems like it is presently not possible to adjust the size of the font used for the preview.

It would be really nice if this was added as an option or if it would simply inherit the font size picked for the editor.

**Comment by ali-hardan** [comment]
I suggest to be add "custom CSS" option. you can change font size by customization CSS.

like [Diary](https://github.com/billthefarmer/diary) app.

**Comment by gsantner** [comment]
ali-hardan: please open request for custom css. but nope, i want in general this to be inherited by app-settings font size. yours is a good idea for addition.

**Comment by gsantner** [comment]
Closing in favor of #263 where this could be done according to any preferences, sizes and types. I will make preview to inherit the global font options. The rest one can customize to wishes by CSS.
