### ISSUE TITLE
App crashes when trying to view "Info" for folders

### ISSUE THREAD

**Issue by free-soul** [gsantner/markor#264]
#### General information

* **App version:** v0.3.8
* **System:** Android 8.0.0 on Honor 9 Lite

#### Description

After selecting a folder (press and hold) and on selecting "Info" from menu Markor app crashes. Would be nice if folder details (number of documents inside, their titles etc.) are shown.

**Comment by gsantner** [comment]
thanks. open for pull requests. please continue any discussion on #160
