### ISSUE TITLE
Remove fine line at the bottom of the icon

### ISSUE THREAD

**Issue by lokesh-krishna** [gsantner/markor#265]
Presently the Markor icon seems to have a line at the bottom which creates a shadow effect of sorts when not using adaptive icons. This is however something that launchers can handle on their own.

When using adaptive icons with any mask, this line can no longer offer even that shadow effect and instead ends up appearing like an artifact.

Could you consider doing away with this line unless I'm missing some purpose that it serves? If it does need to stay then is there a way to remove this from the background layer of the adaptive icon while retaining it in the legacy icon?

Attaching images for reference:

![](https://i.imgur.com/A5weKRe.jpg)

The line doesn't get in the way here but the launcher itself offers a shadow.

![](https://i.imgur.com/UB3HxZh.jpg)

Here the line just appears like an artifact.

**Comment by lokesh-krishna** [comment]
zjis? I am sorry but I didn't understand that.

**Comment by gsantner** [comment]
this.

**Comment by gsantner** [comment]
its the other way round. there is no white fill at this point.

**Comment by lokesh-krishna** [comment]
I'm using the 0.3.9 build which carries the fix but the icon still displays as earlier.
 Attaching image for reference:

![](https://i.imgur.com/ni5yMiQ.png)

**Comment by gsantner** [comment]
There is no single thing blackish, blue or something on bottom and it doesnt appear on any of my launchers on mx oreo device - are you sure its not from your launcher?

**Comment by lokesh-krishna** [comment]
I tried two other launchers. The first was Pixel Launcher:

![](https://i.imgur.com/MqzaWho.png)

The line shows up in this as well.

The second was Nova Launcher:

![](https://i.imgur.com/PNtg3Ou.png)

There is no line here. So it is a launcher dependent issue. Is there anything that can be done on the launcher end of things to fix this so that I contact the developers? My default launcher is the one that comes with OmniROM.

**Comment by lokesh-krishna** [comment]
Just wanted to report that this is finally not an issue on the default OmniROM launcher.
