### ISSUE TITLE
Written text gets missen on screen rotation 

### ISSUE THREAD

**Issue by Olamatto** [gsantner/markor#269]
#### Expected behavior
While writing a text, the application ought to work perfectly well and stable on any screen orientation.

#### Actual Behavior 
After typing a text, then changing screen orientation makes all written text wipe off. 

#### How to reproduce
- Download and install the application [here](https://f-droid.org/repository/browse/?fdid=net.gsantner.markor)
- Lunch the application 
- Click on add note 
- Put in a title,  add some text in the text box
- Now rotate the screen to landscape mode and see that all text has been deleted 
<hr>

Application version: v 0.3.8
Operating system: Android v7.0

#### Recording Of The Bug
https://youtu.be/f8NQJdoLI3w

**Comment by gsantner** [comment]
there is one special case where you won't see the text on rotation, but it's not lost, only not shown

**Comment by Olamatto** [comment]
It's actually lost,  even rotating it back it can't be found.
