### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by KrKK** [gsantner/markor#27]
Maybe in next update you add support to tables?

Example:

| Hours | Monday | Thursday | Friday |
|-|-|-|-|
| **8:00 - 8:45** | pe | english| maths |
| **8:55 - 9:40** | biology | geography | ict |

**Comment by gsantner** [comment]
The app does not implement a markdown parser/convertor, but uses an library. If you want such functionality help us searching a better one, which is not too bloated. Further discusison please in #30

**Comment by gsantner** [comment]
Markor supports tables since long time. In next update (Markor>=v2.1.7) there will be textaction button to make it easy to create tables.

See video for #338 :
 ![video_2019-10-27_14-16-37](https://user-images.githubusercontent.com/6735650/67635210-38ae5500-f8bc-11e9-8ca0-6e45919bf329.gif)
