### ISSUE TITLE
App crashes while creating folder on screen rotation 

### ISSUE THREAD

**Issue by Olamatto** [gsantner/markor#270]
#### Expected behavior
App ought to remain stable on any screen orientation, while creating a folder 

#### Actual Behavior 
While creating a folder, saving a new folder on screen rotation makes app crash. 

#### How to reproduce
- Download and install the application [here](https://f-droid.org/repository/browse/?fdid=net.gsantner.markor)
- Lunch the application 
- Click on option button by the top right
- Select create folder
- Type in folder name, then rotate the screen to landscape 
- And click create

Then the app crashes 
<hr>

Application version: v 0.3.8
Operating system: Android v7.0

#### Recording Of The Bug
https://youtu.be/bTrUERF7yb4

**Comment by gsantner** [comment]
thanks but this has already been reported
