### ISSUE TITLE
help wanted: is it possible to remove vibration?

### ISSUE THREAD

**Issue by puntomaupunto** [gsantner/markor#274]
#### General information

* **App version: 0.3.9 Google Play** 
* **System: Android 7.1.1, Gemini phone** 

#### Description

(first important bit: Gemini phone has a physical keyboard)
Pressing a key makes a vibration, which is a bit annoying since I have already the feedback from the keyboard. Is there a way to disable this vibration\/

**Comment by gsantner** [comment]
this all is coming from OS. I dont do any animation, vibration or sounds at markor

**Comment by puntomaupunto** [comment]
ok, thanks! I'll check elsewhere how to remove it :-)
