### ISSUE TITLE
Feature: Auto hide top title bar when on-screen keyboard shows.

### ISSUE THREAD

**Issue by ali-hardan** [gsantner/markor#275]
It's good feature for who wants to only write and wants to see nothing except the text.

You can see [Writer Plus app](https://play.google.com/store/apps/details?id=co.easy4u.writer). It's has this feature and very simple & attractive gui. But it's closed-source...

**Comment by gsantner** [comment]
Good idea.

From experience I know that detecting if soft keyboard is visible or not, or status changed is not possible. Still not at Android in 2018. Only hacky solutions available.

**Comment by GhostInTheSteiner** [comment]
> From experience I know that detecting **if soft keyboard is visible or not**, or status changed is not possible. Still not at Android in 2018. Only hacky solutions available.

Please, become a bit more creative and rethink your user's needs. The goal of that feature is to enlarge the content's space on screen, so it's totally sufficient if you hide it while the user is scrolling down. Other apps like Pure Writer implement said behaviour quite nicely ;)

Excuse my slightly harsh reply, but I really like your app and that's literally the only feature holding me off from using it. Should I open a new issue or do we reopen this one?

**Comment by gsantner** [comment]
Doesn't change the fact that Android does not offer a proper solution, and the hacks/workaround are often working rather bad. I have tried multiple solutions and spent much time on it, I was not happy about any.
