### ISSUE TITLE
Markor very slow when editting long documents.

### ISSUE THREAD

**Issue by ali-hardan** [gsantner/markor#276]
Markor very slow when editting long documents. I have tested 1.3MB document. Markor is very slow, but some closed-source apps, like [QuickEdit](https://play.google.com/store/apps/details?id=com.rhmsoft.edit) is highly fast & stable for editing long documents. Test it!

**Comment by gsantner** [comment]
This is because of syntax highlighting used. For big documents it is recommended to disable hightlighting.
Not much we can do about that, regexes are already optimized very much.

**Comment by ali-hardan** [comment]
I have disabled syntax highlighting, but it's still very slow.

Why fixing it not possible when some other apps (like QuickEdit) fixed it and can edit large documents fastly by them?

**Comment by gsantner** [comment]
All our stuff is based on Regex - and do all at once work. This hardly wont ever change, writing this in custom from scratch is own science which isnt in scope.

**Comment by meonkeys** [comment]
One idea would be to allow disabling of syntax highlighting while keeping auto-indenting, auto-bullets, and auto-numbering enabled. Is that possible?

(links to other related issues: #90 #169 )

**Comment by gsantner** [comment]
@ all / @meonkeys : Auto formatter (that does add e.g. bullet when pressing enter in list) is now enabled indp. to highlighter. This means if you want to get something faster, you can disable highlighter right now, while still getting the format-specfic benefits inside the editor input field.
