### ISSUE TITLE
Feature: custom font for editor by selecting TTF file.

### ISSUE THREAD

**Issue by ali-hardan** [gsantner/markor#277]
use custom font for editor by selecting TTF file. like [QuickEdit app](https://play.google.com/store/apps/details?id=com.rhmsoft.edit).

**Comment by lokesh-krishna** [comment]
Why was this issue closed? Is it because the request was implemented or because it won't? 
If it's indeed possible to pick a .ttf file then where should it be located?

**Comment by gsantner** [comment]
because it is implemented.

https://gsantner.net/blog/2019/05/06/markor-v1.8-file-navigation-favourites-markdown-editor.html
