### ISSUE TITLE
Special docs: diary/journal

### ISSUE THREAD

**Issue by nutpantz** [gsantner/markor#278]
I would love to see a diary or journal option, just a text file (with auto date and time in the first line) saved in it's own directory. File name as the full date and time (military time would work better than am/pm)would be all that's really needed.

**Comment by gsantner** [comment]
can you give some more details on exact flow. when creation, how many files (every day one?) .. and many other things.

**Comment by ali-hardan** [comment]
A very helpful example is [Diary app](https://github.com/billthefarmer/diary). It's a foss Android application. It supports markdown syntax. It saves your journal to plain text files. all day has a file.

for example, my today diary will saves in: `/sdcard/Diary/2018/06/09.txt`

**Comment by gsantner** [comment]
If gets implemented, than it should be done by the means of "filepath template". As in having specifiers for year,month,date etc the user can specify himself. if resolves to existing filename, then just open.

**Comment by gsantner** [comment]
has somebody started working on this?

**Comment by gilcot** [comment]
@nutpantz  See [Bill Farmer's rewrite of Diary](https://github.com/billthefarmer/diary) ; it's already doing the job. So let's keep Markor as simple and generic as it is.

**Comment by gsantner** [comment]
So to sum this up:
* You can basically keep diary / journal with markor, having the structure like other app uses is a nice to have, but it's not planned to add special "add" button which does only the job to work like this
* But: I'm thinking of adding "file" template, which means you could do "%yyyy-%mm%-%dd.md" and get that pre-set when adding new file. This is something unrelated to this issue or what is wanted here, but something users (and myself) asked for.
