### ISSUE TITLE
Files are read-only on SD card

### ISSUE THREAD

**Issue by fxshpac** [gsantner/markor#279]
#### General information

I can't make any changes saved to files which reside on SD card.

* **App version:**  0.3.10 from Play Store
* **System:** Samsung Galaxy S8+ with stock 8.0

#### Description

I can open the file, preview the file but if I make any changes to the file and save it. Then re-open it later, the content stays untouched.

**Comment by gsantner** [comment]
I dont think that markor can make any fixes here. If your card isnt writeable, or your samsung ROM disallows it, markor cant write to it.

**Comment by fxshpac** [comment]
I don't think the Samsung ROM is disallowing it because I have other apps which can write to SD card with no issues. So technically Markor can archive the same. Let me know your thoughts on that. Thx

**Comment by contrapunctus-1** [comment]
Facing the same issue on Android v9, Nokia 6.1. Syncthing can write to the path, but Markor says it cannot.

Remounted the card, issue persisted. I'm not sure what I did next (tried adding a new file?) which caused Markor to ask me to select the SD card root path. It worked after that.

**Comment by gsantner** [comment]
I'm afraid that I can't help you on this. When the correct storage is mounted it should behave same like syncthing or other apps. Unless you use root at the other app.
