### ISSUE TITLE
Add support for unix lineendings

### ISSUE THREAD

**Issue by hnicke** [gsantner/markor#280]
#### General information

* **App version:** v0.3.10 (24), installed via fdroid.
* **System:** Android 7.1.2, Samsung S5 (klte), LineageOs.

##### Wittnessed behaviour
I'm syncing some notes in .md format between my phone and my unix workstation. After markor wrote it's changes to the file, all line endings are in DOS style (^M).

##### Expected behaviour
Markor should respect the line-ending style of each file and not change it.

Did I simply miss the option in the config?

**Comment by hnicke** [comment]
I've further investigated the issue. Markor is handling line endings correctly.
The problem is the sync program ("synchronize ultimate") or the nextcloud server.

**Comment by gsantner** [comment]
Thanks for letting know reason
