### ISSUE TITLE
CSS property support

### ISSUE THREAD

**Issue by fxshpac** [gsantner/markor#281]
#### General information

* **App version:** 0.3.10 from Play store
* **System:** Samsung Galaxy S8+ Stock Android 8.0

#### Description

I have a md file which links to a picture taken in portrait mode but when previewing it in Markor it's in landscape mode. 

If I take the html output of the md file, add the following CSS property to the html header and open it in PC browser, the picture is shown in portrait mode correctly.

```
<style> img { image-orientation: from-image; } </style>
```

So I injected the same CSS property in Markor hoping to get the same result but unfortunately it's not doing anything. Is this because Markor doesn't support this particular CSS property?

**Comment by gsantner** [comment]
I cant help you with user  custom styles/css. Export the whole as .html, look at it at desktop and edit the css in header till you find out it works.

**Comment by gsantner** [comment]
I cant help you here. Maybe androids webview implementation does not supply exifdata.
You can always correctly rotate your picture without exif.
