### ISSUE TITLE
[Not an Issue] Thank You

### ISSUE THREAD

**Issue by bauripalash** [gsantner/markor#282]
I am a student and have a Jekyll blog hosted on GitHub. I could not find a easy way to write blog posts with markdown until i found Markor.

 Markor is helping me a lot to write articles in Markdown and Work on my mission to make the world a better place..

This is not an Issue , Feel Free to close it.

**Comment by gsantner** [comment]
That was one of the main reasons and things I do with Markor too ;).
Thanks for  feedback!
