### ISSUE TITLE
Export to calendar

### ISSUE THREAD

**Issue by joshimio** [gsantner/markor#283]
Hi,

In the app neutrinote, from inside the note you can hit Menu > Paste to Calendar. This adds a link in the Notes/Description field of a standard calendar entry. Then from the calendar if you click this link, it opens up the note in neutrinote. In effect this allows you to add more information to calendar entries, including images, through a notes app.

This would be a nice feature to have in markor too. 

Thanks.

**Comment by gsantner** [comment]
This was already on my personal list but not created bug yet
