### ISSUE TITLE
Seperator based on setting

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#287]
#### Description
Add options for Markdown syntax, Plain syntax, LinkBox special file, ToDo syntax, that allow to specify text to be appended.

Also allow to specify some variables/dynamics. A Jekyll user may know liquid date syntax, which I do prefer for resolving this.

 Currently this is:

* Date:  `{{ date: "dateformat" }}`
* May be extended. date most important

For ToDo use as default: `{{ date: "dateformat" }}`

Replaces: #259 #284 #286

**Comment by svemoe** [comment]
I am a newbie, but I am willing to work on that issue :smile:
