### ISSUE TITLE
Incompatibility with images added with other editors

### ISSUE THREAD

**Issue by wedza** [gsantner/markor#288]
#### General information

-   **App version:** 0.3.10 (24)
    
-   **System:** Android 8.1.0
    

#### Description

I don't know how to explain the issue so I'm gonna take an example. 

For an image called "i like apples.png", Markor will save the image with the path "./folder/i&20like&20apples.png" _(which work well in Markor)_.

However, in most Markdown editor, there's no "&20" instead of the space, so Markor doesn't show the picture, which leads to an incompatibility when using multiple Markdown editors.

It will be great if Markor will be able to show images, even If it doesn't have been inserted in Markor.

Here's an example. The first image has been added with another Markdown editor (Mark Text), and the second one was added with Markor.

![image](https://user-images.githubusercontent.com/20335741/41823287-c87bfa52-77fd-11e8-8dbd-ab77137c6ce3.png)

Results to this 

![image](https://user-images.githubusercontent.com/20335741/41823279-af34d122-77fd-11e8-80c1-b701fc7abb8a.png)

Thanks a lot for your app, I'm migrating from proprietary software to this and I'm delighted.

**Comment by gsantner** [comment]
Hi, thanks for reporting.
This is behaving like specified in Commonmark Markdown Specification.

Image and Links are sharing most in spec (see image section). Example 463 shows that URL must not contain whitespace.
<https://spec.commonmark.org/0.28/#example-462>
Even tho it may look not easy on eyes, this (%20) is how todo it and the most compliant way.
I cant do much about that, it's the parser we are using doing this - and it just works conform to spec which is good.
