### ISSUE TITLE
Widget not opening selected files

### ISSUE THREAD

**Issue by bjesus** [gsantner/markor#289]
#### General information

* **App version:** 0.3.10
* **System:** Android 8.1, Google Pixel

#### Description
When clicking a file on the Markor widget, I only get an empty new file and without even the ability to edit it (the title bar is editable, but the content isn't).

Please see https://imgur.com/a/dyI6mnj  . I'm clicking on three files and nothing opens, than I'm clicking on "new file" button and you can see I get a slightly different screen (the toolbar shows up at the bottom of the screen).

**Comment by gsantner** [comment]
open for pull requests.

**Comment by bjesus** [comment]
Is this happening to everyone? I mean, can someone just confirm that this is indeed a bug?
Also, was this working in the past? Any idea on what might have changed? I'd be happy to try and fix it, some hints would be appreciated! Thanks!
