### ISSUE TITLE
FR: Support of github flavored markdown

### ISSUE THREAD

**Issue by KabbAmine** [gsantner/markor#29]
First of all, thank you for your awesome app, having and making all my notes in markdown, your app is a real life saviour.

The only thing I miss is [gfm](https://github.github.com/gfm/) support. Can it be implemented? At least tables (#27) and task list items ([github-markdown-css](https://cdnjs.com/libraries/github-markdown-css) may help).

**Comment by gsantner** [comment]
The app does not implement a markdown parser/convertor, but uses an library. If you want such functionality help us searching a better one, which is not too bloated. Further discusison please in #30
