### ISSUE TITLE
feature request: file encryption

### ISSUE THREAD

**Issue by nutpantz** [gsantner/markor#292]
I would love to see any method of encryption implemented.  Either universal password in settings to be used for all encrypting and then just pick to "save as encrypted" and have anything encrypted auto opened with the password in settings.
Or a way to use open key chain to encrypted and decrypted notes internally not by sharing the text.

**Comment by gsantner** [comment]
See #60.

If theres no community work / PR this likely wont happen. I like it, but without bloating the app with many libs this won't be easily possible. Too theres massive problems because different android versions don't support many things, or api calls are not compatible between.

**Comment by fullstopslash** [comment]
https://www.openkeychain.org/ is an app that deals with the encryption and key management. All that would have to happen is taking advantage of the interface from the app.
