### ISSUE TITLE
Markdown:  highlighting code blocks issues

### ISSUE THREAD

**Issue by thousandsofthem** [gsantner/markor#293]
#### General information

* **App version:** 
v0.3.10 (24) F-droid

* **System:** 
Android 8.0.0, Samsung S8+, stock

#### Description

1) code blocks are not supported (backticks x3)
e.g.
```
Stuff
2nd line
```

2) Dark theme, code block color is "white-on-almost-white", which is hard to read

![screenshot_20180710-133507_markor 01](https://user-images.githubusercontent.com/736279/42504975-0877f6ca-8446-11e8-87d6-354924e19e6f.jpg)

Overall, great app! :heart:

**Comment by gsantner** [comment]
Highlighting of \`\`\` code blocks is disabled on purpose. Every bit of highlighting takes massive amount of cpu/mem, and this one is one of the biggest ones.
