### ISSUE TITLE
Status Bar hidden : Display twitch while editing note

### ISSUE THREAD

**Issue by pyluyten** [gsantner/markor#294]
#### General information

* **App version:v0.3.10 (24)** 
* **System:Android One 8.0.0** 

#### Description

How to reproduce : Setup Editor in full screen mode (hide status bar). Then Edtit a note. To reproduce the bug it might be necessary to edit a long note or delete some cars.
Effects : there is a graphical twitch. Maybe bar is shown then hidden again, but too quickly to be seen.

**Comment by gsantner** [comment]
upload screenrecord e.g. to github repo and link it. cannot see this

**Comment by pyluyten** [comment]
sorry i could not reproduce it. If it happens again i will upload a screerecord.
