### ISSUE TITLE
White-on-light highlighting in edit mode

### ISSUE THREAD

**Issue by dvdtGravWe11** [gsantner/markor#295]
#### General information

* **App version:** 0.3.10
* **System:** Android 6.0.1, OnePlus One, CyanogenOS 13.1.2-ZNH2KAS3PO-bacon

#### Description
When editing while using the dark theme, text formatted as code is highlighted in a bright color, resulting in a white on light appearance that is very hard to read.
Examples:
```
    Text
`Text`
```

    ```Text```

**Comment by gsantner** [comment]
At Markor we use only one set of highlighting colors, mainly due performance reasons, to not  have to lookup additionally things.
If you have a suggestion that works better for both, dark and light time, pass on the hexcode ;).

**Comment by returntrip** [comment]
hey @gsantner as per separate chat: HEX codes for BG with samples
LT: https://www.w3schools.com/code/tryit.asp?filename=FU8847JQXI8M
DT: https://www.w3schools.com/code/tryit.asp?filename=FU883SNISM53

Thanks for your time!

**Comment by dvdtGravWe11** [comment]
The backgroun color of #8c8c8c works very well, @returntrip . I think you picked well!

Thanks to the Markor Team for working on this! I love the app.

**Comment by gsantner** [comment]
Works fine yes, thx for suggestion.

@dvdtGravWe11 : currently team is only me, but glad you like it

**Comment by gsantner** [comment]
Color included in latest changes, will be in next release v1.0.1 due in some days.
