### ISSUE TITLE
Feature Request: Toggle text wrapping

### ISSUE THREAD

**Issue by dvdtGravWe11** [gsantner/markor#298]
#### General information

* **App version:** 
Markor version 0.3.10
* **System:** 
CyanogenOS 13.1.2-ZNH2KAS3PO-bacon
Android 6.0.1

#### Description
It would be nice to have an option to toggle text wrapping off, and the ability to tap and drag to pan across long lines as necessary.

**Comment by gsantner** [comment]
use search.
