### ISSUE TITLE
Find better markdown parser/convertor

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#30]
Anddown lacks a lot of functionalities. It would be better to replace it with something more powerful. But it should still be lightweight and not a fully bloated library like RxMarkdown, which would pull in RxJava and son on.

**Comment by KabbAmine** [comment]
Have you considered [commonmark-java](https://github.com/atlassian/commonmark-java)? Looks like a promising library and quite extensible.

*Note that I'm not a java developer, so I'm just assuming from their README that it may be what you need*

**Comment by sjmduncan** [comment]
commonmark-java does look promising, and also like a drop-in replacement for AndDown. I'll see how it performs.

**Comment by gsantner** [comment]
@sjmduncan Does it support highlighting too? Having both with the catch of one replacement would even be better :D (but no must)

**Comment by sjmduncan** [comment]
@gsantner Would be nice! It seems possible even!

It might not be all that easy. There's some relevant discussion here [here](https://github.com/atlassian/commonmark-java/issues/1) and a [fork](https://github.com/vsch/flexmark-java) which addresses that issue (but has lower performance). There's also the [extension API](http://www.javadoc.io/doc/com.atlassian.commonmark/commonmark/0.10.0). I haven't looked at anything in much detail yet.

**Comment by sjmduncan** [comment]
I've replaced AndDown with commonmark-java since it was mostly trivial, the one drawback is that it's a little slower.

I've started looking to use it for syntax highlighting but haven't decided what the best way to do that is. For the moment syntax highlighting won't *quite* match the preview.

**Comment by gsantner** [comment]
I think in Markor the preview can be slow, as it is done once, so no problem. At edit highlighting it is important to be fast.
