### ISSUE TITLE
Filter to do list by priority, context, tag or keyword

### ISSUE THREAD

**Issue by schultzter** [gsantner/markor#300]
#### General information

* **App version:** v0.3.10 (24)
* **System:** Android 8.0.0

#### Description

Trying Markor (and todo.txt) and it would be really useful to be able to filter the to do list by any combination of priority, context, tag, or keyword. If there's already a way to do that I haven't been able to find it yet, sorry.

Thanks,

#### Log

N/a

**Comment by gsantner** [comment]
Sort is on the wishlist, thats what you want I think. Filter means delete, I guess you don't want to delete :)
#211

**Comment by schultzter** [comment]
Looking forward to search. 

What would also like is to focus on a context or tag. For example, if I have a context @Home then I would like to show only those items tagged with @Home. Similarly for combinations of priority, context, and tags. 

Thanks.

**Comment by gsantner** [comment]
Always open for pull requests!
