### ISSUE TITLE
Multi-step undo (or: I just irretrievably deleted whole file!) 

### ISSUE THREAD

**Issue by linuxcaffe** [gsantner/markor#302]
Markor just went from hero to zero, in my books, as a file I had been working on just disappeared, without a trace! Poof!

I had previously hit the floppydisc (save?) icon (without feedback) and one moment, the previews were looking good, the next, all gone.. I suspect fat fingered the trash can, and one more keystroke..

So, this issue is to mitigate the future vanishings, maybe multiple undo steps, maybe save a version every time you hit the disc icon, maybe a warning on the trash icon?

I don't feel like I can currently trust markor with anything important, like the file I was just working on, but I enjoyed using it till then :)

**Comment by linuxcaffe** [comment]
Thanks for explaining how Markor's undo feature works. I still don't know exactly how I made the file disappear, probably related to select-all and..? but it was instantaneous and (seemingly) unrecoverable, but I like the app, so I'd be happy to join the discussion and help ensure that it can't happen again.

You suggested that there should be 5 steps back available, limited by memory, maybe user definable memory limit, for undo? (for me, the "back" button seemed to grey-out after a single step)

The trash icon could have an optional prompt (delete Y/n?), if (for example) the text to be trashed contains a newline character (ie. consists of multiple lines) or some other threshold(s).

The ultimate dufus-proofing might be to piggyback on a revision-control (git?) so that each time the save icon is hit, revisions (if any) are saved, and the file could be rolled back to any state, any time.

As to writing fast on touchscreens, I'm using a compact bluetooth keyboard, with Markor fullscreen, so...

Thanks for the consideration and the fine software :)

**Comment by gsantner** [comment]
Git is no option here, no. But anything else that supports single-document-revisioning (in memory) is an idea
