### ISSUE TITLE
Format: Ledger (Accounting, money)

### ISSUE THREAD

**Issue by devmsv** [gsantner/markor#303]
Hi, would it be possible to add ledger (*.ldg *.ledger) syntax highlight and recognition to markor?

Ledger is a plain-text accounting system and it would be great to have support on markor to take notes of expenses on the smartphone.

If not it would be great an option to add some extension so its appears on the app just to edit it normally.

See: www.ledger-cli.org for more info

**Comment by gsantner** [comment]
I don't know that format and not thinking of starting on it. But I'm open for reviewing and merging pull requests if someone works on it.

**Comment by linuxcaffe** [comment]
fwiw, I would use this :)

**Comment by gsantner** [comment]
free to work on

**Comment by gsantner** [comment]
Hey, have small news on this: Now you can open ledger files with Markor. Just like recent Asciidoc addition, it gets loaded in Plaintext format, so you can edit the files with Markor. Note that no ledger specific features or highlighting is there, and I don't plan to implement that on my own.

**Comment by gsantner** [comment]
Hey, have small news on this: Now you can open ledger files with Markor. Just like recent Asciidoc addition, it gets loaded in Plaintext format, so you can edit the files with Markor. Note that no ledger specific features or highlighting is there, and I don't plan to implement that on my own.

If you wish to include a "template showcase file" to Markor which shows ledges features, I'm happy to add one if you send it. (Similar to i.e.  Zim, hugo files in dropdown at new file selection).

**Comment by gsantner** [comment]
Closing, so far nobody stepped up for this. If there is interest, start to work on it please and make a pull request. Thanks.
