### ISSUE TITLE
Color red on gray (dark theme) 

### ISSUE THREAD

**Issue by marwal88** [gsantner/markor#304]
#### General information
Link / highlight color red is messing with your eyes on a gray background.
If this is a preference-thing one should be able to choose it away.

See help-pages using dark theme to see/reproduce the issue. 
* **App version:** 0.3.10
* **System:** android N

**Comment by gsantner** [comment]
Red is the accent color of the app, and accent color is used by default on textviews for links.
Even more, red on black isnt sooo bad, there are much worse examples I experience every day.

![grafik](https://user-images.githubusercontent.com/6735650/43993716-4b08561e-9d92-11e8-9129-ea0708d1b098.png)

Closing.
