### ISSUE TITLE
Text-Module-Action: Ask for picture (drawing / camera)

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#306]
The goal is to get a Text-Module-Action (bottom bar action in editor) to request a picture from another application, and insert the picture than according to format `![name](path.jpg) in markdown`.

The main points would be:
* Quick access to a camera app (There should be a camera intent filter be available)
* Quick access to a drawing app (Very possible - direct intent to start "Simple Draw (FOSS)" app)
* Else quick access to any picture supplying app

**Comment by gsantner** [comment]
Every help welcome, happy to review PRs ;)

**Comment by gsantner** [comment]
<https://github.com/gsantner/memetastic/blob/master/app/src/main/java/io/github/gsantner/memetastic/activity/MainActivity.java#L469>

**Comment by Conceptron** [comment]
Hi, I have almost finished implementing this feature, but I am facing a bug. 

Doing `_hlEditor.getText().insert(...)` is not changing the text in the editor after the camera actiivity returns. [Link](https://github.com/Conceptron/markor/commit/9f7ba47621bb6ed61e0cfe1ae0d6695b6294b762#r30364490) to line of code. You can see the commit details in the same link.

**Comment by gsantner** [comment]
Well done @Conceptron!


* We now have  at the MD-Image button additionally:
  * Camera picture
  * Gallery picture
* Beside dialog UI most abstracted and reusable in other apps, via ShareUtil

* Changes <https://github.com/gsantner/markor/compare/f17e2c78b6a6dcc0598af3d5a453d495ba491249...d38456d99bba3992e1adb6de48d774384bcfedbf>

![screenshot-2018-09-04__12-31-00](https://user-images.githubusercontent.com/6735650/45026402-79a33480-b03e-11e8-99de-422740cbc54a.png)
