### ISSUE TITLE
'Hide statusbar' crashing an app

### ISSUE THREAD

**Issue by KrKK** [gsantner/markor#31]
#### General information

* **Device:**   LG L5 (LG-E610)
* **Android Version:**  Android 4.1.2
* **App version:**  v0.1.2

#### Steps to reproduce

1. Enable 'Hide statusbar' in Editor Settings
2. Open or Create new file

#### Expected result
**What do you see instead?**
'Hide statusbar' in App Settings doesn't crash

**Comment by gsantner** [comment]
Update the app

**Comment by gsantner** [comment]
Are you sure that you have 0.1.2 installed?

**Comment by gsantner** [comment]
This is fixed 0.1.3. Wait for F-Droid to publish it.

**Comment by KrKK** [comment]
Ok, thanks
