### ISSUE TITLE
Root considerations

### ISSUE THREAD

**Issue by FBachofner** [gsantner/markor#310]
Hi @gsantner 

in #290 you say:

> You can use root permission to edit them (to dangerous!), somehow rely on a system app to get somehow access, maybe some dirty hacks or hidden APIs to get access. I don't want to do that, none of them.

This is certainly your right and you also make some good arguments for it.  You might also, however, consider the following: most people who use a markdown editor probably have some significant IT "chops" and know the potential pitfalls of root access.

You initial "solution" to the write-to-SD card seems to be a good step in the right direction (at least it makes the program's limitations more transparent).  I look forward to testing the next version of Markor.

Also, FYI -- closing a thread to persons who have previously commented on a thread is probably counterproductive in that you may see new threads like this one.

Thanks for your excellent work on Markor to date.

**Comment by FBachofner** [comment]
In addition to writing to SD card as Root, there does seem to be an "official" way to allow no-hassle SDCard-writing.

There is an article [here](https://metactrl.com/docs/sdcard-on-lollipop/) which describes it for Android >= 5.x

I followed similar step and this seems to be how I enabled SDCard writing on my main phone for apps like FolderSync, QuickEdit and Epsilon Notes.

Sorry in advance if this is considered a "dirty hack" by you.  It seems legit . . . but I am not an Android developer, so my lens is different than yours.

**Comment by gsantner** [comment]
I have unlocked the thread again - I did this to not get 10 comments back with "it still doesnt work", and write back multiple times - it cant because you dont have the update yet. :-)

Too know people have rooted devices  (including me) , and  would like to use that power. But still, just one bad character and your device gets broken. Especially if you have e.g. Markor as default text editor, and select some conf file or like that and Markor gets automatically started. Thats no burden that I want to to live with.

What always possible is, is that you manage your core documents, big files and images on SD, and reference those from Markor.

Again - I strongly advise people to edit files with Markor or any other textedit App. Do that with terminal + nano/vi. If you still want Markor with root acces: I'm open for communty pull requests (e.g. from you if wanted). BUT - this has to be done on a different flavor - must not be incorporated to the main flavor for now.

**Comment by gsantner** [comment]
> There is an article here which describes it for Android >= 5.x

I have made a look at that. On many many articles. Have not get this working or even had the option as seen in this screenshot - on 2 devices with SD.

If you want an in-depth, read this huge document: <https://stackoverflow.com/questions/40068984/universal-way-to-write-to-external-sd-card-on-android/40201333#40201333> . It is impossible to proper overall support SD cards across all versions. At least without having like 1000 of special cases and designs. I'm developing Markor here, not wanting to have 80% sdcard code which barely works, and 20% textedit stuff :P.

**Comment by gsantner** [comment]
I'm tagging this issue as wontfix - as in:
* I won't work on this
* I disadvise contributors to start working on this or ask about it to be added
* BUT - as said above, if one writes it, sends a PR, I will happy review / accept

**Comment by FBachofner** [comment]
> I have unlocked the thread again - I did this to not get 10 comments back with "it still doesnt work", and write back multiple times - it cant because you dont have the update yet. :-)

Thanks @gsantner . . . I understand!

> If you want an in-depth, read this huge document:

Thank you for the link.  I'll take a look as this issue really interests me.

I assure you I understand that you do not want to waste time on special cases and incorporating code which barely works.

> Especially if you have e.g. Markor as default text editor, and select some conf file or like that and Markor gets automatically started. Thats no burden that I want to to live with.

While people certainly blame software (and publishers) for borking their systems, in my experience those who make the effort to get Root are not among those.

That said, I certainly understand your reticence!  ;-)

Gruss aus Kalifornien!

**Comment by FBachofner** [comment]
> has to be done on a different flavor - must not be incorporated to the main flavor for now.

Seems like a very sensible solution if someone has the ability to work on it.  I am sorry I don't -- perhaps It is time for me to learn some Android development.

If I had done this some time ago, perhaps I would have picked up Writely -- another MD editor which was really quite excellent (especially its file selection mechanism).  Unfortunately it was abandoned some time ago.

**Comment by gsantner** [comment]
>  If I had done this some time ago, perhaps I would have picked up Writely -- another MD editor which was really quite excellent (especially its file selection mechanism). Unfortunately it was abandoned some time ago.

Markor IS based on Writely ;). It started as a fork, but is now like 95% code and all by Markor project.

**Comment by FBachofner** [comment]
Hi @gsantner 

> Markor IS based on Writely ;). It started as a fork, but is now like 95% code and all by Markor project.

Well, that would explain (at least in part) the fact that your file selection mechanism is better than most!  :-)

BTW, Writely had great ability to save to the SDCard.  When I updated from Android 5.x to 7.x Writely was no longer able to do that :-(

You might take a peek at how Writely did it (SDCard writing) in past versions.  There may be a simple-to-edit, appropriate for most use-cases there!

**Comment by gsantner** [comment]
>  When I updated from Android 5.x to 7.x Writely was no longer able to do that

theres your answer :D

**Comment by FBachofner** [comment]
Hi @gsantner 

> theres your answer :D

Well, no.  :-(

Lots of other programs have the ability to write to the SDCard _across a great many versions of Android_.  This includes text/Markdown editors like [QuickEdit](https://play.google.com/store/apps/details?id=com.rhmsoft.edit) and [Epsilon Notes](https://play.google.com/store/apps/details?id=com.ekartoyev.enotes)

If you look at the comments on QuickEdit, the top comment gives a rating of 5 and states:

> 4 just for having the common decency of writing to sdcard. Another for having critical mass of required functionality in an uncluttered ui.

Markor excels at the second issue but (unfortunately) completely fails at the first.

I understand your reluctance to work on this issue, but you should become and remain aware it is of _significant_ importance to a large number of users.  I have seen many hundreds of reviews and people test/abandon text editing apps over just this issue daily.

I like Markor enough that I am going to see about [linking](url) to the SDCard from the "main" file system (I typically have root).  However, this is a pain in the rear that will keep me examining/testing other apps until such day Markor has the SDCard functionality built in.

**Comment by gsantner** [comment]
My phone is anyway damaged, need a new one. Probably wil go for XZ2 Compact (<https://www.sonymobile.com/at/products/phones/xperia-xz2-compact/>), which has SD slot. Maybe I will have some findings there.
