### ISSUE TITLE
Markdown table and image size rendering

### ISSUE THREAD

**Issue by seth100** [gsantner/markor#312]
#### General information

* **App version:**  1.0.0 (25)
* **System:** Android 7.1.2

#### Description

I have this Markdown **table**:

```
| Tables | Are | Cool | 
| ------------- |:-------------:| -----:| 
| col 3 is | right-aligned | $1600 | 
| col 2 is | centered | $12 | 
| zebra stripes | are neat | $1 | 
```

And I would like it to be rendered like a real table.
Is it possibile to support that?
It is currently rendered as the source, so not a graphical table.

Then, about **image size**, is it possible to set it with something like:

```
![](image.jpg x=200)
```

Or

```
![](image.jpg 200x300)
```

Thanks

**Comment by gsantner** [comment]
md tables are supported. use markdown table formatter to get right format.

img: use img src with width/height. the said one is not complaint to spec and also not implemented in parser.
