### ISSUE TITLE
version 1.0.0?

### ISSUE THREAD

**Issue by gilcot** [gsantner/markor#313]
Hi.

Is there any break? Why jump from 0.3.10 to 1.0.0 instead of 0.4.0?

**Comment by gsantner** [comment]
I'm feeling like Markor is solid enough, even more with recent hardening work. Could also jump to 0.3.11 or 0.3.10.1 or 0.4.0, thats a matter of naming. v1.0.0 usually means "this thing is ready for use" and out of beta/alpha, which Markor is since a long time.

**Comment by gilcot** [comment]
For me, not being v1 doesn't mean "beta", but I understand the point of view. Thanks a lot for the reply (a line about that should be added in the changelog...)
