### ISSUE TITLE
Back navigation when viewing a file within a folder returns to the overall screen rather than the folder

### ISSUE THREAD

**Issue by Ketrel** [gsantner/markor#32]
#### General information

* **Device:**  Oneplus 3T
* **Android Version:**  7.1.2
* **App version:**  v0.1.3

#### Steps to reproduce

1. Ensure the option 'Remember last folder location on startup' is **unchecked**
2. View file (either view or edit mode) within a folder
3. Press back button

Additional setting change from default: 'Preview first when opening notes' is **checked**

#### Expected result
**What is the expected output?** 
Return to the file listing within the folder the file was in

**What do you see instead?**
The contents of storage folder selected in options

**Additional Info/Comments**  
It appears that the option to 'Remember last folder on startup' being unchecked additionally causes Markor to not remember the last folder when exiting the view/edit mode.

**Comment by gsantner** [comment]
Register on <https://hacktoberfest.digitalocean.com/>, send a PR to fix this and get your t-shirt for free :).

**Comment by lex111** [comment]
@gsantner I'm not sure, but would like to try to fix it, will there be any recommendations?

**Comment by gsantner** [comment]
I added this comment to all issues, it's not specific meant to make you feel like you have to do it :).

There are multiple ways

* onActivityResult of MainActivity
* Save last path in MainActivity / don't change path when coming back

**Comment by lex111** [comment]
Yes, of course, but I want to try :).
