### ISSUE TITLE
single-document-revisioning support

### ISSUE THREAD

**Issue by linuxcaffe** [gsantner/markor#320]
#### General information
re v 0.3.10(24) running on android 6.0.1

#### Description
Feature request for improved revisioning support, initially mentioned in issue #302  

recap: After spending a few hours creating/ editing an important file (with my boss!) I hit a key combination that deleted all contents, irrecoverably. I'm hoping to see the implementation of some method(s) to mitigate this sort of (huge) problem. 

@gsantner suggested (in the closed issue #302) that supporting a single-document-revisioning scheme would be ok. .. and so I post this issue, hoping to cause a mild case of developer itch, even though I know didly about said s-d-r :)

As well, or alternatively, a session-based "revert-all-changes" button, might serve as a safety-net of last resort, and not to pile too many ideas into a single Issue, but perhaps a "save version" option could be used in conjunction with the existing Save button?

Again, thanks for the consideration and the awesome app.

**Comment by gsantner** [comment]
I have opened #252 which has small previous search on this.

I am now making undo/redo a opt-in feature by default. It is not easy to make this power feature understandable (in the way it is done) for everybody, or make it like everybody expects it. As said undo/redo queue is limited by device power and so its amount of steps available. I never had lost anything myself yet, and its probably better to make this not visible in UI if dangers of Undo/Redo are not considerable.

**Comment by gsantner** [comment]
Latest commit adds an option for undo/redo, and notes that it is only for advanced usage. It also notices what todo to be really sure that history doesnt go back to zero - close and reopen editor.
