### ISSUE TITLE
Maybe I could help with this small feature?

### ISSUE THREAD

**Issue by megamorphf** [gsantner/markor#321]
## Why am I writing this?

I tested you app @gsantner  today and I loved it. I would love to help.  I have little expierence in Android development, but I will learn it no problem.  First feature I would like to implement is the ability to add prefix to every todo item in `todo.txt`.  Secondly it would be nice for it to support GFM todo lists for example:

```markdown
- [ ] Task that is not done.
- [x] Task that was done.
```
Also I liked your idea for prioritization (A), (B) ... clean and simple.  So new todo syntax would look like:

```markdown
- [x] (A) This is a completed high priority task
- [ ] (B) This is an uncompleted high priority task
```

Furthermore I believe that `- [x] ` sequence is to verbose, so maybe the rendering engine could support `[x]` for marking todo items?

If anyone thinks they would find this feature useful express your thoughts and ideas below.

**Comment by gsantner** [comment]
Todo.txt is not a format I just made for Markor, it is a written down one with specificiation - and has multiple apps and pieces of software supporting it. I don't want to introduce something that makes it incompatible with other software. See <http://todotxt.org/> and <https://github.com/todotxt/todo.txt>.

![https://raw.githubusercontent.com/todotxt/todo.txt/master/description.png](https://raw.githubusercontent.com/todotxt/todo.txt/master/description.png)

We could make syntax highlighting for the said, but the "mark done" actions need to stay at todo.txt spec. Btw todo.txt also has support for key value pairs (`key:value` like `doonweekend:true`) :D.

**Comment by megamorphf** [comment]
> Todo.txt is not a format I just made for Markor

Cool I did not know that I will check out the format it looks cool. Thanks for info I agree this would make it incompatible.
