### ISSUE TITLE
what is network permission used for?

### ISSUE THREAD

**Issue by nutpantz** [gsantner/markor#322]
I was reading on Reddit privacy that a user was using your app offline and noticed 2mb of data being used. No one there wanted to sign up to got hub to ask..

**Comment by gsantner** [comment]
if you put a image url reference  in your written documents, and show the markdown document  the image will get downloaded.  thats exactly whats stated in description and nothing else. (image in browser preview)

do you have a reference yo reddit post, or can link to here?

**Comment by nutpantz** [comment]
https://www.reddit.com/r/privacy/comments/9cwf5o/markor_android_open_source_app_and_online_data/

**Comment by gsantner** [comment]
Ah! **No, Markor is not spyware.**


 It doesnt do anything with Internet/Network with any setting, stats or like that. As said, if you enter Images (either via HTML or in markdown syntax) it will get downloaded/displayed in the "Preview" mode which just displays converted Markdown -> HTML.
And well, if you add e.g. one photography picture URL which has 5MB than you have 5MB in download.
