### ISSUE TITLE
Configurable file-import directory, relative filepath button

### ISSUE THREAD

**Issue by timokau** [gsantner/markor#329]
#### Description

@Conceptron and @gsantner's work on camera picture landed in f-droid and it makes adding pictures so much easier :)

The one thing I miss is having the ability to configure the location of the pictures and insert relative links instead of absolute. I sync a folder with the markdown files with my PC and I'd love for the pictures to be put in that folder and referenced relatively.

**Comment by timokau** [comment]
By the way the changelog in the 1.0.2 f-droid version still only shows changes up to 1.0.1.

**Comment by gsantner** [comment]
changelog: I know, see Matrix post ;)

**Comment by timokau** [comment]
Not sure which matrix post you're talking about. I don't see matrix mentioned anywhere and the only room I can find in matrix's room directory is "gsanter projects" in which I can't see any posts.


I'm not sure if the title change reflects what I meant: I would like to configure where the pictures I take using Markors insert-picture dialog are saved. Is that the same as "Configurable file-import directory"?

**Comment by gsantner** [comment]
You have to click to join there. There most discussion happens about Markor and my other open source apps happens. This makes issues/problems like this for example easier to talk about.

**Comment by timokau** [comment]
I did click to join, but apparently posts from before I joined are not visible.

**Comment by gsantner** [comment]
Ah, yes thats a privacy feature the channel has turned on

**Comment by gsantner** [comment]
I see/use matrix more as a IRC frontend and I dont want public logging of channels.

**Comment by gsantner** [comment]
Closing this as I'm feeling like the whole file copy/move/import and referencing is already really insane complex and there are tons of settings already.
