### ISSUE TITLE
Save button makes the file not save

### ISSUE THREAD

**Issue by gibboni** [gsantner/markor#331]
#### General information

* **App version:** 1.1.0 Google Play Store
* **System:** Android 8.0.0 Sony XZ2 Compact

#### Description
Steps to reproduce the bug:
1. Press + to create a new note.
2. Enter title and some content
3. Wait for the save icon to be enabled (it is grayed out at start)
4. Press save icon
5. Press the back arrow from top
6. Note is NOT created

The note creation works if I **skip** steps 3 and 4 and only just press the back arrow. If I wait then the note is not created.

**Comment by ema-pe** [comment]
Same bug. I also notice that if I edit a note with new content, it won't be saved, even if I press the save icon.

**Comment by gsantner** [comment]
The whole dynamic filename logic (when adding new document, writing text on titlebar) is very big and at same time hard to work on. I will make soon what I wanted to make for quite some time:
* To make the "+"=new button popup a dialog to enter filename and the type (markdown/plaintext/todo.txt
* Directly renaming of filenames only, on accept press, no more file moving at "auto-save" time.

**Comment by davebrny** [comment]
just started using this app a few days ago and I didn't know what wad going on with that save button but pressing the preview button before you exit seems to save so I've been using that instead :)

**Comment by ema-pe** [comment]
@gsantner I suggest to release quickly a new version that removes temporarily the save button, because I think there are a lot of users that are trapped on this bug.

Also I can suggest to create a beta version to allow some voluntary users to test Markor, before the new version is relased on FDroid and Google Play. Bugs like this could be easily detected.

**Comment by rainbyte** [comment]
It seems auto-save is not working well neither:

1. I created a note like this

    ```
    some text
    ```

1. Then I added more content

    ```
    some text
    new content
    ```

1. Pressed `back` and opened note again, result was:

    ```
    some text
    ```

This happened various times, and the content was lost

**Comment by gsantner** [comment]
I'm activating history/undo/redo again. seems like the point were it was default-disabled it makes problem on some devices.
I myself tried it multiple/many times now but didn't loose any single character on 1.1.1
