### ISSUE TITLE
Website | Blog unreachable, unavailable

### ISSUE THREAD

**Issue by rancidfrog** [gsantner/markor#337]
Not really an app bug, but reporting since link is in [release section](https://github.com/gsantner/markor/releases/tag/v1.2.0) - https://gsantner.net/blog/android/2018/09/18/markor-release-v1.2.html

Unable to reach blog post nor website,
![](https://i.imgur.com/HqKkTC8.png)
Cached version also brings up error,
![](https://i.imgur.com/mwueXJk.png)

**Comment by gsantner** [comment]
Hi, tried it multiple times with multiple devices and different internet connections, all work fine.
Do you maybe have some firewall rules active?
Too let external tool access and speedtest the site, all fine. https://tools.pingdom.com/#597b932614000000
