### ISSUE TITLE
Markdown Table Editor

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#338]
#### General information

* **App version:** v1.2.0
* **System:** 7.1.1

#### Description
Currently I'm using an external [tool](https://www.tablesgenerator.com/markdown_tables) on both desktop and mobile to edit markdown tables (to be honest it gets unpracticable when there are more than 1 word + 3 cols).

The target is to add a TextAction, which allows to edit a table. When there is an existing table under cursor it needs to be analyzed and filled into the table editor.

The table editor is supposed to be some kind of Dialog, fragment or View, but no Actvivity. It has to work without leaving current activity(=editor). 

Features for the table editor itself have not to be big, its basically enough if you can add&remove columns&rows, and enter text (no highlighting needed!).

Steps:
1. Make code to get NxM array out of an existing table. Try it on Commonmark and GFM tables.
2. Make scrollable UI to show the table
3. Add buttons to add/remove cols/rows
4. Make cells editable
5. Implement insertion of edited result, replace existing table if one was preselected

**Notice:** This feature is free to take and will not be developed by the team.

**Comment by dugite-code** [comment]
As I am very interested in this but don't have the time/technical knowledge to contribute I've added a [$20 bounty over on bounty source](https://www.bountysource.com/issues/63545644-markdown-table-editing-popup)

**Comment by aubreyz** [comment]
Can I make a different suggestion here which will cover tables and a bunch of other things. And that would be to allow a simple form of snippet. 

a) If you have a special folder in the documents folder called snippets
b) Pressing a button will bring up a menu of the items in that folder
c) Selecting an item insets the whole file at the current cursor (or perhaps after a line break from current cursor if the file has a line feed to start)

This will allow almost anything.

**Comment by gsantner** [comment]
@aubreyz 
this is unrelated to this issue, please open new one

**Comment by gsantner** [comment]
Hey everybody, there are good news! ( @dugite-code  @aubreyz  )

I spent my free time today on Markor table editing!

In next update (Markor>=v2.1.7) there will be textaction button to make it easy to create tables.
tables also will have borders by default with next update to make them better recognizable.


![video_2019-10-27_14-16-37](https://user-images.githubusercontent.com/6735650/67635210-38ae5500-f8bc-11e9-8ca0-6e45919bf329.gif)

@dugite-code I don't have a bountysource accoun. If you want to support the project please do so at <https://gsantner.net/supportme> and can remove the bountysource :smile:  .
