### ISSUE TITLE
Main view: toolbar too big

### ISSUE THREAD

**Issue by def14nt** [gsantner/markor#339]
Here's a screenshot of it:
http://imgur.com/gallery/dpDO3Um

Here's my device info from CPU-Z:
http://imgur.com/gallery/7WCkZNJ

**Comment by gsantner** [comment]
whats the problem in screenshot?

**Comment by def14nt** [comment]
How is it invalid? If you can't see a clear bug with the header - its out of place - then you haven't looked hard enough.

**Comment by def14nt** [comment]
And that makes the app look horrible, to be honest. Fix that and it will look OK.

**Comment by def14nt** [comment]
And I'm using FastHub (android) so issue templates aren't supported, sorry.

**Comment by gsantner** [comment]
You still didnt tell me exactly what the problem is, whats your Android version and whats the App version you have. "It's horrible" or "Weird" is not any helpful.

**Comment by def14nt** [comment]
The header is incorrectly positioned on the screen of my Android. I am running Android 7.1.1.

**Comment by def14nt** [comment]
![yxt8sj7](https://user-images.githubusercontent.com/43454318/46164832-ef3da180-c286-11e8-933c-5241b8fa8105.png)

**Comment by def14nt** [comment]
I know I'm defo pro at paint lol

**Comment by gsantner** [comment]
paint is best

**Comment by def14nt** [comment]
lol, but srsly thats the issue above, idk anything about the android java apis so dont have a clue tbch

**Comment by def14nt** [comment]
@gsantner

**Comment by gsantner** [comment]
It was changed to "normal" in said commit above

**Comment by def14nt** [comment]
p.s this issue put me on Google (Google def14nt)
