### ISSUE TITLE
Providing visual feedback when save button is perssed

### ISSUE THREAD

**Issue by vapitea** [gsantner/markor#343]
#### Feature suggestion

* **App version:** 
* **System:** 

#### Description

I think it would be good if the application provided some visual feedback when the save button is pressed. I am not that trusting of software, it would calm my heart if i could see a little toast or some color change when i press save.
 Even if there is autosave i press save 3 times at least, i think there are lots of people like me in this.

**Comment by gsantner** [comment]
You didnt fill out the first 2 parts, and thats why I'm closing this.

Save button is now invisible again, exactly due the reason above. I don't want people to constantly press save, including myself.

Save button have made a problem so another reason for deactivation. Please understand that there is more behind 'Save' than just writing a file, actually quite much with auto-remove and that.
