### ISSUE TITLE
Feature Request: Option to markdownify entries in linkbox

### ISSUE THREAD

**Issue by durcheinandr** [gsantner/markor#347]
Sharing to linkbox only append a new line with

`<url>`

and it would be fine to have an option to extend it to something like

`* [<title>](<url>)`

**Comment by gsantner** [comment]
Hey @durcheinandr 
theres some news on this.

While you won't be able to automated markdownify stuff, links are now automatically shown at import in markdown manner. This requires that the browser supplies both URL + title. As this is not mandatory for browsers to provide (and many in fact do not) the data this will not work with all browsers, but should work with most commons ones.
Please don't ask to support `browser X`, if they provide data as they should they do, if don't then not - ask at theirs bug tracker if required. Markor can't fix other apps lacking intents.
