### ISSUE TITLE
todo list: first char on cursive-ish font/lang not connected

### ISSUE THREAD

**Issue by ali-hardan** [gsantner/markor#349]
The letters of some languages like arabic and persian, must be connected.

For example, I write "Yes" in Persian:

بله

When you press space between letters, it be:

ب ل ه

The problem is:
In markor todo list, the connection of the firt letter and second letter of line does not happen.

So, بله will be:
ب‌له

I will send screenshot.

**Comment by ali-hardan** [comment]
![screenshot_ -](https://user-images.githubusercontent.com/4679877/46246027-288d2300-c3e7-11e8-8624-a0e0ea610fbc.png)

**Comment by gsantner** [comment]
is it only the first/second? doed that happen on other edit texts too?

**Comment by ali-hardan** [comment]
Yes, it's only on first and second characters.
No, **I saw this problem only in markor todo list.**

This problem only happen after horizontal lines be visible. Before horizontal lines appears, the litters view are correct.

**Comment by gsantner** [comment]
When somebody starts on this - look at `FirstLineTopPaddedParagraphSpan.java`.

**Comment by gsantner** [comment]
Likely that this won't get fixed, hence closing.
