### ISSUE TITLE
Rework Highlighter

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#35]
Add highlighting to _most_ markdown elements

**Comment by gsantner** [comment]
Register on <https://hacktoberfest.digitalocean.com/>, send a PR to fix this and get your t-shirt for free :).

**Comment by cagdasgerede** [comment]
What do you mean by adding highlighting?

**Comment by gsantner** [comment]
To highlight markdown syntax. This is implemented already, but lacks a lot of elements right now.

![https://www.bram.us/wordpress/wp-content/uploads/2013/02/sublime-markdown1.png](https://www.bram.us/wordpress/wp-content/uploads/2013/02/sublime-markdown1.png)

**Comment by jamiet-dev** [comment]
What additional elements do you want highlighted?

**Comment by gsantner** [comment]
e.g.:
* task list (gfm
* normal lists seem to be broken (when starting with a hypen - only)

**Comment by jamiet-dev** [comment]
OK, I'll take this

**Comment by jamiet-dev** [comment]
I have the issues you mentioned on the original PR fixed
How should things like `***text**` and `**text***` be handled?
what about `***text***` ?

**Comment by gsantner** [comment]
thx!

Maybe check out <https://stackedit.io/editor> for this questions

**Comment by jamiet-dev** [comment]
I put up a new PR for this. The only thing that isn't working is italics with two start characters and one end character. ie: `**italics*` or `__italics_`

**Comment by gsantner** [comment]
for simplicity and speed we can live with 99% being supported

**Comment by jamiet-dev** [comment]
I broke bold with my previous PR. You merged it before I had a chance to fix it. My latest PR should fix it. Sorry about the sloppiness.

**Comment by gsantner** [comment]
np

**Comment by gsantner** [comment]
I think we are quite at the maximum what is possible with regexes. thanks for working. 

closing.
