### ISSUE TITLE
Write document:  Markor introduction/showcase

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#357]
#### General information

* **App version:**  v1..2.2
* **System:** Android 7.0.1

#### Description
Currently Markor doesn't ship any files with it. It would be cool to have one document which showcases whats possible with the supported formats, and at same time it would be great if it can describe some features of markor. This will be used both 
* for giving the users who just installed the app some edges what this is and what it can do
* for screenshots in stores

Needed are currently 3 documents:
* 1 for todo.txt (todos)
* 1 for Markdown (notes)
* 1 for Plaintext (don't know, maybe something with linkbox? :) )

If somebody starts on this - you don't have todo all 3 at the same time, starting with one is okay.

**Comment by HarryHeights** [comment]
Is this like a changelog?

**Comment by gsantner** [comment]
@HarryHeights No. Changelog is available at CHANGELOG.md and is existing. This is about making a nice document showing syntax of formats (like header, lists in markdown etc) and maybe describing little about the app in it.

**Comment by HarryHeights** [comment]
Hmmm. I more of a writing and document guy than a programmer or developer. I think this involves writing, if you could help bring down what you need to my understanding I'm sure I can help out.

**Comment by def14nt** [comment]
@gsantner  I'd he happy to do that. I'll come up with something by Monday.

**Comment by def14nt** [comment]
@gsantner I think we are better off copying the README from the project, or a shortened version, to avoid repeating ourselves pointlessly. I'll trim a bit of the text off the README and share a StackEdit link with you, if that's OK.

Thanks. :+1:

**Comment by def0x099** [comment]
@gsantner Sorry about the massive delay. I'm currently looking through the README and tidying it up, so I'm in the right mood for :writing_hand: :smile:

**Comment by gsantner** [comment]
:D.

You can use this as a startpoint for syntax example, that's what I use as readme template


[readme.md.txt](https://github.com/gsantner/markor/files/3000864/readme.md.txt)

**Comment by def0x099** [comment]
@gsantner On that topic, there's a PR flying at you right now from me.
