### ISSUE TITLE
Italic TextAction apperance

### ISSUE THREAD

**Issue by puntomaupunto** [gsantner/markor#361]
#### General information

* **App version:** 1.2.2
* **System:** Gemini (Android 7)

#### Description
"Italic" TextAction inserts a couple of double _ instead of single ones: the text is therefore shown in bold, not italics.

**Comment by gsantner** [comment]
I tried it multiple times now, but I cannot verify this. Always getting correctly the left and right underscore.

Could you please make a screenrecord and paste the link here?

**Comment by puntomaupunto** [comment]
I tried to reproduce the behaviour, but I did not manage. By the way, I needed to click twice on the TextAction to have a double _, so I don't think that I obtained it by chance. Anyway, I close the issue.

**Comment by gsantner** [comment]
ok, good to hear !
