### ISSUE TITLE
Simplify original (english) wording

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#362]
#### General information

* **App version:**  v1..2.2
* **System:** Android 7.0.1

#### Description
Look through existing original english strings/"translations" and try to improve wording. In general the target is always to be as short as possible, while the meaning stays the same / no information gets lost. You can use for example [hemingway editor](https://hemingwayapp.com/) to identify what is too complicated or can be otherwise improved.

Files:
* res/values/strings.xml and -not-translatable.xml
* res/raw/
* README.md
* metadata/en/full_description.txt (used for F-Droid and Play Store)

**Comment by nightrainlily** [comment]
I can take this!

**Comment by gsantner** [comment]
@nightrainlily Thanks! Let me know when you need some information or context! You can also checkout the [translation project on Crowdin](https://crowdin.com/profile/gsantner) where the app is translated by others (which should also give some impression).

**Comment by nightrainlily** [comment]
I can get started now. as much instruction and context as possible would be great!

**Comment by gsantner** [comment]
Okay! So here are my suggestions, where you don't need any setup or like that, just a browser and a notepad :smile:  :

* main strings - <https://github.com/gsantner/markor/blob/master/app/src/main/res/values/strings.xml#L11>
  * All - check spelling. Everybody can make typos. 
 * Longer strings: Look if it can be shortened/improved
* Wordings in App Store, Readme and homepage
  * As you will see, they are all mostly the same, only slight differences or things striked out. The probably most updated and biggest one is homepage, so I would suggest to go just for that.
  * Instead of just button texts and short descriptions, this is lengthy text with descriptions.
  * Here having a good read is very important
  * Homepage - https://gsantner.net/project/markor.html
  * Readme - https://github.com/gsantner/markor/blob/master/README.md#markor
  * F-Droid - https://github.com/gsantner-extra/markor-metadata-latest/blob/master/en-US/full_description.txt

I don't know how well you know github and pull requests, for strings you can send one if you want. For homepage I recommend to work with etherpad, as it allows easy collaborative editing together. You can freely edit and add comments here: <https://yourpart.eu/p/markor_project_page_rework> . It has the latest copy of the project page.

**Comment by nightrainlily** [comment]
I made some changes to the README file, but are the F-Droid and the Homepage contained in the repo? I forked it and I can't find them anywhere.

**Comment by gsantner** [comment]
F-Droid is the metadata file. homepage is copied at https://yourpart.eu/p/markor_project_page_rework , ready for edit

**Comment by nightrainlily** [comment]
Let me know if you still want me to update those other files, given that I did the readme. I'm not sure why, but I can't seem to pull down a version of the repo that includes metadata files, possibly because they are sourced on another branch?

**Comment by gsantner** [comment]
Thanks! I will look into the changes and likely will merge most of them.

Yeah they are a git submodule, in a different repository in gsantner-extra

**Comment by gsantner** [comment]
@nightrainlily thanks for helping! have included your changes now! :+1: :tada:

**Comment by gsantner** [comment]
@nightrainlily If you want to work on another project, I would appreciate help in my other project, MemeTastic. ( https://github.com/gsantner/memetastic ). All filepaths etc are very same, including README.
