### ISSUE TITLE
Add support for Chrome Custom Tabs

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#363]
#### General information

* **App version:**  v1.2.2
* **System:** Android 7.0.1

#### Description
Currently Markor always does open an external browser when clicking on something that is not a filepath (in browser) or using the "open link" textaction.
It would be nice to use the "Chrome Custom Tabs" feature to show links, which allows to much faster view contents. Reference to docs (many guides and blogs posts available which shows howto too): <https://developer.android.com/reference/android/support/customtabs/package-summary> /  <https://developers.chrome.com/multidevice/android/customtabs>

This is also already done in another project of mine, [dandelion*](https://github.com/gsantner/dandelion) where you can too find some hints. Important is that this does not only work with Chrome, but also Firefox/Fennec (which implements the interface too). Be sure to specify their package id's and that should work.

![https://developers.chrome.com/multidevice/images/customtab/performance.gif](https://developers.chrome.com/multidevice/images/customtab/performance.gif)

**Comment by lifeLessCoder** [comment]
Hey can I work on this? @gsantner

**Comment by gsantner** [comment]
Of course, no need to ask!  :-)
