### ISSUE TITLE
TextAction: color picker

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#364]
#### General information

* **App version:** v1.2.2
* **System:** Android v7.1.2

#### Description
Add a way to add a color to the text using an color picker. The first step is to have some textaction available which pops up an dialog for color selection.
I don't like to have a big bunch of libs and depencies included, please search for something that does the job without any huge extras  ( like 10 ways to integrate into fragment/activity/preference)..we really just need something simple :smile: .

**Comment by jakubAerik** [comment]
I'll work on it.

**Comment by gsantner** [comment]
@jakubAerik  Tell me when a question arises

**Comment by jakubAerik** [comment]
Please may i ask you, where can i find the id of the text which i write for example in QuickNote activity? What's the name of this id or name of the xml file where the current id is? Thank you for your help :) .

**Comment by gsantner** [comment]
It's bound to _hlEditor in DocumentEditActivity.

For inserting text you usually do   _hlEditor.getText().insert()

**Comment by jakubAerik** [comment]
Please, which method or action cause when i choose bold action(when i click on icon which represent bold text) for example in QuickNote activity on some text and then i click on preview button, text is bold?
I was thinking that's that regexes in SimpleMarkdownParser, but I was wrong.
Thanks.

**Comment by gsantner** [comment]
As I expect it to be it available in multiple formats (plaintext,markdown) I would place the code in CommonTextActions. Just see how other stuff is added (Example: open browser link) and add our new color picker R.drawable and string.

Then also reference the same in the real format specific TextAction (so a button in bottom bar gets generated). The runCommonAction method will execute then.

Refs:

https://github.com/gsantner/markor/blob/master/app/src/main/java/net/gsantner/markor/format/plaintext/PlaintextModuleActions.java#L46


https://github.com/gsantner/markor/blob/master/app/src/main/java/net/gsantner/markor/format/plaintext/CommonTextModuleActions.java#L22

**Comment by jakubAerik** [comment]
Hi :) 
I have almost done your issue, but one problem left...if i select some text for example in plain text and i want to set some color using the color picker, the selected text change the color but only for one milisecond and then, text has again same color as at the beggining :/ i dont know if some method or what has invoke after when i choose color for text from color picker and set deffault color for text in current mode(dark/white)...can you help me with this?

**Comment by gsantner** [comment]
ooh, I think you are doing way more than it was planned! :D It would be enough if you just insert the color into text: ala `#af0622`. 

Did you try to make changes on highlighter? You don't have to! Highlighter will clear the TextSpans automatically again, and the text itself in editor should not be colored. Its more really about choosing and inserting!
Though inserting text as `<span color="#code">text</a>` is also nice.

**Comment by jakubAerik** [comment]
Oh :D okay than...actually, when i choose some color from color picker i set color for all text so i don't know if you want that or no :) if yes, it's done :P

**Comment by gsantner** [comment]
Please open a PR, makes review/responding easier! :D

When you make ColorSpans they are always just applied temporary till the next syntax highlight (which happens when you type a new char).
 So creating/applying them is not needed, it will anyway just be available for small amount of time, and never restored at opening a new file ;).

**Comment by gsantner** [comment]
This is done
