### ISSUE TITLE
TextAction: Show pictures in a picture view

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#365]
#### General information

* **App version:** v1.1.2
* **System:** Android v7.1.1

#### Description
Currently when the user has placed the cursor inside a link he can click the "open in browser" action to open it externally. I would like to have something similar to fastly show the picture under the cursor.

Todo:
* Add new dummy textaction, run it from textactionbar on bottom
* Reuse logic from "open in browser" in CommonTextactions to extract image path
* Show picture in a fullscreen dialog on pressing the textaction in bottom bar

Ideas for afterwards, but can also be done together with above:
* Extract all image paths inside the current document and show swipeable gallery of all pictures in the current document
* Start the swiping list with the nearest image from cursor position

**Comment by noob893796** [comment]
Can I start to work on this issue?

**Comment by gsantner** [comment]
Sure! Let me know when questions come up

**Comment by noob893796** [comment]
So if i am not mistaken, the main purpose of this function is to quickly show an image for user. That means that you want to click on URL and itll open internally in app. By clicking back user would get back to previous activity. 

Give me further details if im mistaken.

Thank you! Have a nice day. 👍

**Comment by gsantner** [comment]
Mostly right, with exception of activity. I want some kind of fullscreen dialog or alike, the documentactivity should not be left.

**Comment by fxshpac** [comment]
Just saw this post and also interested in this feature but a better feature for me to have a viewing mode where all the media referenced by the note can be browsed just like a gallery. From there you can open the individual media. Just a thought to throw out here :)

**Comment by fxshpac** [comment]
@noob893796 sorry i didn't mean to interrupt you, so please go ahead

**Comment by gsantner** [comment]
I'm currently busy so not looking too much into this the next 2-3 days. 
Thats spirit of community projects, to work together to make something great and thats what I see here. Keep going guys ;).

Fir any of you - take a look at #395 for some more information and target of this so nobody ends up with the same again.
Be it just "images" being available to browse visually, or also other files -> "view attachments" like, is also nice idea. **But again, keep in mind this is about Editor and parsing its contents, not about making javascript/css in a webview!**
