### ISSUE TITLE
TextAction: Add voice to note (audio recording)

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#367]
#### Description
Often spoken is the easiest way to take notes. It would be great to just be able to press a microphone button and a start/stop audio recording thing popup. 

Target of this:
* Create new audio recording button
* Popup dialog which has options for start/stop and cancel
* Save recorded audio in same folder as current document
* Add filename to current cursor position in text

### Suggestion
What I liked greatly so far is [this project](https://android-arsenal.com/details/1/6797), which basically resolves most important points. Sadly it doesn't allow set save paths. But as 99% of the important things is done [in a single file](https://github.com/IvanSotelo/RecordDialog/blob/master/recorddialog/src/main/java/com/deskode/recorddialog/RecordDialog.java) I think the best option is to copy/fork the file and adapt it to Markor needs. We don't need stuff like Hangouts ringetone when pressing start or fancy start animation for example:-).

![https://raw.githubusercontent.com/IvanSotelo/RecordDialog/master/20180521_093731.gif](https://raw.githubusercontent.com/IvanSotelo/RecordDialog/master/20180521_093731.gif)

**Comment by stupidly-logical** [comment]
That library is very outdated.

**Comment by stupidly-logical** [comment]
Can I use some other library if it satisfies your specifications?

**Comment by gsantner** [comment]
Yes, but I had some research and all seem to have a fixed savepath sadly :/

**Comment by poutrosgit** [comment]
Could it be possible to select what format to save in? Given that it's a voice note, a lossless (like wav as shown, or flac since it's open) or a lossy format that is good for voice (like opus) would be good to work with. Maybe flac would better by default because of needing less space storage than wav. Support is almost universal and voice notes aren't expect to be played anywhere else other than the phone of origin so saving in flac shouldn't be an issue for interoperability.

**Comment by gsantner** [comment]
when the lib/methods support it yes. But for sure we won't have something like ffmpeg here :-).

**Comment by ivenk** [comment]
I would like to give this a try. I have already started on but it might take a couple of days until i can submit a pr.

**Comment by gsantner** [comment]
Nice! :D

**Comment by ivenk** [comment]
Okay back on it! Hat some professional stuff to sort out

**Comment by gsantner** [comment]
Closing as implemented :tada:
