### ISSUE TITLE
Don't change file extension when saving

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#37]
Currently file gets moved to *title.md* when it was called title.markdown. Resolving this will keep the original extension.

**Comment by gsantner** [comment]
If you need more information ask.

Register on <https://hacktoberfest.digitalocean.com/>, send a PR to fix this and get your t-shirt for free :).

**Comment by manmeet-22** [comment]
@gsantner GitHub identifies both .markdown and .md. So does it matter much?
GitHub supports markdown, mdown, mkdn, mkd, md .
Rest if I am taking your statement wrong can you elaborate the issue statement?

**Comment by gsantner** [comment]
The NoteActivity currently always does save files with the .md extension. Resolving this will keep the original extension (but may change the filename itself).

**Comment by manmeet-22** [comment]
As far as I have used your app, I think it works fine. When I touch the share button on preview-
- Plain Text, Html and Html source in .txt
- File sends the xyz.md file
- Rest pdf, image in their own format.

I didn't find any option to save files.

**Comment by gsantner** [comment]
create a file in normal filemanager: test.txt or test.markdown, put some text into it (other app) and see what happens ;)

**Comment by manmeet-22** [comment]
Working on it.
