### ISSUE TITLE
Lifehack: Insert dynamic Timestamp / calendar date

### ISSUE THREAD

**Issue by tengucrow** [gsantner/markor#374]
I prefer using timestamps in my notes, but Markor (as any Android editor) doesn't have support adding timestamps to text notes "from box", so I've wrote simple javascript code and save it as markdown file. 

When open file in "view mode" - it runs script and prints current date/time so you can copy and paste them into other note. Also you can vary form of timestamps and keep it in different files. I prefer one timestamp for one .md-file so I cat simple "select all" and then copy it. 

**Important**: save file as markdown (.md) and add wihtespace lines before and after **script** tags.

    <script>
    
    function pad(number) {
    // padding number less than 10 
    // to get ISO-like format 
      if (number < 10) {
        return '0' + number;
      }
      return number;
    }
    
    // get current date 
    var d = new Date();
    
    // print datetime stamp 
    document.write(
        pad(d.getFullYear()) + "-" +
        pad(d.getMonth()) + "-" +
        pad(d.getDay()) + " " +
        pad(d.getHours())+ ":"  + 
        pad(d.getMinutes() + ":"  +
        pad(d.getSeconds())  
    ) 
    // https://www.w3schools.com/jsref/jsref_obj_date.asp
    
    </script>

**Comment by gsantner** [comment]
Hi!
This ("textaction for insert time") is already reported and planned in #260 :-)

**Comment by gsantner** [comment]
I'm letting this on top till hacktober ends (so this is on top, much needed feature :)).

When somebody comes here click here: #260

**Comment by gsantner** [comment]
Done at #454 , will be available in next update (> 1.5.0).

Example: 

![https://user-images.githubusercontent.com/22313019/49843145-73032680-fdbe-11e8-8055-16d0befbfc19.gif](https://user-images.githubusercontent.com/22313019/49843145-73032680-fdbe-11e8-8055-16d0befbfc19.gif)
