### ISSUE TITLE
TextAction: Date & Time insertion

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#375]
#### General information

* **App version:** 1.1.2
* **System:** android 7.1.1

#### Description
The target is to have an TextAction (a button in the bottom bar) which opens a new **dialog** with features below:
* Selection of a date/timeformat, with some default options like `hh:mm`, also there should be an EditText so the user can do an own custom format. (resulting from #260)
* Show below all formats what would be result at the current time object
* Have an button to show an date/timepicker which allows you to select a different time than the current time object. So you could select 05:00 in the timepicker, and then press `hh:mm:ss` as format and you get `00:05:00` inserted into text.
* Add on very bottom a checkbox which changes insertion to text. When checked insert the format string. When not (default) then insert the formatted time (what you get from `SimpleDateFormat.format(dateObject..)`. (resulting from #374)

**Comment by IzzySoft** [comment]
:+1: low prio (as in 90%+ I expect people want to have "now"): consider a date/time picker that also lets you input date/time manually (text-input instead of "month view"). I just had to initialize a new device with LOS, and on selecting current date/time had that stupid picker where you could only skip month-wise – initalized with a day from the year 1971. Happy skipping :scream: 

As said, very low prio – and only if it doesn't cause too much trouble. After all, in the rare cases that would be needed, one could do so manually in the text itself :wink:

**Comment by gsantner** [comment]
@IzzySoft  already on the list :D. (point 3)

**Comment by tengucrow** [comment]
My solution was just palliative for my own notes :) When taking notes on phone I just put them to QuickNotes and separate them by datatimestamps.

It would be nice get date/time picker button or two in toolbar (one button - "get now date/time", and second - "get date/time from calendar", and for both buttons date/time "format" field in settings section (something like for strftime library i.e. "@ %Y-%m-%d %H:%M"). So avrage user can use default values or customize his own format.

**Comment by gsantner** [comment]
Target is to have one option, don't two or more. The reason is that the bar is already quite full, and nobody wants to scroll forever to get the right thing :).

Yeah, the thing with "just paste NOW to text" is what I meant with "have some defaults like mm:ss" :). Should be just one tap to open our datetime dialog and then press the "Now (Time)" button there

**Comment by petraspeter** [comment]
Hi, I would like to pick this one up, if nobody else is working on it.

**Comment by gsantner** [comment]
Seems like nobody started working on it, happy about help ;-)

**Comment by gsantner** [comment]
Done at #454 , will be available in next update (> 1.5.0).

Example: 

![https://user-images.githubusercontent.com/22313019/49843145-73032680-fdbe-11e8-8055-16d0befbfc19.gif](https://user-images.githubusercontent.com/22313019/49843145-73032680-fdbe-11e8-8055-16d0befbfc19.gif)

**Comment by IzzySoft** [comment]
Thanks, though not exactly what I had in mind. According to your demo GIF, I'd be faster tapping in the date/time manually :wink: Unless (which I couldn't yet test for obvious reasons, so you might already have implemented this) it remembers the last-used format, or a default is somehow configurable?

**Comment by gsantner** [comment]
Improvements are always doable^^

Guess for hh:mm thats right, but for something more it gets bad to type in manually :D (like saturday 15. october, 20:10:10 UTC+1)

**Comment by IzzySoft** [comment]
Agreed. But whether I type "2018-12-13 16:15" or "YYYY-MM-DD HH:MI" and then have to remember whether those "codes" are correct… I'm certain the former is faster. And in most cases sufficient. If it, however, remembers the last used format (or has a way to configure a default format), the next time(s) it's just about 2 or 3 taps.

**Comment by gsantner** [comment]
@IzzySoft 
![screenshot_20181213-180210](https://user-images.githubusercontent.com/6735650/49954699-57546900-ff01-11e8-8c67-08f8c65c5b36.png)
![screenshot_20181213-180221](https://user-images.githubusercontent.com/6735650/49954700-57546900-ff01-11e8-9d9b-da727b1c38a8.png)
