### ISSUE TITLE
Fix execption: createCalendarAppointment ActivityNotFoundException

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#377]
report from gplay below

![grafik](https://user-images.githubusercontent.com/6735650/46469309-4f769b00-c7d3-11e8-8f43-987be1f45fa6.png)

**Comment by manjutapali** [comment]
I feel the activity isn't added in the manifest file.

**Comment by gsantner** [comment]
From our side, yeah all activities are added, of course. This looks like a rare case where the user has no Calendar app installed on the device.

**Comment by gsantner** [comment]
No, I don't know more than you see above in the error log, I dont have a bug report.

**Comment by MikeMikerson** [comment]
I reproduced the issue by disabling the only calendar app I had installed on the device and then clicking Share -> Calendar. Submitted a pull request - #379
