### ISSUE TITLE
Fix exception: WrFilesystemListFragment IndexOutOfBounds

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#378]
report from gplay below

![grafik](https://user-images.githubusercontent.com/6735650/46469368-73d27780-c7d3-11e8-9a93-a34a1e218869.png)

**Comment by notepad104** [comment]
What is the behaviour required in case of `_selectedItems` does not have any item for rename or menuInfo item in `onActionItemClicked`

**Comment by gsantner** [comment]
do nothing. Rename should not even be visible for zero items

**Comment by gsantner** [comment]
Hi!

No, copy paste errror log from gplay.
