### ISSUE TITLE
Set title to first line content when title is empty

### ISSUE THREAD

**Issue by ali-hardan** [gsantner/markor#388]
Set title to first line content when title is empty, like most note-taking apps.

**Comment by gsantner** [comment]
thats the behaviour, yes.

**Comment by ali-hardan** [comment]
I did not understand what you mean from

> thats the behaviour, yes.

My English is bad. 

Currently, when I save document without title, the title will be "null" string.

**Comment by gsantner** [comment]
Please do a bug report with filled out points that are shown in the Issue template, not wipe them they are there for a reason. Also just "it doesn't work" like reports cannot be resolved without details what the problem is. Thanks!
