### ISSUE TITLE
Title bar not sets to first line of content

### ISSUE THREAD

**Issue by ali-hardan** [gsantner/markor#389]
#### General information

* **App version:** 1.3.0 
* **System:** Android 7.0, Galaxy J5 Prime 

#### Description

I see this bug after this works:

- Open Markor.
- Click on + icon to make new document.
- Write "Hello" in content, and keep "title" empty.
- Don't press physical back button of phone. Only click on back icon in the Markor top-bar.
- I see my document has saved as "null.md" and there are not exists "Hello.md"

But, When I press on physical back button of phone instead back icon in Markor top-bar, It makes "Hello.md", and also makes "null.md". I mean: It makes two files contains "Hello".

**Comment by gsantner** [comment]
I had a fix for this in place, but then decided to disable that button. It serves anyway as duplicate to the normal 'back button' in Markor, which space is better to be used for something else. Now you see like 5 chars more of title text.

![screenshot-2018-10-15__22-57-52](https://user-images.githubusercontent.com/6735650/46978040-16d99a00-d0ce-11e8-8340-fbf5c4b2eaf0.png)

**Comment by ali-hardan** [comment]
Please don't forget "null.md" creation bug.
