### ISSUE TITLE
FS: Directory 'go up' sometimes doesn't detect being in subfolder

### ISSUE THREAD

**Issue by sas-3** [gsantner/markor#397]
#### General information

* **App version: 1.3** 
* **System: oreo** 

#### Description
I have notes organized within folders. Sometimes the back button doesn't take you back to the rootdirectory (as set in settings) and just offers to exit the app instead.

**Comment by sas-3** [comment]
Cant tell you a pattern now but I'll observe it. It happens from time to time, certainly once a day, because I use markor quite a lot :-)


On October 19, 2018 1:25:35 PM UTC, Gregor Santner <notifications@github.com> wrote:
>I tried, but cannot confirm this issue yet, works always correctly
>here. Do you have some way to reproduce it?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gsantner/markor/issues/397#issuecomment-431362178

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ali-hardan** [comment]
Thanks, But it is not fixed. test my pattern.
