### ISSUE TITLE
feature request: support for multiple window

### ISSUE THREAD

**Issue by Gettyk** [gsantner/markor#398]
#### General information

* **1.3.0:** 
* **System: Android  4.4.4** 

#### Description
I can't use markor with the [multiple windows](https://www.google.fr/search?q=android+multiple+windows&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjY2LyYl5XeAhVFKBoKHUpdDMwQ_AUIDigB&biw=1280&bih=588#imgrc=6IIpv5XyLml7pM:) option.  That would be great to have this as a new feature!

**Comment by gsantner** [comment]
This is an Android OS feature, not an app feature. Markor works well with split.

![creenshot_20181020-163552](https://user-images.githubusercontent.com/6735650/47256848-6cbf9080-d486-11e8-8c05-5a5ef7771f79.png)

**Comment by Gettyk** [comment]
Sorry for bothering you but I can't create a double screen with markor on my android phone. I am used to use double screen with a lot of apps (chrome, quickedit, epub reader....) but when I try with Markor, it doesn't work.

**Comment by gsantner** [comment]
split screen was officially added to Android 7. Don't know what special you have here and can't resolve issues related to this. I don't have any such, but the splitscreen works well on Android7+ where it is officially available as feature. Maybe some else can, and I'm open for accepting pull requests.
