### ISSUE TITLE
Merge PreviewActivity+NoteActivity / make use of fragments

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#40]

**Comment by gsantner** [comment]
If you need more information ask.

Register on <https://hacktoberfest.digitalocean.com/>, send a PR to fix this and get your t-shirt for free :).

**Comment by AkshayCHD** [comment]
hello sir, I would like to work on this issue, wanted to ask if I have to add fragments instead of multiple activities, then should i create a tabbed view for them.

**Comment by gsantner** [comment]
no, tabs are not needed as theres always the document-browser, which will open a document then

**Comment by gsantner** [comment]
@AkshayCHD I changed the title so it's more specific 👍

**Comment by AkshayCHD** [comment]
okk sir thank u

**Comment by gsantner** [comment]
Have fun hacking! :)

**Comment by gsantner** [comment]
@AkshayCHD Did you start on it?

**Comment by SpotlightKid** [comment]
As requested in #99 here a comment about an issue that might be solved by this:

> [Currently] When the preview is closed with the back arrow the app returns to the list of documents, not to the previously opened document.
