### ISSUE TITLE
A lot of features request!!

### ISSUE THREAD

**Issue by vfxturjo** [gsantner/markor#405]
Hi, the developer of markor.
This is my first post (issue) in GitHub. I opened a GitHub account just to request some features!!!
Your app is really a great app.
One of the best.

_Please consider adding some of the features mentioned below..._

- 1 - search option will also search inside notes. Not only the name of the notes.

- 2 - some more markdown features/options... (At least for Todo list)

- 3 - ability to add sub tasks using marking options in tasks.

- 4 - ability to add description inside a task.

_Some more if you can..._

- 5 - browsing folders through sidebar (exploring folders in sidebar like a tree view)
This can be included in "themes" option so user can choose what style he want.

- 6 - file browser in markor app will show "custom summary"/"1st few lines"/any other useful thing instead of "last opening date"... Aaaannnnddd "only file name" mode too.. if anyone wants that..

- 7 - markor quick note as a popup. User can surf internet and take notes!!!!

- 8 - native tasks support... What i mean by that....---> sidebar will have specified place/section for tasks.
You can add folders to better organize your tasks. 

- 9 - In Each folder, you add tasks (with subtasks and notes) just like a native todo list app. (Like ticktick or todoist with description) It will feel like that. And the data of those folders will be saved in a certain txt file.
I think i cant fully express myself. :( Sorry for my bad English. he folders in sidebar Todo section are actually a txt file. Just like other notes. 

- 10 - I don't want to make individual txt file for individual tasks. It will be messy. But we keep same kind of things (related things) in a folder, right? Thats why i want a todo list folder to be one txt file. Example-
"To do after xm" folder will contain many tasks/todos. They will be stored in "To do after xm.txt" but will be shown as a task list with "task complete" checkbox, priority based color/highlighting system, A-Z/custom orientation of tasks, tapping a tasks will open description/subtasks etc etc.

- 11 - Just check out any todo list app and you will clearly understand what i am trying to tell you (specially ticktick, please)  So it will be like "one app for all your tasks and notes" 😎 including both interface- note taking and todo list style in one place, in this lightweight apk!!!!
People will be crazy for this app 😬

- 12 - sd card support...

- 13 - it is nice to see all notes made with markor is actually txt files and real folders. It would be great if it could sync to Google drive in exactly same manner (same file structure under a certain root folder set by user)

Ummm i have these features requests.. Can't think of something more now.
I love your app!!! This app has great potentials
I think you will consider my requests.
I know coding will take time. I will be waiting for these features in future update.
Best wishes for you all.

**Comment by gsantner** [comment]
HI @vfxturjo , thanks for giving feedback!

I added a number at beginning of each topic, so it's easier to respond. In general it's better to have an own Issue for each seperate thing, but in this case I think it's more like Q&A where some new issues will result from. In general you can find existing topics via search, I will check all those that are already reported at some point (where discussion should happen there).

* [x] 1) Issue #301 
* [x] 2) Issue #357 , #358 
* [x] 3,4) Markor uses a open standard / markup format called [todo.txt](http://todotxt.org/), which is about one task a line. I don't want and can't change that or use a different way. There are multiple applications out there on desktop and mobile which are all compatible with Markor. Making one task for example multiline would make it incompatible with everything else, hence no this won't happen. You can still use normal markdown notes as a todo and define your own structure, however you like that! Thats the great benefit with markor being very flexible. 
* [ ] 5) Unsure about that one, more ways to navigate the app always means people understand it harder. Having bottom-swipe-navigation AND navdrawer-sidebar is honestly a combination that's not a very good idea. You can create a new issue about this, but likely it won't be done in a navdrawer way. (new issue)
* [ ] 6) There is always room for improvement here. Just collect some things expected. (new issue)
* [x] 7) You can do splitmode that is available from Android 7. Then you have markor on bottom or top and browser at opposite. That's how I sometimes use it. There are too some permission issues and big differences between Android versions. So popup itself likely not will get there, but split mode works well.
* [x] 8) You will always just edit plaintext with markor, and no other GUI frontend like text-lists. For browsing/adding new projects/places/tags you can use the specific buttons in todo. For browsing for existing tasks with e.g. `@home` just long press the `@` button and select `home`.
* [x] 9,10) You can create as many todo files as you want! Just create a new file starting or ending with `todo`. So if you want to seperate by work and home just create `work.todo.txt` and `home.todo.txt` ;). But having one list combined out of multiple textfiles is not planned. 
* [x] 11) Being lightweight but powerful is the projects target, what was always the goal and will stay. But also keep in mind, all new cool and fancy stuff adds up and than you are on the road to casual require,ents, and then to high requirements. That's what I don't want here, want to stay with existing open plaintext formats. The ones you can also copy to PC and edit with `notepad.exe` if you like that. I don't care about  the project being the best ever, it should do the job well for what it's there and what I get from feedback everyday this is the case and also can state that myself as using it everyday.

Thanks for feedback ;).

**Comment by vfxturjo** [comment]
Wow! Thanks for reply!!!!!

Thanks for numbering :)
1, 2.. ok
3. Okay then
4. Yeah but i was saying that the default navigation style/system will be yours, But a user can change the interface style (like if he want, he can change usual folder view/folders nested inside sidebar)
[screenshot_20181025-155052](https://user-images.githubusercontent.com/44445014/47492076-04015b00-d86e-11e8-8ae0-8687122896b8.png)
I mean user will be able to decide how they want to navigate. They can change it LATER AFTER INSTALLING APP, IN SETTINGS. So they wont get into understanding problem.
I dont know if you will like it... I dont want to force you :)

6. Yeah you can do this i think.

7. I dont have android 7 :( i cant effort right now.
Check out *material note" app. It has this feature. I am telling you to steal it. But you can do it i think. Sometimes bubble popup is more useful than split mode... Sometimes....

8. Text will be same, just like todo.txt, but when presenting, it can show like a gui with checkbox. And you can change it to "gui mode" or "classic plain text mode". Thats what i am saying. So people can edit those in windows notepad too.  Because the content (text) is same, with same todo.txt format text, just having a sign that will be used for that gui to determine of the task is done or not. Like #done at the end of a task which will be used for showing the tick in checkbox. If there is no #done tag, checkbox will be empty. Everything else is same. So people can edit them in notepad.exe... and see both "todo.txt" formatting OR interface with checkbox, whichever they prefer :)

9,10. okay then... Will talk about it later if i have any other questions about it..

11. Yeah you are right. The more features you implement, people will want more. And i like your wish for keeping it simple :)

Thanks again for spending your time for me. ❤

**Comment by gsantner** [comment]
8. No, this is exactly what I was talking about! It is an very advanced texteditor, that can be used for variety of things, including currently todo,bookmarks and notes. But I don't wanna have an additional frontend/gui for the formats. The functionality is all tailored for texteditor and nothing else, that's what it's making it lightweight. And as said, I want to stay lightweight. What you request is not compatible with that and the projects goal.

**Comment by vfxturjo** [comment]
Okay now i understand.
I was thinking that i couldn't express myself property so i said it again.
Anyway, thanks for replying!!! :D

Sorry for my bad English and best wishes for you :)

**Comment by vfxturjo** [comment]
Heeeyyyyy sorry....

I wrote -------- "Check out 'material note' app. It has this feature. I am telling you to steal it. But you can do it i think"
Sorry for that.

I was trying to say "i am NOT telling you to steal it."
Really sorry.

**Comment by gsantner** [comment]
I know/thought so 😅.

Your english is fine, no need to apologize

**Comment by gsantner** [comment]
Closing this as there is no specific feature/bug in this. Open new issues with specific thing if needed.
