### ISSUE TITLE
Unsmooth scrolling in open source licenses area

### ISSUE THREAD

**Issue by def14nt** [gsantner/markor#406]
Very small bug but it's there. Dragging your finger (scrolling) in the open source licenses area isn't smooth - it stops when you stop, instead of keeping going like it should.

**Comment by gsantner** [comment]
This is because we dont use a webview or some complex component, but just a scroll-enabled textview (which is better/lightweight on ressources). It just doesnt have anything else implemented than scroll-by-direction :D.

**Comment by JohnVeness** [comment]
I too think this should be fixed, e.g. changing the component. This view appears when the app is first launched and (if I remember correctly) on updates and the lack of inertia is a small "papercut“. It gives a bad first impression, giving the user a feeling that the app might be a bit slow and clunky.

**Comment by def14nt** [comment]
@gsantner u should reopen this tbch

**Comment by gsantner** [comment]
why?!

**Comment by gsantner** [comment]
@def14nt 
If you can make it in less lines better than that, than show that and make a PR. Otherwise keep such comments for yourself.
