### ISSUE TITLE
Add 'App Shortcuts' for launchers

### ISSUE THREAD

**Issue by def0x099** [gsantner/markor#407]
There's a new kid on the block: [quick actions](https://developer.android.com/guide/topics/ui/shortcuts/). Would be cool if someone with Java know-how would send a pr for this, looks great.

**Comment by def14nt** [comment]
@gsantner I can take this up, but I can't promise anything until I learn the Android APIs. I will find time to mess about with it (as long as Gradle isn't a PITA). I'll see what I can do. 🤸
