### ISSUE TITLE
Feature Request: Adding settings option to determine whether the editor opens in edit mode or view mode by default

### ISSUE THREAD

**Issue by ManchurianSector** [gsantner/markor#408]
#### General information

* **App version:** 1.3.0
* **System:** LineageOS

#### Description
It would be really helpful if markor has a settings toggle that allowed the editor to open in view mode or edit mode by default

**Comment by gsantner** [comment]
this already exists. look at the settings of first said

**Comment by ManchurianSector** [comment]
I dont see it unfortunately

**Comment by gsantner** [comment]
representation -  prefer repräsentation
