### ISSUE TITLE
Allow export as PDF

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#41]
Allow rendered markdown to be exported as pdf

**Comment by KrishAmal** [comment]
Hey , i'd like to help . Can i use a library for that ? ( Because the android classes for native pdf generation require min API 19 )

**Comment by gsantner** [comment]
this is too to weight out if it is worth it. Moving to API19 - nope. Library, yes if its lightwright doesnt pull in too much dependencies. Basically html2pdf

**Comment by gsantner** [comment]
If you need more information ask. This issue is an idea, and about people to start contributing to the project. It has not much information because I pasted many ideas/issues and just let them out at the same time :). If you are interested in working on this, and have questions I can give you more details on this.

Register on https://hacktoberfest.digitalocean.com/, send a PR to fix this and get your t-shirt for free (4 accepted PRs to same or different GitHub repositories needed)  :). You have to mention the issue number in the commit/PR (e.g. `fix #20` / `about #8`) Find more hacktober issues from my projects: <https://github.com/search?&q=label%3Ahacktoberfest+user%3Agsantner>

**Comment by KrishAmal** [comment]
Yes , I'm indeed interested in working on this , a few lines of code enables Print PDf feature for devices running kitkat and above , however for the devices pre API 19, the libraries i've come across aren't lightweight and some use an AGPL license like [iText](https://github.com/itext/itextpdf)

**Comment by gsantner** [comment]
If you can implement this, so it works just for API19+, while still having an lower minSdk this is very fine :). There are annotations for marking API specifivs

**Comment by KrishAmal** [comment]
I've set the PDF-share menu item to be visible only on API 19+ devices. As for the imports , i did test the app on pre-API 19 (emulator) , and it works fine .
