### ISSUE TITLE
Feat: Export to hastebin

### ISSUE THREAD

**Issue by def14nt** [gsantner/markor#412]
This would be useful for error logs from apps etc, and would add to Markor's usefulness :)

**Comment by gsantner** [comment]
The code is already in Markor (probably the reason why you report I guess) - but the reason why it's not active is that you can't delete entries manually there. If you upload something wrong or overseen e.g. a secret info in the textfile theres no way to delete. Currently I don't plan at least to activate that.

**Comment by def14nt** [comment]
I honestly haven't looked in the source code yet. I was thinking more along the lines of code exporting (hence using hastebin) so error logs, hello worlds etc @gsantner

**Comment by gsantner** [comment]
<https://github.com/gsantner/markor/blob/master/app/src/main/java/net/gsantner/opoc/util/ShareUtil.java#L428> ^^
Another thing is that Markor is always said to be working offline. I tend to not include any network stuff in the app if possible (that's what other apps should do)

**Comment by def14nt** [comment]
It *will* still always work offline, but with more jazz :)

**Comment by gsantner** [comment]
Hehe, but then you need to describe everything and all in privacy documents and stuff.. :smile: too ^^

**Comment by def14nt** [comment]
A `we are not affiliated with Hastebin or X` and to be sure a link to their terms & privacy terms should do it
