### ISSUE TITLE
Changelog link to 1.3.0 blog post 404s

### ISSUE THREAD

**Issue by JohnVeness** [gsantner/markor#415]
In the CHANGELOG file in the repo, next to the heading for 1.3.0, there is a link to a blog post, specifically to https://gsantner.net/blog/2018/10/06/markor-release-v1.3.html , but that link brings up a 404 error.

**Comment by gsantner** [comment]
There will be a 1.4.0 post, this one was planned but never actually released.

**Comment by JohnVeness** [comment]
Thanks. For info, 1.3.0 was released on F-Droid, which is why I went looking in the CHANGELOG, which is linked from the F-Droid app entry.

**Comment by gsantner** [comment]
I will from now on set the link always to CHANGELOG, and change it to blog post when it's there
