### ISSUE TITLE
Black theme for AMOLED devices

### ISSUE THREAD

**Issue by sojusnik** [gsantner/markor#416]
We now have a light and a dark theme. Additionally, a pure black theme for AMOLED devices would be very useful. Especially the top title bar should also be black in order to be easy on the eyes and save energy. [PureWriter](https://play.google.com/store/apps/details?id=com.drakeet.purewriter) implemented this very well.

**Comment by roelfrenkema** [comment]
Just addapt the CSS to your wishes. 
Settings > Representation > Inject->head 
Thats all you need.

**Comment by gsantner** [comment]
In the next update will be an option under `Editor` settings to choose editor basic theme. There is an option `Black and white` which will make default (non-hl) text white and background black. Toolbar is not changed by this and currently not planned to be changed.

**Comment by sojusnik** [comment]
@gsantner Thanks for the editor settings! This helps a lot!

@roelfrenkema I'm not into coding and therefore don't know how to manipulate `head` with CSS. What would be the correct value to turn the toolbar completely black?

**Comment by gsantner** [comment]
you cant change the toolbar with CSS, only the content!

`background: 'black'` should do it usually

**Comment by sojusnik** [comment]
@gsantner 

Thanks for clarifying!

Since more and more devices have AMOLED screens now, I'm still convinced that there is demand for a pure black and white main interface of the app itself, not the editor. By main interface I mean those elements that are changed when switching from the light theme to the dark one. This would make Markor even more aesthetically pleasing and energy friendly.

I can't realistically estimate the effort to create such a pure black theme, in addition to the already present dark theme, but think that this issue should be reopened again so that maybe another person can implement it.

Würde mich freuen von dir zu hören und nochmals danke für diese App!
