### ISSUE TITLE
Unobtrusive syntax highlighting

### ISSUE THREAD

**Issue by sojusnik** [gsantner/markor#417]
If syntax highlighting in editor mode is enabled, then special characters that are used for Markdown formatting, like `*`, `~`, `#` etc., should be greyed out, while the word should be shown formatted. So if I write a word in bold – `this is an example with a **bold** word` – then the four `*` should be grey and transparent, while the word "bold" should be shown as bold, like already implemented.

This would drastically improve the readability. Have a look at [WriterPlus](https://play.google.com/store/apps/details?id=co.easy4u.writer) for proper implementation.

**Comment by gsantner** [comment]
I have thought about this and looked at it, but at Markor it's prefered to stay with syntax itself highlighted.

**Comment by sojusnik** [comment]
Too bad :disappointed: 
A simple option in the settings would be good compromise.

**Comment by gsantner** [comment]
A simple option would toggle two complete different ways to work, requiring nearly full duplicated rewrite of code. It's not just adding a checkbox..!

**Comment by sojusnik** [comment]
Oh, thanks for the clarification! I wasn't aware that this is so complex.
