### ISSUE TITLE
Replace markdownbar with markdown actions instead of just characters

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#42]
E.g. a icon showing bold text -> makes selected text, or current word bold / not bold depending on current state.

Example UI from OctoDroid below

![30575545-de5735e4-9d01-11e7-852a-e5dda1950155](https://user-images.githubusercontent.com/6735650/31045858-14482ae8-a5ed-11e7-97af-14d9d1c04f95.png)

**Comment by gsantner** [comment]
If you need more information ask.

Register on <https://hacktoberfest.digitalocean.com/>, send a PR to fix this and get your t-shirt for free :).

**Comment by KrishAmal** [comment]
Hey @gsantner I'd like to work on this . After a particular word/text is set as bold , should the user select the text only or the text with the special characters ( eg: \*\*hello\**\)  to set it as not bold ?

**Comment by gsantner** [comment]
i would go for both, Left/right scan, and inner scan (which stops if non-markdown chars are found)

**Comment by gsantner** [comment]
I think you will know what is best. Maybe go after how <https://stackedit.io/editor> does it like

**Comment by KrishAmal** [comment]
@gsantner  Yeah sure. The Stackedit.io implementation looks neat .

**Comment by KrishAmal** [comment]
Hey , what does the smart shortcuts accomplish ?

**Comment by gsantner** [comment]
Some little intelligent bracket inserter. All this can be removed then, the whole bar. As your solution will replace the character insertion with real actions :)

**Comment by KrishAmal** [comment]
Okay cool 👍 . 
I've planned to include actions for the following

1. Bold
2. Italic 
3. Strike-through
4. Inline code
5. Blockquote
6. Heading 1
7. Heading 2
8. Heading 3 
9. Ordered List
10. Numbered List
11. Horizontal Line
12. Links

**Comment by gsantner** [comment]
Nice :D

have fun hacking 😎😀👍

**Comment by KrishAmal** [comment]
Definitely 😄
