### ISSUE TITLE
"Sort by" button too close on the screen side during a searching

### ISSUE THREAD

**Issue by ema-pe** [gsantner/markor#421]
#### General information

* **App version:** v.1.3.0 (39)
* **System:** LineageOS 14.1

#### Description

When you press search button, the button to change the order of files is too close to the right screen side, anyone can see that it is not properly aligned.

The following image shows the bug:

![markor-bug](https://user-images.githubusercontent.com/21246809/47840982-fdb03900-ddaf-11e8-9b25-1563b7006831.jpg)

**Comment by gsantner** [comment]
Thanks for reporting!
I tried this now, but I'm feeling like the extra width available for search input doesn't hurt :wink:
