### ISSUE TITLE
Bullets are redundant for checklist

### ISSUE THREAD

**Issue by sivaraam** [gsantner/markor#430]
#### General information

* **App version:** 1.4.0 F-Droid
* **System:** Android 5.1.1, Samsung Galaxy J1 ace

#### Description
The bullets that prefix a checkbox in the preview of a checklist seem redundant as the checkbox itself seems sufficient to distinguish list items. Avoiding to show the bullet points for checklist would save some space in the preview.

**Screen shots**
![screenshot_2018-11-18-02-37-35](https://user-images.githubusercontent.com/12448084/48665796-f6409d80-eada-11e8-9c3e-99b85c111836.png)
![screenshot_2018-11-18-02-37-41](https://user-images.githubusercontent.com/12448084/48665797-f8a2f780-eada-11e8-91da-794f4d2df540.png)

**Comment by gsantner** [comment]
thats generated like this by the flexmark parser. Actually know it like this in most parsers. Dont want to change common behaviour a user awaits at this
