### ISSUE TITLE
[Feature] Shortcut in toolbar to create a checklist

### ISSUE THREAD

**Issue by sivaraam** [gsantner/markor#431]
#### General information

* **App version:** 1.4.0 F-Droid
* **System:**  Android 5.1.1, Samsung Galaxy J1 ace

#### Description
It would be nice to have a short-cut in the bottom toolbar to start creating a check-list (`- [ ] `) just like the ones that are available for creating a ordered/unordered list in the bottom toolbar.

Also, it would be nice to have the prefix (`- [ ] `) for the second item in the list automatically appended after I hit enter in the first item. Just like the ordered/unordered lists.

**Comment by gsantner** [comment]
#429
