### ISSUE TITLE
Incorrect activity title in some cases

### ISSUE THREAD

**Issue by sivaraam** [gsantner/markor#432]
#### General information

* **App version:** 1.4.0 F-Droid
* **System:**  Android 5.1.1, Samsung Galaxy J1 ace

#### Description
The title of the activity is incorrect in one cases. This leads to confusion as to location I'm currently in. For example:
1. Open the app
1. Tap on a folder
1. Tap on More/To-Do/QuickNote in the bottom navbar

**Expected**: The title of the activity changes accordingly (as 'Markor').
**Actual**: The title is that of the folder name which is confusing.

**Screen shots**
![screenshot_2018-07-12-03-26-56](https://user-images.githubusercontent.com/12448084/48665889-e629bd80-eadc-11e8-8d9f-70ccd9f52330.png)
![screenshot_2018-07-12-03-27-06](https://user-images.githubusercontent.com/12448084/48665891-ed50cb80-eadc-11e8-9f6a-8574bcef5d5d.png)
![screenshot_2018-07-12-03-27-00](https://user-images.githubusercontent.com/12448084/48665893-f17ce900-eadc-11e8-8206-8f200080e31b.png)

**Comment by jakeoneijk** [comment]
Hello, If nobody is working on this, I want to try this.

**Comment by jakeoneijk** [comment]
how about changing the title as the name of the Menu(eg) when tap 'To-Do' change the title as 'To-Do')
