### ISSUE TITLE
TextAction: Insert custom snippets/text blocks

### ISSUE THREAD

**Issue by ghost** [gsantner/markor#437]
HTML has a lot of useful tags for text formatting, all of which could be a good addition to the bottom bar, though adding all of them obviously isn't that practical.

I think it would be a great idea to add a few extra buttons that can be configured to input text to the right and left of the cursor, similar to the bold, italic and striketrough buttons.

And you could even take it a step further and let them execute javascript code.

This would also double as a way of having templates, signatures, and so on.

**Comment by gsantner** [comment]
> And you could even take it a step further and let them execute javascript code.

No, this won't come for sure. I don't want some kind of scripting engine in this lightweight app ;).

**Comment by gitgerardo** [comment]
I like the idea . It would be nice to have the possibility to edit the "**handy buttons**" tool bar. If I have e.g. to insert the video tag ```<video controls src="XY"></video> ``` every day , it would be nice to have the possibility to have it in the tool bar . You don t think so?

**Comment by gsantner** [comment]
Thats more kind of snippets feature then

**Comment by gsantner** [comment]
I will soon close this in favor of a different/new one. The plan is more to go for a "snippets" feature where you can have a custom amount of defined text blocks that can be inserted into current text.

Want this to have each a title and content, and reachable via menu. 

The bottombar is a set of buttons with icons only (which I want to keep that way, and only the hottests actions). When user start with custom actions I want them to be able to have title so they can always see what it is about and don't have to guess.

**Comment by gsantner** [comment]
Note: Customizable actions order (#899) was done recently, this might make it easier to implement this. If somebody is interested to develop on this.

**Comment by harshad1** [comment]
Theoretically, one can use the insert time / date dialog for this :).
