### ISSUE TITLE
$x$ gives block equation instead of inline equation

### ISSUE THREAD

**Issue by seadra** [gsantner/markor#440]
This is broken by the recent changes regarding math block rendering. $x^2$ should give an inline equation (that's how it works in latex and typora), and it used to work this way in markor before 1.4.0. Now, it gives a block equation.

**Comment by gsantner** [comment]
![screenshot-2018-12-09__20-30-34](https://user-images.githubusercontent.com/6735650/49701800-4948d480-fbf1-11e8-93b8-abb452034764.png)
![screenshot-2018-12-09__20-29-53](https://user-images.githubusercontent.com/6735650/49701801-4a7a0180-fbf1-11e8-97f2-ad4259b7a09f.png)

**Comment by seadra** [comment]
I just tried a similar simple example in a new document, and it still gives a block equation. Using v1.4.0 from F-Droid

**Comment by seadra** [comment]
Could you re-open the issue? I am not able to

**Comment by gsantner** [comment]
It's fixed in 1.5.0. Please install the update and try then. For F-Droid - wait some days till they publish update.

**Comment by seadra** [comment]
Thanks. I just tried with 1.5.0, but it's still not completely fixed. If there is a parenthesis, it is still rendered on multiple lines. For example, $R(x)$ gives the following as the output:

$R
x
$

The first and last lines are rendered as normal text, and the middle line with x is rendered with math.

**Comment by gsantner** [comment]
Maybe ask at KaTex whats a suitable and working configuration. I'm not using that myself, and I wait for KaTex project to finally provide a working config that works for common cases.I can't find one single line that works for all cases.
