### ISSUE TITLE
"Apps" not opening correctly

### ISSUE THREAD

**Issue by shawn1thompson** [gsantner/markor#442]
#### General information

* **App version:** 1.4.0 (40) F-Droid
* **System:** Android version 8.0.0, Moto g6, stock rom

#### Description
All of the apps created by Markor open linobox even though the location is specified in Settings.

#### Log
I'm not sure where to obtain t the log.

**Comment by gsantner** [comment]
Can you please describe more whats the problem? Markor is one app, don't understand what you want to say at all :-).

Log: As said in template, use the link below. But in this case I think it's not needed. <https://gsantner.net/android-contribution-guide/?packageid=net.gsantner.markor&project=markor&web=https://github.com/gsantner/markor#logcat>

**Comment by shawn1thompson** [comment]
Sorry, I mean the apps that Markor creates in the launcher, i.e., linkbox, Todo, and quick note.

Shawn Thompson
shawn.thompson@politicalphilosopher.xyz
"Each one teach one"

-------- Original Message --------

**Comment by gsantner** [comment]
Ok, so there is an problem with Markor's launcher shortcuts.
Still you didn't say what the problem is, and what happens!

**Comment by shawn1thompson** [comment]
Sorry, I thought I had. So all of the launcher shortcuts open the linkbox file, even quicknote and Todo. Three path for all there is correctly configured in Markor's app-wide settings.

Shawn Thompson
shawn.thompson@politicalphilosopher.xyz
"Each one teach one"

-------- Original Message --------

**Comment by shawn1thompson** [comment]
I'm not sure what changed, but it's working correctly now.
