### ISSUE TITLE
Option to Prevent automatic screen timeout

### ISSUE THREAD

**Issue by anishmittal2020** [gsantner/markor#443]
#### General information

* **App version:** 
* **System:** 

#### Description
 Could you please let us enable a key to prevent automatic screen timeout (just like the feature in Adobe acrobat app).

**Comment by jakeoneijk** [comment]
hello I wanna work on this :)

**Comment by gsantner** [comment]
@jakeoneijk sure, no need to ask!
Please add yourself to CONTRIBUTORS.md too, if you want of course ;).

**Comment by jakeoneijk** [comment]
thanks a lot !!!

**Comment by gsantner** [comment]
This is now implemented thanks to @jakeoneijk
