### ISSUE TITLE
Feature request: Option to select default new file type

### ISSUE THREAD

**Issue by ali-hardan** [gsantner/markor#452]
#### General information

* **App version:** 1.5.0
* **System:** Android 7.0

#### Description

I want to set default type to "Jekyll Post".

**Comment by JohnVeness** [comment]
I think this is a good idea, but rather than have an actual setting visible in the UI, I think it would be better if the app just remembered the last file format the user created.

**Comment by gsantner** [comment]
Will be taken in account for `NewFileDialog` changes. As there likely will be more features  and options baked into it I won't go for this for now (to only drop it in next patch again).
