### ISSUE TITLE
Feature Request: Words Count, Customise Markdown Colors

### ISSUE THREAD

**Issue by Knifemint** [gsantner/markor#453]
#### General information

* **App version:1.5.0** 
* **System: Galaxy Note 3 (LineageOS 15.1 Unofficial Build 20181129)** 

#### Description

Some feature requests:
- Word count in File Details, similar to Writer and Writer Plus.
- Customisable markdown syntax/highlights colors. Different headers with the same color is quite confusing.
- Allow opening the file without opening the keyboard automatically. I've noticed that files that weren't opened yet with Markor does not open the keyboard automatically. Maybe a preview button at the right side of the file in notebook might be nice.

**Comment by gsantner** [comment]
Hi @Knifemint 

* Likely to be included, please open a seperate issue! :)
* Won't come for sure. Performance is important at highlighting and dynamic colours make it not easier on cpu. Devices already struggle with the current constant colours. Too colours MUST work with both, dark and light colours and various other things must be considered. This won't happen.
* Seems like a minor issue with NewFileDialog, seems to be already fixed
