### ISSUE TITLE
Activity Title not updated at MainActivity

### ISSUE THREAD

**Issue by TakuyaSama** [gsantner/markor#457]
#### General information

* **App version:** 1.5.0 F-Droid
* **System:** LineageOS 15.1, based on Android 8.1

#### Description
The app doesn't change the **activity** **title/name** when i swipe left or right to change the activity. It does if i use the buttons for navigation located at the bottom bar.

**Comment by gsantner** [comment]
@TakuyaSama 
At the main activity (where notebook is)?

**Comment by TakuyaSama** [comment]
@gsantner 
On every single activity.

**Comment by gsantner** [comment]
Sorry but I don't know what you mean.
Except the Main-View with Notepad, the app has not a single Swipe-able activity or fragment!

**Comment by TakuyaSama** [comment]
@gsantner 
I mean navigating between the 4 main activities on the home screen. The ones that you have positioned 4 buttons for navigation at the bar at the bottom. I'm sorry if i'm not explaining well myself.

**Comment by gsantner** [comment]
Okay, then it was exactly what I meant with the one thing ;).
I will take a look

**Comment by gsantner** [comment]
This was fixed in code 6 hours ago..it is not in any release out yet. Even more not in case of F-Droid.

**Comment by TakuyaSama** [comment]
@gsantner 
Oh great, i'll be waiting for it then.
Thanks.
