### ISSUE TITLE
Can't rename a file

### ISSUE THREAD

**Issue by ema-pe** [gsantner/markor#458]
# Description

When I edit a document, I can't rename the file. I attached a video that shows the bug and how to reproduce it.

Video: https://gfycat.com/ImperfectElegantHusky

# System information

I tested this bug on two smartphones:

**App version:** v1.5.0 (42)
**System:** LineageOS 14.1 (Android 7.1.2)
**Source:** Google Play

**App version:** v1.5.0 (42)
**System:** Android 8.0.0
**Source:** Google Play

# Steps to reproduce (if you can't see the video)

1. From the home screen of Markor, click "New file" button;
2. Insert a name and press `OK`;
3. Now the editing window is open, click on the filename;
4. The filename box is highlighted, but you can't edit it.

**Comment by gsantner** [comment]
I have been telling this now like the 20. time.... 

Please read update notes. It's written that you MUST rename via Notebook now. Rename at editor is fully disabled and the whole editbox there is removed from editor in next update completely.

**Comment by def14nt** [comment]
@gsantner I'd remove the white line under the text box then, as it gives the impression it's modifiable.
