### ISSUE TITLE
Enable localization of "my_note" filename suggestion

### ISSUE THREAD

**Issue by ema-pe** [gsantner/markor#459]
This is only a small issue. You should enable the localization of `my_note` suggestion, a string that appears if you want to create a new file or document.

**Comment by gsantner** [comment]
What do you think fits best there, for filename example? Quickly typed my_note.md but there might be some better one. What do you think?

**Comment by ema-pe** [comment]
`my_note` is a good choice, but it should be localizated for every language. For example in italian it should be `mia_nota`.
