### ISSUE TITLE
Can't see all files in browser

### ISSUE THREAD

**Issue by ds6** [gsantner/markor#461]
#### General information

* **App version:** 1.5.0
* **System:** LineageOS 15.1 Android 8.1.0 F-Droid 1.5-alpha0

#### Description
The file browser does not show all file types, and "empty folders" may actually have files in them. Language should be added to specify when there are files in a folder but they are not visible (eg. "No documents") and an option should be included that allows showing and editing all files (eg. I want to edit .tex)

**Comment by gsantner** [comment]
It was yet intentionally, to only show documents. A rework of Notebook is planned which likely will show all files, but it's not fixed yet how it will look like.

#115

**Comment by gsantner** [comment]
Complete rework of filesystem view be part of the 1.7.4 release and will be featured in the 1.8 blog post.

With that rework all files & folders will be shown, with order: folder, documents (as listed before), other files.

**Comment by ds6** [comment]
Thanks for the update.
