### ISSUE TITLE
Formatter / syntax highlighting for VSCode Todo+ extension format

### ISSUE THREAD

**Issue by patrickvbe** [gsantner/markor#462]
#### Description

It would be nice to have (at least partial) syntax highlighting and / or a text formatter for the textual todo+ file format used by the [VS-Code todo+ extension](https://github.com/fabiospampinato/vscode-todo-plus) It has more options and provides a better overview (imho) than the todo.txt format but probably needs less formatting (though some 'shortcuts' for create/check/uncheck would be nice).

**Comment by gsantner** [comment]
Hi @patrickvbe 

I have looked into this `todo+` format and I'm feeling like it's not like a "todo.txt ++", but more a whole different format.
Currently it's not planned to have integrate another/alternative todo format, but to improve and optimize whats there with todo.txt.
If you still would like to work on this, feel free to, and I'm happy to do code review and merge stuff if it's ready, but I won't work on this myself.
