### ISSUE TITLE
[feature request] QOwnNotes-style relative images path

### ISSUE THREAD

**Issue by ptah-alexs** [gsantner/markor#463]
Qownnotes use relative path for images with prefix "file://". Please add ability show this images in markor without edit notes. 

Qon: \!\[alt text](file://media/image.png) == Markor: \!\[alt text](media/image.png)

**Comment by gsantner** [comment]
I checked Markor's parsers options and I could not find any option to turn this off/on. As this is specific to the Markdown parser, please ask the parser's bugtracker. Thanks! if you got an answer let me know and I happily activate the options.

Tracker: https://github.com/vsch/flexmark-java/issues

(I checked options from [here](https://github.com/vsch/flexmark-java/wiki/Extensions#parser)).

**Comment by schiessle** [comment]
@gsantner if I understand the comment over here https://github.com/vsch/flexmark-java/issues/308 this should be already possible
