### ISSUE TITLE
Can't open color dialogue when setting editor color scheme

### ISSUE THREAD

**Issue by ClockGen** [gsantner/markor#465]
* **App version:** 1.5.1 (F-Droid)
* **System:** LineageOS 15.1 (Oreo 8.1.0)

#### Description

On both GPlay and F-Droid versions it's not possible to change colors in editor color scheme preferences. The screen just flashes for a moment and then returns to previous menu. On Markor 1.4 it would show color selection dialogue briefly but would close right away anyway. Selecting predefined configs works fine.

**Comment by gsantner** [comment]
fixed in code alteady, available in next update.
