### ISSUE TITLE
No word wrap when previewing Markdown vs TXT

### ISSUE THREAD

**Issue by def0x099** [gsantner/markor#466]
As the title states, previewed Markdown doesn't seem to fit the text to the screen, compared to previewing with the Plain Text format. This is annoying, because the document scales to the longest line, meaning other text gets smaller and smaller.

**Comment by gsantner** [comment]
#539

**Comment by def0x099** [comment]
Doesn't fix the issue @gsantner. Why are they being rendered differently?

**Comment by gsantner** [comment]
duplicate has better description.

**Comment by gsantner** [comment]
oh, thats about something else.

anyway there were fixes for this in a recent update.
