### ISSUE TITLE
Code blocks being greyed out in editor

### ISSUE THREAD

**Issue by def0x099** [gsantner/markor#468]
What is this beauty
![](https://i.imgur.com/pkQSd1D.png)

**Comment by def14nt** [comment]
@gsantner What was the conclusion?

**Comment by hamid-elaosta** [comment]
The 1.7.0 build I got from F-Droid seems to suffer this issue, code blocks aren't being parsed correctly and it's treating the first two of the back ticks as a single line code block.

It's more obvious if you have monospace set for markdown code blocks

**Comment by def0x099** [comment]
So I should get the Play Store version?On 14 Mar 2019 6:58 pm, Hamid <notifications@github.com> wrote:The 1.7.0 build I got from F-Droid seems to suffer this issue, code blocks aren't being parsed correctly and it's treating the first two of the back ticks as a single line code block.
It's more obvious if you have monospace set for markdown code blocks

**Comment by hamid-elaosta** [comment]
I have no idea if the Play Store version works, I'm just confirming that I also have the issue you are having.

It seems to be a bug that hasn't been resolved yet.

**Comment by gsantner** [comment]
@hamid-elaosta 
Improvements for inline highlight were done at #582

**Comment by gsantner** [comment]
@def0x099 
Checked the file. The first seven lines start each with at least 4 spaces, which means code highlighting gets started. This is behaviour as expected.

Closing.

**Comment by hamid-elaosta** [comment]
@gsantner It doesn't appear to have been resolved in 1.8.1

![Screenshot_20190620-144543](https://user-images.githubusercontent.com/8222444/59854206-5e55ab80-936a-11e9-9a06-ed95659fc256.jpg)

![Screenshot_20190620-144447](https://user-images.githubusercontent.com/8222444/59854221-644b8c80-936a-11e9-97b0-efe9262e7624.jpg)

**Comment by resynth1943** [comment]
Is this the expected behaviour, @gsantner?

**Comment by gsantner** [comment]
I fixed this minutes ago, wait for the update.

**Comment by hamid-elaosta** [comment]
Apologies, I misunderstood ticket #582 and thought it had been resolved in 1.8.1. I see now it's _just_ been fixed and will be in 1.9.0.
