### ISSUE TITLE
Link to named anchors

### ISSUE THREAD

**Issue by SevereOverfl0w** [gsantner/markor#469]
#### General information

* **App version:** 1.5.1

#### Description

I would like to be able to follow links to specific sections of markdown documents.  Currently when I click on a link like `[foo](foo/bar.md#heading)` it attempts to open it with different programs, unrelated to markdown at all.  Github's README, Gollum and https://github.com/plasticboy/vim-markdown#follow-named-anchors are a few examples of places this functionality exists.

**Comment by gsantner** [comment]
How should Markor know that this is not a link to the real file `foo/bar.md#heading`? Because this is a valid filepath, `#` is an allowed character.
While it's likely the common case that this is anchor, still you would then not be able to link to files with a real `#` in the filename. Unsure about this.

**Comment by SevereOverfl0w** [comment]
A solution which would cover this further would be to check for the existence of `foo/bar.md#heading` first, and then fall back to `foo/bar.md` at `#heading`.

**Comment by ranebrown** [comment]
I think supporting anchors to headers is an awesome idea! I do have a couple of questions though:

1. Does something like `[My Header](#Header1)` link correctly to the header in the current document?
2. How are spaces in a header name handled? I.e. if the header is something like `# Header with spaces` is the corresponding link `[My Header](#Header with spaces)`? From what I have seen (GitHub, GitLab, etc.) the link should be converted to lowercase and the spaces replaced with dashes `[My Header](#header-with-spaces)`. Obviously, the user would need to create the links correctly but I think this would be the most compatible option.

**Comment by gsantner** [comment]
You can try both, the first one works for sure.

**Comment by ranebrown** [comment]
Sorry, not clear on which point mean. For sure using spaces in the anchor works and the dash method might work?

**Comment by gsantner** [comment]
Simple: Try all out that you want and you can comment the results here. ;) 

This issue was about loading other files while there is an anchor in the filename.

**Comment by ranebrown** [comment]
So this didn't add support for named anchors, it just opens the file in Markor and ignores the anchor part? I tried all the options I mentioned and none of them seem to work including adding the filename before the anchor. Should I open a different issue regarding adding support for named anchors?
