### ISSUE TITLE
Fix share document as image

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#47]
Currently exporting a markdown document as image just exports the visible part. Resolving this should export the whole document as image. Also the image currently contains a lot of whitespace on bottom (see image), which should be gone too. 

<table><tr><td><img src="https://user-images.githubusercontent.com/6735650/31055983-6c82482c-a6cb-11e7-9274-222d90767b9b.jpg"  width="200px" /></td></tr></table>

**Comment by gsantner** [comment]
If you need more information ask. This issue is an idea, and about people to start contributing to the project. It has not much information because I pasted many ideas/issues and just let them out at the same time :). If you are interested in working on this, and have questions I can give you more details on this.

Register on https://hacktoberfest.digitalocean.com/, send a PR to fix this and get your t-shirt for free (4 accepted PRs to same or different GitHub repositories needed)  :). You have to mention the issue number in the commit/PR (e.g. `fix #20` / `about #8`) Find more hacktober issues from my projects: <https://github.com/search?&q=label%3Ahacktoberfest+user%3Agsantner>

**Comment by jvretamero** [comment]
Can I solve this?

**Comment by gsantner** [comment]
ye

**Comment by aleb2000** [comment]
Reproducible on Markor 1.7.6 F-Droid (Android 7.0, Samsung S6).
Open a file containing a long text -> Representation -> Share -> Image -> select an app (only the visible part is exported)
If I go back when there is the pop-up to select the app and then I share a second time as an image, the document is exported correctly.

**Comment by aleb2000** [comment]
Reproducible on Markor 1.8.0
The 5 seconds wait doesn't fix it, PDF export works correctly also without the waiting time.
Is it wanted that the 5s wait is applyed only on edit mode sharing and not in the representation mode sharing?
Could you reopen this issue?

**Comment by gsantner** [comment]
send a PR to fix it, should be easy to fix.

PDF and image uses the same thing.

**Comment by Z4HD** [comment]
Reproducible on Markor 2.5.0 (121) F-Droid (Android 9.0, MIUI eu 11.0.5, Mi6).

Try to render `markor-markdown-reference.md` by following steps: `Representation -> Share -> Image -> select an app`, only the visible part is exported.

The @aleb2000 's method can't fix this. Is #80 correctly apply in the mainline?

<details><summary>Exported image</summary>

![SharedImage2473681727292489967](https://user-images.githubusercontent.com/25260404/106380320-81708a00-63ec-11eb-8bc9-5ac64684f8b8.jpg)

</details>
