### ISSUE TITLE
Change rename icon

### ISSUE THREAD

**Issue by def14nt** [gsantner/markor#471]
When you hold down on a folder/note in the main view, you can rename it using the icon in the header. I really don't think using the label icon is a good representation of the rename action, as a label is normally used as an icon for modifying a label/tag on an item. Maybe you could change this to the pencil icon?

**Comment by gsantner** [comment]
This will get removed from the toolbar, so wont put any work into this

**Comment by def14nt** [comment]
Why is it getting removed if people are used to it?
