### ISSUE TITLE
Bad color choice

### ISSUE THREAD

**Issue by def14nt** [gsantner/markor#472]
Sorry, but I forget the name of these fullscreen text things lol. 

But is this really a very good color scheme? It makes the app look silly and a bit basic. 

[I couldn't embed it, sorry.](http://imgur.com/a/9AqjiUw)

**Comment by gsantner** [comment]
mostly just the accent color. Changelog is related to the thing, New e.g. green.

**Comment by def14nt** [comment]
@gsantner So this is a WONTFIX? Why? It looks horrible
