### ISSUE TITLE
Allow multiple folders for Notebook section

### ISSUE THREAD

**Issue by JohnVeness** [gsantner/markor#473]
#### General information

* **App version:** 1.6.0
* **System:** Sony Xperia Z5 Compact, Android 6.0.1

#### Description
Up until now all my documents that I've wished to edit in Markor were in one folder (/storage/emulated/0/Documents), with subfolders inside. I now wish to edit documents from that folder, and from another folder outside that hierarchy, e.g. /storage/emulated/0/MoreDocs. I cannot easily move folders around due to other issues to do with file syncing and so on.

At the moment I have changed Markor so that it is looking in the top-level of /storage/emulated/0, but that folder is very busy and takes a lot of scrolling up and down to get to Documents and MoreDocs.

It would be great if we could define more than one folder for Markor to display in its top-level list. So in my instance, I would define both /storage/emulated/0/Documents and /storage/emulated/0/MoreDocs and they would appear separately at the top-level in Markor (ideally as just "Documents" and "MoreDocs").

This would also help if wishing to edit some files on internal storage and some on SD card, where the two folders are even further apart in the filesystem hierarchy.

For info, the Simple Gallery app (https://github.com/SimpleMobileTools/Simple-Gallery) allows exactly this, with a list of folders to look at.

Another advantage of "virtualising" the top-level folder view is that you could add a "Recent docs" folder or similar.

**Comment by gsantner** [comment]
With the upcoming update there will be a favourite/unfavourite option in toolbar.
You willl be able to navigate to favourites from the folder selection.

You can add both, folders and files to favourities. I.e. you can now have as much "Notebook" folders as you wish.
