### ISSUE TITLE
Swipe for preview [feature request]

### ISSUE THREAD

**Issue by subi54** [gsantner/markor#475]
#### General information

* **App version: 1.6.0** 
* **System: Android 8.1** 

#### Description
I did search but came up empty.

Would like to request a feature: Swipe left to go to the preview. iA Writer-esque.

It feels intuitive and more user friendly for larger screens.

Thank you for the wonderful app.

**Comment by gsantner** [comment]
Feels free to work on it ;)

**Comment by nirmalkumarr12** [comment]
Hi, @gsantner  I would like to contribute to this feature.

**Comment by gsantner** [comment]
@nirmalkumarr12 
Very welcome!

Hint: Event x/y difference
