### ISSUE TITLE
Change that pink color, maybe?

### ISSUE THREAD

**Issue by def14nt** [gsantner/markor#483]
#### General information

* **App version:** 
* **System:**

**Comment by def14nt** [comment]
@gsantner oh shit I edited this, sorry.

**Comment by gsantner** [comment]
Still, no. I wont make a change on the accent color and I already told you that.

**Comment by def14nt** [comment]
@gsantner Can you give a solid reason why?

**Comment by tareefdev** [comment]
Another suggestion is to allow the user either to keep the default color or use the Material You color.
