### ISSUE TITLE
accentuated character in filename sorted in wrong order

### ISSUE THREAD

**Issue by legrostdg** [gsantner/markor#484]
#### General information

* **App version:**  1.6.0

#### Description

A filename named `électricité.md` is sorted after `zoo.md`, but the `é` should be considered as a `e`.

**Comment by gsantner** [comment]
As far I see the natural order depends on your system language/locale setting. Markor just uses natural sort order.

**Comment by legrostdg** [comment]
It's weird, my language/locale setting is french, so this should be ordered the way I said. Also note that the other applications I have on my phone do not have this issue (`é` is sorted as `e`)...
