### ISSUE TITLE
share/export to PDF produces large file when document contains image(s)

### ISSUE THREAD

**Issue by eternalbit** [gsantner/markor#485]
#### General information

* **App version:** v1.6.0 (45)
* **System:** Android 7.1.2

#### Description
Including an image (2048x1536, jpeg, **0.93 MB**) taken with the camera in a document results in a **5.9 MB** PDF file on export.
The image is probably handled as an uncompressed bitmap or PNG.

Maybe the _Android.Graphics.Bitmap.Compress_ method could be used to compress the image data before it gets rendered to the PDF via the the _drawBitmap_ Method?
The respective code (?): https://github.com/gsantner/markor/search?q=drawbitmap&unscoped_q=drawbitmap

These links might be useful
- https://stackoverflow.com/questions/8417034/how-to-make-bitmap-compress-without-change-the-bitmap-size
- https://developer.xamarin.com/api/member/Android.Graphics.Bitmap.Compress/p/Android.Graphics.Bitmap+CompressFormat/System.Int32/System.IO.Stream/

**Comment by eternalbit** [comment]
Found another link that might be useful:
https://stackoverflow.com/a/47192359

**Comment by gsantner** [comment]
PDF is created by android internal's PrintManager, Markor doesn't use any draw functionalities. Thanks for research, but this is not applyable. I also don't suggest to integrate another PDF print library, it just bloats.
