### ISSUE TITLE
Optional hiding of YAML front matter?

### ISSUE THREAD

**Issue by caislean-west** [gsantner/markor#487]
#### General information

* **App version: v1.6.0(45) F-Droid** 
* **System: LineageOS (Oreo-Based)** 

#### Description

Hey, love the app!  Quick problem: any markdown starting with a horizontal line (`---`) hides everything until the next horizontal line.  I would guess this is maybe a default behavior of the parser, since this is a [popular metadata format](https://jekyllrb.com/docs/front-matter/) for YAML front-matter in markdown files, so these blocks only show up in editor mode, but not the rendered output.  

However, it would be nice to choose to see that data in presentation mode, rendered in it's "normal" markdown interpretation!  

I must admit, my main motivation is a particular markdown format for [storing food recipes](https://chowdown.io/) that cleverly leverages the front-matter to store the main bulk of recipe information for database purposes; so I understand if this is an odd use-case.  Hopefully this is a simple fix, adding a settings option for the parser somewhere, but if it isn't I would be willing to take a crack at it in my free time (or maybe even adding a chowdown format, if it's widely desired!)

#### Example

A file containing this does not render anything:
```markdown
---
something
```

And this file:
```markdown
---
format: recipe
title: "Apple"
ingredients:
- 1 apple
direction:
- eat an apple
---
Fun apple facts
```
Will only render:
> Fun apple facts

**Comment by gsantner** [comment]
you could aswell just insert a Zero-Width-space in front of each `---`. 
Makes the `---` visible and disables `h3` headline.

**Comment by gsantner** [comment]
@caislean-west 
There is a different header highlighter available since some releases, that only checks `#` for headers. Checkout format markdown settings

**Comment by ibnishak** [comment]
Is this option still available? I could not find it in the format markdown settings. Version 2.2.7

**Comment by gsantner** [comment]
yes, in markdown settings theres a different header option.
