### ISSUE TITLE
markor crashes immediately if I open a file while the keyboard is still up from search

### ISSUE THREAD

**Issue by indeedwatson** [gsantner/markor#488]
#### General information
Version 1.6.0 F-Droid
Android 7.0

#### Description
If I press the looking glass to search, the keyboard will popup to type. After a few seconds, the keyboard will hide on its own. If I'm typing it will hide mid-typing.

However if I type and click on a file while the keyboard is still up, the app will crash.

If I type and wait for the keyboard to disappear and click on a file, it will go into the file normally.

After the keyboard hides itself, I can bring it up again with the search and it will not disappear, nor will the app crash if I click on a file while it's still up.

#### log
https://gist.github.com/indeedwatson/5abe1a0f86e843050d345a1fcb64e318

**Comment by gsantner** [comment]
I cannot reproduce the problem on the current release.

Can you please try if this still happens for you?

**Comment by indeedwatson** [comment]
Yup, keeps happening reliably on 1.6.2

**Comment by gsantner** [comment]
If somebody else has the issue, please write here.
I can't reproduce this on my device(s) and don't really see a issue in the log on first sight

**Comment by 809825706** [comment]
@indeedwatson it maybe due to the input keyboard apk, have you tried other keyboard apk?

**Comment by indeedwatson** [comment]
I haven't, and my phone is pretty much dying so I'm not sure i'll be able to test that but I'll be sure to comment if I manage to do it.

**Comment by def0x099** [comment]
@gsantner Cannot reproduce with Markor v1.7.2 with Google Pixel 2 XL.
