### ISSUE TITLE
margin in css is ignored

### ISSUE THREAD

**Issue by Offerel** [gsantner/markor#494]
Hello there, i have added a custom css in representation header for blockquote. But it seems that the margin is ignored.

```
blockquote: {
color: #3c763d;
    background-color: rgba(66, 185, 131, .1);
    padding: 0;
    margin: 15px 0;
    border-left: 4px solid #42b983;
}
```
Do you have any idea what's wrong with the css or the implementation?

**Comment by gsantner** [comment]
> blockquote: 

the first line seems not quite right to me

**Comment by Offerel** [comment]
Grrrrr, my failure. I misspelled margin, now it works. Sorry for confusion.

**Comment by gsantner** [comment]
np
