### ISSUE TITLE
Missing borders in tables

### ISSUE THREAD

**Issue by mat-m** [gsantner/markor#495]
#### General information

* **App version:** 1.6.2 GPlay
* **System:** Android 8

#### Description

I saw 3 closed issues related to this, but I did not understand if adding a border is upstream-dependent or not (#92).
I think currently, tables are lacking borders. It helps to visualize columns on the phone, when the width left a quite small space between the two values, like the prices in my table.

![screenshot_20190203-015458_markor](https://user-images.githubusercontent.com/1039753/52171166-49300580-2758-11e9-87fb-4e4a2867b7d5.jpg)
![screenshot_20190203-015701_markor](https://user-images.githubusercontent.com/1039753/52171167-49c89c00-2758-11e9-91f0-711b5b6d17a3.jpg)

**Comment by gsantner** [comment]
Some people want borders some do not. That's a thing of taste, and may differ from table to table.

You can edit per-table by directly entering it in the document, or via the `inject -> head` option.

<https://www.w3schools.com/Css/css_table.asp>
