### ISSUE TITLE
Support for org-mode syntax highlight

### ISSUE THREAD

**Issue by juacq97** [gsantner/markor#496]
#### General information

* **App version: 1.6.2 (47) Play Store** 
* **System: Android 4.4.4** 

#### Description
First of all, great app, it's the best markdown editor on Android by far. 
I wondering the posibilitty of add support for org-mode syntax. I have already read past entries about this format, and there were no plans to add it. That was more than a year ago, I do not know if you have changed your mind, at least I should ask hehe.

While Org-mode has many features, its markup syntax is quite simple and similar to markdown.
![captura-2019-02-03](https://user-images.githubusercontent.com/7623047/52185222-4bd33f00-27da-11e9-87ac-bc4dbdc2aaa1.png)

Will there be a way to reconsider supporting this format? It would be a killer feature that would appeal to all org-mode users that we do not have an application to write comfortably from the smartphone (there are some, but they are oriented to task lists, not to writing).

**Comment by gsantner** [comment]
#182
