### ISSUE TITLE
Setting editor->hide_statusbar does not work in landscape mode

### ISSUE THREAD

**Issue by haeckse** [gsantner/markor#499]
#### General information

* **App version: 1.6.2 (47)** 
* **System: Android 9** 

#### Description

In the editor, the status bar with the formatting buttons hides in portrait mode, but as soon as one rotates the device and enters the landscape view, the status bar shows up

**Comment by gsantner** [comment]
I tried this and can't reproduce the issue, always get no statusbar at editor when the option is enabled. Rotated multiple times, didn't was visible.

**Comment by haeckse** [comment]
That is strange since it is a persistent problem, at least in my phone environment. But since you've decided to close the issue already, I guess we should leave it at that.

**Comment by gsantner** [comment]
Somebody else that this happens for? please comment :D
