### ISSUE TITLE
Closing unchanged documents changes modified date

### ISSUE THREAD

**Issue by vaskas** [gsantner/markor#5]
Hi Gregor,
So great to finally have a maintained Writeily fork - thanks for doing this.

One annoying issue I observed in Writeily and Markor is the fact that the editor always changes the modified date even if the file was left unchanged.

I've been using Syncthing for my notes and this often produced conflicts when syncing semi-regularily.

**Comment by BrainBlasted** [comment]
I've encountered this as well, and it causes some annoyances when managing repositories from my phone.

**Comment by gsantner** [comment]
> Hi Gregor,
> So great to finally have a maintained Writeily fork - thanks for doing this.

np

> One annoying issue I observed in Writeily and Markor is the fact that the editor always changes the modified date even if the file was left unchanged.

I now changed it to save only if title or content was changed. You can pull latest master and try it.
