### ISSUE TITLE
"Notebook" translations are cut in Sardinian, Spanish and Portuguese

### ISSUE THREAD

**Issue by asereze** [gsantner/markor#501]
#### General information

* **App version:** 1.6.2
* **System:** Android 8.1, Xiaomi Redmi Note 4X, LineageOS 15.1

#### Description
The last word from the translations for "Notebook" in Sardinian ("Blocu de notas"), Spanish ("Bloc de notas") and Portuguese ("Bloco de notas") is cut off when the text is highlighted, even if there seems to be enough space for it. I don't know if it would be easy to fix it, otherwise I could just change the Sardinian translation to just "Notas" ("Notes") and the other translators could be contacted for it. I'm creating a new issue because I wasn't sure if I should have commented in #20 or not.

![photo_2019-02-12_18-10-41](https://user-images.githubusercontent.com/11271324/52654067-8e3eff00-2ef1-11e9-9527-26d01c224146.jpg)
![photo_2019-02-12_18-10-43](https://user-images.githubusercontent.com/11271324/52654069-8ed79580-2ef1-11e9-901b-1f54b1f015c7.jpg)

**Comment by gsantner** [comment]
In general, yes translations should be kept short where possible, while it keeps the meaning. Thats not only the case for this string but all.
