### ISSUE TITLE
The string for "Cancel" is missing from Crowdin

### ISSUE THREAD

**Issue by asereze** [gsantner/markor#502]
#### General information

* **App version:** 1.6.2
* **System:** Android 8.1, Xiaomi Redmi Note 4X, LineageOS 15.1

#### Description
The string for "Cancel" is missing from Crowdin and the xml file and I can't translate it. I'm creating a new issue because I wasn't sure if I should have commented in #20 or not and in the Crowdin chat I can't upload images.

![photo_2019-02-12_17-48-42](https://user-images.githubusercontent.com/11271324/52655718-1ffc3b80-2ef5-11e9-82db-60222fd1ff27.jpg)

**Comment by gsantner** [comment]
The generic android cancel is used which should be translated in all languages. Good to know that this is not for all languages the case.
