### ISSUE TITLE
Feature request: make note title optional

### ISSUE THREAD

**Issue by mogarithm** [gsantner/markor#503]
Currently, the user is required to enter a note title before entering the note editor. In order to make the user's note entry quicker (less steps), I suggest making the note title optional. 

Please refer to the similar Markdown note-taking Android app, WriterP, for an example of how to do this. The user is presented a single page with a Title textbox and a Note Text textbox. The title textbox can be left blank, in that case the note is saved with the first line of the note text being used as the title.

This would be a significant improvement over the existing "quick note" functionality.

**Comment by gsantner** [comment]
we already had this and it didnt work well.
markor is file centric not database centric, you alwqys require a name. and random name doesnt make sense.
