### ISSUE TITLE
Be able to check boxes from the markdown preview

### ISSUE THREAD

**Issue by nitrocode** [gsantner/markor#504]
It would be nice to be able to build checkbox lists and be able to tick them on and off using the markdown preview mode.

**Comment by gsantner** [comment]
Thanks for the report. Representation/Preview is and will stay read only.

**Comment by wolfisberg** [comment]
@gsantner is there a specific reasoning behind that decision? Because being able to check boxes from preview mode (without adding any other changes/features) would open the app to a lot more use cases for me and I'm sure for others as well.
