### ISSUE TITLE
Markor switches to display mode as soon as you scroll the formatting bar

### ISSUE THREAD

**Issue by DoctorSubtilis** [gsantner/markor#506]
#### General information

* **App version:** : 1.6.3
* **System:** Android 7

#### Description
Markor switches to display mode as soon as you scroll, in editing mode, the formatting bar.  

downgrade to 1.6.2 solved the problem (but please fix it also in the new release).

**Comment by gsantner** [comment]
Does this update fix it for you?

APK here: https://github.com/gsantner/markor/releases/tag/v1.6.4

**Comment by DoctorSubtilis** [comment]
**Yes**. Thank you!

**Comment by gsantner** [comment]
@DoctorSubtilis 
OK. If you are a F-Droid user, just wait 1-2 days to get the update from there.
