### ISSUE TITLE
Pin files in notebook

### ISSUE THREAD

**Issue by ranebrown** [gsantner/markor#507]
Is there a way to pin specific files to always show at the top instead of using any of the sort options? If not is this a feature that could be added?

Thanks

**Comment by gsantner** [comment]
Currently the easiest option is to create a launcher (desktop) shortcut to get to a document fastest.

**Comment by ranebrown** [comment]
Is that something that can be done within the app? Do you have plans to add pinning functionality?

**Comment by gsantner** [comment]
jep, just look at the Share ---> menu in editor :)

**Comment by ranebrown** [comment]
Cool beans 👍

**Comment by gsantner** [comment]
With the upcoming update there will be a favourite/unfavourite option in toolbar.
You willl be able to navigate to favourites from the folder selection.

You can add both, folders and files to favourities. I.e. you can now have as much "Notebook" folders as you wish.
