### ISSUE TITLE
Markor switches to display mode when selecting text

### ISSUE THREAD

**Issue by rerobins** [gsantner/markor#511]
#### General information

* **App version:**  1.6.4
* **System:** Android 8.0.0

#### Description

Similar to the issue in #506 switches from edit mode to display mode when attempting to select text by long pressing on the first word and sliding to the right to select additional words on the same line.

**Comment by gsantner** [comment]
<https://github.com/gsantner/markor/commit/1e53dd4f9cd613e21bea65e8c8b32762dfc52370>
