### ISSUE TITLE
table of Contents

### ISSUE THREAD

**Issue by 809825706** [gsantner/markor#513]
It's a good feature to generate table of contents automatically, but it is on the top of the file. When redirecting to somewhere in the file, we have to go back to the top for the next redirection. Why not add a button to go to the top or show the table of contents in a small pop-up window.

**Comment by gsantner** [comment]
Hey!

Thanks for your report, but you are asking for "to top" feature, not TOC.

Please create a new one saying to top and please fill out the Issue template that you ser when starting.
Thanks!
