### ISSUE TITLE
View: Back To Top button

### ISSUE THREAD

**Issue by 809825706** [gsantner/markor#514]
#### General information

* **App version:** v1.7.0 google play
* **System:** Android 9.0, redmi 4x, LineageOS

#### Description
It's a good feature to generate table of contents automatically, but it is on the top of the file. When redirecting to somewhere in the file, we have to go back to the top for the next redirection. 

Why not add a button to go to the top or show the table of contents in a small pop-up window.

**Comment by 809825706** [comment]
this requirement is mentioned in #192

**Comment by rici13** [comment]
Hello can I work on this issue?

**Comment by gsantner** [comment]
yes, go for it!

If possible - please don't use libraries, try first to solve it with plain HTML/CSS/JS or webview scroll calls from java.

**Comment by gsantner** [comment]
@rici13 
Thanks!

Please make a pull request as soon as you start, that makes it easier to detect bigger issues and you don't do certain things multiple times :).

**Comment by jakub231** [comment]
Hello, I would like to work on this issue. @gsantner Could you assign it to me?

**Comment by gsantner** [comment]
@jakub231 
No this is done
