### ISSUE TITLE
Feature proposal: Black theme

### ISSUE THREAD

**Issue by ssaavedra** [gsantner/markor#515]
#### General information

* **App version:** 1.6.4
* **System:** Any; AMOLED Displays

#### Description

The dark theme is not black. Phones with AMOLED displays can benefit from reduced battery usage by using black backgrounds instead of grays, since LEDs are completely turned off when black. I propose to add a note blackish theme for better battery on AMOLED devices.

There are some open source apps, such as KDE Connect, NewPipe, Riot.im or Slide which are already doing this.

**Comment by gsantner** [comment]
Thanks for the request, but currently no other themes than Dark/Light are planned! :)

**Comment by ssaavedra** [comment]
For the editing part, I'm already using the "Black or White" scheme, which achieves the purpose; my proposal is just to add the theme to the selection plus settings interfaces. If you would welcome it in the form of a PR, I can try to add that to my list of pending stuff to do myself, but I wanted to know first if this would have good reception.
I wasn't thinking on adding more colors.

Just add some colors like

```
    <color name="darker__background">#ff000000</color>
    <color name="darker__background_2">#424242</color>
    <color name="darker__primary_text">@color/white</color>
    <color name="darker__secondary_text">#9e9e9e</color>
```

and configure the new theme appropriately, if there is any interest in that. I could prepare a PR, but I'm not sure if it would be interesting, given the speed of closing this issue :-)

**Comment by gsantner** [comment]
If you can make a working solution I happily merge.

Across the project everything is a simple if isDarkMode boolean switching between the AppThemes and certain Colors, icons.
