### ISSUE TITLE
Line breaks in rendered markdown

### ISSUE THREAD

**Issue by ranebrown** [gsantner/markor#516]
When writing a markdown document I have line breaks to keep this text width to ~80 columns. The rendered markdown combines these lines and only adds a break if the line ends with 2 spaces.

This does not seem to be the behavior in Markor i.e. a line break in the plain text equals a line break in the rendered markdown.

Is this intentional behavior?

**Comment by gsantner** [comment]
Yes it is. Tried multiple apps/parsers and seems like every does it differently ;). E.g. try <dillinger.io>.

This is enabled at <https://github.com/gsantner/markor/blob/v1.7.1/app/src/main/java/net/gsantner/markor/format/markdown/MarkdownTextConverter.java#L116>

**Comment by ranebrown** [comment]
Thanks for the info. In case you are interested here is a link to the [CommonMark spec](https://spec.commonmark.org/0.12/#hard-line-breaks) on line breaks.

**Comment by jnizniowski** [comment]
Is it possible to give it as an option?
It was quite confusing to discover that my long file with one break per line is presenting as a one-liner. 
Dillinger, as you mentioned, does it as expected: one break equals to `<br>`.

**Comment by gsantner** [comment]
have  to think about it. Theres huge amount of option, not everything needs one.

Well, thats how most markdown specifications work, if you want a new line make one empty line in between or end with two spaces. thats how markdown in most cases is implemented, and so here.

Dillinger does it not according to e.g. commonmark.

**Comment by jnizniowski** [comment]
Oh, I didn't realize that two spaces make a break! That's a game-changer. I have a script in Automate that creates a log file in Markdown, so now I know that I need to add two spaces to make it readable in Markor.

And, of course, you're right that not everything should be an option.

**Comment by gsantner** [comment]
Thanks for feedback, great that it works for you
