### ISSUE TITLE
Make the new L/R swipe feature optional

### ISSUE THREAD

**Issue by ravilov** [gsantner/markor#518]
#### General information

* **App version:** 1.7.0 (54)
* **System:** Android Nougat (7.1)

#### Description
The new L/R swipe feature interferes with scrolling too much. Please make it optional via a checkbox in the settings.

**Comment by gsantner** [comment]
Wait for 1.7.1

**Comment by ravilov** [comment]
Just got 1.7.1, the option is indeed there. Thanks.
