### ISSUE TITLE
Shortcut to folder

### ISSUE THREAD

**Issue by ravilov** [gsantner/markor#519]
#### General information

* **App version:** 1.7.0 (54)
* **System:** Android Nougat (7.1)

#### Description
There is already a way to create a launcher shortcut to open a file. Can we have the same for folders? Just an intent to make Markor show a folder listing just like it does already.

**Comment by nitrocode** [comment]
how to shortcut to specific files?

**Comment by gsantner** [comment]
in the editor -> share button -> launcher
