### ISSUE TITLE
Click on task list from the representation mode (markdown)

### ISSUE THREAD

**Issue by owazae** [gsantner/markor#521]
#### General information

* **App version:** 1.7.2
* **System:** Android 7.1.2

#### Suggestion

I would be great if from the representation mode (markdown), we could press on task list

 * [ ] to do 

To make it appear done or undone

* [x] to do

So that we don't have to edit the file manually.

#### Feedback
It would be great if my file **todo.md** could be considered markdown and not like a text file. It forced me to rename it **_todo.md**

**Comment by gsantner** [comment]
representation mode is and stays read only.
