### ISSUE TITLE
bad display when open an existing markdown file

### ISSUE THREAD

**Issue by madeindjs** [gsantner/markor#522]
![Screenshot_20190319-213604](https://user-images.githubusercontent.com/11815139/54640128-534f5e80-4a8f-11e9-9283-282bae42cb55.jpg)

#### General information

I just openeed my QuickNotes.md and this happend everytime. Thiers is not a big issue becaude when I collpase and open keyboard again the toolbar is correctly positionned. Also, I not know if this related, but I activate the fullscreen mode.

Package: net.gsantner.markor
Version: v1.7.2 (58)
Flavor: Default (release)
Build date: 2019-03-18T06:26Z
ISource: com.google.android.packageinstaller
VCS Hash: 8f80e12878e617a98dcef34e745d6b408c4c233d

**Comment by gsantner** [comment]
Hi thanks for the report!

This may happen on some rare device+keyboard combination. The space between the textaction bar and the keyboard is not from Markor, so nothing I can fix.
I can only suggest  to disable fullscreen there.
