### ISSUE TITLE
File browser: Customization of Filename and description/date format

### ISSUE THREAD

**Issue by ubergeek77** [gsantner/markor#524]
#### General information

* **App version:** 1.7.2 F-Droid
* **System:** Android 9.0

#### Description

I've searched around for this first, but I don't think this is has been requested before.

If you're a heathen like me, you're more used to the non-European date format, where the month comes before the Day (insane, right?) This is just what I'm accustomed to, so for me, this:

03/24/2019

Is easier for me to read at first glance than this:

24/03/2019

Markor doesn't appear to have any settings to change the displayed date of a note on the main screen, and it defaults to the day-month-year display format.

Could an option to switch to the other date format be considered for a future release?

Related feature request/suggestion (please let me know if I should file this as a separate issue):

If a note has a display date that is up to two or so days older than the current date, perhaps the display could show things such as "2 days ago," "Yesterday," or "Today." If it is older than two days old, it would just show the date as normal. I feel like this would be easier to read at a glance, especially if you have a good handful of notes that are not very old.

**Comment by HoWilgh** [comment]
2019/03/24 would be easier for sorting. This is also the ISO version.... please see https://www.iso.org/iso-8601-date-and-time-format.html.

**Comment by gsantner** [comment]
The filesystem/notebook view will be released with fully new layout.
While it won't allow to set format, it will always take  the default for date and time according to the current locale.

E.g. german:

![screenshot-2019-03-28__16-56-36](https://user-images.githubusercontent.com/6735650/55172816-91750e00-5172-11e9-95a1-87be0474e024.png)

**Comment by gsantner** [comment]
The goal on this has changed sligthly. It's now to be able to configure the description line (where currently the date shows up.
With this extended way, the users should be able to configure both, custom date format as well e.g. show filesize. (`%YYYY-%MM-%DD %FS` for example)

**Comment by gsantner** [comment]
Thought on the "blinking filename" to show full filename by horizontal animating filename: Makes sense to do that on-hover or on-selected. However by default no such scrolling, as otherwise everything blinky blinky the whole time and you cannot focus.

**Comment by uheinema** [comment]
Thumbs up.
Or just show it on longpress? Maybe easier.
And Configurations are nice, but tend to implie GUi changes later, and a source of  problems by settimg them wrong.

**Comment by gsantner** [comment]
no setting for that part.
