### ISSUE TITLE
What does the LinkBox function do?

### ISSUE THREAD

**Issue by def0x099** [gsantner/markor#525]
Aside from being a separate page, what does the LinkBox actually do? I can't find a guide on Markor, and there's nothing UI-wise, so I'm scratching my head here.

**Comment by gsantner** [comment]
It's for "Read it later" & bookmarks.
You can directly share links from browser into it ;).

**Comment by def0x099** [comment]
Ahh, thanks. Expect to see a PR on that README later...

**Comment by def0x099** [comment]
@gsantner You can share links to the QuickNote section too. Does having this as a separate function really offer any advantages over using QuickNote?
