### ISSUE TITLE
Feature Request: Add explainers for each page

### ISSUE THREAD

**Issue by def0x099** [gsantner/markor#526]
When a page is opened for the first time (QuickNote, LinkBox etc. I'm not familiar with the rhetoric), it would be great if there was a popup explaining what the page does, especially for more obscure functions like LinkBox, where the name does not reveal the function of the page.

This would stop things like #525.

**Comment by HoWilgh** [comment]
Some explanation should be shown if one long-presses a Tab/Symbol.

**Comment by gsantner** [comment]
The filesystem/notebook view will be released with fully new layout.
While it won't allow to set format, it will always take  the default for date and time according to the current locale.

E.g. german:

![screenshot-2019-03-28__16-56-36](https://user-images.githubusercontent.com/6735650/55172816-91750e00-5172-11e9-95a1-87be0474e024.png)

**Comment by gsantner** [comment]
<https://github.com/gsantner/markor/commit/08475b1079bc3d1e0c3adc9a00ab3df08645c68b>

**Comment by def0x099** [comment]
@gsantner Yeah maybe don't use that arrow bud, use the unicode one
