### ISSUE TITLE
Feature Request: Bundle markdown demo with Markor

### ISSUE THREAD

**Issue by def0x099** [gsantner/markor#527]
![](https://raw.githubusercontent.com/gsantner/markor-metadata-latest/master/en-US/phoneScreenshots/01.png)

This file shows off what Markdown can do. I think this would be useful to get a feel for the syntax without reading a guide (in a hurry?).

**Comment by gsantner** [comment]
planned since long time, #357. but wanted to add a more descriptive example of the syntax though :)
