### ISSUE TITLE
Links to folders show a default file (index) instead?

### ISSUE THREAD

**Issue by fidian** [gsantner/markor#530]
I like to write markdown for websites. My build process converts *.md into *.html, which seems like a fairly consistent feature. In order to make links work, I typically have each page in a separate folder and then I name the files "index.md", which get generated into "index.html". The links in my markdown will link to the folder, and web servers will show the index page when that happens.

Example file structure:

    index.md
    test/index.md

Example file (index.md):

    This is a link to the [test](test/).

Is there a way you would be willing to add an option that would allow links to folders so they pull up a set of default files instead of just a blank screen?

**Comment by gsantner** [comment]
My suggestion is to create a kind of "main" index file in the root of your notebook. From there link folders(or ie indexes) / files.
There will be a small change for this in the next update: all files starting with `index.` will open by default in preview mode.
