### ISSUE TITLE
Text deleted from edited note when switching apps

### ISSUE THREAD

**Issue by jlamoure** [gsantner/markor#531]
#### General information

* **App version:** 1.6.4
* **System:** 7.1.2 LineageOS

#### Description

Editor is open, type out new text into editor. Click on preview mode, or keep in edit mode (same behavior either way). Switch to Firefox to copy text. Switch back to open note, paste. Switch to Firefox again to copy another chunk of text. Switch back to open note, original pasted text is missing from editor or preview mode.

I had no problem with this type of usage previously. It may have started beginning with the release that started opening notes in their own card.

**Comment by gsantner** [comment]
I can't reproduce the problem, also I don't think the window feature is the reason.

Can you please disable the window feature in Markor settings and report back?

**Comment by jlamoure** [comment]
Hi, I disabled the window feature and the bug still occurs. Thanks for getting back to me.

**Comment by jlamoure** [comment]
Some more notes. After having closed the app and some time passed, I was copying a recipe URL and then the recipe into a note, and I had no issues. This bug has been occurring consistently lately so that surprised me. I turned the window feature back on, closed everything, and now it seems I cannot reproduce the bug where before I could not be rid of it. Let me know if you'd like me to try anything else.

**Comment by gsantner** [comment]
Can you upgrade to the latest release? you can find it only at github releases yet

**Comment by jlamoure** [comment]
I upgraded, still not getting the bug anymore. I'll let you know if I do.

**Comment by jlamoure** [comment]
Experienced the bug again. What happened was: create new note, go to firefox and copy url, paste url into note, copy text from page in firefox, return to note and note is empty. I paste the text, go back to copy the url again, and the note is not empty when I return to the note for the third time.
