### ISSUE TITLE
Move finished todo's to the bottom

### ISSUE THREAD

**Issue by TobiasDev** [gsantner/markor#532]
Hello! 

I recently started using the Todo.txt format in Markor for tasks that don't need a reminder. I think it is fantastic how fast it is to add a task into it. However, I was wondering if it would be possible to move finished tasks automatically to the bottom? 
Since I would like to see the tasks I have ahead of me, and the ones that are closed, can just stay at the bottom. 

Personally I wouldn't mind a bit more whitespace between the tasks as well. I think it is hard sometime to see what the next task says since they are so closed together.

**Comment by gsantner** [comment]
For the use case of "moving done stuff away" there is archiving. This is a feature that is common to todo.txt apps (some call it done, others archive).

This action moves away all done stuff to an seperate file, e.g. todo.done.txt.

You can access it by the highlighted textaction:

![screenshot-2019-04-01__12-44-43](https://user-images.githubusercontent.com/6735650/55322190-2b86d000-546b-11e9-800c-c5226f2e6873.png)



![screenshot-2019-04-01__12-42-28](https://user-images.githubusercontent.com/6735650/55322194-2e81c080-546b-11e9-9ded-cd8d727cdcdf.png)
