### ISSUE TITLE
Proposal - Todo.txt to be more list-like

### ISSUE THREAD

**Issue by reaysawa** [gsantner/markor#533]
Benefits for separating each item into it's own UI entity:
- Reorder each item at will without having to copy and paste.
- Filter/group by project, context or priority.

**Comment by reaysawa** [comment]
@gsantner if you think this is out of reach for this app, please let me know. I partially think it is, but since Todo.txt is already supported, I thought there would be room for turning Markor into a really great app for TODOs too.

**Comment by gsantner** [comment]
Hey @reaysawa 

I know, some people other talked about this too.
But keep in mind Markor is a advanced texteditor.

I think there are plenty of tools/apps which have own UI for the apps use case, thats where they are superior. Markor is about all magic with text editing, nothing more nothing less. ;)
