### ISSUE TITLE
Feature Request - Export to Zim-Wiki's markup format

### ISSUE THREAD

**Issue by JoelMon** [gsantner/markor#537]
On the desktop [Zim-Wiki](https://zim-wiki.org/) is awesome. Zim-Wiki also uses a kind of text markup to create it's pages but it's not Markdown. Zim- Wiki is capable of exporting to markdown though.

Would it be possible to have Markor export to the markup format that Zim-Wiki uses so that files can be imported/exported between both programs? I'm not sure how popular this feature would be but I defiantly cast my vote!

**Comment by gsantner** [comment]
#393
