### ISSUE TITLE
Scroll position is being incorrectly remembered when entering subfolder

### ISSUE THREAD

**Issue by JohnVeness** [gsantner/markor#538]
Starting in F-Droid version 1.7.3, when you enter a folder in the Files section, the subfolder that is displayed seems to be inheriting the scroll position of its parent, rather than being scrolled to the top as expected.

**Comment by gsantner** [comment]
Cannot reproduce the issue on latest Version 1.7.4. please wait/try that

**Comment by gsantner** [comment]
Cannot reproduce the issue on latest Version 1.7.4. please wait/try that

**Comment by JohnVeness** [comment]
Still happens for me in 1.7.4 and 1.7.5. Let me know if you want video demo.

**Comment by gsantner** [comment]
would be helpful yes please. gif e.g. is also fine

**Comment by JohnVeness** [comment]
Please see. I open Folder 20, and expect to see the contents of that folder starting at the top, I.e. files 01 onwards. Instead I am scrolled far down in that folder.
![](https://i.imgur.com/icMBXC2.gif)

**Comment by JohnVeness** [comment]
Still occurs in 1.8.0

**Comment by JohnVeness** [comment]
Still occurs in 2.0.2. In addition, i notice that if you scroll down in a subfolder then press Back (which sometimes, but not always, opens the parent folder), the parent folder is also scrolled down more that it was previously. Please can you reopen?

**Comment by JohnVeness** [comment]
Still occurs in 2.1
