### ISSUE TITLE
Add option for line breaks / disable word wrap in editor

### ISSUE THREAD

**Issue by nvllsvm** [gsantner/markor#539]
#### General information

* **App version:** 1.7.3 (F-Droid)
* **System:** Android 9 (OmniROM OnePlus 6T)

#### Description
Add an option to disable word wrap in editor mode. This is particularly helpful when working with formatted tables.

Consider this table - it's cleanly readable in plain text:
```
| Name                      | Next                                        |
| ------------------------- | ------------------------------------------- |
| Software Mixing Explained | https://www.youtube.com/watch?v=HyLQ5hefprE |
| Space Brothers            | Episode 45                                  |
```

However, the wrapping in Markor results in a mess.
![Screenshot_Markor_20190412-000055](https://user-images.githubusercontent.com/6550543/56011584-4b619380-5cb6-11e9-8d5c-e3b848d3ee8f.png)

**Comment by gsantner** [comment]
Will be included in next update
