### ISSUE TITLE
Crash of 1.7.3 on startup

### ISSUE THREAD

**Issue by nuntius35** [gsantner/markor#540]
#### General information

* **App version:** v1.7.3 from F-Droid
* **System:** Android 5.0.2, Modell SM-P900 (a 12'' tablet by Samsung)

#### Description
v1.7.2 works fine, v1.7.3 crashes on startup

#### Log
I/Timeline( 3321): Timeline: Activity_launch_request id:net.gsantner.markor time:5196768
V/ApplicationPolicy( 2910): isApplicationStateBlocked userId 0 pkgname net.gsantner.markor
W/ActivityManager( 2910): NORMAL SET : srcAppInfo.processName = com.sec.android.app.launcher, destAppInfo.processName = net.gsantner.markor
V/ApplicationPolicy( 2910): isApplicationStateBlocked userId 0 pkgname net.gsantner.markor
I/ActivityManager( 2910): Start proc net.gsantner.markor for activity net.gsantner.markor/.activity.MainActivity: pid=10591 uid=10251 gids={50251, 9997, 1028, 1015, 3003} abi=armeabi-v7a
E/Vold    ( 2220): Failed to find mounted volume for /storage/extSdCard/Android/data/net.gsantner.markor/files/
W/ContextImpl(10591): Failed to ensure directory: /storage/extSdCard/Android/data/net.gsantner.markor/files
E/Vold    ( 2220): Failed to find mounted volume for /storage/extSdCard/Android/data/net.gsantner.markor/files/
W/ContextImpl(10591): Failed to ensure directory: /storage/extSdCard/Android/data/net.gsantner.markor/files
E/AndroidRuntime(10591): Process: net.gsantner.markor, PID: 10591
V/ApplicationPolicy( 2910): isApplicationStateBlocked userId 0 pkgname net.gsantner.markor
W/ActivityManager( 2910):   Force finishing activity net.gsantner.markor/.activity.MainActivity
V/ApplicationPolicy( 2910): isApplicationStateBlocked userId 0 pkgname net.gsantner.markor
I/WindowManager( 2910): Screenshot max retries 4 of Token{17a5b666 ActivityRecord{12fe3ec1 u0 net.gsantner.markor/.activity.MainActivity t271 f}} appWin=Window{236b2c3e u0 net.gsantner.markor/net.gsantner.markor.activity.MainActivity} drawState=1
D/CrashAnrDetector( 2910): processName: net.gsantner.markor
D/CrashAnrDetector( 2910): broadcastEvent : net.gsantner.markor data_app_crash
W/ActivityManager( 2910): Activity pause timeout for ActivityRecord{12fe3ec1 u0 net.gsantner.markor/.activity.MainActivity t271 f}
I/WindowState( 2910): WIN DEATH: Window{236b2c3e u0 net.gsantner.markor/net.gsantner.markor.activity.MainActivity}
I/ActivityManager( 2910): Process net.gsantner.markor (pid 10591)(adj 9) has died(254,512)

**Comment by gsantner** [comment]
there is already 1.7.4 released, which fixes this.

**Comment by gsantner** [comment]
I will give you a apk when I'm home.

Would you be willing to give me some feedback, and test 1-3 builds? Testing done on other devices is always helpful.

**Comment by nuntius35** [comment]
> Would you be willing to give me some feedback

I can test them.

**Comment by gsantner** [comment]
@nuntius35 
<https://github.com/gsantner/markor/releases/download/v1.7.4-2/base.apk>

Can you give this a try? Any issues?

Also, if you have a SD card, please check if you can create/delete/edit files there. (You should get a popup at first time). For that check on SD card root folder.

**Comment by nuntius35** [comment]
This version works fine! I see the new introductory slides on the first
start, the rest also seems good. Unfortunately I don't have any SD card
for my device.

Am 13.04.19 um 20:00 schrieb Gregor Santner:
> @nuntius35 
> <https://github.com/gsantner/markor/releases/download/v1.7.4-2/base.apk>
> 
> Can you give this a try? Any issues?
> 
> Also, if you have a SD card, please check if you can create/delete/edit files there. (You should get a popup at first time). For that check on SD card root folder.
> 

-- 
Andreas Geyer-Schulz
gsa@posteo.de

**Comment by gsantner** [comment]
k, thx for feedback
