### ISSUE TITLE
Cannot share text from my browser

### ISSUE THREAD

**Issue by dkuku** [gsantner/markor#541]
#### General information
That's an idea-I wanted to share a link from the browser to markor but it's not on the list. It would be nice to have a possibility to receive shared text from other apps. Trello app allows me to choose a board and a list where it is added. It might be a dialog to choose a file or create new ona and add the text at the bottom.
* **App version:** 
* **System:**

**Comment by gsantner** [comment]
Markor accepts text from browser, actually this is one of the main features. I use that **every day**, after all that's the main case for LinkBox ;).

Which browser do you use?

**Comment by dkuku** [comment]
I tried it in brave browser and must have been blind (or did not scroll the
list :) ) now I see it. Sorry about that.

**Comment by gsantner** [comment]
oh okay, than all good
