### ISSUE TITLE
'Prefer representation' setting doesn't work for To-Do, QuickNote or LinkBox buttons

### ISSUE THREAD

**Issue by firecat53** [gsantner/markor#542]
#### General information

* **App version:**  1.7.3
* **System:** Android 9 (Pixel 3)

#### Description

When the 'Prefer representation' setting is checked, it correctly displays the file representation when clicking file names in the 'Files' tab. However, clicking the 'To-Do', 'QuickNote' or 'LinkBox' tabs opens the associated file in edit mode.

I would expect that clicking those tabs when 'Prefer representation' is selected would open those files in representation mode.

Thanks!

**Comment by gsantner** [comment]
First of all, this setting in general was removed 1-2 versions ago.

Second, the main view is for editing and adding content, they are intentional always in edit mode.

**Comment by firecat53** [comment]
I'm on 1.7.3 - are you saying that Settings->Representation->Prefer Representation is removed in 1.7.4? If so, may I ask why that setting is being removed? It's quite useful!

**Comment by gsantner** [comment]
It may return in a better form later on. Theres lots of rework and new stuff going on currently. removing old bad code makes it possible to get more stable and make the project better.
