### ISSUE TITLE
file browser: hide dotfiles

### ISSUE THREAD

**Issue by Offerel** [gsantner/markor#546]
Could you please add a option l to exclude files/folders, such as hidden files (starting with . ), and optionally files/folders defined by a pattern. 

Markor version 1.7.5

**Comment by gsantner** [comment]
already on my personal list, and to be enabled by default / invisible

**Comment by Offerel** [comment]
I can confirm that dotfiles successfully hide by this setting, but dotfolders not. Could you please extend that for folders to please?

**Comment by heX16** [comment]
![image](https://user-images.githubusercontent.com/3930496/75960963-1cf23580-5ed2-11ea-981e-05bc8f90d739.png)

I can’t find the sequence from which this error appears. But I have encountered her several times already.
