### ISSUE TITLE
[Feature request] Use Storage Access Framework (SAF) for better cloud integration

### ISSUE THREAD

**Issue by Backfighter** [gsantner/markor#547]
#### General information

For api leveles > 19 android supports the storage access framework. 
Which allows to gain long term persistent access to files stored in cloud providers. 
Usage of this system could drastically improve cloud integration for Markor. 

#### Description

As stated in the [documentation](https://developer.android.com/guide/topics/providers/document-provider) the saf supporters read, write, create and delete operations on cloud providers that offer a DocumentProvider. 

Since api level 21 there even exists the [ACTION_OPEN_DOCUMENT_TREE](https://developer.android.com/reference/android/content/Intent.html#ACTION_OPEN_DOCUMENT_TREE) which allows access to a full directory. 
This could be used to select the root folder for notes on a cloud provider and allow for newly created notes to be seamlessly synced. 

Using this system can potentiality solve a lot of the current problems with cloud storage.

**Comment by locuturus** [comment]
I will add to this that I am testing Android 10 and working with SAF and document providers is pretty much the only way you're going to have file system access in Android 10 and up.  There is no more general access to 'real' file path — check out 'scoped storage' for more details.  

If I clear app data, permissions, or reinstall Markor now it will lose its grandfathered legacy storage permissions and the app's built in file browser will only see certain directories under sdcard/Android/* and that's by design now.

**Comment by gsantner** [comment]
I really hope there will be still options to do traditional file access (with `java.File` class). The whole app and libs build around that and I don't plan to fully rewrite everything.

SAF is already in use for mounting sdcard, but beside that I currently don't plan to make use of it.

**Comment by gsantner** [comment]
BTW, scoped storage will be optional in Q at final release. But may be no opt-in in later versions.

https://9to5google.com/2019/04/25/scoped-storage-will-be-optional-beginning-with-android-q-beta-3/

**Comment by mischkl** [comment]
I'm on Android 10 and I'd like to navigate my Dropbox files from Markor. Would this change make this possible?

**Comment by gsantner** [comment]
for your information, I'm running Android 11 and still everything works fine as is - regarding internal storage access. Press accept for permission and thats it.

![screenshot-2020-11-11__21-02-02](https://user-images.githubusercontent.com/6735650/98858653-44d26980-2461-11eb-9ab7-83c551a20cba.png)
