### ISSUE TITLE
Three minor usability enhancements

### ISSUE THREAD

**Issue by aubreyz** [gsantner/markor#551]
#### General information

* **App version:** 1.7.5 (67)
* **System:** Moto g6

#### Description

In order of images
a) The icons for folder versus file are way too close together in appearance. There should be some evident difference in shape or shade or size. If you don't want to use color, I suggest making the file icons half their size, or better still replace with a mini MD TXT Todo

b) Favorites (Star) are nice, but there should be some indication of favorite markings in the main unfiltered file list (perhaps a different color of filename text or similar)

c)  Potentially confusing to have a star in the widget linking to the Linkbox when the star is used in a different context for a different purpose (favorites in menu)

![Untitled](https://user-images.githubusercontent.com/25100168/56865265-e13e3380-69c3-11e9-8379-e7df50c6e55a.jpg)

**Comment by gsantner** [comment]
thanks for feedback, addresse in commit

**Comment by aubreyz** [comment]
Like the fixes - thanks. Still hard to quickly distinguish folder from file though without a careful look (to my eyes anyway)
