### ISSUE TITLE
Wrong date shown below filenames in Files view

### ISSUE THREAD

**Issue by ljb279** [gsantner/markor#552]
#### General information

* **App version: v1.7.6 from F-Droid** 
* **System: Android 7.0** 

#### Description
In the Files (previously: Notebook) view, each filename has a date below.  It would be useful to have the modification date of each file shown, but what is actually shown is the modification date of the parent directory (folder) - the same date for each file.

(Might this be related to #549 "Minor bug - file information" where the name of the parent folder is shown instead of the file name?)

**Comment by gsantner** [comment]
easy to fix

**Comment by gsantner** [comment]
@melkor0 Maybe a easy one for you? :)

**Comment by ljb279** [comment]
Not likely, sir! Java and Android are not at all among my (now-rusty) programming skills. Sorry.
