### ISSUE TITLE
Where did the search function go?

### ISSUE THREAD

**Issue by indeedwatson** [gsantner/markor#554]
I haven't used my phone in a long time, I updated markor recently, and the looking glass at the top bar is gone
![Screenshot_20190502-193312](https://user-images.githubusercontent.com/10749504/57111209-93059900-6d11-11e9-8a9e-c1b81b89f805.png)

**Comment by gsantner** [comment]
Files were completly re-done (as in complete own implementation). Search will return.

**Comment by indeedwatson** [comment]
So the only way would be to use an older version until this is reimplemented? Any ETA? Because this makes the app nearly unusable for me, specially since now every file appears to have the same exact creation date.

**Comment by gsantner** [comment]
#552

**Comment by indeedwatson** [comment]
Alright, the date is really a minor annoyance, any estimated time for the search?

Just to know if I should wait a bit or use an older version.
