### ISSUE TITLE
Preview instead of path

### ISSUE THREAD

**Issue by contrapunctus-1** [gsantner/markor#563]
In the browser view, below each file name, Markor v1.8.0 displays the file path. This seems less useful than its previous behavior of displaying the first few words of the file.

**Comment by gsantner** [comment]
Can you share a screenshot?

On all my devices it shows the modified date, as it should.

**Comment by contrapunctus-1** [comment]
v1.8.0 from F-Droid, on a Nokia 6.1 running Android v9
![Screenshot_20190515-143409](https://user-images.githubusercontent.com/8513118/58118866-64e3ec80-7c1f-11e9-8345-2810532cbc6c.png)

**Comment by contrapunctus-1** [comment]
Bump. I've also observed this on a Samsung Galaxy J7 Prime running Android v8
