### ISSUE TITLE
EXIF rotation tags of images are not honoured in rendered mode

### ISSUE THREAD

**Issue by kodfodrasz** [gsantner/markor#564]
#### General information

When switching to rendered mode of a Markdown document where I inserted a landscape photo from the gallery I noticed that the image orientation was incorrect, as if EXIF rotation metadata were ignored.

* **App version:** 1.8.0 (70) / F-Droid
* **System:** Xiaomi Mi A1 / Android One 9 2019.04.01 bugfix level

#### Description

The image is rotated incorrectly in the web view.

#### Log

 1. I selected insert image from the gallery.
 2. the image was displayed correctly (with the bus standing in the gallery).
 3. the image was inserted into the document (copied)
 4. I press the preview/rendered view mode button
 5. the webview displays it incorrectly (See screenshot. The bus should be displayed upright).

Also checked when image is not being copied (with different image as I experienced hints of caching), result is the same.

Screenshot:

![kép](https://user-images.githubusercontent.com/3705124/57655092-19559100-75d6-11e9-9879-af3f9b401abe.png)

Thanks for your work, I really like the app so far!

**Comment by aubreyz** [comment]
The flag should not be honoured. It is not honoured in HTML, latex, pandoc etc. It is not supposed to be honoured.

**Comment by kodfodrasz** [comment]
Firefox and Chrome do honour the flag when rendering images. It is actually an AndroidWebView limitation as I could find after some research:

https://stackoverflow.com/questions/12137704/adding-local-images-to-webview-doesnt-respect-exif-rotation

**Comment by gsantner** [comment]
@kodfodrasz 
Thanks for looking into. If that's an Android limitation Markor can't fix that.

**Comment by kodfodrasz** [comment]
Where can this problem be reported upstream? It should be fixed in Android then... Is there other way to present html? Telegram for instance loads an embedded default browser of some kind when configured so and clicking on urls (might be bad UX for Markor).

**Comment by gsantner** [comment]
This will need fixes in Android itself and maybe markdown parser library. I'm pretty sure this is already reported and that a report by some user of a small app hardly will change something on it :D^^.

**Comment by kodfodrasz** [comment]
It is not reported, but I'm reporting it now to upstream in the hopes it will be fixed eventually.

The issue is: https://issuetracker.google.com/issues/132751286

**Comment by aubreyz** [comment]
> Firefox and Chrome do honour the flag when rendering images. It is actually an AndroidWebView limitation as I could find after some research:

That is simply not correct. Chrome does auto-rotate pictures based on EXIF data ONLY  if they are displayed directly in a browser tab as the main document, or if they are manually rotated using some snazzy new CSS code. Chrome as a standalone picture viewer is not "HTML". 

Having standard HTML suddenly change to respect camera EXIF rotation tags would break about a zillion web pages going back decades.

**Comment by kodfodrasz** [comment]
> > Firefox and Chrome do honour the flag when rendering images. It is actually an AndroidWebView limitation as I could find after some research:
> 
> That is simply not correct. Chrome does auto-rotate pictures based on EXIF data ONLY if they are displayed directly in a browser tab as the main document, or if they are manually rotated using some snazzy new CSS code. Chrome as a standalone picture viewer is not "HTML".
> 

I have indeed tried that with the picture as the document...

> Having standard HTML suddenly change to respect camera EXIF rotation tags would break about a zillion web pages going back decades.

I beg to differ, this should not cause any compatibility issues in my opinion, if implemented at the right level in the browser.

**Comment by aubreyz** [comment]
Yes, it is implemeneted at the level of supporting  an "image-orientation" CSS property. That has nothing whatsoever to do with browser support in general for rotating images via standard HTML (or Markor support via standard HTML).

I'm out of here.

**Comment by kodfodrasz** [comment]
> Yes, it is implemented at the level of supporting an "image-orientation" CSS property. That has nothing whatsoever to do with browser support in general for rotating images via standard HTML (or Markor support via standard HTML).
>
TIL. Thx.

> Do you have an image orientation CSS property?

I have tried adding the folowing to the generated HTML (via relevant Markor setting), but it did not have any effect on the rendered view.

~~~css
img, picture {
  image-orientation: from-image; 
}
~~~

> I'm out of here.
Thank for your contribution to the discussion.

**Comment by kodfodrasz** [comment]
> Having standard HTML suddenly change to respect camera EXIF rotation tags would break about a zillion web pages going back decades.

Actually now I better understand what you meant that it would be a breaking change, the **webpage** word mislead me, as it would be a breaking change for photo editing applications implemented on the web platform.

I was thinking about pages as documents where I'd expect an image to be displayed as expected, and width and height reported to the underlying layout engine applying CSS rules from the already oriented picture.

**Comment by aubreyz** [comment]
There might well be an issue of having whatever engine Markor uses to render HTML support a CSS rotation property (if supplied). However it has to be a case of the code giving advice as to how to use the tag explicitly, and the browser supporting that advice.

It has been enough of a problem getting browsers to support it to make relying on that support a hazard for web developers. For example in browsers from 2014: only Firefox supported it, Chrome and Safari had big issues, and Opera had no support at all. So a designer could not rely on straight HTML (which is what markdown is generating) and could not really rely on CSS either unless they know exactly what browser (and age of browser) every user would be using. Bear in mind that html rendering has to be backwards compatible -- we would expect a modern browser to reliably render a web page from 1990.

**Comment by gsantner** [comment]
Thanks all for the research!

Markor uses the standard system/Android WebView component and theres no plan to change that. It has that bug and that's it, our project won't fix that.
