### ISSUE TITLE
Strange grey panel appear in pdf export

### ISSUE THREAD

**Issue by timeislove** [gsantner/markor#565]
#### General information

* **App version:** v1.8
* **System:**  android 9

#### Description: no problem with the preview, but there is a strange light grey color panel appear in the pdf export, the strange of all is that the panel started to appear randomly, in one case started on the top of of the first page (like the margin), in other cases it started in later lines of codes.

I may send you a screen capture if you like.

**Comment by gsantner** [comment]
Yes, screenshot/capyure plz

**Comment by timeislove** [comment]
Hello, here you go.Note the grey panel would sometime display in the latter pages(lines) or the doc.RegardsOn 14 May 2019 22:25, Gregor Santner <notifications@github.com> wrote:Yes, screenshot/capyure plz

**Comment by gsantner** [comment]
there is no picture. Hint: Pictures/attachments are not added when replied by mail

**Comment by timeislove** [comment]
Hello, screen capture sent to your mailbox. Pls check.On 17 May 2019 15:39, Gregor Santner <notifications@github.com> wrote:there is no picture. Hint: Pictures/attachments are not added when replied by mail

**Comment by timeislove** [comment]
Hello,Apart from the grey panel display in pdf export that I reported to you, I herewith report one major and serious bug, as I do not know how to post pic in GitHub, I tried to explain it to you via email.The bug is when I select priority for a new item, the previous one item would disappear! I have to undo twice to get them back.Attached the screen capture to show you the sequence! The filename serial numbers are showing the datetime and sec.I am now using v1.8.1 but same happen to 1.8Pls fix it asap as it would get the to-do item deleted shealthily.Regards

**Comment by gsantner** [comment]
PDF/Image export will always use light/white mode starting with next update. Hence this won't happen anymore for sure. #594
