### ISSUE TITLE
Big plus/new file button no longer working

### ISSUE THREAD

**Issue by JonasT** [gsantner/markor#566]
When I'm in the files/notebook view and press the big red plus button, I see the button press animation but nothing actually happens afterwards. I saw the new file dialog some time before so I'm not sure what the issue is, but it's broken now. I installed markor like 2 days ago from f-droid without changing any seting except the notebook folder location, so it's a pretty default install

Device: Gemini PDA x27

OS: Android 8.1 without root, ships with default google apps and play store

Markor version 1.8.0 (installed via f-droid)

**Comment by nehrwert** [comment]
Sometimes I also have that problem. But after a restart of markor it works again.

**Comment by gsantner** [comment]
Cannot reproduce the issue. But doing pull-to-refresh should also do the job
