### ISSUE TITLE
Unable to open file without an extension

### ISSUE THREAD

**Issue by 532910** [gsantner/markor#567]
While it allows to create and edit `None` `Type` files, trying to open it again ask to share it without the possibility to open it.

![image](https://user-images.githubusercontent.com/14617699/58067539-45ed4800-7b96-11e9-9ccd-d28435332990.png)
![image](https://user-images.githubusercontent.com/14617699/58067568-6b7a5180-7b96-11e9-857b-b6352c879bef.png)
![image](https://user-images.githubusercontent.com/14617699/58067543-4d145600-7b96-11e9-8ce9-e993befcac78.png)
![image](https://user-images.githubusercontent.com/14617699/58067547-543b6400-7b96-11e9-8f3c-fbea8c11445f.png)

**Comment by gsantner** [comment]
intended.

**Comment by 532910** [comment]
What intended?

**Comment by gsantner** [comment]
currently txt and md and various other extensions. use the selection box.

**Comment by 532910** [comment]
I don't understand. I've selected `None` from the selection box. How should I open it again?

**Comment by gsantner** [comment]
With the upcoming  v1.8.2 / v1.9.0 update, Markor will ask if you want to open the file with an external app or the editor. The list of options where it asks is limited, but included none, json, xml, py, html and other common stuff.


![screenshot-2019-06-20__15-43-49](https://user-images.githubusercontent.com/6735650/59853957-78d75700-9361-11e9-9d6d-447390335a10.png)
