### ISSUE TITLE
None type files support

### ISSUE THREAD

**Issue by 532910** [gsantner/markor#569]
Please ass support to open files without extension

**Comment by aubreyz** [comment]
This is a repeat of your last question. None is a folder on creation.

**Comment by gsantner** [comment]
With the upcoming  v1.8.2 / v1.9.0 update, Markor will ask if you want to open the file with an external app or the editor. The list of options where it asks is limited, but included none, json, xml, py, html and other common stuff.


![screenshot-2019-06-20__15-43-49](https://user-images.githubusercontent.com/6735650/59853957-78d75700-9361-11e9-9d6d-447390335a10.png)

**Comment by 532910** [comment]
Thank you! Could you say, why it's "Mordor" in your case?

**Comment by gsantner** [comment]
debug/test flavor
