### ISSUE TITLE
Sorting notrs by date is not working

### ISSUE THREAD

**Issue by terxw** [gsantner/markor#571]
#### General information

* **App version:** 
1.8

* **System:** 
android 9

#### Description
Notes are not sorted according to date, first in list are 1 year old notes, oldest are at the bottom, newest in the midle

**Comment by gsantner** [comment]
Check the "reverse" order option ;)

**Comment by terxw** [comment]
Sorry for being unclear, I did try all posibilities and the wrong order persist.
For example:

2018
2018
2017
2019
2019
2017

regardless of the reverse or not reverse order

**Comment by gsantner** [comment]
Are speaking about the modification date or the creation date? Markor is sorting against the modification date.
