### ISSUE TITLE
todo.txt deskop widget

### ISSUE THREAD

**Issue by ranfdev** [gsantner/markor#572]
#### Description
Markor has a nice preview of todo.txt files. Is it possible to show a preview of a todo.txt file inside a widget? This could remove the need to install a separate app to manage todos.

**Comment by gsantner** [comment]
currently the easiest way to do this, is by using the ToDo launcher ;)

**Comment by ranfdev** [comment]
Yes, i could press the ToDo button... but it's a lot more useful to have a widget with the preview on the homescreen, to be able to check the todo list at a glance

**Comment by gsantner** [comment]
#156
