### ISSUE TITLE
Support markdown footnotes

### ISSUE THREAD

**Issue by legends2k** [gsantner/markor#573]
#### General information

* **App version:** 1.8.0
* **System:** Android 8.0.0, OnePlus 3T, Oxygen OS 5.0.8

#### Description
After authoring a markdown in edit mode with footnotes[^1] in its content, switching to the rendered view (pressing the _Representation_ button), doesn't show footnotes formatted by as plain text.

This isn't that big of a deal, but it'd be nice to support it.

Of course, I file this issue without knowing the exact markdown format supported by Markor amongst the plethora of syntax in use in the wild today. If this isn't in the charts, I can completely understand. I'm referring to the [one used by Pandoc](https://pandoc.org/MANUAL.html#footnotes).

[^1]: like this

**Comment by gsantner** [comment]
Please take a look at Markors parser, flexmark, if and how it supports it. Thanks!

**Comment by gsantner** [comment]
Adding parsers' flexmarks footnote extension: <https://github.com/vsch/flexmark-java/wiki/Footnotes-Extension#syntax>

**Comment by legends2k** [comment]
@gsantner Thanks for adding footnotes!
