### ISSUE TITLE
[q] CSS class of bold text?

### ISSUE THREAD

**Issue by hut** [gsantner/markor#579]
#### General information

* **App version:** 1.8.0
* **System:** Any

#### Description

Hi,

I'm trying to style bold text (i.e. the representation of markdown text surrounded in `**double asterisks**`) with a custom CSS, but I can't figure out what CSS selector to use.

For `*italic text*`, styling by the "em"-tag works, but styling the "b" tag has no effect on bold text. I suspect that bold text is actually rendered through a span with a certain class. Any ideas?

**Comment by gsantner** [comment]
https://www.w3schools.com/csSref/pr_font_weight.asp

Example:
```
css:
.boldtext {
  font-weight: bold;
}

html/text:

<p class="boldtext">text</p>
<span class="boldtext">text</span>

or.. directly in style
<span style="font-weight: bold;">text</span>

```

**Comment by hut** [comment]
That's the answer to the inverse question ;)

But I don't want to make text look bold. I want to make bold text (i.e. anything in `**double asterisks**`) look different, and wonder what kind of HTML tag or CSS class markor uses to denote bold text, so I can use the same HTML tag or CSS class in my own style sheet.

**Comment by gsantner** [comment]
`**text**  = <strong>text</strong>`


![Screenshot_20190616-131058_Markor](https://user-images.githubusercontent.com/6735650/59563306-75c62900-9038-11e9-8fdb-81b81a5a3e91.png)

**Comment by hut** [comment]
Ah! Great, thank you!
