### ISSUE TITLE
Incorrect Markdown Formatting

### ISSUE THREAD

**Issue by szinubuntu** [gsantner/markor#580]
#### General information

* **App version:** v1.8.1
* **System:** Android 8.0.0

#### Description

Create a new markdown file with below contents and the formats will not be rendered correctly for bold texts:

```markdown
This is some wrong formatting **bold**text.

This is correct **formatting** .
```

In short: when there is no space after the ending `**` I do expect text to be bold but in the app it's not correctly rendered.

![Screenshot_2019-06-17-18-08-54](https://user-images.githubusercontent.com/7077098/59640079-08df8b80-912b-11e9-9280-e017febfda60.png)

Surprisingly github on mobile seems to have the same issue:

![Screenshot_2019-06-17-18-12-28](https://user-images.githubusercontent.com/7077098/59640271-8905f100-912b-11e9-9e34-34adcbaa9e06.png)

#### System Details

```
Package: net.gsantner.markor
Version: v1.8.1 (71)
Flavor: Gplay (release)
Build date: 2019-05-30T23:25Z
ISource: Google Play Store
VCS Hash: c14fa5619931c6e8f9454e00c1b18aaf86cac40a
```

**Comment by gsantner** [comment]
This is correct/expected behaviour.
