### ISSUE TITLE
Nested outline support in Markdown

### ISSUE THREAD

**Issue by frozencemetery** [gsantner/markor#582]
#### General information

* **App version: v1.8.1 F-droid** 
* **System: Android 8.0.0, Moto G6** 

#### Description

By way of background: markdown has support for nesting bulleted and numbered lists, like so:

1. thing1
    1. subthing1
1. thing2

which can of course be combined with each other.  So:

- p1 - The renderer is aware of this, and renders correctly.  This is good.

- p2 - The editor is kind of aware of this: it will keep the most recent level.  However,  it changes the background color of all text indented more than one level to a light grey.  (I'm using the Dark theme with Markor color scheme; no custom changes.)  This makes the (white) text harder to read, and it's not clear what it's for.  I suspect this not intended; my guess is that it's registering 4+ spaces as the markdown four-spaces-means-code delimiter (#468).

- p3 - Pressing the "bulleted list" button while indented always causes a "- " to be inserted at the *start* of the line (i.e., not at the logical indent), unless already present, at which point it's removed.  Ditto for the "numeric list" button.  This means that the operations are not smart enough to terminate an indented section - one must hit delete until reaching the start of the line.

- p4- Probably related to previous, but the numeric and bulleted buttons stack up on each other.  For instance, pressing the "bulleted list" button followed by the "numeric list" button results in "1. - ", and pressing the "bulleted list" button again results in "- 1. - ".

- p5 - Indentation control is very manual.  For comparison, Google Docs's mobile application has editing buttons to increase and decrease indentation level of the current line in the heirarchy.  Right now in Markor, one has to move the cursor before the delimiter, remove whitespace, and restore position after the delimiter - which is multiple precise touches on a small screen, or manual re-entry of the delimiter.  How this would interact with #336 I have not thought through.

p6 - Resolving the above would make Markor usable for outlining, which I would personally appreciate, and for numeric outlining when pared with #193.  I expect the org-mode folks will also want this capability eventually (#182) - at least, I use layered indents in org on the desktop a lot.

**Comment by gsantner** [comment]
@frozencemetery 
Did some improvements to code highlighter. It won't match anymore now in these cases:
* Inline code highlighter won't match <code>´´´</code> anymore
* Block code highlighter won't match with 4-space indent anymore if the first char is any of [0-9+-*] 

* p2: This is totally highlighting for code. Nothing special to Markor.
* p3-p4: tasks are open. feel free to contribute.
* p5: You also should not that you work with a lightweight editor here, not a big fat cloud office with tons of libs and stuff ;). See other mentioned issues.
* p6: The changes will help you at editing, with better visibility of nested list items

**Comment by frozencemetery** [comment]
Sorry, open where?  I didn't see issues (which is why I filed this).

For p5, I don't personally consider buttons for "insert four spaces at line start" and "delete four spaces at line start" heavyweight.  I'm not a UI expert so I thought it might help to have something to compare to; clearly I was mistaken.

**Comment by gsantner** [comment]
#336 e.g.

A issue with 6 points is not really likely to get resolved, hence it's better to have sep. one.
