### ISSUE TITLE
TextActions: Indent/deindent buttons

### ISSUE THREAD

**Issue by frozencemetery** [gsantner/markor#584]
#### General information

* **App version: v1.8.1 F-droid** 
* **System: Android 8.0.0** 

#### Description

It would be nice to have two buttons, one "indent" which adds four spaces to the start of the line, and one "deindent" which removes four from the start of the line (if they exist).

In addition to nesting lists, this also makes it slightly easier to work with blockquotes.  (This is my attempt to file #582 again, hopefully in a more useful and lightweight form this time.)

Thanks!

**Comment by carlosolimpio** [comment]
Hello, I've made a PR for this issue, could you help to review it? Thanks
