### ISSUE TITLE
Add option to set tab width

### ISSUE THREAD

**Issue by sojusnik** [gsantner/markor#585]
If I intend text with `tab` in a text editor like [gedit](https://wiki.gnome.org/Apps/Gedit) or [zim](https://zim-wiki.org/) in this way:

![grafik](https://user-images.githubusercontent.com/1245718/59978595-52721f80-95de-11e9-9708-81fba88aada5.png)

then markor renders it as if a normal `space` was used in the default view (and only the first line!):

![markor text](https://user-images.githubusercontent.com/1245718/59978803-bbf32d80-95e0-11e9-97ff-54c3fcac085d.png)

and doesn't take them into account at all in the preview:

![markor preview](https://user-images.githubusercontent.com/1245718/59978802-b990d380-95e0-11e9-8853-b7a11fde253c.png)

Can we have an option to show a with `tab` intended text properly, like in the first picture, both in the default view and the preview?

**Comment by gsantner** [comment]
Markdown has no special handling for tab character, it just gets put into html as is. tab in html is just a space.
I don't want to introduce some custom solution which doesnt work in (isnt compatible with) any other Markdown editor/previewer.

As of text editor itself, it may be possible to change size of tabwidth, havr to check that. It's app to the UI to decide how long a tab is. I guess in your case it's 4 spaces.
However for view mode as said tab won't be any differnt to a single space anyway so I think this doesn't make much sense to change.

**Comment by gsantner** [comment]
Markdown has no special handling for tab character, it just gets put into html as is. tab in html is just a space.
I don't want to introduce some custom solution which doesnt work in (isnt compatible with) any other Markdown editor/previewer.

As of text editor itself, it may be possible to change size of tabwidth, havr to check that. It's app to the UI to decide how long a tab is. I guess in your case it's 4 spaces.
However for view mode as said tab won't be any differnt to a single space anyway so I think this doesn't make much sense to change.

**Comment by sojusnik** [comment]
I see, thanks for clarifying! Nevertheless, the tab width option for the text editor is very appreciated.

**Comment by gsantner** [comment]
![grafik](https://user-images.githubusercontent.com/6735650/60332242-ebf65400-9985-11e9-8372-3cb2ae02731f.png)

**Comment by sojusnik** [comment]
Magnificent, thanks!

**Comment by sojusnik** [comment]
Do you plan to make width of the indentation configurable or fix it at 4 spaces? If latter, then I would appreciate 8 spaces, since it's more common.

**Comment by gsantner** [comment]
It will get an settings option, defaulting to 4.
