### ISSUE TITLE
Support for content:// urls

### ISSUE THREAD

**Issue by dElogics** [gsantner/markor#586]
#### General information

* **App version:**  1.82
* **System:**  Pie (Resurrection Remix 7.0.2) on Moto G (2nd gen, 2014) (codename: thea)

#### Description
Apparently newer version of android do not support write permissions when the file is opened using full unix-like URLs even if they've been granted read/write access to SDcard. I'm getting a warning that the file cannot be edited because it's readonly.

So markor must support URLs like content:// which's seems to be the new way in Android (9 at least).

**Comment by gsantner** [comment]
Markor uses SAF for sdcards, not direct file access.

See and mount like shown in blog post. <https://gsantner.net/blog/2019/05/06/markor-v1.8-file-navigation-favourites-markdown-editor.html#improved-sd-card-support>
