### ISSUE TITLE
Add reload button / improve auto-reload

### ISSUE THREAD

**Issue by d3m1gd** [gsantner/markor#587]
#### General information

* **App version:** 1.8.2 (72)
* **System:**  Android

#### Description

I use Markor together with Automate to create notifications from my todo.txt file.
If Automate changes the todo.txt file (to mark an item complete), Markor ignores the change and happily overwrites the file with whatever is inside the buffer right now.

Expected behavior.

Markor monitors open files for changes and offers to reload a file if such change happens. Would be nice to have an option to silently update the buffer to the newest change from filesystem.

This behavior would be nice with sync apps as well, as sync apps overwrite files directly, and don't notify Markor about the change in any way, so it is Markor's job to monitor such changes and act accordingly, updating outdated buffers.

**Comment by gsantner** [comment]
exactly that is implement for the sepedate editor screen. but not for the bottom tabs.

**Comment by d3m1gd** [comment]
i've just tried to create a separate non-tab file with todo.txt format. Issue is still there, Markor doesn't pick up the changes made by other programs. I've tried to change through both Automate and Editor (another editor app from f-droid), with Editor picking up on the Automate's changes and offering to reload the file, while Markor doesn't react at all.

**Comment by gsantner** [comment]
**are changes made while** you have the editor open? Or while you use another app/use tab switcher?

**Comment by d3m1gd** [comment]
so, i open an editor in Markor, open the target file and do some changes, switch to another Editor app, open same file, edit it, save, switch back to Markor - new changes are not picked up by Markor.

Now, to illustrate the point and continue the example, i change the file again in Markor, save it, switch to another Editor, and it immediately offers me to reload the file as it was changed. During the whole thing both editors are in task switcher and point to the same file, and Markor doesn't pick up changes, while the other one does. And that is an expected behavior as i see it
