### ISSUE TITLE
Back button doesn't go back

### ISSUE THREAD

**Issue by indeedwatson** [gsantner/markor#588]
What I mean: I'm in a file, I edit the file. I'm done editing and I press the back button on my phone. Back implies going back to where you were before, like the back arrow in the web browser.

Instead markor goes to the file list, which is super awkward considering there's not even a search bar anymore, so I have to scroll down through hundreds of files to find the file that I just edited.

Another case: I go to view a file. I'm done viewing it and I want to view another file, so I press the back button to go *back* to where I was before: file list. Instead, I get taken to the editor. Why would the back button open the editor?

In case it's not clear, workflow should be:

file list -> note -> editor `[back button]` -> note `[back button]` -> file list

or simply

file list -> note `[back button]` -> file list

**Comment by gsantner** [comment]
When you done editing, and press back you get **back** to file list.

The architecture was always like this:
Choose file -> Edit file -> view file. Pressing back on view goes back to edit. So this is expected behaviour. Won't make changes on this.

**Comment by indeedwatson** [comment]
Hey thanks for responding @gsantner . I'm gonna be annoying and say that I still believe this is both unintuitive and inconsistent and I'm gonna explain both.

>     * [x]  When you done editing, and press back you get **back** to file list.
> 


You're not so much going back, as *jumping* back, back is the same as previous, and the previous screen to the editor was the view (by note I mean viewing the note, semantics). 

If I go to my photos, open an image (viewing the image) and then i click on edit, and when I'm done editing I press back, it goes *back* to the image, not to the gallery view. If I'm looking for a video and I select a video and fullscreen it, if I press back it goes back to the main video view, not to the videos list. I could keep quoting examples but you get the point, I'm only mentioning them because I didn't think this behavior was intentional.

I'm curious if you can cite some examples that follow the logic that you proposed. The only thing I can think of is where I'm typing right now, github has a "write" and "preview" (using on desktop browser), but in this case it's a sub-element of a website (and even then I've lost plenty of comments because I pressed preview and then hit back on the browser instead of switching the little tab).

In mobile UX, when an action takes you to another screen, back will almost always take you to the previous screen. This is why it's unintuitive.

>     * [x]  The architecture is like this:
>       Choose file -> Edit file -> view file. Pressing back on view goes **back** to edit. So this is expected behaviour. Won't make changes on this.

This isn't true, when I select a note, it goes to the note view. I then press back and it goes to the editor. In this case it's not like before when it's "jumping" back but at least it's going in the back direction, in this case it's just not performing a "back" action in any shape or form. This is why it's inconsistent.

Apologies for the wall of text but I wanted to make my case. I use this app a lot so little things like this can get frustrating.

**Comment by gsantner** [comment]
Thanks for more feedback

> when an action takes you to another screen, back will almost always take you to the previous screen

* The view mode is no separate screen/activity. It's only a overlay at the editor. Think of it like a dialog. Pressing back on dialog closes it.
* When the whole view/edit/view/edit/view/edit presses would be reversed by pressing back you would need like 10 presses to get out of the whole. I don't want to move on to such behaviour.

**Comment by gsantner** [comment]
BTW, have you tried the swipe option to hide/show Viewer? See Representation settings. It's the fastest way to quick switch.

**Comment by indeedwatson** [comment]
>The view mode is no separate screen/activity. It's only a overlay at the editor. Think of it like a dialog. Pressing back on dialog closes it.

I understand that's how you see it, but I can't actually think of any examples of that on mobile UX.

The way I see it, the loop wouldn't happen because going into edit/view is like going forward. Think of your browser, if you google something, click a website, click something within that website, press back, go to another link, press back, and back again, you'd end up back at google, you wouldn't reiterate the whole loop.

>Also, it's always Open file -> Editor -> Viewer. The Edit button in Viewer only acts as hide viewer, as back button does too.

I don't follow. I press on a note in the list, and I'm taken view the note, not to edit it. I have to click on the pencil at the top to edit.

>BTW, have you tried the swipe option to hide/show Viewer? See Representation settings. It's the fastest way to quick switch.

I very rarely edit. Most of my editing is done on my computer and synced, and I use the phone to view, but I will give it a try thanks.

**Comment by gsantner** [comment]
> I don't follow. I press on a note in the list, and I'm taken to view the note, not to edit it.

You didn't mention that you have the `start into view` settings option checked. When this is set, view will be swapped with edit in back hierachy in the upcoming update.

**Comment by indeedwatson** [comment]
You know I thought about that and went to the settings looking for that option, but didn't find it. I set up this app long ago so I wasn't sure.

That is good to know, I'll try to get used to using the swipe for switching between edit/view and unlearn the back button to finish editing, I think there's some instinctive impulse that wants to make sure the changes are saved, and since I couldn't find a save button (which now I realize is in the context menu), my impulse was to go back to view mode to "confirm" those changes..
