### ISSUE TITLE
Katex: input inconsistency and possible user-defined macros support

### ISSUE THREAD

**Issue by Color87CEEB** [gsantner/markor#589]
#### General information

* **App version: 1.8.2** 
* **System: Android 9** 

#### Description
There is an inconsistency with how many `\` is needed for Katex functions as shown below:
![Screenshot_20190629-193213-01](https://user-images.githubusercontent.com/37738001/60383823-e5acc880-9aa8-11e9-9153-5262df75c054.jpeg)
![Screenshot_20190629-193222-01](https://user-images.githubusercontent.com/37738001/60383825-e6455f00-9aa8-11e9-9bc3-1ea2f9d9e3f3.jpeg)
By default Katex function only needs one backslash, I just wonder is there any way to fix it. 

Also is it possible for a user to submit their own macros file that Katex can point to and render with? It seems that Katex does allow user to add their own macros (e.g. [Katex.org front page example](https://katex.org/) and documented in [Katex Macros Options](https://katex.org/docs/options.html)). 

Thanks.

**Comment by gsantner** [comment]
Please ask at katex / katex autorenderer
