### ISSUE TITLE
Allow to share text and links into Markor

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#59]
Add support of handling text and link sharing into markor. So if someone has some text selected and presses Share, than Markor should be available with two Options:

* Create new note - Open editor for new file, set content
* Append to existing note - Open filesystemdialog to select an existing file. Do add a newline and the shared text.

Additionally it should be possible to share URLs into Markor (not to open with, but to be able to share into). This kinda allows to make it useable as Read-It-Later ;).

**Comment by gsantner** [comment]
If you need more information ask. This issue is an idea, and about people to start contributing to the project. It has not much information because I pasted many ideas/issues and just let them out at the same time :). If you are interested in working on this, and have questions I can give you more details on this.

Register on https://hacktoberfest.digitalocean.com/, send a PR to fix this and get your t-shirt for free (4 accepted PRs to same or different GitHub repositories needed) :). You have to mention the issue number in the commit/PR (e.g. fix #20 / about #8) Find more hacktober issues from my projects: https://github.com/search?&q=label%3Ahacktoberfest+user%3Agsantner

**Comment by shivtej1505** [comment]
Hi, @gsantner, I would like to work on this issue. Will let you know if I ran into some issue.

**Comment by gsantner** [comment]
@shivtej1505 Theres already an (unfinished) PR open about that: <https://github.com/gsantner/markor/pull/67> . But I don't know wheter it will be updated or not, and if it will match what is needed, so fell free to work too on it
