### ISSUE TITLE
Share files from file browser (multiple)

### ISSUE THREAD

**Issue by esmoak** [gsantner/markor#590]
When selecting multiple files from Markor app and touching the three dot menu, the only option given is "Move."

Can we get a "Share" option added? This could make backing up files easier.

It would be amazing if it had similar share options as the individual files.

Maybe there would be an option to multi-select and then share them to a new combined file? Like select todo.txt and .md files and share/convert them to one combined file if needed.

But, all I'm really requesting is a minimum ability to share multiple documents to Telegram or email.

Thanks for the amazing app.

**Comment by gsantner** [comment]
@esmoak You will find a new share option in the file browser menu in the next update
