### ISSUE TITLE
Once enabled dot file could not be hidden.

### ISSUE THREAD

**Issue by 532910** [gsantner/markor#592]
Once enabled dot file could not be hidden.

* **App version:** 1.8.2
* **System:** lineage-16.0-20190625-microG-oneplus3

![image](https://user-images.githubusercontent.com/14617699/60402128-1c134200-9b94-11e9-98b3-02097bdb348a.png)

**Comment by gsantner** [comment]
Please install 1.8.3+ and report back

**Comment by 532910** [comment]
https://github.com/gsantner/markor/releases/download/v1.8.3/net.gsantner.markor-v75-.1.8.3.-flavorDefault-release.apk
works fine

**Comment by gsantner** [comment]
K
