### ISSUE TITLE
Open plain files silently.

### ISSUE THREAD

**Issue by 532910** [gsantner/markor#593]
I have a lot of text notes without extension and I'm very grateful for adding support to open such files. (#567 #569)

Could you add a settings toggle to open files in markor silently, without asking. Really I'd prefer open files with any extension in markor (that I open by markor).

**Comment by 532910** [comment]
Just updated to 2.0.1 from F-Droid
General -> Always open with this app -> None
but it still asks with wich app to open

**Comment by 532910** [comment]
could you add support for all (.*) files,  please

**Comment by 532910** [comment]
Reopen please.

**Comment by 532910** [comment]
It works. Thank you!

**Comment by gsantner** [comment]
Glad it works :smile:
