### ISSUE TITLE
[Q] Date sort order

### ISSUE THREAD

**Issue by terxw** [gsantner/markor#599]
#### General information

* **App version:** 

1.8.2 fdroid and v76 2.0.0 rc1

* **System:** 

android 9 Onepl
us 6 oxygenOs 9.0.6

#### Description

Cannot sort files by date

When i sort files by date i get mixed sorting order
![Screenshot_20190702-192553](https://user-images.githubusercontent.com/461094/60533285-885e8480-9cff-11e9-9ac5-8ec8cf6c6d4f.jpg)

intended order

![intended order](http://imgur.com/hvUCLVR.jpg)
#### Log

https://pastebin.com/KxYm63hj

**Comment by gsantner** [comment]
I don't see any issue here.  Sort order looks 100% correct to me.

```
24.06.2019
19.04.2019
06.02.2019
25.08.2018
30.06.2018
29.06.2018
12.05.2018
11.05.2018
```

**Comment by terxw** [comment]
Maybe you didnt see my edit with the screenshot with the same folder and same files in totalcommander?

**Comment by gsantner** [comment]
Keep in mind, files are sorted by multiple groups.

* First: Folder (if folder option checked)
* Second: Documents (+folder if folder option not checked)
* Third: Non document files.

**Comment by terxw** [comment]
Adding third screenshot with actual position of the most recent files in markor.

I have two folders and md files only



![](http://imgur.com/R06NmJh.jpg)

**Comment by gsantner** [comment]
Please share the same without the menu overlay. The stuff starting from done.txt looks fine to me.

**Comment by terxw** [comment]
Yes, you were right, sorting is ok, but diferent types of files get sorted in groups, i found somenhtml files in there, after deleting them the sort order of .md files is ok, but it would be better if sorting by date meant only by date 😁
Thank you for your help!

**Comment by terxw** [comment]
Here is my folder file list

[list](https://pastebin.com/8ftkvutV)

**Comment by gsantner** [comment]
thanks, you may delete the file if its sensitive, have it downloaded.
