### ISSUE TITLE
QuickNote label is cut when selecting it

### ISSUE THREAD

**Issue by ema-pe** [gsantner/markor#601]
#### General information

* **App version:** v.1.8.3 (75)
* **System:** LineageOS 14.1 (Android 7.1.2)

#### Description

When I select `QuickNote` section, the label is cut at the middle, maybe because is there not enough space when increasing font size?

There is also another bug shown in the attached video. When I switch to landscape mode, below the file name the full path is shown, then if I go back to portrait mode the path is shown in any case, even if before switching to landscape only edit time is shown.

Video: https://streamable.com/xcbxv

**Comment by gsantner** [comment]
#520
