### ISSUE TITLE
Embedded images are not displayed

### ISSUE THREAD

**Issue by fullcavediver** [gsantner/markor#604]
#### General information

* **App version: 2.0.0 (77)** 
* **System: Android 9.0** 

#### Description

File with embedded images will not load and app will hang. Reference file can be found in the attachement.

Thanks for help.

#### Attachement (please rename back to .md)

[README3.md.txt](https://github.com/gsantner/markor/files/3361510/README3.md.txt)

**Comment by gsantner** [comment]
The issue is the file is really huge, and syntax highlighting will try to match everything. You can try to disable syntax highlighting, or reference to file. 
This is about performance of your device, if your device is not capable to load the file with highlighting than theres not much that can be done at that part.

**Comment by fullcavediver** [comment]
Sorry, but it's not the big file problem. the attached file created with Markdown Monster is bigger and it opens on my smartphone in 2 seconds. Is this a compatibility problem? The first file was converted with pandoc. Please change the status back to open. It is clearly a bug.

Thank you.

[README5.md.txt](https://github.com/gsantner/markor/files/3362391/README5.md.txt)

**Comment by fullcavediver** [comment]
interesting, if I turn off syntax highlighting, it actually works. Thanks for the tip!
Which syntax highlighting is supported in markor?

I created the following reference file:

````javascript
function fancyAlert(arg) {
  if(arg) {
    $.facebox({div:'#foo'})
  }
}
```

```markdown
*This text will be italic*
_This will also be italic_

**This text will be bold**
__This will also be bold__

_You **can** combine them_
```

```markdown
# This is an <h1> tag
## This is an <h2> tag
###### This is an <h6> tag
```
```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>
  <meta charset="utf-8" />
  <meta name="generator" content="pandoc" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
  <meta name="author" content="John MacFarlane" />
  <meta name="dcterms.date" content="2019-04-05" />
  <title>Pandoc User's Guide</title>
  <style>
      code{white-space: pre-wrap;}
      span.smallcaps{font-variant: small-caps;}
      span.underline{text-decoration: underline;}
      div.column{display: inline-block; vertical-align: top; width: 50%;}
  </style>
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
  <![endif]-->
</head>
```
`

but I don't see any difference when I turn on the syntax highlighting. Can you give me an example?

THX

**Comment by gsantner** [comment]
Markdown, todo.txt and plaintext.

Though on plaintext only links (http/s)  are highlighted/reduced in size.

On Markdown its most syntax elements (like bold/italic/headers), and some additional things are available as additional settings option.
In general highlighting is quite expensive, and the bigger/complex the file the harder it gets.
Notice: Syntax highlighting is applied to everything, uses regex for matching.

**Comment by fullcavediver** [comment]
thanks for the explanation.

The function is very important when editing the markdown files. I do not want to turn it off permanently. 

Maybe you can find out why markor works very well with files created with markdown monsters like this one:

```
![][image1]

[image1]: data:image/png;base64,iVBORw0KGgoAAAA...

(...)

![][image2]

[image2]: data:image/jpeg;base64,/9j/4AAQSkZJRg...
```

but not with pandoc like this:
```
![](data:image/png;base64,iVBORw0KGgoAAAA...

(...)

![](data:image/jpeg;base64,/9j/4AAQSkZJRg...
```

Two test files:

[test1.md.txt](https://github.com/gsantner/markor/files/3367316/test1.md.txt)
[test2.md.txt](https://github.com/gsantner/markor/files/3367317/test2.md.txt)
