### ISSUE TITLE
Feature request: External storage read/write

### ISSUE THREAD

**Issue by KAndrsn** [gsantner/markor#605]
#### Description

Enable the use of external storage (removable SD cards).  I want to keep my files on external storage, but the permissions do not allow that choice.

**Comment by gsantner** [comment]
This is available since Markor v1.8.
See <https://gsantner.net/blog/2019/05/06/markor-v1.8-file-navigation-favourites-markdown-editor.html?source=github_issues#improved-sd-card-support>
