### ISSUE TITLE
Links to local images don't work

### ISSUE THREAD

**Issue by ravilov** [gsantner/markor#607]
#### General information
* **App version:** 2.0.1 F-Droid
* **System:** Android 7.1.1 / LineageOS 14

#### Description
Links to local images don't open as an image in Markor or in an external picture viewer (preferrable, used to work this way) but instead open a new blank "document" within Markor (just an awkward blank page).

Example:
```
[test link](../media/image.jpg)
[![test image link](../media/image.jpg)](../media/image.jpg)
```
The URL/path is verified to be correct, it shows just fine as an image within the document.

**Comment by gsantner** [comment]
Please also include full filepath where the md file is, and the picture(s)

**Comment by ravilov** [comment]
MD file is at `/external_sd/docs/markor/misc/test.md` and contains nothing but the text mentioned above. Image is at `/external_sd/docs/markor/media/image.jpg`.

**Comment by gsantner** [comment]
So this is NOT about displaying pictures inside markdown document, but what happens when clicking on the link?

**Comment by ravilov** [comment]
Yes, that is correct. Pictures within the document display just fine.

**Comment by gsantner** [comment]
@ravilov  will be included in next update

**Comment by ravilov** [comment]
2.0.7 just landed and I can confirm this is now fixed. Links to images now open in an external viewer just like they used to. However 2.0.7 also brought [a new issue](#665)... 🙂
