### ISSUE TITLE
Sort todo by date (created||finished)

### ISSUE THREAD

**Issue by esmoak** [gsantner/markor#610]
Adding the ability to sort by date in addition to tag, priority, and category would greatly improve the power of the todo format for things like workout or reading logs.

Related to #211

**Comment by tomdaly** [comment]
Hi @gsantner I think I can complete this enhancement. Shall I assign myself to this issue and develop it?

**Comment by gsantner** [comment]
@tomdaly 
Hey nice thanks!
Let me know when you need some help.

There should be some kind of comparable/comparator, where you need an additional one (see other todo.txt sort stuff in SttCommander
