### ISSUE TITLE
Can't browse thru folders of txt as markdown html

### ISSUE THREAD

**Issue by colcord** [gsantner/markor#612]
#### General information

I have folders of txt files formatted as markdown with links between them. I store them in my Dropbox folders on my phone. I'm used to being able to browse them, jumping between them, then editing one, then jumping back to browsing.

In my other apps, I've been able to say that any file with extension txt is a markdown file. 

I can't see how to do that in this app. I can click the button to declare that the current txt file is a markdown format, then click to preview it then click on a link to the next file, but then I have to press three or four buttons to get to the next file.

Am I missing something?
I've read through the titles of all the open and closed issues. I've read through the wiki and the pinned issues.

I've read through gsantner.net

The app looks good. I like the features. I'm really glad you're hosting it on GitHub. I like the focus on privacy.

* **App version:** 
2.0.1 (78)

* **System:** 
Android 8.1 on Nexus 6P

#### Description

Settings, Prefer Representation is checked.
Folders of.txt files.
Link box file has markdown link to index.txt file in one folder.

Steps to reproduce:
* Open Markor
* Click on linkbox icon on the bottom row.
* Result: see markdown of links.
* Expected: see links that I can click on (since Prefer Representation is clicked)
* Click on preview button at the top row.
* See links and click on one
* Result: see markdown of index page
* Expected: see index page with active links
* (No preview button on top row)
* Click on hamburger menu
* Click on format button
* Click on markdown button
* Expected: to see live links
* Result: see markdown still
* Click on edit button (no preview button)
* Result: see markdown highlighted, and preview button
* Click on preview button
* See live links

**Comment by gsantner** [comment]
Rename files to have .md extension instrad of .txt. Most editors and viewers will automatically switch to markdown when it has this extension. 
Markor opens .txt as non-markdown plaintext.
