### ISSUE TITLE
Vertical scrollbar for editor

### ISSUE THREAD

**Issue by opusforlife2** [gsantner/markor#619]
It's quite tedious to have to keep flicking to scroll up or down a large file. A scrollbar to hold and drag would make text navigation quite convenient.

- Most important is scrollbar in editor. It would be good to have this for the viewer also, but no must have.
- Not a must, but if possible show the scrollbar e.g. 3 seconds after scrolling and auto hide it afterwards. Saves screen width for text if not takes space in horiziontallayout.

**Comment by gsantner** [comment]
Do you expect this only for editor, or also for viewer? Please update your comment with this info.

**Comment by opusforlife2** [comment]
- Good point! It would be good to have this for the viewer also.
- Second option is fine. It doesn't need to be visible all the time.

**Comment by opusforlife2** [comment]
@gsantner I think the scroll bar for the viewer is a must have too.

**Comment by gsantner** [comment]
For priority I see this situation:


Do desktop apps usually have clickable scrollbar:

* PDF/Doc viewer - Yes
* Browser - Yes
* Editor - yes

Do mobile apps usually have clickable scrollbar:

* No
* No
* No


 I don't feel like this is a must have or highest priority todo.

**Comment by opusforlife2** [comment]
If the scrollbar is auto hidden, wouldn't that mitigate the space problem?

**Comment by gsantner** [comment]
Depends, swhen you scroll you cant see the text on the right hand side because scroll overlay will be visible.

**Comment by opusforlife2** [comment]
Well, considering that the user will have their giant thumb on the scroll bar anyway, why should text visibility close to/under the scroll bar be a consideration? Also, the scroll overlay (spanning the whole height) could be highly translucent. Just the scroll bar could be opaque/less translucent.

**Comment by opusforlife2** [comment]
I like how the scroll indicator currently looks. There is no scroll bar at all, just a small rectangle indicating current position. What if this indicator was made wide enough to grab when visible, and there is no scroll bar at all? The height of the scroll indicator can continue hinting at the size of the document like it currently does. This is true for both the viewer and editor.

Also, I looked closely and saw that the text wraps at quite a distance from the right edge of the screen. The scroll indicator/bar would have to be ridiculously thick for it to interfere with the text.

**Comment by Helguli** [comment]
You only need to enable fast scrolling to achieve that, I had the same issue in my app.

**Comment by gsantner** [comment]
@Helguli 
This is for Recycler/ListView only, which we don't have here

**Comment by Helguli** [comment]
@gsantner 
Can I contribute to this project by taking this as a first issue?

**Comment by gsantner** [comment]
@Helguli
Yes you can work on it! 

I'm closing this issue, don't plan to work on it myself. Only want to really include it if it's no change on existing behaviour. As said, other mobile apps don't have such a scrollbar either and I don't feel the need for Markor either.

**Comment by opusforlife2** [comment]
@gsantner As a counter-example, FX File Explorer's inbuilt text viewer does have a scroll bar which works exactly as you've specified in this issue. I can use that to browse my hosts file, for instance.
