### ISSUE TITLE
Disallow renaming to existing file (overwrites target with source content)

### ISSUE THREAD

**Issue by junior291492659** [gsantner/markor#620]
#### General information

* **App version:**  2.0.1
* **System:** Android 6.0 (can be reproduced on an Android emulator 6.0 and a Redmi Note 4X phone )

#### Description
    
  I install the version 2.0.1 and start the app, click the floating button to create a new file named "test1", set the type as "Plain Text", click ok then it get to the "edit" page of "test1.txt" and I set text with "Test1", a file "test1.txt" containing "Test1" is created successfully.
    
  Then I create a new file named "new" again, set the type as "None", click ok then it get to the "edit" page of "new" and I set text with "New", a file "new" containing "New" is created successfully as well.
    
  But then I long click the "new" file, click the "rename" icon in the action bar, and set its name as "test1.txt", click ok and the  previous "test1.txt" is overwritten since its content is "New" instead of "Test1".
    
  I have noticed that there is a hint  written in the dialog when creating a new file or folder, which tells user that files and folders are not overwritten. Indeed, if I set a file name and file type which is the same as one of the existed file, it will get to the "edit" page of the existed file to avoid overwriting. But the scenario I described above is in conflict with this principle. This can be a bug somehow and perhaps a pop-up hint would be helpful.

#### Reproducing video
[https://youtu.be/o-uy-n_RwGY?t=34](https://youtu.be/o-uy-n_RwGY?t=34)

I have reproduced it successfully in the latest version 2.0.2 in the google play.
It would be really appreciated to get your concern on this.

     
## Notes
* Pre state
  * new: "new"
  * test1.txt: "Test1"
* Post state (rename new -> test1.txt)
  * ~~new~~ file deleted
  * test1.txt: "New"

**Comment by gsantner** [comment]
Goals, requires modification of of rename dialog class:
* Validate input, check if input renamed file exists
* In case exists, show red error description in dialog content. Do nothing on click or disable the `ok/rename` button.
* Validate if input filename is valid. (i.e. contains no illegal character)

**Comment by tomdaly** [comment]
Hi @gsantner, I'd like to have a go at adding this enhancement if you can assign me :)

**Comment by gsantner** [comment]
You can always start, I'm happy to review again. thanks

**Comment by tomdaly** [comment]
@gsantner almost completed the fix but need to add a new string "File already exists! Please choose a different filename", can you recommend a good way to translate this new string and add it to each language strings.xml?
Thanks

**Comment by gsantner** [comment]
* Use string ID "file__folder_already_exists_please_use_a_different_name". 
* Goto values/strings.xml and add that text with said ID (see others in that file howto)
* Leave other strings.xml untouched. Translations come from Crowdin
* Change text from "File already..." to "File/Folder already..."
