### ISSUE TITLE
Quick Note does not appear as a destination when sharing selected text

### ISSUE THREAD

**Issue by madalu** [gsantner/markor#622]
#### General information

* **App version:** v2.0.1(78) F-Droid
* **System:** Android 8.1.0

#### Description

When sharing text from the contextual menu in an Android app, Markor does not offer Quick Note as a destination. 

Expected behavior: When highlighting text in an app, selecting "Share" from the contextual menu, and then sharing the text with Markor, one would have the option to send the text to the Quick Note file, since the Quick Note file is a place to deposit snippets of text.

Actual behavior: Instead, there is no option to send to the Quick Note file. Instead, the only options are "To-Do," "Share", "Clipboard," "Calendar," "Select existing document," and "Create new document." The only exception is if one is copying a url via the contextual menu. Markor detects that the item is a URL and then offers both "Link Box" and "Quick Note" as destinations. 

Steps to reproduce: 

- Open Firefox and navigate to example.com
- Share the url from the main menu and share with Markor. Both "Link Box" and "Quick Note" appear as destinations.
- Now, in Firefox, select some text on the page and select "share" in the pop-up contextual menu. Share with Markor. Note that both "Quick Note" is missing. (I would expect "Link Box" to be missing in this instance, since one is not sharing a URL. However, "Quick Note" should be a possible destination.)

Further steps to reproduce:

- Share a file as plain text from within Markor to Markor. Note that the "Quick Note" option appears.
- Select text within a file in Markor and use the pop-up contextual message to share with Markor. Note that the "Quick Note" option does not appear.

**Comment by gsantner** [comment]
Install v2.0.2 where this is not the case.
