### ISSUE TITLE
[FEATURE] Add CSS class to body based on docunent type

### ISSUE THREAD

**Issue by ravilov** [gsantner/markor#634]
#### General information
* **App version:** 2.0.1/fdroid
* **System:** Android 7.1.1 (LineageOS 13)

#### Description
I have some custom CSS styling in place to enhance the appearance of `<pre>` tags in my .md documents. That works very well, however the same styling is then also applied to the entire content of a .txt document. I know all documents get converted to HTML internally so I was wondering if it's possible to simply add a CSS class to the `<body>` tag of that HTML based on the source document type. Something like

`<body class="doctype-md">`
`<body class="doctype-txt">`
`<body class="doctype-todo">`

Etc. And then I can adapt my custom CSS to only apply to certain types of documents.

I think that would be a very clean solution that would not only fix my problem but also make the whole system more versatile and extendable.

**Comment by gsantner** [comment]
theres already `{{ post.text_converter_name }}` in place for that, which you can add anywhere as class. I'm adding that to body too.

**Comment by gsantner** [comment]
With next update you will get e.g. `<body class='format-markdown fileext-txt' onload='onPageLoaded_markor_private();'>`

**Comment by ravilov** [comment]
Awesome, thanks.

**Comment by ravilov** [comment]
Just upgraded to 2.0.3 and I can confirm the new feature works. Although in a bit strange way - for a plain `txt file (not todo.txt) `{{ post.text_converter_name }}` yields `format-markdown fileext-txt`. If I'm reading the source code right it should be `format-plain fileext-txt` but no matter what I do it never says that. I can't customize my CSS based on `fileext-txt` becausr then it will apply to todo.txt documents as well which I don't want. The reported `text_converter_name` of "markdown" does seem correct though - Markor does indeed attempt to parse a plain text file as if it was markdown. So in addition to unexpected `text_converter_name` this ends up breaking the appearance of plain text content as well...

**Comment by gsantner** [comment]
thanks for checkig

**Comment by ravilov** [comment]
Just updated to 2.0.5 from FDroid and now this seems even weirder. Now I'm getting `format-markdown fileext-` for both .txt and .md documents. As if Markor forgot how to extract the file extension. Plus it still tries to parse .txt documents as if they were markdown...

**Comment by gsantner** [comment]
In some minutes you will see a commit here, which will yield these results:

```
<body class='format-todotxt fileext-txt'  todo.txt
<body class='format-markdown fileext-md'  quicknote.md
<body class='format-keyvalue fileext-ini' keyvalue.ini
<body class='format-plain fileext-txt'   something.txt
```

This will be included in next release.

@ravilov

**Comment by ravilov** [comment]
Just updated to 2.0.6 and it seems everything is now working as expected. Thanks!
