### ISSUE TITLE
Write newline to end of file

### ISSUE THREAD

**Issue by PaperMountainStudio** [gsantner/markor#635]
#### General information

* **App version:** 2.0.1
* **System:** Android 9

#### Description
All files should end with newline. It makes it more convenient to read when copying the file to other operating systems.

**Comment by gsantner** [comment]
There is no general rule for this. Markor saves what the user inputs in editor and nothing else. 
What you mean, with operating systems support is about something different, `\r and \n` linefeeds I assime.

**Comment by PaperMountainStudio** [comment]
I mean when you write a file, newline should be the last character.

**Comment by PaperMountainStudio** [comment]
https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

**Comment by PaperMountainStudio** [comment]
Thanks.
