### ISSUE TITLE
File browser: Minor selection issues

### ISSUE THREAD

**Issue by shinmai-rookie** [gsantner/markor#641]
###  General information

- **Android version**: 8.1.0
- **Markor version**: 2.0.4

### First bug

If you select a file and then press the back button without deselecting that file, you go to the previous level in the file system with that file still selected, which means that you cannot enter any folder because you're in select mode and any press just makes that folder selected.

I think the best solution would be to deselect everything when you move to an upper path.

### Second bug
When you move a file to another directory, the file stays selected (in the original location), and you have to manually update the folder for the changes to appear. In fact, you can still choose to move that same file again, though it doesn't actually have any effect.

It probably would be less confusing to deselect all the files that have been moved and update the current folder afterwards.

**Comment by ivenk** [comment]
Hey @gsantner,
i would like to give this a try. Could you point me to a file from where to start off ?

**Comment by gsantner** [comment]
@ivenk 
FilesystemViewer classes. Especially Adapter::unselectAll

**Comment by ivenk** [comment]
Thank you !

**Comment by ivenk** [comment]
Okay,
so i finally had the time and looked at the code. 
I think i found a good fix for the first issue. Currently working on the second one. I will try and submit a PR tomorrow (Wednesday).
