### ISSUE TITLE
Bad links escaping

### ISSUE THREAD

**Issue by aoi-miko** [gsantner/markor#645]
#### General information

* **App version: 2.0.4(81) release F-droid** 
* **System: Android 7.1.1 LineageOS with Bromite WebView** 

#### Description
Files in directories with special chars like "%20", "%2F" break image viewing and relative links functionality.

Steps to reproduce:
Create "Markor%2Ftest" directory in /sdcard
Create "/sdcard/Markor%2Ftest/note1.md", type there "my note 1"
Create "/sdcard/Markor%2Ftest/note2.md", and type there "[note1.md](note1.md)"

Switch to viewer, follow the link: It does not open "/sdcard/Markor%2Ftest/note1.md", it tries to open "/sdcard/Markor/test/note1.md" (%2F is html code for "/")

Why do I need it first of all?
Because nextcloud app follows this naming policy for all appliances installed into subfolder, and there's no way to change it in nextcloud.

As far as I can realize, Markor uses web browser internally for viewer.
So, all links needs be carefully percent-encoded in md-to-html translator.

**Comment by aoi-miko** [comment]
document.location in viewer is wrong: it tells "file:///sdcard/Markor%2Ftest/".

**Comment by aoi-miko** [comment]
If you're experiencing this bug too, just append this code at bottom into Settings->View->Inject (head) 

```<base>
<script>
var newbase = document.baseURI.split("%").join("%25");
document.querySelector("base").setAttribute("href", newbase);
</script>```

**Comment by aoi-miko** [comment]
If you're experiencing this bug too, just append this code at bottom into Settings->View->Inject (head)

`<base>
<script>
var newbase = document.baseURI.split("%").join("%25");
document.querySelector("base").setAttribute("href", newbase);
</script>`

**Comment by aoi-miko** [comment]
If you're experiencing this bug too, just append this code at bottom into Settings->View->Inject (head)

```
<base>
<script>
var newbase = document.baseURI.split("%").join("%25"); document.querySelector("base").setAttribute("href", newbase);
</script>
```

**Comment by gsantner** [comment]
I'm thinking of automatically injecting text if filepath contains said percent.

The reason is, converters do/may convert html escape sequences.

**Comment by gsantner** [comment]
@aoi-miko 
Thanks for your injection code. Markor now adds this automatically in case of percent in filepath for NC/OC.

I also checked and could display images in viewer, as well opening files on click. The reffering  document was outside in documents folder, the two files were laying in my nextcould.

This will be included in next release.

**Comment by aoi-miko** [comment]
@gsantner
Wow.. Thanks a lot!

>Bromite webview.
Oh. I was thought it's a totally fluent drop-in replacement, to typical webview and there wouldn't be any difference.
So, your issue header did its purpose.

Thank you for developing a good android app.

**Comment by gsantner** [comment]
NP!
