### ISSUE TITLE
Markdown relative links with backslash does not work

### ISSUE THREAD

**Issue by artkpv** [gsantner/markor#649]
Hello, thanks for this tool!
#### General information

* **App version:** 2.0.5
* **System:** Redmi 4.x, Android 7.1.2, LIneageOS 14.1

#### Description

Steps:
1/ Create "index.md" and "все/какой-тофайл.md" with this content:
```
[ссылка на страницу](все/какой-тофайл)
```
2/ Result: no links created (no ability to navigate a link)

![Screenshot_20190815-124441](https://user-images.githubusercontent.com/3657998/63087498-05b22180-bf5b-11e9-8640-1837e15bc582.png)

**Comment by gsantner** [comment]
* Please switch to the view mode to get links rendered
* Your file reference is wrong, it says `n..md` but step says only one dot.

**Comment by artkpv** [comment]
@gsantner Thanks for the comment. Here is the update. It does not work if i have spaces in links. Please see screenshots.

![Screenshot_20190815-131607](https://user-images.githubusercontent.com/3657998/63088965-16fd2d00-bf5f-11e9-8810-dbc4e6036161.png)
![Screenshot_20190815-131611](https://user-images.githubusercontent.com/3657998/63088966-1795c380-bf5f-11e9-8c80-4a0a041e3ca4.png)

Text is this:
```

Testing broken links

Latin chars:
[latin chars page link](latin chars page link)

Double brakets:
[[все/страница]]

Braket and paranthesis:
[страница](все/страница)

With .md at end:
[страница](все/страница.md)

With uppercase chars:
[Страница](все/Страница.md)

With uppercase and dots chars:
[Страница с точками](все/Страница.еще.что-то.md)

With spaces:
[Страница с пробелами](все/Страница еще что-то)

```

**Comment by gsantner** [comment]
Spaces are not valid in URLs and in our used Markdown specification. You need to use `%20` instead of spaces in links. 

You can use the file button to let Markor do this all for you in correct manner. Please see GIF :)

![markor-link-spaces](https://user-images.githubusercontent.com/6735650/63089879-e6aa9400-bf48-11e9-87c1-78a1ba1c444f.gif)

**Comment by gsantner** [comment]
Markor's FAQ also mentions this now as this was asked already multiple times :)

See: <https://gsantner.net/project/markor.html?source=github#format-markdown>

**Comment by artkpv** [comment]
Thanks for the details! I see. Though spaces were expected there :(
