### ISSUE TITLE
custom font through import in css

### ISSUE THREAD

**Issue by agmemon10** [gsantner/markor#651]
#### General information

* **App version:** 2.0.6 play store
* **System:** Android 9

#### Description

I am trying to use a custom font family by importing it in the style tags, but can't get it to work. Was wondering if anyone else was able to get something like this to work.

Sample:

<code>

<p style="font-family:'QCF_P028';"> ﮘﮙﮚﮛﮜﮝﮞﮟﮠﮡﮢﮣﮤﮥﮦﮧﮨﮩﮪﮫﮬﮭﮮﮯﮰﮱﯓﯔﯕﯖﯗﯘﯙﯚﯛﯜﯝﯞﯟﯠﯡﯢﯣﯤﯥﯦﯧﯨ </p>

<style>
@font-face {
  font-family: 'QCF_P028';
  src: url('http://downloads.qalamproject.com/fonts/QCF_P028.TTF');
}
</style>

</code>

**Comment by gsantner** [comment]
Please see the example here:

https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face#Examples

**Comment by agmemon10** [comment]
My original post did not post correctly (probably because I was trying to post from mobile). That being said, the method in blog post for custom fonts let's me use the QCF_P028 font in the editor, but I am trying to get Markor to only apply it to certain text in "view" mode (when I tap the eyeball icon).

Attached below is the markdown file for reference (had to attach as a text file, FYI). On my computer's markdown viewer, it [correctly renders as this](https://i.imgur.com/bKk6Tog.png), but in Markor's viewer, [it comes up as this](https://i.imgur.com/7tQxO1Y.png)


[Untitled-2.txt](https://github.com/gsantner/markor/files/3513843/Untitled-2.txt)
