### ISSUE TITLE
Hugo/Notable markdown template

### ISSUE THREAD

**Issue by daniele-athome** [gsantner/markor#652]
I'd like to request adding of a new Markdown template based on [Hugo front matter](https://gohugo.io/content-management/front-matter/), also used by [Notable](https://github.com/notable/notable):

```
---
tags: [tag1, tag2, tag3]
title: Note title
created: '2019-07-29T14:47:15.537Z'
modified: '2019-07-29T14:47:36.296Z'
---

# Note title

Note content
```

Would you be interested in a pull request? I can implement the feature myself. Also since this kind of template needs access to user data, I could also modify `getTemplateContent` (and maybe the UI in the future too to input tags) to work with those. What do you think?

**Comment by gsantner** [comment]
> Would you be interested in a pull request? I can implement the feature myself.

Of course! Thanks for PR! :) :smile: All help is welcome
