### ISSUE TITLE
Text files formatted as markdown

### ISSUE THREAD

**Issue by plroman** [gsantner/markor#654]
* **App version:** 2.0.5 via f-droid

This issue seems related to #650 but with the opposite behavior: my files ending with `.txt` are treated as markdown. I can fix it by manually setting it to plain text, but it reverses back to markdown as soon as I reload the file or the app.

Since this behavior is recent, I looked at the recent commits and found ae2b3b23 that modifies `MarkdownTextConverter.isFileOutOfThisFormat(String)` which seems to be the culprit since it's called by `DocumentIO.loadDocument(...)` which seems to determine the format of the file.

I looked a bit at `MarkdownTextConverter.java` but I can't quickly find the bug and I noticed some code in it that might be outdated now? Is there a reason to keep `EXT_MARKDOWN__TXT`, `EXT_MARKDOWN__TEXT` and both `txt` and `text` in `MD_EXTENSIONS_PATTERN_LIST` since you now enable mardown format for files ending in `.md.txt`?

I can provide a log if you want.

Thanks for your help.

**Comment by gsantner** [comment]
Please update to 2.0.6, fixed already.
