### ISSUE TITLE
View mode for .txt files wrongly assumes markdown formatted

### ISSUE THREAD

**Issue by JohnVeness** [gsantner/markor#658]
I have the setting "Prefer view" ticked, so that when I open files I see the rendered version first and have to click or swipe to enter the editor. This suits my workflow.

However, plain text files are always shown as if they are markdown formatted. For example, lines starting with - have bullet points, and single line breaks are ignored in blocks of text.

Can you have it so that plain text files are rendered as plain text in View mode? Ideally with word wrapping, but otherwise displayed as is, including single line breaks?

**Comment by gsantner** [comment]
Markor Version?

**Comment by JohnVeness** [comment]
Ah, sorry for the noise. This seems to be fixed in 2.0.6.

**Comment by gsantner** [comment]
exactly :)
