### ISSUE TITLE
MD: TOC in edit mode (for nav in edit mode)

### ISSUE THREAD

**Issue by hannanhtang** [gsantner/markor#660]
Hope it can pop up the catalog dialog about the file I opened after I click the title in the top of interface. like this:

<https://github.com/hannanhtang/FileCloud/blob/master/Snipaste_2019-08-24_15-53-38.png>
![img](https://raw.githubusercontent.com/hannanhtang/FileCloud/master/Snipaste_2019-08-24_15-53-38.png)

**Comment by gsantner** [comment]
Closing this as won't fix.

Currently I don't expect this to get into Markor, but it's open for pull requests by community.

**Comment by gsantner** [comment]
Implemented now, see #690
