### ISSUE TITLE
[fixed] SupportMe popup shows all the time

### ISSUE THREAD

**Issue by ravilov** [gsantner/markor#665]
#### General information

* **App version:** 2.0.7 fdroid

* **System:** Android 7

#### Description
Every time I start Markor or return to the file list, the "donate" popup shows up. Used to it would show up occasionally and then not show for a few days at least. Has this been done on purpose to encourage people to donate?

**Comment by gsantner** [comment]
I know, the goal was to reduce the amount which seemed to do the opposite :D. Theres a fix released but fdroid takes some days to build.

Till that, if you want it away you can uninstall and reinstall Markor.

**Comment by OffifialMITX** [comment]
@gsantner: please show it less often
Markor: No, I donßt think I will.

**Comment by gsantner** [comment]
@OffifialMITX Please read again :smile: . This is a temporary issue, fix is there you just need to update when FDroid publishes it.

**Comment by OffifialMITX** [comment]
Oh wait no, it's a failed attempt at memefying the situation.

**Comment by OffifialMITX** [comment]
I did nit mean to directly ask you.

**Comment by ravilov** [comment]
Got 2.0.8 from FDroid, confirmed this has been fixed. 👍
