### ISSUE TITLE
Is there a native way to display equations?

### ISSUE THREAD

**Issue by OffifialMITX** [gsantner/markor#666]
I've been struggling since the beginning of the semester trying to document my maths and physics lessons digitally. So this is the abomination I've come to:
```<style>table {text-align: center;}
.hz {border-bottom: solid;}
.z {border-bottom: solid thin;}
up {position: relative; top: -0.8em; letter-spacing:-0.85em;}
upd {position: relative; top: -0.8em; left: 0.35em; letter-spacing:-0.85em;}
ga, du {position: relative; font-size: small;/* border: 1px solid red; color: green;*/}
ga {bottom: 10px; line-height: 400%;}
tw, thr, ot {position: absolute;}
tw {top: -6px; left: 0px;}
thr {top: 3px; left: 0px;}
du {bottom: 5px; line-height: 300%;}
ot {top: 1px; left: 0px;}</style>

### <table><tr><td rowspan="2">[U]=1</td><td class="hz">kg•<sup>m</sup>/<sub>s²</sub>•m</td></tr><tr><td>C</td></tr></table>

- |<up>→</up>F<sub>G</sub>|=|<up>→</up>F<sub>el</sub>|
- (<du>&nbsp;&nbsp;5<ot>12</ot></du>)= √[5²+12²]= √[25+144]= √169= _13 **LE**_
- (<ga>&nbsp;&nbsp;5<tw>&nbsp;-2</tw><thr>12</thr></ga>)= √[5²(-2)+12²]= √[25+4+144]= √173= _13.152946437966 **LE**_
```

In other words I need to be able to put 2 or 3 strings inline on top of each other, put the arrow (→) on above a string, and write broken strings (numbers). Also something shorter than e.g. `<sub>x</sub>` and a kind of `<s>` that isn't affected by that would be nice as well.

Is there a native way to do this stuff? And if not, any hope for implementation?

**Comment by OffifialMITX** [comment]
Looking at the issue number, it's not a big surprise that this monstrosity summoned satan.

**Comment by gsantner** [comment]
Yes. Markor supports KaTex, can be enabled in settings via Format->Markdown->Math.

Create a file from the markdown-reference.md, it contains a sample of KaTex. Refer to KaTex page to find out more

**Comment by OffifialMITX** [comment]
Ok, thank you :)

**Comment by gsantner** [comment]
![grafik](https://user-images.githubusercontent.com/6735650/64130386-79548b00-cdb1-11e9-9a86-34ea0eb59661.png)

<https://gsantner.net/project/markor.html#can-i-use-markor-in-class-to-write-down-equations-math>

Markor's FAQ now lists support for math
