### ISSUE TITLE
Implement file move/rename/delete for SD card

### ISSUE THREAD

**Issue by riveravaldez** [gsantner/markor#671]
#### General information

* **App version:** 
Package: net.gsantner.markor
Version: v2.0.8 (87)
Flavor: Default (release)
Build date: 2019-08-27T02:25Z
ISource: F-Droid

* **System:**
Android 6.0
Kernel 3.10.49

#### Description

Set the default folder on an SD card.
Everything seems to work fine.
But after select a note, the 'Move' option doesn't appears anymore in the up-right options-menu.
So, can't move/organize the notes within Markor.

**Comment by jakub231** [comment]
Hello, I would like to work on this issue. @gsantner Could you assign it to me?

**Comment by adelobosko** [comment]
seems it fixed by #1333, I have not crashed in the last master branch.

**Comment by gsantner** [comment]
See comment at #603
