### ISSUE TITLE
Copy to clipboard from filebrowser

### ISSUE THREAD

**Issue by moshpirit** [gsantner/markor#672]
#### General information

* **App version:** 2.0.8
* **System:** Android 9

#### Description
I would like to have a quick copy button or gesture to quickly copy the content of the note, since I use Markor as a template for common responses and I have two options now:

1. Open the note → selecting a piece of text → select all → copy
2. Open the note → menu → share → plain text → copy to the clipboard

Something like this would be pretty cool:
1. Select the note → copy (in the menu above) besides favorite, rename, etc

**Comment by wladokacur** [comment]
Hi, i I understand correctly, copy button should be next to old icons (favourites, renames, delete)?

**Comment by gsantner** [comment]
yes thats easiest, so action that is only visible  when one file is selected

**Comment by moshpirit** [comment]
Yes! Thanks a lot for replying! 😊

**Comment by wladokacur** [comment]
Can you set me permission in project?  I want push commit to feature branch but i  got error like in picture,

![error](https://user-images.githubusercontent.com/37113879/66074439-7d62fc80-e559-11e9-9511-72e115cedfd4.png)

**Comment by gsantner** [comment]
You have to push to your own fork! Click fork button at repository and change URL to wlakdokacur/markor

**Comment by gsantner** [comment]
@wladokacur Do you need help? You can join the Markor community and have also chat with me and others there which can help. <https://matrix.to/#/#markor:matrix.org>
