### ISSUE TITLE
Q: Use on B/W only devices

### ISSUE THREAD

**Issue by dov** [gsantner/markor#673]
#### General information

* **App version:** 
Version v2.1.0 (90)

* **System:** 
Onyx NovaPro, Android 6.0..1

#### Description

I tested out Markor on my Android E-ink tablet, and it mostly works fine! But even though I chose the B/W color theme, is the H1 markup colored in a light gray color, that hard to see and read on the screen. I looked for a way of turning off this coloring, but could not find any. So what I'm requesting is for the B/W theme turn off any markup coloring, or at least to make the markup coloring configurable.

**Comment by gsantner** [comment]
Hey @dov 

the editor theme is about normal (non highlighted) text foreground and editor background color. Any syntax highlighting color is not affected.

You can get what you suggested by turning off syntax highlighting in General settings + using B/W editor theme.

**Comment by dov** [comment]
Thanks. Actually I wouldn't mind syntax highlightening, as long as it was done without changing the color. E.g. different fonts, different sizes, font-weight, and slant would be ok. If there was a way of editing the style sheet of the syntax highlightening that would be ideal.
