### ISSUE TITLE
Converted markup always shows body font-weight in bold

### ISSUE THREAD

**Issue by dov** [gsantner/markor#674]
#### General information

* **App version:** 
Version v2.1.0 (90)
* **System:** 
Onyx NovaPro, Android 6.0..1

#### Description

When looking at converted MarkUp, it shows the body text in bold. This happens even though I changed the "head injection" to:

```
<style>
html,body {
  font-family: Roboto Regular;
  font-weight: normal;
}
```

When embedding a bold word through `**bold**` it is shown exactly the same as the surrounding text.

**Comment by gsantner** [comment]
`* { font-weight: bold; }` may resolve the issue for you.

Btw, don't use markup for bold text if you don't want bold. Simple :wink:

**Comment by dov** [comment]
Sorry for not making myself clear enough. I did not expect bold for the body text, and don't want it. I do want it for bold text though... The bug/feature was that it was on, both by default and even after I explicitly tried to turn it off by setting the font-weight.

**Comment by gsantner** [comment]
`**text**` is for "text" in bold. Thats part of Commommark Markdown specification and not a bug.

If you dont want bold, dont use asterisk as is, escape it `\*`, or dont use markdown.

**Comment by dov** [comment]
Again, the problem is that I'm getting bold for non-bold markup (i.e.
default body text), not that I'm getting bold for bold markup.

Currently:

```This is **bold**``` -> ```<b>This is bold</b>```

While | expect:

```This is **bold**``` -> ```This is <b>bold</b>```

This the only problem that I have tried to explain.

**Comment by gsantner** [comment]
@dov 
Thanks for more info.

Then, no I can't reproduce your issue.

![a](https://user-images.githubusercontent.com/6735650/64485777-2a28b300-d214-11e9-9de9-d5560b12fff5.gif)

**Comment by dov** [comment]
Thanks for the gif! I redid the steps on my machine and what I found was that:

* The HTML is indeed correct.
* The rendering of the HTML on my box is apparently wrong.

As I understand that there will be a firmware update of my e-book reader to Android 9 in the near future, I'll leave this issue as is for the time being.

**Comment by gsantner** [comment]
ok so an issue with your device's WebView component :)
