### ISSUE TITLE
Custom File Templates (select, copy file & open it)

### ISSUE THREAD

**Issue by Gregger83** [gsantner/markor#676]
#### General information

* **App**: v2.1.1 (91)
* **OS**: Android 9 

#### Description

Actually the file templates are hard-coded. It would be nice, to be able, to create custom file templates or change the existing ones.

Furthermore it would be nice, to configure the location, where the templates are beeing stored.

#### Log

none

**Comment by macdonaldster** [comment]
I'm going to try to use Texpand to fill in an empty file.

**Comment by madCode** [comment]
I've been using markor to make jekyll blog posts and I would love this feature! A lightweight version of this would be just pointing to any random file to use as a template. Or even being able to open up one of the templates as a markdown file and save it to wherever its stored in the app (presumably as a string).

**Comment by gsantner** [comment]
In the meanwhile, you can always have templates somewhere in a folder, and just use the "import" option from the menu.

**Comment by anishmittal2020** [comment]
@gsantner  From inside Markor file navigation: When we select a folder or a file we only have the option to move it. It would be nice if we could copy and paste any folder or file (as my workflow requires creating a folder that contains the new markdown file, with the same name as the markdown file, and it also contains certain custom resources).

**Comment by madCode** [comment]
@gsantner ah, I didn't realize importing was an option! Love that idea. Thanks :)

**Comment by nikiluk** [comment]
@gsantner Thank you for the great work you're doing both on the technical and on the community side. I reall appreciate the product and I want to say that for me it's more than a MD editor, it's a part of the knowledge management workflow covering my mobile experience and data collection.

Said that, brining customizable templates plus a set of simple placeholders like `{date:FORMAT}`, `{title}`, `#{tag}` or others is needed. Import is great and it works perfectly if you need to do it just once or twice, however, the user who wants to work with a repetitive flow has to always repeat his actions for import multiple times, navigate through folders and make changes after the import.

For example, the following set of user stories will be enabled by customized templates. 

**Scenario 1: Making a quick note**
As a user I want to quickly add a daily note

- GIVEN: I have specified a custom template for a Quick note
- AND, I have set the placeholders to automatically fill in the date for me
- WHEN I press a Quick note button
- THEN The MD QuickNote is generated using the filename and content specified 

**Scenario 2: Bookmarking a website**
As a user I want to be able to bookmark a website from my mobile browser and then come back and easily find my bookmark later.

- GIVEN: I have specified a custom template for bookmarks/"Share to Markor"
- WHEN I Press "Share to Markor" from a mobile browser
- THEN The note's body and a filename is being pre-populated with such elements as `{title}`, `{excerpt}`, `{created_at}`

**Scenario 3: Sharing a picture to a note's library**
As a user I want to make a written note to a picture I've taken

- GIVEN: I have specified a custom template for Sharing image files to Markor
- WHEN I Press "Share to Markor" from a photo viewer
- THEN a copy of the image is created in the `Markor/_resources/` folder
- AND the note's body is populated with the link to the image in the "local" `_resource` folder plus a simple metadata extracted from the image's EXIF data such as _taken_, _location_, etc

**Comment by gsantner** [comment]
I'm well aware people want this, including myself - but expectations on it are very high, and everybody has different demands. So first some middle ground between functionality, fitting for everybody and not being bloat must be found.  
And in any way, especially due the high expectation - that we don't deliver something sub-par 😃 .

**Comment by nikiluk** [comment]
@gsantner it totally makes sense, keeping it "minimal" is important

**Comment by edrex** [comment]
snippets PR is related: #1624 

IMO custom file template MVP needs to support filename as well as content, like the current hardcoded templates. Maybe the first line of the file could be used as the filename?

It might also be worth looking for how other tooling in the "markdown wiki ecosystem" do templating, on the off chance it's possible to define an ad hoc convention that users can share across tools.

**Comment by gsantner** [comment]
I gave my input here <https://github.com/gsantner/markor/pull/1624#issuecomment-1126810379>

Basically, to add the snippets to the list at the "new file" dialog.
