### ISSUE TITLE
"More" tab problem in dark theme sometimes

### ISSUE THREAD

**Issue by JohnVeness** [gsantner/markor#677]
It doesn't happen all the time, and I haven't yet determined a pattern for when it happens, but often the More tab looks like following, when using the dark theme.

![](https://i.imgur.com/rNmu2sM.png)

Changing the theme in the app from light and back to dark, or swiping the app away from the Android recents screen, will fix it temporarily, until it happens again.

Has been happening for a good few versions now. Sorry, not sure when in started.

Happening in v. 2.1.1 from F-Droid.

**Comment by gsantner** [comment]
Do you have Auto theme enabled usually?

**Comment by JohnVeness** [comment]
No, always on Dark

**Comment by iammexan** [comment]
This happens all time whenever I use Markor [v2.1.1(92) on Android 9+] in split screen view and persists when I make it full screen. Came back normal after a relaunch. Also, I'm on always dark mode and I changed the FG colors a little bit.

**Comment by gsantner** [comment]
good hint thanks. that way its always reproduceable for me.
I'm not really using split screen myself didnt know that :D
