### ISSUE TITLE
Settings wording could be improved

### ISSUE THREAD

**Issue by JohnVeness** [gsantner/markor#678]
Here is the first page of Settings. Currently the word General appears twice, as does the word Theme. This can make it confusing if someone was trying to guide another user and told them to look in the General section, or the Theme section.

Also the wording "Editor Settings" under the word "Editor" is rather redundant. Maybe put something like "Font, syntax highlighting etc." instead.

![](https://i.imgur.com/2Y3RXX7.png)

2.1.1 from F-Droid

**Comment by gsantner** [comment]
The bottom options are 2 general options taken out of the general category because they are very important.

for others i will have a look.
