### ISSUE TITLE
Sync position between View and Edit modes

### ISSUE THREAD

**Issue by JohnVeness** [gsantner/markor#679]
I have the setting "Prefer view" ticked, so that when I enter, say, a Markdown file, I get a nice rendered view with a table of contents. I can use the ToC to navigate to a position which might be a long way down the document.

I swipe to enter edit mode, and instead the document will be at the place I was last editing, not the place I was viewing.

Similarly, if I'm in edit mode and make some changes then swipe to view, the view will be at the scroll position when last in view, not where I was just editing.

It would be great if the scroll positions in the two modes could be synchronised somehow. I realise this can be hard with different font sizes, and differences with rendering, but it'd be good if it could at least be vaguely right. Maybe try and match the top line in both modes. Or the middle line. Or, for when moving from Edit to View at least, maybe try to keep the line that had the cursor on it in Edit appear in roughly the same vertical place when switching to View.

Many thanks for considering this. I realise it's hard!

**Comment by gsantner** [comment]
I thought about this too. But it's not that easy, because you dont get what you see. At least converted text line wise

**Comment by gsantner** [comment]
I'm closing this as it's very unlikely to happen.

Markor uses different converters and it's impossible to always know wheres what exactly. And injecting something into webview text is not an option.

**Comment by contrapunctus-1** [comment]
Sorry to hear that, because I find this to be a noticeable hindrance to productivity in Markor. 🙁

**Comment by davebrny** [comment]
on really large documents i would rather it guessed the scroll position and got it close enough vs having to start at the very start each time, but thats just me. i get that it wouldnt seem very professional and people would probably start hounding you about it not being exact

**Comment by gsantner** [comment]
Not much feasable with flexmark.

**Comment by davebrny** [comment]
fair enough, thanks
