### ISSUE TITLE
Allow to disable Chrome Custom Tabs, use other installed browser/app

### ISSUE THREAD

**Issue by mat-ale** [gsantner/markor#686]
#### Description

Hi,

could you please add the possibility to choose whether opening URLs with "Chrome Custom Tabs" feature (currently as default) or with other system apps (by calling the system API to choose the application the user wants to use)?

Thanks

**Comment by gsantner** [comment]
Markor doesnt open URLs in webview.

**Comment by mat-ale** [comment]
I have YouTube URLs e.g.
```
[YouTube url](https://m.youtube.com/watch?v=f4Mc-NYPHaQ)
```
and when I click on it the link opens in-app, without asking to use any other external app

**Comment by gsantner** [comment]
Ah, no thats not internal WebView. It's your browser, using a custom tab (<https://developer.chrome.com/multidevice/android/customtabs>).

You can move on from there to any other app using the menu

![Screenshot_20190924-083103_Fennec_F-Droid](https://user-images.githubusercontent.com/6735650/65486848-d79ef600-dea5-11e9-866d-594022a97373.png)

**Comment by mat-ale** [comment]
Ah ok, nice thanks

**Comment by mat-ale** [comment]
Hi,

would it be possible to add an option to avoid opening URLs in the custom tab and just call the system app selector API in order to directly use my favourite app to open links (e.g. for YouTube links I have the mobile app which I would like to use instead of first see the browser custom tab and then select the option to open with other apps)?

Thank you!

**Comment by gsantner** [comment]
please rename issue according

**Comment by mat-ale** [comment]
@gsantner done! Thank you

**Comment by gsantner** [comment]
When asked, "hey can we add this settings option" I recently think lot about if we **really** need it, or if it's more a bloat for very minor use. I thought about this one today, and I say thats the case here ... as you can anyway use the said button if really needed.
