### ISSUE TITLE
Last two updates from playstore abolishes Quicknote.md contents

### ISSUE THREAD

**Issue by aubreyz** [gsantner/markor#689]
#### General information

* **App version:** Last two updates (2.1.3 (94)
* **System:**  Moto G7

#### Description

The updates remove the existing content in quicknote.md so the content is lost. Not sure if any other files are lost, but at least this one is.

**Comment by gsantner** [comment]
Please check filesystem for the quicknote file. Maybe just your filepath has changed (it follows notebook path by default). 

I'm not aware of any change that would result in quicknote/file clearing. Neither by code nor myself as using it multiple times throughout every day.

**Comment by aubreyz** [comment]
Done a search. No not anywhere else, and all the other files are in their usual place. 

It is not in fact cleared - it is deleted completely on installed (has happened 3 times now, and only to that file) - and any usage via send-to or whatever then starts a new file.

**Comment by aubreyz** [comment]
If you can suggest a way to test in a controlled way, I am happy to do.

**Comment by gsantner** [comment]
Hm I'm usually editing and sharing to quicknote too.
Can you tell me your filepath to quicknote? is it on SD Card?

**Comment by aubreyz** [comment]
No on internal memory  card at /documents/markor/
The thing happens (as far as I can figure out) just on updating version - so right now I have just updated from playstore and there is  no quicknote.md there at all (it was there immediately before update with a fair bit of content). 

Not sure how I can simulate a reinstall easily, but the phenomenon is reproducible for the past few updates. In between updates the file sticks around just fine.... A mystery.

If relevant I do have a widget which has the lightening symbol thing that I think links to the quicknote - but I don't actually use that.

**Comment by aubreyz** [comment]
I have turned off foldersync for this folder in case that is an issue (though the logs do not show any file deletion). I suggest we just leave this issue up for a while and see whether anyone else is experiencing anything similar.

**Comment by gsantner** [comment]
agreeing to let it open for some time.

can you please try the following:

* Write something into QuickNote
* Uninstall Markor
* Reinstall Markor - DONT START IT
* Goto system settings -> Apps -> Markor and give it Storage permission
* Start markor and check if text is still there
* Do all steps again, except System settings one

**Comment by aubreyz** [comment]
I tried a (slightly modified I'm afraid) version of your experiment. The problem is reproducible, and in fact involved the todo.txt file and quicknote as well, although not linkbox (which I think is now handled differently anyway). Steps here with screenshots:

Screenshot before uninstalling - you can see quicknote and todo.txt files

![Screenshot_20190930-132849](https://user-images.githubusercontent.com/25100168/65879762-71741080-e388-11e9-9830-62f05f2b3a3f.png)

Screenshot of folder in sold explorer prior to uninstalling shows
Quicknote 6kb and todo.txt 138 bytes

![Screenshot_20190930-132935](https://user-images.githubusercontent.com/25100168/65879852-a718f980-e388-11e9-955e-bc41b5dc29a7.png)

Then uninstalled and immediately reinstalled. That in itself does nothing to the files which are as before size wise

![Screenshot_20190930-133025](https://user-images.githubusercontent.com/25100168/65879924-cca60300-e388-11e9-9c37-e4da75f0e423.png)

Then loaded Markor, which requested permission to access files. I gave permission. Quicknote contents is now blank. Solid explorer shows that both quicknote and todo.txt are reset to zero size. I did not try to load todo.txt at any point. Linkbox and other files are not changed. 

![Screenshot_20190930-133851](https://user-images.githubusercontent.com/25100168/65880084-1b539d00-e389-11e9-8305-463c1d48daa9.png)

**Comment by gsantner** [comment]
OK thanks for testing, it helps.
Weird that it happens fo you but none else yet (including myself :D).

I have an idea how to fix that. Would you be available to do 1-2 test installations I will provide these days?

**Comment by aubreyz** [comment]
Bit confused by the outcome here? Are we saying from the two commits that this probably fixed the problem and needs testing again by me?

**Comment by gsantner** [comment]
You didn't answer that you want to test.
The fix is contained in next update (versioncode>=95), can be opened in case not working.

**Comment by aubreyz** [comment]
As a matter of interest why is the Fdroid version higher than the playstore one -- which still has this bug. It would seem to be a fairly urgent one to get updated on the playstore seeing it is abolishing user data -- is there some restriction on how the playstore can be updated, even for critical issues?? At the moment folk updating to the existing playstore version will have a problem.

**Comment by gsantner** [comment]
You are wrong, there is no update with this out yet.

**Comment by gsantner** [comment]
https://github.com/gsantner/markor/releases/tag/v2.1.4
