### ISSUE TITLE
MD: View: Colored code syntax highlighting

### ISSUE THREAD

**Issue by 532910** [gsantner/markor#690]
Please add support for syntax highlighting.
For code blocks and for whole code files.

**Comment by gsantner** [comment]
code blocks are too much resource intensive, not planned.

for highlighting you have to be more specific, which exact format you miss..and it needs somebody to implement it.

**Comment by 532910** [comment]
1. All modern text processors highlight syntax without any resources problems. (even nano!)

2. I set `Highlighting delay` for the minimum 50ms for Markdown and todo.txt, but still doesn't see any impact on resources.

3. Leave it for users how to spend their resources.

**Comment by gsantner** [comment]
Feel free to implement it, or find somebody who is willing to implement it.

I happily accept pull requests that implement it in a way that it works without major performance degrade.

<https://hacktoberfest.digitalocean.com/>

**Comment by 532910** [comment]
What is the problem to use Markdown library with code block highlighting support?

**Comment by gsantner** [comment]
So do you mean Editing or viewing converted Markdown?

Viewing Markdown support it.

For editor, show me one open source lightweight library that does it in native android component without web stuff. And supports everything Markor does too. There is none.

**Comment by 532910** [comment]
![image](https://user-images.githubusercontent.com/14617699/65832637-1e8a5280-e2cf-11e9-9e3a-5165a2dcfb9a.png)

vs 

```c
int main()
{
    return 0;
}
```

**Comment by gsantner** [comment]
github=web.

**Comment by gsantner** [comment]
I understand now what your expectation is. I thought it's about edit mode.

For future github issues: Please use and fill out the issue template and include more details, that makes everything a lot easier. Thanks :smile: 

Relevant: `https://github.com/vsch/flexmark-java/issues/183`

**Comment by 532910** [comment]
Really I tried to combine two issues into one:
1. Markdown code block highlighting in view mode as in github for example.
2. Code highlighting in editor mode, like vim for example, that supports a lot of syntax highlights.

**Comment by gsantner** [comment]
Ok than thats an issue too, please have separate ones in such cases. 

In this case, not needed as 2 is wontfix, sorry.

**Comment by gsantner** [comment]
@532910 
![Screenshot_20190930-165152_Mordor](https://user-images.githubusercontent.com/6735650/65890263-1f37ed00-e392-11e9-9a6a-7f550a2df7db.png)
![Screenshot_20190930-165242_Mordor](https://user-images.githubusercontent.com/6735650/65890264-1f37ed00-e392-11e9-8b8c-5a8c4b34927f.png)

**Comment by 532910** [comment]
Thank you!
