### ISSUE TITLE
File size

### ISSUE THREAD

**Issue by 532910** [gsantner/markor#691]
Please add support for file size information.

**Comment by gsantner** [comment]
Thats available!
 
At file browser select a file and open File Info in toolbar.

**Comment by 532910** [comment]
It's very complicated. File size (optionally in line numbers) should be in the line with mdate.

**Comment by 532910** [comment]
![image](https://user-images.githubusercontent.com/14617699/65831606-635cbc00-e2c4-11e9-9ae8-c941bd6d170f.png)

**Comment by gsantner** [comment]
You dont have open what I meant. Open the dialog via toolbar.

**Comment by 532910** [comment]
> You dont have open what I meant.

Once again: it's extremely complicated!

**Comment by gsantner** [comment]
Sorry if it is too **extremely complicated** for you.

![video_2019-09-29_13-33-24](https://user-images.githubusercontent.com/6735650/65831840-043f7d00-e2ad-11e9-8450-7669d5780f53.gif)

**Comment by 532910** [comment]
`Long-press app` -> `press special button` vs `just show file size` is extremely complicated for all normal humans.

**Comment by gsantner** [comment]
For #524 there will be a option to change description line. I'm thinking of an additional `%FS` filesize token (like `%HH`) fits for it.

Than every user can chose on his own.

**Comment by 532910** [comment]
If `description line` is the current line with date, it will be very cool and solve the issue. This also solve issue about date formatting. Could you also include %FL for number of lines.

**Comment by gsantner** [comment]
Yes exactly, the date line.

No %FL is not applicable for performance reason. Like really huge performance reason. To get the value of linecount for each file, each file would need to be read when opening a folder.

**Comment by 532910** [comment]
All my notes takes about 1Mb.
Line number calculation takes about 0.04s on my phone!

**Comment by gsantner** [comment]
Oh so you are a developer and have some Android experience?

Markor really needs some contributors, currently doing this all alone. Feel free to help.

**Comment by 532910** [comment]
> Oh so you are a developer and have some Android experience?

Unfortunately, no.

I've just opened termux, and
```
% cd notes

% du -sh
932K

% time wc -l **/*(.) # only files recursively
wc -l **/*(.)  0.01s user 0.03s system 82% cpu 0.043 total
```

**Comment by gsantner** [comment]
Ah ok.

Expect reading line-by-line in java to be lots of slower than highly optimized native C tools :D
