### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by 532910** [gsantner/markor#704]
Markor shows `TODO` file as `todo.txt` formatted, but doesn't allow to select it as `To-Do` file in `General` settings

**Comment by gsantner** [comment]
with change from yesterday this is not the case anymore, TODO will open as plainteext

**Comment by gsantner** [comment]
[Commit #d158275 at gsantner/markor](https://github.com/gsantner/markor/commit/d158275062d08d2708fb55fb354ebead4c6f36e4)  - #700

**Comment by 532910** [comment]
2.1.3 still opens `TODO` as `todo.txt` formatted

**Comment by gsantner** [comment]
There is no update out with this change yet.
