### ISSUE TITLE
MD: Math: Theme KaTex according to Light/Dark app setting

### ISSUE THREAD

**Issue by 532910** [gsantner/markor#706]
Black is invisible on dark gray:

![IMG_20191001_062953](https://user-images.githubusercontent.com/14617699/65932126-07ee1380-e415-11e9-97ec-56a1473218b4.jpg)

**Comment by gsantner** [comment]
I dont feel like its too much an issue.

Styling should also be possible with custom CSS if needed.

**Comment by 532910** [comment]
It's the bug definitely:

![image](https://user-images.githubusercontent.com/14617699/65962464-680aa700-e461-11e9-92a5-1c20b0267a9a.png)

**Comment by gsantner** [comment]
To be honest, the dark one looks better to me, less distracting on night.

Nevertheless, it's something simply not themed. No major bug, quite minor theming issue.

**Comment by 532910** [comment]
The dark theme is definitely better as it produces less photons that burns out eyes. The white theme is the same as to look at the sun.

But the border must be visible. And yes, this is not a major bug.

**Comment by gsantner** [comment]
For contributors:
Check AppSettings::isDarkThemeEnabled to decide on the color/theme.

![grafik](https://user-images.githubusercontent.com/6735650/66395121-2ed4b880-e9c6-11e9-8228-bea93e243f1b.png)

![grafik](https://user-images.githubusercontent.com/6735650/66395129-34ca9980-e9c6-11e9-9141-e8f664eae261.png)

**Comment by 532910** [comment]
Works fine now, is it were fixed?

![image](https://user-images.githubusercontent.com/14617699/66697651-5edecd00-ece0-11e9-9bab-ef1a94382939.png)

**Comment by gsantner** [comment]
Not by Markor at least, may be due updated KaTex libs
