### ISSUE TITLE
Loosing changes when forgetting to save

### ISSUE THREAD

**Issue by hamoid** [gsantner/markor#708]
#### General information

* **App version:**  92
* **System:** Android 7.1.2, Moto E 2nd gen, LineageOS

#### Description

There is something I do on my phone that makes me loose changes to texts in Markor. Maybe I'm doing something wrong, but I think it should not be possible to loose data. I take important notes like contact information or things to do, which I've lost already in 4 occasions during the last year, with different versions of Markor.

I think what I do is closing the program forgetting to tap Save. I click the left arrow on the bottom on the screen and it asks if I want to close the app and I say Sure. Then I realize I've lost my changes again. The previously saved versions of the texts are there, but not anything I typed after the last save.

Could the app maybe offer saving automatically, for instance 5 seconds after the last character was entered?

**Comment by gsantner** [comment]
do you swipe out apps from drawer?

**Comment by hamoid** [comment]
I'm not so versed in the Android terminology. What does it mean "swipe out apps from drawer"?

I can't really reproduce it, but I'm sure it happens. 

I only use the bottom-left (a triangle, hides keyboard, second tap to exit) and bottom-center (a circle, takes you to the "desktop") buttons. But I can't say yet which sequence and what timing produces this. 

I just repeated a bunch of time editing a file and pressing those two buttons but could not reproduce the problem. 

When it happens I was not doing something extremely fast. This weekend I wrote down an e-mail, showed it to the person to make sure it was correct. Today the e-mail was no longer there (luckily I could ask someone else).

Sorry for not providing reproducible steps. I'll keep trying.

**Comment by gsantner** [comment]
OK so sounds not you swipe it out. That is the bottom square button with removing markor from task switcher.

Sorry that it happened to you, but may be not too easy to fix (except doing periodically save for example).

One more question, do you edit on a SD card?

**Comment by hamoid** [comment]
I'll try to remember to tap save :) It would be easier to remember if the button was visible, but I know there's no more space. What about swapping the search and the save icons? Maybe other users don't like it?

At the top of the file list it says /storage/emulated/0. Is that the sdcard? I used to develop Android looong time ago, forgot it all :)

Thanks for creating FLOSS apps!

**Comment by gsantner** [comment]
> I'll try to remember to tap save

No I basically dont want anybody including me to think about saving. That results always in - type 10 words, press save, type 19 words, save, .... - thats what I dont want.

no thats usually the internal storage just with a separate partition basically. SD card is usually at /storage/ABCD-1234

**Comment by aubreyz** [comment]
This issue has me confused -- where is a save button? I don't see such a thing at all....

**Comment by gsantner** [comment]
@aubreyz 
It's in the top-toolbar in the overflow. But don't mind it. I don't want users to manually save.

**Comment by aubreyz** [comment]
Ahh I see it now. Thank you. I suppose that would be useful if one has just made a critical change - would it be the case that if say the phone crashed or battery ran out before one has backed out or closed a document those changes would be lost?

**Comment by gsantner** [comment]
If you expect your phone to shutdown in some seconds I suggest to save yes.
