### ISSUE TITLE
QuickNote launcher shortcut not opens file

### ISSUE THREAD

**Issue by vojtapolasek** [gsantner/markor#710]
#### General information

* **App version:**
2.1.2-92 from F-Droid

* **System:**
Android 8.1, Blackberry Keyone

#### Description

When I add a shortcut to "quick note" to my home screen, after clicking it the quick note file does not open. Only thing I see is notification saying "can't open the application".
The file can be normally opened and edited from within the app.

**Comment by gsantner** [comment]
Do you have granted write permission?

**Comment by gsantner** [comment]
@vojtapolasek 
Android debug log would help here very much to analyze the issue.

Can you please provide a [logfile](https://gsantner.net/blog/2018/03/19/android-contribution-guide.html?packageid=net.gsantner.markor&project=markor&web=https://github.com/gsantner/markor#providing-logs-to-developers-logcat) to me? Do you have a computer available to make it?
