### ISSUE TITLE
Feature: Presentations / Slides

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#712]
#### General information

* **App version:**  v2.2
* **System:**  9

#### Description
* The goal is to add functionality to Markor for creating presentations(/slides).
* Lightweightness and low amount of dependencies is the biggest goal. Massive amount of functionalities, very fancy themes or any animations are not a goal of this.
* Preffered is a solution that is also printable, as such not content created by javascript/dynamic at webview.
* Markdown and combinations of js/css however is not forbidden, or HTML only.
* New format is also an option, as long its plaintext
* Start with some googling whats possible and available and post ideas/suggestions here for discussion vefore starting to implement at Markor

**Comment by cl0ne** [comment]
I found [gist](https://gist.github.com/johnloy/27dd124ad40e210e91c70dd1c24ac8c8) with list of similar tools

**Comment by gsantner** [comment]
@cl0ne 
Collecting ressources is for sure a good first idea, thanks for link :D.

From what I've found there, revealjs seems to be quite bloated, and most others specific to frameworks. Except, [Remark](https://github.com/gnab/remark) seems to have a more simplicistic approach so a potential candidate :smile: .

**Comment by gsantner** [comment]
Hacked this together over the weekend. More details on a upcoming blog post :D.
To biggest extend pure CSS :smile: 

![video](https://gsantner.net/assets/blog/img/markor/markor-presentation-v1.gif)
