### ISSUE TITLE
Todo/Editor: Move current/selected line(s) up and down via button

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [gsantner/markor#715]
### Description

Hi, I think it would be a great addition to this wonderful app to add two buttons in markdown and todo mode : each would move the current line up or down. A bit like *:m-2* and *:m+1* in vim.

This is IMO something missing in this note app : ability to organize the order of the notes.

What do you think ?

Anyway thanks a lot for this app :)

**Comment by gsantner** [comment]
I think this not only for todo.txt but in general is a nice to have, to be able to move current line/selected lines around. But yeah, primary use case is todo.

Implementation: See CommonTextActions, lets have new "move line up/down" actions there.

**Comment by Delko97** [comment]
Hello, i would like to do this issues. Can i assign it ?

**Comment by gsantner** [comment]
@Delko97  
Thanks, sure go for it!

**Comment by gsantner** [comment]
@Delko97
Thanks, sure go for it!

Please make a pull request as soon as you start, that makes it easier to detect bigger issues and you don't do certain things multiple times :).

**Comment by aleksfadini** [comment]
Agreed would be a great feature to have.

**Comment by gsantner** [comment]
@aleksfadini 
If you want you can also start on this issue (or somebody else looking to this comment). 
It happens to be often that somebody commented that he wants to start but then nothing happens :smile: . (Thats why asking for pull request).

**Comment by Delko97** [comment]
@gsantner heh don't worry i want to finish this issue, just went on unexpected holiday... :D will make pull request tommorow when I come back....

**Comment by thiswillbeyourgithub** [comment]
Hi, I don't really understand. I updated markor yesterday on F Droid and this seems to be mentionned in the changelog, however I don't understand how to move the lines. Has it not been added or am I just missing something ?

Anyway thanks a lot :)

**Comment by gsantner** [comment]
The option is in the "keyboard" button dialog. (bottom bar)

**Comment by thiswillbeyourgithub** [comment]
Hi,
I think there has been an issue.

Let's take the following example : `
- A
- B
`
let's click `move line down` while having the cursor on A

Your fix appears to move the context of line A at the end of line B whereas what I asked was putting A at B and B at A, so as to end up with : `
- B
- A`

Am I correct ?
