### ISSUE TITLE
go back to the notes folder from favourites/recents

### ISSUE THREAD

**Issue by 532910** [gsantner/markor#717]
With the new feature "Long click on main view plus button -> open favourites/recents" it's impossible to go back to the notes folder.

Steps to reproduce:
1. Open markor (it will show notes folder)
2. Long press on `+` button (it will show favourites/recents)
3. Now, to go to the notes folder you need to restart the app, or select it via file navigation (that's extremely hard), or via `folder` button

Solutions:
1. Long press on `+` button should switch in loop: `notes` -> `recents` -> `favourites` and not just `recents` -> `favourites` as now
2. System back button should move you `back` and not to `storage` as now.

**Comment by gsantner** [comment]
Use Toolbar (folder icon) -> Notebook option. There are lots of other options as well.

Back button for filebrowser is only planned for "go up" for Markor, don't want to change that.

![Screenshot_20191004-201228_Mordor](https://user-images.githubusercontent.com/6735650/66229958-97741a80-e6d2-11e9-9a40-b8f3a79547dc.png)

**Comment by 532910** [comment]
As I said, the Toolbar (folder icon) work, but it's very unintuitive. OK, leave back as you wish. But please, add `notes` in the long press `+` button loop.

**Comment by gsantner** [comment]
When clicking `+` shortly starting with next update, markor will open notebook folder.
