### ISSUE TITLE
strage folders in the / view

### ISSUE THREAD

**Issue by 532910** [gsantner/markor#718]
Markor 2.1.3, LineageOS 16.0 with microG, OP3T

Why `self` and `emulated` are strikeout? What is `emulated-0`?

![image](https://user-images.githubusercontent.com/14617699/66230012-de223e80-e6eb-11e9-8c0e-8bab9b8ae305.png)

**Comment by gsantner** [comment]
/storage/emulated and /storage/self are not acceissble.

emulated-0 is a virtual remap to /storage/emulated/0 which is accessible.

**Comment by 532910** [comment]
> /storage/emulated and /storage/self are not readable

It's wrong! It shows `self` as empty and in the `emulated` it shows `0` (in which it shows my storage)

**Comment by gsantner** [comment]
For self it shows empty because Markor is not able to read it's structure.

> and in the emulated it shows 0 (in which it shows my storage)

This one is virtual as well.  /storage/emulated/ cannot be browsed without root.


![Screenshot_20191004-202558_Termux](https://user-images.githubusercontent.com/6735650/66230792-76142e00-e6d4-11e9-9468-39fd9996dce1.png)

**Comment by 532910** [comment]
While termux shows the same result for me, markor shows `0` in `emulated`.

Anyway, I understand why it looks so, but it's very confusing for ordinary user.
To be clear it should look so:
1. do not show unreadable folders at all
2. show `emulated-0` as storage
3. show `appdata-public (emulated)` as just `appdata-public`

**Comment by gsantner** [comment]
The `(   )` is added to recognize whether or not it's internal-emulated storage or from SD-Card. note C151 below:

![Screenshot_20191004-204225_Mordor](https://user-images.githubusercontent.com/6735650/66231744-c1c7d700-e6d6-11e9-8351-bee36dac146c.png)
