### ISSUE TITLE
Create links in preview for pages with hyphens

### ISSUE THREAD

**Issue by rhnvrm** [gsantner/markor#719]
#### General information

* **App version:** 2.1.4
* **System:** Android 

#### Description
For example, if I have dates with hyphens as file names, I am unable to link to those in the preview.

![photo6105125282475256069](https://user-images.githubusercontent.com/952036/66241994-1f334680-e71e-11e9-81bf-ea6833755bbf.jpg)

**Comment by gsantner** [comment]
can you upload markdown file too please?

**Comment by rhnvrm** [comment]
Sure,

The directory structure is:

```
.                   
├── 2019-06-11.md
├── 2019-08-19.md
├── 2019-08-20.md
├── 2019-08-21.md
├── 2019-08-22.md
├── 2019-08-23.md
├── 2019-08-24.md
├── 2019-08-28.md
├── 2019-08-29.md
├── 2019-08-30.md
├── 2019-09-03.md
├── 2019-09-04.md
├── 2019-09-05.md
├── 2019-09-06.md
├── 2019-10-05.md
└── diary.md
```

And here is `diary.md`

```markdown
# Diary

## 2019

### October
    * [2019-10-05](2019-10-05)

### September
    * [2019-09-06](2019-09-06)
    * [2019-09-05](2019-09-05)
    * [2019-09-04](2019-09-04)
    * [2019-09-03](2019-09-03)

### August
    * [2019-08-30](2019-08-30)
    * [2019-08-29](2019-08-29)
    * [2019-08-28](2019-08-28)
    * [2019-08-24](2019-08-24)
    * [2019-08-23](2019-08-23)
    * [2019-08-22](2019-08-22)
    * [2019-08-21](2019-08-21)
    * [Day one](2019-08-20)
    * [Day zero](2019-08-19)

### June
    * [2019-06-11](2019-06-11)

Shortcuts
`_w_w` to open todays diary
`_w_i` to refresh this page

Yankable scripts
You can run <Leader>E to run the command and it
should put the result in the buffer

List all tasks completed yesterday:
task end:yesterday completed

List all tasks completed today:
task end:today completed
```

**Comment by gsantner** [comment]
replace ) by .md) at every line and it should work for you.

**Comment by rhnvrm** [comment]
So, I had imported this file from somewhere else into markor today so I guess I did not realize that it is not an issue with hyphens.

The actual issue is that lists starting with multiple (4) spaces are being considered as plaintext instead of a list.

**Comment by rhnvrm** [comment]
If someone is looking to fix this in their `vimwiki/vimwiki/diary.vim`

You need to set your list_margin as 0.

```vim
let g:vimwiki_list = [{'syntax': 'markdown', 'ext': '.md',
                      \ 'list_margin': 0}]
```

**Comment by gsantner** [comment]
@rhnvrm 
If you would do at least on bullet without indent before, the second level indent should also work. like


```
## test
* Month January
  * link
  * link

* Month February
    * link
    * link
```

**Comment by rhnvrm** [comment]
Yes, but since it is an auto generated page, at first glance on mobile I could only detect the issue after pasting it on the github issue. :man_facepalming: 

Thanks a lot for the second eye and the amazing and extremely useful app!

**Comment by gsantner** [comment]
how do you generate this all? do you have some kind of custom tooling?

**Comment by rhnvrm** [comment]
I'm using [vimwiki](https://github.com/vimwiki/vimwiki), it can be used to maintain a [diary](https://blog.mague.com/?p=602). I have a custom setup but here is a basic tutorial that mentions the major features.
