### ISSUE TITLE
Markdown: Diagrams, Graphs, Flowcharts with Mermaid

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#720]
#### General information

* **App version:** v2.1
* **System:** v9

#### Description
This hacktoberfest issue is about adding support for [mermaid.js](https://mermaidjs.github.io/) to Markor, which allows to create diagrams via Markdown.

Note that Markor's markdown parser, flexmark also has features for Mermaid. Please have a look at the infos [here (flexmark-extensions wiki)](https://github.com/vsch/flexmark-java/wiki/Extensions) and make use of it.  
**For reference howto integrate** Mermaid: previously KaTex was integrated into Markor, it also has javascript&css files bundled via assets and shows in View mode.

-----------

![grafik](https://user-images.githubusercontent.com/6735650/66252913-73efb500-e750-11e9-98fd-91af934a85a6.png)

-----------

**Comment by jbrezina605** [comment]
Hi. I'm interested to solve the issue #720. Could you please assign it to me? Thanks.

**Comment by gsantner** [comment]
Feel free to go!

**Comment by jbrezina605** [comment]
I will start do it.

**Comment by gsantner** [comment]
@jbrezina605 
Thanks! Please make a pull request as soon as you start, that makes it easier to detect bigger issues and you don't do certain things multiple times :).

**Comment by jbrezina605** [comment]
Okay, I'm understand ;)

**Comment by pschwede** [comment]
Why not graphviz?

**Comment by gsantner** [comment]
@pschwede 
In some markdown appplications I've tried, I've seen Mermaid & probably others which just requires adding some small js/css files. Note: Mermaid is just the first suggestion and probably the most likeley one to be added.    

In contrast to that, graphviz is a fat native/c++ based library, that requires NDK and blows up app size, while it's only for a minority of users helpful. Also not have notice graphviz expliciteley somehwere yet.  

Does this answer your question?

**Comment by ChristianKurz** [comment]
I would also suggest looking into plantuml.

**Comment by gsantner** [comment]
I dont much care which, it needs somebody who works on it /develops it.

So please, if you want it, if you need it - work on it and send a PR.

**Comment by HOMMEEN** [comment]
Does it mean to modify the source code to integrate `Mermaid` into `Markor`?

**Comment by gsantner** [comment]
@HOMMEEN   
This is part of the issue - to find out how to integrate it and how it works. I don't use mermaid.

Most probably you need to modify source code of Markor for proper integration, yes.

I won't reply additionally to your email, as you have it here.
