### ISSUE TITLE
File browser: Thumbnails for images

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#724]
#### General information

* **App version:** v2.1
* **System:** v9

#### Description
Currently the integrated file browser only supports icons for file and folder generic.

The goal of this hacktoberfest task is to add autoamted creation of thumbnails for images and showing it in place of file icon.

* Use threads to create thumbnails in the app's cache folder.
* Apply it then in the view adapter when loading finished.
* Only do it for a certain set of file extensions, for now only jpg/png is enough.
* Don't add a additional library to the project. There are functions in ContextUtils and ShareUtils that has most required functionalities in place already.

**Comment by shldhll** [comment]
@gsantner I would like to work on this issue. Can you assign me?

**Comment by gsantner** [comment]
@shldhll 
Did!

Please have a look at my other project's file <https://github.com/gsantner/memetastic/blob/64a335988515232cca6782795a153b9752c008f3/app/src/main/java/net/gsantner/memetastic/service/ImageLoaderTask.java#L63> for implementation. I'm the whole author of it, as that it can be relicensed to Apache2 of this project.

that part is relevant:

![grafik](https://user-images.githubusercontent.com/6735650/66276317-45252c00-e881-11e9-9c28-f50e2b5f5e87.png)

**Comment by shldhll** [comment]
@gsantner This will make the implementation a lot simpler! Thanks for you help, much appreciated.

**Comment by gsantner** [comment]
@shldhll 
No problem! Please make a pull request as soon as you start, that makes it easier to detect bigger issues and you don't do certain things multiple times :).

**Comment by gsantner** [comment]
For next one reading this:
This issue is free to take again :)

**Comment by gsantner** [comment]
Closing, the list is pretty nice & clean, lets keep it this way.
