### ISSUE TITLE
add changelog link to the "more" tab

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [gsantner/markor#726]
### Description 
Hi,

Markor is a note taking app, so when it displayed the changelog at startup after the last update I had to skip reading it to be sure not to forget what I needed to note :/

I really like to read the changelog of each increment and I feel like everything is not written down in the changelog file (seems to be last updated a month ago when the update was juste a few days ago).

So do you think it would be possible to add a link to the changelog in the "more" tab at the bottom right of the screen ? I think it would be nice :)

xoxo

**Comment by gsantner** [comment]
the copy build info button on bottom shows changelog.
this might be moved to a different point at some time
