### ISSUE TITLE
Insert DateTime button is missing from TextAction toolbar

### ISSUE THREAD

**Issue by eloemosynator** [gsantner/markor#730]
#### General information

* Markor v2.1.4 (95) 
* Android on Google Nexus 5 

#### Description

I used to quickly insert current date/time in my markdown documents by clicking the rightmost button (with clock icon) in the TextAction toolbar, but now it's gone. Has it been purposefully removed for some reason?

**Comment by gsantner** [comment]
Its in the attachment menu now. 

Look for the clip icon.

**Comment by eloemosynator** [comment]
Thanks, it is indeed there. I'd have never found it as I mostly don't use attachments and it's not overly intuitive.

**Comment by gsantner** [comment]
its gonna be moved to bottom i n next version

**Comment by gsantner** [comment]
@eloemosynator 

Checkout update:
https://github.com/gsantner/markor/releases/tag/v2.1.5

Download update:
https://github.com/gsantner/markor/releases/download/v2.1.5/net.gsantner.markor-v97-2.1.5-flavorDefault-release.apk

Its gonna make you happy.

**Comment by eloemosynator** [comment]
Wow, amazing turnaround, thank you! The date/time button is back in TextActions for quick access :)
