### ISSUE TITLE
How to download project

### ISSUE THREAD

**Issue by Clabber** [gsantner/markor#734]
#### General information

* **App version:** 
* **System:** 

#### Description
Cant download this project, file not found on server.

**Comment by gsantner** [comment]
what do you want to download? source code or apk?

**Comment by Clabber** [comment]
Thank you.. The apk.



On Oct 13, 2019, at 10:51 AM, Gregor Santner <notifications@github.com<mailto:notifications@github.com>> wrote:


what do you want to download? source code or apk?

**Comment by gsantner** [comment]
https://github.com/gsantner/markor/releases/download/v2.1.5/net.gsantner.markor-v97-2.1.5-flavorDefault-release.apk
