### ISSUE TITLE
todo.txt: Add option to natural sort whole string

### ISSUE THREAD

**Issue by matthewbegun** [gsantner/markor#736]
Hi, I had a quick look but I can't seem to work it out. There are many ways to sort, but not default A-z?

Use case, when I sort by priority, the finished tasks don't get sorted to the bottom of the list.

Thanks,
Matt

**Comment by gsantner** [comment]
for done tasks, markor supports archiving (or todo.done known by other software). That is the suggested option to move away finished tasks.


In the bottom textaction area theres a archive button which moves all finished tasks to a todo.done.txt file. (filename freely choosable)

**Comment by matthewbegun** [comment]
So I typically archive finished tasks on a weekly basis, and sort my list multiple times per hour. My use cases are something like TDD for software development and fact checking manuscripts. Also shopping lists, ofc.

I would want my finished tasks to accumulate at the bottom of the list, no matter how I had sorted the list otherwise. 

I believe that is the reason that todo.txt uses the 'x' character to mark finished task - its alphabetically sorted to the bottom of the list so that any line based text sorting algorithm should do that.

Would it be a lot of work to add an option for that? I would normally just move on to something else, but I really like Markor for writing markdown files and it would be awesome if I could do everything in one app :). 

For example simpletask and todo.txt for android both default to this behaviour. In fact, I don't think I can turn it off in either of those apps.

**Comment by gsantner** [comment]
Closed via <https://github.com/gsantner/markor/commit/f8ad03bf3247960050727c18ab93c5339ff1bd41>

**Comment by matthewbegun** [comment]
thanks!

**Comment by gsantner** [comment]
@matthewbegun 
Test version with this available here
<https://github.com/gsantner/markor/releases/download/v2.1.5/net.gsantner.markor-v98-2.1.5-flavorDefault-release.apk>

**Comment by matthewbegun** [comment]
The sort by text lines is exactly what I was after. Tested working for multiple files, not big ones though (~20-30 lines).

Thanks again.
