### ISSUE TITLE
done Tasks are not moved to tasks.done.txt (or similar filename)

### ISSUE THREAD

**Issue by jonaheinrichs** [gsantner/markor#737]
At first I would like to say, I love the App. I can synchronise the app data via Syncthing without any cloud storage. Also I placed the data onto the external SD-Card into the Syncthing media file.

My Problem is that Markor is not moving tasks that have been marked as done to the done file, when I click the archive button.

Data Path and Todo Path:
![Screenshot_20191015-141256_Markor](https://user-images.githubusercontent.com/26126206/66830531-f731b780-ef55-11e9-895f-5d882700ac94.jpg)

#### General information

* **App version: v2.1.5 (97) ** 
* **System: Android 8.0.0 (Samsung S7 - SM-G930F)** 
Package: net.gsantner.markor
Version: v2.1.5 (97)
Flavor: Default (release)
Build date: 2019-10-09T21:03Z
ISource: com.google.android.packageinstaller

#### Description
I added some test todo's and marked some as done:

![Screenshot_20191015-135305_Markor](https://user-images.githubusercontent.com/26126206/66829577-f13ad700-ef53-11e9-8720-332730b931ef.jpg)

After that I clicked on the Archive Button to move the done tasks to the archive file:
![Screenshot_20191015-135314_Markor](https://user-images.githubusercontent.com/26126206/66829835-7de59500-ef54-11e9-8203-98698f26cf58.jpg)

There I chose _todo.done.txt_. But the todo file and the todo.done files stay the same...
Here I thought Markor would move them to the done file after clicking the archive button.

![Screenshot_20191015-135344_Markor](https://user-images.githubusercontent.com/26126206/66829965-bedda980-ef54-11e9-9fc2-2a87a0f88195.jpg)
todo.done file:
![Screenshot_20191015-135349_Markor](https://user-images.githubusercontent.com/26126206/66829974-c3a25d80-ef54-11e9-9c1d-901a904792ff.jpg)

#### Log
I 
- closed the app
- started logging
- opened the app
- clicked on the To-Do Tab
- clicked archive
- then chose _todo.done.txt_
- closed the app again
- stopped logging

[Markor-todo-done-not-working.log](https://github.com/gsantner/markor/files/3729055/Markor-todo-done-not-working.log)

**Comment by gsantner** [comment]
Works fine for me here (use it every day).

I strongly think this is a issue with writing to SD Card.

**Comment by jonaheinrichs** [comment]
Hmm, thanks for the fast reply! 
But Markor has no Problem writing to all my files... only the archive button is not removing the done rows from the todo.txt file and does not add them to the todo.done.txt file.

**Comment by gsantner** [comment]
That logic may not use the additional Sscard logic it means. Not issue on your side.

**Comment by jonaheinrichs** [comment]
With Markor I can edit the todo.txt file and the todo.done.txt file without Problems.
But the archiving function what should move the done ToDos from the one to the other is not working...

**Comment by gsantner** [comment]
I know. And in next update it will also work for archiving.
