### ISSUE TITLE
Remembered editor position not applied when defaulting to View Mode

### ISSUE THREAD

**Issue by JohnVeness** [gsantner/markor#738]
When entering a file, Markor always seems to be at the top of the editor rather than the last editor position.

V2.1.5 from F-Droid

**Comment by gsantner** [comment]
Has somebody else this issue? Please write here if so. Doesnt happen for me on any device (also don't see a relevant change on this).

**Comment by JohnVeness** [comment]
It seems to only happen with the setting "Open existing files in view mode" selected.

**Comment by gsantner** [comment]
related https://github.com/gsantner/markor/commit/da4863e3d4bd6ab650ef43aceaf5982a2bb7f43f

**Comment by gsantner** [comment]
--> #912
