### ISSUE TITLE
Selecting home screen icon action does not work

### ISSUE THREAD

**Issue by ddomgn** [gsantner/markor#739]
#### General information

* **App version:** 2.1.5
* **System:** Android 9

#### Description

1. Add Markor icon to the screen.
1. Long tap on an icon, them select any menu item, e.g. *QuickNote*.

Expected: Markor app is opened on a selected tab.

Actual: "app isn't installed" message shown.

![Screenshot_20191016_065724_com huawei android launcher](https://user-images.githubusercontent.com/10861368/66882263-2c381b80-efe3-11e9-9ab6-00b5c220e1a7.jpg)

**Comment by gsantner** [comment]
which launcher do you use?

**Comment by ddomgn** [comment]
I use EMUI 9.1 on Huawei Honor 8X, no custom launcher.

**Comment by ddomgn** [comment]
I fixed it by turning on **Launch(special documents)** setting (Fettings / General / Features), which is turned off by default. Thank you @gsantner!

**Comment by gsantner** [comment]
Hmm, nice that it works for you!
In general those shouldnt be needed for that actions to work.

If somebody else gets same behavior post here.
