### ISSUE TITLE
Also hide bar when textactions are disabled

### ISSUE THREAD

**Issue by ohenepee** [gsantner/markor#740]
#### General information
Textactions bar still shows without the buttons when you hide it in the settings, thus still stealing screen real estate for apparently no purpose.

* **App version:**  2.1.5 (97)
* **System:** Android 7.1

#### Description
I guess the obvious expectation is a hidden textactions along with the empty bar. No need to keep the bar still visible.

**Comment by gsantner** [comment]
with the move of "Representation Page" to the new "View Overlay Mode" the hide functionality was not added.

This is a very easy change, one line of code required. Leaving this to hacktoberfest community.

**Comment by Irfan-S** [comment]
Hi, could you specify the exact steps required to reproduce the issue? I'm unable to trace the exact cause of the bug.

**Comment by gsantner** [comment]
Settings - General - TextActions. Disablee that and you see a empy bar in editor. that instead should be hidden and editor take its place too.

**Comment by WendlerTech** [comment]
@gsantner mentioned that the functionality hadn't been added yet, but the code seemed to show that it was there. I spent _way_ too much time figuring out why it wasn't executing as expected; turns out someone just added a bottom margin to the document fragment.

**Comment by gsantner** [comment]
Yeah guess then its two lines, setMargin  and Setvisibility
