### ISSUE TITLE
different colors to distinguish files and folders

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [gsantner/markor#741]
#### Description
I have several documents and separate folder that I need to access via Markor. It's a bit frustrating that the only difference between folders and files is the icon on the left. They are all grey so it's not so quick to make out the difference.

To me it would be an improvement to add a bit of color to make them easier to make out :)

Thanks for reading !

**Comment by gsantner** [comment]
In the top menu there is a option "folders first" which moves all folders to top, then all files below.
That makes it easier to distinguish as you have only files after certain point.

However I dont want to use different / colored icons for folder. Orienting on some other filemanagers where its also same surrounding + white/black colored icon.

Keep it simple!
