### ISSUE TITLE
search button switches to edit mode

### ISSUE THREAD

**Issue by 532910** [gsantner/markor#746]
Pressing the search button switches markor to edit mode.

version 2.1.5 from f-droid

**Comment by gsantner** [comment]
missing version information

**Comment by 532910** [comment]
> missing version information

Sorry. Updated.

**Comment by gsantner** [comment]
vc97 or vc98?

Search is hidden in menu in vc99 release

**Comment by 532910** [comment]
97
Why it's hidden in 99?

**Comment by gsantner** [comment]
* hidden in view overlay

**Comment by 532910** [comment]
It's workaround for this issues, not a fix.

**Comment by gsantner** [comment]
what is the fix then?

when theres no button, you cannot press it.

please stop doing such minimalistic bug reports and always include whats wrong, what version you have and whats expected.

theres the Issue Template for a reason.

**Comment by 532910** [comment]
> what is the fix then?

Do not switch to edit mode and do search in the view mode.

**Comment by gsantner** [comment]
OK so look there is this template when you create new issues.


![grafik](https://user-images.githubusercontent.com/6735650/67248967-89095b00-f455-11e9-9395-659d97de7229.png)

Please fill that one out accordingly.



![grafik](https://user-images.githubusercontent.com/6735650/67249038-c1109e00-f455-11e9-9dc7-b3aea4bca136.png)

Neither from the title, nor description it's for me clear that you want "Feature: Search in View" and something along 

> "Hey! Theres no search for view available.
> I only found a button in view which does go to editing instead.
> Can you please add search for View mode? Thanks."

Look, I'm doing this project fully in free time, and I don't waste time with repeating and 

* asking for a somewhat usable feature request & bug report over and over.
* asking for basic details

If you really want to help, please please do better bug reports and feature requestst. saves a lot of time. thanks.

**Comment by gsantner** [comment]
I'm closing this topic and locking as I want to enforce bug reports to be at least minimum according to the issue template.
