### ISSUE TITLE
input 

### ISSUE THREAD

**Issue by bijang** [gsantner/markor#748]
the input method is a bit wysiwyg, bold button, italic button, H1 H2 etc, with corresponding 'boldifying' (not a term ;P) when pressing B, is this necessary? why not a proper p;ain text with hash etc, to open up the possibilities, esp when most are coming for markdown and theres a preview option? I'm comparing to what I consider your main viable alternative, neutrinote, which isnt perfect in its implementation...
many thanks for your consideration
also , inspired by same, a qr code scanner??

**Comment by gsantner** [comment]
Markor is a editor for plaintext, no wysiwyg but syntax highlighting. the actions are for inserting text.

I don't understand what you want.

**Comment by nofishonfriday** [comment]
Hi,
sorry for picking up this closed issue, but it seems to be a good place for my question (rather than opening a new issue for it).

New to Markor, in edit mode I don't see the bold, italic etc. buttons in the bottom bar, have they been removed meanwhile or am I missing a setting?
Thank you.

**Comment by gsantner** [comment]
Yes Markor supports a few different formats. And for plaintext (like notepad .txt's) there is no syntax for italics. But Markdown has
