### ISSUE TITLE
[improv] Automatically underline phone numbers or street adress ?

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [gsantner/markor#749]
Hi,
would it be possible to have markor automatically detect phone number or street adress and "link" them ? By that I mean that clicking on them would call the phone or map app.

I think it would be useful.

Thanks for reading !

**Comment by gsantner** [comment]
For View or Edit mode?

For any of them, adress is impossible to autodetect as it cna be anything. It's impossible to know if "gsantner 5" is a adress or not.

For number: click in View mode may be possible.

**Comment by gsantner** [comment]
I'm closing this as it's not really possible to differentiate generic what is a address or a telephone number.
If somebody writes `+2141` the user might mean as well a count of things, a JIRA ticket, a calculation, a telephone number, ... .

But what I can suggest you todo is this: Write telephone  numbers like this: `[Call +49 1234 1234](tel:+1-1234-1234-1234)`
