### ISSUE TITLE
[Feature request] Markdown todo: validate from view mode

### ISSUE THREAD

**Issue by jdorel** [gsantner/markor#752]
#### Description

In markdown, it would be great if we could validate / invalidate a todo item from the view mode. You can see this behavior in Scarlet Notes app (there is also reordering but I think it should be an option).

**Comment by gsantner** [comment]
Thanks for the request!

This however was already requested - and no: View mode is really a View Mode and I want it to stay as such. Viewing is for viewing only, not making changes to content.

**Comment by jdorel** [comment]
As an alternative, when a todo list is detected in markdown, could there be a new todo mode ?

**Comment by gsantner** [comment]
Could. But currently no separate editing mode is planned.

For todo.txt there is the `done` button (first button in the button row). Use that to mark tasks done.

**Comment by jdorel** [comment]
Yes, but there can only be a single todo file. My typical workflow involves multiple files (per organisation todo lists, shopping lists, ...). Also a different mode could improve on ergonomics so that button size can be larger.

**Comment by gsantner** [comment]
> Yes, but there can only be a single todo file.

That is not quite right, you can have as many todo files as you want! :smile: 

Just create a file that starts with `todo.   .txt` or ends with `todo.txt`, anywhere you want. It will open in  todo.txt mode.

**Comment by jdorel** [comment]
Indeed, my bad. I mistook the To-Do special file with todo files, sorry 😏.
Anyway, thanks for this great product.

**Comment by gsantner** [comment]
Happy to help!
