### ISSUE TITLE
inputing nested lists

### ISSUE THREAD

**Issue by bijang** [gsantner/markor#756]
nested lists is a difficult thing, anyway to improve upon this?
Also is H1 H2 H3  buttons maybe a waste of realestate? I understand it's a RTF type input to hide a hash and a space, just like to B is to hide wraparound stars etc... I guess this raises issues of the general pros and cons of this shortcut format vs just exposing the hash or the star etc... so for example, if you wanted to preserve the H1 H2 format why not put just a H and 1 tap is H1 or #, two taps H2 or ## ...etc 
essentially does the ergoniomics of the input bar need to be looked at?
And can it do nested lists without resorting to the * or other in the main input kepboard
Many thanks for your consideration and thank you for a fantastic application

**Comment by gsantner** [comment]
Create a list with `*` at begin of line, when you press enter the list automatically creates a new entry.
