### ISSUE TITLE
Http protocol image link address

### ISSUE THREAD

**Issue by at2008** [gsantner/markor#757]
App seems to only support https protocol image link address, is this the case? Why not support the image address of the http protocol? It should be more than one that I need this.

**Comment by at2008** [comment]
> please do a proper bug report and fill out the fields, especially about version&system.
> 
> android version is highly important for this.

Android 9
![20191101021219](https://user-images.githubusercontent.com/25857125/67974433-68a78080-fc4d-11e9-91e0-88f691c7b032.jpg)
![20191101021213](https://user-images.githubusercontent.com/25857125/67974443-6b09da80-fc4d-11e9-9eb5-248b72a3ac98.jpg)

**Comment by gsantner** [comment]
>  Android 9

That was my exact guess. Android 9 disallows cleartext traffic by default as new privacy standard (which is IMO very good).

Need to think if I want to force this privacy&security feature by default.

**Comment by at2008** [comment]
I see.
Thanks for the reply, Markor is a great Markdown tool.
