### ISSUE TITLE
Feature: Save as New File

### ISSUE THREAD

**Issue by ChiefMikeK** [gsantner/markor#760]
#### General information

* **App version:** v101-2.2.1 from github
* **System:** Android 6.0.1 Samsung

#### Description

Sometimes I need to _save_ a new **Quicknote{¿date?}.md** vice **appending** the older/current Quicknote.md but there's no easy way to accomplish that.    
So suggest you add an entry to the menu-pull-down as in screenshot:    
● Save As _(newfile)_ & also for **_translations_** be shure to distinguish it from    
● Save _(overwrite)_

#### Screenshot

![Markor-SaveAs](https://user-images.githubusercontent.com/20070053/68051699-05881d80-fd23-11e9-84a7-ea3aa915e661.png)

**Comment by jakub231** [comment]
Hi! Can I work on this issue? Is it still open? Thanks

**Comment by gsantner** [comment]
@jakub231 
Yes not done yet, thanks

**Comment by gokomer** [comment]
Hi @gsantner I've added the menu item but I'm not sure how to approach implementing save as UI. How do you want this to be implemented?

![2019-11-17_15-05](https://user-images.githubusercontent.com/11593018/69007218-16a07380-094c-11ea-9bf1-939fb01fe7da.png)

**Comment by ChiefMikeK** [comment]
> ![2019-11-17_15-05](https://user-images.githubusercontent.com/11593018/69007218-16a07380-094c-11ea-9bf1-939fb01fe7da.png)
##  fwiw
In some languages the word **"as"** doesn't translate well that is why I had recommended including **(overwrite)** & **(newfile)** in the dropdown 👀  
:neckbeard:

**Comment by ChiefMikeK** [comment]
## Still Hoping to 👀 this! 
🔜¯\_(ツ)_/¯ :neckbeard:

**Comment by 2catycm** [comment]
Hi, I think I have understood how to add the UI, and I found the DocumentEditFragment class to read. However I don't know what is the way to open a dialog and ask the user for new location(directory, and ask for a new name as well), is there a java class in this project that I should read?
BTW, after a `save as` action, the word/notepad/typora would like to open the new copied file to edit in the same activity, so after the action, I think I should invoke the loadDocument() method in DocumentEditFragment class, did I got it right?

**Comment by gsantner** [comment]
newfile and rename dialog java classes.

**Comment by gsantner** [comment]
newfile and rename dialog java classes.

**Comment by 2catycm** [comment]
thanks for assigning, I will try my best to finish the issue.&nbsp;



---Original---
From: "Gregor ***@***.***&gt;
Date: Mon, May 16, 2022 02:03 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [gsantner/markor] Feature: Save as New File (#760)




 
Assigned #760 to @2catycm.

**Comment by gsantner** [comment]
keep in mind, its not your job. assignment is just a note who MAY do what.

**Comment by 2catycm** [comment]
OK



---Original---
From: "Gregor ***@***.***&gt;
Date: Wed, May 18, 2022 21:53 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [gsantner/markor] Feature: Save as New File (#760)




 
keep in mind, its not your job. assignment is just a note who MAY do what.

**Comment by 2catycm** [comment]
Here's an possible [PR](https://github.com/gsantner/markor/pull/1707) that may solve this issue.

**Comment by gsantner** [comment]
there is now a button "Markor" when you select text, and you can select also all text. Using that button leads to the Share-Into screen where you can "Save as new file", or append to, or whatever you like to.

If you want to make safety copies, make it before changing up your text, or use some sync software functionalties (which i.e. do backup/history on server side). Trusting on editor undo or alike is not what you should look out to, whats gone is gone and when you turn off the screen Markor will save, as it should.
