### ISSUE TITLE
Double tap to edit

### ISSUE THREAD

**Issue by suhr** [gsantner/markor#761]
It would be nice to be able to switch to editing mode by double tapping.

**Comment by gsantner** [comment]
there is swipe gesture to switch to edit mode.

**Comment by suhr** [comment]
Yes, but swiping doesn't work very reliably. Tapping is easier and, I believe, is more intuitive.

**Comment by gsantner** [comment]
tapping plays with focus, cursor pos and keyboard popping up.

I dont want to add this sorry.
