### ISSUE TITLE
Markor as an extension for a web browser or as a web application

### ISSUE THREAD

**Issue by podtor** [gsantner/markor#762]
It will be possible in the future to create some extension for a web browser or to create a web application?

**Comment by gsantner** [comment]
You have to ask at your browsers forum. Whats Markor todo with that?

**Comment by Agrotsa** [comment]
> You have to ask at your browsers forum. Whats Markor todo with that?

Not sure, but I think that the OP might be thinking about a browser extension like those by [Qownnotes](https://github.com/qownnotes/web-companion/), [Joplin](https://github.com/laurent22/joplin/blob/master/readme/clipper.md), [Onenote](https://www.onenote.com/clipper), etc. A web clipper extension to save content from the web as sanitized articles in Markdown format. I think is a great idea.
Creating a web version of Markor sounds less useful and way more complicated to me. But it's just my humble opinion.
