### ISSUE TITLE
Voice reader (TTS)

### ISSUE THREAD

**Issue by Agrotsa** [gsantner/markor#768]
Many of us use services like Mozilla Pocket or Wallabag to listen captured web pages while we are working out, doing the weekly shopping, just walking by the street, etc. It's a great way of taking advantage of those dead times in which we can't read a book or doing something that requires much of our visual attention.
The mentioned services are awesome for listening to web pages, but if Markor could do the same with our saved notes and drafts, the "circle" would be complete.
There are many voice readers for Android, like @Voice Aloud, which is closed source, or [FBreader](https://githttps://github.com/geometer/FBReaderJhub.com/geometer/FBReaderJ)  via a plugin, but none works well with MD files since those apps don't try to read the rendered markdown file but the plain text file, with all the tags and formatting marks in the MD file. This makes the listening almost uncomprehensible, or at least very confusing and frankly disagreeable.

All these apps seem to use the TTS (Text To Speech) engine that Android has built in, and the installed voices (robotic PicoTTS, Google's, or better ones like those by IBM, that's up to the user), those we hear when using our maps application, for example, to "read" aloud the saved pages.
I don't know a thing about software developement, but since [Wallabag](https://github.com/wallabag/android-app) is open source, couldn't you take the parts of its source code that calls the TTS sinthesizer, and integrate them in Markor? I guess that things arent that easy and would involve some extra work, but if it could be done, it'd be an awesome and greatly usefull feature.

Greetings

**Comment by gsantner** [comment]
As long as the used component / library is fully open source I'm fine with it. In addition, I want it to use the system TTS, not deliver a own TTS engine with markor.

**Comment by Agrotsa** [comment]
I know that FBReader has an open source version, and old one, I believe, but I don't know about its TTS plugin, I can't see its Github repository, so perhaps said plugin isn't open source.
But Wallabag is totally open source, GPL3 license, so I guess the libraries or whatever mechanisms that it uses to call the Android's built in TTS sinthesizer are freely re-usable in other projects. Maybe you could ask its developers?
I know also of [Librera](https://github.com/foobnix/LibreraReader) using TTS technology and also [OsmAnd](https://github.com/osmandapp/Osmand), the open source alternative to Google Maps based on OpenStreetMap, uses Android's TTS engine for "speaking" addresses, route indications and such.
Maybe Wallabag or Librera may be more suitable for reading aloud longer text blocks than just a "In 200 meters, turn left", and similar messages that are the usual stuff in maps and GPS applications. I'm afraid my limited knlowledge ends here and can't help much more :-|

**Comment by gsantner** [comment]
I'm waiting for community contribution on this.

**Comment by Agrotsa** [comment]
Ah, ok. I'm sorry about not having any informatics education and being unable to contribute with coding. Thanks anyway for your interest, and I hope some developer reads this and finds it interesting.

**Comment by xuvatilavv** [comment]
A note on this, Markor already mostly works with Android's built-in Select to Speak feature, it just needs to be enabled in the device's accessibility settings. Most markdown formatting is ignored, with the exception of `*` and '>` from what I've just tested. Only thing lacking is the ability to read only after an arbitrary point in a document. 

I noticed while testing this that only the "read entire document" feature works within markor, trying to instead select specific text to read will always read the entire document top to bottom. Not sure if this is a problem with markor or Android itself, so I'm not sure if I should create a bug here for it.

**Comment by gsantner** [comment]
@xuvatilavv 
If you want, do some experiments with the edittext component. Maybe you can find something helpful regarding reading from a given start location (/or selected text).

In general we will not add any kind of custom TTS in Markor and use sys/installed TTS.

**Comment by gsantner** [comment]
Closing - there is the TTS by the android system available for anybody who wants/needs to activate it.
