### ISSUE TITLE
Not able to empty QuickNote file

### ISSUE THREAD

**Issue by seth100** [gsantner/markor#771]
#### General information

**App version:**  `2.2.2`

**System:** `Android`

#### Description

- Open app
- Open "QuickNote"
- Edit note and delete all the content
- Go back (via icon or phone back button)

Changes are not saved, so the note is not fully empty, the content that was existing before edit is still there.

If I just edit the QuickNote by putting other text (not empty) the changes are correctly applied.

Thanks

**Comment by gsantner** [comment]
it is intentional that you cannot save a completly empty file.
that is due some users due some reason select&delete all and end up with empty file then unwanted.

if you want to clear your file, just leave one dot for example and save is gonna happen.
