### ISSUE TITLE
Black blank space above the keyboard

### ISSUE THREAD

**Issue by fairplay** [gsantner/markor#772]
#### General information
When I set cursor in the edit mode black blank space appears above the keyboard. Than cursor placement is lower than this space is taller. When I set cursor in the beginning -- there is no such space appeared.

* **App version:** 
2.2.2
* **System:** 
Huawei Honor 10, Android 9

#### Description
![photo_2019-11-08_08-36-15](https://user-images.githubusercontent.com/272090/68463439-ac872080-021f-11ea-9aa2-6fb5549f54b1.jpg)

**Comment by gsantner** [comment]
do you have the fullscreen/hide bars option enabled?

**Comment by fairplay** [comment]
Yes, disabling "Hide statusbar" in Editor helps, thanks.

**Comment by gsantner** [comment]
OK thanks for confirm!

On some devices hide one bar only works not so well, thats known

**Comment by fluidicice** [comment]
I have the same issue partially. The Black bar only appears on newly created files and disappears permanently once the file is reloaded - so it's not that big of a deal. However I looked through all the settings multiple times and couldn't see a "hide status bar" setting.

Markor Version: 2.10.3 (139)
Phone: Samsung Galaxy S10+
OS: e.Foundation v1.6
Android 11

![Screenshot_20230105-150946_Markor](https://user-images.githubusercontent.com/113685731/210711060-92ceeacc-08e2-4e00-8a78-b759b8c8e00f.png)
