### ISSUE TITLE
Files in cloud eg. on onedrive or nextcloud

### ISSUE THREAD

**Issue by podtor** [gsantner/markor#778]
#### General information

* **App version:v2.2.3 (105)** 
* **System: Android 8.0** 

#### Description
How to choose a folder on onedrive or nextcloud location? I would like to use the cloud to sync files to have a backup and the possibility to share them, and working on Windows.

**Comment by gsantner** [comment]
For NextCloud you can configure the filepath in the NextCloud app. Usually it's somewhere under `/storage/emulated/0/Android/`  media OR data.
For OneDrive have a look at <https://www.tacit.dk/foldersync/>

**Comment by jpggithub** [comment]
For nextcloud, the workaround proposed does not permit to sync.
