### ISSUE TITLE
Not scrolling down correctly in editor as you type

### ISSUE THREAD

**Issue by JohnVeness** [gsantner/markor#782]
For the last couple of versions from F-Droid, and certainly in 2.2.3, the window doesn't scroll down correctly as you type. That is, when the cursor reaches the bottom, it then disappears underneath the onscreen keyboard so you can't see what you're typing. The text will eventually scroll up, but a line or two too late.

Hope this is understandable. I can do animated gif if helpful.

**Comment by gsantner** [comment]
likely related https://github.com/gsantner/markor/pull/742
