### ISSUE TITLE
Search in View discards at first try automatically when defaulting to View Mode

### ISSUE THREAD

**Issue by 532910** [gsantner/markor#789]
#### General information

* **App version:** 2.2.3 (104)
* **System:** 16.0-20191114-microG-opnepus3

#### Description

The first attempt (after file opening) will be stopped accidentally. It happens every time.

See video <https://sergio.outerface.net/misc/ScreenRecord-2019-11-20-03-58-39.mp4>

**Comment by gsantner** [comment]
can you please add a gif/video?

**Comment by 532910** [comment]
https://sergio.outerface.net/misc/ScreenRecord-2019-11-20-03-58-39.mp4

**Comment by gsantner** [comment]
related to #738

**Comment by gsantner** [comment]
Ive just tried and can confirm still the case.

**Comment by gsantner** [comment]
--> #912
