### ISSUE TITLE
Markdown: Add Outline View button (for headings)

### ISSUE THREAD

**Issue by michaeldurland** [gsantner/markor#790]
#### General information

* **App version:** v2.2.3 (105)
* **System:** Android 9, LG G6

#### Description
It would be great if Markor could have a window that slides out with a swipe from the left edge of the screen to show an outline of headings of the current document. Clicking on a heading in the outline would jump the editor cursor to that line. This would ease navigating/scrolling through large docs to find a heading of interest to edit. Kind of like this VS Code feature: https://code.visualstudio.com/docs/languages/markdown#_outline-view
Thanks for a great app!

**Comment by lexterror** [comment]
I would like to see that too. "Typora" has that feature but it's not for mobile. https://www.typora.io/ I didn't see this topic before I opened the same one.

**Comment by gsantner** [comment]
Open for implementation.
But I prefer a button/toolbar-button/textaction over slide gesture to show that UI.

**Comment by gsantner** [comment]
For edit mode there is a easy way: open search and type  "# "

**Comment by gsantner** [comment]
Available starting with next update:

![video_2020-05-24_14-40-13](https://user-images.githubusercontent.com/6735650/82754357-e97dc380-9dbb-11ea-995d-81664555b1b6.gif)
