### ISSUE TITLE
Feature Request: "Outline preview with navigation"

### ISSUE THREAD

**Issue by lexterror** [gsantner/markor#792]
I would like to see the outline of the document and the ability to jump to different sections from the outline. 

Thank you.

**Comment by gsantner** [comment]
#790

**Comment by gsantner** [comment]
Available starting with next update:

![video_2020-05-24_14-40-13](https://user-images.githubusercontent.com/6735650/82754357-e97dc380-9dbb-11ea-995d-81664555b1b6.gif)

**Comment by gsantner** [comment]
Implemented now, see #790
