### ISSUE TITLE
Markdown: Add support for nested check lists

### ISSUE THREAD

**Issue by ascii78** [gsantner/markor#794]
#### General information

* **App version:**  2.2.3
* **System:** android 9

#### Description

Just synced succesfully with my Typora markdown notes. I have some task lists that are indented as
follows:

```
- [ ] main
   - [ ] indented
```

I can tick the main box with the provided tick button, but not the indented one. It does not recognize that it is a task entry and will add another `- [ ]` to the beginning of the line.

**Comment by harshad1** [comment]
This happens with unordered lists too.
```
- Foo
    - Bar
```
> Place cursor on line 'Bar' and press list button
```
- Foo
-      - Bar
```

**Comment by westurner** [comment]
List items nested beyond 3 levels are also being highlighted? Is that a separate bug?

```markdown
- one
  - two
    - three #highlighted
      - four #hl
         - five #hl
```

**Comment by westurner** [comment]
Is it a regex for markdown task lists?
A regex match group for `(\s*)` would likely solve?

**Comment by gsantner** [comment]
As you see in other #s , starting with amount of space will make code highoithting. thats gonna stay.

**Comment by westurner** [comment]
If someone can fix the thus broken markdown implementation, would you be open to such a patch?

https://spec.commonmark.org/0.29/#list-items

https://spec.commonmark.org/0.29/#example-264 :

```markdown
- foo
  - bar
    - baz
      - boo
```

https://spec.commonmark.org/0.29/#example-266 :

> Here we need four, because the list marker is wider:

```markdown
10) foo
    - bar
```

**Comment by gsantner** [comment]
I dont feel like its too much broken, but when you can provide a PR that not negatively impacts performance its welcome.

**Comment by harshad1** [comment]
Here is my attempt at fixing this issue :) https://github.com/gsantner/markor/pull/877

**Comment by harshad1** [comment]
@ascii78 Would you be willing to review / test my attempt at fixing this issue? I have a PR (see comment above).

**Comment by ascii78** [comment]
sorry, not a developer so i don't now how i would a review a change that is not in a release, maybe someone else can help ?
