### ISSUE TITLE
Decrease text margins

### ISSUE THREAD

**Issue by Kamul-PL** [gsantner/markor#795]
#### General information

* **App version:** v2.2.3 (105)
* **System:** Android 9 (LOS 16)

#### Description
Could the margins size of text be decreased? They're quite big in edition mode, and even bigger in view mode. Phones have relatively small X resolutions, which is some kind of problem especially in case of documents with line breaking. And I think settings the margins value even to zero (or almost zero) pixels shouldn't harm in any way, but could make text edition/viewing more comfortable.

**Comment by gsantner** [comment]
To clarify: You mean the distance between each character, horizontally, right?

**Comment by aubreyz** [comment]
No I think he is talking about the space before the first character and after the last one (in both edit and view). I took a look at my screen and it looks like about a 2 em (2 character) gap at start and end. 

I agree that this is too big and could be reduced ideally (to allow at least an extra 2 or 3 characters per line especially in edit mode).

**Comment by Kamul-PL** [comment]
> No I think he is talking about the space before the first character and after the last one (in both edit and view). I took a look at my screen and it looks like about a 2 em (2 character) gap at start and end.

Yes, that's exactly what I meant. And, at least in my case, there's a space for about 3 characters at the beginning, and 3 character at the and of every line. It maybe looks good, but is impractical in case of relatively low resolution displays.

**Comment by gsantner** [comment]
I have to think about it.
Thats the standard android activity margin apps should have.

**Comment by subi54** [comment]
@Kamul-PL in Settings > View > Inject Body
Try:
```
<style>
p {
margin-left: -xx em/px;
}
</style>
```
Same with margin right.

**Comment by Kamul-PL** [comment]
> @Kamul-PL in Settings > View > Inject Body
> Try:
> 
> ```
> <style>
> p {
> margin-left: -xx em/px;
> }
> </style>

It would be good as a temporary solution (it won't work in edit mode though), but... I tried it, and it doesn't help in my case. I'm not sure if I'm doing something wrong - hopefully not.

**Comment by Kamul-PL** [comment]
> I have to think about it.
> Thats the standard android activity margin apps should have.

I'm not telling, that such margins value are breaking the Android standards. But if someone (like me) uses Markor, among others, to share the same text documents between my phone and PC, it would be good to have a possibility to display as much of text in single line, as it is possible.

Besides that, I'm using Markor to display text of songs, guitar chords and tabs when I'm playing the guitar. Especially here, it is highly desirable, to view as much information at once, as it is possible.

So I would be very appreciate for such a change (or option to change).

**Comment by gsantner** [comment]
My suggestion for this case is:  decrease font size.

Otherwise, its a phone screen not a PC screen, you cant get much fit with same size on it.

**Comment by Kamul-PL** [comment]
@gsantner This is what I've already done, but there are some boundaries... And decreasing the margins we gain more space without the costs of readability.
