### ISSUE TITLE
Start on bottom works only in edit mode

### ISSUE THREAD

**Issue by Kamul-PL** [gsantner/markor#796]
#### General information

* **App version:** v2.2.3 (105)
* **System:** Android 9 (LOS 16)

#### Description
It seems *Start on bottom* option work only in *edit mode*. If I have default view set to *view mode*, opened files are displayed from the top. Also if I open a file in *view mode*, and than change mode to edit.

**Comment by gsantner** [comment]
The first part: Start on bottom is a **editor** setting and I dont think about adding one for view.

For the second part, see #768
