### ISSUE TITLE
Separate title from content when sharing

### ISSUE THREAD

**Issue by sojusnik** [gsantner/markor#797]
#### General information

* **App version:** v2.2.3 (105)
* **System:** Android 9

#### Description

When sharing a text selection from Firefox, then the title of the webpage precedes the shared content, separated only be a normal space, which makes it hard to identify the beginning of the actual shared text. A more obvious separation between the title and the content would improve the readability a lot. A solution could be a simple new line, instead the normal space, between the title and the shared content. In other words, the title and the content should start with their own line.

**Comment by gsantner** [comment]
Beside changing links to Markdown format I don't plan changing shared content. From user view it's exptected to see the exact same text what I give into Markor and not magically manipulate something.

Still, please can you give a original text example and what you expect, in a code block? (\`\`\`)

```
text
text
```

**Comment by sojusnik** [comment]
> From user view it's exptected to see the exact same text what I give into Markor and not magically manipulate something.

The thing is that when sharing from Firefox, the user also sees the title of the webpage, which is quite irritating, because you only expect to see the shared text.

At the moment I get the following, when sharing the first two sentences from your [website](https://gsantner.net/project/markor.html):
```
Markor - Project Website & FAQ - Markdown Editor, todo.txt, Android app | gsantner Markor is a TextEditor for Android. This project aims to make an editor that is versatile, flexible, and lightweight.
```

According to my suggestion, this should be more readable:
```
Markor - Project Website & FAQ - Markdown Editor, todo.txt, Android app | gsantner
Markor is a TextEditor for Android. This project aims to make an editor that is versatile, flexible, and lightweight.
```

The ideal solution IMHO would actually be a version without the page title, but with the URL:
```
Markor is a TextEditor for Android. This project aims to make an editor that is versatile, flexible, and lightweight.
https://gsantner.net/project/markor.html
```
But I assume that Firefox on Android is not providing the URL when sharing, instead adding the title before the actual shared content.
