### ISSUE TITLE
Feature: Possibility to use app without giving a "write to external" permission

### ISSUE THREAD

**Issue by serebryakov-av** [gsantner/markor#798]
#### Description

Is it possible to make app working without giving to it write to external permission?

p.s. How difficult to fix it in the code? I found method `mkdirIfStoragePermissionGranted` that called even if I create a file inside the "AppData (private)" section.

**Comment by gsantner** [comment]
That may be possible but that makes it hard to work interopt with other apps.
For now no goal to make it work different for private vs external.

**Comment by serebryakov-av** [comment]
Got it, thank you!

p.s. Thinking about another way to solve my problem. #60 (Encryption) or supporting encrypted disks.

**Comment by gsantner** [comment]
What you also can do is share text to markor. theres also a temporary editor
