### ISSUE TITLE
Open file with Markor, edit it, and push back

### ISSUE THREAD

**Issue by serebryakov-av** [gsantner/markor#799]
#### Description

For example there are two applications:
1. File manager that handles some storage (remote, or local and encrypted).
2. Markor.

The case?
1. Pick in the file manager "Open file with..."
2. Choose Markor.
3. Make up some changes.
4. Save the file.
5. File saves into original source in the "File manager".

**Is it possible to implement such a feature?**

p.s. What I need to learn/search to get know how to implement the feature in the Markor? On https://developer.android.com for example.

**Comment by gsantner** [comment]
Ehm thats how it's supposed to work already :D. So picking a file and choosing markor should start editing it

**Comment by serebryakov-av** [comment]
May be I confused because it can't work without permission to access external files #798 ;)

But after I gave the permission I got an error that:
"Markor can only edit local, offline available documents and does not support file managers that do not provide the full file path.
Note: Sync apps may place files in custom folders. Open them by changing Markor's document folder accordingly, or in another file manager.
Dropbox: Android/data/com.dropbox.android/files/u123456/scratch/
Own/NextCloud: Configure in the app settings"

The same with Dropbox and Google Drive.

**Comment by gsantner** [comment]
Which filemanager is it

**Comment by serebryakov-av** [comment]
Dropbox and Google Drive. They holds files internally.

**Comment by gsantner** [comment]
Google Drive isnt supported but dropbox is

**Comment by serebryakov-av** [comment]
So, Dropbox doesn't work either...

**Comment by gsantner** [comment]
I have tried Dropbox some months ago and it worked fine. Official Dropbox app crashes when I try to login so don't know whats up with it's app.
Theres also FolderSync which works for all kinds of storages.

I don't see any bug or todo here, closing.
