### ISSUE TITLE
Changing case of the file name deletes the file

### ISSUE THREAD

**Issue by sjmduncan** [gsantner/markor#8]
Version 0.1.1 (F-Droid)

Changing the case of one or more letters of the filename from within Markor will delete the file.

For example

Notes -> notes
Notes -> NoTes
Notes -> nOTES
...

Will delete Notes.md while

Notes -> Mynotes
Notes -> note
Notes -> Motes
...

Are safe renames.

**Comment by gsantner** [comment]
Hm. Maybe a bug/(feature) of java.io.File.rename() . thanks for reporting

**Comment by gsantner** [comment]
<https://github.com/gsantner/markor/commit/7cb7579e739e6f4786e0e0ed8093a7ad07a90ea5>

**Comment by gsantner** [comment]
@sjmduncan 
What would you say fits best as icon for rename, out of <https://material.io/icons/> ?

**Comment by sjmduncan** [comment]
@gsantner I can't see a better one, but material always seems to be missing at least a few basic ones.

I do think the icons could be better. The new file icon could be 'note add' and the move icon could just be 'folder'. Rename and the editor shortcut in preview are probably fine sharing the 'mode edit' icon because they do the expected thing in their respective contexts.
