### ISSUE TITLE
Broken search function in Edit window

### ISSUE THREAD

**Issue by subi54** [gsantner/markor#800]
#### General information

* **App version: v2.2.3 (105)** 
* **System: Android 8.1.0 Moto G5S+** 

#### Description

Hello, 
My issue is with search in Edit window. I can search well enough, but the window does not jump to the selection.

P.S. In the color scheme setting, is it possible to put in custom hex code? Am I missing something?

P.P.S. Markor + Syncthing + VSCode + Git works wonders.

Love Markor. It is precise in what it does, text editing. It is amazingly responsive. Thank you for the wonderful app @gsantner.

**Comment by gsantner** [comment]
Can you please paste me a example document where this happens for you? works for me here at least

**Comment by subi54** [comment]
Could not upload the `.md` file. Please rename the `.zip` extension to `.md`.
[Worm.zip](https://github.com/gsantner/markor/files/3940562/Worm.zip)

**Comment by gsantner** [comment]
I tried search with your file and I cannot reproduce any issue.
Search works fine for me in both edit and view mode.

![video_2019-12-15_12-43-01](https://user-images.githubusercontent.com/6735650/70862132-19cd5600-1f30-11ea-8fd0-a22c4082ba9f.gif)

**Comment by subi54** [comment]
@gsantner my apologies. I think my search wasn't jumping to target because I did not have the keyboard open. It works when the edit window is focused and keyboard pops up.

Thank you for looking into it nonetheless and sorry for wasting your time.

**Comment by gsantner** [comment]
no problem, good to hear it works for you now :D
