### ISSUE TITLE
Hide bottom bar in Main View

### ISSUE THREAD

**Issue by ksz16** [gsantner/markor#801]
#### General information

* **App version:** Markor 2.2.3; AnySoftKeyboard 1.10.606 (both from F-Droid)
* **System:** LineageOS 14.1
* **Device:** Motorola MotoG LTE X1039

First of all, I would like to thank you for a great app.

#### Description
I have a question about bottom bar in Main View (I mean bar with "Files, To-Do, QuickNote & More")

When I select Files and try to edit QuickNote.md or todo.txt, only visible bar is Texaxtions.
But when I choose QuickNote or To-Do directly in Main View, I can see Texaxtions and bottom bar together.

Is there any way to hide bottom bar when editing in Main View and on-screen keyboard shows?

![Screenshot_20191212-101417](https://user-images.githubusercontent.com/22708888/70869076-6728e200-1f87-11ea-890b-005bfc8ea2e7.png)
![Screenshot_20191212-101446](https://user-images.githubusercontent.com/22708888/70869080-6e4ff000-1f87-11ea-95cb-e5e9e013a7b3.png)
![Screenshot_20191212-101501](https://user-images.githubusercontent.com/22708888/70869083-73ad3a80-1f87-11ea-8a9f-ceb4457d2972.png)
![Screenshot_20191212-101537](https://user-images.githubusercontent.com/22708888/70869088-77d95800-1f87-11ea-95ff-c4d9c031cf38.png)

**Comment by gsantner** [comment]
Possible but I don't plan to hide it, and neither introduce a new setting.

**Comment by ksz16** [comment]
May I ask why?

**Comment by gsantner** [comment]
1) Don't want to hide something on main view just for sake of change 
2) Don't want to add new setting with low use : smiley :

**Comment by ksz16** [comment]
I just wanted to save screen space when editing in Main View mode :)
Thank you for your reply and your work.

**Comment by gsantner** [comment]
Thanks for understanding : D

**Comment by gsantner** [comment]
hey @ksz16 

Theres news on this you gonna like. With next update, bottom nav will automatically hidden when you have keyboard open, thus having more space for seeing what you type.
