### ISSUE TITLE
Force closes when ~1MB txt file set as QuickNote

### ISSUE THREAD

**Issue by Kamul-PL** [gsantner/markor#802]
#### General information

* **App version:** v2.2.3 (105)
* **System:** Android 9 (LOS 16)

#### Description
When I choose a bigger txt file (about 1MB) as a QuckNote file, Markor crashes every time I'm trying to open settings. So, the only possibility to change the file to something else is to rename my 1MB test file, so Markor can't find it.
The example file, which I use to test could be find here:
https://www.dropbox.com/s/pq8xzutetzy7ua6/test-1MB555.txt?dl=0

PS. Markor opens bigger files at least a few times slower than *Jota Text Editor*. This causes lags on Markor app opening when I have a bigger file set as QuickNote (that's the way in my case, because I normally use something, that we could name a diary, as a QuickNote file). Is there any place to some speed optimizations?

#### Log

12-17 18:28:40.188  2597  9426 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=net.gsantner.markor/.activity.MainActivity bnds=[438,703][643,1016]} from uid 10042
12-17 18:28:40.279  2597  2720 I ActivityManager: Start proc 13843:net.gsantner.markor/u0a147 for activity net.gsantner.markor/.activity.MainActivity
12-17 18:28:41.117  2597  2720 I ActivityManager: Start proc 13893:com.android.webview:sandboxed_process0/u0i76 for webview_service net.gsantner.markor/org.chromium.content.app.SandboxedProcessService0
12-17 18:28:41.878  2597  9426 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=net.gsantner.markor/.activity.MainActivity bnds=[438,703][643,1016]} from uid 10042
12-17 18:28:42.512  2597  2717 I ActivityManager: Displayed net.gsantner.markor/.activity.MainActivity: +2s312ms
12-17 18:28:48.077  2597 12760 I ActivityManager: START u0 {flg=0x10000 cmp=net.gsantner.markor/.activity.SettingsActivity} from uid 10147
12-17 18:29:01.447   524   702 D SurfaceFlinger: duplicate layer name: changing net.gsantner.markor/net.gsantner.markor.activity.SettingsActivity to net.gsantner.markor/net.gsantner.markor.activity.SettingsActivity#1
12-17 18:29:15.455   524  1099 W SurfaceFlinger: Attempting to set client state on removed layer: net.gsantner.markor/net.gsantner.markor.activity.SettingsActivity#1
12-17 18:29:15.455   524  1099 W SurfaceFlinger: Attempting to destroy on removed layer: net.gsantner.markor/net.gsantner.markor.activity.SettingsActivity#1
12-17 18:29:18.664  2597  9426 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10210000 cmp=net.gsantner.markor/.activity.MainActivity bnds=[438,703][643,1016]} from uid 10147
12-17 18:29:21.478   524   701 W SurfaceFlinger: Attempting to destroy on removed layer: AppWindowToken{a02c907 token=Token{6296346 ActivityRecord{a831321 u0 net.gsantner.markor/.activity.SettingsActivity t3225}}}#0
12-17 18:29:27.504  2597  5375 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=net.gsantner.markor/.activity.MainActivity bnds=[438,703][643,1016]} from uid 10042
12-17 18:29:29.244  2597  2717 I ActivityManager: Displayed net.gsantner.markor/.activity.MainActivity: +1s726ms
12-17 18:29:29.742   524   702 W SurfaceFlinger: Attempting to set client state on removed layer: Surface(name=AppWindowToken{ca68b69 token=Token{90709f0 ActivityRecord{cde233 u0 net.gsantner.markor/.activity.MainActivity t3227}}})/@0x2ab3ea1 - animation-leash#0
12-17 18:29:29.742   524   702 W SurfaceFlinger: Attempting to destroy on removed layer: Surface(name=AppWindowToken{ca68b69 token=Token{90709f0 ActivityRecord{cde233 u0 net.gsantner.markor/.activity.MainActivity t3227}}})/@0x2ab3ea1 - animation-leash#0
12-17 18:29:34.239  2597  2610 I ActivityManager: START u0 {flg=0x10000 cmp=net.gsantner.markor/.activity.SettingsActivity} from uid 10147
12-17 18:29:34.530 13843 13843 E AndroidRuntime: Process: net.gsantner.markor, PID: 13843
12-17 18:29:34.534  2597  2610 W ActivityManager:   Force finishing activity net.gsantner.markor/.activity.SettingsActivity
12-17 18:29:34.647  2597  4076 I WindowManager: WIN DEATH: Window{81a197f u0 net.gsantner.markor/net.gsantner.markor.activity.SettingsActivity}
12-17 18:29:34.649  2597 16192 I ActivityManager: Process net.gsantner.markor (pid 13843) has died: fore TOP 
12-17 18:29:34.651  2597  2947 W InputDispatcher: channel '2b964ab net.gsantner.markor/net.gsantner.markor.activity.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
12-17 18:29:34.651  2597  2947 E InputDispatcher: channel '2b964ab net.gsantner.markor/net.gsantner.markor.activity.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
12-17 18:29:34.652  2597  3407 I WindowManager: WIN DEATH: Window{2b964ab u0 net.gsantner.markor/net.gsantner.markor.activity.MainActivity}
12-17 18:29:34.653  2597  3407 W InputDispatcher: Attempted to unregister already unregistered input channel '2b964ab net.gsantner.markor/net.gsantner.markor.activity.MainActivity (server)'
12-17 18:29:34.663   524   701 W SurfaceFlinger: Attempting to set client state on removed layer: net.gsantner.markor/net.gsantner.markor.activity.SettingsActivity#0
12-17 18:29:34.663   524   701 W SurfaceFlinger: Attempting to destroy on removed layer: net.gsantner.markor/net.gsantner.markor.activity.SettingsActivity#0
12-17 18:29:34.665  2597 16192 W ActivityManager: Force removing ActivityRecord{cde233 u0 net.gsantner.markor/.activity.MainActivity t3227}: app died, no saved state
12-17 18:29:34.674   524  1549 W SurfaceFlinger: Attempting to destroy on removed layer: AppWindowToken{ca68b69 token=Token{90709f0 ActivityRecord{cde233 u0 net.gsantner.markor/.activity.MainActivity t3227}}}#0
12-17 18:29:37.375  2597 16192 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=net.gsantner.markor/.activity.MainActivity bnds=[438,703][643,1016]} from uid 10042
12-17 18:29:37.422  2597  2720 I ActivityManager: Start proc 14167:net.gsantner.markor/u0a147 for activity net.gsantner.markor/.activity.MainActivity
12-17 18:29:37.880  2597  2720 I ActivityManager: Start proc 14205:com.android.webview:sandboxed_process0/u0i77 for webview_service net.gsantner.markor/org.chromium.content.app.SandboxedProcessService0
12-17 18:29:39.502  2597  2717 I ActivityManager: Displayed net.gsantner.markor/.activity.MainActivity: +2s114ms
12-17 18:29:42.778 14167 14167 E AndroidRuntime: Process: net.gsantner.markor, PID: 14167
12-17 18:29:42.784  2597 12760 W ActivityManager:   Force finishing activity net.gsantner.markor/.activity.MainActivity
12-17 18:29:42.797  2597  2719 I ActivityManager: Showing crash dialog for package net.gsantner.markor u0
12-17 18:29:45.705  2597 12760 W ActivityManager:   Force finishing activity net.gsantner.markor/.activity.MainActivity
12-17 18:29:45.719  2597 12760 I ActivityManager: Killing 14167:net.gsantner.markor/u0a147 (adj 901): crash
12-17 18:29:45.733   524  1549 W SurfaceFlinger: Attempting to destroy on removed layer: AppWindowToken{96fee67 token=Token{fe84226 ActivityRecord{948a181 u0 net.gsantner.markor/.activity.MainActivity t3228}}}#0
12-17 18:29:45.734   524  1549 W SurfaceFlinger: Attempting to destroy on removed layer: 297d1ac net.gsantner.markor/net.gsantner.markor.activity.MainActivity#0
12-17 18:29:45.889   524  1549 W SurfaceFlinger: Attempting to destroy on removed layer: e640370 Application Error: net.gsantner.markor#0

**Comment by gsantner** [comment]
I suggest to use a smaller file for QuickNote and split off text chuncks and pieces that belong together.
QuickNote is not made to fit big amount of text but to be fast, every text more lowers the speed.
Unfourtunatly cannot do much about that without creating completely new editor and overall Markor app.
