### ISSUE TITLE
Multiple todo.txt files

### ISSUE THREAD

**Issue by shawn1thompson** [gsantner/markor#805]
#### General information

* **2.2.3 (104)** 
* **Android v. 9** 

#### Description
I see that theoretically it is possible to have multiple todo.txt files, but I'm unsure practically how it works in the app. I have a todo.txt and a someday.txt that I use. I have the todo tab pointed at my todo.txt file in the settings.

**Comment by macdonaldster** [comment]
Hey, I often keep multiple TODO.txt files. When I edit them in the app, I need to switch the "Format" of the file (upper left when in file, three vertical dots menu, Format, todo.txt). You are then good to edit that file as a TODO.txt file. However, this format designation is not "sticky". You have to reset it (for me, anyway) whenever I edit the file again (e.g. jump to different file, etc).

It would be nice if:

1. The application maintained a db of files and their preferred format (in a "dot file", in a small db, or even just in memory, I guess?)

2. There was an emacs like file spec header (I prefer footer, but whatever) that could act as a filespec for the Markor editor (e.g. "; -*- mode: todo.txt;-*-"). I personally find this kind of thing a little "in the way" but it does work.

**Comment by gsantner** [comment]
Name files like `something.todo.txt` or `todo.something.txt` and it will always be loaded in todo.txt :-)

**Comment by macdonaldster** [comment]
Hey, I know this issue is closed but I JUST figured this out by accident the other day when I created a new TODO file and chose the todo.txt format ON CREATE... it named it '2019-12-29.todo.txt'... GAME CHANGER. :) This app continues to surprise and delight me.

**Comment by gsantner** [comment]
the date comes from when you select the Jekyll option once shortly

**Comment by macdonaldster** [comment]
Sorry, I have a Texpand replacement (bound to "dddd") to create that date filename. I meant the todo.txt suffix was added when I selected the format.

**Comment by gsantner** [comment]
ah :D
Yeah thats intentional
