### ISSUE TITLE
customize editor style for todo.txt format

### ISSUE THREAD

**Issue by blendmaster** [gsantner/markor#809]
As of version 2.2.3 (105), the editor for todo.txt format in dark mode adds a bright white line between each task in the file. I personally think it's too bright and visually noisy, but couldn't find a way to change it. I saw in view mode settings you can inject custom CSS, but there doesn't seem to be an equivalent for the editor mode. I think it'd be nice to have the same thing for the editor, either straight CSS injection or customizable colors.

**Comment by gsantner** [comment]
can you confirm this is about EDITOR and not about VIEWER?

**Comment by blendmaster** [comment]
Yes, this is the editor mode (pencil), not the viewer mode (eye). I was able to use the custom CSS to hide the `<hr/>` in viewer mode actually.

**Comment by gsantner** [comment]
Ok thanks.

For editor custom styling is not planned currently
