### ISSUE TITLE
MD: let any list item be a checkbox

### ISSUE THREAD

**Issue by contrapunctus-1** [gsantner/markor#813]
## Situation
```
* foo|
```

User presses the checkbox button.

## Current outcome

v2.2.4, F-Droid, Android 9, Nokia 6.1 (TA-1089)

```
- [ ] * foo|
```

## Requested outcome
```
* [ ] foo|
```

**Comment by gsantner** [comment]
In all specs and typed markdown I saw `- [ ]` is used. I don't want to add another option, which again is incompatible with most other stuff.
