### ISSUE TITLE
Feature request: Implement scoped directory access

### ISSUE THREAD

**Issue by mcladyz** [gsantner/markor#814]
Please implement [scoped directory access](https://developer.android.com/training/articles/scoped-directory-access) so that READ_EXTERNAL_STORAGE & WRITE_EXTERNAL_STORAGE are no longer needed.

Scoped directory access is new in Android 10.

**Comment by gsantner** [comment]
I currently dont plan todo so, open for community contribution.
For Android 10 its optional and not mandatory.

**Comment by increasingawareness** [comment]
I think this is worth revisiting as apps that target Android 11 will need to implement Scoped Storage: https://developer.android.com/preview/privacy/storage

> To give developers additional time for testing, apps that target Android 10 (API level 29) can still request the requestLegacyExternalStorage attribute. This flag allows apps to temporarily opt out of the changes associated with scoped storage, such as granting access to different directories and different types of media files. After you update your app to target Android 11, you cannot use requestLegacyExternalStorage to opt out of scoped storage.

See this [Android Developer's Medium post for more details](https://medium.com/androiddevelopers/modern-user-storage-on-android-e9469e8624f9)

**Comment by gsantner** [comment]
I dont have any Android 11 upgradable 11 nor I plan to buy one.

I'm not statisfied with recent Android changes locking everything down.

**Comment by increasingawareness** [comment]
So the users are no longer the priority? I love this app and am thankful for all the work you've put into it, but it doesn't make any sense not to target the next API, especially if you want people to keep using it. Would you be open to pull requests that implement a target for API 30 (Android 11)? I can start testing in Android Studio in a few weeks to see what I can come up with if you're open to it.

**Comment by gsantner** [comment]
I'm open for pull requests, but as long API 29 is accepted on Google Play I will keep it.
Also, it doesn't much matter which API, it's mainly a Google Play enforcement. E.g. on F-Droid it's still possibile to submit e.g. API23 if required. Theres a world outside Google Play. And for Markor even I think the outside is half if not bigger.

**Comment by mcladyz** [comment]
> I'm not statisfied with recent Android changes locking everything down.

But don't you see the benefits of the change? Isn't it better to grant the application access to only specific places unless the user definitely wants it to access everything?

**Comment by gsantner** [comment]
For an app that basically is a filemanager? no.

And as said, project is open for community contributions.
