### ISSUE TITLE
Markdown: Escape square brackets in link text

### ISSUE THREAD

**Issue by contrapunctus-1** [gsantner/markor#815]
## Situation
User presses 📎 - Insert Link, writes "[1]" in Description and "foo" in URL/Path.

## Current outcome

v2.2.4, F-Droid, Android 9, Nokia 6.1 (TA-1089)

```
[[1]](foo)
```

Which does not render as expected in Markor's view mode. (Not sure what Common Mark specifies for this input?)

## Requested outcome
```
[\[1\]](foo)
```

**Comment by gsantner** [comment]
The number seems to be in reference link style (<https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links>). I don't want to make magically changes on what the user types in.
