### ISSUE TITLE
ugly cursor in todo mode

### ISSUE THREAD

**Issue by 532910** [gsantner/markor#818]
#### General information

* **App version:** 2.2.5 (107) from f-droid
* **System:** LNGOS 16 on android 9 op3t

#### Description
on the first line cursor looks good, on the second --- does not:

![image](https://user-images.githubusercontent.com/14617699/72002765-19875880-3259-11ea-8215-eaef36bf81ce.png)
![image](https://user-images.githubusercontent.com/14617699/72002845-463b7000-3259-11ea-89bb-d27d6df9c353.png)

**Comment by gsantner** [comment]
thanks for the report.

I had a quick look into it and I can reproduce it the same way. However I don't plan to make the cursor size dynamically. Actually I like it that way :smiley:

**Comment by 532910** [comment]
But the cursor size is already dynamic! And the solution to make it static (always the same as on the first line).
