### ISSUE TITLE
Changelog: Black on gray is badly visible

### ISSUE THREAD

**Issue by 532910** [gsantner/markor#819]
#### General information

* **App version:** 2.2.5 (107) from f-droid
* **System:** LNGOS 16 on android 9 op3t

#### Description
Black on gray is badly visible:

![image](https://user-images.githubusercontent.com/14617699/72002980-80a50d00-3259-11ea-9aef-f0ec7d7551b7.png)

**Comment by gsantner** [comment]
Just browsing through issues and fixing lots of minor stuff. I don't feel this is tooooo bad and keep it rather simple, as is.
