### ISSUE TITLE
color in TODO doesn't work

### ISSUE THREAD

**Issue by 532910** [gsantner/markor#821]
#### General information

* **App version:** 2.2.5 (107) from f-droid
* **System:** LNGOS 16 on android 9 op3t

#### Description
Steps to reproduce:

1. Open TODO in editor mode
2. Press `clip` button -> `Color`
3. Select Foreground or Background color
4. In both editor and view modes it will look unrendered:

![image](https://user-images.githubusercontent.com/14617699/72004023-97e4fa00-325b-11ea-9981-87b0436c1b3d.png)

**Comment by gsantner** [comment]
this is not really expected, todo is a plain text file, not html or markdown. so it's also rendered just as text.

The attach dialog is same across all formats, don't plan to magically hide options currently.
