### ISSUE TITLE
Sometimes widget is empty

### ISSUE THREAD

**Issue by 532910** [gsantner/markor#822]
#### General information

* **App version:** 2.2.5 (107) from f-droid
* **System:** LNGOS 16 on android 9 op3t

#### Description

Sometimes widget is empty. I don't know how to reproduce it. Killing the app doesn't help.

![image](https://user-images.githubusercontent.com/14617699/72004303-2c4f5c80-325c-11ea-9b68-6be4e36d637a.png)

**Comment by doctor-owl** [comment]
Yep this is happening to me too on Samsung Galaxy S9+. I'm not sure what triggers it but it happens a few times per day. I have to remove the widget and replace it to make it work again. Also one time it randomly switched to light theme despite the app still being in dark mode.

**Comment by gsantner** [comment]
Notice for all widget issues and feature requests: I'm not actively working on the widget (and never really have). I'm fully waiting for community contribution on this.

Beside PR review and tests by me, full community work on the widget feature is expected. So if you read this, please go for it, thanks. :smiley:.

**Comment by gsantner** [comment]
Thanks to @stefanfris who worked on widgets recently. Do you want to take a look into widgets again?
Would be very nice, thanks!

**Comment by 532910** [comment]
> but it happens a few times per day

It's significant rare for me. (About one a week)

> I have to remove the widget and replace it to make it work again.

This workaround works for me too.

> Also one time it randomly switched to light theme despite the app still being in dark mode.

I've also seen this once.

**Comment by StarTroop** [comment]
For whatbit's worth, I've noticed the wodget going empty whenever I rotate my screen into landscape mode. This was reproducable when I had my launcher (Trebuchet) set to rotate the homescreen. I've since disabled that setting, but if I ever go into landacape mode in another app, the widget empties once more.
A reboot also temporarily fixes the widget.
I will disable auto-rotate entirely for a while to see if it's successful in preventing this issue.
Wish I was able to help more.

**Comment by gsantner** [comment]
Please retry when v2.5.0 comes out, as far I can see there were some improvements recently. Though I don't use widgets at all.

**Comment by 532910** [comment]
Not fixed.

![image](https://user-images.githubusercontent.com/14617699/101956967-95c8af80-3c11-11eb-948f-d608a61b47d8.png)

I don't use widgets too, but how is that related?

**Comment by sotitrox** [comment]
This is still happening in the last version

**Comment by gsantner** [comment]
Repeating: if somebody wants it fixed, fix it and send a PR.

**Comment by harshad1** [comment]
@sotitrox Several widget improvements have been made recently (and I am working on more). Are you still seeing this bug? If so, on which launcher?

**Comment by sotitrox** [comment]
last week I put one widget again, and this is working fine, no problem at this time 👌👌👌
