### ISSUE TITLE
todo.txt Archive dialog: Bad layout at buttons

### ISSUE THREAD

**Issue by 532910** [gsantner/markor#823]
#### General information

* **App version:** 2.2.5 (107) from f-droid
* **System:** LNGOS 16 on android 9 op3t

#### Description
`Cancel` & `OK` buttons are truncated:

![image](https://user-images.githubusercontent.com/14617699/72004742-11c9b300-325d-11ea-9c8a-c11bfaf93592.png)

**Comment by gsantner** [comment]
Reduced vertical space so buttons can fit more easily

![Screenshot_20200502-162006_Mordor](https://user-images.githubusercontent.com/6735650/80866805-4fc16b80-8c80-11ea-9a06-b19df74daaf4.png)
![Screenshot_20200502-162027_Mordor](https://user-images.githubusercontent.com/6735650/80866806-50f29880-8c80-11ea-9a41-a9b8668498be.png)
