### ISSUE TITLE
Cleared todos/quicklist not saved: permit saving empty files

### ISSUE THREAD

**Issue by r3r57** [gsantner/markor#824]
#### General information

* **App version:** 2.2.5 F-Droid
* **System:** Android 9, Honor Play

#### Description
I'd like to suggest to revert https://github.com/gsantner/markor/commit/cb4ff38f488cfef1efb8906e7eebf734721d54f3 to permit saving empty files. I found it kinda counterintuitive since I often delete my whole todos or quicklist.
I could not reproduce https://github.com/gsantner/markor/issues/689 which might occur under certain - and apparently rare - circumstances.

Nevertheless, this bug exists/existed, so maybe we could keep this issue open and see if there are other users, which wonder why their cleared todos/quicklist is not saved properly.

I'll do my best to identify what caused https://github.com/gsantner/markor/issues/689.

**Comment by gsantner** [comment]
It comes out of a combination of permission requests (you didn't grant yet, hence nothing loaded, but then something is loaded and you save), plus file read speed. Especially SD Cards are slow as hell due storage access framework.

I currently don't plan changes on this, save a empty dot in this case - thanks :smiley: :+1: .

In any case, one person wondering about non-empty file is much better than two losing a files contents.

**Comment by JohnVeness** [comment]
I've been hit by this issue too, while blanking the contents of another textfile (not todo or quicknote) and noticing it doesn't save. Does #689 only occur on those two special files? If so, maybe you could only not save those two files, rather that not saving any file.

Also, maybe show a warning to the user when trying to save an empty file so they know what's happened?

**Comment by uraza** [comment]
I ended up here because not being able to clear the content of todo.txt and QuickNote.md looks really weird. :)
It looks like the commit done for #689 was more a workaround, since @gsantner was not able to reproduce it on his side.
