### ISSUE TITLE
Mathematical Syntax incompatible with TeX: double escapement of curly brace

### ISSUE THREAD

**Issue by argmaxmax** [gsantner/markor#825]
#### General information

* **App version:** v2.2.3 (105) Google Play Store
* **System:** OnePlus 6, Android 9: OxygenOS 9.0.9

#### Description

As a Mathematician using Vim-Wiki on my Linux System to keep a Wiki consisting of Markdown FIles and Links between them, I rely heavily on TeX Support for Mathematical Typesetting in single and double dollar brackets. 

But I noticed on sync with my phone, that in Markor the Syntax is incompatible with TeX. in TeX you would write `$ \{ $` for a left curly brace. This renders as a curly brace.

In Markor however, it doesn't render at all. In order to write a left curly brace, you have to double escape the brace: `$ \\{ $`. 

This is a **huge dealbreaker** for Mathematicians since Markor is completely incompatible with all written papers and in general typed Math, because curly braces are ubiquitious in Math (Sets, Maps, Transforms, etc.).

Therefore it would be amazing to be able to continue using this marvelous app by implementing a Markdown Mathematics Interpretation without double escapement.

**Comment by gsantner** [comment]
Please ask at KaTex github first.
Note that KaTex or Markor is not LaTex, even if it sounds similar!

**Comment by argmaxmax** [comment]
In Standard KaTeX the syntax is exactly like in TeX. In every other distribution of KaTeX I use (vim-instant-markdown, Typora, Dynalist) it is also handled like in TeX.

So it is not a KaTeX issue, it is an implementation issue. 
I am not sure but looking in the way the Markdown Parser treats escapement might relieve it. 

The point is, Markor was a promising Markdown App, but it seems Mathematicians are losing out.

**Comment by gsantner** [comment]
Wrap in a div to disable markdown for a section.

```
<div>
$ \{ $
</div>
```

I get a curly brace (only) with this.

**Comment by argmaxmax** [comment]
Hello @gsantner , this is not a feasible solution.
It requires you to surround every math zone in every document, which is a tremendous amount of manual work; and because there is no concept of a `<div>` in Markdown syntax. Also, in Standard KaTeX, the Math Syntax follows TeX Syntax.

This should be an open issue.

I again say this is a dealbreaker for Mathematicians and everyone who regularly uses Math.
