### ISSUE TITLE
Sometimes floating Plus button dont show New note dialog

### ISSUE THREAD

**Issue by kai11** [gsantner/markor#826]
#### General information

Package: net.gsantner.markor
Version: v2.2.3 (105)
Flavor: Gplay (release)
Build date: 2019-11-09T14:58Z
ISource: Google Play Store
VCS Hash: cefb99c938f7ef3c23962758e6ca91dc660a8152

Phone: Moto Z Play
System: 8.0.0

#### Description
Sometimes floating plus button dont show new note dialog.
I cannot reprodice this reliably, but it usually happens when app was opened, backgrounded, then left like this for a while.
Swiping app out from history and reopening always fixes it - plus button will show new note dialog.
Bug frequency: once or twice per week with few times during day usage.

#### Log
Not yet.

**Comment by gsantner** [comment]
let me know when theres a **reliable** way to reproduce, if even still a issue.
