### ISSUE TITLE
Add grid layout to file manager (alternative)

### ISSUE THREAD

**Issue by dhebbeker** [gsantner/markor#828]
#### General information

* **App version:** v2.2.5 (107)
* **System:** Android 9

#### Feature request

Provide a tiles-view of the notebook folder. The current view as list contains details, which may not be directly important for the every-day usage: File extension and date and time of the file. 

I suggest to provide an additional view, where every compatible file and folder is displayed as a tile. The name (without extension) is displayed within each tile. Tiles of files and folders are differentiated by form or colour. This shows more items to the user on the first sight and allows a quicker workflow to open the desired file.

Here is a self-made sketch: <img src="https://user-images.githubusercontent.com/1594340/72384580-0b847c80-371e-11ea-9d7c-9ebbac9a1dbf.png" width=400>

**Comment by gsantner** [comment]
You mean a grid as alternative representation. right?

**Comment by dhebbeker** [comment]
Yes! For example:
1. This <img src="https://content.intland.com/hs-fs/hubfs/Imported_Blog_Media/project_browser_faster_access-336x336.png?width=336&height=336&name=project_browser_faster_access-336x336.png">
2. This https://codepen.io/zavoloklom/pen/wtApI

The tiles may all have the same size (as in a grid).

**Comment by gsantner** [comment]
OK.

I'm assigning this to community milestone, so leaving this open for community contribution.

Important for me is the latter, uniformed size of each grid element.

**Comment by dhebbeker** [comment]
Thanks! Here is a self-made sketch: <img src="https://user-images.githubusercontent.com/1594340/72384580-0b847c80-371e-11ea-9d7c-9ebbac9a1dbf.png" width=400>

**Comment by gsantner** [comment]
I want to keep the filemanger simple and leanint and list should be enough.

Closing.
