### ISSUE TITLE
tooltips for editor tools

### ISSUE THREAD

**Issue by dhebbeker** [gsantner/markor#829]
#### General information

* **App version:** v2.2.5 (107)
* **System:** Android 9

#### Feature request

For those who use this app for the first time, or those who forget (like me :wink:), it could be useful to have tooltips for the tool icons which are located at the bottom of the editor: <img src="https://raw.githubusercontent.com/gsantner/markor/master/metadata/en-US/phoneScreenshots/02.jpg" width=350>

In my opinion, some icons are not self-evident and would be hard or impossible to improve. And some look like I would rather not try them in a productive file (like the [`delete`](https://material.io/resources/icons/?icon=delete) or the [`open_in_browser`](https://material.io/resources/icons/?icon=open_in_browser) icons).

I suggest to add **[tooltips](https://material.io/components/tooltips/#placement)** to all tool icons. The tooltips would be [displayed through long press](https://storage.googleapis.com/spec-host-backup/mio-components%2Fassets%2F0B8wSqcLwbhFuZVFJeXRLd3hlM0E%2Fbaseline-video-list.mp4): <img src="https://storage.googleapis.com/spec-host-backup/mio-components%2Fassets%2F0B54x0KDcs5U-a0Vrdnlib1R5TFk%2Ftooltip-usage-do.png" width=500>

**Comment by gamato** [comment]
Also btw tooltips are displayed when the app is used in desktop mode (e.g. in Samsung DeX), so it is useful to have them wherever possible (as is a good custom in desktop GUIs).

**Comment by dhebbeker** [comment]
> Also btw tooltips are displayed when the app is used in desktop mode

Thanks for the tip @gamato! Apparently the "[content description](https://developer.android.com/reference/android/view/View.html#attr_android:contentDescription)" of the text actions are visible in desktop mode. Unfortunately I have no setup to test it. It should be possible to use the same string when [setting the tooltip](https://developer.android.com/reference/androidx/appcompat/widget/TooltipCompat.html#setTooltipText(android.view.View,%20java.lang.CharSequence)).
