### ISSUE TITLE
Disabling option Launcher (Special documents) make every app icon disappear

### ISSUE THREAD

**Issue by VariabileAleatoria** [gsantner/markor#830]
#### General information

* **App version:** 2.2.5
* **System:** Android 9, MIUI 11

#### Description
Unchecking the feature option "Launcher (Special documents) to hide To-Do and QuickNote icons from app drawer, makes disappear every icon of the Markor app from MIUI launcher.
Would it be possible for a drawer-less launcher as this to have only one icon instead of three?

**Comment by gsantner** [comment]
With enabled it should be 4 (3 + Markor), otherwise 1.

**Comment by VariabileAleatoria** [comment]
I rarely reboot so I didn't thought trying, silly me, it worked.

Btw with enabled they are 3 (Markor + To-Do + QuickNote)

**Comment by gsantner** [comment]
alright
