### ISSUE TITLE
What the heck happened to hiding textactions?

### ISSUE THREAD

**Issue by ohenepee** [gsantner/markor#833]
#### General information

* **App version:**  Latest Update
* **System:** Android 7.1

#### Description
After the latest update (as at now) from Play Store, I can't find the option to hide the textactions bar which sits right above the virtual keyboard... I edit plain text files, hence have no need for this bar which is stealing PRECIOUS screen real estate... Is there any reason why that option is gone?

**Comment by gsantner** [comment]
The bar is now always visible, and there is no option anymore. This was always a niche use and has made issues for some users. This as a option is gone for the good.
The bar and it's contents is pretty much the most important feature of Markor.

A hide option won't come back.
