### ISSUE TITLE
List elements indented by over 6 spaces are highlighted

### ISSUE THREAD

**Issue by harshad1** [gsantner/markor#838]
#### General information

* **App version:**  2.2.5 (107) F-Droid
* **System:** Stock Android 10 on Pixel 3 XL

#### Description
In markdown files, any list items indented by over 6 spaces appear highlighted. This i's especially troublesome as I prefer a using 4 spaces for 'tab'.
```
- Indent 0 spaces
  - Indent 2 spaces
    - Indent 4 spaces
      - Indent 6 spaces <- This row and any rows with an equal or greater indent will be highlighted
```

**Comment by harshad1** [comment]
![Screenshot_20200122-212128](https://user-images.githubusercontent.com/1940940/72959013-cc79ab00-3d5d-11ea-8a83-e220fc7075ea.png)

**Comment by gsantner** [comment]
duplicate and wontfix #250
