### ISSUE TITLE
App Settings backup & restore

### ISSUE THREAD

**Issue by anishmittal2020** [gsantner/markor#839]
It will be useful if we can export and import app settings (such as `settings.json`).

**Comment by gsantner** [comment]
Storage format of settings is xml (android preferences xml), hence format should be xml not json.

**Comment by opensource21** [comment]
At [Stackoverflow](https://stackoverflow.com/questions/5951418/android-viewing-sharedpreferences-file) is an example of export. However, in the example the type information are lost. So this must be added to enable import. I didn't find any information about a standard xml format, so I would guess that json-serializing would be an easier to implement option.

**Comment by gsantner** [comment]
The settings (preferences.xml) can be backed up as is, and restored. However after restore a immediate app exit is required so app doesn't re-overwrite settings. Next time it boots with restored settings.

We do exactly this in OpenLauncher project, please have a look on that
