### ISSUE TITLE
Insert link to file using original file, not the copied version

### ISSUE THREAD

**Issue by GertVanKruiningen** [gsantner/markor#841]
#### General information
Adding link to file in markdown document

* **App version:** v2.2.6
* **System:** Android

#### Description
I have a folder structure with lots of documents like .pdf and .mp3.
This structure is separate from where my markdown documents are.
I and want to create a link to these files in my markdown documents I am editing in Markor.
But when I add this link, it comes with an option to copy this file !

Is it possible to not copy the file, and just use the "absolute" address of the file that I want to link into the markdown document in Markor?

**Comment by gsantner** [comment]
There are three options at the dialog. The second, cancel option does exactly that, insert the absolute path.
