### ISSUE TITLE
Custom reordering of toolbar options

### ISSUE THREAD

**Issue by raoul-van-oosten** [gsantner/markor#844]
#### General information

* **App version:** 2.2.6
* **System:** Android

#### Description

It would be great if the options on the Markdown toolbar could be reordered. I indent a lot, but right now it is quicker to manually insert four spaces than it is to click on the Special Key button, scroll down and click on Indent.

**Comment by gsantner** [comment]
This is an option, but unsure if and when this will make it (if ever).

It might be possible that there is a completly different UI than the current bottom bar, making this obsolte.

**Comment by harshad1** [comment]
I too would really like this.

@gsantner For now, would you be willing to move the indent and de-indent buttons to the main bar? Perhaps to the right of the Accordion key.

I would be happy to contribute a PR for this.

**Comment by gsantner** [comment]
I rather do not want additional options in the bar. Time is way better spent on looking into "custom order".

**Comment by harshad1** [comment]
@gsantner I am starting to look at reordering action items.

Here is how I am thinking of making this work:

1. Add a `Reorder Actions` option under Format->Markdown and Format->Todotxt
2. Clcking this will open a RecyclerView in which we can hold and drag to rearrange the actions. Top to bottom = left to right.
3. There will be an 'overflow' item in the RecyclerView. Any actions ordered after the overflow menu will not appear directly in the action bar. Instead they will be accessible through an overflow dialog which can be launched by pressing the overflow action.
4. The overflow action will always be the last action on the action bar
5. All items currently in the 'special key' section will be converted to regular actions

What do you think?

**Comment by gsantner** [comment]
@harshad1 
1. Yes but we also need K-V and plaintext menus then similar to md/tt
2. sounds good, but please don't add additional libraries just for dragging. also please just implement this once and pass the values for each format into recyclerview. (these are actually the tmaid's etc which are defined already with ID and tooltip for each format..so you don't need to re-invent the wheel with new identifier)
3. Yes
4. Yes
5. Not sure on this one. Please atm keep SpecialKey as is.

**Comment by harshad1** [comment]
>     1. Yes but we also need plaintext submenu then similar to md/tt.
Good point, I'll add one

>     2. sounds good, but please don't add additional libraries just for dragging. also please just implement this once and pass the values for each format into recyclerview. 

Yes. I don't plan on making a separate UI per filetype :) 

> (values passed gonna be ID's in string form... tmaid's etc which are defined already with ID and tooltip for each format..so you don't need to re-invent the wheel with new identifier)

Sounds reasonable. I am curious as to why you used strings instead of IDs though (`R.id.foo`).

>     5. Not sure on this one. Please atm keep SpecialKey as is.

Part of the motivation for making action items re-orderable is so that I can move the indent and de-indent buttons to the front of the main action items row. Would you be ok if I converted only Indent and De-indent from special keys to actions?

**Comment by gsantner** [comment]
> Sounds reasonable. I am curious as to why you used strings instead of IDs though (R.id.foo).

Exactly for the reason that IDs cannot be input, the user cannot guess the numbers of element :D. But..users can enter strings. So we need something based on strings for ID. We can have the string wrapped in strings.xml, but in the end we will require some matching from input string id to run the action.

> Part of the motivation for making action items re-orderable is so that I can move the indent and de-indent buttons

I see, yeah you can move them of course. But I will make thoughts later on about others...like insert OHM sign.

**Comment by harshad1** [comment]
> Exactly for the reason that IDs cannot be input, the user cannot guess the numbers of element :D. But..users can enter strings. So we need something based on strings for ID. We can have the string wrapped in strings.xml, but in the end we will require some matching from input string id to run the action.

Where is user input of string key used? The only place I can think of is SearchOrCustomTextDialog

**Comment by gsantner** [comment]
Guess that will be also part, to clarify and unify the way actions are called, and that they can be invoked by a string

**Comment by gsantner** [comment]
Hey everybody, heres a sneak-peek of what is coming soon :wink: 

![Screenshot_20200418-200349_Mordor](https://user-images.githubusercontent.com/6735650/79645448-c86bf680-81af-11ea-9f72-874b2e58744f.png)

**Comment by harshad1** [comment]
This hasn't been implemented and imo is a low priority.

(The last couple toolbar improvements have been made by me and I don't have any plans to do this).

Nov 26, 2023 12:06:31 dcdom2 ***@***.***>:
