### ISSUE TITLE
quick navigation pageup/pagedown

### ISSUE THREAD

**Issue by zeguramente** [gsantner/markor#846]
#### General information

* **App version:**2.2.6 
* **System:** Android 6 

#### Description
I have now switched from odt to markdown and I'm editing bigger files (>200 DINA4 pages).
For scrolling I used pageup pagedown extensivly (hackers keyboard). At my 8 inch tablet it's faster than swiping.

In Markor it's not switching the complete page (ok there are no pages any more :-))
So it would be great to switch the complete displayed text to the next block (filling display with text) via pageup/pagedown or a navigation button.

I hope my description is understandable :-)

**Comment by gsantner** [comment]
I had this in mind long time back already, it's already there:


![video_2020-02-09_11-14-15](https://user-images.githubusercontent.com/6735650/74100289-0e0fa180-4b25-11ea-9ae6-5517cb592021.gif)
