### ISSUE TITLE
Huge Cache usage

### ISSUE THREAD

**Issue by 532910** [gsantner/markor#847]
#### General information

* **App version: 2.2.6 (108) from f-droid** 
* **System: LNGOS 16 on android 9 op3t** 

#### Description
My total notes size is:
```
% du -sh notes 
920K	notes
```
But cache size is 337Mb!:
![image](https://user-images.githubusercontent.com/14617699/74099039-4ff21500-4b30-11ea-991e-465836d7aca4.png)

**Comment by gsantner** [comment]
have you tried voice recording?

**Comment by 532910** [comment]
Yes, I have tried voice recording and removed it.
Yes, there is `/data/data/net.gsanter.markor/recording.wav` that weights 336MB and dated 3 Nov.
Why it wasn't deleted?

**Comment by gsantner** [comment]
It's kept in cache for the reason that you may not have fully or correctly copied the file from record cache. Which can happen when you force kill the app.

Also: It allows you to restore the last recording in case you accidentally clicked close.
I want to keep it like this. You can always clear the cache if you want to. So a file that I want to be cached in a cache folder, correct functioning.

**Comment by 532910** [comment]
I know how to clear cache, but from the point of view of a simple user it's storage wasting.
