### ISSUE TITLE
Sorting by date does not persist

### ISSUE THREAD

**Issue by Zverik** [gsantner/markor#849]
#### General information

* **App version:** 2.2.6 (108) from Google Play
* **System:** Android 8.0.0 on Sony Xperia X Compact

#### Description

1. Navigate to a directory with many files.
2. Change sorting to "By date".
3. Close the app.
4. Reopen it.

Expected: Files are sorted by date.
Actual: Files are sorted by name.

See two screens: one after the app was re-open, another after I clicked "Sort by date" again.

![markor-before-after](https://user-images.githubusercontent.com/766031/74223649-3f74a280-4cc8-11ea-98b4-98f73203f6b1.png)

Similar to #545, might be a regression somewhere.

**Comment by gsantner** [comment]
Can you please install latest update?

I tried and cannot reproduce, saved&restored for me.

**Comment by Zverik** [comment]
Maybe it's because that folder is constantly updated with Syncthing, so new files appear, and caches somewhere inside Markor get invalidated?
