### ISSUE TITLE
Widget always opens file in editor mode

### ISSUE THREAD

**Issue by kRkk** [gsantner/markor#85]
#### General information

* **Device:**   Nokia 6
* **Android Version:**  Android 7.1.2
* **App version:**  v0.1.5

#### Steps to reproduce

1. Enable 'Preview first when opening notes'
2. Create widget
3. Open file

#### Expected result
Opens in preview mode

**Comment by gsantner** [comment]
I don't think it's good to change this behaviour. Maybe an addiotinal checkable settings option that will explictly enable preview there too
