### ISSUE TITLE
selecting multiple words at the end of line switches to the view mode

### ISSUE THREAD

**Issue by 532910** [gsantner/markor#850]
#### General information

* **App version:** 2.2.7 (109) from f-droid
* **System:** LNGOS 16 on android 9 op3t

![record](https://user-images.githubusercontent.com/14617699/74430589-345b7700-4e6e-11ea-90a5-56d3e366d531.gif)

**Comment by gsantner** [comment]
Do you have "swipe to switch mode" settings option enabled? It's still kind of experimentak.

**Comment by 532910** [comment]
Yes, "swipe to switch mode" is on.

**Comment by gsantner** [comment]
Ok, this is a experimental setting, please keep it disabled if it makes problems.
