### ISSUE TITLE
Feature: Preset filename for New; Note-Taking Friendly

### ISSUE THREAD

**Issue by vramazani** [gsantner/markor#851]
Make an option for predefined filename for New MD file. This would make the app the Goto choice for note taking.

Suggestion: current date and time as. first step.

Next step: make the preset configurable; as in `date %` formatting.

**Comment by macdonaldster** [comment]
Hey, @vramazani if you want, please check out an app called Texpand (I am not affiliated, just a user). 

I have it configured with various filename templates (e.g. 2020-02-14-blog or whatever) using dynamic dates. When I make a new note, I just use my text-replace string ("dddd" for "2020-02-14", etc) and it replaces that with the current date, and whatever else is in the template. It makes it very easy to have fast, appropriate filenames for your notes. I use a similar workflow with AutoHotKey (Windows).

**Comment by gsantner** [comment]
@vramazani 
Theres already a filename template for date based.
From the filename template select Jekyll, it does exactly that (2020-02-05-TITLE.md)

**Comment by vramazani** [comment]
@gsantner my bad, I should've explained better
Currently I use this app for notes, which has __decide later__ title by default.
Anyway I want to have such a shortcut.
Is there an option to make the Jekyll choice the default?

**Comment by vramazani** [comment]
Thank you @macdonaldster
Nice app, doesn't have internet access. It'd be nice to see a FOSS replacement.

Still, I'm interested in having the asked shortcut in Markor; I've become accustomed to it!
Cheers!

**Comment by gsantner** [comment]
> Is there an option to make the Jekyll choice the default?

It will be in future.

> Nice app, doesn't have internet access

By the way Markor also works fully offline too, does no single  internet usage. The only reason why Markor has INTERNET permission is, that if you add image refernces like `<img src="mysite.net/image.jpg">`, it can displays it. So for user generated content

**Comment by gsantner** [comment]
Closing this in favor of #676
