### ISSUE TITLE
Customisable unordered list character

### ISSUE THREAD

**Issue by markormesher** [gsantner/markor#853]
#### General information

* **App version:** v2.2.6 (108)
* **System:** Android 10

#### Description

It would be great to be able to configure the character used for unordered lists, with the options being at least `*` and `-`. Use case: most of my notes predate my use of Markor and I’d like to keep them in a consistent format, and I’m sure many users edit their notes in multiple systems that have different Markdown styles.

If this is something you’d be happy to see in the app, I’d be happy to work on a PR.

#### Log

N/A

**Comment by ChiefMikeK** [comment]
You can add some css code for displaying the html render or do you mean an optional<alternativeFlavor> markdown code ?
### Inject -> head  
```
< style> 
ul {  ...  ;
   }
</style>
```
[CSS Styling Lists](https://www.w3schools.com/css/css_list.asp)

**Comment by gsantner** [comment]
its about what edit mode inserts by default.

> If this is something you’d be happy to see in the app, I’d be happy to work on a PR.

Please do that, I'm happy about help. I suggest a list-selection, makes sure only markdown supported characters can be selected.

**Comment by ChiefMikeK** [comment]
The easiest way would be to add a few more commented out lines to the current **Inject -> head** boilerplate. 👓

**Comment by gsantner** [comment]
This issue is about EDIT mode, not VIEW mode to my best understanding. So any Inject option is not relevant.

**Comment by markormesher** [comment]
@gsantner is right, this is about what the "insert unordered list" button does in edit mode, whether it inserts `*`-style lists or `-`-style lists.

I'll see if I get a bit of time this week(end) to have a look at it. I agree on keeping it to a list selection to only allow valid Markdown lists, and naturally I'll make sure the default value is the current behaviour.
