### ISSUE TITLE
todo.txt cursor start of line before date

### ISSUE THREAD

**Issue by tgrrr** [gsantner/markor#854]
#### General information

* **App version:** 
2.2.6
* **System:** 
Android 10.3.1
OnePlus A6003 
OxygenOS

##### What this is about?

Option to include date at the end of tasks

##### Context
I format my todos with the `.todo` format

```txt
projectName:
  [ ] foo @context @tag @priority @started(2020-03-02 10:42)
_____________
archive:
  [x] bar @context @done(2020-03-02 9:55) @projectName
```

in [atom](https://github.com/irrationalistic/atom-tasks)
in [vscode](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-todo-plus)

##### What happens?

In the todo.txt file:
When I enter a todo, and hit enter, it creates a new todo
The new todo includes the date
However, the cursor is at the right end of the new blank todo, _after_ the date

##### What is expected to happen?

The cursor should be at the _left_ end of the new blank todo, _before_ the date

##### What needs to be done for it to happen

Add an option to place the cursor at the start of the line for new todos

Thanks!

**Comment by gsantner** [comment]
todo.txt format is expecting that the line starts with date and then your content. you should not type before the date. hence cursor is after date. see <https://gsantner.net/project/markor.html#what-is-todotxt>.

If you really want however, turn off date in settings. I wont make a settings option for this special usecase thats for misuse.

**Comment by tgrrr** [comment]
No worries, I understand the todo.txt format, and its benefit

**Comment by macdonaldster** [comment]
@tgrrr If you decide to turn off the auto-date, you can use an Android app like Texpand (https://play.google.com/store/apps/details?id=com.isaiasmatewos.texpand&hl=en) to fill in the date for you and put the cursor where you would like. For example, I have it set up to relace "dddd" with a formatted date string. I often use it when naming files as well as entering log lines in files, etc.
