### ISSUE TITLE
Render a checkbox in the viewer for `- [ ]`

### ISSUE THREAD

**Issue by tgrrr** [gsantner/markor#855]
#### General information

* **App version:** 
2.2.6
* **System:** 
Android 10.3.1
OnePlus A6003 
OxygenOS

##### What this is about?

Render a checkbox in the viewer for `- [ ]`

##### What happens?

 `*[] ` is used to represent a markdown task in markor
`- [ ]` is also what is inserted when I click the tick on the toolbar (the one that floats just above the keyboard)

When I click on the eye icon, a task that starts with:

-  `*[] ` renders as a checkbox

- `- []` renders as a checkbox
- `- [ ]` doesn't render as a checkbox

![Screenshot](https://drive.google.com/folderview?id=1JBggPmj2ELqjwX-2NUmYbnGMSN2kGW-B)

##### What is expected to happen?

Both `- []` and `- [ ]` should render as a checkbox

##### What needs to be done for it to happen

Update code so a task that starts with `- [ ]` renders as a checkbox

Thanks!

**Comment by gsantner** [comment]
Please ask at Markos Parser, Flexmark.

* [] text
* [ ] text
