### ISSUE TITLE
math notation rendering

### ISSUE THREAD

**Issue by kiranajij** [gsantner/markor#857]
The app works great for creating a MD document. But i feel like it's missing a very usefule feature, rendering math texts. Like in other mark down renderers, I thing it should be able to render mathematic symbols for a seemless class note taking and sharing with others.

**Comment by gsantner** [comment]
check markdown settings, there is a math option.

**Comment by yashpalgoyal1304** [comment]
suggested label: question

**Comment by gsantner** [comment]
KaTex is available since long time.
