### ISSUE TITLE
bug: Move text one line up/down

### ISSUE THREAD

**Issue by vramazani** [gsantner/markor#864]
#### General Info

- Version 2.2.7 F-Droid
- Android 9

#### Description
When the cursor is at the end of some line, this "Special Key" (inside keyboard icon) doesn't work right.

To **reproduce**: just go to the end of any line and do one of the two moves.

If this is done on any type of list (hyphen, checklist, number) it will have 2 side effects:
- break the undo history
- add wrong list symbol/checkbox/enumerator by auto completing the list symbol

**Comment by gsantner** [comment]
@Delko97 Could you please have a look as you worked on this?
