### ISSUE TITLE
Jump to section-hyperlink in view mode

### ISSUE THREAD

**Issue by anishmittal2020** [gsantner/markor#865]
#### General information

* **App version:**  2.2.6
* **System:**  Android 9

#### Description

- Inside `./A/A.md`

```markdown
Refer [B1](../B/B.md#b-1)
```

- Inside `./B/B.md`

```markdown
# Introduction

blah blah

# B1 {#b-1}

blah blah

# B2 {#b-2}

blah blah

# B3 {#b-3}

blah blah
```

#### Desired Output

In the view mode for `./A./A.md` when selecting the section hyperlink for the section B1 in `./B/B.md` the view mode should open B at B1 section at the top (i.e. it should scroll automatically to the section). Presently, it does not scrolls down.

**Comment by gsantner** [comment]
Closing in favor of #912
