### ISSUE TITLE
Add encryption

### ISSUE THREAD

**Issue by opensource21** [gsantner/markor#867]
#### General information

* **App version:** 2.2.6
* **System:** Android

#### Description
I really like the app specially the undo functionality. For really private notes I would prefer to encrypt the notes, because if I want to enable sync, I must make it readable for other apps and then a phone is insecure. 
What do you think to add encryption functionality, so that files in a notebook will be encrypted with AES or gnupg?

To make it clear, I don't want to use is as a password-safe. But ensure that simple reading the file system doesn't make the data public.

**Comment by gsantner** [comment]
See #60.

If theres no community work / PR this likely wont happen. I like it, but without bloating the app with many libs this won't be easily possible. Too theres massive problems because different android versions don't support many things, or api calls are not compatible between.
