### ISSUE TITLE
GUI: Wrap Unwrap Option in the Editor Window

### ISSUE THREAD

**Issue by anishmittal2020** [gsantner/markor#871]
#### General information

* **App version:**  2.2.6
* **System:** Android 9

#### Description

- *Wrap Words* Option is available in the *Edit mode* Settings.
- I think it will be useful if this option id available when we open the markdown file. While  we are editing the file in the *top bar* under *three vertical dots* and under *Tools*

#### Purpose

My default settings are to open files in unwrapped condition, as my files have long lines and have many lines.

When I find the line of my interest. I like to wrap the contents of the file, temporarily for that particular file at that time.

**Comment by gsantner** [comment]
#562
