### ISSUE TITLE
Option to disable the big yellow saving permission denied warning message?

### ISSUE THREAD

**Issue by Rising-Soul** [gsantner/markor#872]
#### General information

* **App version:** 
2.2.7 F-droid

* **System:** 
Samsung S4
Android 5.1.1 (Cyanogenmod 12), Lollipop, rooted 

#### Description

I was using version 1.6.0 for a long time, today I updated to 2.2.7, and I get this huge yellow warning message saying that Android doesn't have permission to save here (same folder on my SD card I've always been using, which has write access for all apps).

I probably did some root hackery to get Android's silly file permission limitations disabled, but I don't really remember. 

Saving *does* actually work though, but the huge yellow message takes up screen space that I'd like to have back (it's also really bright in dark mode)... I've looked through all the settings and don't see a way to get rid of it. Could one be added, please?

**Comment by gsantner** [comment]
I don't think about removing it, thats the wrong way. Instead it should be changed to correctly detect writable.

**Comment by JVS-XII** [comment]
@Rising-Soul @t184256 
Decision: 
1. take away storage permission.
2. return to the app
3. perform the required slide actions if any
4. return permission
5. close and open the app again

**Comment by t184256** [comment]
What's "slide actions"?

**Comment by JVS-XII** [comment]
After paragraph 2, upon returning to the app, I saw slide with some order of action. I don't remember what content.

**Comment by JVS-XII** [comment]
> What's "slide actions"?
@t184256 
After paragraph 2, upon returning to the app, I saw slide with some order of action. I don't remember what content.

**Comment by citizen1277** [comment]
https://github.com/gsantner/markor/issues/1732

**Comment by citizen1277** [comment]
Here's the permanent solution to this problem, it's much more refined and reliable:
https://f-droid.org/en/packages/info.aario.snotepad/

**Comment by citizen1277** [comment]
Also, "perform the required order of action on slide if any" has no intelligible meaning in this context.
