### ISSUE TITLE
[FR] Support for linebreaks

### ISSUE THREAD

**Issue by Offerel** [gsantner/markor#875]
It would be nice, when we could enable optional support for linebreaks/newline in markdown. Normally, when I press the enter key a new line is added in the text. In most other markdown applications such linebreaks are optional interpreted also as linebreaks in a reader view and I really miss this in markor.

I think this should be optionally, because in my opinion the official markdown way is it to use 3 spaces at the line end.

**Comment by gsantner** [comment]
Markdown is in most specs: Two spaces on end of line = new line. Thats what Markor has too and it will stay like that, compatible to most other markdown software.

**Comment by adarrra** [comment]
Oh, sad. I also want this feature... E.g. I mostly edit md files in vs code editor and there it's configurable
