### ISSUE TITLE
Change request: Interpret root as notebook folder instead of system root

### ISSUE THREAD

**Issue by add1989** [gsantner/markor#884]
First of all, let me start off by saying how amazing I think Markor is. I genuinely think it is one of the best quality Android apps around, period.

I do however have a small change request I would like to make due to an issue I'm facing, which I'll detail below.

**Background**
I use Vimwiki for my notebook which I can edit remotely via Gitea. When on the go however, I have the directory synchronised to my smartphone via Syncthing and I view/edit it with Markor.

**Issue**
I have a 'Projects' folder and I will often want to link from an active project to another note (e.g. a resource such as a web clipping). In Vimwiki/Gitea, I can specify the link as:

`[Absolute link to resource](/resources/clippings/clipping1.md)`

VimWiki and Gitea both interpret this correctly. However, Markor interprets this as being from the root of my smartphone's file system and I get a brief error about permissions etc. The only way I can get it to work in Markor is using a relative path:

`[Relative link to resource](../../resources/clippings/clipping1.md)`

The problem with this is that once I move the project to the archive, the link becomes broken.

**Proposed Solution**
Can Markor be modified so that when in 'Notebook' mode, it treats the root (/) as the notebook directory instead of the system root?

**Comment by gsantner** [comment]
not really doable as any / could be possibly be a link or not.

**Comment by add1989** [comment]
As I mentioned, relative paths aren't really an option where you want to be able to move things around. Otherwise, every time I archive a project I would have to go through and update all the links in the project.

> any / could be possibly be a link or not (or a correct url fragment)

I am only talking about markdown links that start with '/' - which shouldn't affect anything else adversely as far as I can tell?

I realise that in a normal context (editing text files not part of the Notebook), a path starting with '/' could really mean the root of the device - but could the solution I proposed be applied only in the context of the 'Notebook'? It could even be a setting so users could decide?

**Comment by gsantner** [comment]
You can freely inject javascript  into every loaded document.

This way you can do something along onReady { each img  href = /storage/... + href }

**Comment by add1989** [comment]
> You can freely inject javascript into every loaded document.

Interesting, do you have a link to any documentation describing this? A quick Google search didn't return anything...

**Comment by gsantner** [comment]
Markor Settings -> View -> Inject Head.

There you can write any javascript. That will be injected always when you view a document in Markor.

**Comment by add1989** [comment]
```
var anchors = document.getElementsByTagName("a");

for (var i = 0; i < anchors.length; i++) {
  anchors[i].href = "/storage/emulated/0/vimwiki/" + anchors[i].href
  document.write(anchors[i].href);
}
```
I came up with this which works when I test it in a basic browser environment but not when it goes into Markor - the links just break. Struggling to see how to troubleshoot as I can't see what it's actually setting the links to?

**Comment by gsantner** [comment]
are you running that in the onPageLoad?

**Comment by add1989** [comment]
> are you running that in the onPageLoad?

Yeah, I added it to the function onPageLoaded()

**Comment by gsantner** [comment]
You can easily view the resulting html, by adding after your changes:


document.body.innerText = document.body.innerHTML;

**Comment by add1989** [comment]
I've amended the script to the below:

```
var anchors = document.getElementsByTagName("a");

for (var i = 0; i < anchors.length; i++) {
  if (anchors[i].getAttribute("href").charAt(0) === "/") {
    anchors[i].href = "file:///storage/emulated/0/vimwiki" + anchors[i].getAttribute("href");
  }
}
```
I can now get it to replace the links with what seems to be a correct version, for example:

`/resources/clippings/clipping1.md`

becomes

`file:///storage/emulated/0/vimwiki/resources/clippings/clipping1.md`

The problem is, Markor won't display the file? But when I paste link into my phone's browser from displaying the innerHTML it shows the file fine?

**Comment by gsantner** [comment]
```
[f](file:///storage/emulated/0/00_sync/a.json)

and

[f](/storage/emulated/0/00_sync/a.json)
```
works for me. Please check if the filepath is correct, and maybe try the other way.

**Comment by add1989** [comment]
Checked path is correct and tried both methods, Markor doesn't display the file.

Do you think the lines through the folder name have anything to do with it? The folders still work when I click on them so there doesn't seem to be a permissions issue...

![Screenshot_20200330-142455](https://user-images.githubusercontent.com/51096221/77917644-bb37a800-7292-11ea-8295-98c1e4386bde.jpg)

**Comment by gsantner** [comment]
/storage/emulated/0/ should be accessible fine as soon you grant permission

**Comment by add1989** [comment]
This has started working now without any changes.. literally don't know what the issue was earlier. So of nothing can be implemented in the main app, I guess this issue can be closed with this workaround :)

**Comment by fanlushuai** [comment]
Thanks! I use this for my markdown img path convert.

```
var imgElements= document.getElementsByTagName("img");

for (var i = 0; i < imgElements.length; i++) {
  if (imgElements[i].getAttribute().charAt(0) === "/") {
    imgElements[i].src = "file:///storage/emulated/0/blog" + imgElements[i].getAttribute("src");
  }
}
```
