### ISSUE TITLE
Share Screenshot to Markor Quicknotes directly

### ISSUE THREAD

**Issue by anishmittal2020** [gsantner/markor#886]
I like to take screenshots from Android browser then there are options to share the screenshot to an app such as follows:

![image](https://user-images.githubusercontent.com/42092626/78044888-8c463280-7375-11ea-9253-6486e2ec9483.png)

But it will be much useful, to be able to add to quick notes (and or to any markdown files), right after taking the screenshot.

Presently, we have to open Markdown file, then add screenshot manually by going to the path of the screenshot.

**Comment by gsantner** [comment]
Makes sense for the future, but currently don't plan accepting other input than text for Markor. Thanks :smile:
