### ISSUE TITLE
Copy and paste quickly to QuickNotes

### ISSUE THREAD

**Issue by anishmittal2020** [gsantner/markor#889]
When we select any message, we have an option with the Google translate app that it can pop up to the to right and we could just select that round pop up to translate it immediately.

Similar feature could be added to Markor to quickly add snippets to notes.

The following image shows how it works with Google translate app.

![Screenshot_20200402-190139_WhatsApp_1](https://user-images.githubusercontent.com/42092626/78281526-1aa7e900-751b-11ea-9ef6-4a0eb9106474.jpg)

**Comment by gsantner** [comment]
Long press to select a section and it should present you with tranlsate and copy option.

**Comment by anishmittal2020** [comment]
@gsantner Many apps don't allow to share the data 

The example which I have shown using whatsapp, it does not allow to share data to another app, you can only share it to some other recipient of whatsapp, but you can only copy it. This is why the bubble helps as it is activated when anything is copied.

I thing this issue should not have been closed so early.

**Comment by gsantner** [comment]
I dont want to add clipboard monitor to markor.
