### ISSUE TITLE
"#" sign in normal text is highlighted (when it shouldn't)

### ISSUE THREAD

**Issue by chaojian-zhang** [gsantner/markor#890]
#### General information

* **App version:** 

```Package: net.gsantner.markor
Version: v2.2.8 (111)
Flavor: Gplay (release)
Build date: 2020-03-26T15:33Z
ISource: Google Play
VCS Hash: 82cfa7bb4b8e51b57d2d9e5ed4e34d306da5c61c
```

* **System:** Android 10

#### Description

Try something like:

`A line containing "C#" in it`.

The text after `#` will be incorrectly highlighted.

#### Screenshot

![Screenshot_20200402_225737_net gsantner markor](https://user-images.githubusercontent.com/7077098/78319564-69fb1300-7535-11ea-82bf-d85f39cd1d73.jpg)

**Comment by gsantner** [comment]
Notice: This only affects the "simple" markdown header highlighter without dyn-height
