### ISSUE TITLE
Markdown: copying first character on new line

### ISSUE THREAD

**Issue by thousandsofthem** [gsantner/markor#891]
#### General information

* **App version:** 
2.2.8 (and many previous ones)
* **System:** 
Android 8.0.0
#### Description

Steps to reproduce:
* Edit .md file ("Files", "QuickNote")
* Enter "Foo"
* Hit "Enter" button on keyboard to insert newline
* See "F" appears on new line

![Screenshot_20200404-122051_Markor](https://user-images.githubusercontent.com/736279/78423405-c877dc80-766e-11ea-8085-db6cf38ee991.jpg)

It makes sense to copy previous line's formatting for bullet points and such, but not for every single character out there.
Proposed solution: do such copying for whitelisted characters only, e.g. `*`, `-`

**Comment by gsantner** [comment]
No confirmation, but related: #883 #880 #877 #882 
@harshad1 Guess this is fixed / does not happen with your most-recent PR?

**Comment by harshad1** [comment]
@gsantner I am unable to reproduce this with the version on F-Droid (does not happen with my PR either). Could you check if you are able to reproduce this?

**Comment by gsantner** [comment]
Cannot r either

**Comment by gsantner** [comment]
please try with next update.

**Comment by thousandsofthem** [comment]
ok
