### ISSUE TITLE
Fatal crash - NullPointerException: Attempt to get length of null array

### ISSUE THREAD

**Issue by tingsu** [gsantner/markor#892]
#### General information

* **App version:** 
the latest released version on Google Play (v2.2.8); also affected a previous released version (v 2.0.1)

* **System:** 
Google Pixel 3 Phone (Android 9.0); also reproducible on an Android emulator 6.0

#### Description

I searched the issue history, have not found similar issues. See the reproducing video below:

![20200404_113704](https://user-images.githubusercontent.com/3156978/78423841-7aaca580-7669-11ea-84be-72a875a3b11f.gif)

#### Log

```
 FATAL EXCEPTION: Thread-322
 Process: net.gsantner.markor, PID: 5825
 java.lang.NullPointerException: Attempt to get length of null array
 	at other.writeily.model.WrMarkorSingleton.deleteFile(WrMarkorSingleton.java:108)
 	at other.writeily.model.WrMarkorSingleton.deleteSelectedItems(WrMarkorSingleton.java:126)
 	at net.gsantner.opoc.ui.FilesystemViewerFragment.lambda$null$4$FilesystemViewerFragment(FilesystemViewerFragment.java:448)
 	at net.gsantner.opoc.ui.-$$Lambda$FilesystemViewerFragment$WXm7FNaiavc13YsiGz2lvupeaUQ.run(lambda)
 	at java.lang.Thread.run(Thread.java:818)
```

**Comment by gsantner** [comment]
You should not be able to delete this...

**Comment by tingsu** [comment]
Okay, are there any way to avoid this? I think showing a crash is not good for user experience to some extent.

**Comment by gsantner** [comment]
delete button  will get removed here

**Comment by gsantner** [comment]
btw, do you understand what you have tried? you tried to wipe your whole stored data

**Comment by tingsu** [comment]
Thanks for your quick reply and fix, @gsantner . Yes, I understand this deletion action should never be tried. I just came cross this issue.

**Comment by gsantner** [comment]
np
