### ISSUE TITLE
Undo and Redo behave inconsistently when doing text editing

### ISSUE THREAD

**Issue by tingsu** [gsantner/markor#894]
#### General information

* **App version:** 
Version: v2.2.8 (the latest released version)
Apk: net.gsantner.markor-v111-2.2.8-flavorDefault-release.apk
(also exist in a previous version v2.0.1)

* **System:** 
Google Pixel 3 phone (Android 9.0) and Android emulator 6.0

#### Description
The ``undo`` and ``redo`` behave inconsistenly when doing text editing. See the video below.

https://youtu.be/1mO0RbX5g_4

Let me explain the video content and my observation in detail. 

Step 1: I input a line of text, which contains a priority ``(C)`` and a letter ``Y``. Now, if I toggle between ``undo`` and ``redo``, the text can switch between ``(C) Y`` and ``(C)``. It is correct and expected functionality. 

Step 2: I keep the text as ``(C) Y``. Then, I switch to Tab ``QuickNote`` and come back. **At this time, I can toggle between ``undo`` and ``redo`` (as they are enabled on the GUI page), but the text will not change, and remain same as  ``(C) Y``**.  Okay, I guess the switch action internally writes the text into disk, so the user cannot use the ``undo`` and ``redo`` function. Let's assume this is correct and intended functionality. **Although, I feel this is quite strange and does not conform to my intution**.

Step 3: Then, I delete ``Y``. Now, I find if I toggle between ``undo`` and ``redo`` again, the text can switch between ``(C) `` and ``(C) Y``. It is correct and expected functionality.  

Step 4: I keep the text as ``(C)``. Then, I switch to Tab ``QuickNote`` and come back. **Note I can still toggle between ``undo`` and ``redo`` (as they are enabled on the GUI page), but the text will not change, and remain same as  ``(C) ``**. 

Step 5: Then, I delete ``(C) ``. Now, I find if I toggle between ``undo`` and ``redo`` again, the text can switch between ``(C) `` and ``empty``. It is correct and expected functionality.  

Step 6: I keep the text as ``empty``. Then, I switch to Tab ``QuickNote`` and come back. **Note I can toggle between ``undo`` and ``redo``  (as they are enabled on the GUI page), but at this time the text CAN be changed. The text can switch between  ``(C) `` and ``empty``**. This behavior is obviously inconsistent with my previous assumption on this functionality. 

Now, I become quite confused about the exact logic behind ``undo`` and ``redo``. When the text cannot be changed in Step 2 and 4, why the ``undo`` and ``redo`` button are enabled on the GUI page? --- It gives me the intuition that these two buttons will function to change the text. 

So, my suggestion is: (1) disable ``undo`` and ``redo`` on the GUI page (show them in gray) when the file was written to the disk; or (2) still enable ``undo`` and ``redo`` to function as expected (i.e., able to change the text) when the file was written.

Hope my explanation makes sense. Thanks.

**Comment by tingsu** [comment]
Any update on this issue? Thanks for readling my long description.

**Comment by junior291492659** [comment]
Hello, @gsantner , I read a few issues created by @tingsu in a row after [issue896](https://github.com/gsantner/markor/issues/896). And this issue just caught my attention especially after I went through the detailed description and video.
The strange behavior of ```undo``` and ```redo``` is quite confusing. Take this issue for example, their function should be consistent. And it seems go "wrong" when gets into empty file situation(as the step 5 and step 6 reveals).
Is there any conection between these two issue? And the suggestion from @tingsu seems reasonable. I would really appreciate it if you can take it into consideration.

**Comment by harshad1** [comment]
@gsantner Not sure if this is related but DocumentEditFragment / onCreateOptionsMenu is called every time any character is entered or deleted.

Also, the TextHandler and Markdown auto format should probably be disabled around the undo / redo calls

**Comment by tingsu** [comment]
Thanks your explanation @harshad1. I am not sure whether this issue is related to #896 , in which @gsantner  points out an internal design strategy: ``do not save empty file``? Because, I observe the inconsistency appears only when I empty the file content, and toggle between ``empty`` and ``(C)``. 

I think correctly display ``undo`` and ``redo`` is quite important to inform the app user when he/she could do ``undo`` and ``redo``. But, now, this information is somehow confusing.

**Comment by tingsu** [comment]
Can I hear your comments on this, @gsantner ?

**Comment by gsantner** [comment]
There is some work ongoing. 
As said across multiple issues and chats: Markor will keep not saving any empty files.

**Comment by tingsu** [comment]
Hi @gsantner , I saw you disabled the discussion on the issue #896, as you insist that "Markor will keep not saving any empty files". I can understand this design choice, as this design can guarantee the file content will never be unexpectedly lost.  For safety, it is a good choice.

Then, do you think, as I proposed in #896, adding a dialog to alter the user when he/she clicks the ``trash`` icon will be a better design?  As for me, I click the ``trash`` icon, I really want to empty the file content, but the current implementation will somehow unexpectedly recover the file content. I think this point is confusing. I know, you want to keep the safety design choice, but this design somehow sacrifice the user experience.  Can I know your thoughts on this (I have not received your feedback on this problem in issue #896)?  Also, as you may note, a number of users (not only me) have similar confusions...  I like Markor, so I insist on this issue. If you still do not agree, then just let it go ... Thanks.

**Comment by gsantner** [comment]
I have disabled discussion because I don't want to describe on all issues again and again. So there is this one now.

Bottom actions is mainly for altering editor text (so Text Actions), have to think about this.

**Comment by tingsu** [comment]
Thanks for your quick reply and considering my proposal. Stay tuned :)

**Comment by gsantner** [comment]
With next update, the toolbar menu button will always be enabled and visible. And pressing it will also save when content empty.

**Comment by tingsu** [comment]
Thanks for your quick fix, @gsantner and @harshad1  !  I downloaded the latest released version ``v.2.2.9 (112)`` on Google Play, and manually verified these related issues (#894, #895 , #896). However, none of them were fixed.  So, can I know what parts you have already fixed? Or, I misunderstand something here?

**Comment by tingsu** [comment]
Can I know further update? Thanks.
