### ISSUE TITLE
Reloading an empty file unexpectedly enables the undo button

### ISSUE THREAD

**Issue by tingsu** [gsantner/markor#895]
#### General information

* **App version:** 
Version: v2.2.8 (the latest released version)
Apk: net.gsantner.markor-v111-2.2.8-flavorDefault-release.apk 
(also exist in a previous version v2.0.1)

* **System:** 
Google Pixel 3 phone (Android 9.0) and Android emulator 6.0

#### Description
If I reload an empty file, the GUI unexpectedly enables the ``undo`` button. As a user, I feel this is not necessarily. Sometimes, it even confuses users on the ``reload`` function. See the video below.

![20200408_220252](https://user-images.githubusercontent.com/3156978/78828632-4a586480-79e5-11ea-8614-319b656f3675.gif)

**Comment by tingsu** [comment]
Any update on this issue? will this issue be fixed together with issue #894 via the pull request #902 ?

**Comment by gsantner** [comment]
I'm closing and locking this topic as I found multiple similar issues. New nr is #894 .
