### ISSUE TITLE
Multiple switchings between Todo and QuickNote tabs will unexpectedly recover deleted content

### ISSUE THREAD

**Issue by tingsu** [gsantner/markor#896]
#### General information

* **App version:** 
Version: v2.2.8 (the latest released version)
Apk: net.gsantner.markor-v111-2.2.8-flavorDefault-release.apk

* **System:** 
Google Pixel 3 phone (Android 9.0) and Android emulator 6.0

#### Description
The reload function is somehow buggy. If i switch between ``Todo`` and ``QuickNote`` tabs will unexpectedly recover deleted content. See the video below.

![20200408_222246](https://user-images.githubusercontent.com/3156978/78830050-a328fc80-79e7-11ea-87c2-d128622067a3.gif)

**Comment by gsantner** [comment]
Give it some time to save the file.

**Comment by tingsu** [comment]
Okay, @gsantner, thanks for your quick reply. Is there any more reliable way to avoid such "unexpected“ behavior? Maybe provide an explicit save functionality? How do you think?

**Comment by gsantner** [comment]
there is a save button in the menu.

**Comment by gsantner** [comment]
Oh I see you completely want to delete all content?

This is not saved by purpose. Markor is built to not save empty files so you dont end up with bad files. In that case have a dot or something left.

**Comment by tingsu** [comment]
Yes, I want to completely delete all content. However, when I toggle between the two tabs. The original content returns back, which is unexpected and annoying. 

>This is not saved by purpose. Markor is built to not save empty files so you dont end up with bad files.

Then, please see the case below I encounter. I empty the file content, and leave the app. However, when I come back to the app later, the deleted content is saved as a file (which of course I did not want to have).

![20200408_235351](https://user-images.githubusercontent.com/3156978/78837457-67486400-79f4-11ea-8471-b80fca32c4df.gif)


From my view, this should be avoided to ensure user experience. How do you think?

**Comment by gsantner** [comment]
I will keep it this way, to not save empty files.
I rather have people asking that people destroying their stuff by accident.

**Comment by tingsu** [comment]
Okay, but the case I proposed at the beginning is that: I want to delete the content completely, but when I toggle between the two tabs (two obviously unrelated actions) , the content will come back. It is obviously not intended.

**Comment by gsantner** [comment]
it is by what I want markor to do: Not save empty files.

**Comment by tingsu** [comment]
Okay, I understand. ``Not save empty files`` is a good practice, but using the previous deleted content to make sure a file is not empty (so that it can be saved) is  not a perfect solution, I have to say :)

**Comment by tingsu** [comment]
Or, I think a better way is to show a dialog when users click the ``delete`` icon. The dialog can alter the user to make sure he/she really wants to empty the file. If he/she confirms, then this empty file should be discarded. This can make the user experience more smooth. How do you think?

**Comment by junior291492659** [comment]
> Or, I think a better way is to show a dialog when users click the `delete` icon. The dialog can alter the user to make sure he/she really wants to empty the file. If he/she confirms, then this empty file should be discarded (no need to keep the original non-empty file as a backup). This can make the user experience more smooth. Or, this deletion action can be moved to much safer places (e.g., in the menu with the `save` action). How do you think?

@gsantner Thanks for your amazing app. I have also encountered this problem during my usage. These gif files explain the issue quite well. And I absolutely get your idea of not saving empty files when users delete all the content on purpose or not after creating a fresh file and then explore other functions or just leave the app as the second gif shows. It can be somehow odd or unfriendly to users since I had the exact feeling when I uncovered this unexpected recovery from the very begining. 
The designing of not saving empty file to avoid bad files totally makes sense. But this suggestion from @tingsu can work well in my view as a common user because users can have their control of the empty file in this way.
It would be really appreciated to your concern on this. And thanks for your discussions anyway.

**Comment by skull591** [comment]
I encounter this issue as well. The design is quite confusing and I think it's better to improve it one way or another.

**Comment by oraluben** [comment]
Hi, I think this is a little bit confusing, is that possible to explicitly notify about the feature?

**Comment by gsantner** [comment]
I'm closing and locking this topic as I found multiple similar issues. New nr is #894 .
