### ISSUE TITLE
Resilio Sync

### ISSUE THREAD

**Issue by rlayton6** [gsantner/markor#897]
#### General information

* **App version:** 
v2.2.8 (111)
* **System:** 
Android 8.0.0
#### Description

I have indeed come from Markor's dialog saying that the file cannot be opened, so my question is where can I change Markor's Document Folder? 

There is no mention of it that I can find in the settings. I suspect it might be the 'App start folder' but that doesn't give the option to point it to the SD-CARD as far as I can tell. I'm using a custom folder on my SD-CARD, and I don't care that it won't be writeable in Markor.

Thanks.

**Comment by gsantner** [comment]
Settings - General - Notebook.

In the main view file Browser goto sdcard folder and press red plus button once and it will help you with sdcard.
