### ISSUE TITLE
Preview broken

### ISSUE THREAD

**Issue by contrapunctus-1** [gsantner/markor#9]
#### General information

* **Device:** Moto G 5S Plus
* **Android Version:**  v7.1.1
* **App version:**  v0.1.2

#### Steps to reproduce

1. Try to view the preview in any way, be it before (with "Preview first when opening notes") or after editing (with the eye icon).

#### Expected result
**What is the expected output?** 
Preview of note.

**What do you see instead?**
Blank white screen (regardless of theme), with a back button, file name, share button and edit button on top.

**Comment by gsantner** [comment]
Works for me. I cannot reproduce the problem on my devices (one is 7.1.1 + 0.1.2 too).
YoDo you gave the app the permission to storage?

![screenshot_20170917-165023](https://user-images.githubusercontent.com/6735650/30521929-5547c910-9bc8-11e7-9931-b58b1ead7a44.png)

**Comment by contrapunctus-1** [comment]
It does have storage permission. Resetting app data did not fix it. I forgot to mention that the same problem also occurred with Writeily Pro 1.3.2 on this device, also obtained from F-Droid.

**Comment by gsantner** [comment]
Do you maybe some kind of code injection installed (XPosed/XPrivacy, Magisk, ...)?

Can you try to create a new folder somewhere on your device and change the save-path folder (see settings) to that?

**Comment by contrapunctus-1** [comment]
I don't have any of those. This is the stock firmware - although I did disable and remove permissions for a few proprietary extensions (Google Play Services etc)

> Can you try to create a new folder somewhere on your device and change the save-path folder (see settings) to that?
Tried, no change.

> Everything else works right? Than maybe it can too be a bug in the used markdown render library (anddown).
I wonder if that's it. I am also facing a very similar problem in Octodroid on this device - I can't preview Markdown in that, either 😶

**Comment by gsantner** [comment]
> I wonder if that's it. I am also facing a very similar problem in Octodroid on this device - I can't preview Markdown in that, either 😶

Okay, I think I and the app cannot help you in this then. Seems to be an upstream problem that seems to especially affects your device.

**Comment by contrapunctus-1** [comment]
I've discovered the cause. I had disabled Chrome - re-enabling it made previewing in Markor as well as Octodroid work again.

**Comment by gsantner** [comment]
Disabled Chrome?

**Comment by contrapunctus-1** [comment]
No, not System Webview - I checked, and it cannot even be disabled on this device - Chrome, the browser.
