### ISSUE TITLE
Drastically slower editing

### ISSUE THREAD

**Issue by contrapunctus-1** [gsantner/markor#90]
#### General information

* **Device:** Moto G 5s Plus
* **Android Version:** v7.1.1
* **App version:** v0.1.5

#### Steps to reproduce

1. Edit any file (perhaps ones larger than a certain size? This file is 3KB, and I was able to edit it in Markor before - I created it in it.)

#### Expected result
**What is the expected output?** 
Normal editing.

**What do you see instead?**
Extremely slow input, deletion and navigation (via ASK's left/right arrow keys), keyboards crash and restart if you type too fast.

I've tried this with AnySoftKeyboard and Hacker's Keyboard, to see if it might be a keyboard issue. Both are working fine in other applications.

**Comment by gsantner** [comment]
increase highligting Time in settings

**Comment by gsantner** [comment]
@ all Auto formatter (that does add e.g. bullet when pressing enter in list) is now enabled indp. to highlighter. This means if you want to get something faster, you can disable highlighter right now, while still getting the format-specfic benefits inside the editor input field.
