### ISSUE TITLE
Main: Foldername in toolbar not reloaded at file browser

### ISSUE THREAD

**Issue by tingsu** [gsantner/markor#900]
#### General information

* **App version:** 
Version: v2.2.8 (the latest released version)
Apk: net.gsantner.markor-v111-2.2.8-flavorDefault-release.apk
* **System:** 
Google Pixel 3 phone (Android 9.0) and Android emulator 6.0

#### Description

I observe two issues in which page titles are not correctly show.

(1) The first issue was found on the version v2.0.1, where the ``markor`` page title disappears when switching to other tabs and come back. 

I noted two similar issues #600 (reported in v1.8.3) and #457 (reported in v1.5.0), but was already fixed at that time. But the issue still exists in v2.0.1. I am not sure whether the root cause has been totally fixed.

Reproducing Video:

![markor_2 0 1_title_disappear](https://user-images.githubusercontent.com/3156978/79112158-3a8ea680-7d7e-11ea-9701-269f289f6573.gif)

(2) The second issue was found on the latest version v2.2.8, where the ``todo`` page title is not correctly shown (which shows ``markor`` instead) if I grant permission later. The title only updates when I switch to other tabs and come back.

![markor_2 2 8_and_2 0 1_incorrect_title_name](https://user-images.githubusercontent.com/3156978/79112259-7295e980-7d7e-11ea-9bd1-e6640d8a172f.gif)

**Comment by gsantner** [comment]
I've made an additional change on it, however I couldn't reproduce the issue and thus verify the fix.

Please verify then with the update after >2.2.8

**Comment by tingsu** [comment]
Thanks for your fix, @gsantner. I will help validate.
