### ISSUE TITLE
folder location in sd card issue.

### ISSUE THREAD

**Issue by stevenleeS0ht** [gsantner/markor#901]
#### General information

* **App version:** 2.2.8
* **System:** Android 9

#### Description

When choosing folder location in sd card (for example: `/xxx-sd/Documents/markor`). When creating first text file, it will save the file to `/xxx-sd/Documents/Documents/markor/hello1.md`. When creating second text file, it will save the file to `/xxx-sd/Documents/Documents/Documents/markdor/hello2.md`. 

There seems problem in path evaluation logic.

**Comment by gsantner** [comment]
#693

**Comment by gsantner** [comment]
See #603 comment
