### ISSUE TITLE
Create new file: Remember selection

### ISSUE THREAD

**Issue by evilDancingTeddyBear** [gsantner/markor#908]
It would be great if the default note type (when creating a new note) was the same type you selected on your previously created note. This way you don't have fiddle with the dropdown every time if you typically prefer plain text (or a different note type). Right now the default is always markdown.

Adding a default new file type to the settings is another solution, but I think this one is more user friendly won't clutter the settings menu

**Comment by gsantner** [comment]
Btw, duplicate of #845
