### ISSUE TITLE
external sd card access

### ISSUE THREAD

**Issue by pcause** [gsantner/markor#909]
I have an android 9 tablet and 10 phone.  I want to have my storage on external sd card.  Markor only shows the internal storage.   I know that in later android version you need to use certain api to access an external sd card.  Can this be added to markor

**Comment by gsantner** [comment]
See website FAQ how to.

**Comment by gsantner** [comment]
See also #631

**Comment by gsantner** [comment]
See also https://github.com/gsantner/markor/issues/603
