### ISSUE TITLE
New file-names should be trimmed

### ISSUE THREAD

**Issue by opensource21** [gsantner/markor#911]
#### General information

* **App version:**  2.2.9
* **System:** Android 9.1.0

#### Description
If I create a new file, the name should be trimmed. 
"My new file .md " should be "My new file.md"

**Comment by gsantner** [comment]
Hm, while it might be a nice-to-have feature, I don't see why it's a **should**/**must**. `My new file .md` is a totally fine and valid filename.

**Comment by opensource21** [comment]
Some keyboards added the space automatic after words, which is really handy for writing normal text. A blank after md will destroy the way how markor detect the type.
So it no a bug, only a feature-request. And it's really annoying.
I can't see a use case where the blank is wanted.

**Comment by gsantner** [comment]
Is there maybe a input type that disables the behaviour of the/your keyboard? I'm thinking of the noSuggestions option specifically.

**Comment by opensource21** [comment]
I used it often for protocols, so suggestions are very useful for me. (A button which inserts the date too).

**Comment by gsantner** [comment]
Well, you can experiment with inputType. Maybe you find something that doesn't add the space.

I personally would rather disable the dumb auto-space keyboard feature than implement workarounds for apps that are out there (not really specific to markor).

**Comment by opensource21** [comment]
Using the default of my phone and unfortunately there is no option for it. Markor is the first app where I struggle with it. So to have it as an option would be really great. I can create PR for it if wanted.

**Comment by gsantner** [comment]
I will add trim. But most things today I read about your device and it's software sounds like it's crap and spying on you ;).
