### ISSUE TITLE
Pressing 'back' in the toolbar in a file kicks me back to the root folder

### ISSUE THREAD

**Issue by harshad1** [gsantner/markor#916]
Using Markor 2.2.9 (F-Droid) on a Pixel 3 XL.

How to reproduce:
1. open a file located in a subfolder `root_folder -> subfolder_foo -> subfolder_bar -> test.md`
2. Press the back button in the _toolbar_
3. I am kicked back to `root_folder`

otoh:
1. open a file located in a subfolder `root_folder -> subfolder_foo -> subfolder_bar -> test.md`
2. Press the back button in the _navigation bar_
3. I am sent back to `subfolder_bar`

The toolbar and navigation bar back buttons should both send me back to `subfolder_bar`

**Comment by gsantner** [comment]
This is expecter/wanter behaviour. The "back button" in toolbar is "Home (android.R.id.home)", taking to the home of the previous or main activity.

For going normally back, there is the systemback button, or however "back" is defined in the system (like Pixel Back gesture)

**Comment by harshad1** [comment]
This behavior is surprising and not consistent with Android design or the behavior of other apps.

I would suggest changing the icon to 'home' if you want to keep the current behavior.

**Comment by gsantner** [comment]
Sorry but I currently dont plan to make changes on that button.
For what you want to do and need there is the normal back button.

**Comment by harshad1** [comment]
Will you accept a PR to add a settings option to change this behaviour?

Default -> go back to root?
Setting activated -> go back to the previous screen?

**Comment by aisbergde** [comment]
could you keep the behavior but change the button icon from the current used "back" icon to a "home" icon?
Seeing the back icon I also aspect a back to the current folder but not a back to root. The current combination is irritating.

**Comment by aisbergde** [comment]
or even better: put two icons
- home
- back

access to the OS back is complicated on some devices.

**Comment by anishmittal2020** [comment]
@gsantner System back

> For going normally back, there is the systemback button, or however "back" is defined in the system (like Pixel Back gesture)

@gsantner If I open a markdown file using the Shortcut. And if I use the back as you said, it closes the app!
