### ISSUE TITLE
Could the sharing function grab the content of a webpage

### ISSUE THREAD

**Issue by foxmask** [gsantner/markor#918]
Hi, 

#### General information

* **App version:** 2.2.10(113)
* **System:** Android 8.1.0

#### Description

when using the "sharing" function from a web page from a browser, could it be possible to: 

- add a "#" to set a title in front of the first line 
- get the body of the webpage to set the content of the markor note ? (and not just the URL of the webpage ?)

**Comment by gsantner** [comment]
1) The shown shared input is editable. So you can easy add or change to any format you like to. Dont plan to add some new option here, theres very many options already and not everything needs to be an option.

2. No. Markor is primary a offline app. I wont introduce anything that connects to internet on its own.
