### ISSUE TITLE
Question about, "create a new note " action, when using sharing function

### ISSUE THREAD

**Issue by foxmask** [gsantner/markor#919]
Hi, 

#### General information

* **App version:**  2.2.10
* **System:** Android 8.1.0

#### Description

Just a question, when we use the sharing function, from a webpage for example, the first choices are quicknote / sharing / clipboard / web browser.

But it seems to be a little bit weird as I come from a web browser with the sharing function.

I expected to be able to find "create a new note" before or after "quicknote".

Is it possible to move up the "create a new note" choice when we arriving from a sharing function from a browser ?
Thanks;)

**Comment by gsantner** [comment]
In most cases users share small portions in text, like links from browser.
And thats where exactly quicknote and todo comes in place, to quickly save the stuff and not think about it much.

When you really want to create a new file, you have the option always there. I dont plan to move it differently.
