### ISSUE TITLE
Tables not rendering

### ISSUE THREAD

**Issue by dugite-code** [gsantner/markor#92]
I know this has come up before but with the swap to commonmark-java I was hoping to see tables, but I am having no luck. I note there is the org.commonmark.ext.gfm.tables.TablesExtension in the code so I would have expected it to work.

#### General information

* **Device:**   Motorola force x
* **Android Version:**   Android 7.0
* **App version:**  0.15

#### Steps to reproduce

Enter markdown:
```
| First Header  | Second Header |
| ------------- | ------------- |
| Content Cell  | Content Cell  |
| Content Cell  | Content Cell  |
```

#### Expected result
| First Header  | Second Header |
| ------------- | ------------- |
| Content Cell  | Content Cell  |
| Content Cell  | Content Cell  |

**What do you see instead?**
```
| First Header  | Second Header || ------------- | ------------- || Content Cell  | Content Cell  || Content Cell  | Content Cell  |
```

**Comment by gsantner** [comment]
We cannot fix upstream's bugs, we got table-extension enabled [here](https://github.com/gsantner/markor/blob/master/app/src/main/java/net/gsantner/markor/renderer/MarkDownRenderer.java#L31).

**Comment by gsantner** [comment]
I tried it on current master and tables generated by <http://www.tablesgenerator.com/markdown_tables> do work. Maybe a little bad readability, but it does order column/row wise, and makes header bold.

Example:
```
| title       	| adsf           	| asdf        	|
|-------------	|----------------	|-------------	|
| hello world 	| asdfdsifj dsij 	| why         	|
| afd         	| afd            	| fsadfdsfdsg 	|
| adsf        	| test           	| asdf        	|
```

![screenshot_20171027-103904](https://user-images.githubusercontent.com/6735650/32095354-21fa3e76-bb03-11e7-87ff-30c5ed687c2c.png)

**Comment by dugite-code** [comment]
Thanks, looks like it was a simple format issue. An extra space looks like it's needed so: `|--  |` not `|-- |`

Sorry to waste your time
