### ISSUE TITLE
[Request] Allow change background and font color in reading mode

### ISSUE THREAD

**Issue by MelBourbon** [gsantner/markor#920]
#### General information

* **App version:** 2.2.10
* **System:** Android 9 on OnePlus 5T using Oxygen 9.0.11

#### Description
As a user I want to modify the color of the foreground (text) and background also in reading mode as I can do for the editing mode as I prefer a black on white reading instead of the current grey background.

**Comment by C-Y-Liu** [comment]
I think you can use the `inject head` function and modify the css of the page.
This is my view mode page with my modification.
![Screenshot_2020-05-07-21-12-13-225_net.gsantner.markor.jpg](https://i.loli.net/2020/05/07/DtTuwzZgQilJRUO.jpg)

**Comment by MelBourbon** [comment]
Ok, was not aware of this feature. Thanks. With this my request can be terminated.

**Comment by gsantner** [comment]
Exactly, yes with the Inject you can customize everything in view mode to detail own preference.
