### ISSUE TITLE
Note's last modification changes when moving it

### ISSUE THREAD

**Issue by alihardan** [gsantner/markor#921]
#### General information

* **App version:** 2.2.10
* **System:** Android 8.0

#### Description

When I move a note from a place to another using markor, timestamp of file changes; The file's last modification time will be the movement time.

When I move file using file manager, the behaviour is correct and moving not affect file modification time. 

Thanks again for your awesome app.

**Comment by gsantner** [comment]
It may me possible currently to modify mod-time per direct file acccess, but with [Androids  abstraction](https://developer.android.com/reference/androidx/documentfile/provider/DocumentFile) this won't be possible in future, and is not possible for sdcards already.

Closing as won't fix.
