### ISSUE TITLE
Feature to collapse sections

### ISSUE THREAD

**Issue by madeindjs** [gsantner/markor#922]
Is it possible to add a feature to add a button collapse a complete section.

This is an example on VSCode:

![Capture d’écran du 2020-05-08 10-23-23](https://user-images.githubusercontent.com/11815139/81386909-16707c00-9116-11ea-96bd-beddc3e1f170.png)
![Capture d’écran du 2020-05-08 10-23-42](https://user-images.githubusercontent.com/11815139/81386912-17a1a900-9116-11ea-8069-584c7e236240.png)

I think this feature is really useful when user work on a big markdown file.

PS: thank you for your work on this app. I use Markor everyday !

**Comment by gsantner** [comment]
Very hard with Android EditText. Wont be coming

**Comment by aisbergde** [comment]
Schade, dass es nicht implementiert werden wird. Aber die Idee ist schon gut! :-)
