### ISSUE TITLE
Tapping on "L" button in widget opens ToDo file instead of LinkBox.

### ISSUE THREAD

**Issue by bomzhellino** [gsantner/markor#927]
* **App version:** 
v.2.2.10 (113)
* **System:** 
Android Q Bliss ROM
#### Description
Tapping on "L" button in a widget opens ToDo file instead of LinkBox.

**Comment by gsantner** [comment]
LinkBox is no more since quite some time. LinkBox is just a file as any other now, there are no "LinkBox" specific in Markor anymore.

**Comment by gsantner** [comment]
with next update, will be "jump into app" instead of a "L" character.

![Screenshot_20200517-211849_OL_GS](https://user-images.githubusercontent.com/6735650/82157862-3b868c80-9884-11ea-9a77-6a0361c66710.png)
