### ISSUE TITLE
Feature request: please add an ability to change accent color of the app.

### ISSUE THREAD

**Issue by bomzhellino** [gsantner/markor#928]
Feature request: please add an ability to change accent color of the app.

**Comment by gsantner** [comment]
No, I want to keep the app more simple and applying custom colors to everywhere is a mess.

Also, the user might configure some color bad, making the app unusable.

**Comment by ELY3M** [comment]
my fork will have it.  I really hate pink color!   users need to be able to change color of the accent.  
I do agree that it may make a mess.
