### ISSUE TITLE
bolded and italicized text immediately followed by a comma not bolded/italicized in edit mode

### ISSUE THREAD

**Issue by 429IhD0** [gsantner/markor#930]
I slightly altered the regex

![image](https://user-images.githubusercontent.com/28206448/82364174-eb6f0d80-99dc-11ea-8414-e7514a905c7f.png)

now i no longer have ot leave a space between the comma and the closing asterisks 😆

![image](https://user-images.githubusercontent.com/28206448/82363997-aba82600-99dc-11ea-9463-a5e1e94bec10.png)

**Comment by gsantner** [comment]
You can send a pull request.


Please check/make sure it's not creating new issues.
Thanks

**Comment by 429IhD0** [comment]
will do when 

> You can send a pull request.
> 
> Please check/make sure it's not creating new issues.
> Thanks

Will do when do when I'm sure, after testing for a bit! I added period as well in my local version, since I find myself bolding/italicizing sentence-final words often enough :)

**Comment by gsantner** [comment]
Ok, i will just close this. See you then!

Be careful with dot regarding wildcard

**Comment by moshpirit** [comment]
I've noticed that this happens with "?", "!", "=", "_", "(", " ' " (without spaces) and probably many others
