### ISSUE TITLE
Markdown: Add code block action

### ISSUE THREAD

**Issue by aisbergde** [gsantner/markor#932]
#### General information

2.2.10
andoid
source Google play store

#### Description

format option for inline code is available. 
but I miss a quick format option to support code blocks like. 

I don't know how to print here so it will be not interpreted. I mean 
- starting 3 "`" 
- then code
- then ending 3 "`" 

```
line1
line2
```

**Comment by gsantner** [comment]
In next update, long pressing the code button will make a code block.

When no text selected, wrap current line in code block. When text selected on one or more lines, wrap all those lines in code block. 

![screenrecord](https://user-images.githubusercontent.com/6735650/82659141-b69aca80-9c17-11ea-9989-08a6db9e9193.gif)
