### ISSUE TITLE
todo: handling image link

### ISSUE THREAD

**Issue by aisbergde** [gsantner/markor#933]
#### General information

* **App version:** 2.2.10 (113)
* **System:** 

#### Description

it is possible to add pictures to a todo task. But nothing can be done with it, it's only displayed as text

`2020-05-21 ykykykyyk <img style='width:auto;max-height: 256px;' alt='Markor_2020-05-21T18-57-22' src='Markor_2020-05-21T18-57-22.jpg' />`

why not to make this a link which can be clicked to see the image? 

Or maybe it could be shown in the view modus?

**Comment by gsantner** [comment]
Todo is for taking notes in plaintext. HTML is not supposed to be added / should not be expected to render in view mode.

The "attach" functions of Markor work the same way for all  Formats, but realistically for todo.txt images do not make sense.

**Comment by aisbergde** [comment]
> The "attach" functions of Markor work the same way for all Formats, but realistically for todo.txt images do not make sense.

that's the point I was irritated: Why to add an image if nothing is done with this image.

I don't understand why something can be added if this can't be used, not only images but also other attachments. But maybe there are some scenarios when this could be useful, Currently I have no idea how to use this feature.

**Comment by gsantner** [comment]
The point of some of the "attachment" options are, that you are able to create pics/audio and copy it to folder. You can always reference them then in the folder from other (i.e. markdown) files.

- Color: OK..valid user interest to insert a hex color
- Link: OK..valid user interest to add something with http to todo
- File: Copy file to current folder  (not makes sense to show in todo)
- Image: Copy image, or take image with camera, copy to current folder (not makes sense to show in todo)
- Audio: Same as for Image
- Date: OK..valid user interest to add date

**Comment by aisbergde** [comment]
I think I got the idea (or a part of the idea):

These features in the todo section are not only to create "**real** todo entries" but they are also a way to prepare something to be later used, for example in mardown files. So *they are* something to do, and the todo list a valid place :-)

And it could be a good idea to share some content with the todo list from other apps.

BTW, your comment gives some very good ideas how to use todo in combination with markdown editor and why it makes sense to use them together in one app. Why not to add some of this ideas in the documentation (the link from the app to the help / FAQ)

**Comment by gsantner** [comment]
Yeah FAQ gets extended from time to time when something gets asked over and over :D.

If you feel like a specific question/information should be added I'm happy to add something. I'm also happy to add it when a user writes/describes it as myself often things are 100% clear as I programm it (Different/user perspective)
