### ISSUE TITLE
Feature request: Side bar showing table of contents

### ISSUE THREAD

**Issue by JackalZhao** [gsantner/markor#936]
#### General information

It is exhausting to pan over a long document (probably when more than 5000 words), it is so hard to navigate easily. So I suggest Markor could add an **side bar** which could be swipe out to show the table of contents whecher in **preview mode** or **edit mode**.  

The pictures below shows some example of **table of contents** for markdown document: 

![image](https://user-images.githubusercontent.com/19181833/82652815-d39fbf80-9c50-11ea-86f8-08c889f672e6.png)

![image](https://user-images.githubusercontent.com/19181833/82652847-e0bcae80-9c50-11ea-9fee-6981c5ff16a6.png)

**Comment by gsantner** [comment]
#660

**Comment by gsantner** [comment]
Implemented now, see #690

**Comment by gsantner** [comment]
Implemented now, see #790
