### ISSUE TITLE
todo.txt - attachment: create "note" as link to markdown file: "note:<file>"

### ISSUE THREAD

**Issue by aisbergde** [gsantner/markor#937]
#### Description

I installed this VS Code extension
https://marketplace.visualstudio.com/items?itemName=davraamides.todotxt-mode

And I like this idea:

- Save selection to a note and add to a task as a note:<file> metadata tag, with preview

Markor can already add several links to the todo-file.

It should be easy to create a new attachment type "markdown note" or "note":

the user can select an existing markdown file (or can create a new one) similar to taking photos and a `note:<file>` will be added, like:

`(B) 2020-05-21 ykykykyk note:Demo-Note-20200522-130048.md`

Markor is a great combination from todo.txt and markdown and this idea should be compatible with Markor's philosophy.

Even it Markor will not (yet) display this as a clickable link to a markdown file, the todo.txt can be "processed" by other todo.txt programs which can handle and show the notes.

**Comment by gsantner** [comment]
Is this somehow part of todo.txt community specs, or supported in other todo.txt applications? I prefer to have enough features for it to work, but not bloat it with everything that is out there.

**Comment by aisbergde** [comment]
I would say, it is:

https://github.com/todotxt/todo.txt-cli/wiki/Todo.sh-Add-on-Directory

https://github.com/todotxt/todo.txt-cli/wiki/Todo.sh-Add-on-Directory#note--take-notes-related-to-tasks

**Comment by gsantner** [comment]
I'm closing this as won't fix. For the reason, the user can select a file of any type and not just plaintext files. Hence `note:` is a different thing. And something I currently don't think of adding to Markor. todo.txt is supposed to be lightweight and simple: 1 todo = 1 line of text. I don't want todo.txt implementation to be much more complicated than the initial spec is.
