### ISSUE TITLE
explain (document), what is the "dedicated launcher"?

### ISSUE THREAD

**Issue by aisbergde** [gsantner/markor#938]
#### General information

* **App version:** 
* **System:** 

#### Description

there is an option "Launcher (Spezielle Dokumente)
I enabled this, but I don't see an effect.
searching https://gsantner.net/project/markor.html I found only
"or by using the dedicated launcher"
and I have no idea what does it mean.

Could you extend the documentation a little bit and explain?
Or add some description directly in the app?

**Comment by gsantner** [comment]
adds seperate launcher for quicknote and todo. just like markor icon/button.

**Comment by aisbergde** [comment]
I think I got it:
if I long press on the icon I get a context menu and I can select one of 4 actions. 

It was not clear for me that this feature is called "dedicated lancher".  I was looking something to be created in the app list of the android launcher.

If the "normal user" knows what a dedicated lancher is, fine, I didn't know, that'w why I suggest to explain this a little bit.

**Comment by gsantner** [comment]
added section in faq
