### ISSUE TITLE
Documentation: "experimental functions"

### ISSUE THREAD

**Issue by aisbergde** [gsantner/markor#939]
#### General information

* **App version:** 
* **System:** 

#### Description

in the settings "experimental functions" can be enabled, but the user get's no hint what will be enabled. I have seen, that "Datei-Verschlüsselungs-Passwort" will be enabled, but it is not clear of there also other features will be enabled in other places.

I suggest to make this more transparent, there could be different ways to to:
- list the experimental features in a sub menu of experimental features
- if this is not possible, use a suffix " (experimental)" for these features in the place where they are located
- ...

**Comment by aisbergde** [comment]
one more issue with experimental features: if this option will be disabled but some experimental functions have been enabled they still are enabled but now they can't be disabled, because they are not shown.

it would be more intuitive to disable all experimental features if this setting is disabled.

**Comment by gsantner** [comment]
theres not much left as most things are not marked experimental anymore, and the others are mainly expert options. Won't make a specific documentation about this.
