### ISSUE TITLE
todo.txt - move current line to another file, move items with selected tag to another file

### ISSUE THREAD

**Issue by aisbergde** [gsantner/markor#940]
#### General information

* **App version:** 
* **System:** 

#### Description

currently it is possible to move completed tasks (done) tasks to another file.

I would request a feature to remove also non completed lines from the current todo-document to another selectable file:
- the current line
- multiple lines based on tag

For example:

the classic GTD method uses
- todo
- done
- someday
- waiting

some people have other lists.

Markor support to move the "x" marked completed tasks to another file. But it is complicated to move a "normal" line (or lines) from one file into another file. On a desktop this could be easy done by using a multi window editor. In Markor (and general in Android) this is hard to do: 
select in first file and move to clipboard, open another file, past from clipboard, ...

the "move multiple lines based on tag" I imagine this way:
- enter the tag (or select from the list of tags)
- move entries to other files
  - select the target file
  - or (I would prefer this) use some automatic and use the tag as part of the filename:
    - if the current file is `todo.text` and the tag is "+waiting" then move to `wating.text`
    - if the current file is `inbox.todo.text` and the tag is "+waiting" then move to `wating.todo.text`

**Comment by gsantner** [comment]
I want to keep todo simple, just like the format is simple.
For moving "archiving todo" tasks, copy-paste is always a option, and done tasks as one would move e.g. done tasks already off with archiving the file should be then empty.

**Comment by aisbergde** [comment]
if there would be a **filter by list or tag** (context or project) then it would be easy:

- filter by list or tag
- mark all
- cut
- past into another file

This not a problem on a PC, but there are not so much Android apps for todo.txt
I found only 4 of them:

- in one I can't open a different file, and I think it will work only with one file at a time
- one is working with 2 files for `todo` and `done` which needs to be configured in settings, it will be complicated to switch to other files
- one can open different files but can`t show the whole file as text (or I don't know how)
- Markor can easy switch between different files and it can switch between editor and preview, but it is the only one which can't filter data

Maybe there are other "normal" Android text editors which can filter lines by a containing word. But the easiest handling would be if Markor could filter lines. 

I am not an app programmer and I can not contribute to much in this case. I am a specialist for BI, database, dwh... Or I could try to understand the code :-) 

I am fascinated by the idea to use a plain text file for task management. But I need to find a way to work not only the PC but also on Android. If I am onside in projects I am normally several days without my personal laptop but working on customers hardware. Maybe I should try to combine the Android apps with some Web apps. But my goal is to find a solution which will on Windows PC and Android without the need of a third web tool.

**Comment by gsantner** [comment]
for filter as in "search by tag", "search by category/project", you can long-press the buttons. I know you look for editing features, but that maybe helps.

This "search by type on long click" at todo is implemented for category,tag,priority.

**Comment by gsantner** [comment]
for filter as in "search by tag", "search by category", you can long-press the buttons. Then you get a selection of all existing tags/categories. Let's say it contains home,garden etc.. When you click on `@garden` then, all `@garden` todos show up. I know you look for editing features, but that maybe helps.

**Comment by aisbergde** [comment]
This is fine! 

That means a kind of filter is already implemented. I get a list and the list contains what I need.
What about using this feature and extend it a little bit?

- There could be a separate list view beside edit and preview
-...

**Comment by gsantner** [comment]
I dont plan a "third mode"

**Comment by aisbergde** [comment]
and I am afraid you don't plan any actions directly in this list?
Anyway this list helps ☺️

**Comment by gsantner** [comment]
KISS principle :D

**Comment by harshad1** [comment]
@aisbergde Are you looking for something similar to todoist's 'remember search' feature?

This would require
1. defining a search grammar
2. adding a grammar based filtering mechanism
3. adding a way to remember filters

**Comment by aisbergde** [comment]
Currently I found a solition:
I use simplenote on the same file, they have all filters I need and I can even save them. This is fine for me and I don't miss it so much in Markor anymore

**Comment by aisbergde** [comment]
I mean: SimpleTask, not simplenote
