### ISSUE TITLE
todo.txt sort by duedate compatiblity with other lineending

### ISSUE THREAD

**Issue by aisbergde** [gsantner/markor#941]
#### General information

* **App version:** 
* **System:** 

#### Description

editing a todo txt the order by due date doesn't work

**Comment by gsantner** [comment]
I can not confirm this. Works well. Also added unit test for sort-by-duedate which results with :heavy_check_mark:  in both descending and ascending case.

Also manually tried it and works well.

![screenrecord](https://user-images.githubusercontent.com/6735650/82738343-70805c80-9d26-11ea-99ca-fd16d3c81132.gif)

**Comment by aisbergde** [comment]
do you have a newer version?
I also made a video, but I need to find out how to upload it using this github app here.

**Comment by gsantner** [comment]
Git version but I'm 100% sure that I haven't done changes on that part since last release (`https://github.com/gsantner/markor/compare/v2.2.10...master`), even more not since about autumn

**Comment by aisbergde** [comment]
I can't find how to upload the video. Maybe I need to do this when I am on the PC. I can also try to share the file I used to test the sorting.

**Comment by gsantner** [comment]
github only support gif sadly, or external links

**Comment by aisbergde** [comment]
![Screenrecorder-2020-05-24-00-41](https://user-images.githubusercontent.com/9020187/82742222-8eb47f80-9d5b-11ea-96ac-4e57e95496df.gif)
I converted the video to gif

**Comment by gsantner** [comment]
hmm interesting. Please report back if you still encounter when next update is out.

**Comment by aisbergde** [comment]
[example.todo.txt](https://github.com/gsantner/markor/files/4672679/example.todo.txt)

You could also try this file, maybe there is something special in this file.

**Comment by gsantner** [comment]
Probably it's due the file seems to use a ?different? linefeed. Markor works on `\n` basis as standard on Android/Linux.

![grafik](https://user-images.githubusercontent.com/6735650/82742455-accfaf00-9d5e-11ea-86cd-46e4a1487430.png)

**Comment by aisbergde** [comment]
but all other sorting is working.

You can try to reproduce (I just was able to reproduce):
- use Markor tor create a new file, based on the todo example
- in one column add the " due:" at the end and then use the toolbox to insert the current date after the " due:"
- change the date manually
- do something similar in another line
- try to use all kind of sorting. All sorting are working but not sorting by due date

Maybe yo need to switch to german language.

**Comment by aisbergde** [comment]
the different file could happen because I sync data with my OneDrive using FolderSync (as you suggest) and OneDrive is syncing with my PC. I uploaded from the PC because I can't find how to upload something to github on android.

**Comment by gsantner** [comment]
When you move the due to middle of the task (on your computer!) does sort by due work then?

**Comment by gsantner** [comment]
Oh I see theres already a older line-ending task. So in general, `Determine and keep EOL (for saving/reading files) (\n vs \r\n)` #827 is the correct place then for generic line-ending stuff.

specific sort question only fine here.

**Comment by aisbergde** [comment]
only to be clear:

the "not sorting by due date issue" happens directly after creating the sample file and adding two due dates directly in Markor, without any synchronizing with desktop. 

The question is: 
can this be reproduced or not, as I described?

**Comment by gsantner** [comment]
I cannot reproduce. I've downloaded your file and it sorts...

Also works fine for new example file with two due's added.

![video_2020-05-24_14-55-20](https://user-images.githubusercontent.com/6735650/82754651-e257b500-9dbd-11ea-93a0-dccfae1647c7.gif)

**Comment by aisbergde** [comment]
very strange. I can reproduce on both devices, Android 7 and 10. The sorting also doesn't work when I add some text behind the due dates.

I will wait for a new version and then retry. Please keep the issue open even if you can't reproduce on your device.

I hope my syntax is right?
due:yyyy-mm-dd

**Comment by gsantner** [comment]
Jup.
You can also long-press the date button. In todo format it adds `due in 3 days from today`
