### ISSUE TITLE
Special keys menu: Add list option for "cursor select whole line" 

### ISSUE THREAD

**Issue by aisbergde** [gsantner/markor#942]
#### General information

* **App version:** 
* **System:** 

#### Description

it is hard to mark a whole line (which is a task), for example to move the line from one file to another. Please add a new keyboard action to mark a whole line.

**Comment by gsantner** [comment]
the first button (checkbox) is exactly for this

**Comment by aisbergde** [comment]
no, the first button will add or remove the "x" to mark or unmark the task as comleted.

what I am asking for is a quick way to mark the text of one line as selected text so I can use the context menu on this selected text to copy or cut.

the request behind is to find a way how to move a task (line) between different files, but not only to the done file.

**Comment by gsantner** [comment]
As in keyboard, hardware key-combination? Than <https://github.com/gsantner/markor/issues/154> duplicate

**Comment by gsantner** [comment]
Thanks now I know where you mean. Is quite easy to add, so when somebody reads this: for functionality it's two invocations, plus if+string.

**Comment by gsantner** [comment]
thanks @harshad1
