### ISSUE TITLE
hUUID crashes the app on Android 7.0 tablet

### ISSUE THREAD

**Issue by aisbergde** [gsantner/markor#945]
#### General information

* **App version:** 
* **System:** 
Android 7.0
Tablet Teclast 
T10(E3C5)

#### Description

hUUID works fine on my smartphone.
But I also installed Markor on a Tablet
And every time when I try to create a new line in the todo with hUUID option 'on' the app crashes. And together with the App there is a message that also Google Playstore crashes.
With disabled hUIDD no issues.

I only tested the hUUID and don't know if I really need it and the tablet is not so important.

I only want to report the existence of the bug. It is not so important for me to fix it.

There are no updates for the tablet and the Android Version is from April 2017

#### Log

I will only create logs if you are interested

**Comment by gsantner** [comment]
This is one of the reasons I don't specifically announce experiments (#939 ) atm. I don't plan to make changes/fixes on experiments unless I feel theres a need to make it out-of-experiment :D.

**Comment by aisbergde** [comment]
but how a user can know that this an experimental feature?
The feature is there in the menu or it isn't and a user will not know what is experimental. 
that's why I asked to give hint's in setiings if something is experimental.

I see, to create a logfile is not that easy... I will check what I can do.
maybe I will first try to use the build in debugging function.

**Comment by gsantner** [comment]
Hm then I think really you have a older version. Because it was shortly out and then changed to experimental. (i.e. option shows only up when you enabled experimental settings).

What app version is it?

**Comment by aisbergde** [comment]
zur Debug Funktion: da steht 
> eine zusätzliche Option "Debug Log senden" im oberen Menü wird hinzugefügt...
Bei mir wird nirgendwo etwas hinzugefügt, in keinem Menü

**Comment by gsantner** [comment]
Die bringt in dem fall nichts.
Aber mir war ein problem bekannt in der ersten huuid version das schon gefixed ist.

Nachdem du huuid siehst ohne experimental, hast du noch die alte version wo das noch nicht behoben ist.

**Comment by aisbergde** [comment]
hUUID is only shown when experimental is "on"
But I can't know what is experimental and what isn't becaue I can't compare. That's why I suggested a hint on each experimental feature. 

the version is the latest avilable from Play Store: 2.2.10(113)

**Comment by aisbergde** [comment]
dann teste ich das einfach noch mal, wenn eine neuere Version raus ist. Oder kann ich die schon irgendwo laden?
Also nicht, dass ich die selbst aus Code compiliere, so was habe ich noch nicht gemacht. Das Repo selbst clone ich gerne, wenn das ausreichend sein sollte.

**Comment by gsantner** [comment]
Auf F-Droid sind die Updates normalerweiße zuerst, <https://f-droid.org/de/packages/net.gsantner.markor/> <https://f-droid.org/de/>

**Comment by aisbergde** [comment]
ich lade meistens Apps aus dem Google Play store, wenn es da nicht zu finden ist, auch mal aus f-droid.
Irgendwas aus Github verwende ich normaler nicht, zumindest nicht für Android. Es sei denn, ich würde dazu extra aufgefordert, zum Testen beispielsweise. 

Ich habe eben in f-droid nachgeschaut, da steht, das Markor vor 3 Monaten aktualisiert wurde und dass ich die aktuelle Version habe. Ich habe ja auch geschrieben, welche ich habe: 2.2.10 (113)
Also ist das schon das, was aktuell verfügbar ist.

**Comment by aisbergde** [comment]
vergiss das mit den 3 Monaten, das steht so in der App. Auf der Website (dein erster Link) steht das "richtiger" beschrieben.

**Comment by gsantner** [comment]
Also aktuell aus gplay installiert?

**Comment by gsantner** [comment]
hab die funktion mal unbenannt. aus irgendeinem grund scheinen einige geräte die funktion in der runtime zu ?blockieren? (XPosed zb)
