### ISSUE TITLE
ShareInto: After sharing, show confirmation containing openfile button

### ISSUE THREAD

**Issue by aisbergde** [gsantner/markor#946]
I tried several times to share a link to QickNote. Sometimes this works, sometimes not: the links are not available in Qicknotes, they have not been created. 

It looks like this (not creating) only happens, if in Markor the QickNote is currently open. But sometimes entries are also created if QickNote is open. I did not find a clear logic.

So I started to switch to Markor each time after sharing a link. I would suggest something from these variants:
- an option to automatically switch to QuickNote (or todo) to be able to check if the link was created
- better: some short confirmation from Markor (a Pop up Window) that the link qas copied. This could be combined with a button like "Click here to see in Markor" to jump to the just created entry.  
If I share something to "Pocket" I get this kind of confirmation pop up for a few seconds and so I can be sure that an entry was created.

Anyway it will be useful to be able to jump to the new entry:
- if it is a todo task some category or tag can be assigned
- if it is a Quicknote some comments could be added

And this is also compatible with your KISS prinicipals, a confirmation about success is always better then sharing some links and later seeing that nothing was saved.

**Comment by gsantner** [comment]
I'm using QuickNote every day, and haven't failed me yet at any time.
But yeah, probably adding a snackbar or click-toast makse sense.

**Comment by aisbergde** [comment]
Maybe I got this issues only on the tablet running on Android 7. It looks like on the smartphone with Android 10 it works better or even stable.

**Comment by gsantner** [comment]
Rel: #925
