### ISSUE TITLE
Elastic landscape layout (file hierachy, outline and text at same time)

### ISSUE THREAD

**Issue by JackalZhao** [gsantner/markor#948]
### Description

Preview looks like: 

![image](https://user-images.githubusercontent.com/19181833/82756393-9b44e080-9e0c-11ea-8e1a-696c071e4b4e.png)

This landscape layout is one of my thoughts, inspired by [liandi](https://github.com/88250/liandi), which could help users to manage and preview markdown documents on their phone more efficient. 

It has four columns

- The left one is mount folders, which lists all the document folders users added. 
- The next column lists the files and subfolders of the selected main folder. 
- The third column is the outline column ( I think this may be hided if needed )
- The forth column is the preview column, which shows the content of the document. 

Users can use this layout to manage and view their files, instead of constantly back and forth to check documents. When editing is needed, Markor can turn back to portrait mode to edit more efficiently.

**Comment by gsantner** [comment]
Hey I'm sorry but quite sure this will be a wontfix. For two reasons:

* On phones, barely a editor for one file fits. Hence split doesn't make sense.
* On tables might makes sense, but **big** Android tablets are not very much used... And even in that case, my opinion is that the more content-text fits, the better.
