### ISSUE TITLE
remember latest used folder

### ISSUE THREAD

**Issue by aisbergde** [gsantner/markor#949]
#### General information

* **App version:** 
* **System:** 

#### Description

switching to "files" always the root folder is used. 
I want to request to use the latest used folder. 
for example if todo files are in the subfolder 'todo' and I open a file then I want to be in this folder 'todo' again when I want to select a different file, but I don't want to start in the root folder again.

**Comment by gsantner** [comment]
when you open a file, press back button, and so open files again..you should be in "old" folder, and at same scroll state. At least thats how works since long time

**Comment by aisbergde** [comment]
I understand the logic behind, but this is not the way I usually work.

example:
- I select any file (todo or md) to view or edit
- I switch from todo to QuickNote
- now I want to open another todo file
- why I should go back to a file I opened before if I am not interested in the content of  this file, but I want to open a different file?
- for me the "natural" way is to go to "files" directly as I do on any desktop system if I want to open another file.

Why I should work a different way on the smartphone? And on the desktop I know that the folder keeps it's state. It is irritating when the behavior on the smartphone is different and when I should not go directly to the target but first to another file.

**Comment by aisbergde** [comment]
the back button doesn't return to the latest used folder, it returns to the root folder. I tested on 2 different devices.

**Comment by gsantner** [comment]
> the back button doesn't return to the latest used folder, it returns to the root folder. I tested on 2 different devices.

This is not a bug, but how it's intentionally this way. See `https://github.com/gsantner/markor/issues/916#issuecomment-623157290`. For normal go back, use the OS back button (or OS back gesture).

**Comment by aisbergde** [comment]
I got it, but it is complicated on my android 7 tablet: first I need to hide the keyboard, only then I get access to the OS back butten, but it works.
