### ISSUE TITLE
Question regarding katex frac rendering

### ISSUE THREAD

**Issue by yashpalgoyal1304** [gsantner/markor#952]
#### General information

* **App version:** Version v2.2.10 (113) F-Droid
* **System:** AOSP 6.0 M

#### Description
The [`\frac` function family](https://katex.org/docs/supported.html#fractions-and-binomials) is rendered without the horizontal dividing bar. The above link contains how it should look.

Input: `$ I = \frac V R $`

![Frac Rendering](https://user-images.githubusercontent.com/19423063/82840928-f1d81a80-9ef1-11ea-9b43-50c33cda6583.jpg)

Input: `$ v_{max}^2 = R g \Big( \dfrac{\mu_s + tan \theta}{1 - \mu_s tan \theta} \Big) $`

![frac rendering](https://user-images.githubusercontent.com/19423063/82839889-79238f00-9eee-11ea-9960-9ee13e4b5d1e.jpg)

**Comment by gsantner** [comment]
Is it due colors? Can you see the line white light mode? Otherwise, please ask at KaTex how to correctly use it.

**Comment by yashpalgoyal1304** [comment]
Nope, not visible in light mode either. I dont understand the last sentence.

**Comment by gsantner** [comment]
Try other projects/katex website with frac, or ask at katex bugtracker.

**Comment by yashpalgoyal1304** [comment]
I have used it in Gitlab which uses KaTeX and it is rendered with no problems/issues.

**Comment by gsantner** [comment]
I cannot reproduce your issue, works fine for me...

Maybe try to wrap it with a div. 

```
<div markdown="0">
math
</div>
```

![1](https://user-images.githubusercontent.com/6735650/82841578-2635e180-9ec6-11ea-97f4-62e96f929936.png)


![Screenshot_20200525-222647_Markor](https://user-images.githubusercontent.com/6735650/82841588-2a61ff00-9ec6-11ea-9ff5-fb1022b356f5.png)

**Comment by yashpalgoyal1304** [comment]
Glad to see it working. Okay, i will try

**Comment by gsantner** [comment]
Then reset Markor app settings. I tried it on two devices now and it always worked for me.

Also, check if theres maybe another syntax error somewhere maybe?

**Comment by yashpalgoyal1304** [comment]
From where can I reset?

**Comment by gsantner** [comment]
Android systemsettings.

As you say, you have some font issues, so don't really looks like it's a markor specific issue.

Markor also comes bundled with some other fonts, you can try them as well. Set them via Markor settings.

**Comment by yashpalgoyal1304** [comment]
This issue shouldnt be closed. As it is NOT solved yet. I get that it *might* be some problem with my phone, but it is not investigated what yet. And no way to test that is suggested either.

With that said, i will propose to reopen this issue.

**Comment by yashpalgoyal1304** [comment]
I tried sharing as `HTML`, and pasting the output to a .html file saved in the same directory (/Documents/markor/) and i was shown plain text on opening that file with any browser - inbuilt `Browser` , inbuilt `HTML Viewer` , MiXplorer's `HTML Viewer` and so on.

**Comment by gsantner** [comment]
KaTex is rendered at runtime by javascript. That only comes with with Markor bundled.
For exported html, thats not there hence mah not rendered.

There you need pdf export or alike instead.

**Comment by yashpalgoyal1304** [comment]
> exported html, thats not there hence mah not rendered.

Okay, my intent was not to point out error here. I was trying to troubleshoot and see if i somehow can check the rendering in other things. Do u know any other android app or any other way in which i can test if it works or not??

**Comment by yashpalgoyal1304** [comment]
In further investigation, 

1. i couldnt find any other app on F-droid which renders TeX or any if its variation. So, I went over to ApkPure.com to search for apps. It contains many apps. I tried this one: [LaTeX equation editor: Unicode Math Symbols](https://apkpure.com/p/net.blackenvelope.write.latex) and it is rendering fine as well. It was crashing for some reason after 10-30s and i couldnt select the output.

![Screenshot_2020-05-26-16-36-30~01](https://user-images.githubusercontent.com/19423063/82893785-2fc75400-9f6f-11ea-9d0e-410909443c4c.png)

2. The other apps which support equation input like [μMath+](https://f-droid.org/app/com.mkulesh.micromath.plus) or [Equation Editor](https://apkpure.com/p/com.tinkutara.mathchat) perform editing via GUI so i didnt test with those and the like.

3. This app mentioned LaTeX: [arXiv eXplorer](https://f-droid.org/app/com.gbeatty.arxiv) but i couldnt find any article which contains any fractions in the app. On clicking download, the [pdf downloaded](http://arxiv.org/abs/2005.12185v1) rendered fraction just fine (and the pdf is not raster, i.e. i am able to select the fraction text). If u could find an article which contains fraction in the description in app, please let me know. I will check it.

Thing to notice: the bar doesnt seem selectable (the minus sign was selectable) even on extending selections some more. Can that help somehow?

![Screenshot_2020-05-26-16-39-03~01](https://user-images.githubusercontent.com/19423063/82894053-9a788f80-9f6f-11ea-8abf-021048b18201.png)

4. Finally I turned online. I am using [Vivaldi 3.0 browser](https://vivaldi.com/download/). And `a = \dfrac b c` was rendered correct on https://katex.org/ and https://arachnoid.com/latex/ . The output seems selectable on both

**Comment by yashpalgoyal1304** [comment]
Throwing in some further links which i am searching on surface. If u think they can be helpful in investigation, I will try to look into them: [Radical Expressions](https://apkpure.com/p/com.dspsoft.radicalexpressions)

**Comment by gsantner** [comment]
OK so:

* I cannot reproduce the issue. 
* I don't know the **exact** reason why its missing for you.
* Its not missing on others devices and users, otherwise it would have been reported already ( frac is fairly common). Also got some emails with questions and screenshots where I do see other people having used fracs and they do render.

Thus:

* I close the issue as cannot reproduce and I cannot help you.
* You need to install android sdk/studio on your PC and debug Markor on your own, when you want to get it fixed.
