### ISSUE TITLE
it should be possible to use + in filenames when creating new files

### ISSUE THREAD

**Issue by aisbergde** [gsantner/markor#953]
#### General information

* **App version:** 
* **System:** 

#### Description

"+" is a valid char in filenames, when creating new files it should be possible to use them in filenames
currently when I create a new file any + is ignored by Markor. 
After creating files I have to use a file manager to rename them.

I want to use @ and + in filenames to use the same names as for context and project in todo.txt

**Comment by gsantner** [comment]
I have removed + from inputfilter of illegal chars,  @ was already allowed.  
But, do yourself a favor and dont.   
Don't  use any of those `https://www.mtu.edu/umc/services/digital/writing/characters-avoid/`. At least one application will always fail you.

**Comment by aisbergde** [comment]
thanks for advice, I will try to consider to not use these charactes. 

Currently I am setting up a new "based on markdown notes system". I will try to find or build a system which will parse the content of files and extract @abc and +def as keywords to put them in file properties. 

I got the idea to use the @abc and +def in filenames in one blog about using gtd with todotxt and the idea behind is to better search by tags. In Widows I can enable full text search for content and that's fine. Therefore I will not need the "+". For Android I have to find a way...

**Comment by gsantner** [comment]
I suggest you to use jekyll style filenaming (where Markor also has a template).

This way you can later easily spinup a simple webserver with your notes beaufully serverd as webpage/blogpage.

This is exactly what I do myself, <https://gsantner.net/> is built with Jekyll. And I write the content with Markor among others.

**Comment by aisbergde** [comment]
I will investigate this jekyll style.

Today I found Notable as markdown based notes system counterparts on windows which should work fine with Markor and when I see the Markor jekyll template then I see something similar elements. 

I will investigate this jekyll system. Thank you for advising!

**Comment by aisbergde** [comment]
@gsantner 
Do you have any advise how to use tags or content on android? For example my documents could be start this way, as you suggested:

```
---
tags: [android, git, notizen, pc, sync, todotxt]
title: git notizen todotxt sync pc android
created: '2020-05-27T07:50:23.030Z'
modified: '2020-05-28T17:50:26.420Z'
---
```

But how to extract the metadata on android without full text search? The only idea I have is to use all tags in the title and the title as filename `git notizen todotxt sync pc android.md`
Then Markor (and any file explorer) should be able to find these tags because they are part of some filename.

Do you use another way to extract metadata from files to search by them - on Android?

I also found one app DocSearch I could use for fulltext search. But maybe there are some other ideas? Do you use Markor as notes system?

**Comment by gsantner** [comment]
Everything in content, including "tags" field is for Jekyll.

I name files (and their parent folders) accorringly so I can find them. This way any `unix find -iname` or normal desktop filemanager search can also find them in the same way.

**Comment by aisbergde** [comment]
this is the easiest way. Currently I do the same.

**Comment by aisbergde** [comment]
@gsantner 
it looks like using jekyll style yaml front matter is the best solution for tagging. Some desktop apps can handle this and that's why it is easy to use tags in yaml front matter on the desktop to filter and list. But I did not yet find an android solution allowing this. 

I know you don't want to install any kind of full text search. But maybe some yaml front matter support would be fine?

Or do you know any solution how to manage tags in markdown files on android?

**Comment by gsantner** [comment]
**Anything** that means reading any portion of text of multiple files in paralell..is a nope.

**Comment by aisbergde** [comment]
I could imagine to parse multiple file content on desktop to create one (1)  mapping file on desktop and to synchronize this file with android. Or better one file per directory. 

Could you imagine that Markor will read one file instead of multiple files and uses information in this optional file containing a mapping between tags and filenames?
