### ISSUE TITLE
additional full text search

### ISSUE THREAD

**Issue by aisbergde** [gsantner/markor#956]
#### General information

* **App version:** 
* **System:** 

#### Description

I would like to use Makor as editor in a markdown notes system. But currently in Markor I can only search in filenames. I use @abc and +def in filenames to tag (That's why Markor should allow "+" in new created filenames).

But if I want to build a markdown bases notes system I would need a full text search. For now I will try some external apps to access the Markor files. But maybe you want to extend Markor. 

Maybe there are some suggestions for existing apps I could use?

**Comment by gsantner** [comment]
This has been requested multiple times already. Wontfix.

Some devices even have issues reading a single full file...doing that recursive? no thanks. Markor stays lightweight and without any index db.
