### ISSUE TITLE
make long file names easier to read

### ISSUE THREAD

**Issue by aisbergde** [gsantner/markor#961]
I build filenames from keywords. It is hard to read (and therefore select) long filenames, especially in portrait mode. It would be fine, if
- I could set a much smaller font size for filenames, not bold, whatever could help to show longer portions of the name
- long filenames would be displayed in a treadmill (Laufband): automatic vertical scrolling of long names if they are to long to be completely displayed. Some file explorers have this feature.

**Comment by gsantner** [comment]
I think it makes sense to close as duplicate for #524 and improve the description to generic "file browser filename customization"

**Comment by Groxx** [comment]
Just to toss in another option:
In cases where there's a large duplicated middle chunk between many files, the middle could be "..."'d.  It won't cover all cases, but might reduce the amount of multi-line / scrolling names that need to be shown.
