### ISSUE TITLE
File browser scrolling sometimes not works

### ISSUE THREAD

**Issue by aisbergde** [gsantner/markor#962]
quite often I have the issue that vertical scrolling in Markor file browser stops to work. Killing Markor in the list oft running apps and restart solves the issue. But it happen too often: several times per day. And  in the last maybe 10 minutes I had to start 3 times.

Maybe this is also related to not every time working of a selection per long press. Often I can long press a file and it will be selected, I can use the rename butten to see the full name. But very often nothing happens on a long press on a file. And it looks like these no scrolling issues could be related to the no able to select issue.

**Comment by gsantner** [comment]
Can somebody else reproduce the issue? I haven't seen that one yet

**Comment by gsantner** [comment]
@aisbergde  by the way, do you use XPosed, XPrivacy, Magisk or anything like that? (which does code injection or overlays)

**Comment by aisbergde** [comment]
non of these, but maybe some other which does something unwanted. And maybe I use the same on Smartphone and on tablet.

**Comment by gsantner** [comment]
> MIUI

I wanted to respond "das erklärt alles" but it does not. However it has lots of bloat and is quite distant to "normal" aosp android. I have LineageOS on it. But MIUI may be really relevant, I haven't tried Markor on a device with MIUI.

The only thing that really could tell that, is to start adb and see if you get some error/crash output in logs, and share it with me.
