### ISSUE TITLE
performance improvement discussion

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#963]
@Groxx from `#95  https://github.com/gsantner/markor/issues/95#issuecomment-636319570`

I decided to see if I could speed up the file open process since it lags pretty hard at the moment, and there are two obvious causes from profiling:

1. When you first open a file, it's parsed 2x immediately.  Once for editing, once for viewing I'm guessing?  I haven't looked closely enough yet to be certain.
![Screenshot (21)](https://user-images.githubusercontent.com/77197/83327059-eb1d1080-a22d-11ea-9c06-fe9bee2e3575.png)

2. flexmark is re-compiling all its core regexes every time the file is parsed... because it has no way to reuse them.  And [many of them could be static but are not](https://github.com/vsch/flexmark-java/blob/master/flexmark/src/main/java/com/vladsch/flexmark/ast/util/Parsing.java):
![Screenshot (19)](https://user-images.githubusercontent.com/77197/83327123-7dbdaf80-a22e-11ea-886f-39d35332e3ce.png)

---

1 seems fairly achievable, unless I'm missing something obvious?  It just needs to prep the "other" fragment in the background when the activity starts up.  Even the simple "just block the main thread until it's ready if they switch back too fast" strategy would be no slower than it is now.
I can see if I can manage that this weekend, but we'll see how my schedule turns out :)

2 obviously depends a bit on what your settings / extended features are, but given that those parsers are actually a *majority* of the time spent opening my files, and are heavily cacheable, it seems like there's a *lot* of opportunity for speedup.  Like, reducing all app rendering times by 1/2 or more.
Unfortunately I think that would require changing flexmark and any extensions that are in use, and I'm not sure how feasible that is (aside from obviously-static regex compilation).  DocumentParser seems almost intentionally not-reusable, and it has been that way for about 4 years :|

**Comment by gsantner** [comment]
The "double parse" happens due, when activity/fragment starts, the textfield is empty. The second comes then when file content got read and set to textfield. However for the first, there is a `if() return`, so basically in that case nothing should really be executed


flexmark: I tried various but it's the best I could find with the best compatibility. 

However I don't feel theres an bigger issue with Flexmark. Main issues are:

* File reading synchronously
* Highlighting based on regexes applying to the whole file (i.e. apply regex to 1 MB fulltext if it is' 1MB of text)
* Low-end devices (or even high end depending on filesize) have issues loading bigger files as a whole into memory. And even more twice due it's present as string/byte[] after loading AND internally in the textedit.
* Saving data at activity is limited to what I remember about 400kb of data. (for rotation, instance state etc)

**Comment by Groxx** [comment]
Seems like markdown should *often* be friendly to chunked parsing (context resets between paragraphs and whatnot)... but yeah, I'm not aware of any libs that support that.  Not that I've really looked though.  And it'd depend on how they wrote the file, e.g. a single huge list would probably be a pain, among more complex cases.

Do you have any interest in changing libraries, or relatively happy with flexmark? I imagine file compatibility is pretty high on the priority list, and it sounds fairly good there.

**Comment by gsantner** [comment]
Markor is by far not only Markdown, so it would need support for all pieces for "chunked parsing/highlighting". And I don't think this will ever happen.

Do you have any interest in changing libraries, or relatively happy with flexmark? To be honest I am happy with it and not plan to change. As said the performance issue is not really the markdown converter (as it is only used for _view mode_) but other things

**Comment by harshad1** [comment]
vim / neovim also use regex for syntax parsing. It may prove useful to study how they handle performance issues.

**Comment by gsantner** [comment]
jup, but the "place whole file contents in string AND in edittext internally" remains the main reason for error ("OutOfMemoryError", "ActivityTransactionError")

**Comment by Groxx** [comment]
I did set up a pull request in flexmark for this: https://github.com/vsch/flexmark-java/pull/413
But we'll see where it goes.

**Comment by pfalcon** [comment]
> speed up the file open process since it lags pretty hard at the moment

Glad that I found a ticket dedicated to performance issues. I'd like to +1 that they exist - with "default view mode", from press on an .md file in directory viewer to opening of the file, it take ~0.1-0.3s, i.e. quite a noticeable lag (Markor 2.3.2 from F-Droid). The same lag is when following a link from one .md file to another. My files are minuscule - 100-200 bytes.

(Doing feasibility study for using Markor primary as a viewer for "notebooks" of Markdown files, with occasional editing. And yeah, currently such usage is not comfortable.)

So, are there any further updates? @Groxx' patch was merged, does Markor uses the new flexmark version now?

**Comment by gsantner** [comment]
markor currently uses the highest flexmark version that works with the android sdk on the currently configured minSdk.

**Comment by gsantner** [comment]
If somebody wants to improve something, please just open PR, and/or start discussion here.  
I'm closing this as there no immediate todo, but it's open for comment still.

**Comment by keithfancher** [comment]
Hi, I'm not sure if this thread is a good place to bring this up, but: I've noticed that Markor is quite slow to process/highlight even _very_ small files on startup. (I'm referring to "edit" mode here, by the way. And just regular markdown/todo.txt highlighting, not code or anything like that.)

This is especially jarring with `todo.txt` files, since the formatting changes the position of the text on the screen. But it occurs in all file types (that I've used so far).

The behavior I'm seeing:

- I open a file (that isn't already in memory) in edit mode
- The file loads un-highlighted/un-formatted
- There is a delay, often between 0.5 and 1 second
- The formatting/highlighting is applied

As I mentioned, this occurs even with very small files -- say, a (markdown) checklist with two items in it.

I'm using Markor `2.10.6 (142)` on a Pixel 6, Android 13. I've tried with and without "dynamic highlighting" enabled, same result. My files are in `storage/emulated/0/`, directly on my phone's internal storage, no SD card, if that matters.

I've searched through other issues and discussions on github and this one is the closest I've found to being relevant. Happy to open a new issue if that's preferred, though.

**Comment by harshad1** [comment]
You can control the highlighting delay per format under that format in settings. The default for todo.txt is very high (800ms iirc). Drop it to ~200ms or less and you will see a much better experience.

We should probably reduce the defaults - I spent a considerable amount of time speeding up the highlighting this year, but we never reduced the defaults.

**Comment by keithfancher** [comment]
> You can control the highlighting delay per format under that format in settings. The default for todo.txt is very high (800ms iirc). Drop it to ~200ms or less and you will see a much better experience.

Ah, cool, I've never come across this setting. Is it hidden or something? I'm _fairly_ certain I've searched through every setting in the menu.

There's a "syntax highlighting" section in my "format -> todo.txt" options, but the section is empty. I also don't see it in "edit mode" or elsewhere...

**Comment by harshad1** [comment]
Hmmm. There is an option in general settings called 'experimental features'. It may be hidden by that.

**Comment by keithfancher** [comment]
> Hmmm. There is an option in general settings called 'experimental features'. It may be hidden by that.

Yup, that was it! Thank you!

Oh, awesome, I can also change the number of spaces in a "tab" with this enabled. I was looking/hoping for that option as well.

If these features are "experimental"... does that mean they're likely to go away in the future? Or is it just a trial ground for up-and-coming features?

In any case, thanks again! :+1: :tada:

**Comment by harshad1** [comment]
They've been in there for a long time and I don't think they will go away. We should probably clean them up and perhaps remove the 'experimental' switch and have them be always visible.

Note that the tab width option controls how wide an actual tab character appears. To control the size of an an indent (i.e. how many spaces are inserted) long press the indent action (this setting is remembered per file).
