### ISSUE TITLE
Feature Request: allow to choose default font in view mode 

### ISSUE THREAD

**Issue by andrea993** [gsantner/markor#965]
I use the app to write simple notes and I would not like to edit the CSS. I personally doesn't like a lot the default view mode font. It will be pretty if you add an option to choose the default font (like the option which is in edit mode).

Regards,
A993

**Comment by gsantner** [comment]
Font of edit mode is also used a view mode. I thought about moving but kept it there for now.

I don't see the need of two separate settings for font, just makes it complicated to the user. And for those who **really** want a different font then the overall font there is CSS as you already discovered.

**Comment by andrea993** [comment]
then I should have an issue. I've different fonts in view and edit mode
