### ISSUE TITLE
creating new files in the app often not works

### ISSUE THREAD

**Issue by aisbergde** [gsantner/markor#966]
often I can't create new files clicking on the + button in the file section. After restarting the app I create new files again. This happens on both devices: Pocophone F1 with Android 10 and Tablet with Android 7

**Comment by gsantner** [comment]
I guess thats duplicate with your #962 , so seemingly theres something wrong with FS for you at Markor. Btw my daily device is poco f1 too (and don't have that issue)

**Comment by aisbergde** [comment]
do you also have the MIUI Global 11.0.8.0?

maybe some missing permissions or other settings which remove some rights from Markor if it "sleeps"? I don't care much about  the tablet. And I can also quickly restart the app. But it really looks like some background process destroyes something. I am afraid that this is not relates to Markor but something different.

**Comment by gsantner** [comment]
> MIUI

I wanted to respond "das erklärt alles" but it does not. However it has lots of bloat and is quite distant to "normal" aosp android. I have LineageOS on it. But MIUI may be really relevant, I haven't tried Markor on a device with MIUI.

The only thing that really could tell that, is to start adb and see if you get some error/crash output in logs, and share it with me.
