### ISSUE TITLE
file browser / view mode: Link to folders

### ISSUE THREAD

**Issue by virtos** [gsantner/markor#967]
Should we display a Markor's file browser when called by the link? Other programs like Epsilon Notes support it and it is very convenient.

Examples: 
```
[contents of the folder test](test/)
[contents of the current folder](./)
[contents of the parent folder](../)
```
Currently following these links opens a system share dialog, which is strange.

_Note: there was a suggestion to [open an index file](https://github.com/gsantner/markor/issues/530) for folder links, it will also allow navigation but will require manual update of index.md for every folder._

**Comment by gsantner** [comment]
File browser/ mainactivity currently not supports folderpath arguments but thats something that can be added.

**Comment by virtos** [comment]
I am not an android developer. Is this a good place to start?

**Comment by gsantner** [comment]
When you want to get something to work for your own benefit, it usually is always a good place to start.

**Comment by gsantner** [comment]
@virtos Yes it is :D

**Comment by sak96** [comment]
## Markor Integration

Markor Fix for folder links to open index.html.

1. Settings
2. View Mode
3. Inject -> body

```html
<script>
  window.onload = function() {
    Array.from(
      document.getElementsByTagName('a')
    ).forEach(
        (a) => {
          if (a.href.endsWith('/')) {
            a.href+='index'
          }
        }
    )
  }
</script>
```
