### ISSUE TITLE
[DE] Improve wording at "Insert picture"

### ISSUE THREAD

**Issue by aisbergde** [gsantner/markor#968]
Wenn man eine Bilddatei einfügen will, kommt ein erklärender Text und unten gibt es 3 Auswahl-Möglichkeiten.
Ich frage mich jedes Mal, was wohl die Bedeutung der 3 Knöpfe sein könnte, insbesondere Notizbuch und aktuelle.

Vielleicht ist das in der Englischen Version besser erklärt, in der deutschen Version ist es unklar formuliert. Ich schlage vor, die Verständlichkeit zu erhöhen.

**Comment by aisbergde** [comment]
Ich stolpere immer wieder und immer noch darüber, wenn ich die Funktion eine Weile nicht nicht verwende. Es ist völlig unverständlich, was "Notizbuch" machen soll und was "Aktuelle".

Ich kann auch keinen Unterschied feststellen, wenn ich es teste: beide Male wird die einzufügende Datei in den aktuellen Ordner kopiert. Mir ist also der Sinn und Zweck dieser Auswahlmöglichkeiten (bis auf Abbrechen) völlig unklar.

Da ich auch nicht finden kann, wie man einen relativen Speicherort definieren kann, werde ich da mal nach einem bestehenden Issue suchen oder einen erstellen.

**Comment by aisbergde** [comment]
Ich glaube, aus einem anderen Issue heraus den Unterschied zu verstehen: das eine ist der Notizbuch-**Ordner** und das andere der aktuelle **Ordner**. Und da bei mir der Notizbuch-Ordner der aktuelle Ordner war, sehe ich keinen Unterschied.

Vielleicht den deutschen Text leicht anpassen:

Die Datei ist nicht im aktuellen Ordner vorhanden. Möchtest du sie in den Notizbuch-Ordner oder in den aktuellen Ordner kopieren? Dies überschreibt eine vorhandene Datei gleichen Namens.

Und dann der Name des 3. Knopfes nicht "aktuelle" sondern "aktuell"

Und noch komfortabler wird es, wenn geprüft wird, ob der aktuelle Ordner und der Notizbuch-Ordner übereinstimmen und dann diese Fallunterscheidung gar nicht erst angeboten wird, sondern nur Speichern oder Abbrechen (mit entsprechend geändertem Text).

**Comment by gsantner** [comment]
Es kommt vielleicht in der Zukunft eine scrollbare liste mit auswahloptionen, aktueller ordner, notizbuch ordner PLUS alle favourisierten Ordner. Sollte alles abdecken.

**Comment by gsantner** [comment]
--> #925
