### ISSUE TITLE
selected text: quick action to copy or move to existing or new note

### ISSUE THREAD

**Issue by aisbergde** [gsantner/markor#972]
I want to suggest an easy way to move content from one note into a new note.

There could be a new quick edit botton to move or copy the current selected text into a new note. Or to append to an existing note.

When pressing the button I should be able to
- choice between move to or copy to
- append to existing note or create a new note

For example often I write something in Quicknote because it is easy to access, but later I want to move it in a separate note. Sometimes I also edit a note and think a separate file would be better.

**Comment by gsantner** [comment]
I would rather stay away from Android "quick actions popup". It often not shows up and every OS/phone vendor brews his own soup. (Especially looking at MIUI).

**Comment by aisbergde** [comment]
any way to copy or move selected text to an existing not or to create a new note would be fine.
For example currently you have implemented the "add attachment" as link where you have a file picker. I suggest something similar: the user can also use the file picker and he can use an existing note or create a new one. The only difference is that the file is not used as source for a link but as target to store content in this file.

**Comment by harshad1** [comment]
On my phone, I can select text (in any application, including Markor) and share this text into Markor. The share into markor UI lets me append this text to any file.

**Comment by aisbergde** [comment]
> On my phone, I can select text (in any application, including Markor) and share this text into Markor. The share into markor UI lets me append this text to any file.

You are right, copy text into a new file (and maybe also extend to existing, I see this entry) works fine via sharing. Thanks for advise.

Maybe this is enough and an additional move is not required? Copy works like standard share, move can't work like a standard share and a different implementation would make it more complicated.

Something like "restore previous selection" would be fine to switch back to the first file, select the copied content and then delete. But I don't know how complicated this is would be to implement.

**Comment by gsantner** [comment]
> Something like "restore previous selection" would be fine to switch back to the first file, select the copied content and then delete. But I don't know how complicated this is would be to implement.

Note that it's kind of a special use case. Usually you don't want that to happen, as you open editor you want to start typing...and then you overwrite something because last time you forgot to deselect it

**Comment by gsantner** [comment]
I'm closing as I feel like theres something usable already there.
