### ISSUE TITLE
Todo.txt should be highlighted/formatted in 'view' mode

### ISSUE THREAD

**Issue by harshad1** [gsantner/markor#980]
Currently, todo.txt format files are displayed as plain text in 'view' mode. Instead, they should be displayed as with the correct highlighting for dates , contexts, projects, priorities etc.

**Comment by gsantner** [comment]
#859

**Comment by opusforlife2** [comment]
@gsantner I read that issue, and this is not a duplicate of that. That issue talks about organisational functions like sorting and grouping, which would take additional coding to achieve. This issue is simply about colour coding in View mode, which _already_ exists in Edit mode.

**Comment by gsantner** [comment]
edit mode and view mode are completely seperate, its not possible to use the same.

the said issue is about doing a proper "fancy" view mode implementation, this includes but is not limited to syntax highlithing, colors and optional grouping/filtering etc.

Hence yes, this is duplicate.
