### ISSUE TITLE
Feature request: quickly toggle between light and dark theme.

### ISSUE THREAD

**Issue by ksz16** [gsantner/markor#981]
From the editor, without the necessity to open settings.
With a gesture or button, doesn't matter.

**Comment by gsantner** [comment]
Hey,

I don't wanna creep the toolbars with every kind of stuff for special use cases for where thers already settings.

**Comment by ksz16** [comment]
OK, I understand. So what about the gesture?
Or the possibility of custom gestures to which the user can assign behaviour.

**Comment by gsantner** [comment]
Same, I don't really see the need to make it more complicated than it is. By the way there is a "Auto" theme which automatically switches to dark mode after-work :D. And...not everything needs an option, most users are already overwhelmed by whats there in markor

**Comment by ksz16** [comment]
I am aware of "Auto" mode, but unfortunately is not applicable in my scenario of use.
Of course I understand - your soft, your rules. Anyway I still think Markor is a great app :-).

Maybe I'll try to get it via Tasker. So, my last question: how can I trigger this behavior programmatically? I'd appreciate any hint.

**Comment by gsantner** [comment]
I'm not a user of tasker, but if it runs as root you could swap `>light<` with `>dark<` in preference file

**Comment by ksz16** [comment]
Yes, this may be one of the options (editing .../shared_prefs/app.xml file).
But I rather meant to use activity manager (am <command>). Is it possible?

**Comment by gsantner** [comment]
Jup than light/dark swapping is  option.

am not as is without changes.

**Comment by ksz16** [comment]
OK. Thanks for your help.

**Comment by ksz16** [comment]
I noticed that in Android 10 some apps automatically change color depending on the main theme.
The current auto mode in Markor is based on the daytime (if I understand correctly). Auto mode based on the main theme would solve this problem.

And lastly, it would be nice to have a dark AMOLED theme too.

**Comment by gsantner** [comment]
A third theme is not planned.

Auto theme is based on local daytime yes, as that works with any Android version out therr. This newly introduced system dark/light is not checked atm.

**Comment by ksz16** [comment]
Ok, thanks.

**Comment by gsantner** [comment]
Though "system day/night theme" might be added in future
