### ISSUE TITLE
 Community discussion - PaulEmm43

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#985]
![grafik](https://user-images.githubusercontent.com/6735650/85691659-3a871d00-b6c4-11ea-8ecc-24805ce67c27.png)

![grafik](https://user-images.githubusercontent.com/6735650/85691776-54286480-b6c4-11ea-835f-0c5c45fb8f77.png)

![grafik](https://user-images.githubusercontent.com/6735650/85691805-5a1e4580-b6c4-11ea-868a-5ba26f27b53e.png)

![grafik](https://user-images.githubusercontent.com/6735650/85691919-77531400-b6c4-11ea-8935-89874c4b34d2.png)

![grafik](https://user-images.githubusercontent.com/6735650/85691949-7de18b80-b6c4-11ea-8f8c-91d3e7a06aaf.png)

**Comment by gsantner** [comment]
@PaulEmm43
I've asked aisbergde actually to move discussion, not you. Still, I thought makes sense to seperate yours too. So did.

If you have something to comment just leave it here here. Also, if you have images to send, either visit this page in browser [here](https://github.com/gsantner/markor/issues/985) and use the upload button .... OR send it via mail to [me](https://gsantner.net/page/about.html)

**Comment by PaulEmm43** [comment]
Hi Gregor

Apologies for the delay in getting back to you. I had a quick look for the
upload button you spoke of at https://github.com/gsantner/markor/issues/985
but though I could see the thread didn't see that damn button.

I've attached the screen shot, and I hope it helps. I suspect the problem
may in part be my ancient Android (5.1) - it is actually an upgrade from
4.4 (KitKat). But most apps seem to be able to find my SD card including
another editor I like (QuickEdit).

However I'm really impressed by Markor - the more I see the better I like
it. For real non experts like me it would be helpful to make it easier to
find the Reference.md file - I came across it by accident while learning
how to create various doc types and it's really helpful.


Regards
Paul Milton

**Comment by gsantner** [comment]
![Screenshot_2020-06-23-02-22-13](https://user-images.githubusercontent.com/6735650/85942389-72869e00-b918-11ea-96e5-9b74bbb0c9f2.png)

**Comment by ChiefMikeK** [comment]
## Fyi button is sort of hidden :neckbeard: using firefox Android tablet 
![attachments](https://user-images.githubusercontent.com/20070053/86242356-2f0d8780-bbd7-11ea-8052-8be7fb8c0ff5.png)

**Comment by gsantner** [comment]
![grafik](https://user-images.githubusercontent.com/6735650/88457652-b9b07200-ce77-11ea-831b-86b83061b58a.png)

**Comment by gsantner** [comment]
I'm sorry that there is not much news on this, but as far I can tell for most devices it works fine..still there are some where it makes problems. On the device(s) I can test & debug on, the access to sdcard worked fine.
