### ISSUE TITLE
bug: "Formated" data from clipboard is shown in "plain text" format.

### ISSUE THREAD

**Issue by mmm4m5m** [gsantner/markor#992]
1. Select unsorted list item from "markdown" view - full line! (not part, not one word)
2. Copy and paste inside "plain text" editor

**Comment by gsantner** [comment]
Please add a GIF or video

**Comment by mmm4m5m** [comment]
1. Select full line (not part, not one word):
![image](https://user-images.githubusercontent.com/995706/85945524-171fd480-b947-11ea-968e-a65ea14d55ca.png)

2. Copy and paste in "plain text" editor:
![image](https://user-images.githubusercontent.com/995706/85945516-02dbd780-b947-11ea-8e82-3f2e5c155649.png)

You can see there one small dot which you can not remove.
You need to close and reopen the file.

**Comment by gsantner** [comment]
I remember to have been able to reproduce this issue. But cannot anymore on git-master. So seems to be fixed.

So please wait till next update is out, and report back whether issue still is present.

**Comment by mmm4m5m** [comment]
There is 'paste as plain text'. I think it is new and works. Thanks!
(With regular 'paste' the same happens as described above.)
