### ISSUE TITLE
Question regarding newfile + overwrite

### ISSUE THREAD

**Issue by subjekcintasemuacg** [gsantner/markor#994]
In newest update, making file/title with same name as existing file automatically DELETED existing file contents! Isn't it supposed to "direct" you to your existing file???????????

Uh this is my first time making issue I don't know what to write.....

#### General information

* **App version:** 
* **System:**

**Comment by gsantner** [comment]
I can reproduce on current git version that it's overwriting.

However not sure if it's better to 

* "remove no overwrite notice" 
* OR "fix no overwrite on existing file".

What you think?

**Comment by subjekcintasemuacg** [comment]
Uh I don't quite understand. And I'm not really sure about the git thing.
Is it possible to just do it like last time??

I think it's really awesome before.
If there's a "notice" I think it's too cluttering. And "redirect" to the existing file is just perfect.

**Comment by gsantner** [comment]
OK so option 2 is more the one that is wanted.

**Comment by subjekcintasemuacg** [comment]
Ok. Thank you.
Cannot wait for next update.

**Comment by harshad1** [comment]
@gsantner My understanding is that the desired behavior is 'if the file already exists, then don't re-create it, instead just show it'

**Comment by gsantner** [comment]
Jup that is right

**Comment by Russe** [comment]
Uhh, just lost a file with this behaviour.
I agree, a note is not a good idea, because it can be missed or misinterpreted.
So your decision to show the already existing file instead of recreating it is fine for me.

**Comment by gsantner** [comment]
reopened

@harshad1 
I found in latest release that it's overwriting still/again

**Comment by harshad1** [comment]
I'm not able to reproduce this. Could you give me the exact steps to reproduce?

**Comment by gsantner** [comment]
Create file a.md, go back to file browser, create new file again with a.md (empty file template).And then whatever was in a.md got emptied out, empty file shows up

**Comment by harshad1** [comment]
I followed those steps with a fresh install from F-Droid and the file was not overwritten.

What software do you use to record your phone, and how do you upload the recordings here?

**Comment by gsantner** [comment]
I use  normal screenrecord from OS and ffmpeg to GIF. Theres also "Video transcoder" on fdroid which can do the same.


![Screenshot_20200803-053700_Markor](https://user-images.githubusercontent.com/6735650/89143608-7b881200-d54b-11ea-9139-1e6b7d1d241b.png)


![ScreenRecord-2020-08-03-05-29-56](https://user-images.githubusercontent.com/6735650/89144304-9a87a380-d54d-11ea-836c-3649c248ae79.gif)

**Comment by harshad1** [comment]
Markor will not save files with length < 5. We discussed this in https://github.com/gsantner/markor/pull/998

**Comment by gsantner** [comment]
Alright, bad case for showing :D. GG

Gonna check tomorrow again if finding still issue

**Comment by harshad1** [comment]
@gsantner @subjekcintasemuacg Has this be reproduced after the latest release? Can this be closed?

**Comment by subjekcintasemuacg** [comment]
is there a new release???
