### ISSUE TITLE
Can't type in square brackets

### ISSUE THREAD

**Issue by BobbyS38** [gsantner/markor#995]
Hi. I am using Zim Wiki for the first time. I wanted to place in sqaure brackets [[ ]] but there happens nothing when I hold CTRL + ALT and press on 8 or 9 for the sqaure brackets. I am using the german keyboard. When I change to US Keyboard I can type in square brackets by pressing the keys for them. How can I fix this issue? It is really annoying to change to US Keyboad everytime I want to type in square brackets. Also I can't use any symbol which can only be used by holding CTRL + ALT like | { } ~ etc.

**Comment by gsantner** [comment]
Hi, I'm using german (virtual) keyboard as well and not have a issue with any character. Not sure what CTRL+ALT+8 means, but "AltGR + 8 / AltGR + 9" is [ / ] to my knowledge.

I also don't have such a special hardware keyboard where I could help you to debug. So if you need help on this, you probably need to debug on your own as I don't really think anybody else can reproduce this.

**Comment by BobbyS38** [comment]
Ok thats interesseting. Normally you can use CTRL+ALT to use the third character which is on one key (I dont know how to describe it). For some reason it doesn't work in Zim Wiki. But Alt Gr + 8 or 9 worked for me
