### ISSUE TITLE
New notes save to "Notes" folder within currently viewing folder

### ISSUE THREAD

**Issue by Staikken** [gsantner/markor#996]
#### General information

* **App version:** v2.2.10 (113)
* **System:** Android version 8.0.0

#### Description
When I press the "+" button from a folder it creates a new note within a new "Notes" folder (Even if the current folder is my notebook and also named "Notes"). I tend to work inside my most recent notes folder so I get recursive notes folders. 
Opening and editing a note also saves it down a "Notes" level causing duplicate files.
Is "../Notes/foo.md" hard coded into the save method?

**Comment by gsantner** [comment]
I'm not aware of anything "Notes" in project at all for filepaths.

**Comment by Staikken** [comment]
It unfortunately makes the app unusable for me. "Notes" was what I named the notebook folder on my external storage. Somehow the path construction is adding it into the save path again.

**Comment by gsantner** [comment]
duplicate #603

**Comment by gsantner** [comment]
See #603 comment
